### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by Grimdoc** [CorsixTH/CorsixTH#1000]
Seems like I lost push permission here.
So please add this Norwegian language update to the CorsixTH\Lua\languages\ directory.
See attached file (rename it from *.txt to *.lua before adding).

[norwegian.txt](https://github.com/CorsixTH/CorsixTH/files/178304/norwegian.txt)

**Comment by TheCycoONE** [comment]
Everyone can make a pull request, so I'm not sure what's happening with your situation.

**Comment by TheCycoONE** [comment]
Looking at your public repository Grimdoc/CorsixTH the last thing I see is a patch-3 branch with prompt changes for 0.50.

**Comment by Alberth289346** [comment]
To be a bit more verbose, nobody pushes directly to the CorsixTH repository normally, everything is done by issueing a Pull Request from your own repository copy. One of the other devs will then do a review, and if all is fine (which is usually the case with language changes), he will merge it into the main CorsixTH repository.
