### ISSUE TITLE
Mouse irretrivably freezing when placing objects on new install, in first game.

### ISSUE THREAD

**Issue by BigJDJD** [CorsixTH/CorsixTH#1001]
Not even half a minute into my first game and the cursor freezes never to return again. When placing objects in a room the cursor freezes. Either I am unable to click to place the second object in my purchased inventory, or it occurs after placing the object and I scroll over the object.  

Some objects I have not had problems with (for instance chairs in GPs office, benches, radiators and reception desks) others always cause it to freeze, for instance GP filing cabinet. 

I assume I have some sort of corrupted install, or dodgy pathway for the game to access my cursor, but I haven't a clue. 
#### Steps to Reproduce:

Would happily provide information if told how, though unable to provide saved game as I never get more than 30 seconds in. 
#### Expected Behavior:

Expect to maintain control over the cursor and continue playing. Inevitable have to close the window. NB cursor remains active and functional outside the CorsixTH window.
#### System Information

**CorsixTH Version: 0.50 
**Operating System:** Ubuntu 14.04 LTS

**Theme Hospital Version:** GOG.com 

Always two errors in quick succession, both similar: 

```
Will not check for updates since this is the Trunk version.
starting game with difficulty full
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The motion handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/game_ui.lua:355: attempt to index local 'entity' (a boolean value)
stack traceback:
    ./Lua/game_ui.lua:355: in function 'onCursorWorldPositionChange'
    ./Lua/game_ui.lua:433: in function <./Lua/game_ui.lua:425>
    (tail call): ?
    (tail call): ?
    ./Lua/app.lua:880: in function <./Lua/app.lua:875>

Warning: No event handler for motion
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/game_ui.lua:407: attempt to index local 'entity' (a boolean value)
stack traceback:
    ./Lua/game_ui.lua:407: in function 'onCursorWorldPositionChange'
    ./Lua/game_ui.lua:675: in function 'onTick'
    ./Lua/app.lua:981: in function <./Lua/app.lua:976>
    (tail call): ?
    ./Lua/app.lua:880: in function <./Lua/app.lua:875>

Warning: No event handler for timer
```
### Additional Info

![image](https://cloud.githubusercontent.com/assets/17910277/13855232/3da45e48-ec67-11e5-9df2-3b58095c2f6a.png)

**Comment by mugmuggy** [comment]
This was fixed with #1007
