### ISSUE TITLE
Dynamic info showing incorrect information

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#101]
I first noticed this with #99 then again tonight I saw one patient with queuing for blood machine when she was on her way to the decontamination clinic and then this one who is fed  up and leaving and it says she is queuing for GP office
![7](https://f.cloud.github.com/assets/4965487/1758229/3729b2ba-668c-11e3-852e-5d6da0dc5cef.png)
I am testing epidemics, so it may be related to that branch only, but as I have also seen this in the master recently I will assume for now this is a general issue.

**Comment by bobcanthelpyou** [comment]
@MarkL1961 are the dynamic info are still incorrect sometimes?

**Comment by mugmuggy** [comment]
#1173 is the same issue, where there is more discussion
