### ISSUE TITLE
Firing staff does not remove them from payroll and they keep costing money

### ISSUE THREAD

**Issue by voodoo070** [CorsixTH/CorsixTH#1031]
#### Describe the issue

Firing staff does not remove them from payroll and they keep costing money

#### Steps to Reproduce
1. Hire doctor

2. Fire doctor

3. Check expense log after a month ends

#### Expected Behavior

Staff stop costing money when you fire them

#### System Information
CorsixTH Version: 0.60 beta 1

Operating System: Windows 7

### Additional Info

http://i.imgur.com/pJ0obdx.jpg

**Comment by MarkL1961** [comment]
What shows the following month?  There is an initial fee when you first hire, then the month cost and a cost if you fire.  Your statement looks correct to me, but would be wrong if you were charged again in Feb

**Comment by voodoo070** [comment]
http://i.imgur.com/cCUqm1T.jpg

you just keep paying for him
he also remains on the staff list but since he walked off the level thats just where he walked off

**Comment by MarkL1961** [comment]
That is unexpected behaviour then

**Comment by Alberth289346** [comment]
commit b54c5a832baa5815511ab7f66f78351b0c4c338c gets the blame by git bisect.

**Comment by sadger** [comment]
Think found the cause of this one with @TheCycoONE's help, the patients and staff were not being removed from the lists in Hospital because the calls to setHospital were removed entirely. Will put a PR in soon fixing this.
