### ISSUE TITLE
0.60 Beta 1 OS X build crashes on launch

### ISSUE THREAD

**Issue by clobber** [CorsixTH/CorsixTH#1035]
The 0.60 Beta 1 build for OS X [provided here](https://github.com/CorsixTH/CorsixTH/releases/tag/v0.60-beta1) crashes on launch.

Crash log: https://gist.github.com/anonymous/b96859a2959c0f5b3d561f7bcdc2eab1

Using OS X 10.11.4 with Theme Hospital CD version.

cc @tobylane since it looks like you are working on the OS X build configuration.

**Comment by JamesBream** [comment]
Absolutely no issue running the GOG version here on Mac OS X 10.11.4.

**Comment by joewestcott** [comment]
I have the same issue with 0.60B1 crashing on startup, barely making the dock. It does produce a .crash file in ~/Library/Logs/DiagnosticReports/, I can attach if desired.

**Comment by clobber** [comment]
@joewestcott Please upload it here (https://gist.github.com) and share in this issue.

I just checked the build on another machine and interestingly enough, I was able to launch it. There seems to be a problem with one of the frameworks (maybe Lua?) and certain hardware configs, so the more details the better.

**Comment by joewestcott** [comment]
On further inspection it does seem to be related to my ~/.config/CorsixTH directory, as renaming it lets me get to the find the HOSP screen. On selecting my HOSP (on disk version) it crashes straight after.

**Comment by clobber** [comment]
Okay, please post the crash log anyway! I was not able to get to the selection screen even after removing my config directory.

**Comment by joewestcott** [comment]
@clobber Sure, hope it's useful. Let me know if you need any more details. https://gist.github.com/joewestcott/f6afd79aeb19152a315e5c58b417c2cd

**Comment by clobber** [comment]
@joewestcott Probably details on your Mac would be good (model, cpu, etc) since that only appears in the log if you click the "Report..." button when the crash dialog comes up. Otherwise, the logs sitting in ~/Library/Logs/DiagnosticReports/ do not contain that extra info.

**Comment by joewestcott** [comment]
Do you think it's anything to do with the HOSP version? James' had no issue using the GOG distribution and you and I are using files from the disk. Plus the fact the game crashes for me the instant I choose the folder. Not sure if you picked up on that :) I'm using a late '13 MP.

**Comment by joewestcott** [comment]
Tried it on another mac (same HOSP folder) and I can get one stage further, this time to the circle with the Doctors/Nurses in before it crashes. He's the crashlog (with extra mac detail at the end) https://gist.github.com/joewestcott/f6afd79aeb19152a315e5c58b417c2cd

**Comment by clobber** [comment]
Doubt it. I can't even get to the point of game data selection screen, so that appears unrelated.

**Comment by TheCycoONE** [comment]
I believe this is because tobylane compiled for his system instead of targeting a lower common denominator. @tobylane look at http://stackoverflow.com/questions/19397973/what-is-exc-bad-instruction-sigill-why-is-it-caused and see if it helps.

**Comment by tobylane** [comment]
Clobber and James are both on 10.11, I'm on 10.10, Travis CI is on 10.9. I don't think that should matter. Clobber is on Core Duo, James and I are on i7, Joe on i5.

http://cl.ly/fi0A This build has been made following Cyco's advice. If this works I'll make another beta with this procedure. I can't find the recipes for the homebrew bottles but it's a reasonable assumption that they aren't Core Duo friendly.

**Comment by joewestcott** [comment]
No difference with that build Toby, tried on both machines. The error both times is the same: This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.
Illegal instruction: 4

**Comment by tobylane** [comment]
The deprecated part is an upstream problem. The illegal instruction is probably something that even when I compile locally it is a optimisation that isn't back compatible or safe. I can't identify the right way to be backwards compatible on CPUs, the closest thing I can see is "Enable Additional Vector Extensions" which is SSE 4.2 in these builds.

**Comment by TheCycoONE** [comment]
Well SSE 4.2 would exclude a lot of CPUs. On Linux you would be looking at the -march option.

**Comment by tobylane** [comment]
Yes, it's `-march=core2`

**Comment by TheCycoONE** [comment]
Is he on a core 2 or an original core? Might be safer just to target i586.

I'm not sure how you ensure all brew libraries are the same.

**Comment by TheCycoONE** [comment]
Never mind I see OSX 10.6 required core 2 duo so we don't support older processors anyway. Just a matter of ensuring brew and corsixth use the same and not using newer vector instructions than SSE4.

**Comment by clobber** [comment]
@tobylane That build above doesn't seem to be packaged right. Crashes with:

```
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/USER/Desktop/*/CorsixTH.app/Contents/MacOS/libavformat.dylib
  Reason: Incompatible library version: libavformat.dylib requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
```

And yeah, it's *Core 2 Duo*, not Core Duo. It'd be impossible to run on Core Duo because it's not 64-bit and unsupported on OS X since 10.7. Any package on homebrew will run on latest OS X.

**Comment by clobber** [comment]
Okay, I'm able to compile a working build doing the following via Terminal with having [Homebrew](http://brew.sh) and [Xcode Command Line Tools](https://developer.apple.com/library/ios/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-DOWNLOADING_COMMAND_LINE_TOOLS_IS_NOT_AVAILABLE_IN_XCODE_FOR_OS_X_10_9__HOW_CAN_I_INSTALL_THEM_ON_MY_MACHINE_) installed:
```
brew install cmake lua sdl2 freetype ffmpeg
brew install sdl2_mixer --with-smpeg2

luarocks-5.2 install lpeg
luarocks-5.2 install luafilesystem
luarocks-5.2 install luasocket

git clone https://github.com/CorsixTH/CorsixTH
cd <wherever my checkout folder is>

cmake .
cd CorsixTH

open CMakeLists.txt 
```
Now in CMakeLists.txt, Find & Replace all occurrences (should be 2) of the following line:
`\${TARGET_BUILD_DIR}/\${FULL_PRODUCT_NAME}`

...with a hardcoded path to your checkout folder, for example:
`/Users/YOURNAME/Downloads/CorsixTH-master/CorsixTH/CorsixTH.app`

Save the CMakeLists.txt file and close it. Now back in Terminal to compile the app and open the folder:
```
make

open .
```

There will be a newly compiled CorsixTH.app in the folder.

**Attached is a compiled build of Beta 2 to test and verify there are no issues running it:**
[CorsixTH-v0.60-beta2.zip](https://github.com/CorsixTH/CorsixTH/files/222911/CorsixTH-v0.60-beta2.zip)

**Comment by joewestcott** [comment]
I'm getting module `lfs` not found (strict.lua:66)

**Comment by TheCycoONE** [comment]
No longer relevant to 0.62.
