### ISSUE TITLE
Windows & Mac installers, but no Linux .sh?

### ISSUE THREAD

**Issue by Makitk** [CorsixTH/CorsixTH#1037]
Downloaded the Linux source, but why not make a Linux .sh available?
I do hope you would explore the possibilities for a .sh, .deb, and/or .rpm once you hit v1.0.

I can't figure your sourcebuild out, so will have to wait and hope...

**Comment by Alberth289346** [comment]
there is a debian build upstream, afaik

As for source build:
````
# download source into "cth" directory (other name is also allowed)
cd cth    # if you used a different name for download, change it here too

# build
cmake .   # <-- note the '.' parameter
make

# run
./CorsixTH/CorsixTH   # Will ask for the CD "HOSP" directory.
````

**Comment by Makitk** [comment]
@Alberth289346 
Debian stable does not have the packages that the [compile instructions](https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile) offer me to install.
I've received several dependency errors trying to get all packages installed, mainly when trying to install the LibAV packageset.

**Comment by Alberth289346** [comment]
Not a debian user, so don't know the details there.
https://launchpad.net/debian/+source/corsix-th  seems to be for 0.50 (ugh), and debain unstable

Movies are optional, you can switch them off with a -D option to cmake
````
cmake -D WITH_MOVIES:BOOL=OFF .    # <- don't forget the dot at the end
````
that should solve your libAV problems.

**Comment by emorrp1** [comment]
Hi @Makitk, `corsix-th` 0.60 is now in stretch (I will try to be quicker with future releases). I normally install it on Jessie by [enabling backports](https://wiki.debian.org/Backports#Using_the_command_line) and following the steps in [SimpleBackportCreation](https://wiki.debian.org/SimpleBackportCreation). Unfortunately official backports need a "notable userbase", which seems unlikely, so you'll need to re-follow these steps on each new release.

There's also a nice easy way to create a .deb for the Game Data files (e.g. from GOG): `game-data-packager theme-hospital setup_theme_hospital_*.exe`.

**Comment by Makitk** [comment]
@emorrp1 The stretch version depends on a lot of things that Debian stable does not have, nor wishes to install due to a bunch of broken dependencies. Is there anything you could do to make the package more stable-friendly?
I do have backports enabled, but have never found corsix-th in the list of available packages.

**Comment by Alberth289346** [comment]
Given that we depend on the data of the original game makes stuff a bit awkward, I guess. We are working on getting free graphics, but sound, music, and strings aren't being worked on afaik.

**Comment by Makitk** [comment]
I was more thinking about using libraries that exist within Debian Jessie stable rather than Debian Stretch testing.

**Comment by emorrp1** [comment]
Hi @Makitk, the only dependency not in Jessie is FFmpeg rather than libav, but it is in jessie-backports. You are right that the "simple" backporting steps I linked to was probably a bad suggestion, here's a much simpler method I've just tested on a fresh jessie install:

`sudo apt edit-sources` to ensure it contains at least these three lines (note the `-src` that will prevent actually installing anything from unstable):
```
deb http://ftp.uk.debian.org/debian jessie main
deb http://ftp.uk.debian.org/debian jessie-backports main
deb-src http://ftp.uk.debian.org/debian unstable contrib
```

```
sudo apt update
sudo apt install devscripts
sudo apt install -t jessie-backports libavdevice-dev # only ffmpeg needed from backports
sudo apt-get build-dep corsix-th # all other libraries exist in jessie
apt-get source --compile corsix-th
sudo gdebi corsix-th-data_0.60-1_all.deb
sudo gdebi corsix-th_0.60-1_amd64.deb
```

You'll note it builds cleanly in Jessie, but unfortunately as I mentioned, corsix-th itself will unlikely be in the official backports unless there's more demand.

**Comment by TheCycoONE** [comment]
Does CorsixTH not work with the version of LibAV in jessie? I wrote LibAV support in for Ubuntu some time ago, though admittedly it's not as well tested as the ffmpeg path.

**Comment by emorrp1** [comment]
@TheCycoONE I assume so, I simply haven't tested it as Debian [has switched back](https://lists.debian.org/debian-devel-announce/2015/07/msg00001.html) to ffmpeg for the next release, so the build file (and dependencies) would need to be edited to configure WITH_LIBAV=true.

**Comment by TheCycoONE** [comment]
We do not plan to offer linux builds. I will link to downstream packages on the releases page for the next version as I'm notified of their existence.

I think the other issue in this ticket about Debian dependencies was resolved?
