### ISSUE TITLE
Inside tiles not buildable when placed before the parcel

### ISSUE THREAD

**Issue by TatiGranger** [CorsixTH/CorsixTH#1044]
#### Describe the issue
I created a map on the map editor, but when I tried it in game it wouldnt let me build on it. I transfered to the outside map editor to check the flags on it and sure enough they weren't marked with the "H", I checked if every corner was closed and they were,after some tinkering I decided to remove and add again the back walls. Got my "H"s by doing so, saved, went back to the game. Couldnt build. Loaded the map again on my map editor. The "H"s were gone. After some failed attemps to fix it and a research with no results about this issue I gave up and decided to report the bug.

#### Steps to Reproduce
1. Load the .map file on map editor
2. Check the flags, no H marked
3. Remove the back wall and replace with a new one
4. Check the flag, got the H marks
5. Save the map

#### Save Game
 Folder with .map file and .level:
https://www.dropbox.com/sh/izyffd8zmfop3df/AABaG4na9sLVtw4xdjK56BZGa?dl=0 

#### Expected Behavior

6. Load it again or try in game
6.1 - if loaded again H marks are gone
6.2 - if tried in game can't build

#### System Information
**CorsixTH Version:0.50

**Operating System: Windows 8.1

**Theme Hospital Version: GOG.com

#### Gamelog.txt
No game log file
```

### Additional Info
![screenshot 2016-04-19 05 18 23](https://cloud.githubusercontent.com/assets/9095043/14632353/83dded02-05ee-11e6-9fc2-239f444b9df4.png)
![screenshot 2016-04-19 05 18 51](https://cloud.githubusercontent.com/assets/9095043/14632356/8bdbcf10-05ee-11e6-98cd-31f1e32482c8.png)
![screenshot 2016-04-19 05 19 44](https://cloud.githubusercontent.com/assets/9095043/14632366/919af64c-05ee-11e6-9f40-0259a3a1ec66.png)

**Comment by TheCycoONE** [comment]
Taking a quick look at your map it looks like you didn't assign parcel numbers to your interior. Everywhere you own initially must be "Parcel 1"

**Comment by TatiGranger** [comment]
Humm them problem is I also did before,  I wonder if that is not saving aswell now. Did you try to change and save it? Did the changes to solve this problems were still on the new saved file?

**Comment by TheCycoONE** [comment]
What map editor are you using? Your issue says 0.50 but that version has no map editor. The MapEdit program from 0.40 is discontinued. I tried editing your map in the map editor from 0.60-beta2 and it works fine:
https://www.dropbox.com/s/cq7xt56bh2tsw7m/Test002.map?dl=0 (I only bothered fixing the floor by the entrance).

It's worth noting that the new 0.60 map editor places flags based on the tile type (e.g. inside / outside / wall), and does not detect / care what is an enclosed space.

**Comment by TheCycoONE** [comment]
@voodoo-burger I drew a relatively small area of inside tile on your huge map near the door and I am able to build on the portion that I drew: https://www.dropbox.com/s/ezmt0kjuwu6x4dk/Huge%20Map.map?dl=0

Clearly I'm missing something in my testing, so as mentioned in the other issue, I'd like to know exactly what steps you took to make the map (in order)

**Comment by MarkL1961** [comment]
the H is to do with path finding or it was with the external editor.
I have not used the new editor, so I will have a bash with it tonight to see what problems if any I can find

**Comment by TheCycoONE** [comment]
Not anymore, we base the flags just on the tile type now rather than trying to determine enclosed areas. It should be much simpler and more foolproof, but based on these bug reports there is something we didn't account for.

**Comment by voodoo-burger** [comment]
I am also able to build on the portion of the floor you re-drew. It seems the issue is that you need to place the parcel first, and then the floor. The other way around doesn't work.

**Comment by MarkL1961** [comment]
I noticed that there are two new things that were not needed before.
Camera position was where you were looking when you saved and now is something you select and a dropdown for the number of players.   I did both and could build as expected, perhaps this was not done above?
I would attempt creating another map to try out this theory, but I still find the map editor slow and judery to use.  For me it does not like dragging and freezes and then paints objects in the wrong place.  Annoying as I could not find an undo button.  This was window mode, I'll perhaps try full screen to see if that is better

**Comment by MarkL1961** [comment]
Something else I have just noticed is that the map is saved near your saves and the level file is in the level file where corsixth is run from.  Both folders are levels.
Previously you placed both parts for a map in the same folder.
I noticed this as I created another test map and placed it in the level folder with the game and then when I tried to play it it was the old test map.  I then copied my new map to where the saves and there is no level file in that location and I got to load my newer map.
So it could be like me you are making changes and loading the wrong map without realising it?

**Comment by TheCycoONE** [comment]
I have confirmed, a floor built on a tile that has never had a parcel does not get flagged buildable even after the parcel is added. Oddly it seems that setting the parcel back to 0 and resetting the tile to grass does not reproduce.

**Comment by MarkL1961** [comment]
There are my locations
C:\CorsixTH 0.60\Levels
C:\Users\Mark\AppData\Roaming\CorsixTH\Levels

**Comment by TheCycoONE** [comment]
@MarkL1961 both folders are used for both, you can store your .level files and .map files in either folder. The one in Roaming\CorsixTH\Levels overrides the other one. This is by design because users don't necessarily have write access to where CorsixTH is installed, especially on Linux.

**Comment by TheCycoONE** [comment]
I'd like to keep this bug on topic though. It's clear that placing an inside floor tile before placing the parcel causes a problem with the 0.60 map editor.

**Comment by MarkL1961** [comment]
Yes but  I placed the floor after the walls and then the parcel and I had the buildable flag.  Parcel was 0 as default and I changed to 1.

**Comment by MarkL1961** [comment]
@TheCycoONE 
I don't see how this is off topic if we are trying to discover what causes an error sometimes and not others. Both I and @voodoo-burger placed the parcel after the floor he can't build and I can!
Therefore explore other options in case we are missing something.  
The thing with the level folders may be relevant if like me you end up with two maps with the same name that are in different locations and any changes don't seem to take affect (because you are not aware that the older one is overriding the newer one)

**Comment by TheCycoONE** [comment]
Oh, I didn't see where you said you built inside tiles before parcels and could build on it (on a new section of map). I was able to reproduce with the instructions provided by @voodoo-burger

Beside the road I made two sets of tiles, one with parcel added then tiles, and the other with tiles then parcel and I could only build on the one with parcel then tiles. However anywhere that was buildable I could clear and make buildable again in any order.

https://www.dropbox.com/s/qx3ov2fq86tsmmb/Huge%20Map2.map?dl=0

**Comment by MarkL1961** [comment]
I'll take a look at your map in a minute
I built another in full screen (still slow at responding though) and did things in stages in case it was adding an heliport that removed the flag or something and when it came to playing it the game did not recognise there was one.  Yes, this is off topic.
Not selecting camera or number of players did not make a difference.

**Comment by TheCycoONE** [comment]
So far I can't see in code how parcels would be a difference either - but I did produce it. This will take some digging.

Thanks for your efforts @MarkL1961

**Comment by MarkL1961** [comment]
@TheCycoONE 
Loaded the above map in the old editor and only middle tiles have the buildable flag in the large building  (I did this as you can see flags in the old editor.)
I can see the bits you refer to and purple part is not buildable.  Becomes buildable when you add walls, again this is the older editor.  The large building has walls, I take it with the new editor walls has nothing to do with the buildable flag now?

Now loaded it in the new editor and renamed it test map to go with my level file.  Load the scenario the build flags are as I saw them above.
Then in the new editor added parcel 2 to the purple space and also added another door to the large building.  In game there was no change to the large building, only the middle tiles are buildable and a couple in the purple space.

![test map](https://cloud.githubusercontent.com/assets/4965487/15687706/073fde1c-276e-11e6-9eca-b9b395dcd64d.png)

**Comment by MarkL1961** [comment]
just a thought, in the old editor there could be issues with the build flag if buildings were too big or had too many doors.
I would try and create a large building from scratch, but as I have no real control of what the mouse is doing it could take weeks doing it a tile at a time

**Comment by MarkL1961** [comment]
How does the game determine where is buildable now then if walls don't have an affect?  Is it parcels that are not 0?

**Comment by TheCycoONE** [comment]
All 'inside' tiles (on the inside tab) are given the flags buildable, passable, and hospital. The game uses the combination of those flags and parcel id to determine if you can build on the tile.

All 'road' tiles and some of the 'outside' tiles are given the flag passable, but not hospital or buildable.

It looks like 'passable' is being preserved, but 'hospital' is being lost. 'builadble' isn't actually shown so we don't know the state of that flag.

**Comment by MarkL1961** [comment]
Is there a way to add the debug menu or at least the flags part to the editor?
That way we can see what happens before and after save as it maybe that saving loses the flag.

**Comment by TheCycoONE** [comment]
Yep, I've done this myself for testing. Just edit Lua/dialogs/menu.lua: copy the lines starting from https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/dialogs/menu.lua#L755 to just before https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/dialogs/menu.lua#L543

The bytes overlays do not work because they grab information directly from the map file, not live, but flags and heat overlays do work.

I had plans for introducing the flags overlay as part of another editor mode but didn't get around to them.

**Comment by TheCycoONE** [comment]
Ok, what I see is that this only happens when you draw the tiles, save, load, and draw the parcel. And what's better is that I do see the issue in the code as well. When loading a map we only mark the hospital and buildable flags for parcels.

The safest fix would be to add a parameter that is set when loading in the map editor which causes it to always set all flags as set on the map. That said I don't know that there is any harm in always setting them regardless - I will run some tests removing the condition altogether.

**Comment by voodoo-burger** [comment]
Thanks for the great effort guys!
