### ISSUE TITLE
Custom maps should save under users folder.

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1045]
Currently custom maps are being saved in the same directory as the maps shipped with CorsixTH which is often under Program Files in Windows and probably /usr/share on Linux. Programs are not suppose to be saving files in these directories (and may not have write access to them).

We need to be saving under %APPDATA%/CorsixTH/Levels on Windows and the equivalent directory on Linux. When showing the list of custom levels to load, we should include both levels in that folder and levels shipped with the game.

**Comment by Lego3** [comment]
On Windows it might be better to start saving stuff that users are supposed to easily find in e.g. My Documents?

**Comment by TheCycoONE** [comment]
@Lego3 not a bad idea but out of scope for this issue. My main concern is that without fixing this people that use a Linux distribution package will not be able to save their maps. That is probably a 0.60 blocker.
