### ISSUE TITLE
Some patients in emergencies (still) reported as killed in 0.60b2

### ISSUE THREAD

**Issue by ciand** [CorsixTH/CorsixTH#1048]
Despite being reported as fixed in #1032 and #1038 being closed as a result, this is still an active issue.

I had a 3 patient Broken Wind emergency, all three treated with a 100% drug but 2 are reported as dead; 6 patient Sweaty Palms with 5 reported as dead

The fax after shows all as cured and awards you the correct bonus.

**Comment by TheCycoONE** [comment]
Where are they reported as dead?

**Comment by ciand** [comment]
Asisstant announces the death/increment the death total he announces; they appear in the casebook as a death and your total at year-end is incrememted. I didn't check if your reputation suffers yet.

**Comment by ciand** [comment]
Reputation appears to take a hit of -1 for each reported death although as you get a boost for the emergency in total you may still get an overall increase.

**Comment by TheCycoONE** [comment]
Alright, I've reopened #1032 Thanks.
