### ISSUE TITLE
General diagnosis still pretty useless

### ISSUE THREAD

**Issue by zheega** [CorsixTH/CorsixTH#1060]
It is a big room, but hardly any patients visit it, and the revenue is very low. It should be updated/changed/removed.

#### System Information

**CorsixTH Version: 0.60-beta2

**Operating System: Windows 10

**Theme Hospital Version: GOG.com

**Comment by TheCycoONE** [comment]
There's no plan to change this from the original Theme Hospital. Is there anything different about the original Theme Hospital's handling of this room that made it more useful in your opinion?

**Comment by zheega** [comment]
No, it was useless as well. Makes me mad every time :)

Sometimes it has as low as 1% of GP's visits.

**Comment by TheCycoONE** [comment]
Sorry, it's going to stay that way. No strategy if every room is a cash cow.

**Comment by MarkL1961** [comment]
Try moving up the middle slider in the hospital policy screen as this will make patients visit more diagnosis rooms.  Move it back when queues start to build up though

**Comment by TheCycoONE** [comment]
Hiring less skilled / less attentive doctors will also cause it to be used more.
