### ISSUE TITLE
App:CheckForUpdates() - http.lua:189: use of undeclared variable 'PROXY'

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#1061]
Hi,

I know this must be a problem with my CorsixTH install but I'm out of ideas for what the cause could be.

My firewall isn't blocking my Lua Interpreter and my CorsixTH executable, so does anyone have an idea for what the cause of this error could be? I'm behind a router with broadband internet.

I've used LuaRocks to download and install LuaSocket 3.0-rc1-2.

I've compiled a 64 bit CorsixTH executable from the latest master branch code for v0.60-beta2.

I'm using Windows 10 64 bit with the free Zone alarm firewall. I've tried disabling it and just using the Windows firewall with it set to allow internet access for my Lua interpreter and CorsixTH.exe.

```
Checking for CorsixTH updates...
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The movie_over handler.
A stack trace is included below, and the handler has been disconnected.
...e\AppData\Roaming\LuaRocks\share\lua\5.3\socket\http.lua:189: use of undeclared variable 'PROXY'
stack traceback:
        [C]: in function 'socket.http.request'
        ...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:1427: in method 'checkForUpdates'
        ...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:442: in method 'loadMainMenu'
        ...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:294: in field 'callback_on_destroy_movie'
        ...mming\Github\build\CorsixTH\Release\Lua\movie_player.lua:260: in method '_destroyMovie'
        ...mming\Github\build\CorsixTH\Release\Lua\movie_player.lua:229: in method 'onMovieOver'
        ...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:1057: in function <...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:1056>
        (...tail calls...)
        ...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:880: in function <...he\Programming\Github\build\CorsixTH\Release\Lua\app.lua:875>
```

**Comment by J-Shep** [comment]
I see @TheCycoONE you've [commented](https://aur.archlinux.org/packages/corsix-th/) about 3.0rc1 being broken before.

**Comment by TheCycoONE** [comment]
It is broken, you need to use a newer commit from luasocket (they don't have a working release version).

I included a working version in CorsixTH\deps

**Comment by J-Shep** [comment]
@TheCycoONE Thanks for your help.
