### ISSUE TITLE
Cured emergency patients marked as killed

### ISSUE THREAD

**Issue by TheMatia** [CorsixTH/CorsixTH#1062]
#### Describe the issue

When some (but not all) emergency patients are cured, they get the thumbs-down face above their heads, hovering over them makes the message "Dying!" appear in the bottom toolbar, and the doctor person in the bottom corner will pop up with an "Oh no! You just killed another patient!" message. However, their treatment history says that they have been cured, and they walk out of the hospital and off the map like all cured patients. I should note, however, that I haven't noticed any of my emergency patients actually dying since I noticed this bug, so it could be a bug with the deaths rather than with the cures.

#### Steps to Reproduce
When an emergency occurs, watch carefully.

#### Expected Behavior
Emergency patients should be cured or killed like any other patient.

#### System Information
**CorsixTH Version:** *0.60 Beta 2*

**Operating System:** *Windows 10 64-bit*

**Theme Hospital Version:** *CD*

#### Gamelog.txt
---------------------------------------------------------------

Welcome to CorsixTH v0.60-beta2!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.

#### Additional Information
Screenshot:
![corsixth_deathbug](https://cloud.githubusercontent.com/assets/13178182/14938463/2b7fa7b8-0f1c-11e6-9d8c-05ecd80daa93.png)

**Comment by wolfy1339** [comment]
This was fixed in the latest revision
