### ISSUE TITLE
Machine smoke freezes on machine replacement

### ISSUE THREAD

**Issue by TheMatia** [CorsixTH/CorsixTH#1064]
#### Describe the issue
When a machine (in this case, a Slicer) was at a poor state of repair and started smoking, I selected it and chose to replace it (the handymen were too far away and I was in the midst of an emergency). When I did that, the number of times used went down to 0 as normal, but the smoke froze instead of vanishing.

#### Steps to Reproduce
1. Get a machine down far enough that it starts to smoke

2. Click on it and choose to replace it

#### Expected Behavior
Smoke should vanish completely

#### System Information
**CorsixTH Version:** *0.60 Release Candidate 1*

**Operating System:** *Windows 10 64-bit*

**Theme Hospital Version:** *CD*

#### Gamelog.txt

---------------------------------------------------------------

Welcome to CorsixTH v0.60-rc1!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.

### Additional Info
*Screen shot (2 uses after replacing machine):*
![image](https://cloud.githubusercontent.com/assets/13178182/14953120/5f95d8a4-105e-11e6-9946-a27fd11a1496.png)

**Comment by TheMatia** [comment]
Update: The frozen smoke does go away the next time a handyman repairs the machine.

**Comment by TheCycoONE** [comment]
Thanks @TheMatia 
As a newly introduced bug I have assigned a 0.60 milestone target in spite of the low severity (not game breaking).

**Comment by TheCycoONE** [comment]
@JoshKeegan are you available to look at this?

**Comment by JoshKeegan** [comment]
More than happy to sort this, but it might be a week or two before I get around to it.
Is there any date set for the 0.6 release yet?

**Comment by TheCycoONE** [comment]
Alright, I'd like it fixed sooner than that so I'll take a look first.

As for the release:
The first release candidate that's available for two weeks with no blocking bugs will become 0.60. Release candidates will be released either weekly or every other week as demand dictates. Only regressions over 0.50 are blocking bugs, but other severe game breaking bugs (e.g. anything that crashes) can also be fixed during this period.

**Comment by JoshKeegan** [comment]
Got to look at it today, see PR #1070

**Comment by TheCycoONE** [comment]
Thanks!
