### ISSUE TITLE
More Ram

### ISSUE THREAD

**Issue by Tunaa** [CorsixTH/CorsixTH#1066]
How can i allocate more Ram to CorsixTH? I hope someone can help me.

**Comment by TheCycoONE** [comment]
RAM is allocated by your operating system on an as needed basis, why do you want to allocate more RAM to CorsixTH?

**Comment by Tunaa** [comment]
my fps are very low. i want to allocate corsix more memory. usual this works always on my laptop

**Comment by TheCycoONE** [comment]
How do you normally allocate programs more resources?

**Comment by Tunaa** [comment]
i am seaching for some configs. this works very well for me. but sadly ive found no config for corsixth where i can change the memory

**Comment by TheCycoONE** [comment]
You won't find one, this is typically a feature of languages like Java that run in a garbage collected VM. Increasing the heap size in those languages means the garbage collector can run less aggressively and sets a maximum memory limit for the program to use. CorsixTH requests memory on demand and has no limit.
