### ISSUE TITLE
Game crashing randomly

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#1067]
#### Describe the issue
I am really not sure what is going on, I was buying some radiators and then the game suddenly crashed.
#### Steps to Reproduce
Not sure how to reproduce

#### Save Game
http://vps.wolfy1339.com/~wolfy1339/CorsixTH/Autosave8.sav

#### System Information
**CorsixTH Version:** 0.50

**Operating System:** Windows 10

**Theme Hospital Version:** Origin

#### Gamelog.txt
```
Created game with savegame version 105.
Warning: Trying to remove nonexistant room build callback (function: 000001F4A10968A0) from humanoid (table: 000001F49FD87000).
Warning: Trying to remove nonexistant room remove callback (function: 000001F4A7325BF0) from humanoid (table: 000001F49FD87000).
```

### Additional Info
Gamelog.txt was last edited ‎May ‎2, ‎2016, ‏‎22:03:32 according to Windows Explorer, so I don't think it's relevant to this session

**Comment by TheCycoONE** [comment]
How reproducible is this?

**Comment by wolfy1339** [comment]
It just happened again. I don't know... I haven't reproduced it in the same circumstances

**Comment by wolfy1339** [comment]
Going to try and debug in VisualStudio

**Comment by TheCycoONE** [comment]
Ok, hopefully it happens in VS where you can see it. Otherwise it probably wrote a dump file somewhere for sending to Microsoft, but I'm not sure where you'd find it.

**Comment by wolfy1339** [comment]
Nothing yet

**Comment by wolfy1339** [comment]
> Otherwise it probably wrote a dump file somewhere for sending to Microsoft, but I'm not sure where you'd find it.

I did find this in `Control Panel > All Control Panel Items > Security and Maintenance > Reliability Monitor` when you right click on CorsixTH.exe and select *View technical details*:

```
Description
Faulting Application Path:	C:\Program Files\CorsixTH\CorsixTH.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	CorsixTH.exe
Application Version:	0.0.0.0
Application Timestamp:	55d13487
Fault Module Name:	ntdll.dll
Fault Module Version:	10.0.10586.240
Fault Module Timestamp:	5716d0a8
Exception Code:	c0000005
Exception Offset:	000000000002fe34
OS Version:	10.0.10586.2.0.0.256.48
Locale ID:	4105
Additional Information 1:	2617
Additional Information 2:	26175b701b13bc996149ee5ad6987af6
Additional Information 3:	23ec
Additional Information 4:	23ecec2fc93c56524add5d2b4f78f546

Extra information about the problem
Bucket ID:	94a1bef2f1b4f4c398a8ddcd68e65619 (120466493486)
```

**Comment by Alberth289346** [comment]
There was a user in #openttd with the same problem (at least in the same .dll file) yesterday. Dit that get updated recently?

**Comment by wolfy1339** [comment]
I did have updates to Windows a couple days ago.
And a quick Windows Explorer search reveals that some of the `ntdll.dll` files were modified a couple days ago, which probably means they were updated.

Full version of Windows 10: 10586.240
It seems as though this version is a Windows Insider Build from the Release Preview ring.

After a little bit of research, [KB3147458 ](https://support.microsoft.com/en-ca/kb/3147458) included an updated `ntdll.dll` file

**Comment by TheCycoONE** [comment]
IIRC an ntdll.dll fault represents anything that happens in kernel space, so it could be a driver or anything. It is definitely outside of CorsixTH though.

**Comment by MarkL1961** [comment]
Has a familiar ring to it, is it anything to do with 64 and 32 bit versions and running the wrong one?

**Comment by Alberth289346** [comment]
closing issue, as we don't fix windows nt bugs
