### ISSUE TITLE
screen switches between 2 displays rapidly while placing items in new room.

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1069]
#### Describe the issue

Recently updated my OS, it has now SDL2-devel-2.0.4-4.fc23.x86_64 . (Don't think anything was changed in SDL2 code recently, so my update seems the likely candidate.)

Game play seems normal. When building a new room however, the screen alternates between two different screens (captured with "print screen" function) very rapidly:

![screenshot from 2016-05-07 14-19-35](https://cloud.githubusercontent.com/assets/3254232/15092243/44ec61da-1464-11e6-8c36-050492265b9f.png)
![screenshot from 2016-05-07 14-19-34](https://cloud.githubusercontent.com/assets/3254232/15092248/565ab020-1464-11e6-9a9c-5f5bfbb35212.png)

This is a quite disturbing while playing the game :)

The size of the disturbance varies, sometimes it's a small area, sometimes (like here) it's the entire screen (except the window and the desk I am holding with the mouse).

Game functions normally otherwise, and the disturbance ends when you have placed everything, and press the "done" placement at the window. Editing a room also shows glitches, ghost images of items that were moved, but have been placed in the mean time. Maybe you could produce distrurbances like above there too, but did not try much.
#### Steps to Reproduce
1. It happens with every room placement, it seems. The above example was the first room in the normal campaign.
#### System Information

**CorsixTH Version:** master commit 4f3ac15

**Operating System:** *Linux Fedora 23

**Theme Hospital Version:** _CD_

**Comment by Alberth289346** [comment]
First analysis suggests scaling multiple times in SDL is causing havoc. SDL itself does not give an error, so it may be a driver problem at my machine.

**Comment by sgtbigman** [comment]
I tested for this behavior a few days ago on a machine running Fedora 23, but I was not able to reproduce the issue. Of course, this was while using the demo data, so there is that difference, at least.

Aside from that, I've noticed Gnome (or possibly Fedora itself) having some drawing/refreshing issues from time to time, so maybe this could be related to that type of thing as well.

**Comment by TheCycoONE** [comment]
Alberth is running an AMD HD7000, which might be important to the issue. We couldn't reproduce it in ArchLinux but that was on nvidia. It would be good if everyone posted their video card and what drivers they're using as well.

**Comment by TheCycoONE** [comment]
The other thing we determined is that it only happened when the scale was changed more than twice in a frame - which is more confusing than enlightening.

**Comment by mpmc** [comment]
I was told by tobylane on IRC to post my graphics info on here as I'm getting similar glitches.

!['Screenshot'](http://i.imgur.com/gkaDJCE.png)

System: Xubuntu 1604 x64.
Corsix Build git ab8ad632759bbfd6e7c8d961be99fc01be03a3c5 / LUA 5.3.

Graphics info:

```
01:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Redwood PRO [Radeon HD 5550/5570/5630/6510/6610/7570] [1002:68d9] (prog-if 00 [VGA controller])
	Subsystem: PC Partner Limited / Sapphire Technology Radeon HD 5570 [174b:e142]
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f7e20000 (64-bit, non-prefetchable) [size=128K]
	I/O ports at e000 [size=256]
	Expansion ROM at f7e00000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: radeon
	Kernel modules: radeon

01:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Redwood HDMI Audio [Radeon HD 5000 Series] [1002:aa60]
	Subsystem: PC Partner Limited / Sapphire Technology Redwood HDMI Audio [Radeon HD 5000 Series] [174b:aa60]

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD REDWOOD (DRM 2.43.0, LLVM 3.8.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by TheCycoONE** [comment]
Thanks @mpmc, so that's another vote for something affecting AMD devices. My understanding is that this isn't a CorsixTH regression (the same behavior happens in 0.50 when compiled against SDL 2.0.4)?

**Comment by TheCycoONE** [comment]
Also it would be very helpful if someone with the affected hardware could do a bisect on sdl2, and then report the bug upstream.

**Comment by Alberth289346** [comment]
Tried this, but it already failed on a self-built version of sdl 2.0.3 against head of master (ie 0.60-ish).
I also tried cth 0.50 against that sdl 2.0.3, and it also failed.

This seems to point squarely to the video driver

**Comment by TheCycoONE** [comment]
Yes definitely sounds like a regression in the video driver now. Tricky.

**Comment by Alberth289346** [comment]
Issue seems to have resolved itself. At least, I could build a GP without glitches with some newer kernel which arrived through updates in the last year.
