### ISSUE TITLE
norwegian language for 0.6 rc 2

### ISSUE THREAD

**Issue by Grimdoc** [CorsixTH/CorsixTH#1075]
As we discussed earlier, here is the updated norwegian.lua for 0.6 rc 2.

Attached file to be renamed to "norwegian.lua" (from *.lua.txt) and put in directory *\Lua\languages\
Thanks.

[norwegian.lua.txt](https://github.com/CorsixTH/CorsixTH/files/272692/norwegian.lua.txt)

**Comment by Alberth289346** [comment]
See PR #1076
