### ISSUE TITLE
Wrong package name in the How to compile wiki - liblua5.2-0-dev

### ISSUE THREAD

**Issue by Sancho-Panza** [CorsixTH/CorsixTH#1079]
Hi,

In the wiki:
How to compile > Compiling on Linux > Debian based distributions:

I think it's not liblua5.**2-0-dev** but liblua5.**2-dev**. I think the error has been made because of the liblua5.2-0 package, which is correct.

See the [debian website](https://packages.debian.org/search?suite=all&section=all&arch=any&searchon=names&keywords=liblua5.2).

**Comment by tobylane** [comment]
Thank you, I've made the change. Our wiki can be edited by anyone on Github, feel free to correct anything else you find.
