### ISSUE TITLE
Drag pasting in map editor slow

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1084]
When dragging to paste objects/tiles the cursor stops and then jumps.  In the clip it does not seem bad with walls only floor tiles and parcel placing.  However if I try to build a larger building I get the same problem with walls as well.

see attached clip https://www.dropbox.com/s/3edgcgq8lv3yo7f/map%20edit.wmv?dl=0

Expect smoother mouse movement that allows you to place tiles in the desired place. it gets worse with larger areas and you end up with tiles where you didn't want them

Windows 9 using 0.60 and original cd data for TH

**Comment by TheCycoONE** [comment]
I've noticed this too. It definitely makes the map editor frustrating to use.

**Comment by TheCycoONE** [comment]
My profiling has shown that the slow down is caused by the canvas:scale() lines in UIMapEditor:fillCursorArea. It appears that the method we are using to draw scaled is too inefficient.
