### ISSUE TITLE
Version 0.6 Music despite setting 0.1 too loud. Sound with 1.0 but too quiet.

### ISSUE THREAD

**Issue by robin110** [CorsixTH/CorsixTH#1085]
CorsixTH Version 0.6

*\* Operating System: *\* \* e.g. Windows 7 \* 64bit

*\* Theme Hospital Version: *\* \* Origin CD

Really great version. Am thrilled and played through yesterday without error the most 2 Level. had not crash.

But that was only possible without the music, because this is Inisetting

Music = 0.1 and
Sound = 1.0
Announcements = 1.0

still too loud.

The sound scheme loud quiet works Ingame wonderful, but the music is far too loud.

In turn, the sound for the setting 1.0 is much too quiet. I had the boxes quite noisy provide the details like typing on the keyboard and listen to other great gimicks.

Furthermore, the Music Mixer does not notice the selection of titles.

At each start, all music files are selected again.
But are "Candy", "Doctor", and "on the Mend" at its best. The rest I find annoying.

Would be great if CorsixTH the jukebox and the volume also come to grips with.

thank you
robin greeting

**Comment by TheCycoONE** [comment]
You may find setting the music volume to around 0.05 or so more to your liking. The lowest recognized value is 0.0128 (which can be written as 0.01) not 0.1. We pass these values directly to SDL_Mixer, which I understand uses a linear scale for volume rather than an exponential one to account for our logarithmic perception of values, which is to say the difference between 0.01 and 0.1 will sound a whole lot more significant than the difference between 0.1 and 0.2 (or 0.5).

**Comment by robin110** [comment]
"0.01" is still too loud for music. It would be better if the sound instead of 1 a 10 would get. But that does not work.

Conclusion: Sound is too quiet, the music too loud.

The game is not playable with music.

**Comment by TheCycoONE** [comment]
That is the full range of control we have over the volume I'm afraid. You're probably running into an issue like: http://stackoverflow.com/questions/5864603/sdl-mixer-midi-volume-issues-on-windows-vista-7

MIDI support on modern computers is bad. The ideal solution is to get an ogg / mp3 recording of the music (from one of the good midi cards of the past like a roland sc-55) and play with them instead. Unfortunately we can't provide those tracks. Alternatively in the forums there some fan created sound tracks that are similar in feel but not copies of the original music.

**Comment by botcherO** [comment]
Have a look at VirtualMidiSynth: http://coolsoft.altervista.org/en/virtualmidisynth
I use it to play the MIDIs with waaaaaay better Samples than the normal ones (like my old Ensoniq Soundscape ISA Card had in the Old Days), but it also has a Mixer with a Master Volume Controller usable from the Systray everytime a Midi Song is played. 
It works with every game i played so far, including CorsixTh 0.60.

**Comment by TheCycoONE** [comment]
@botcherO That's a really great tool. I tried it out and the MIDI sounds so much nicer. Would you mind adding the suggestion to the wiki?

**Comment by botcherO** [comment]
Sure, where do you want that in the wiki?

**Comment by MarkL1961** [comment]
I think in FAQ would be good
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions, perhaps 
Q: my midi sounds don't play or the quality is poor 
A: ~your suggestion

**Comment by botcherO** [comment]
Sorry, that took a while. :)
Added it to the FAQ a minute ago.

**Comment by MarkL1961** [comment]
@robin110 
Can you try the solution from @botcherO  see https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions and if this works for you we can perhaps close this?
