### ISSUE TITLE
Hunting the 'stuck room' bug

### ISSUE THREAD

**Issue by Brainsample** [CorsixTH/CorsixTH#1087]
Howdy folks,

While trying to improve the AI, I stumbled on the 'stuck room' bug quite a lot.
It's a game breaking bug, so I really wanted to hunt it down.
# 

Bug description:
The bug occurs when two staffmembers try to enter a room at the same time, but only one fits in the room. The dispatcher never sends too many staffmembers, as far as I know. But the second staffmember is sent to the room because of the last_room behaviour. The staffmember who is left outside will keep the door reserved, and meander away.
# 

Repro:
In savegame 'just in time to test.sav', you can see nurse BonnMond heading for the staffroom. Nurses Watercliffe and Andberry are both closing in on the now vacant pharmacy. This situation would be very rare without the adjustments I made to the AI code. But that doesn't matter, the savegame works fine in the unpatched game client. After a few seconds, the door will be stuck.

https://drive.google.com/open?id=0BxhJYefjYNIAR2NacXdWZ2V5aU0
# 

Workaround:
It is possible to fix the situation in-game. The trick is to force the offending staffmember to use the door. To do this, pick up and place the bad staffmember inside the room. Then pick up and re-place the staffmember who was stuck inside the room. Now the bad staffmember will walk out the door as if nothing had happened, and the door is unstuck.

Of course you don't know in advance who keeps the door reserved, but you can cycle through all staff.
# 

Fix:

The bug is triggered here, where it is decided that the second staffmember is not allowed to get in:
Original \lua\humanoid_actions\walk.lua line 233:

``` ruby
    if class.is(humanoid, Staff) and is_entering_room and
        humanoid.humanoid_class ~= "Handyman" then
        -- A member of staff is entering, but is maybe no longer needed
        -- in this room?
        if not room.is_active or not room:staffFitsInRoom(humanoid) then
            humanoid:queueAction({name = "idle"},0)
            humanoid:setTilePositionSpeed(x1, y1)
            humanoid:setNextAction({name = "idle", count = 10},0)
            humanoid:queueAction{name = "meander"}
            return
        end
    end
```

This is the place where the door should be released, like so:
Patched \lua\humanoid_actions\walk.lua line 233:

``` ruby
    if class.is(humanoid, Staff) and is_entering_room and
        humanoid.humanoid_class ~= "Handyman" then
        -- A member of staff is entering, but is maybe no longer needed
        -- in this room?
        if not room.is_active or not room:staffFitsInRoom(humanoid) then
            humanoid:queueAction({name = "idle"},0)
            humanoid:setTilePositionSpeed(x1, y1)
            humanoid:setNextAction({name = "idle", count = 10},0)
            humanoid:queueAction{name = "meander"}
            door.reserved_for = nil
            if door.queue:size() > 0 then
                door.queue:pop()
                door:updateDynamicInfo()
            end
            return
        end
    end
```

Popping the queue is apparently necessary, because otherwise the first patient has to skip a turn.
I hope this fixes most, if not all the cases of the stuck room bug.

Version CorsixTH v0.60-rc2

**Comment by TheCycoONE** [comment]
Excellent sleuthing!

Are you going to open a PR?

**Comment by Brainsample** [comment]
Hi TheCycoONE,

Thank you, sleuthing is what I do best. Working with repositories not so much. :)
So I'll leave that to people with experience. In this case it's only five new lines of code, that's not too bad. Let's give the fix a good test, to see if there are any side effects. The workaround can be used to identify old cases of the bug, if necessary.

**Comment by lewri** [comment]
Hi, new here.

Just thought I'd add my comments here.

I noticed this bug occurring both in Operating Theatre (sometimes one doctor wandered round the room and not getting changed, can fix by dragging him out and he re-enters as normal); and in my X-ray room.

More info on X-ray:
The doctor (and a handyman also trying to enter) would get stuck 1 block away from the door and unable to move. Tried removing items each side of door but didn't fix. Also trying to edit room and didn't fix. Dragging stuck doctor into room didn't fix (wandered round room and not seeing patients), then dragging him out again didn't fix (stuck in same place, same when trying to do it with handyman).
Eventually another doctor appears and enters room. Handyman gets unstuck and enters room. No errors was logged in the error command line screen, but have included the save it happened in. Should occur soon after.

[playthrough.zip](https://github.com/CorsixTH/CorsixTH/files/322438/playthrough.zip)

**Comment by Brainsample** [comment]
Hi Lewri,

Thanks for your playthrough. :)
It is doctor Manton who keeps the door of the X-ray room reserved, in this case. If you place doctor Manton in the X-ray room, and then place another doctor in the room, doctor Manton will have to leave. Doctor Manton is the only one who can use the door, so he'll just walk out, and everything will be back to normal.

The code-fix I proposed prevents this bug from happening, but unfortunately it doesn't solve the problem after it has happened. For that you have to find out which staffmember (always a doctor or a nurse) keeps the door reserved. If you feel up to it, you can apply the fix yourself with a text editor.

Patients are asked to be patient!

**Comment by l29ah** [comment]
The bug have just occurred to me at ea0e6df.

**Comment by TheCycoONE** [comment]
Thanks for the update. I guess it didn't hit any of the new (since 0.60) action queue checks then. Too bad.

**Comment by edsilmon** [comment]
Could this be a similar issue to the people stuck in the toilets issue (/catastrophe)?

**Comment by mugmuggy** [comment]
Fixed
