### ISSUE TITLE
Map Editor Parcels

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1090]
Map editor supports the placement of 9 parcels, the old editor went up to 31.
Looking at one of the multi-player levels from TH it had 32.

Perhaps we should do the same?

32 sounds like a lot, but the L43 map uses this many and has  a lot of buildings that fit nicely, so I can see other map makers wanting a similar amount for their creations as well

**Comment by bendyson** [comment]
Would you mind giving a quick description of what 'Parcels' are please? I've had a read through the PRs and googled but couldn't find anything. Not going to learn if I don't ask :)

**Comment by MarkL1961** [comment]
Plot numbers.
Map makers parcel up the different buildings on the map. 1 is owned from the start and the rest you buy in game.  For multi-player (which is not working yet) it is the first plots that belong to the players 1 for player 1, 2 for player 2 etc 5 and higher you buy or bid for in game

**Comment by Alberth289346** [comment]
When you play the game, you can buy new parcels in the town map window. After buying you own it, and can use it for building more rooms in the game.

The first N parcels are for the N players that play (where N==1 always, in the current implementation). Other parcels are just for buy (single player) or for the highest bidder (multi-player).

Another easy way to ask questions is to visit the IRC channel (#corsixth at freenode.net)
