### ISSUE TITLE
error missing MSVCP140.DLL

### ISSUE THREAD

**Issue by evinx** [CorsixTH/CorsixTH#1096]
#### Describe the issue
![screenshot_1](https://cloud.githubusercontent.com/assets/7832892/16201610/8326c7a8-3712-11e6-9526-62271aef501e.png)
#### Steps to Reproduce
1. New install the first time start corsixth

#### Save Game
NONE

#### Expected Behavior
Don't Know

#### System Information
**CorsixTH Version:**
Version 0.60 (last from this website)

**Operating System:**
Windows 10 64bit

**Theme Hospital Version:**
Origin download

#### Gamelog.txt
```
NO GAMELOG.txt
![screenshot_2](https://cloud.githubusercontent.com/assets/7832892/16201805/48828eba-3713-11e6-8124-bb1e1ed34f6d.png)
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by TheCycoONE** [comment]
You need the Microsoft Visual C 2015 redistributable. See the link at the top of https://github.com/CorsixTH/CorsixTH/releases/tag/v0.60

A warning will be added to the installer. #1095

**Comment by evinx** [comment]
ah thanks keep up the good work love it :+1:
