### ISSUE TITLE
Selecting "Custom Campaign" makes the main menu unresponsive in Debian

### ISSUE THREAD

**Issue by emorrp1** [CorsixTH/CorsixTH#1098]
#### Describe the issue

Firstly, is the `CorsixTH/Campaigns/ChrizmanTV.campaign` intended to ship with v0.60? If so, I believe [CorsixTH/CMakeLists.txt#L212](https://github.com/CorsixTH/CorsixTH/blob/v0.60/CorsixTH/CMakeLists.txt#L212) needs "Campaigns" added to the list of directories to install.

Without that change, compiling with cmake didn't install the Campaigns directory, causing an error due to "No such file or directory".

#### Steps to Reproduce
1. Launch main menu

2. Select Custom Campaign

3. Music continues, but can no longer click on the other menu buttons, including exit.

#### Expected Behaviour

The extra campaign selection dialog should open, as it does when the Campaigns directory is present. Or a warning should be displayed that no Campaigns could be found.

#### System Information
**CorsixTH Version:** *0.60*

**Operating System:** *Debian 8 Jessie*

**Theme Hospital Version:** *GOG.com*

### Additional Info
```
---------------------------------------------------------------

Welcome to CorsixTH v0.60!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
...dialogs/resizables/menu_list_dialogs/custom_campaign.lua:69: cannot open ./Campaigns/: No such file or directory
stack traceback:
	[C]: in function 'dir'
	...dialogs/resizables/menu_list_dialogs/custom_campaign.lua:69: in function 'createCampaignList'
	...dialogs/resizables/menu_list_dialogs/custom_campaign.lua:45: in function 'constructor'
	./Lua/class.lua:76: in function 'UICustomCampaign'
	./Lua/dialogs/resizables/main_menu.lua:111: in function 'callback'
	./Lua/window.lua:682: in function 'handleClick'
	./Lua/window.lua:1478: in function 'onMouseUp'
	./Lua/window.lua:1462: in function 'onMouseUp'
	./Lua/ui.lua:649: in function <./Lua/ui.lua:636>
	(...tail calls...)
	./Lua/app.lua:901: in function <./Lua/app.lua:896>

Warning: No event handler for buttonup
```

**Comment by TheCycoONE** [comment]
Yes the Campaign folder was meant to be included. Thank you for the report.
