### ISSUE TITLE
Information after building new rooms appears each level

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1101]
#### Describe the issue

(Couldn't find a post for this before so made one)
While maybe not a bug, maybe more an improvement on the feature. In original game when you built a new room for the first time you got a dialogue box about the room and what it does. In CorsixTH however, this dialogue appears every level. While it could be helpful, it does become a little irritating over a while.
I know pressing 'I' will switch them off completely, but not quite the same as the original 
#### Steps to Reproduce

Just build a room you haven't built before in that level
#### Save Game

N/A
#### Expected Behavior

Should only appear the first time you build a room on your entire playthrough (not level by level)
#### System Information

CorsixTH 0.6, Win 10 64-bit, GOG.com
#### Gamelog.txt

N/A

Thanks,
Lewri

**Comment by Lego3** [comment]
This has worked before for the original campaign, so unless you mean individual scenarios it is a regression.

**Comment by TheCycoONE** [comment]
All the code still looks to be there for original campaign progression. I haven't tested but I don't see any obvious problem there. I suppose there is no harm in making it persist for other levels as well - is this what you mean @lewri

**Comment by MarkL1961** [comment]
Tested against 0.50 and it was working then

**Comment by MarkL1961** [comment]
I think we understand the problem and until 0.50 CorsixTH did the same unless in debug.  For some reason this got broke and we need to see where so we can restore it to match TH

**Comment by TheCycoONE** [comment]
On a vaguely related note, ```debug``` should not disable these dialogs. If it's annoying for developers there should be another config option for it.

**Comment by Alberth289346** [comment]
or even no config, I don't see the point of enabling the setting, and then disabling it again if you're debugging.

**Comment by lewri** [comment]
I'm not sure what happened. But once I reached Evergeen Hospital (might be wrong) level the dialogues stopped coming up. Synopsis for level: £200k in bank, rep of 600 (on playing board its the burning building)

**Comment by lewri** [comment]
As far as I know this is no longer a problem.
