### ISSUE TITLE
Doctors endlessly meandering in rooms with patient present

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1104]
#### Describe the issue

Hard to describe this one since the error started spreading more as I played. On occasion, doctors were seeing patients in GP Office and the patient would endlessly be stuck in consult. The doctor would wander round the room endlessly (i.e. not going to desk/filing cabinet) and not dismissing themselves even when tired (just kept going and going).
You could resolve this error by dragging said doctor out of room and putting him back in. Patient would be dismissed and and then re-enter room when doctor was back inside. Diagnosis went normally after.
However, the problem spread to multiple GPs Offices (all resolveable), but then hit Cardio.
On cardio, the doctor meandered round the room and the patient stuck on the treadmill. Dragging doctor out did not dismiss patient, still stuck. Doctor would re-enter room and patient still stuck, but doctor could not complete diagnosis or call next patient. At this point I made savegame and uploaded.

Other steps I tried (not necessarily in this order):
1. Sent patient home. Patient had 'exit' icon above but still did not move. Neither called in next patient
2. Attempted to edit room. Doctor left, but could not edit since patient still inside.
3. Called handyman to machine. A second cardio spawned in the room, handyman fixed the second cardio. Second cardio not functional.
4. Dragged different doctor in room.
#### Steps to Reproduce
1. Random occurence through game. But savegame should have instances happening.
#### Save Game

[playthrough (2).zip](https://github.com/CorsixTH/CorsixTH/files/333308/playthrough.2.zip)
#### Expected Behavior

Doctors should carry out patient diagnosis and then dismiss patient.
#### System Information

**CorsixTH Version:** *0.60

**Operating System:** Win 10 64-bit

**Theme Hospital Version:** GOG.com
#### Gamelog.txt

Created game with savegame version 111.
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000002505FCC81F0) from humanoid (table: 000002506B91B8B0).
Warning: Trying to remove nonexistant room remove callback (function: 000002506C60D720) from humanoid (table: 000002506B91B8B0).
Warning: Trying to remove nonexistant room build callback (function: 000002506DE21D90) from humanoid (table: 0000025066129FB0).
Warning: Trying to remove nonexistant room remove callback (function: 0000025067912470) from humanoid (table: 0000025066129FB0).
Warning: Trying to remove nonexistant room build callback (function: 0000025066E37FE0) from humanoid (table: 000002506C7C2530).
Warning: Trying to remove nonexistant room remove callback (function: 000002506D08DBD0) from humanoid (table: 000002506C7C2530).
Warning: Trying to remove nonexistant room build callback (function: 0000025066E46320) from humanoid (table: 0000025065EEE480).
Warning: Trying to remove nonexistant room remove callback (function: 0000025066CBAFA0) from humanoid (table: 0000025065EEE480).
Warning: Trying to remove nonexistant room build callback (function: 0000025067995360) from humanoid (table: 0000025066F89220).
Warning: Trying to remove nonexistant room remove callback (function: 00000250660ABF80) from humanoid (table: 0000025066F89220).
Warning: Trying to remove nonexistant room build callback (function: 000002506DB51B40) from humanoid (table: 0000025066FFB4E0).
Warning: Trying to remove nonexistant room remove callback (function: 00000250654426A0) from humanoid (table: 0000025066FFB4E0).
Warning: Trying to remove nonexistant room build callback (function: 0000025065263B40) from humanoid (table: 00000250678BCF20).
Warning: Trying to remove nonexistant room remove callback (function: 000002505EECEC00) from humanoid (table: 00000250678BCF20).
Warning: Trying to remove nonexistant room build callback (function: 0000025066E4A760) from humanoid (table: 000002506C212130).
Warning: Trying to remove nonexistant room remove callback (function: 000002506EFD9910) from humanoid (table: 000002506C212130).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000001B8CCF053E0) from humanoid (table: 000001B8C6D336E0).
Warning: Trying to remove nonexistant room remove callback (function: 000001B8C4D6D050) from humanoid (table: 000001B8C6D336E0).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:667: Can only finish current action
stack traceback:
    [C]: in function 'assert'
    C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:667: in method 'finishAction'
    C:\Program Files\CorsixTH\Lua\rooms\cardiogram.lua:97: in field 'after_use'
    ...Files\CorsixTH\Lua\humanoid_actions\multi_use_object.lua:264: in local 'timer_function'
    C:\Program Files\CorsixTH\Lua\entity.lua:219: in method 'tick'
    C:\Program Files\CorsixTH\Lua\world.lua:1075: in method 'onTick'
    C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
    (...tail calls...)
    C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
### Additional Info

An error did occur earlier in the game but did not take note of it causing problems
Problem did not stop handymen entering room
![corsixth_screen1](https://cloud.githubusercontent.com/assets/20030128/16359358/16bfb9d8-3b29-11e6-8850-8f169fbf9535.PNG)
![corsixth_screen2](https://cloud.githubusercontent.com/assets/20030128/16359359/17a630d4-3b29-11e6-8061-6787805f3d8e.PNG)

**Comment by Alberth289346** [comment]
Thanks for the report, but in it's broken state, there isn't much that can be done.

It's like looking at a shattered glass in the floor (or in your case several different glasses on the floor where all the pieces are everywhere), and then trying to decide how it (they) fell, and why. As you can imagine, that's hard or impossible to do.

To get insight in what causes the problem, a savegame earlier in time is required, one just before the glass was dropped. With such a savegame, you can load the savegame, and replay the events over and over again, analyzing each step of the way, and eventually finding out why the glass gets dropped while it shoudn't, and fix it.

**Comment by lewri** [comment]
Here's the savegame I have before it broke. However, speeding through the game (10 months) it did not break again.
I think the break occurred when I moved the pharmacy above the cardio machine to where the staff room is in the block with GP Offices (had 2 pharmacies at the time). At this point I imagine the error from the gamelog occurred. 
[buglogautosave4.zip](https://github.com/CorsixTH/CorsixTH/files/333508/buglogautosave4.zip)

No output in gamelog for that autosave.

**Comment by Brainsample** [comment]
Each time (room.lua line 98:)Room:createEnterAction(humanoid) is executed, a callback is registered, so the entity knows what to do in case the room is deactivated. That callback is erased when the entity safely enters the target-room in (room.lua line 291:)Room:onHumanoidEnter(humanoid)

However, when a staffmember is rerouted before entering the room, the callback is not erased. Then, when you edit the old target-room, all its callbacks are executed in (room.lua line 927:)Room:deactivate(). This can make staffmembers meander when they're in an other room with a patient.

=======

I've added these debug lines to (app.lua line 1373:)App:afterLoad(), to show all registered callbacks for staffmembers after loading:


```lua
function App:afterLoad()
	for _, room in pairs(self.world.rooms) do -- Go through all rooms
		print(room.room_info.id) -- Print the room type
		for enroute, _ in pairs(room.humanoids_enroute) do -- Go through all registered callbacks
			if enroute.profile then -- Only look at staffmembers
				print("\t", enroute.profile.name) -- Print the staffmember's name
			end
		end
	end
```

Note: It looks like the staffroom never clears the callbacks in humanoids_enroute.

=======

I think the best way to fix this, is to clear the old callback each time a staffmember is rerouted.
And also clean up the humanoids_enroute for all rooms in afterLoad() for savegame compatability.

**Comment by lewri** [comment]
I think I found the steps that caused the bug to happen. It affects Doctor HIGHSMITH (at least to start with)

When editing the Staff rooms, he was ejected from it while deleting it (the one with the 4 GP Offices). After that he seems to be stuck in meander (his position to go to is in his GP Office though). I imagine deleting the staff room while a staff  member was resting led to the bug. But not sure how.
If someone can reproduce this (might need to edit the other staff room after deleting the mentioned one) then it could be a confirmation.
![corsixth_screen3](https://cloud.githubusercontent.com/assets/20030128/16363982/e7f15354-3bd3-11e6-8dca-e89e900842bc.PNG)

**Comment by Brainsample** [comment]
Hi Lewri,

Yes, editing the staffroom must be the easiest way to reproduce the bug.

I'm testing these lines of code, still misplaced in App:afterLoad().
The aim is to clean up all bad callbacks after loading a game:

```lua
function App:afterLoad()
  for _, room in pairs(self.world.rooms) do -- Go through all rooms
    for enroute, _ in pairs(room.humanoids_enroute) do -- Go through all registered callbacks
      local clear_this_callback = true -- Presume the callback must be cleared
      for _, action in pairs(enroute.action_queue) do -- Go through the action queue
        if action.name == "walk" then -- Only look at walk actions
          if room == self.world:getRoom(action.x, action.y) and -- This walk action leads into the room
              room ~= enroute:getRoom() then -- The entity is not already in the room
            clear_this_callback = false -- Assume the callback is valid, don't clear
          end
        end
      end
      if clear_this_callback then room.humanoids_enroute[enroute] = nil end -- Clear if necessary
    end
  end
  
  print("------------Check the results--------------")
  
  for _, room in pairs(self.world.rooms) do -- Go through all rooms
      print(room.room_info.id) -- Print the room type
      for enroute, _ in pairs(room.humanoids_enroute) do -- Go through all registered callbacks
          if enroute.profile then 
              print("\t", enroute.profile.name) -- Print the staffmember's name
            else
              print("\t", enroute) -- Print the table index
          end
      end
  end
```

It also checks patients, and it seems to work well.

**Comment by Brainsample** [comment]
After some digging, I think there are three possible ways of fixing this.

1) Do the bookkeeping as the game progresses, clearing the callback every time an entity changes its destination. That's not easy to do, and hard to maintain.

2) Build a fresh humanoids_enroute every tick. It may seem blunt, but does have the advantage of knowing who goes where.

3) Make humanoids_enroute obsolete, and change the action queue on the fly in the function Room:deactivate(). This function is the only place humanoids_enroute is actually used (apart from all the bookkeeping).

=======

I've experimented with all three options. The first one is torture, lol. Number 2 and 3 worked with some light testing. Let me clean up my code, and let you know tomorrow :)

**Comment by Brainsample** [comment]
For testing, I placed this cleaning loop in World:onTick(). It was a good test, and works as an "if everything else fails" solution, but it's not very elegant.

```lua
  for _, room in pairs(self.rooms) do -- Go through all rooms
    for enroute, _ in pairs(room.humanoids_enroute) do -- Go through all registered callbacks
      local clear_this_callback = true -- Presume the callback must be cleared
      for _, action in pairs(enroute.action_queue) do -- Go through the action queue
        if action.name == "walk" then -- Only look at walk actions
          if room == self:getRoom(action.x, action.y) then -- The action leads into the room
            clear_this_callback = false -- Assume the callback is valid, don't clear
          end
        end
      end
      if clear_this_callback then 
        room.humanoids_enroute[enroute] = nil
      end
    end
  end
```

Then why not clean up humanoids_enroute just before it is used? That's much more efficient ... and it also makes humanoids_enroute obsolete, hehe. This new Room:deactivate() should give the functionality we want:

```lua
function Room:deactivate()
  self.is_active = false -- So that no more patients go to it.
  self.world:notifyRoomRemoved(self)
  for _, humanoid in pairs(self.world.entities) do -- Go through all entities
    if humanoid.action_queue then
      for _, action in pairs(humanoid.action_queue) do -- Go through the action queue
        if action.name == "walk" then -- Only look at walk actions
          if self == self.world:getRoom(action.x, action.y) then -- The action leads into the room
            if class.is(humanoid, Patient) then
              humanoid:setNextAction({name = "seek_room", room_type = self.room_info.id})
            elseif class.is(humanoid, Vip) then
              humanoid:setNextAction({name = "idle"})
              humanoid.waiting = 1;
            else -- For staffmembers
              local current_room = humanoid:getRoom()
              if current_room then -- In a room
                if current_room.room_info.id = "staff_room" then
                  humanoid:setNextAction({name = "use_staffroom"})
                else -- Treatment / diagnosis / research
                  self:commandEnteringStaff(humanoid)
                end
              else -- In the corridor
                humanoid:setNextAction({name = "meander"})
              end
            end
          end
        end
      end
    end
  end
end
```

Yep, I was still able to make doctors meander in a room with a patient! So I added the different actions, depending on the staffmember's current location. Maybe something similar must be done for patients too.

**Comment by lewri** [comment]
While I can't write in Lua, I can at least make some understanding of the code. Looks like you've made good progress @Brainsample! 
I suppose trying to work out why editing a room causes doctors in different rooms to 'meander' in the first place could be addressed. If it's specific to staff rooms (perhaps building multiple staff rooms causes the breakage) then maybe something in the code there needs addressing too.

**Comment by Brainsample** [comment]
Hi Lewri,

You help a lot by posting your findings here. :) Before the different actions depending on the doctor's current location were added, I made the doctor meander in a room by:

- Find two nearby GP rooms with a doctor.
- Make sure there are no nearby doctors in the corridor.
- Wait for a patient to arrive in room A.
- Pick up the doctor in room A, place him in the staffroom.

Observe: The doctor in room B is now called to room A.

- Before the doctor has left room B, edit room A.
- Wait for a patient to arrive in room B.

Bug observed: Room B has a meandering doctor, and a patient.
So even when the doctor didn't act on some expired callback, it still went wrong.

Having the doctor take back command of room B fixes the meandering. But there are other options, like forcing the doctor to leave room B, and then meander in the corridor.

**Comment by Brainsample** [comment]
All walk-actions made by createEnterAction() have a field named "is_entering", it contains the destination room. Checking "is_entering" is more efficient than checking the room's coordinates.

To keep things simple and reliable, I've been testing the "leave room and meander" version. That should work for all staff & room combinations.

When editing a room in CorsixTH 0.60, queueing patients don't stand up to find a new room. This behaviour makes sense: the user may just want to quickly move a machine.


```lua
function Room:deactivate()
  self.is_active = false -- So that no more patients go to it.
  self.world:notifyRoomRemoved(self)
  for _, humanoid in pairs(self.world.entities) do -- Go through all entities
    if humanoid.action_queue then
      local in_queue = false -- Presume a patient is not in the queue
      for i, action in pairs(humanoid.action_queue) do -- Go through the action queue
        if action.name == "queue" and self.door == action.reserve_when_done then 
          in_queue = true -- A patient is in this room's door queue
        elseif self == action.is_entering then -- A walk action leads into this room
          if class.is(humanoid, Patient) then
            if not in_queue then
              humanoid:setNextAction({name = "seek_room", room_type = self.room_info.id})
            end
          elseif class.is(humanoid, Vip) then
            humanoid:setNextAction({name = "idle"})
            humanoid.waiting = 1;
          else -- For staffmembers
            if humanoid:getRoom() then -- In a room
              if humanoid ~= self.door.user then -- Don't disturb the door animation
                humanoid:setNextAction(self:createLeaveAction())
                humanoid:queueAction({name = "meander"})
              end
            else -- In the corridor
              humanoid:setNextAction({name = "meander"})
            end
          end
        end
      end
    end
  end
end
```

Test plan: Try to disrupt your hospital in every possible way, by editing or crashing rooms.

**Comment by lewri** [comment]
Hi Brainsample,

I started up my game again today. Trying to find a workaround for the error, I rebuilt problematic rooms. However, on rebuilding the 4 GP Offices I got this:

>Warning: Could not find a humanoid to remove from the reserved user list
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\map.lua:60: bad argument #1 to 'floor' (number expected, got nil)
stack traceback:
	[C]: in function 'math.floor'
	C:\Program Files\CorsixTH\Lua\map.lua:60: in method 'getRoomId'
	C:\Program Files\CorsixTH\Lua\world.lua:2270: in method 'getRoom'
	C:\Program Files\CorsixTH\Lua\room.lua:75: in method 'getEntranceXY'
	C:\Program Files\CorsixTH\Lua\room.lua:692: in upvalue 'tryMovePatient'
	C:\Program Files\CorsixTH\Lua\room.lua:754: in method 'tryToFindNearbyPatients'
	C:\Program Files\CorsixTH\Lua\room.lua:554: in field 'onHumanoidLeave'
	C:\Program Files\CorsixTH\Lua\rooms\gp.lua:199: in method 'onHumanoidLeave'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:352: in field 'on_next_tile_set'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:219: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...

Hope it helps!
(NB: If just rebuilding the room doesn't work, try rebuilding the following first: Pharmacy (near research lab), cardio, staff room (both))

**Comment by Brainsample** [comment]
Hi Lewri,

Hmmm, did you get that error by rebuilding the GP offices one by one, or all together?
It does looks like this is a different problem, deserving its own bug report.

=======

By the way, if you want to help test the new function I made, here are some simple steps. No coding skills required. :) The first step is optional.

- Google, download and install "notepad++" , it is an excellent text editor.
- Install CorsixTH for a second time, but not in the folder "Program Files", or windows will annoy you to pieces.
- In your new installation folder, find and open the file "..\lua\room.lua" in notepad++
- Find the function "Room:deactivate()"
- Using the magic power of copy and paste, replace the original function with the block of code from my previous comment.
- Save the file, start your test-client.

This won't affect your original installation of CorsixTH at all. Just remember that saved games made with an altered client may not be compatible with the official version. It's always a good idea to save those games with a name like "test 1104" , so you can tell them apart.

**Comment by lewri** [comment]
Yeah I have completely lost the save now for any reference (though, the autosave I uploaded might work from earlier). Just clicking 'X' once on editing the GP Office caused this bug. After I completely rebuilt the 4 GP Offices the problem above did stop, for a while.

I'll make a new report if needed, when I can. Thanks for instructions on testing out the code!
