### ISSUE TITLE
Reflexion/Idea3 not deactivated after placing second doctor in GP

### ISSUE THREAD

**Issue by Brainsample** [CorsixTH/CorsixTH#1106]
Repro:
- Find a GP office where a doctor is treating a patient.
- Pick up and place another doctor in the room.

Bug observed: The original doctor walks out the door with "Reflexion" or "Idea3" still active.
# 

Usually, the moods are deactivated in 

``` lua
function GPRoom:onHumanoidLeave(humanoid)
  -- Reset moods when either the patient or the doctor leaves the room.
  if self.staff_member then
    self.staff_member:setMood("idea3", "deactivate")
    self.staff_member:setMood("reflexion", "deactivate")
  end

```

But the doctor who is leaving is not the staffmember anymore, so it doesn't work.
(Unrelated: A leaving handyman can deactivate the mood too soon)
# 

Here's a possible fix, just deactivate everyone's mood for simplicity:

``` lua
function GPRoom:onHumanoidLeave(humanoid)
  -- Reset moods when either the patient or a doctor leaves the room.
  if humanoid.humanoid_class ~= "Handyman" then
    for staff, _ in pairs(self.humanoids) do
      staff:setMood("idea3", "deactivate")
      staff:setMood("reflexion", "deactivate")
    end
  end

```

CorsixTH v0.60

**Comment by TheCycoONE** [comment]
Couldn't we use humanoid:setMood here instead of looping over the staff, since that is the humanoid that is leaving?

**Comment by TheCycoONE** [comment]
Disregard the previous, I wasn't thinking about patients leaving.
