### ISSUE TITLE
Patient gets cured in diagnosis room

### ISSUE THREAD

**Issue by Brainsample** [CorsixTH/CorsixTH#1108]
This is not a severe bug, but it does look a bit strange. Repro:

- Load  [guesscure.zip](https://github.com/CorsixTH/CorsixTH/files/344674/guesscure.zip)
- Look at the patient's treatment history: GP, ward, GP.
- Verify the patient is heading for General Diagnosis.
- Edit General Diagnosis.
- Let the game run a few ticks.

Observe: The patient is diagnosed with The Squits because of the "guess cure" rule.
The patient starts walking towards Pharmacy.

- Stop editing General Diagnosis.

Bug observed: The patients goes to General Diagnosis, where he is cured.

Expected behaviour: The patient keeps going to Pharmacy to get cured.

CorsixTH v0.60

**Comment by Alberth289346** [comment]
Yep, lots of internal book-keeping and callbacks triggering at the wrong moment making messes. I'd be +1 for removing what's possible.

**Comment by Brainsample** [comment]
As it turns out, this is easy to fix.
Here is the point where the cure just has been guessed:

CorsixTH v0.6 seek_room.lua line 177:
```lua
    humanoid:setDiagnosed(true)
    if humanoid:agreesToPay(humanoid.disease.id) then
      humanoid:queueAction({
        name = "seek_room",
        room_type = humanoid.disease.treatment_rooms[1],
        treatment_room = true,
      }, 1)
    else
      humanoid:goHome("over_priced", humanoid.disease.id)
    end
```

The goHome() branch already cleans all callbacks.
All that's needed is a clean up line in the agreesToPay() branch:

```lua
    humanoid:setDiagnosed(true)
    if humanoid:agreesToPay(humanoid.disease.id) then
      humanoid:unregisterRoomBuildCallback(action.build_callback)
      humanoid:queueAction({
        name = "seek_room",
        room_type = humanoid.disease.treatment_rooms[1],
        treatment_room = true,
      }, 1)
    else
      humanoid:goHome("over_priced", humanoid.disease.id)
    end
```

And the patient will keep walking towards the treatment room.

**Comment by TheCycoONE** [comment]
This looks right to me.

**Comment by Alberth289346** [comment]
The build callback has protection against going to the wrong room, line 247:
```` lua
-- So the room that we're going to is not actually the room we waited for to be built.
-- Example: Will go to ward, but is waiting for the operating theatre.
-- Clean up and start over to find the room we actually want to go to.
````
Also, there is a ``remove_callback``, doesn't that one need to be fixed too?

**Comment by Brainsample** [comment]
Indeed, those callbacks quickly turn into a maze.

```lua
        print(room.room_info.id, action.room_type, action.room_type_needed) -- Debug line
        local found = false
        if room.room_info.id == action.room_type then
          found = true
        elseif room.room_info.id == action.room_type_needed then
          
          -- So the room that we're going to is not actually the room we waited for to be built.
          -- Example: Will go to ward, but is waiting for the operating theatre.
          -- Clean up and start over to find the room we actually want to go to.
          TheApp.ui.bottom_panel:removeMessage(humanoid)
          humanoid:unregisterRoomBuildCallback(build_callback)
          humanoid:unregisterRoomRemoveCallback(remove_callback)
```

The output of this added debug line is: general_diag  general_diag nil
So the cleanup lines are never executed, in this case.

=======

Unregistering the remove_callback as well seems like a good idea.
However, when we do that we get a warning:
```lua
    humanoid:setDiagnosed(true)
    humanoid:unregisterRoomBuildCallback(action.build_callback)
    humanoid:unregisterRoomBuildCallback(action.remove_callback)
    if humanoid:agreesToPay(humanoid.disease.id) then
      humanoid:queueAction({
        name = "seek_room",
        room_type = humanoid.disease.treatment_rooms[1],
        treatment_room = true,
      }, 1)
```
"Warning: Trying to remove nonexistant room build callback(function: 0D9EF088) from humanoid (table: 0B974CB0)"

**Comment by TheCycoONE** [comment]
The lines around 245 in the build callback are for a different case. In that case we are waiting indirectly for a room (we can't go to room_type until room_type_needed is built). Once room_type_needed is built we continue with the original goal of going to room_type.

In this case we are waiting for room_type because we have not been diagnosed yet, but our diagnosis is over the guess threshold and there is none of room_type available so we don't wait for it to be built at all, we go to the treatment room instead.

I haven't sorted out the remove callback yet.

**Comment by Brainsample** [comment]
Aha, the problem with unregistering the remove_callback was that I used the wrong function!
This doesn't show a warning:

```lua
    humanoid:unregisterRoomBuildCallback(action.build_callback)
    humanoid:unregisterRoomRemoveCallback(action.remove_callback)
```

The absence of a warning must mean that something is being removed. :)
