### ISSUE TITLE
Vip rating computation on average queue length is incorrect

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1115]
In the VIP evaluation code, the queue length is summed over all non-exploded rooms in the world, and then divided by the number of existing rooms in the world.

Clearly this is not how you would compute queue length, it should not take exploded rooms into account at all (number of existing rooms includes them).

Secondly, the VIP is evaluating one hospital only, so only rooms of the visited hospital should be taken into account. (Of course in single player, this makes no difference as there are no other hospitals)

**Comment by MarkL1961** [comment]
That sounds more like a maintenance efficiency check.  Percentage of rooms destroyed being high suggests poor overall maintenance.  However with earthquakes being over;y strong that would not be a fare thing to evaluate on any way.

On the second point, I think you'll find lots of places where more than the players hospital was not taken into account and will need changing once multi-player becomes an option.  Some are noted above the functions.

**Comment by Alberth289346** [comment]
Comments suggest it measures average queue length. Since exploded rooms have 0 queue length, the average decreases if you have many exploded rooms.

Line 301 CorsixTH/Lua/entities/vip.lua counts queues for non-exploded rooms, line 309 then divides by all rooms, including the exploded rooms.

It's fine to name it maintenance efficiency or whatever, but then the comment is wrong.


I am well aware of not properly handling multiple hospitals all throughout the code, but if we ever want multiplayer, they must be found and fixed at some time, and I see no reason not to start with that now, fixing what you encounter.
