### ISSUE TITLE
OpenGL mode is very slow and glitchy (GTX 560)

### ISSUE THREAD

**Issue by katastic** [CorsixTH/CorsixTH#1126]
I just installed the newest version, and tried OpenGL mode. When zooming out, it gets very lagging (~.5-1.0 FPS) and the background "black" is improperly cleared leaving glitched old pixels. Also, in mid-range zoom, the texture appears to change (or is subsampled to a significantly different luminance) for grass.

See picture:

http://i.imgur.com/mHPMKQu.png

OpenRCT2-0.0.5.0-develop-76043d4-windows-win32.exe
Windows 7, 64-bit
OpenGL
1080p (but set to windowed in a smaller subset) -- Problem occurs regardless of resizing window.
Window Scale Factor 1.00

Drawing Engine 
  software -- No problem
  Software (hardware ...) (can't read the rest) -- No Problem
  OpenGL -- problem occurs

Hardware
   AMD FX-8370
   32 GB RAM
   nVidia GTX 560 SE

**Comment by katastic** [comment]
One last note. The final screen in the image doesn't indicate the proper FPS for the last zoom because the screenshot was taken quickly. If left zoomed out, the average FPS goes between 2 and 5. If fullscreened at 1080p, it goes down to 1.

**Comment by MarkL1961** [comment]
Interesting that the screenshots are for a different game!

**Comment by katastic** [comment]
OH GOSH DARN IT.

I had both githubs open and posted to the wrong one.

I can't stop laughing at myself.

**Comment by katastic** [comment]
That being said, it's a valid report for a game, and I expect changes soon.

**Comment by MarkL1961** [comment]
I'll close this and you can post an issue under the right game then

**Comment by katastic** [comment]
I was joking. Have a good night.

**Comment by MarkL1961** [comment]
I know, and it's morning here 

cya

**Comment by maki-chan** [comment]
And one final note from my humble self: I didn't know there was a project like OpenRCT, I love the old RCT games. At least, it brought my attention to those projects ;)

**Comment by MarkL1961** [comment]
@maki-chan   A lot of projects out there for old classics OpenTTD (transport tycoon) is another and Return to the Roots if you liked settlers 2
