### ISSUE TITLE
Level 10 should not have earthquakes

### ISSUE THREAD

**Issue by willsv** [CorsixTH/CorsixTH#1128]
In almost every level I've had most of my rooms destroyed by huge earthquakes. It seems that they are too frequent and too strong.

Also, I've read that in Eggsenham (level 10) on the original TH there were no earthquakes but I had the same problem.

Best.

**Comment by TheCycoONE** [comment]
Possibly related to #550 ?

**Comment by TheCycoONE** [comment]
I believe you are right about level 10. If you don't mind I'd like to make this issue focus on that, rather than the perception of being overly violent (possibly related to #550)

**Comment by TheCycoONE** [comment]
Related to #296

**Comment by willsv** [comment]
What he is referring to is to the screen movement, which is not quite the same as I was saying.
When I say "strong" i mean in the way it affects the machines and how it wipes out half my rooms, and not just screen movement.

**Comment by TheCycoONE** [comment]
Okay. Addressing #296 by removing random occurrence earthquakes would make the frequency match the original game and fix the level 10 problem.

The actual strength is difficult to determine exactly - my understanding is that it isn't consistently too strong. In the original game earthquakes were a big problem - once you got an earthquake warning you had to actually click through your machines and make sure they were near max strength or they would get wiped out in later levels. It is possible that our upper range is too high. I still want to make this about the easier issue, then address balance in a new issue afterwards if necessary after.

**Comment by willsv** [comment]
Makes sense, thanks!

**Comment by Tristesseract** [comment]
Hi,
Eggsenham Level 10 should not have earthquakes. I ran 25 years of game time on the gog version to confirm.

Thanks

**Comment by TheCycoONE** [comment]
I believe this is fixed already by #1139
