### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by mmcnicholas47** [CorsixTH/CorsixTH#1134]
#### Describe the issue

When I try to start I get this error message. Not sure how to fix it. I have GOG and Origin versions. Old Corsix worked fine updated and got this.  http://prntscr.com/corm95 http://prntscr.com/cormez. Sounds like I might have to move some files around. Can anyone help?
#### System Information

**CorsixTH Version:** \* 0.6*

**Operating System:** _Windows 10_

**Comment by wolfy1339** [comment]
As per the release info, 
> Note: CorsixTH 0.60 for Windows requires the Visual Studio 2015 Redistributable which is not included in the installer. This is not the same version that was required for CorsixTH 0.50’

**Comment by mmcnicholas47** [comment]
I did install that as well - or at least I think I did. Should I reinstall it and see If that does the trick?

**Comment by TheCycoONE** [comment]
That is definitely the redistributable issue so yes. Maybe you installed the   wrong one e.g. 32 vs 64 bit

**Comment by TheCycoONE** [comment]
The installer for future versions will tell the user to download the redistributable if they do not have it.
