### ISSUE TITLE
Death - is it working correctly?

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1165]
Load the attached save, cancel buying items and focus on the pharmacies.
Last invis emergency enters, takes the cure and you hear the boo, advisor pops up and mentions that you have killed a patient.  The patient though shows the cured icon and is cured.  At this point pause the game and take a look round, there are not many places to be cured or die so it won't take long.
If it wasn't him who did die and why can't you see it?
I have also seen in another level where a patient falls down to die, gets up and walks out!  The above happens every time with this save, couldn't get a save to replicate the second observation though
https://www.dropbox.com/s/7nqjf23yew91hkg/Autosave2.sav?dl=0

**Comment by mugmuggy** [comment]
Just took a look at this one. Kill 'em twice
https://github.com/CorsixTH/CorsixTH/blob/63afae1554a2abeba225d5865f5ea77b18e73c78/CorsixTH/Lua/hospital.lua#L1286-L1291

Already dead patients from emergency_patients will retrigger the patient:die() call upon end of emergency as they aren't in a room - like patients waiting to be treated which is the intent obviously here. Maybe we just need to check `not patient.dead` as well.

**Comment by TheCycoONE** [comment]
Thanks @MarkL
