### ISSUE TITLE
Dynamic information showing incorrect information

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1173]
Dynamic information is not always correct.

In this case it should not be showing diagnosis progress it should be something like fed up and going home  
![fedup-going home](https://cloud.githubusercontent.com/assets/4965487/20983667/39fc44b2-bcb5-11e6-8b69-a8ef86d396fb.png)

**Comment by MarkL1961** [comment]
This time it says he is queuing for GP office and did so when he was sat on bench, but he is in x-ray!

![queuing for gp office](https://cloud.githubusercontent.com/assets/4965487/20984152/025ae9e4-bcb7-11e6-8908-2f4164a8bc00.png)

**Comment by MarkL1961** [comment]
Now he is going home for some reason, but it still says diagnosis progress.
![going home](https://cloud.githubusercontent.com/assets/4965487/20984303/8b05c8e0-bcb7-11e6-9682-89e3f46573d2.png)

**Comment by TheCycoONE** [comment]
So is it a matter of simply not updating often enough?

**Comment by MarkL1961** [comment]
How often does it update?
I thought it was more or less instant, but I started to notice it showing the wrong information so started taking screenshots

**Comment by TheCycoONE** [comment]
It is instant, but not necessarily every action updates it.

**Comment by MarkL1961** [comment]
Interesting, they should do.  Especially things like going home as you need to know why

**Comment by MarkL1961** [comment]
![cured and fed up](https://cloud.githubusercontent.com/assets/4965487/21468559/cf99956c-ca0f-11e6-8b31-93c2284ccc2f.png)
Spotted someone who is cured and also fed up and leaving, I don't think this should be possible.  You can leave at any point up to being treated and then you either leave cured or dead

**Comment by mugmuggy** [comment]
This last issue, I just seen happen when I was mucking about so took a deeper dive - World:onEndDay calls Patient:tickDay.

It has this bit of code
https://github.com/CorsixTH/CorsixTH/blob/a549a809217a135d51214eba8f33d263178d90e6/CorsixTH/Lua/entities/patient.lua#L637-L646

I'm guessing as onEndDay gets called in World:onTick, whilst the treatment in this case Pharmacy is underway when health meets that criteria and that random value condition is also true. This sets the mood to exit.

The treatment is finished in the Room:dealtWithPatient is being called updating the cured state etc. When it calls Patient:goHome again, its already set to the onEndDay/tickDay mood and not updating the value as the patient is already going_home.

https://github.com/CorsixTH/CorsixTH/blob/a549a809217a135d51214eba8f33d263178d90e6/CorsixTH/Lua/entities/patient.lua#L526-L533

It doesn't make much sense for a patient to leave a diagnosis/treatment room. Maybe only allow them to make that decision outside a room.
`if not self:getRoom()  and math.random(1,30) == 1 then`

**Comment by mugmuggy** [comment]
With 1609 we have a save we can refer to the state, though I have plenty of others with epidemics, I didn't really pay attention to it.

The if isn't selective enough initially, and non infected patients fall into the first consequent, thus are then excluded on the nested if condition and excluded by the nature that you had to be infected to be vaccinated on the else if condition and dynamic info is not set.

Until the fax is sent with the outcome of the epidemic, the coverup_in_progress is true and doesn't allow the updating of non-infected dynamic info. The save in 1609 captures the end of an epidemic. Things return to normal after the fax, and break again, on the next one.

https://github.com/CorsixTH/CorsixTH/blob/3de736a9d92b5e6411678fad7eac4e21a035e9fe/CorsixTH/Lua/entities/humanoids/patient.lua#L976-L988
