### ISSUE TITLE
diagnosis procedure sliders getting stuck in hospital policy screen (F9) 

### ISSUE THREAD

**Issue by jvs3** [CorsixTH/CorsixTH#1174]
#### Describe the issue

In the hospital policy screen (F9) under diagnosis procedure when the 'send home' and 'guess at cure' slider are close the 'send home' slider can no longer be moved. As the 'guess at cure' slider can only be moved to the right of the 'send home' button this results in the 'send home' slider getting stuck if both sliders are moved to the right.

#### Expected Behavior

Both sliders should be moveable even if they are in the same spot.

#### System Information
**CorsixTH Version:** 2fe2658da038a7537768c6b5e06cf03991715a52

**Operating System:**  Linux Debian Jessie

**Theme Hospital Version:** CD

**Comment by MarkL1961** [comment]
Cannot replicate this.
One slider is meant to stop the other so they cannot pass each other.
I move them together and can then move them back

**Comment by jvs3** [comment]
I attached some savegames. Stuck sliders.sav is when both sliders are to the far right, Stuck sliders 2.save is when both sliders are not all the way to the right. In both situations I can no longer move the 'send home' slider. When the sliders are both all the way to the right I can also no longer move the ' guess at cure' slider.

[Stuck sliders 2.sav.zip](https://github.com/CorsixTH/CorsixTH/files/638445/Stuck.sliders.2.sav.zip)
[Stuck sliders.sav.zip](https://github.com/CorsixTH/CorsixTH/files/638444/Stuck.sliders.sav.zip)

**Comment by MarkL1961** [comment]
I can replicate this if both are moved to 100%

**Comment by MarkL1961** [comment]
Tested against 0.30 and cannot replicate.  From version 0.50rc I can replicate it.
I don't have a version in between, but could download one if needed

**Comment by Alberth289346** [comment]
It's a matter of having bad luck, which apparently doesn't happen often.
I managed to reproduce it once with the "2" save game, but trying a second didn't fail again.
