### ISSUE TITLE
Error at launching (demo AND origin version)

### ISSUE THREAD

**Issue by Kap0yuu** [CorsixTH/CorsixTH#1176]
#### This is an error from Corsix 0.60 right after localizing HOSP files from demo or the Origin version. (I'm running on Mac OS X 10.12.1)

This is what Corsix tells me : 

http://img11.hostingpics.net/pics/128972Capturedcran20161212174838.png

I did everything like the detailed section describes.

**Comment by TheCycoONE** [comment]
What OSX build were you using, there is no official release for OSX, but people have reported success with brew.

**Comment by TheCycoONE** [comment]
Closing to to lack of feedback.
