### ISSUE TITLE
Diagnosis progress bar should not exceed 100%

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#1177]
This one speaks for itself
![diag progress bar](https://cloud.githubusercontent.com/assets/4965487/21113451/8f0071fa-c0a1-11e6-9da9-8f8d7ad053c4.png)
Even though more diagnosis rooms have been used than needed I don't believe the progress bar should exceed 100% and leave the dynamic info area

**Comment by Alberth289346** [comment]
Just expressing it is super-extra sure we got a diagnosis :p 
You are right of course, it should be limited to 100%.
