### ISSUE TITLE
Bins are not removed when a room is removed

### ISSUE THREAD

**Issue by fusionstream** [CorsixTH/CorsixTH#1180]
#### Describe the issue
When you edit the room (after it has been built), then edit it and keep on clicking 'X' until the dialogue where you can either confirm the blueprint or destroy the room completely, the bin will remain there.

#### System Information
**CorsixTH Version:** 0.60
**Operating System:** Windows 10 Pro
**Theme Hospital Version:** CD

In trying to get a screenshot to paste here, I've found that this issue is not readily reproducable (it happened numerous times especially with GP Office but when I tried to reproduce with another GP's office, the bin was removed. In the event I come across it again, what should I do? Save the game?

**Comment by MarkL1961** [comment]
Could it be that you got the bin from corridor items and placed it in a room after it was built?

**Comment by MarkL1961** [comment]
Are you sure the bin was in the room, could it have been on the outside wall in the corridor?

I have tried various ways to replicate your observation and can't.

**Comment by fusionstream** [comment]
Definitely created when the room was created. Also it is evidently more than just bins. Have just seen radiators and fire extinguishers too. I've had it happen 3 more times so far, I have 1 screenshot and 2 phone camera shots... I will save the game if I come across it again.

**Comment by MarkL1961** [comment]
If you have the auto save file from the month before we can test that

**Comment by fusionstream** [comment]
![20161216_003806](https://cloud.githubusercontent.com/assets/3389188/21249558/d95bed08-c379-11e6-979f-58d929e862db.jpg)
![20161216_010442](https://cloud.githubusercontent.com/assets/3389188/21249559/d964b8a2-c379-11e6-9a31-e8754b784948.jpg)
![image 1](https://cloud.githubusercontent.com/assets/3389188/21249573/ea068c08-c379-11e6-86e8-c0635f121817.png)

My autosaves are all after this event. I will try now to get more evidence.

**Comment by mugmuggy** [comment]
I was able to reproduce this but with #221 being resolved now, it shouldn't be possible.

The bit of code here explains it
https://github.com/CorsixTH/CorsixTH/blob/a549a809217a135d51214eba8f33d263178d90e6/CorsixTH/Lua/dialogs/edit_room.lua#L604-L611
When a radiator/extinguisher/bin was on the door tile and the door object was associated with the tile in the room, the door was found first and breaking out of the while loop and leaving the other object behind.

**Comment by mugmuggy** [comment]
Is resolved with fixes in #221.
