### ISSUE TITLE
FPS limit disabled on first run after install

### ISSUE THREAD

**Issue by brendan221** [CorsixTH/CorsixTH#1182]
#### Describe the issue
After installing the game, I was surprised to see an FPS counter and more so when I realised the FPS wasn't capped at all. I know now that there actually is a limit, only it's disabled when track_fps is true. But of course after installing this game for the first time, track_fps is false in my config.txt file.

If I exit the game and start it again the issue is gone, the behaviour is as expected for track_fps = false.

#### Steps to Reproduce
1. Install CorsixTH using the installer found here:
https://github.com/CorsixTH/CorsixTH/releases/download/v0.60/CorsixTHInstaller.exe
The path to the theme hospital files must be provided during installation or the issue does not occur. To repeat the issue, simply delete the CorsixTH folder in AppData and run the installer again. Ticking the _Start CorsixTH 0.60_ checkbox has no effect on the issue.

2. Start the game and begin the campaign with default settings. The FPS, Lua memory usage, and entity count is shown in the dynamic information bar and the FPS limiter is disabled.

#### Expected Behavior
No FPS tracker, and FPS limiter enabled.

#### System Information
**CorsixTH Version:** 0.60

**Operating System:** Windows 10

**Theme Hospital Version:** GOG.com

#### config.txt (I couldn't find gamelog.txt)
```
fullscreen = true
width = 1920
height = 1080
language = [[english]]
audio = true
free_build_mode = false
play_sounds = true
sound_volume = 0.5
play_announcements = true
announcement_volume = 0.5
play_music = true
music_volume = 0.5
prevent_edge_scrolling = false
adviser_disabled = false
scrolling_momentum = 0.8
twentyfour_hour_clock = true
check_for_updates = true
warmth_colors_display_default = 1
grant_wage_increase = false
movies = true
play_intro = true
allow_user_actions_while_paused = false
volume_opens_casebook = false
alien_dna_only_by_emergency = true
alien_dna_must_stand = true
alien_dna_can_knock_on_doors = false
disable_fractured_bones_females = true
enable_avg_contents = false
theme_hospital_install = [[E:\Brendan\Games\Theme Hospital\HOSP]]
unicode_font = nil -- [[X:\ThemeHospital\font.ttc]]
savegames = nil -- [[X:\ThemeHospital\Saves]]
levels = nil -- [[X:\ThemeHospital\Levels]]
use_new_graphics = false
new_graphics_folder = nil -- [[X:\ThemeHospital\Graphics]]
screenshots = nil -- [[X:\ThemeHospital\Screenshots]]
audio_mp3 = nil -- [[X:\ThemeHospital\Music]]
audio_frequency = 22050
audio_channels = 2
audio_buffer_size = 2048
debug = false
idehost = nil
ideport = nil
idekey = nil
transport = nil
platform = nil
workingdir = nil
track_fps = false
zoom_speed = 80
scroll_speed = 2
shift_scroll_speed = 4
player_name = [[brend]]
```

**Comment by MarkL1961** [comment]
I can't replicate this following your instructions.  However I have seen this behaviour at times and have never been able to pinpoint why it happens or why it then stops

**Comment by Alberth289346** [comment]
Corsix/Src/sdl_core.cpp sets "track_fps = true;" in "init", see line 81 (or search for track_fps in the file).
Perhaps the Lua value is not copied to the C++ code if there is no config file?

**Comment by TheCycoONE** [comment]
Probably the point is that we should have a vsync or fps setting independent of track_fps.

**Comment by mugmuggy** [comment]
I came across this issue doing the default mouse capture, if there was a new option to be persisted and, in this case capture_mouse, in the config file, the first time it ran track_fps behaivour is enabled. Likewise if no file exists.

**Comment by lewri** [comment]
Are we still currently seeing this? Personally I don't remember seeing this on first run when installing 0.63 a while back.

**Comment by TheCycoONE** [comment]
I don't see this when I blow away my config. `sdl_core` still initializes it to true, but it also initializes limit_fps to true and track_fps doesn't do anything while limit_fps is on.
