### ISSUE TITLE
Buttonup Handler Error When Editing Ward

### ISSUE THREAD

**Issue by nbLurkerAbove** [CorsixTH/CorsixTH#1183]
#### Describe the issue
When trying to move the ward, my mouse stopped clicking. This occurred after clicking the ward with the edit tool.
Related: The nurse does not leave the room to allow you to edit, but the room still will not be editable if the nurse is removed beforehand.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. *Attempt to edit the ward*

3. *Try clicking any button*

#### Save Game
https://1drv.ms/u/s!AgojhGzFsyVYkVEz5GGfxtGEoyms

#### System Information
**CorsixTH Version:** *0.60*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *CD*

#### Gamelog.txt
```
Created game with savegame version 111.
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 00000297C97AA0F0) from humanoid (table: 00000297C74901E0).
Warning: Trying to remove nonexistant room remove callback (function: 00000297C9D4CD50) from humanoid (table: 00000297C74901E0).
Warning: Trying to remove nonexistant room build callback (function: 00000297C9CFE5F0) from humanoid (table: 00000297C9642C60).
Warning: Trying to remove nonexistant room remove callback (function: 00000297B7C551F0) from humanoid (table: 00000297C9642C60).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:59: bad argument #2 to 'findIdleTile' (number expected, got nil)
stack traceback:
	[C]: in method 'findIdleTile'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:59: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:656: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:307: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:647: in method 'setNextAction'
	C:\Program Files\CorsixTH\Lua\room.lua:103: in field 'callback'
	C:\Program Files\CorsixTH\Lua\room.lua:931: in method 'deactivate'
	C:\Program Files\CorsixTH\Lua\room.lua:938: in method 'tryToEdit'
	C:\Program Files\CorsixTH\Lua\game_ui.lua:540: in function <C:\Program Files\CorsixTH\Lua\game_ui.lua:513>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>
```
#### Additional Information
Editing any other room works normally

**Comment by TheCycoONE** [comment]
Dumping the humanoids_enroute for the room reveals the issue to be a patient with no tile_x/tile_y. Unfortunately at present that invariant is badly enforced. We may just have to add more checks until we can get to the true cause of the issue.

I should note that this entity does not show up in the world.entities list. It's likely that they left the hospital but were not cleaned up everywhere (a common problem at the moment).

```
ward
class:Standard Male Patient x:52 y:87
class:Standard Female Patient x:66 y:84
class:Standard Male Patient x:nil y:nil
```

**Comment by mugmuggy** [comment]
Looks like a recurrence of #133/#497. That patients last trip was to the Research Dept.

**Comment by TheCycoONE** [comment]
Looks the same to me.
