### ISSUE TITLE
Game Crash in Teaching Mode, Reproduceable

### ISSUE THREAD

**Issue by lymelement** [CorsixTH/CorsixTH#1184]
Game crashed after placing a doctor in the general diagnosis room in the teaching mode. This bug can be reproduced.

#### Steps to Reproduce
1. Start a new game;
2. Turn on 'Teach Mode';
3. Enter the 'Teach Mode'. After placing a doctor in the general diagnosis room, the game will not be responding.

#### System Information
CorsixTH Version: 0.60

Operating System: Windows 10

Theme Hospital Version: Download from some Chinese gaming site, not sure about the version. Sorry.

**Comment by MarkL1961** [comment]
Could it be that you are using a pirated copy of theme hospital?
I have just tried to reproduce this with Free Build mode turned on and did not have any crash

**Comment by lymelement** [comment]
Maybe... But where can I find the genuine Theme Hospital?
Thanks.

**Comment by MarkL1961** [comment]
Try gog.com 
Tried with tutorial mode and I don't get a crash there either although building general diagnosis is not part of the tutorial.

Read this it could answer any questions you may have
https://github.com/CorsixTH/CorsixTH/wiki/Getting-Started

**Comment by TheCycoONE** [comment]
Pirated versions are unsupported
