### ISSUE TITLE
Module 'lfs' not found 

### ISSUE THREAD

**Issue by andoruB** [CorsixTH/CorsixTH#1185]
I'm getting this whilst trying to run the executable:

```
~/bin/CorsixTH$ ./CorsixTH 
An error has occurred in CorsixTH:
./Lua/strict.lua:66: module 'lfs' not found:
	no field package.preload['lfs']
	no file '/usr/local/share/lua/5.3/lfs.lua'
	no file '/usr/local/share/lua/5.3/lfs/init.lua'
	no file '/usr/local/lib/lua/5.3/lfs.lua'
	no file '/usr/local/lib/lua/5.3/lfs/init.lua'
	no file '/usr/share/lua/5.3/lfs.lua'
	no file '/usr/share/lua/5.3/lfs/init.lua'
	no file './lfs.lua'
	no file './lfs/init.lua'
	no file '/usr/local/lib/lua/5.3/lfs.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.3/lfs.so'
	no file '/usr/lib/lua/5.3/lfs.so'
	no file '/usr/local/lib/lua/5.3/loadall.so'
	no file './lfs.so'
stack traceback:
	[C]: in upvalue 'fn'
	./Lua/strict.lua:66: in function 'require'
	./Lua/app.lua:23: in main chunk
	[C]: in function 'persist.dofile'
	./CorsixTH.lua:56: in function 'dofile'
	./CorsixTH.lua:108: in main chunk
	[C]: in ?
```

I have installed the luarocks package:

```
$ apt policy luarocks 
luarocks:
  Installed: 2.2.0+dfsg-2
  Candidate: 2.2.0+dfsg-2
  Version table:
 *** 2.2.0+dfsg-2 500
        500 http://debian.mirror.linux.de unstable/main amd64 Packages
        500 http://debian.mirror.linux.de unstable/main i386 Packages
        100 /var/lib/dpkg/status
```

But it still refuses to budge. I've installed all the requirements, except Timidity and LuaSocket.
I'm using Debian Sid amd64, CorsixTH source version is commit 060890f off this git repo, and the Lua version used is 5.3. Any ideas what I could've done wrong?

**Comment by Alberth289346** [comment]
luarocks is an install system for lua, like apt-get is one for packages. You still need to install lfs.
My Fedora system has lfs in the package system, as "lua-filesystem-1.6.3-3.fc24.x86_64". Maybe debian also has such packages.

**Comment by andoruB** [comment]
Whoops, for whatever reason after reading the compiling instructions, I came out with the assumtion that both lfs and LPeg are components of luarocks, silly me. So it's a bit like python-apt. And indeed, debian supplies the lua-filesystem(-dev) and lua-lpeg(-dev) packages.
