### ISSUE TITLE
[Request?] Fluidsynth support

### ISSUE THREAD

**Issue by andoruB** [CorsixTH/CorsixTH#1186]
Not sure if this actually possible within CorsixTH, but I wanted to be able to use external (software, not hardware!) synths, in my case QSynth (which is really just an excellent Qt interface for Fluidsynth), and be able to select custom soundfonts, and change the way the music is "rendered". So far I took a look into the config file, but it seems there's no actual option for using an external synth, or for outputting the MIDI messages to a certain MIDI port.

**Comment by Alberth289346** [comment]
I am not sure, but issue #1160 seems to discuss this.

**Comment by andoruB** [comment]
Yup, it does, but no satisfactory answer is available :(  
Also, I don't think it's possible to set a default synth under Linux. I think it's all done through midi ports.

**Comment by TheCycoONE** [comment]
According to https://www.libsdl.org/projects/SDL_mixer/ FluidSynth is supported, so it's just a matter of figuring out how to use it.

**Comment by TheCycoONE** [comment]
Looks like a compile flag. So you will need to build your own SDL Mixer or request your distro to use it.

**Comment by TheCycoONE** [comment]
You may also just need to set the SDL_SOUNDFONT environment variable as per the warning in gentoos https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/sdl-mixer/sdl-mixer-1.2.12-r4.ebuild

**Comment by andoruB** [comment]
Thanks, will try it out. In the meantime: would it be possible to use a different backend for MIDI output? One that might enable more flexibility?

**Comment by TheCycoONE** [comment]
@andoruB any update?

**Comment by TheCycoONE** [comment]
I use fluidsynth regularly on linux, by setting the `SDL_SOUNDFONTS` environment variable, i.e. in my `.profile` I have
`export SDL_SOUNDFONTS=/usr/share/soundfonts/FluidR3_GM.sf2`
