### ISSUE TITLE
System + Language + Engine

### ISSUE THREAD

**Issue by MHStrider** [CorsixTH/CorsixTH#1188]
![test](https://cloud.githubusercontent.com/assets/19584531/21545606/95a56798-cde1-11e6-8373-a57123720326.png)
![test](https://cloud.githubusercontent.com/assets/19584531/21545611/a66dcb1a-cde1-11e6-8b0b-f1d7179b44ba.png)

You can somehow Lua to make friends with cyrillic / russian?
This folder settings for screenshots, fonts and music. Folders contain Russian letters.

CorsixTH latest version, Windows 7 Home Premium, Theme Hospital of GOG.

**Comment by TheCycoONE** [comment]
You need to set the font to one that supports Cyrillic.

Open %APPDATA%\CorsixTH\config.txt and set ```unicode_font = C:\Windows\Fonts\ARIALUNI.TTF``` (or some other true type font that you have installed)

**Comment by MHStrider** [comment]
Changing only the visual part of the font. And icons "???" not disappear.
Now I read the forum, yet it seems that it's a little problem with the engine.

**Comment by tobylane** [comment]
Now when recreating this it changes the language to English. Do we want it to tell the user what they need?
