### ISSUE TITLE
Hospital file should be split

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1191]
The hospital (and also world) source files are way too large, so splitting them would be useful.
I tried unduplicating the staff name conversion function (world.lua:2294, drugcasebook.lua:183) to a new hospital_funcs.lua file. The code is quite trivial, getting the new file to be included in the system is not.

- It does not get picked up by itself for some reason, while all the class files do get picked up, or we wouldn't have all the classes available.
- Adding a "dofile" in Corsix (below the utility include) crashes on use due to missing _S global, although at the time of the call _S exists, or the program would not display any text.
- Adding a "dofile" in app crashes on meta-table and/or persistence magic during loading of the file

**Comment by lewri** [comment]
I believe you have started a little work on this Alberth289346 even if it may currently look different from original intent.
Or maybe I'm mistaking your player_hospital and ai_hospital work for this :)

**Comment by Alberth289346** [comment]
Yep, stabbing at it until you break yourself a way in :) 

What you can do is limited and costly though, with everything nailed down and the need to stay backwards compatible
