### ISSUE TITLE
CorsixTH Randomly crashed while the game was paused.

### ISSUE THREAD

**Issue by colinha667** [CorsixTH/CorsixTH#1194]
My game crashed randomly while I had the game passed for a few mins. All of a sudden, the Windows prompt to close the program came up and I had to close my game. Here are the steps in which the crashed occurred:

1. Hovering mouse over rooms after an announced research in game.
1. Paused the game for a few moments.
3. Windows encountered an error and needed to close while on the blue pause screen.

Here is the app data crash details below:

Source
CorsixTH.exe

Summary
Stopped working

Date
‎2/‎17/‎2017 9:59 PM

Status
Report sent

Description
Faulting Application Path:	C:\Program Files\CorsixTH\CorsixTH.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	CorsixTH.exe
Application Version:	0.0.0.0
Application Timestamp:	573903da
Fault Module Name:	ntdll.dll
Fault Module Version:	10.0.14393.479
Fault Module Timestamp:	5825887f
Exception Code:	c0000005
Exception Offset:	000000000002f7db
OS Version:	10.0.14393.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	6c9d
Additional Information 2:	6c9d3556297ed2dc3b988563d1e4eda9
Additional Information 3:	2bb5
Additional Information 4:	2bb5860b2683998fdca02ef6cef094b1

Extra information about the problem
Bucket ID:	d97c72a738704294531f290cb59fd19b (120655184823)

**Comment by TheCycoONE** [comment]
Is there any information in the gamelog.txt? Is the crash reproducible?

It looks like a driver crashed; whether that's a problem with CorsixTH, SDL, or the drivers themselves is hard to tell from this report.

**Comment by colinha667** [comment]
I can't seem to find the gamelog.txt. is it stored in the program files?

**Comment by TheCycoONE** [comment]
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file

**Comment by lewri** [comment]
No response, assume resolved
