### ISSUE TITLE
Game freezes after earthquake

### ISSUE THREAD

**Issue by lucasmr** [CorsixTH/CorsixTH#1199]
Using Windows 7 64.

stack traceback:
        C:\Users\Lucas\Downloads\CorsixTH\Lua\world.lua:589: in method 'tickEarthquake'
        C:\Users\Lucas\Downloads\CorsixTH\Lua\world.lua:1003: in method 'onTick'
        C:\Users\Lucas\Downloads\CorsixTH\Lua\app.lua:1005: in function <C:\Users\Lucas\Downloads\CorsixTH\Lua\app.lua:1002>
        (...tail calls...)
        C:\Users\Lucas\Downloads\CorsixTH\Lua\app.lua:906: in function <C:\Users\Lucas\Downloads\CorsixTH\Lua\app.lua:901>

Warning: No event handler for timer

Save file: http://filebin.ca/3FMoNG3xPI0g

**Comment by TheCycoONE** [comment]
If this was 0.60, earthquakes have been largely rewritten since then. Try the latest builds instead. Please include a version number in your tickets.

**Comment by lucasmr** [comment]
Happens on 0.60 and also on the latest dev build.

**Comment by MarkL1961** [comment]
Your save is from 0.60.  Here is the error message running this save after around one minute



---------------------------------------------------------------

Welcome to CorsixTH Trunk!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

`  Will not check for updates since this is the Trunk version.
Savegame version changed from 111 (v0.60) to 116 (Trunk). The save was created using 111 (v0.60)
Warning: loaded savegame version 117 (Trunk) in older version 116 (Trunk).
Savegame version changed from 111 (v0.60) to 116 (Trunk). The save was created using 111 (v0.60)
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:589: attempt to compare number with nil
stack traceback:
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:589: in method 'tickEarthquake'
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:1003: in method 'onTick'
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:1005: in function <C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:1002>
        (...tail calls...)
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:906: in function <C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:901>

Error in timer handler:
C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:589: attempt to compare number with nil
stack traceback:
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:589: in method 'tickEarthquake'
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\world.lua:1003: in method 'onTick'
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:1005: in function <C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:1002>
        (...tail calls...)
        C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:906: in function <C:\Users\Mark\Downloads\CorsixTH (c258bbf1 )\Lua\app.lua:901>
Warning: No event handler for timer   `

**Comment by lucasmr** [comment]
Well, I loaded the save on the latest dev build with the same results. Maybe it's not useful then?

**Comment by TheCycoONE** [comment]
Thanks for checking @MarkL1961 

I'll review the save game (likely tonight) to determine how it survived the 115 afterLoad logic in a bad state.

**Comment by MarkL1961** [comment]
I think it is connected to the decontamination room, which has two handy men and neither are repairing the machine.  As soon as it is Dec 4th the error is thrown.  Have tried to replace the machine and remove the handymen. but the room seems to be locked down.

**Comment by TheCycoONE** [comment]
@MarkL1961 I suspect you are right. The above pull request fixes a regression in the latest build, which I think @lucasmr will confirm results in a stack trace close to what he is seeing in 0.60.

**Comment by MarkL1961** [comment]
Whilst testing with the trunk version earthquakes have seemed to be much better.  The one thing I think that is still not right is the tremor, which seems to last as long as the quake.  I suspect it is lasting one day and if we are to match TH it should be less than that, perhaps the equivalent of an hour or 1 / 24th of a day.  Is that feasible, so many ticks rather than a day?  In TH the tremor is a quick jerk of the screen to warn you an earthquake is coming

**Comment by TheCycoONE** [comment]
There is a local variable in world.lua that controls the length. I was testing against the original when I made my changes but I don't remember exactly whether I matched the original or found it was determined by game speed. I think it had something to do with the fastest game setting. You can play with earthquake_warning_length and suggest a value you like.

**Comment by MarkL1961** [comment]
Okay, I will do some comparing with TH tp see if I can determine how long they lasted

**Comment by MarkL1961** [comment]
I have not compared with TH yet but a value of 5 seems to be about right.  Just enough to warn you an eEarthquake is coming and not too long that it damages your machines.
The save below is close to a tremor if you want to test it out with that value
https://www.dropbox.com/s/q4s7bwud58awu5j/tremor.sav?dl=0

**Comment by lewri** [comment]
As of 151 it seems the error in this save has changed to pathfinding... Not sure if we're straying away from the original issue now though:

```lua
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\world.lua:1593: bad argument #2 to 'findPath' (number expected, got nil)
stack traceback:
        [C]: in method 'findPath'
        Lua\world.lua:1593: in method 'getPath'
        Lua\humanoid_actions\walk.lua:400: in field '?'
        Lua\entities\humanoid.lua:534: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:618: in method 'queueAction'
        Lua\humanoid_actions\spawn.lua:78: in field '?'
        Lua\entities\humanoid.lua:534: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:634: in method 'finishAction'
        Lua\room.lua:784: in method 'crashRoom'
        Lua\entities\machine.lua:152: in method 'machineUsed'
        Lua\world.lua:644: in method 'tickEarthquake'
        Lua\world.lua:1020: in method 'onTick'
        Lua\app.lua:1140: in function <Lua\app.lua:1137>
        (...tail calls...)
        Lua\app.lua:1040: in function <Lua\app.lua:1035>

Error in timer handler:
Lua\world.lua:1593: bad argument #2 to 'findPath' (number expected, got nil)
stack traceback:
        [C]: in method 'findPath'
        Lua\world.lua:1593: in method 'getPath'
        Lua\humanoid_actions\walk.lua:400: in field '?'
        Lua\entities\humanoid.lua:534: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:618: in method 'queueAction'
        Lua\humanoid_actions\spawn.lua:78: in field '?'
        Lua\entities\humanoid.lua:534: in upvalue 'Humanoid_startAction'
        Lua\entities\humanoid.lua:634: in method 'finishAction'
        Lua\room.lua:784: in method 'crashRoom'
        Lua\entities\machine.lua:152: in method 'machineUsed'
        Lua\world.lua:644: in method 'tickEarthquake'
        Lua\world.lua:1020: in method 'onTick'
        Lua\app.lua:1140: in function <Lua\app.lua:1137>
        (...tail calls...)
        Lua\app.lua:1040: in function <Lua\app.lua:1035>
Warning: No event handler for timer
```

**Comment by lewri** [comment]
Further "fixing" the affected room Decontamination by resetting it (go back to placing door after picking up handymen) we still get some weird errors with staff being fired.
Though this appears to be just broken.. and probably doesn't happen now. And likely safe to disregard it:

```lua
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\entities\humanoid.lua:834: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in function 'next'
        Lua\entities\humanoid.lua:834: in method 'notifyOfStaffChange'
        Lua\hospital.lua:2353: in method 'notifyOfStaffChange'
        Lua\hospital.lua:1748: in method 'removeStaff'
        Lua\entities\humanoids\staff.lua:273: in method 'despawn'
        Lua\entities\humanoids\staff.lua:249: in method 'fire'
        Lua\entities\humanoids\staff.lua:191: in method 'checkIfWaitedTooLong'
        Lua\entities\humanoids\staff.lua:125: in method 'tick'
        Lua\world.lua:1065: in method 'onTick'
        Lua\app.lua:1140: in function <Lua\app.lua:1137>
        (...tail calls...)
        Lua\app.lua:1040: in function <Lua\app.lua:1035>
```

**Comment by TheCycoONE** [comment]
Too old to do anything useful with this i think. If people are still getting errors related to the newer earthquakes they can open a new issue.
