### ISSUE TITLE
Insane stuck patients near psychiatry and invisible soda machine

### ISSUE THREAD

**Issue by l29ah** [CorsixTH/CorsixTH#1206]
https://dump.bitcheese.net/files/sipamub/buggie.sav
ea0e6dfe1ab6444ddcd876a9b4fa2d78172c463d, Gentoo Linux, nothing interesting in the log.

**Comment by l29ah** [comment]
The soda machine is next to them but it turns visible only when someone uses it.

**Comment by mugmuggy** [comment]
I happened upon an invisible soda machine in #867 and that was on 0.50 and this one is post 0.60
