### ISSUE TITLE
Norwegian language update, april 2017

### ISSUE THREAD

**Issue by Grimdoc** [CorsixTH/CorsixTH#1212]
Attached file to be renamed to "norwegian.lua" (from *.lua.txt) and put in directory *\Lua\languages
Thanks.

[norwegian.lua.txt](https://github.com/CorsixTH/CorsixTH/files/922047/norwegian.lua.txt)

**Comment by TheCycoONE** [comment]
Thanks Grimdoc, I'll see about making a PR for this shortly
