### ISSUE TITLE
'Folders' menu renders values with default font

### ISSUE THREAD

**Issue by tiriana** [CorsixTH/CorsixTH#1218]
Despite I have custom font set, values of options in 'folders' menu are rendered with default font:

#### Steps to Reproduce
1. Set custom font
2. Enter Main menu -> settings -> Folders 

#### Actual Behavior
Values of settings are rendered with default font

#### Expected Behavior
Values of settings are rendered with custom font

#### System Information
**CorsixTH Version:** *0.60*

**Operating System:** *Ubuntu 16.04*

**Theme Hospital Version:** *CD*

#### Gamelog.txt
// file is empty
```
```

### Additional Info
![image](https://cloud.githubusercontent.com/assets/5216143/25673756/b2b428c4-3038-11e7-8a38-4c807eaec45f.png)

**Comment by wolfy1339** [comment]
Could you post the values in English

**Comment by tiriana** [comment]
@wolfy1339 

![image](https://cloud.githubusercontent.com/assets/5216143/25693766/6b841932-30ab-11e7-9b80-5db36cf4ef8e.png)

**Comment by TheCycoONE** [comment]
By the default font, you mean whatever is specified in `config.txt` or always arialuni?

**Comment by tiriana** [comment]
I mean that the values (on the right) are rendered by the orginial font despite unicode_font is specified.

**Comment by mugmuggy** [comment]
Option labels are set with no font specified to the lower level functions
:setLabel(_S.folders_window.screenshots_label):setTooltip(_S.tooltip.folders_window.screenshots_location)

But the values are set with the 'built_in' font on the values
local built_in = app.gfx:loadBuiltinFont()

self.screenshots_panel:setLabel(app.config.screenshots and app.config.screenshots or tooltip_screenshots, **built_in**):setAutoClip(true)

Removing built_in gives this
![font](https://user-images.githubusercontent.com/8009292/31276660-698994cc-aae0-11e7-94e9-589d1246e75d.png)

You can see the effect by searching ', built_in' and replace with nothing in folder_settings.lua and then hitting the 'X' on the screen (this resets the font label in say resetScreenshotDir back to the built_in

**Comment by TheCycoONE** [comment]
@mugmuggy Good find! I don't think we want to be using the built_in here - or anywhere? Would you mind making a PR?

**Comment by Lego3** [comment]
Note that the built in font is used here because paths are incomprehensible in the original Th font. It is missing slashes and colon.

**Comment by mugmuggy** [comment]
It seems there is a preference of the language font, then built-in, then original TH font. I can see that setLabel is probably calling lots TheApp.gfx:LoadFont("QData", "Font01V") when loading these dialogs , which would be the default TH font with those missing symbols.

But that function actually encapsulates checks for language_font if its isn't a specific symbol one for the bitmap_font, and uses that. Chuck in Font("unicode") into the English or other translations where it maybe missing and you get the symbols visible again.

The issue then is it affects the entire game so we probably want to parse in the font itself still, just the built_in value needs to be selected.

Something like this for example would ensure language_font was selected over the builtin, keeping say English working fine.

folder_settings.lua
  local built_in = app.gfx:menuFont()

graphics.lua
function Graphics:menuFont()
  local font
  if self.language_font then
	print ("Language Font")
    font = self:loadFont("QData", "Font01V")
  else
    print ("Builtin")
    font = self:loadBuiltinFont()
  end
  return font
end
