### ISSUE TITLE
Unable to move around map after zooming out

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#1220]
#### Describe the issue
Unable to move around map after i've zoomed out using the scroll on my mouse
#### Steps to Reproduce
1. Open a map

2. Zoom out using scrollwheel

3. Try to move to different places of the map

#### Expected Behavior
Be able to move around the map

#### System Information
**CorsixTH Version:** 0.60

**Operating System:** Windows 10 (1703)
**Theme Hospital Version:** Origin

#### Gamelog.txt
Nothing in gamelog.txt

**Comment by wolfy1339** [comment]
If you zoom back in you will be able to move around again

**Comment by TheCycoONE** [comment]
Possibly related to map bounds? If you turn on debug mode you should be able to disable map bounds, and see if that changes the behaviour.

**Comment by lewri** [comment]
No response
