### ISSUE TITLE
Hospital value award balance issue

### ISSUE THREAD

**Issue by AphidGit** [CorsixTH/CorsixTH#1222]
#### Description

At the end of each year, you get either an award or a penalty based on your hospital value. This is compared to a fixed amount, which is larger in the later missions. This turns into a pretty nasty balance issue: in Battenberg it's not uncommon to lose more than 120 reputation and game-over even if you didn't kill anyone and sent less than 5 patients home in the first year. 

In addition, if we want to make custom missions that are fairly long but challenge you to keep up your hospital value, you can't do that: the challenge is trivial for year 2 onwards, and can only be challenging for the 1st year because of the implementation.

I managed to get past by borrowing a ton of money and planting several dozen drinks machines to temporarily cheat at hospital value, but I don't feel that this should be necessary. This technique wasn't necessary in the original as far as I recall. This might have to do something with the fact that you can't cheat using juniors and Training in the corsixTH version to lower your doctor salaries though, as that's the biggest money sink in the first year (research costs). 

You can also get past the problem in the last mission by dumb luck: usually your reputation will be around 525-550 at the end of the first year, so just hope you roll a 1 or 2 and not a 15 on the 15-sided die, or just save on 31 december and reload until you don't lose. Seems a bit lame to me.

#### Steps to Reproduce
1. Play one of the last 3 missions. 
2. Don't build like crazy, play a bit carefully. 
3. Notice a massive reputation drop at the end of the first year because hospital value. 

Also see line 239 of CorsixTH/Lua/dialogs/fullscreen/annual_report.lua

Notice how in the worst case scenario, we can lose 'HospValuePenalty x 15' of reputation. This value is by standard 6, but could be modified in the level files. I suppose it might be a little higher for the last level(s). So if it was say 10 we could lose up to 150 reputation points. Note that actually meeting the hospital value goal after 1 year is usually impossible for the later missions (as it goes up above $125,000, requiring you to more than double your money in the first year, after running costs, AND factoring in any depreciation of value from building.  

### Suggested fix: 

Probably make this goal somewhat more dynamic than it currently is. E.g. instead of requiring you to have X value to avoid the penalty, instead require to have this: 
`S * e ^ (C * min(t, E)) `, where 'E' is the expected amount of years to complete the mission, and 'C' is chosen such that `S * e ^ (CE) = X`, thus being ` C = 1/E * ln(X/S)` . 

Also: Really reduce the randomness. 1d15 is extremely random. 5d4 - 4 or 5 + d4 would be more reasonable.

**Comment by MarkL1961** [comment]
15 x -6 = -90 (not a lot to lose if you had other reputation gains in the trophy room)
Values are by default taken from the file with 0 and then the level file can overwrite some values
I am not aware of depreciation being implemented as yet!
I have never had any issues playing any of the levels.  Are you saying they are too easy or not hard enough?

**Comment by AphidGit** [comment]
Read the suggested fix bit; I'm saying it's too hard to avoid the penalty in the first few years for the last few missions. You should be able to avoid it as it can cause a game-over pretty easily. On the other hand, the goal is really easy to reach for say year 5. **The goals for trophies should scale with time, not be constant.** I do suggest that they cap out after some time though.

**Comment by MarkL1961** [comment]
Each level had to be played differently to win it and it often meant losing a few times before you got it right.  The only thing I would want to change is that there is a difference between easy, hard and full, at the moment they are the same for this trophy - which does seem odd, but this is what TH did as the awards are taken from their files

**Comment by TheCycoONE** [comment]
Thank you for the well thought out comments.

I'm reluctant to accept controversial balance changes at this time. I would accept accuracy changes if it's demonstrated that the actual game performs differently in some way.
