### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by TheOTNN** [CorsixTH/CorsixTH#1223]
#### Description of the issue
I have created a Lua file for the language and dumped the strings, copied the copyright warning, selected the coding style or whatever it is to UTF 8 and for some quick check only translated a few words for main menu. But whenever i go in the game and open settings to set my language in order to check my changes if they are working as intended; my language which is Turkish can not be seen. Am i missing something?
![cth](https://user-images.githubusercontent.com/29413926/27104955-72f3abaa-5096-11e7-8a89-d231a952d222.png)
#### Steps to Reproduce
1. *Download the Lua file that is given in the link below to check *
2. *Search for ''Oyun Yükle or Devam et'' to see my changes*
3. *Locate the Lua file with other languages*
4. *Open the game and see it is not working just like how it is in the screenshot in here description*
#### Lua File
https://drive.google.com/file/d/0B0GiJv3vXTuQUkQxT05pLWxZRUE/view?usp=sharing

#### Expected Behavior
Do not know what to expect.
#### System Information
**CorsixTH Version:** *0.60*

**Operating System:** *Windows 7*

**Theme Hospital Version:** *Origin*

#### Gamelog.txt

```Created game with savegame version 111.
Error in buttonup handler: 
... (x86)\Origin Games\Theme Hospital\CorsixTH\CorsixTH.lua:56: cannot open D:\Program Files (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\debugger.lua: No such file or directory
stack traceback:
	[C]: in function 'persist.dofile'
	... (x86)\Origin Games\Theme Hospital\CorsixTH\CorsixTH.lua:56: in function 'dofile'
	...rigin Games\Theme Hospital\CorsixTH\Lua\run_debugger.lua:17: in function <...rigin Games\Theme Hospital\CorsixTH\Lua\run_debugger.lua:7>
	(...tail calls...)
	...es (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\ui.lua:261: in method 'connectDebugger'
	...rigin Games\Theme Hospital\CorsixTH\Lua\dialogs\menu.lua:757: in field 'handler'
	...rigin Games\Theme Hospital\CorsixTH\Lua\dialogs\menu.lua:408: in method 'onMouseUp'
	...x86)\Origin Games\Theme Hospital\CorsixTH\Lua\window.lua:1462: in field 'onMouseUp'
	...es (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\ui.lua:649: in function <...es (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\ui.lua:636>
	(...tail calls...)
	...s (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\app.lua:901: in function <...s (x86)\Origin Games\Theme Hospital\CorsixTH\Lua\app.lua:896>

**Comment by TheCycoONE** [comment]
Based on your screenshot you don't have a unicode font defined.

https://github.com/CorsixTH/CorsixTH/wiki/Game-Guide#folder-locations

**Comment by TheOTNN** [comment]
Will check what can i do when i am available but can you please clarify what i need to do? I think i need to download some fonts from the internet and then drop them at the folder where you shared the link with me. If so, can you also add a link of the font with me?

**Comment by TheCycoONE** [comment]
You can likely use a font that is already on your computer as long as it covers Turkish.

You are using windows, so you would set it to something like: C:\Windows\Fonts\arial.ttf (I'm not sure if arial.ttf covers Turkish, but that's the idea, pick a suitable font)

**Comment by TheOTNN** [comment]
Okay, i have chosen a text font it covers all the letter but in the game it appears as some cubes.

**Comment by MarkL1961** [comment]
Did you then select this as your font in the game?

You can either do this direct in the config.txt by including the path to this font or from within one of the option menus you see before you start a game - file or folder locations I think

**Comment by TheCycoONE** [comment]
It sounds to me like the font doesn't actually cover the characters you use.

**Comment by TheOTNN** [comment]
Let me show you. 
![arialss](https://user-images.githubusercontent.com/29413926/27563267-4fa19750-5ad9-11e7-9b49-662e4dc04eda.png)
As you can see at this picture i pick Arial for expamle, it covers all the letters of the language.
![csss](https://user-images.githubusercontent.com/29413926/27563318-88b371c6-5ad9-11e7-8bba-ff7f02c88335.png)
Set it as it is in the screenshot.
![lss](https://user-images.githubusercontent.com/29413926/27563277-62407afc-5ad9-11e7-81c8-5dab97a96038.png)
Then the result.

By the way i don't even know if one of those cubicles means Turkish, maybe they're other languages.

**Comment by TheCycoONE** [comment]
Ok, I took a closer look. The answer is in the console window when you start the game. There are a couple of strings in your new translation with newlines in them. E.g. Good job...

Remove those newlines so that the end " is on the same line as the start ", when there are no more errors you will see Türkçe in the list with arial.ttf

The other three languages with boxes are chinese, simplifed chinese, and korean, which arial doesn't cover.

I hope this helps.

**Comment by TheOTNN** [comment]
Okay i think i managed it and news occured sadly, here is an ss of it.
![ess](https://user-images.githubusercontent.com/29413926/27593393-bfcdccb6-5b5f-11e7-8357-11a8218882b3.png)

**Comment by TheCycoONE** [comment]
The message tells you the problem. It would be an issue near line 336. I didn't run into that though so you must have changed something in the file that I didn't. I'm a bit worried that you might have messed up your file.

**Comment by MarkL1961** [comment]
It is telling you that a `  }  ` is missing on the line with `  return_to_main_menu  `
Every string of words starts with `  {  `  and ends with `  }  `, just look at the other lines of text.  Whereas any comments or information sits behind ` -- ` or  `  --[  ` which then ends with `  ]--  ` when it is more than a line of text.  Commas and the end of each line is also important.
If you start again with a clean file that works and replace text between the `  {  }  `, you should be fine and don't change the name of the line i.e.   `  return_to_main_menu  ` as this is how this is referred to e.g. where this line appears it will show the text that is between the braces.

**Comment by TheOTNN** [comment]
Started with a new file and managed to complete the string with problem. The problem was, one or two strings was not a single line. Now it works so far.

But here's another question. The font when i changed into Turkish is so annoying how can i get the font while in English?

**Comment by MarkL1961** [comment]
Change the language in game back to English and keep your chosen font should work.

You could try a different font if the one you use is not good.  What font does your pc use when in word or a similar package?

We have a forum for translations where you can ask others who are doing the same thing in other languages http://forums.corsixth.com/index.php?board=11.0 so they may know more than we do here

**Comment by TheOTNN** [comment]
Yeah, i know i'm coming from there you can see the subject named ''Testing'' and it's mine, my nickname is just different it's ''UltimateBox''.

**Comment by TheCycoONE** [comment]
Maybe try lucon.ttf

The font rendering in the game isn't great - to the best of my knowledge we haven't really played with the hinting options; and the game is designed for these bi-colour bitmap fonts built into the game which to the best of my limited knowledge on the subject we aren't able to reproduce with freetype.

**Comment by TheOTNN** [comment]
It seems i don't have lucon and didn't understand things you said about two pass approach. Anyway, os far i can see my editings on lua file and it's good.

**Comment by TheCycoONE** [comment]
Sorry @TheOTNN the two pass thing was meant to be internal. I'll move discussion about using system fonts off this ticket.

Going to close this issue now. Whenever you are done your updates you can make a PR or attach the lua file to a new issue ticket the same way you did here.

Thanks!
