### ISSUE TITLE
Movie player stack trace without game data directory

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#1225]
#### Describe the issue

Starting CorsixTH Trunk without a game data directory defined, shows an stack trace of the movie player.

#### Steps to Reproduce
1. Start the CorsixTH without a game data directory defined

#### System Information
**CorsixTH Version:** *cb3b74e8b152862f201881f49322615bba06d45a*

**Operating System:** *Debian 9 (x86)*

**Theme Hospital Version:** *CD*

#### Gamelog.txt

```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The window_resize handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/movie_player.lua:228: attempt to index a nil value (field 'moviePlayer')
stack traceback:
	./Lua/movie_player.lua:228: in method 'deallocatePictureBuffer'
	./Lua/app.lua:1514: in method 'prepareVideoUpdate'
	./Lua/ui.lua:434: in method 'changeResolution'
	./Lua/ui.lua:717: in function <./Lua/ui.lua:715>
	(...tail calls...)
	./Lua/app.lua:906: in function <./Lua/app.lua:901>

```

**Comment by MarkL1961** [comment]
Could be  handled better, but the game needs to know where your files are to work correctly

**Comment by TheCycoONE** [comment]
Normally the game asks for your game directory when it starts and the HOSP dir is undefined.
You built this yourself @bobcanthelpyou - could you copy your CMakeCache file (or the build options you used)?

**Comment by bobcanthelpyou** [comment]
@TheCycoONE i see the stack trace exactly when i have to choose the HOST dir. 

`cmake -D LUA_INCLUDE_DIR=/usr/include/lua5.3 -D LUA_LIBRARY=/usr/lib/i386-linux-gnu/liblua5.3.so.0 .`

**Comment by TheCycoONE** [comment]
Can reproduce
