### ISSUE TITLE
Crash seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#1232]
#### Describe the issue
A woman wanted to go to the shrink, I built his office and recruited him but she still didn't go there.
The game crashed with an error message ("Sorry a humanoid just has an empty action queue, which means that he or she didn't know what to do next. Please consult the command window for more detailed information. A dialog with the offending humanoid has been opened. Would you like him/her to leave the hospiral?) and the log below.

#### Save Game
https://drive.google.com/open?id=0B9SUHZiI6ptSc3VzaWh4WmlDaTQ

#### System Information
**CorsixTH Version: 0.60

**Operating System:** Windows 10

**Theme Hospital Version: Origin

#### Gamelog.txt
```
Created game with savegame version 111.

Empty action queue!
Last action: walk
stack traceback:
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:546: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
The humanoid was told to leave the hospital...

Empty action queue!
Last action: walk
stack traceback:
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:546: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
The humanoid was told to leave the hospital...
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000001C74C2FA4B0) from humanoid (table: 000001C74BA7C2A0).
Warning: Trying to remove nonexistant room remove callback (function: 000001C74CB16E20) from humanoid (table: 000001C74BA7C2A0).
Warning: Trying to remove nonexistant room build callback (function: 000001C74B724DC0) from humanoid (table: 000001C751C0C3B0).
Warning: Trying to remove nonexistant room remove callback (function: 000001C74BD2EF80) from humanoid (table: 000001C751C0C3B0).
Warning: Trying to remove nonexistant room build callback (function: 000001C74BF9B440) from humanoid (table: 000001C74B310860).
Warning: Trying to remove nonexistant room remove callback (function: 000001C7522F1950) from humanoid (table: 000001C74B310860).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000001485BD44B10) from humanoid (table: 00000148551A5240).
Warning: Trying to remove nonexistant room remove callback (function: 0000014849499F70) from humanoid (table: 00000148551A5240).
Warning: Trying to remove nonexistant room build callback (function: 0000014855453CE0) from humanoid (table: 000001485473E170).
Warning: Trying to remove nonexistant room remove callback (function: 000001485A3A1FB0) from humanoid (table: 000001485473E170).
Warning: Trying to remove nonexistant room build callback (function: 0000014848E51D70) from humanoid (table: 00000148560120F0).
Warning: Trying to remove nonexistant room remove callback (function: 00000148539154A0) from humanoid (table: 00000148560120F0).
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in method 'finishAction'
	D:\Jeux\CorsixTH\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Warning: Trying to remove nonexistant room build callback (function: 000001485A749080) from humanoid (table: 0000014855AA4530).
Warning: Trying to remove nonexistant room remove callback (function: 000001485B234140) from humanoid (table: 0000014855AA4530).
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in method 'finishAction'
	D:\Jeux\CorsixTH\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>

```

**Comment by sebastienaubry** [comment]
This issue is blocking and prevents me from ending the game :-(

**Comment by MarkL1961** [comment]
From what I can see there is no path to the new room, which is likely the reason it crashes.  Move the cardio and staffroom to clear the path and then patients and staff will be able to get to the phyc.

**Comment by sebastienaubry** [comment]
Thank you very much, I removed these  rooms and now it seems Ok. What is weird is that there is another entrance in the building, which would allow to access the new room.

**Comment by TheCycoONE** [comment]
There is still a restriction that should prevent blocking off an area. There are a few quirks in it still like the radiator door bug. I haven't looked at this save in particular. sebastienaubry says there was another entrance, which makes it very curious. I lack the time at the moment to really investigate.

**Comment by TheCycoONE** [comment]
For what it's worth, the failure is here: https://github.com/CorsixTH/CorsixTH/blob/0.6x/CorsixTH/Lua/humanoid_actions/seek_reception.lua#L47 getPathDistance is returning false rather than a number because it couldn't find a path.

This would be related to #826

**Comment by MarkL1961** [comment]
The other door/main entrance is not connected to the rest of the hospital, it would be once the nearby plot it purchased. (this is from memory).  If patients walked over lawns it would be accessible, they have to stick to pavement tiles or floor tiles in a building - which is only right really.

If the blocking off rules is still in place I am surprised you were able to build there

**Comment by TheCycoONE** [comment]
@sebastienaubry do you recall what order you built those rooms and if you edited or moved any of them?

**Comment by TheCycoONE** [comment]
Thanks @MarkL1961 

I read back on the notes on #819. Evidently this is a known problem and at the time I opted to fix the crash instead of preventing the blocking, with the goal of eventually allowing blocking like the original game. Seems I didn't really follow up over the last couple years and forgot about that resolution.

To be consistent then and to make some progress against #825 we should fix the actual error.

**Comment by sebastienaubry** [comment]
@TheCycoONE : I did exactly what @MarkL1961 explains: I first built the room close to the "curtain" (false wall), then I extended the hospital.
Thanks to your advice I am not stuck anymore :-)

**Comment by MarkL1961** [comment]
I think I agree, if I have understood the intention correctly.

The real error here is the game throws an error because pathfinding can't calculate the distance to a blocked off area.  Perhaps it should instead give the message about planning your hospital better and meander those that cannot find a path - they will leave it is not sorted out.

The fact that you can sometimes build in a blocked area (like this issue) is not really an error if we work towards allowing blocked off areas and handle it in a better way.

Is this what you are thinking? @TheCycoONE

**Comment by MarkL1961** [comment]
@sebastienaubry  Glad that you can move on and finish that level and thanks for reporting. 👍 

There is an issue and this has reminded us of it

**Comment by TheCycoONE** [comment]
@MarkL1961 exactly what my thinking was.

**Comment by MarkL1961** [comment]
I suspect that there are going to be  a lot of places where this error is happening in one form or another i.e. new room callback, staff checking for work, patients looking or waiting for a room.

If you get the time to work on a solution and need a tester let me know

**Comment by mugmuggy** [comment]
> 
> 
> Try this, build the staff room against the dividing wall. Buy the adjacent plot and it will allow you to build!
> 
> Very strange bug....
> 
> ![not connected](https://user-images.githubusercontent.com/4965487/28638858-1e35a7e8-723e-11e7-9477-e803ad8d691d.png)

I went ahead and took a look at this from the TH perspective. It does the same thing at least for one room. One day I partially implemented blocking off like in #826, but never actually got around to fully testing it, some passable flags were wrong, but I did get the build side working fine.

The strategy I used roughly aligned with TH, but TH allows one room as it doesn't check the current room under construction for accessibility which was the difference I had. My strategy was assume patient could seek reception, then for each room make sure they were accessible to each door tile outside room.

TH appears (at least without a reception desk) to check spawn point to first room door, then first to 2nd, when building a 3rd room (2nd in a blocked off area). But it doesn't check accessibility to anywhere else when you build a room. Indeed I believe it only checks the tiles for the door are accessible to each other.

TH Objects are a different matter and I believe are also checked for accessibility immediately to the spawn points, when placing the object only. Thus can't place objects in blocked off areas (except plants, they get treated differently). And you _can't_ block off objects with other objects - eventually it gives up and does allow you to though.

**Comment by iotku** [comment]
Ran into what I believe is the same issue here. (Linux Flatpak, CorsixTH v0.67)

![Screenshot_20230829_162614](https://github.com/CorsixTH/CorsixTH/assets/1768520/827fda59-d9e0-4044-99e5-591aa4b93959)

Of particular note when trying to recover by removing the rooms (from the cardio to the scanner in the right section) to attempt a recovery the doctor in the rightmost scanner room remains frozen in place and unresponsive (I can pick them up and move them in order to remove the room if I move them quickly, but they don't go anywhere and after dismissing them they stay in place) (perhaps they were frozen at the time of the save file which I took after the initial error was thrown). 

Sometimes, maybe depending on the order in which I remove the rooms,  I get a notification that building in a location would block off areas of the hospital during removal (without moving the location or expanding the room).

In some cases removing those rooms resolves the errors from continuously popping up.
Below I have a savefile and log from terminal output containing the error  and the associated stack trace

`.../share/corsix-th/Lua/humanoid_actions/seek_reception.lua:83: attempt to perform arithmetic on a boolean value (local 'this_score')`

[CTH-error.zip](https://github.com/CorsixTH/CorsixTH/files/12471688/CTH-error.zip)

**Comment by Alberth289346** [comment]
`seek_reception.iua` suggests the patient is looking for a reception desk:

seek_reception,lua:
``` lua
local this_score = humanoid.world:getPathDistance(humanoid.tile_x, humanoid.tile_y, x, y)  -- << Line 81

this_score = this_score + desk:getUsageScore()
```
The function at line 81 returns false if there is no path to a reception desik from the patient. Line 83 then tries to add a number to that false value, and you get the error.

**Comment by TheCycoONE** [comment]
Ideally the patient would idle or meander and check again a few ticks later
