### ISSUE TITLE
No animation for Doctor using op_sink1 facing east phase 0

### ISSUE THREAD

**Issue by bacon1986** [CorsixTH/CorsixTH#1237]
#### Describe the issue
Error occurs in middle of gameplay.
Surgeon is now stuck and Operating Theater fails to work.

#### Steps to Reproduce
None

#### Save Game
[Save Before Issue.zip](https://github.com/CorsixTH/CorsixTH/files/1202708/Save.Before.Issue.zip)
[Save After Issue.zip](https://github.com/CorsixTH/CorsixTH/files/1202710/Save.After.Issue.zip)

#### System Information
**CorsixTH Version:** v0.60 launched from Steam

**Operating System:** Windows 10 Enterprise

**Theme Hospital Version:**  GOG.com

#### Gamelog.txt
[gamelog.txt](https://github.com/CorsixTH/CorsixTH/files/1202706/gamelog.txt)

**Comment by bacon1986** [comment]
This may be a duplicate of #1073 
Sorry.

**Comment by TheCycoONE** [comment]
Looks to be, thanks!
