### ISSUE TITLE
Switch from C/C++ to Java

### ISSUE THREAD

**Issue by gDanix** [CorsixTH/CorsixTH#1238]
As the title says, the proposition is to switch the bootstrap code (the one which configures libraries and start Lua VM) to a more "modern" environment, like Java.

I have read #731, and know the "Things I should never know", but I think that a rewriting of that (presumably) small bootstrapping code will carry some benefits:
* Better build tools and packaging system: Unlike CMake, there are a lot of good tools, like Maven, to build and package in a simpler way the project. Also, these tools manage very easily library dependencies.
* Better language integration: There is a project, called LuaJava (https://github.com/jasonsantos/luajava), that enable Lua code to call Java functions using the same syntax used when calling native Lua objects.
* Attract more developers: Because of the previous point, some parts of the project (like multiplayer) can be implemented in a well-known language (Java), and existing Lua code can seamlessly interact with Java-implemented features, keeping both languages code clean (thanks to Java reflection, the functions doesn't need to conform a specific signature, unlike C/C++ (http://gamedevgeek.com/tutorials/calling-c-functions-from-lua/))

Thank you all for your time

**Comment by corsix** [comment]
No.
