### ISSUE TITLE
people getting stuck

### ISSUE THREAD

**Issue by sionmaisley** [CorsixTH/CorsixTH#1239]
People and staff getting stuck in clumps together causing a pileup and preventing you from completing the level, the earthquakes are always a big problem too and usually destroy a room, which can then not be removed and rebuilt as would happen in the real world, this leads to extreme frustration.

**Comment by Alberth289346** [comment]
Patients and staff getting stuck isn't supposed to happen, but these bugs are hard to track down and eliminate.
Rooms getting destroyed is part of the game, and are supposed to happen. I agree it's annoying, but that's the whole point of it. Some work has been done to earth quakes to reduce the effect, and that will be in the next release. It will be a while before that happens though.
