### ISSUE TITLE
Messages not translated into Spanish

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1242]
Describe the issue
I have the game translated into Spanish, but there are still some English messages, which are not translated.

Save Game
https://www.dropbox.com/s/a1axv2qq4utrshm/keeper2.sav?dl=0

System Information
**CorsixTH Version: 0.60
**Operating System: Windows 10 64 bits
**Theme Hospital Version: CD

Additional Info
![med general2](https://user-images.githubusercontent.com/31771827/30233482-1eeebd66-94f6-11e7-93e8-9f52a065df28.jpg)

**Comment by wolfy1339** [comment]
If you are good at translating, maybe you could translate it and post it here so someone can update the language file with the translation

**Comment by KeeperSt** [comment]
Here comes the translation:
  "Cobras muy poco en Medicina General.  Eso hará que la gente venga a tu hospital, pero no le sacarás provecho".

Original text:
  "You're charging too Little for Medicina General.  This will bring people to your hospital, but you won't make a lot of profit from each one".

**Comment by KeeperSt** [comment]
More messages, which are not translated.

Save Game
https://www.dropbox.com/s/rcmo6dt6l22x2vk/keeper4.sav?dl=0

Additional Info
![med general4](https://user-images.githubusercontent.com/31771827/30288213-3dfd6c96-9728-11e7-8830-d4688870f593.jpg)

Here comes the translation:
"¡Un paciente se ha ido de Medicina General sin pagar porque es demasiado caro!"

Original text:
"A patient left without paying for Medicina General because it's too expensive!"

**Comment by KeeperSt** [comment]
More messages, which are not translated.

Additional Info
![med general6](https://user-images.githubusercontent.com/31771827/30289818-aaa94d6a-972d-11e7-9d75-d0eba1d4661d.jpg)

Here comes the translation:
"¡Un paciente se ha ido sin pagar Cálculos de Golf porque es demasiado caro!"

**Comment by KeeperSt** [comment]
More messages, which are not translated.
Additional Info
![med general7](https://user-images.githubusercontent.com/31771827/30290902-58dfe1ac-9731-11e7-850e-6231626f3772.jpg)

Here comes the translation:
"¡Un paciente se ha ido sin pagar Vomitona porque es demasiado caro!"

**Comment by KeeperSt** [comment]
More messages, which are not translated.
Additional Info
![med general8](https://user-images.githubusercontent.com/31771827/30291662-e2170c14-9733-11e7-9247-232f9006745e.jpg)

Here comes the translation:
"¡Un paciente se ha ido sin pagar Gaseocontención porque es demasiado caro!"

**Comment by MarkL1961** [comment]
I believe that these missing translations relate to a feature that was added after the last release and most translations are added just before a release.  The feature is to do with over and under charging.  There is a good chance that it is the same one as all such messages are once only and the treatment is added separately (which is translated).

The only translation needed therefore is for A patient left without paying for ## because it is too expensive. - where ## equals the name of the treatment

Don't go hunting for more of this type because if one treatment is missing they will all be missing.  There are likely to be others for a different scenario so if I can see what they are I will paste them here

**Comment by MarkL1961** [comment]
These are the most likely to need a translation and % is the place holder for the treatments which seem to be translated already:
A patient is leaving without paying for %s. It's too expensive. 
Your charges are high. This will make big profits in the short-term, but ultimately you'll start to drive people away. 
You're charging too little. This will bring people to your hospital, but you won't make a lot of profit from each one.

**Comment by MarkL1961** [comment]
Oddly some are also in the overrides of the English file, which are not normally needed if they exist already in the TH files! The original does not include the treatment name, which might be why they are there.
    low_prices = "You're charging too little for %s. This will bring people to your hospital, but you won't make a lot of profit from each one.",
    high_prices = "Your charges for %s are high. This will make big profits in the short-term, but ultimately you'll start to drive people away.",
    fair_prices = "Your charges for %s seem fair and balanced.",
    patient_not_paying = "A patient left without paying for %s because it's too expensive!",

**Comment by KeeperSt** [comment]
Ok, you are right.  If a treatment is missing, it will be missing in all of them too.  
The translation for
 " A patient left without paying for ## because it is too expensive. - where ## equals the name of the treatment" 
would be
  "Un paciente se ha ido sin pagar ## porque es demasiado caro", where ## equals the name of the treatment.
  In case ## is the place where the patient has gone without paying, the translation would be
  "Un paciente se ha ido de ## sin pagar porque es demasiado caro".

  The translation for
  " Your charges are high. This will make big profits in the short-term, but ultimately you'll start to drive people away."
  would be
  "Cobras demasiado.  Eso te dará grandes beneficios a corto plazo, pero al final la gente se irá".

 The translation for
  "You're charging too little. This will bring people to your hospital, but you won't make a lot of profit from each one."
  would be
  "Cobras muy poco. Eso hará que la gente venga a tu hospital, pero no le sacarás provecho".

**Comment by Alberth289346** [comment]
At least the "charges" messages have been translated already in the master development branch. I don't know if there are development builds currently (there used to be), but you may want to try one of those instead.
Alternatively, you can get the spanish translation from https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/languages/spanish.lua ,  which in your installed version is a path like ``CorsixTH/Lua/Languages/spanish.lua`` (I don't know the precise install details, but it shouldn't be difficult to find the file, as there is only one ``spanish.lua`` file  :)

You can also modify that file if you like, compare with the ``english.lua`` file to see how the patterns work.
If you want to submit changes, start from the github ``spanish.lua`` file (so you're updating against the newest version), improve the translation, and submit the changed file (if possible as a text-attachment, so we don't get a message of 3000+ lines of code here).

**Comment by lewri** [comment]
It looks like some variation of these Spanish translations have been put into spanish.lua ; but maybe not in the same words as  suggested by @KeeperSt 
Do let us know if you think the translations in spanish.lua are not right/acceptable though.
