### ISSUE TITLE
Last line of the final message cannot be read

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1251]
#### Describe the issue
  When finishing the game, the last line of the final message cannot be read.  (I mean the main campaign).

#### System Information
**CorsixTH Versión: 0.60

**Operating System:**Windows 10 64 bits

**Theme Hospital Version:** *CD

### Additional Info
![med general19](https://user-images.githubusercontent.com/31771827/30776767-a6d0d996-a0ac-11e7-8dee-a2837605212c.jpg)

**Comment by TheCycoONE** [comment]
Looks like the translation for the fax is too long, and ran into the text for the top checkbox.

Any spanish translators able to condense this a bit?

**Comment by KeeperSt** [comment]
I have not been able to find the translation, but this could be a shorter translation of the original one:

  "Felicidades por dirigir con éxito los hospitales asignados.  Esta soberbia actuación te permite viajar libremente por todo el mundo.  Recibirás una pensión de 16017 y una limusina.  A cambio, viaja de ciudad en ciudad, saluda a tu público incondicional y fomenta la labor realizada en los hospitales".
  "Estamos orgullosos de ti.  Te agradecemos tu labor de salvar vidas".

  I think we save one line, or two.

**Comment by TheCycoONE** [comment]
The translation is in `Lua\languages\spanish.lua`.

The first paragraph is on line 183 at the moment. I'm not sure where the second paragraph is, but it seems like an original prompt.

https://github.com/CorsixTH/CorsixTH/blob/6a079fd02bc456be7410e4394d7661308e86b3bf/CorsixTH/Lua/languages/spanish.lua#L183
