### ISSUE TITLE
Deprecated variable definition in the level file

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1252]
#### Describe the issue
 [Nuevo documento de texto (3).txt](https://github.com/CorsixTH/CorsixTH/files/1331106/Nuevo.documento.de.texto.3.txt)

#### Steps to Reproduce
 I click on the "Individual match" button, then I click on "Abscence Central", and I trigger a lot of errors.

#### System Information
**CorsixTH Version:** 0.60

**Operating System:** *Windows 10*

**Theme Hospital Version:** *CD

**Comment by TheCycoONE** [comment]
That map is not one of ours; you should write to the author e.g. on the forum where you found it.

**Comment by KeeperSt** [comment]
OK, thanks.  I have already talked to the authors in the forum.
