### ISSUE TITLE
Upside down fax

### ISSUE THREAD

**Issue by KeeperSt** [CorsixTH/CorsixTH#1253]
#### Describe the issue
  The fax tells you that you have won (all that you could) from 0, instead of 0 from all that you could have won.

#### Steps to Reproduce
  When failing in accomplish an emergency, the fax tells you that you have won (all that you could) from 0, instead of 0 from all that you could have won.

#### Save Game
https://www.dropbox.com/s/7aki7d5zu1hq6xb/keeper7.sav?dl=0

#### System Information
**CorsixTH Version:**0.60
**Operating System:**Windows 10 64 bits
**Theme Hospital Version:**CD

### Additional Info
![med general26](https://user-images.githubusercontent.com/31771827/31035971-6e9e3df8-a56a-11e7-8397-41bfa0f1de6f.jpg)

**Comment by TheCycoONE** [comment]
Curious, that's an original prompt. The english is `[44,40] "Out of a maximum bonus of %d, you have earned %d."`

Is this bug present in the original game too, or did they change the order of the parameters depending on the language?

**Comment by MarkL1961** [comment]
Is it a poor translation by Bullfrog?

**Comment by KeeperSt** [comment]
The values are in the wrong order.  In Spanish, your earn 0 out of 4800.  You do not out of 4800 earn 0.
"Has ganado 0 de una prima máxima de 4800". (Correct)       You have earned 0 out of 4800
"De 4800, has ganado 0".  (Wrong)                                          Out of 4800, you have earned 0
So the translation is wrong "out of 0, you have earned 4800".

**Comment by MarkL1961** [comment]
So, like I suggested it was a fault from Bullfrog?  There have been many and the way to get around it could be to provide an override in our Spanish file

**Comment by TheCycoONE** [comment]
I think so. Keeper St. can you provide a reworded sentence so that the 4800 can come first.

**Comment by KeeperSt** [comment]
"De una prima máxima de 4800, has ganado 0."  This is not the usual way to say it, but the order of the sentence can be changed.

**Comment by TheCycoONE** [comment]
Ok, I'll make sure that lands in the next version
