### ISSUE TITLE
Debug Patients

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1256]
#### Describe the issue
There's two errors when using Debug Patient, which I'm not sure if intentional.

Bug 1 - A debug patient is unable to move and stuck in 'idle' and does not join a queue. Only option is to 'Send Home', which then triggers an action.

Bug 2 - A debug patient made with a disease not yet diagnosed breaks the game. Specifically, trying to open the 'Drug Casebook' on patient will result in an error in the log and no longer allow mouse clicks. Command buttons still work, however.

#### Steps to Reproduce
Bug 1 - Add a Debug Patient. They will not move (and permanently have the lightbulb icon).

Bug 2 - Add a Debug Patient with a disease not yet diagnosed. Click on patient and try to view their casebook entry.

#### Expected Behavior
Expected behaviours are for patients to move freely and not cause crashes.

#### System Information
**CorsixTH Version:** 0.6

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt
For Bug 2 only (Bug 1 doesn't make any logs):
 `Error in buttonup handler: 
... Files\CorsixTH\Lua\dialogs\fullscreen\drug_casebook.lua:151: attempt to index a nil value (field '?')
stack traceback:
	... Files\CorsixTH\Lua\dialogs\fullscreen\drug_casebook.lua:151: in method 'updateIcons'
	... Files\CorsixTH\Lua\dialogs\fullscreen\drug_casebook.lua:139: in method 'selectDisease'
	... Files\CorsixTH\Lua\dialogs\fullscreen\drug_casebook.lua:92: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:76: in global 'UICasebook'
	C:\Program Files\CorsixTH\Lua\dialogs\patient.lua:318: in local 'callback'
	C:\Program Files\CorsixTH\Lua\window.lua:682: in method 'handleClick'
	C:\Program Files\CorsixTH\Lua\window.lua:1478: in field 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\dialogs\patient.lua:224: in method 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\window.lua:1462: in field 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\ui.lua:649: in function <C:\Program Files\CorsixTH\Lua\ui.lua:636>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>
`

**Comment by lewri** [comment]
Moving forard for Bug 2... it should probably create a message telling the user 'You haven't discovered this disease yet'. Or make it so only debug patients can be made where their disease has been discovered.

**Comment by TheCycoONE** [comment]
The `debug` menu items are potentially game breaking, and meant for diagnosing issues encountered in game play.

Bug 1 is worth investigating. For 2, the only ideas I would entertain are resetting the button handlers after a crash, and maybe some sort of visual indication of 'valid diseases.

Let's focus this ticket on the first issue.

**Comment by MarkL1961** [comment]
Debug patients have that icon to show they are debug patients.
They can move, not independently though, you click on them and then click where you want to them to go to.  
They are not apart of the normal game play

**Comment by lewri** [comment]
Mark is right. They will move once you right click something for it to go to.

Following that, bug 2 would be the only issue remaining. Going with @TheCycoONE said, I would move a suggestion of a visual indication of diseases. Perhaps diseases not discovered should create the debug patient undiagnosed (to test diagnosis processes).

**Comment by lewri** [comment]
Some debug stuff is fixed. Will close, unless it is worse pursuing testing diagnosis process.
