### ISSUE TITLE
Multiple handymen repair x-ray

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#126]
![a](https://f.cloud.github.com/assets/4965487/1796559/1a1bbdd8-6a76-11e3-887e-8d8b7a3581f6.png)
I don't know if this is general or just the epidemic branch, but I have noticed that when the x-ray needs repair that more than one handyman turns up.  
In the second picture you will see there are two handymen, only one call for repair and having clicked on each of them you will see in the console that they have both answered the call.
As I have only been testing epidemics for the last few weeks I don't know whether this is specific to that branch or a general issue.  Sadger is pretty sure he has not done anything that could cause this.  

Has anyone else seen this?
![7](https://f.cloud.github.com/assets/4965487/1871749/2dcf0500-789b-11e3-9f29-2c0ba3f3a193.png)

**Comment by bobcanthelpyou** [comment]
Possibly fixed by #921

**Comment by lewri** [comment]
May be resolved by PR #921
