### ISSUE TITLE
Building area is not updated when waste is thrown or cleaned

### ISSUE THREAD

**Issue by vyguera** [CorsixTH/CorsixTH#1269]
#### Describe the issue
When you are editing a room and whether a patient throws litter on the floor or if the litter is already on the floor and the cleaner cleans it up in the meantime, the building area is not updated until you move the room around.

#### Steps to Reproduce
1. Load save game attached to this ticket 
2. Edit a room near a crowd of patients. Do not move the room around
3. Wait until a patient throws litter to the floor. The particular square of floor should turn red
4. Wait until a cleaner comes and cleans the litter. The particular square of floor should turn blue.

#### Save Game
https://app.box.com/s/sfi5ef63ahiod7fxpy2j3d0ks3v50rny

#### Expected Behavior
Building area should be updated automatically, without moving cursor, when litter is thrown on the floor and also when a cleaner cleans the litter.

#### System Information
CorsixTH Version: 0.6
Operating System: Windows 7 64bits
Theme Hospital Version: CD

### Additional Info
![waste 1](https://user-images.githubusercontent.com/1656373/32119647-3319c912-bb56-11e7-85f3-f4cd2823c6e9.PNG)
![waste 2](https://user-images.githubusercontent.com/1656373/32119655-38d65654-bb56-11e7-8a98-5828faa4fc28.PNG)

**Comment by TheCycoONE** [comment]
This should already be fixed by #1119 

Are you able to test with the latest master? 0.60 is quite old now. (Yes, I need to put out another release)
