### ISSUE TITLE
consider creating gpg-signed releases

### ISSUE THREAD

**Issue by emorrp1** [CorsixTH/CorsixTH#1271]
Hello,

This is a request for increased authentication of valid project releases above and beyond what's provided by Github's organization permissions. Please consider following this guide to [creating GnuPG-signed releases](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) as a way of verifying that no third party has modified the code against your wishes after the release. According to [debian-watch-may-check-gpg-signature](https://lintian.debian.org/tags/debian-watch-may-check-gpg-signature.html), projects such as phpmyadmin, unrealircd, and proftpd have suffered from this kind of attack. Github accounts support [gpg keys](https://help.github.com/articles/adding-a-new-gpg-key-to-your-github-account/) and the Debian repository will automatically verify the signature on each new release.

Thanks
Phil Morrell (emorrp1)

**Comment by TheCycoONE** [comment]
Done, for 0.61-beta1.

**Comment by emorrp1** [comment]
Awesome, I was able to retrieve your public key from the Github API: https://api.github.com/users/TheCycoONE/gpg_keys

I can verify the signed tag locally, but please can you attach a `CorsixTH-0.61-beta1.tar.gz.asc` file (see below) to the release notes? Unfortunately, Debian doesn't yet have a mechanism for directly uploading tagged releases, so it still uses the tarball.

```
name=CorsixTH-0.61-beta1 # don't ask me why there's no v, it's just what GitHub does
git archive --prefix=$name/ -o ../$name.tar.gz v0.61-beta1
gpg --armor --detach-sign ../$name.tar.gz
```

Thanks for going out of your way to learn the linux processes, I understand most downloads are presumably from Windows.

**Comment by TheCycoONE** [comment]
So what we are trying to prevent seems to be github.com turning malicious (or being hacked) and providing tarballs that don't match the tagged source code. An issue arises because you've downloaded my public signature from github, and the release tarball from github. A malicious party could replace my public signature with another one in my name for which they have the signing key, and then put out their own 'evil' tarball - unless you want to obtain my key in some other way?

**Comment by emorrp1** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

> So what we are trying to prevent seems to be github.com turning malicious (or being hacked) and providing tarballs that don't match the tagged source code.

Yes, that's exactly right, it forms a verifiable chain from your machine to mine or any other Debian Developer's. The chain of trust is then maintained through the upload, build, distribution and download to a users machine. Our tooling needs to be improved to supported signed git tags directly.

> An issue arises because you've downloaded my public signature from github, and the release tarball from github. A malicious party could replace my public signature with another one in my name for which they have the signing key, and then put out their own 'evil' tarball.

Only a bootstrapping issue. Since I've never met you, having your signature doesn't prove the release is from you. However, I'm only going to download your key **once** into my keyring (and the debian package), so it does prove the release is from the same "controller of the corresponding secret key" from now on. This practice does prevent the attack you described and for the record, the fingerprint of the key I received is DB147D8CD6737D34210D 20235C251992033D3D7C (a statement which anyone who trusts my key can verify, since I've signed this markdown message).

> unless you want to obtain my key in some other way?

GPG provides a number of mechanisms for obtaining public keys, you can choose to publish to keyservers [e.g. mine is](http://pool.sks-keyservers.net/pks/lookup?search=0x2C429F5DD6B7F023BD300993453F8D999F113609&fingerprint=on&op=vindex), Web Key Directory, dns, debian packages, in person etc. For proper web of trust, you'd have a [keysinging party](https://www.debian.org/events/keysigning) giving someone your fingerprint in person and proving your identity to them, then it really doesn't matter how the actual key is retrieved.
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEXDaX1B65I75FAped34XHDtO9S4wFAloNvWYACgkQ34XHDtO9
S4xZog//dHcOL2HbVirD5FVtr/MsOtY6aEix4UPzIn29+OIgE0ljDOOO94zRgmLf
NyZj/NukGt6MpGEV9jHtSZg+HhQOiHIxGjPBlTun/GDQ1PQm7o4sbRPtFjg4KEga
TENi5N/6WDAQDWKYuoT/XF93ONVTpMbCibfIYMPJDnPYsuu5lkBnQ4gr4CeTxtsD
HAYgE25kGHL75cN6IxBImKiwc0bOWKzKvbwFeJPkNvpn2gTg7GmEtX/E2zU1AmQB
Pn/v+0q119YOkqPFwpcXEA/44npdeAIPkqnj1Ck0+us82Jw/tAKLCyHjm3vxd1rX
PQrzQrbo8lO8rlWBH7doBRm/m0WKQHsN1n4sfRJQfAkPAjxKMnOi3OZB8HtUmlqC
rnftMYrwy+ezEu9UdpTGWG9zeDwZV0kYo1wDdw3EEkaAz6ukXg5kbGZ4y2R4oRmz
hfDZV63GLr8G8MzSL6ublrVPnNi6e16Td+0FpnqJ667BLrRDhu6+Tp5bndkAlWVx
ouOZhlT+YCJmexnXrCd8Fe8n2TDanf0VggFY5KcKEokixdDlB0Ggka0r8UH2qg1p
IduE4LqKWR9T9dCVVz+5TitPgv08mrXl5ngVKR14zE8ZK5SKWBwGIGmbhO0VnQWo
K/ReZwJVQB1QW2a4Sj2qy2PaR5Co5gmm1qcEIMh3JcRFX3wPHFQ=
=KLE/
-----END PGP SIGNATURE-----

**Comment by emorrp1** [comment]
And I've realised I massively overcomplicated it:

* I gave a really long-winded description of [Trust on first use](https://en.wikipedia.org/wiki/Trust_on_first_use), aka SSH-like security
* Your public key can't be changed without also invalidating the signed tag for anyone who has cloned

**Comment by TheCycoONE** [comment]
Added `asc` which I have verified both on a locally generated tarball and the one downloaded from github. Just have to remember to do this every release.
