### ISSUE TITLE
Scrolling isn't working

### ISSUE THREAD

**Issue by CrippledGamerMax** [CorsixTH/CorsixTH#1273]
I got the app on a nvidia shield k1 which works perfectly apart from scrolling, when in build mood I try to place a object but everything scroll so it’s very hard, even tried the beta tester one but no look, you use to scroll  with 2 fingers but now it’s one. Can this be fixed?

**Comment by lewri** [comment]
Hi!

I think you might be looking for @alanwoolley's port of CorsixTH to Android. The Github page is here.
https://github.com/alanwoolley/CorsixTH-Android

Looking here it appears to be a documented issue, however: https://github.com/alanwoolley/CorsixTH-Android/issues/109
