### ISSUE TITLE
Mouse leaves screen on multiple display systems

### ISSUE THREAD

**Issue by dsnkostic** [CorsixTH/CorsixTH#1279]
If you have system with 2 or 3 monitors, scrolling on the edge of the screen will leave monitor where Theme Hospital is running on.
e.g. I have three monitor setup and the middle is the primary monitor. If I scroll on the left or right edge, mouse simply leaves that monitor and upon clicking, loses the focus. Mouse pointer should be constrained only on primary monitor and should NOT leave to the other monitors.
OS: Windows 8.1,
Using game content from GoG version of Theme Hospital

**Comment by TheCycoONE** [comment]
@dsnkostic on the latest git version, ctrl+f10 can be used to enable/disable mouse locking. There should be a setting to configure the default; and I haven't tested on full screen multi-monitor, but I have every reason to believe it works. Are you able to try it?

**Comment by dsnkostic** [comment]
@TheCycoONE I took the version from this link: https://github.com/CorsixTH/CorsixTH/releases. It says that it is v0.60. Ctrl+F10 does not work on this one.
I did not took the latest git version as I did not tried to compile it yet.

**Comment by dsnkostic** [comment]
@mugmuggy 
I was not aware that you have continuous integration setup. I unpacked the trunk version and upon hitting Ctrl+F10 solves the issue with multiple monitors. Mouse pointer is now contained within primary monitor.
May I recommend that this feature be enabled by default in the next release version.

Best regards

**Comment by TheCycoONE** [comment]
Sounds reasonable to me.

@mugmuggy do you want to do this? Should go in `config_finder.lua`, somewhere near `prevent_edge_scrolling` I think. true by default, then switch your `self.capturemouse` in `app.lua` to read from that instead.  Also throw it in `config_template.txt`. No need to make an in game option.

**Comment by mugmuggy** [comment]
Sure
