### ISSUE TITLE
Crash on very first startup: write/parse issue with config.txt

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#1287]
#### Describe the issue
Starting CorsixTH for the very first time (~/.config/CorsixTH/config.txt doesn't exist, yet) the game crashes immediately. 

On the second startup the game doesn't crash on startup.

```
An error has occurred in CorsixTH:
./Lua/app.lua:105: Unable to load the config file. Please ensure that CorsixTH has permission to read/write /home/bob/.config/CorsixTH/config.txt, or use the --config-file=filename command line option to specify a writable file. For reference, the error loading the config file was: /home/bob/.config/CorsixTH/config.txt:251: unexpected symbol near <eof>
stack traceback:
	[C]: in function 'error'
	./Lua/app.lua:105: in method 'init'
	./CorsixTH.lua:120: in main chunk
	[C]: in ?
```

#### Steps to Reproduce
1. If `~/.config/CorsixTH/config.txt` exist, remove it
2. Start `./CorsixTH`

#### System Information
**CorsixTH Version:** master branch fe1a526b5f1da2439b71d9641165bd2dcbf1bbc3

**Operating System:** Debian 9.1 i686

**Comment by TheCycoONE** [comment]
Welcome back @bobcanthelpyou 

I can't reproduce this. If I remove either config.txt or ~/.config/CorsixTH it just prompts me for the location of the HOSPITAL directory and then continues properly.

It's also rather suspicious that it's complaining about line 251. Are you confident in your steps to reproduce?

**Comment by bobcanthelpyou** [comment]
Hi @TheCycoONE,

Could be reproduced on Ubuntu Xenial x86_64, too.

Using Lua5.3 on both systems.

Debian: `cmake . && make`
Ubuntu: `cmake -D WITH_LIBAV:BOOL=ON . && make`

**Comment by TheCycoONE** [comment]
Sorry, I can produce it. I just wasn't on a late enough commit on this computer.

**Comment by TheCycoONE** [comment]
The regression happens on commit 80f5e569f715243d6b6861b55db70b29982fae93

At the moment I don't see what would have caused it.
