### ISSUE TITLE
DNA machine room cannot be used

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1289]
#### Describe the issue
once the DNA machine room (dont recall the exact name atm) once build the doctor will act strangely (run in squares making sharp turns over and over) and the patients cannot enter or exit the room. some times the VIP visitors will actually stand in line to be threated as patients, and once even a janitor stand in line. this room its useless and the patients cannot use it.
#### Steps to Reproduce
1. load the game with a level that allows DNA machine room build and usage.

2.build it and set up the correct type of doctor.

3.just wait for doctor's to send the patients and you will see this behavior.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### Expected Behavior
the room should work as in the original game worked.
#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.61 (beta)
**Operating System:** *e.g. Windows 10*
windows 10
**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
GOG.com
#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
Created game with savegame version 119.
Warning: Trying to remove nonexistant room build callback (function: 000002BE9E8E1890) from humanoid (table: 000002BE9D1D1020).
Warning: Trying to remove nonexistant room remove callback (function: 000002BE7184AA50) from humanoid (table: 000002BE9D1D1020).
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Warning: Trying to remove nonexistant room build callback (function: 000001D69B336C70) from humanoid (table: 000001D69A9B4700).
Warning: Trying to remove nonexistant room remove callback (function: 000001D69A2BF2A0) from humanoid (table: 000001D69A9B4700).
Warning: Trying to remove nonexistant room build callback (function: 000001D69B32CEF0) from humanoid (table: 000001D69A9B5280).
Warning: Trying to remove nonexistant room remove callback (function: 000001D65ABE5F20) from humanoid (table: 000001D69A9B5280).
Warning: Trying to remove nonexistant room build callback (function: 000001D69B69ED20) from humanoid (table: 000001D69A4C84C0).
Warning: Trying to remove nonexistant room remove callback (function: 000001D69D026BB0) from humanoid (table: 000001D69A4C84C0).
Warning: Trying to remove nonexistant room build callback (function: 000001D69CBD11F0) from humanoid (table: 000001D69C917660).
Warning: Trying to remove nonexistant room remove callback (function: 000001D69CEA19F0) from humanoid (table: 000001D69C917660).
Warning: Trying to remove nonexistant room build callback (function: 000001D69CBCFA50) from humanoid (table: 000001D69A8EE810).
Warning: Trying to remove nonexistant room remove callback (function: 000001D69D1C0990) from humanoid (table: 000001D69A8EE810).
Warning: Trying to remove nonexistant room build callback (function: 000001D69CBC8B50) from humanoid (table: 000001D69A5DDF30).
Warning: Trying to remove nonexistant room remove callback (function: 000001D6DFA37700) from humanoid (table: 000001D69A5DDF30).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	C:\Program Files\CorsixTH\Lua\world.lua:2134: in method 'removeObjectFromTile'
	C:\Program Files\CorsixTH\Lua\objects\litter.lua:98: in method 'remove'
	...gram Files\CorsixTH\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

### Additional Info
this is needed to threat patients such as the alien decease or contagious deseases as well. without this the game is partially unplayable. also i want to add that even if the specialist sits down on the console, the patients cannot go into the room. is like if it where a invisible patient using the machine non stop. (not the animations but the patients go into queque and then leave after a long while waiting, if they dont die)
also my game its on spanish. i dont know if that might be important.

**Comment by pschoffer** [comment]
Hi there, would you have a safe game of that? Was it repeating issue or just one time thing?

**Comment by overlordchaos** [comment]
i think this happens near the final levels of the quest mode. in free mode in the 0.61 version has not happened again atm. still there are months i give up corsixTH cause i wanted to do a custom level and every time i tweaked more the level values more it break.

**Comment by mugmuggy** [comment]
This reads as the door reservation bug, but with no save, closing.
