### ISSUE TITLE
add a mega hospital sandbox mode.

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1292]
#### Describe the issue
(its a suggestion) add a mega map where ALL the map its a HUGE hospital with a helipad near the entrance. also enable ALL the deceases, and ALL the threatments from start.
in other words, a sandbox mode where you can have 100% EVERYTHING researched. as if you where on the final level of the original game campaign. set the level to have tons of patients. also have at your disposal every month 30 doctor's (at least 5 of each specialization) 20 nurses, 20 janitors.
this is an idea to maximize the game. to see how far you can take it.
also in this mode, keep out rules like how many patients must live to win or die to loose. and set the money to 0. i get there is the free campaign mode, but you are forced to choose a custom map with some rules in (like too much patients and low doctors, or vice versa) to have the true feeling of running a real hospital filled with patients and staff members.

**Comment by tobylane** [comment]
You should be able to make what you want, by editing one of the custom maps you've found ([e.g. Biggen](http://forums.corsixth.com/index.php/topic,4986.0.html)) with [increased staff](https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels#staff_levels), expertise, popn in its levels file. I like your plan and would be interested in what you make.

**Comment by TheCycoONE** [comment]
I'm willing to add a level like this to the built in set if someone makes it.

**Comment by edsilmon** [comment]
@OP Only the level config needs editing to give all researched illnesses and machines. Also the win conditions, availability of staff (good/bad) and a bunch of other things are soley based on the (editable) level config unless they're set for random. 

I find 10 reception desks works well in biggen btw until the GP queue (train) gets larger than 30 people :D 

What would also be good in that level is if there were more doors per room as large parts of the hospital are blocked from others - if you cram rooms in all the space - due to the corridors being only 4 wide though they need only be widened in the editor I guess.

**Comment by overlordchaos** [comment]
i am making a huge hospital witch its ALL the map as a single hube box. no corridors or strange shapes. so you can have 30 GP's, 10 OR's, 20 infirmaries etc. not sure how to actually do all the level editions like good staff. edit the .level as edsilmon says.

**Comment by edsilmon** [comment]
This is an explanation of the .level file setup >> https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels

Be wary of making a giant hospital as the handymen and other spare staff tend to disappear off into the corners unless you make a giant pointless room like a massive toilet to fill in the gap while you build up your hospital rooms (this does work)...

**Comment by overlordchaos** [comment]
@edsilmon yes my idea is more on to make huge rooms. such like an infirmary for 40 patients (one for diagnosis and another for recovery) the GP's would be independent since the game wont allow more than 1 doctor per room. but putting those cases aside, yeah i think to do huge comfortable and usable rooms.
i would need a big staff room considering the kind of hospital i would do will have over 50 staff members, considering doctor's/nurses/handymen's i would need to take care of this kind of facility.
also the big rooms would let you on the fly to choose what corners, and corridors to create. what waiting areas you wanna build. its not just a big box hospital without shape, you give the shape you want making rooms.

**Comment by Alberth289346** [comment]
I think you will find it's boring game play, ie there is no challenge at all in such a level

**Comment by overlordchaos** [comment]
@Alberth289346 i am sorry to tell you, you are WRONG. i am running this hospital at the moment and its insanely complicated. i have over 50 staff members, need to check every time they go to rest there is a replacement, then do more rooms to fit the excess of doctor's/nurses running around once they rest and they location its filled. managing the patients try not to kill them. just because the game does not inforce on you "keep low deaths" you cannot do so by yourself without lossing the level.
i also use the cheats to create 20+ patients at once and one or two emergencies at the same time.
inviting several VIP members to visit the hospital while its clean and running at the top of the charts.
so you see, its not just a stupid idea. i agree its way too big. we need more deceases so we get more exam/consults rooms to use the insane space. but i have used 1/3 of the entire mega hospital and i have 2 of each consult/exam room and like 5 GP's offices plus a HUGE staff room, a big research center (even its not really necesary) and a training room where all my doctor's become consultants before they start working in my hospital. so as you see i am running the game at insane difficulty, set by my own standards.

**Comment by edsilmon** [comment]
I prefer to let the game put doctors in my rooms - which it usually does - but I suppose that is my preference. I also tend to put more smaller staff rooms around the hospital so a rested staff member can go straight there from work and back to work quite quickly _by themselves_. I understand the "wow factor" of having such a large ward (40+beds) but all those patients (and staff) all have to come in and out of the same door so will inevitably end up forming huge queues, either inside the ward to get out or outside the ward to get in. 
I have a save game in a large map (dalhem - i may have included a dropbox link to it and a save file) [ https://www.dropbox.com/sh/p5ctc00ydg177y8/AABlgAzqFIqVHtFzzv6mhkWla?dl=0 ] with one entrance to the hospital and it currently has about 20 GP rooms; at one point I had over 100 doctors until they were adequately trained and I reduced their numbers. I also have 10 reception desks as without them the patients queue out of the front doors! when I last tried I couldn't finish the level as the constant epidemics kept lowering my reputation when I failed to cure them. I have edited the .level file to include a custom template I made for myself (On my computer I have several glitched members of staff who are frozen and never leave! I also had serious problems with patients stuck in the toilets and kept reloading from before and changing the internal layout in the hope it would stop the glitches...).
The game has some limitations in the way it runs and giant rooms may take much more time (maybe too much time) for the patients to use; this probably compares to hospitals of today where they usually have small bays of up to a dozen patients cared for by a couple of staff members. This is a game, of course, though!

**Comment by Alberth289346** [comment]
@overlordchaos  fair enough, if you share the game level that you made, we can add it to the distribution and let others try it too

**Comment by overlordchaos** [comment]
@Alberth289346 will leave a copy here. would love some feedback. from the start i must say there is too much space. i did it in 4 wings and you can purchase them if you need them. this is done when we get new deceases to fit new exam/consultation rooms. any feedback will be enjoyed.
btw this is a map EXCLUSIVELY done to have fun on freemode (sandbox) mode. i always hated the rules of number of patients alive/dead get + or - amount of money, etc. as long as you dont kill too much people on real life you dont get insane rules like "expand your hospital and raise the price tag on it afterwards"
https://drive.google.com/open?id=1gNAVAWCdxqDbzme23Qm4H66zfu0ljCJh

**Comment by TheCycoONE** [comment]
You probably don't want MaxDiagDiff to be 100 across the board. That number is out of 1000 and represents how difficult it is to diagnose a patient with that disease. With a very low number they aren't likely to need to visit many diagnostic rooms, and there is no need for better doctors.

**Comment by overlordchaos** [comment]
@TheCycoONE would love some number that makes the patient go to many diagnosis but not more than once cause this hospital will be able to have 200 patients at once (even if you need to use the cheat to create patients) and even if you have several rooms you will be overloaded eventually.
so any suggestions for maxdiagdiff will be appreciated. i dont trust on default values i remember on the original games having 5 patients visit 5 times each diagnosis.

**Comment by edsilmon** [comment]
@overlordchaos I suggest you test it with default numbers and adjust it after you start; that method will mean you are completely happy with the settings. Nobody but you can configure the level to make you happy.

**Comment by overlordchaos** [comment]
@edsilmon i was asking suggested numbers like this range xxx - xxx will go to all the diagnosis rooms but just once not twice or three times. not exact numbers.
i detected a small issue with my original map and the emergencies. anyone willing to test do so with this one. also tweaked with some values the .maxdiagdiff settings.
https://drive.google.com/open?id=1mSB0ZlPpAear5yyPxDuoE7XUOo02tvaB

**Comment by edsilmon** [comment]
> edit: In fact you can delete that whole column of numbers if you also delete the .MaxDiagDiff part of the line on the left - then it will use the game defaults.

@TheCycoONE Corsix will use the default settings from the 00.SAM Theme Hospital LEVEL files?

**Comment by TheCycoONE** [comment]
By default it uses the settings from https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/base_config.lua#L154

**Comment by overlordchaos** [comment]
@TheCycoONE is there any way to make my level (chaos hospital) not to auto open the doors? aka to disable the timer? so i can open it when i want to? and not before?

**Comment by TheCycoONE** [comment]
Unfortunately the timer is hard coded at present. As a workaround, either slow the game to the minimum speed (which gives you quite a bit of time), or enable build while paused in the config. These aren't level settings though; everyone that wants that functionality would have to do it.

**Comment by overlordchaos** [comment]
@TheCycoONE this has been quiet for some time... i can add my level as a crazy mega sandbox mode or someone else can submit one to add to the distribution if you like.
i have stopped work&play on corsix first i have daily life issues so i dont have the time, plus i got piss off that after a few minutes errors pops out and i get frozen stuck patients/doctor's and loosing rooms. i understand this will take a LONG time to fix and make it playable. i would just wish for a new theme hospital made from scratch in HD with all this functions + way more. the game always struck me as unfinished for all the bugs the original game has (clear example when a machine room blows up the fix from the original devs was "here you have a 10x times bigger hospital you will ever need" as the final original campaign level is)

**Comment by lewri** [comment]
@overlordchaos Now we've had some new version releases did you want to look at if you can make your hospital work better now?

**Comment by Jannikergudingenreklamus** [comment]
[hugesandbox.zip](https://github.com/CorsixTH/CorsixTH/files/10149534/hugesandbox.zip)
made with corsix map editor...
you could have made yourself mate... xD

1 unpack files.
2 copy under levels folder
3 start single mission
4 pick "superduper"
voila.
hospital fills entire screen. (need zoom in to get to edges)
4 entry spots for patients. a helipad for emergencies.
4 times more patient spawn in
also training rooms work at 4 times speed

i made 6 different zones to not keep janitors and heating more easy manage during setup of hospital.

this is version 3 version 1 and 2 keep make pathing error message while playing. this version have not crashed yet during 4 hours game

**Comment by TheCycoONE** [comment]
@Jannikergudingenreklamus do you want to contribute that to [CorsixTH/CommunityContent](https://github.com/CorsixTH/CommunityContent/blob/main/CONTRIBUTING.md)

**Comment by Jannikergudingenreklamus** [comment]
> @Jannikergudingenreklamus do you want to contribute that to [CorsixTH/CommunityContent](https://github.com/CorsixTH/CommunityContent/blob/main/CONTRIBUTING.md)

need more quality and bugfixing. it gives pathfinding errors for maybe 85% new players that is not fair sandbox this was first fix to help person want sandbox (i am quite sure bugs is from overlapping room on 2 or 3 different buytiletype) i can fix that on map side by just tweaking floor design or inserting small walls.

will fix within this week and upload in right place but right now this is where google leads people to find sandbox mission so was more to give an answer to fellow gamers. and need goto dentist was on email to find appointment when realise you replied. i am scared dentist so gonna be really drunk and no position promise change within 2-3 days xD

also i really like fork idea...
is much better than sending raw data and tell where to chip it in xD
will really look into that

**Comment by overlordchaos** [comment]
back after a few years. yeah i wanted a gigantic sandbox... untill two point hospital was released. dissapointed the remaster has the same/worse unfixed bugs the original one has. even on their sandbox version the same pathfind errors are present.
i abandoned corsix/TPH a long time ago (specially when two point studios where sold to SEGA and sega stopped fixing bugs and releasing DLC's bundled with game patches. so if you want your game better, pay for it. ) so i love someone took my idea and tried to bring it to fruition but lets be honest on corsix/original game bugs will never be fully fixed like path finding unless you do some sort of reverse engeneering code to actually fix the game compiled code. thats why i lost all hope for original/corsix/remaster games.

**Comment by Alberth289346** [comment]
CorsixTH doesn't rely on original code, we only use the data files. Thus all code of the program is open source from scratch, fully available and thus fixable.

**Comment by Alberth289346** [comment]
For example, our path-finding algorithm is a proper A* search. It should be correct, but if not, the source code is available and can be fixed.

**Comment by lewri** [comment]
> so i love someone took my idea and tried to bring it to fruition but lets be honest on corsix/original game bugs will never be fully fixed like path finding unless you do some sort of reverse engeneering code to actually fix the game compiled code. thats why i lost all hope for original/corsix/remaster games.

So the majority of bugs in CorsixTH are ours, not TH. As Albert said, we only use the data files (not its logic). However, there are definitely some oddities even in those data files, but we are aware of them and make code to properly handle that exception. The eventual hope is to be stripped completely of any reliance of TH, but this will definitely take time.

**Comment by tobylane** [comment]
There is now a [sandbox level](https://github.com/CorsixTH/CommunityContent/blob/main/Levels/Sandbox/sandboxj.level) in the CommunityContent repository. We don't have a plan for including this public content in releases, is that part of this issue?

**Comment by TheCycoONE** [comment]
I think we're fine pointing people there.
