### ISSUE TITLE
add new diseases & new machinery

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1293]
#### Describe the issue
it would be fun to have new deseases in place, in order to make more realistic the game. this could be added to my previous suggested "mega hospital sandbox mode" and to make new machines, you would not need to redo everything. you can take current machines and change colours, or even mix them up (for example put the DNA analizer with the X ray machine and swap the colours, make the person step on one then in another) take the investigation default machinery to analize people and swap the colors and make it a huge micro wave to cure the popcorn DNA decease, caused by eating too much popcorn each day, etc.
you get what i mean lol. this would help to revitalize the game a bit considering after a while it feels silly not to build nothing and to have a small set of machinerys in the entire hospital.

**Comment by tobylane** [comment]
After the cloning is complete, original ideas like this will become more important. It requires coordination of graphics and code. For now there is [a forum thread on disease suggestions.](http://forums.corsixth.com/index.php/topic,292.0.html)

**Comment by overlordchaos** [comment]
ty tobylane but after 10 or 15 times i could not register for that forum. it says that the letters does not match and wont let me register there. i guess its a glitch?

**Comment by MarkL1961** [comment]
That will be the anti spammers captcha
What user name were you going to use and I'll see if I can sort it
