### ISSUE TITLE
map editor: half way done the game crashed.

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1295]
#### Describe the issue
i was making a mega hospital. was about to be done with the walls and corsixTH crashed on me...
aldo i think it has something to do with the MIDI music i think it play all the songs ingame then crashed.
#### Steps to Reproduce
1. load the map editor and use it about 15 minutes or more

2.create a big map

3.(just obserb)

#### Expected Behavior
NOT to crash in the middle of the creation LOL
#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.61-beta1
**Operating System:** *e.g. Windows 10*
windows 10 x64
**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
gog.com
#### Gamelog.txt
*Not Available*

**Comment by TheCycoONE** [comment]
That game log was not from using the map editor; it must have been from an earlier play through.
If you can reproduce, and run the game from the command line, hopefully their would be helpful output there.

**Comment by overlordchaos** [comment]
@TheCycoONE i just finished the map. not sure why there are random crashes like the one i reported.
and yeah i am using 0.61 beta 1

**Comment by TheCycoONE** [comment]
That's unfortunate. Not much to go on in this ticket, but we'll keep an eye out. Save frequently :(

**Comment by TheCycoONE** [comment]
No way to verify, but some crashes relating to background audio were fixed since this was opened.
