### ISSUE TITLE
add an emergency room

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1296]
#### Describe the issue
(its a suggestion) create an emergency room. it could be a nursery with tweaked colors, and that it needs at least 1 doctor and 1 nurse. also add an option to make the default and only emergency "emergency room" (desease) also it would need the desease of emergency room, something like "critical condition" desease.
the patient would drop from the chopper and go straight to the emergency room. no analisys nothing.
also when patients come from the street (random patients) if they have the "critical condition" its from reception straight to the emergency room. i guess bullfrog never added an emergency room cause this was a kids game in the day, and parents may not be ok to have kids to simulate a hospital with an emergency room witch done properly would deal with some mayor casualties. or maybe they where lazy LOL.

**Comment by TheCycoONE** [comment]
Please keep suggestions for new rooms, equipment, and diseases to the appropriate section of the forums. This issue tracker is not the right place to discuss them at this time.
