### ISSUE TITLE
a humanoid error, after a few minutes the game crashes.

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1297]
#### Describe the issue
i did a mega hospital. i have over 62 doctor's, over 5 nurses and 10 janitors. not to mention dozens of patients.
one of those "humanoids" found an empty action? the game asked at me if i wanted to ask that "humanoid" to leave the hospital, since it could not find the action to do?
i see a patient with an EXIT sign leaving the hospital. minutes later the game crash.
#### Steps to Reproduce
1. https://drive.google.com/open?id=1E2AvmTMVR0LTx0VzJXyOY0bw3lG9N_Ed (save game+custom level/map save game as usual, level+map to corsixTH\levels)

2.load the save + level

3.invoke 2 emergencies at the same time (click twice the cheat, then accept 1 emergency on the fax and in the next one, do the same as fast as you can)

#### Save Game
https://drive.google.com/open?id=1E2AvmTMVR0LTx0VzJXyOY0bw3lG9N_Ed (save game+custom level/map save game as usual, level+map to corsixTH\levels)

#### Expected Behavior
NOT to crash the game, even if an error occurs.
#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.61 beta
**Operating System:** *e.g. Windows 10*
win 10 x64
**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
gog.com
#### Gamelog.txt
Created game with savegame version 119.
Warning: Trying to remove nonexistant room build callback (function: 000002751FD2F4A0) from humanoid (table: 00000274C1AE5600).
Warning: Trying to remove nonexistant room remove callback (function: 000002751FE0DD20) from humanoid (table: 00000274C1AE5600).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Recovering from error in timer handler...
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Recovering from error in timer handler...
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Recovering from error in timer handler...
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Recovering from error in timer handler...
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>
Recovering from error in timer handler...
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: Invalid value for parameter 'x'
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:30: in local 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:74: in global 'WalkAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:102: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:654: in method 'queueAction'
	...rogram Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:341: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

### Additional Info
thats the easy way to get this error. aldo i think its related to have too many AI patients and staff at once. maybe the memory gets corrupted and thats why we get this errors with an "humanoid" not finding his action to do.

**Comment by tobylane** [comment]
The debug menu lets you do unnatural things. Concurrent emergencies or VIP visits create bugs that won't be fixed, but you have a good point about crashes.

If you're looking for extra difficulty in a custom level look into increasing earthquakes and epidemics.

**Comment by TheCycoONE** [comment]
Please use release candidate 1.
