### ISSUE TITLE
An Error Has Occured - Handyman Cleaning Vomit

### ISSUE THREAD

**Issue by The-Kitchen-Sink** [CorsixTH/CorsixTH#1298]
#### Describe the issue
When doing cleanup of patient in the attached save file vomit corsix-th .61 beta 1 X64 throws a recoverable error message with the following displayed in the command prompt.  The recovery works but leaves a ghost handyman in the game.

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
        C:\Program Files\CorsixTH\Lua\world.lua:2134: in method 'removeObjectFromTile'
        C:\Program Files\CorsixTH\Lua\objects\litter.lua:98: in method 'remove'
        ...gram Files\CorsixTH\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
        C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
        C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
        (...tail calls...)
        C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

#### Steps to Reproduce
1. Load test,sav attached (in zip file)
[test.zip](https://github.com/CorsixTH/CorsixTH/files/1523604/test.zip)

2. Error occurs within 10 seconds at normal speed

#### System Information
**CorsixTH Version: .61 beta 1

Windows 10 X64 1709

**Theme Hospital Version: GOG.com

#### Gamelog.txt
```
Created game with savegame version 119.
Warning: Trying to remove nonexistant room build callback (function: 000002E38C412F30) from humanoid (table: 000002E38AF41130).
Warning: Trying to remove nonexistant room remove callback (function: 000002E382A32890) from humanoid (table: 000002E38AF41130).
Warning: Trying to remove nonexistant room build callback (function: 000002E38B4884D0) from humanoid (table: 000002E38B276D80).
Warning: Trying to remove nonexistant room remove callback (function: 000002E38AE27DC0) from humanoid (table: 000002E38B276D80).
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	C:\Program Files\CorsixTH\Lua\world.lua:2134: in method 'removeObjectFromTile'
	C:\Program Files\CorsixTH\Lua\objects\litter.lua:98: in method 'remove'
	...gram Files\CorsixTH\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

```

**Comment by tobylane** [comment]
I've had this error a few times but couldn't reproduce it. Your savegame doesn't work for me -
 game_ui.lua:698: attempt to index a nil value (field 'multigesturemove'). Do you have another example?

**Comment by TheCycoONE** [comment]
Note that handyman cleanup was changed in rc1.
