### ISSUE TITLE
the game became unplayable after a while

### ISSUE THREAD

**Issue by overlordchaos** [CorsixTH/CorsixTH#1301]
#### Describe the issue
every time i play, every time more and more errors pop up. i restarted (after i modified) the chaos hospital to divide it on 4 wings. everything was ok untill the hospital started to work. after 1 patient every doctor on GP's office would give me the "handyman" error that makes them frozen and you cannot move them. in fact when a doctor took his place, the frozen NPC dissapeared, and after the consultation was done, it crashed the doctor again. so i need 1 doctor for each patient.
#### Steps to Reproduce
1. *Load save game attached to this ticket* (and add the custom level to corsixTH\levels

2.just obserb (i saved it once the first doctor crashes)

3.after that each doctor that take that consult will return the same error.

#### Save Game
https://drive.google.com/open?id=1GT_cKD59Fafv14s9pu2te57fzYPWMyF8*

#### Expected Behavior
NOT to crash all the "humanoids"
#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.61 beta
**Operating System:** *e.g. Windows 10*
win 10 x64
**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
gog.com
#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
Created game with savegame version 119.
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entities\patient.lua:182: attempt to perform arithmetic on a string value (field 'MaxDiagDiff')
stack traceback:
	C:\Program Files\CorsixTH\Lua\entities\patient.lua:182: in method 'completeDiagnosticStep'
	C:\Program Files\CorsixTH\Lua\rooms\gp.lua:135: in method 'dealtWithPatient'
	C:\Program Files\CorsixTH\Lua\rooms\gp.lua:81: in method 'loop_callback'
	...ogram Files\CorsixTH\Lua\humanoid_actions\use_object.lua:324: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

additional info:
i installed RC 1 started ONCE again my custom map, and it is giving me the same issues that i have over 0.61 beta. so its not exclusive to the beta version this unplayability issue.

**Comment by TheCycoONE** [comment]
This is because your level file is broken. Your lines with MaxDiagDiff need another number for that value.

**Comment by overlordchaos** [comment]
@TheCycoONE i added 100 (i want all the deceases from the start of the level) as it was previously, started over and i am having the same issue. not to mention every time i see more and more errors. please take a look again at this. in fact mod the .level file at your will and you will see its not just those values.

**Comment by edsilmon** [comment]
MaxDiagDiff is **not** for whether the disease is available at the beginning. It is to set how much effort the disease takes to diagnose. 
To set a disease so it doesn't need research **Known** should be **1**
This page explains it ... https://github.com/sydlawrence/CorsixTH-HTML5-Port/blob/master/source/CorsixTH/Levels/example.level

> The following table contains all diagnoses and treatments that shows up in the drug casebook
> in the game. Known specifies whether it should show up from the beginning of the level and
> RschReqd how much research is required to discover the treatment room for the disease, MaxDiagDiff is how hard it is to diagnose (don't apply to diag rooms).
> #expertise[1].Known.RschReqd 1 0 GENERAL_PRACTICE
> #expertise[2].Known.RschReqd.MaxDiagDiff 1 40000 500 BLOATY_HEAD
