### ISSUE TITLE
Random handymen selected - error has occurred

### ISSUE THREAD

**Issue by CosbyArt** [CorsixTH/CorsixTH#1306]
#### Describe the issue
Seemingly at random a handymen characters personal box will appear, and when it does the game crashes with a attempt to recover (see attached image). The handymen it showed the personal box for was on the other side my map (by the reception desk) so it was not one highlighted by me or click button error.

This error occurred when one of my doctors became a Consultant, and I had no character selected myself or any window/box open.  When it happens if I click the checkmark button to recover the game plays fine afterwards.

I reloaded the save game which was a few calendar days before the day it crashed, and it does not repeat the error.

#### Steps to Reproduce
1. I know of no confirmed way to reproduce the error, and my saved game does not repeat the error now afterwards. I have had it happen on various levels, and it seems to be a random error triggered by a unknown event.

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
v0.61-beta1

**Operating System:** *e.g. Windows 10*
Windows 8.1

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
GOG.com

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Created game with savegame version 119.
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Savegame version is 119 (v0.61-beta1), originally it was 119 (v0.61-beta1)
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\world.lua:2134: attempt to perform arithmetic on a nil value (local 'y')
stack traceback:
	C:\Program Files\CorsixTH\Lua\world.lua:2134: in method 'removeObjectFromTile'
	C:\Program Files\CorsixTH\Lua\objects\litter.lua:98: in method 'remove'
	...gram Files\CorsixTH\Lua\humanoid_actions\sweep_floor.lua:45: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1007: in function <C:\Program Files\CorsixTH\Lua\app.lua:1004>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:908: in function <C:\Program Files\CorsixTH\Lua\app.lua:903>

```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

![handymen1](https://user-images.githubusercontent.com/34206133/34066572-b67e6bba-e1de-11e7-8966-adbd1c2cf276.jpg)

**Comment by TheCycoONE** [comment]
Handyman litter cleanup was modified with CorsixTH 0.61-rc1 to address an issue almost identical to this one; please use the latest release (at this time CorsixTH 0.61-rc2.
