### ISSUE TITLE
Very few patients, resulting in no reputation movement

### ISSUE THREAD

**Issue by Y2chaos** [CorsixTH/CorsixTH#1307]
I have version 0.60, running the game from the Origin download. 

I'm lucky if I am seeing more than ten patients in a fully established Hospital. 

![screenshot 2017-12-18 21 15 15](https://user-images.githubusercontent.com/34662620/34128537-fc248454-e438-11e7-8921-3977f97367ad.png)

Any help would be appreciated

**Comment by TheCycoONE** [comment]
In the original game people will choose one of the 4 player hospitals to visit based on their relative merits. In CorsixTH 25% of people will visit your hospital of your reputation is 500, if your reputation is maxed out then 75% of people will visit your hospital.

The total world population for each month is defined in the level file, usually with a fairly slow ramp up - you can speed up the game to help with that. If you are playing a custom level then the map author controls the population.

Is there anything particular / any level in particular that you think is incorrect?

**Comment by overlordchaos** [comment]
i might suggest using cheats to inflate the population? when a fax comes type with the pointer 24328 then the green button on the fax. click a few times over the cheat "create a patient" wait a bit and you will get extra patients. be careful if you are not ready and you kill them it might be your doom!

**Comment by lewri** [comment]
What is the time frame since opening you are seeing 10 patients? If it is April of year 1 it would be pretty normal to only see a few patients. Between year 1 and year 2 it usually ramps up a bit more. 

Either that or your doctors are so efficient at their job nobody's ever waiting around long!

**Comment by lewri** [comment]
Non-issue
