### ISSUE TITLE
Add toggle option for mouse capture

### ISSUE THREAD

**Issue by DavidFair** [CorsixTH/CorsixTH#1309]
In #1264 and #1280 logic was added to capture the mouse. Whilst this can be toggled with a keyboard shortcut (CTRL+F10) or in the configuration it is not an accessible option for novice users. 

Instead we should add another option called something like `Capture Mouse` in the main options window. Personally this was the first place I looked before having to look at the above PRs to disable mouse capture. 

I'm happy to look into this as the changes should be relatively simple. However I'm posting this issue if anybody has any concerns / feedback before the work is completed?

**Comment by TheCycoONE** [comment]
I am in favour. I would also suggest adding a toggle to the in game menu along side the edge scrolling option here:
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/dialogs/menu.lua#L639
