### ISSUE TITLE
Edge scrolling not saved in config when changed by user

### ISSUE THREAD

**Issue by DavidFair** [CorsixTH/CorsixTH#1311]
In #1310 we noticed edge scrolling is not saving into the config (`menu.lua : 640`) . 

I suspect that other options might also have similar issues. Separately each option in `menu.lua` needs to be checked that is sets the right variable in `app` and that the save method is invoked if applicable.

**Comment by pschoffer** [comment]
Hi @DavidFair,
i would like to have a look on this one. Could you please provide more description for unexperienced person. Some steps to reproduce would be great.

Cheers,
Pavel

**Comment by DavidFair** [comment]
Hi Pavel,

In #1310 we added a new in-game option to toggle mouse capture. Whilst testing the PR we noticed the following:

- Open a new or existing game
- Go to the options menu at the top of the screen
- Toggle edge scrolling on / off
- Restart CorsixTH 
- Load back into a game
- Notice the option was not preserved, so it wasn't written to the configuration file.

On the latest master (not sure if it make it into 0.61) the mouse capture option is saved with the following [code](https://github.com/CorsixTH/CorsixTH/pull/1310/files#diff-6f579cb7d10488a99a2ade280cb97e31R646) 

We need somebody to 
- Go through all of the options in the options menu
- Check they are saved in the config and if not
- If they are not add the relevant code as per above.

Hope this clears up the issue.

**Comment by pschoffer** [comment]
Awesome thanks. I will have a look.

**Comment by pschoffer** [comment]
So I tested the behavior.

The only option that is not being persisted is `Lock Windows`. I am not entire sure what it does to be able to comment it in the config file. Could somebody help me explain what is this switch for?

Also the `Edge Scroling` switch gets persisted, but only when the game is closed while the others when the save is made. I will try to figure out why and update here.

**Comment by TheCycoONE** [comment]
Any time saveConfig is called, all of the persisted config entries are saved including edge scrolling, but not triggering the save is a bug.

Lock windows prevents dragging around the in game dialogs. It seems to have never been made a persistent config option at all... My guess is that no one ever uses it, as I can't think of a use case.

I don't mind whatever you decide to do or not do with that one.
