### ISSUE TITLE
0.61(?) installer reported to contain a virus

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1316]
Today (dec 30, 2017), the following was said at IRC:
```
(16:36:22) phex [XXXXXXXX@gateway/web/freenode/ip.XXX.XXX.XXX.XXX] entered the room.
(16:36:32) phex: hello
(16:36:39) phex: when downloading for windows
(16:36:48) phex: chrome claims the installer has a varus
(16:36:53) phex: virus*
(16:42:57) phex left the room (quit: Quit: Page closed).
```
Can't say anything about

**Comment by TheCycoONE** [comment]
Not our problem? Some virus scanners will identify anything unrecognized. No info here.

**Comment by bobcanthelpyou** [comment]
CorsixTH_v0.61_Windows_Portable.zip:
https://www.virustotal.com/#/url/eb28dde5938f7f8d1ba867d34b284cc1be1a0783c36a3e1d18e67f8c75ada60e/detection (url)
https://www.virustotal.com/#/file/8228c30f14cf30efa119cf1709d486a904e211320f76b644f6347c2058ad0848/detection (file)

CorsixTHInstaller.exe:
https://www.virustotal.com/#/url/a8f5357cee31e2090c8ed9339188e9bfa452fbeadf3f1c28ddd5826a8213d958/detection (url)
https://www.virustotal.com/#/file/5847436aac53aff7be34e30e1779223c06e9d140f2313bdbe4b0da38804dbb6c/detection (file)

**Comment by TheCycoONE** [comment]
Yep, false positives. Baidu seems notorious for that.
