### ISSUE TITLE
Loading currently broken on macOS

### ISSUE THREAD

**Issue by robbyt** [CorsixTH/CorsixTH#1320]
#### Describe the issue
I installed via Homebrew, and when I load a saved game (that works on Windows) I get the following error. This happens with all save files. I know that macOS seems to be unsupported, and so I'm happy to help debug this error if I can get some advice on where to begin debugging this.

```
A stack trace is included below, and the handler has been disconnected.
CorsixTH.app/Contents/Resources/Lua/ui.lua:949: attempt to index field 'windows' (a boolean value)
stack traceback:
	CorsixTH.app/Contents/Resources/Lua/ui.lua: in function 'callback'
	CorsixTH.app/Contents/Resources/Lua/ui.lua:669: in function 'dispatch'
	CorsixTH.app/Contents/Resources/Lua/app.lua:753: in function <CorsixTH.app/Contents/Resources/Lua/app.lua:748>

Warning: No event handler for keydown
Cannot check for updates since LuaSocket is not available.
<LocalisedString> Current value:Error while loading game: CorsixTH.app/Contents/Resources/Lua/persistance.lua:234: sync fail after 720 objects (13847 bytes)
```

#### Steps to Reproduce
1. brew install corsixth
2. save a game
3. load that save

**Comment by TheCycoONE** [comment]
Nothing suspicious stands out about the Homebrew formulae. Please post one of your saves.

**Comment by TheCycoONE** [comment]
The error is a bit strange. I'm interested to see your app as well.

**Comment by robbyt** [comment]
I did a bit more testing, and found that a very simple save file produced on the mac can be loaded. However, the attached save file cannot be loaded on the mac (but it will load on the Windows).

I've also attached the .app file that brew generated.

[2018.sav.zip](https://github.com/CorsixTH/CorsixTH/files/1602256/2018.sav.zip)
[CorsixTH.app.zip](https://github.com/CorsixTH/CorsixTH/files/1602257/CorsixTH.app.zip)

**Comment by robbyt** [comment]
One more note, after installing CorsixTH with Homebrew, I had to manually install luafilesystem and lpeg using `luarocks`.

**Comment by TheCycoONE** [comment]
Indeed I can open that save fine in ArchLinux ARM. I see also that the save is produced in 0.61.

That said, the app you posted is not CorsixTH v0.61, it's 0.40!

**Comment by TheCycoONE** [comment]
From my reading of https://github.com/Homebrew/homebrew-core/blob/master/Formula/corsixth.rb lpeg and luafilesystem should be bundled. My best guess at the moment is that you are running an older app you had installed before.

**Comment by robbyt** [comment]
You're correct- homebrew does not place the .app into /applications, and so I was using an older binary.

Thank you for your help, and making such a great port of this game!
