### ISSUE TITLE
Hospital is extremely cold

### ISSUE THREAD

**Issue by vertibird** [CorsixTH/CorsixTH#1338]
I am playing the campaign. In every level my hospital is freezing no matter how many radiators I put and maxing the temperature from town screen doesnt help at all. All my doctors are constantly requiring a raise due to cold.
My Savegame is here:
https://drive.google.com/open?id=1tsAIzHP0hz6ceDqHwbbjv5BXpm7NIl4E

#### System Information
**CorsixTH Version: 0,61

**Operating System:** *e.g. Windows 7 64 bit
**Theme Hospital Version: GOG.com

#### Gamelog.txt
There is no gamelog.txt file (there is no txt file in the same folder of config file).

### Additional Info
![cold](https://user-images.githubusercontent.com/35659951/35195351-3ff597c2-fed3-11e7-8e82-214d2e5ddf23.jpg)

**Comment by overlordchaos** [comment]
you need to spread out the radiators. you need to place them on the hallways as well as chairs so patients can sit down while they wait on the queque to be cured or diagnosed.
add some trashcans to avoide excesive dirt and reduce rat problems in the future.
also on big hallways and big rooms (surgery room an example on this shot) i would recommend add a radiator every 5 tiles. outside the surgery ward you could put 1 radiator on each side of the door. then 2 more one right next to the building door and another one near the surgery ward.
also add one or two expending machines cause the heat will cause patients to get thirsty. and when you are heated or over heated patients will need their soda to survive!

**Comment by vertibird** [comment]
as you can see in the picture, there are two radiators near the doctors, radiator temp is maxed, and the warmth color on minimap is completely blue, not even a little green or red on the building operating table is in. Try the save, you cant increase the heat even if you put 30 radiators.

**Comment by TheCycoONE** [comment]
Most of your hospital is a fine temperature. That said there is an issue with the heat distribution it seems. You can see in the above screenshot there is a 22.8 next to a 4.2 with nothing in between to stop the flow. I watched this over many ticks and it doesn't change.

**Comment by vertibird** [comment]
Is there a fix to this problem?

**Comment by TheCycoONE** [comment]
@vertibird not at this time. This is the first I am aware of it.

**Comment by TheCycoONE** [comment]
I can reproduce in any new game.

**Comment by vertibird** [comment]
I wish you luck! Thanks for looking up!

**Comment by vertibird** [comment]
Good job dev! I await the new update.

**Comment by tmarplatt** [comment]
I'm sorry for the dupe issue, but before I did so I searched and found this one first, and it did not seem like the same issue at all (submitter comments on hospital being cold, while I can avoid that by placing all radiators generally in southeast corners). 

In fact nowhere before this comment it's mentioned that radiators irradiate heat diagonally northwest, ignoring their immediate southeast area.

**Comment by TheCycoONE** [comment]
No problem. It was never explicitly called out in the comments. The PR associated with this issue is more explicit.
