### ISSUE TITLE
Error message added in #1336 crashes error handler

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1353]
#### Describe the issue
In #1336 a nice error message was added to humanoid that should dump the humanoid table if there is no action. However unlike the error handler in Luacheck the error trap in CorsixTH cannot handle table error messages.

#### Steps to Reproduce
1. Change the condition that generates the error to `if true`
2. Open any new or save game

#### Expected Behavior
Should generate the nice error message described in the PR, along with a stack trace, and insert these errors into the game log; with the usual error handler dialog on screen.

#### System Information
**CorsixTH Version:** 408623ef546c42

**Operating System:** ArchLinuxARM aarch64

**Theme Hospital Version:** GOG.com

### Additional Info
```
An error has occurred in CorsixTH:
/home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:2297: attempt to concatenate a table value (local 'str')
stack traceback:
        /home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:2297: in method 'dumpGameLog'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:959: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:902>
        (...tail calls...)
        [C]: in ?
```

**Comment by TheCycoONE** [comment]
Ping @pschoffer

**Comment by pschoffer** [comment]
Damn:) I am on it (in the evening)!
