### ISSUE TITLE
Not continuing to next level

### ISSUE THREAD

**Issue by tbhosman** [CorsixTH/CorsixTH#1354]
#### Describe the issue
I'm in level 5 of the default campaign, but never got the offer to continue to the next level. I've more than passed all conditions to pass the level but never got the fax for the next level. Also tried using the "win level" cheat, but that does not give me the fax either. Tried restarting the level and using the cheat, but still no luck.

Any ideas? Also happy with a save file of level 6.

#### Steps to Reproduce
Issue is already happening in attached save file.

#### Save Game
[https://1drv.ms/u/s!Au2RZTv4zztSitpioYoJsYDrhjnt_Q](https://1drv.ms/u/s!Au2RZTv4zztSitpioYoJsYDrhjnt_Q)

#### Expected Behavior
Continuation to level 6.

#### System Information
**CorsixTH Version:** 5.3

**Operating System:** Windows 8.1

**Theme Hospital Version:** Origin

#### Gamelog.txt
None in map?

### Additional Info
None.

**Comment by tobylane** [comment]
You're $5500 short of the target value. If you put 11 drinks machines (or anything of that value) in the hospital there's a winning fax at the end of the quarter. Winning by the cheat menu works, before making any changes to the hospital.

**Comment by MarkL1961** [comment]
I was just going to say the same, you are not meeting all the win conditions yet

**Comment by tbhosman** [comment]
Thanks, this worked. I don't quite understand though, 120k hospital value is not mentioned in the briefing?

**Comment by MarkL1961** [comment]
Not every condition is mentioned in the briefing, best to view the status screen
