### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by gBringout** [CorsixTH/CorsixTH#1358]
#### Describe the issue
Text wrongly translated in French. Text is at the moment (line 210 in french.lua):   
`  promotion_to_specialist = "L'un de vos INTERNES est devenu MÉDECIN.", -- Fix the famous "Level 5 bug""`

#### Steps to Reproduce
1. Train a doctor to be a specialist

#### Expected Behavior
1. Text should be (line 210 in french.lua) : 
`promotion_to_specialist = "L'un de vos MÉDECIN est devenu un SPÉCIALIST.", -- Fix the famous "Level 5 bug"`

#### System Information
**CorsixTH Version:** *CorsixTH_v0.61_Windows_Portable*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *CD*

**Comment by wolfy1339** [comment]
Thanks for the report. Is it like that in the original game?

**Comment by gBringout** [comment]
I do not remember how it was. But comparing with the other languages, it makes sense for me.
But, the caps does not make any sense (for the french language and comparing with the other string in the files). I would prefer something like (Note the s at médecins and e at spécialiste):

`promotion_to_specialist = "L'un de vos médecins est devenu un spécialiste.", -- Fix the famous "Level 5 bug"`

**Comment by wolfy1339** [comment]
This was closed by #1367
