### ISSUE TITLE
Machines placed with invalid intial state

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1369]
#### Describe the issue
Since #1346 machines placed initially with invalid state

#### Steps to Reproduce
Build room, with machine - times_used is invalid. Prevents picking up the machine and placing it again and on other calls, machineUsed, getRemainingUses and updateDynamicInfo

### Additional Info
![image](https://user-images.githubusercontent.com/8009292/37890156-d401aa3e-3112-11e8-8257-2f53efe37a32.png)

**Comment by mugmuggy** [comment]
Ping @pschoffer

**Comment by pschoffer** [comment]
Damn it my changes breaks a lot of stuff:( Sorry. I will fix it soon hopefully.
