### ISSUE TITLE
Norwegian translation updates

### ISSUE THREAD

**Issue by Grimdoc** [CorsixTH/CorsixTH#1373]
Updated norwegian translation file, based upon trunk.
Also did some cleaning up on the "tooltips" section of the file.
Zipped the file, so it could be uploaded.
[norwegian.zip](https://github.com/CorsixTH/CorsixTH/files/1868044/norwegian.zip)

**Comment by Alberth289346** [comment]
@Grimdoc
Hi, I just converted your zip above to a commit in #1437 
I removed the BOM marker from the start of the file, and deleted all whitespace at the end of the lines.

No idea what you actually changed, you moved so many lines around, git can't make head or tails from it. Basically it says "these 35 pages of text got replaced by those 35 pages".

Anyway, above, AdamFx990 tried some other changes as well, but those never got merged. Is there anything worth rescuing in those changes?

**Comment by Grimdoc** [comment]
No, I don't think the changes by AdamFx990 is worth rescuing.
If I recall right, some of it was even wrong.

Thanks for the help :)

**Comment by Alberth289346** [comment]
Ok, thanks for the check, let's see if this can be merged now :)

**Comment by tobylane** [comment]
Merged in 1437
