### ISSUE TITLE
golf stones income is not accounted

### ISSUE THREAD

**Issue by obama** [CorsixTH/CorsixTH#1374]
#### Describe the issue
after the patient got the golf stones removed the dollar bill shows above his head, but no money is accounted to the bankaccount.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. wait till surgery is done

3.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Windows 10

[golfstones.sav.txt](https://github.com/CorsixTH/CorsixTH/files/1875501/golfstones.sav.txt)

**Comment by mugmuggy** [comment]
Patient is 'insured' so the payments come later.
```
  -- All payment that goes through an insurance company a given month is paid two
  -- months later. For example diagnoses in April are paid the 1st of July
```
