### ISSUE TITLE
More natural meandering

### ISSUE THREAD

**Issue by Brainsample** [CorsixTH/CorsixTH#1376]
Idle doctors in the corridor often move like a rapidly deflating balloon. They walk in several random directions without pause. If every walk action is followed by a pause, it looks more natural (at least to my eyes).

\Lua\humanoid_actions\meander.lua meander_action_start() line 97:

```lua
  local procrastination
  if action.can_idle then
    action.can_idle = false
    procrastination = IdleAction():setCount(math.random(5, 40)):setMustHappen(action.must_happen)
  else
    action.can_idle = true
    procrastination = WalkAction(x, y):setMustHappen(action.must_happen)
  end
  humanoid:queueAction(procrastination, 0)
```

**Comment by TheCycoONE** [comment]
Do we need more state for this, or is it just as natural to idle randomly?

**Comment by Brainsample** [comment]
When idling is random, there can be two or more consecutive walk actions, which looks 'bouncy'.
You wouldn't notice two consecutive idle actions, of course. :)

But alternating idle and walk actions are never bouncy, still the doctors look busy and alive.
It's subjective, maybe some people even like the bounciness?
Give it a try, I think you will like it. :)

**Comment by Brainsample** [comment]
Hmmm, I think I know what you mean.
This seems work just as well:

```lua
  humanoid:queueAction(procrastination, 0)
  humanoid:queueAction(WalkAction(x, y):setMustHappen(action.must_happen))
```

**Comment by TheCycoONE** [comment]
Ok, thanks for looking

**Comment by TheCycoONE** [comment]
@Brainsample why isn't this a PR?

**Comment by TheCycoONE** [comment]
Fixed
