### ISSUE TITLE
Add warning when hospital entrance cannot be reached

### ISSUE THREAD

**Issue by AlexUrbanAc** [CorsixTH/CorsixTH#1378]
**CorsixTH Version:** 0.61
[Empty Hoppalong hospital](https://github.com/CorsixTH/CorsixTH/files/1886490/Hoppalong.zip)
[Last autosave before error occured](https://github.com/CorsixTH/CorsixTH/files/1886491/Autosave2.zip)
[Another try also failed](https://github.com/CorsixTH/CorsixTH/files/1886499/Hoppalong.2.zip)

**Operating System:** Windows 10
**Theme Hospital Version:** GOG.com

#### Gamelog.txt
Created game with savegame version 122.
Savegame version is 122 (v0.61), originally it was 122 (v0.61)
Error in timer handler: 
D:\CorsixTH\Lua\humanoid_actions\seek_reception.lua:59: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
        D:\CorsixTH\Lua\humanoid_actions\seek_reception.lua:59: in field '?'
        D:\CorsixTH\Lua\entities\humanoid.lua:578: in upvalue 'Humanoid_startAction'
        D:\CorsixTH\Lua\entities\humanoid.lua:670: in local 'timer_function'
        D:\CorsixTH\Lua\entity.lua:216: in method 'tick'
        D:\CorsixTH\Lua\world.lua:1051: in method 'onTick'
        D:\CorsixTH\Lua\app.lua:1008: in function <D:\CorsixTH\Lua\app.lua:1005>
        (...tail calls...)
        D:\CorsixTH\Lua\app.lua:909: in function <D:\CorsixTH\Lua\app.lua:904>

EDIT: The issue can be circumvented by buying lots of the hospital early. It seems both main entrances on the Hoppalong map are not reachable by pathfinding, and from the error message I guess getPathDistance returns false if no path is found.

**Comment by MarkL1961** [comment]
Yes it is a flawed map, there has to be a route to the edge of the map from the start.

**Comment by TheCycoONE** [comment]
I'm open to closing this, or making it a feature request on a path sanity check when starting a level.

**Comment by MarkL1961** [comment]
Perhaps the sanity check should be in the map making, maybe on save.
Yes you would get a warning if you saved the map during making it, but if on save there was a warning that it would not be playable and the same with hele-pads it would save this from happening.

In Settlers 3 when map making there was an option to see your map in-game.  It would be at this point the game would list all the things that were wrong with your map if you were to try and play it - is this something we could have?

**Comment by AlexUrbanAc** [comment]
I would think that the game shouldn't break at line 59, but maybe give a warning to the player.

**Comment by lewri** [comment]
I'm going to suggest linking this up with #826 as a reminder that hospital entrance shouldn't be blocked off in any situation.

**Comment by Alberth289346** [comment]
#826 is about **allowing** blocking, while this is about **not allowing**. Seems like different goals to me. Also this is outside the hospital where a user cannot fix anything.

**Comment by TheCycoONE** [comment]
Yes, this is independent of 826. It's simply validation in the map editor that the map is sane.
