### ISSUE TITLE
SDL2: Map Editor does not compile

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#138]
The map editor depended on the OpenGL back end which is no longer part of SDL2.  Because of this it doesn't compile in the SDL2 branch.

**Comment by rallymoose** [comment]
just a tip... take a look at: https://github.com/bkaradzic/bgfx#what-is-it 
might help?

**Comment by TheCycoONE** [comment]
The approach I've been advocating for is to make the map editor part of CorsixTH with SDL2.  This allows reusing the most code. I have been suggesting that people could take over from my own early experiments with this at https://github.com/TheCycoONE/CorsixTH/tree/sdl2_mapedit_builtin if they want, or start from scratch and copy the functionality out of MapEdit into CorsixTH dialogs.

That said, if someone submits a cross platform map editor that works (using any technology, toolkit, or rendering engine) it will be appreciated.

**Comment by Lego3** [comment]
We are working on integrating the Map Editor into the game, that is being tracked in #639 .
