### ISSUE TITLE
map_editor.lua:1517 attempt to call a nil value (method 'updateDebugOverlay')

### ISSUE THREAD

**Issue by AlexUrbanAc** [CorsixTH/CorsixTH#1387]
**CorsixTH Version:** 0.61

**Operating System:** Windows 10
**Theme Hospital Version:** GOG.com

#### Gamelog.txt
Created game with savegame version 122.
Error in buttonup handler: 
D:\CorsixTH\Lua\dialogs\resizables\map_editor.lua:1517: attempt to call a nil value (method 'updateDebugOverlay')
stack traceback:
	D:\CorsixTH\Lua\dialogs\resizables\map_editor.lua:1517: in method 'onMouseUp'
	D:\CorsixTH\Lua\window.lua:1462: in field 'onMouseUp'
	D:\CorsixTH\Lua\ui.lua:654: in function <D:\CorsixTH\Lua\ui.lua:641>
	(...tail calls...)
	D:\CorsixTH\Lua\app.lua:909: in function <D:\CorsixTH\Lua\app.lua:904>

#### Steps to reproduce
- Start Map Editor.
- Open existing hospital (File -> Load).
- Select "Heliport 1".
- Open other hospital (File -> Load).
- Select "Heliport 1".

**Comment by TheCycoONE** [comment]
Cannot reproduce with the given instructions on the current version.
@AlexUrbanAc is this an issue you can reproduce every time, or something that only happened once? Did it matter which maps you clicked?

**Comment by mugmuggy** [comment]
I can reproduce same error a little differently.

Map Editor
Load but don't select a map yet
Click on anything with a text overlay (Parcel/Camera/Helipad)
Then select your map file

**Comment by TheCycoONE** [comment]
Suppressing the error is easy enough, but the real problem is that mouse events are leaking through the dialog, so the same mouseup that loads the new map is also triggering the mouseup even in the map editor dialog (before the button state changes but after the map object is replaced? To determine)
