### ISSUE TITLE
cmake uses wrong include directory when lua 5.2 is available

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#139]
Many distributions package both lua5.1 and lua5.2.

As a convention the include directory for lua5.1 is typically placed under /usr/include/lua5.1
cmake however finds lua5.2 and fills in the lua include directory as /usr/include

It should check the more specific directory first.

**Comment by lewri** [comment]
@TheCycoONE is this issue still present in Lua 5.3?

**Comment by TheCycoONE** [comment]
We fixed it by adding support for 5.2 and 5.3 :wink:
