### ISSUE TITLE
The game auto zoom in

### ISSUE THREAD

**Issue by TheGreatWood** [CorsixTH/CorsixTH#1390]
#### Describe the issue
I have just installed the 0.61 version but when I play, the game automatically zooms in after a few seconds. It's very annoying. How to fix it?
#### Steps to Reproduce
1. *Load save game attached to this ticket*

2.

3.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by TheCycoONE** [comment]
That is weird... I have never heard of it happening. Try unplugging your mouse

**Comment by lewri** [comment]
Is there another copy of the savegame? It seems to not be attached to the issue :(

**Comment by TheCycoONE** [comment]
Closing as this is not reproducible, and there has been no response for months.
