### ISSUE TITLE
Crash on starup / snap package (vanilla Ubuntu 18.04)

### ISSUE THREAD

**Issue by ultraviolet-1986** [CorsixTH/CorsixTH#1398]
Nothing happens when clicking on the app icon, and issuing the command `snap run corsixth` on Ubuntu 18.04 gives the following output:

```
---------------------------------------------------------------

Welcome to CorsixTH v0.61!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occurred in CorsixTH:
/snap/corsixth/1/CorsixTH/Lua/app.lua:152: Failed loading libGL.so.1: libGL.so.1: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in function 'assert'
	/snap/corsixth/1/CorsixTH/Lua/app.lua:152: in function 'init'
	/snap/corsixth/1/CorsixTH/CorsixTH.lua:120: in main chunk
	[C]: in ?
bootstrap.cpp:53: attempt to index local 'video' (a nil value)
```

Thank you very much for your time.

**Comment by wolfy1339** [comment]
The error suggest that it can't find the OpenGL library.

**Comment by ultraviolet-1986** [comment]
Thanks, in that case, it looks more like an issue with a missing dependency in the snap itself - I've just posted a link to the Snapcraft team here: <https://github.com/snapcrafters/corsixth/issues/1>. I'll mark this as a non-issue at this end as the repo/source versions appear to work fine.

Thanks again ^_^b

**Comment by TheCycoONE** [comment]
I guess this means that you are making a snap for us. \o/

**Comment by ultraviolet-1986** [comment]
I made a pull request (single line) to the snapcrafters team repo and it was accepted - the fix is in the stable channel now. I can verify it works (better than the bionic repos version) :)

You're welcome, thanks to popey too ^_^b
