### ISSUE TITLE
cmake luapath vs luajitpath

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#140]
While experimenting with building the program from scratch, I found cmake could be fooled into believing it has LuaJIT, while it doesn't exist at the system
See the following shell commands (run after each other, I added some horizontal lines to make it more clear where the next command starts.
## (Further discussion below the commands)

$ git clean -f -x
Removing CMakeCache.txt
Removing CorsixTH/Makefile
Removing CorsixTH/Src/config.h
Removing CorsixTH/cmake_install.cmake
Removing Makefile
Removing cmake_install.cmake

---

$ cmake -DWITH_MOVIES=OFF -DWITH_LUAJIT=ON .
Note: Using SDL as renderer (default)
Note: SDL audio is enabled (default)
Note: FFMPEG video is disabled
Note: FreeType2 is enabled (default)
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file alloca.h
-- Looking for include file alloca.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found

Building CorsixTH
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL: /usr/lib64/libSDLmain.a;/usr/lib64/libSDL.so;-lpthread (found version "1.2.15") 
  SDL found
CMake Error at CMake/FindLua.cmake:70 (MESSAGE):
  Could not find LuaJIT
Call Stack (most recent call first):
  CorsixTH/CMakeLists.txt:111 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "$HOME/corsix-th/CorsixTH/CMakeFiles/CMakeOutput.log".
See also "$HOME/corsix-th/CorsixTH/CMakeFiles/CMakeError.log".

---

$ cmake -DWITH_MOVIES=OFF -DWITH_LUAJIT=OFF .
Note: Using SDL as renderer (default)
Note: SDL audio is enabled (default)
Note: FFMPEG video is disabled
Note: FreeType2 is enabled (default)

Building CorsixTH
  SDL found
-- Found Lua library: /usr/lib64/liblua-5.1.so
-- Found Lua: /usr/lib64/liblua-5.1.so  
  Lua found
-- Found SDL_mixer: /usr/lib64/libSDL_mixer.so (found version "1.2.12") 
  SDL_mixer found
-- CMAKE_MODULE_PATH=$HOME/corsix-th/CorsixTH/CMake
-- Found Freetype: /usr/lib64/libfreetype.so (found version "2.5.0") 
  FreeType2 found
-- Configuring done
-- Generating done
-- Build files have been written to: $HOME/corsix-th/CorsixTH

---

$ cmake -DWITH_MOVIES=OFF -DWITH_LUAJIT=ON . 
Note: Using SDL as renderer (default)
Note: SDL audio is enabled (default)
Note: FFMPEG video is disabled
Note: FreeType2 is enabled (default)

Building CorsixTH
  SDL found
-- Found LuaJIT library: /usr/lib64/liblua-5.1.so
  LuaJIT found
  SDL_mixer found
-- CMAKE_MODULE_PATH=$HOME/corsix-th/CorsixTH/CMake
  FreeType2 found
-- Configuring done
-- Generating done
-- Build files have been written to: $HOME/corsix-th/CorsixTH

---

LuaJIT was not at the system, and indeed, after "make", and starting the game, it produces the usual "JIT not available" message.

TheCycoOne found the reason:
(09:02:27 PM) TheCycoONE: AlbertFree: ahh, it uses the same variable for the luajit path and lua path, so without clearing the cmakecache it doesn't look anywhere different
(09:02:28 PM) TheCycoONE: that might be considered an issue
(09:02:38 PM) TheCycoONE: yeah, lets call that an issue
(09:02:53 PM) TheCycoONE: delete your cmakecache and it should work, but it would be nice if you filed that

**Comment by lewri** [comment]
@TheCycoONE is this still a relevant issue?

**Comment by TheCycoONE** [comment]
The `WITH_LUAJIT` flag does nothing anymore except change the error message. It should be dropped entirely.
