### ISSUE TITLE
Game crashes right after opening movie and subsequent movies

### ISSUE THREAD

**Issue by lekoook** [CorsixTH/CorsixTH#1409]
#### Describe the issue
See title.
Someone on irc suggested to me to disable the intro movie in config.txt and I did. Made it to the menu but game crashes again after the "board game" movie. So I disabled movies entirely and the first level loaded successfully.
There seems to be some issues with compiling as well. I had to copy the contents of /source_dir/CorsixTH/ to /usr/local/share/corsix-th/ in order to run the game. Else an error pops up saying: "CorsixTH.lua not found" in the above directory.

#### Steps to Reproduce
1. Compile and build CorsixTH

2. Run ./corsix-th

3. Game crashes after the opening movie

#### System Information
**CorsixTH Version:** *0.61*

**Operating System:** *Ubuntu 16.04*

**Theme Hospital Version:** *Origin*

#### Gamelog.txt
crash log: https://pastebin.com/hgBy4ggE

**Comment by TheCycoONE** [comment]
@lekoook are you able to try the latest git version of CorsixTH. I have made changes to the memory handling in movies - though mostly from the point of view of patching memory leaks. Asan is clean for me.

As for compiling the latest git version. Read the instructions on the wiki. In particular if you had to copy the source directory then you are missing -DUSE_SOURCE_DATADIRS=ON

**Comment by LeDocteurr** [comment]
@TheCycoONE : I think it would be a good idea to also have a "night build" available for download, at least from time to time, many people posting issues here are not developers and only come here from the main CorsixTH webpage to report bugs.

**Comment by TheCycoONE** [comment]
We have CI builds for Windows - https://github.com/CorsixTH/CorsixTH/wiki/Testing-Builds

**Comment by lekoook** [comment]
@TheCycoONE ahh yes that flag solved the compiling issue. The wiki didnt mention using that flag rather just "cmake .." so I assumed. But running the Lua 5.3 version's command doesnt seem to work as well even with 5.3 libraries installed.

As for the movie, I just re cloned the repo again and compiled again. Same issue unfortunately.
Crash log: https://pastebin.com/w8UAPHS4

**Comment by TheCycoONE** [comment]
Unfortunately as I said, with ASAN enabled I am not seeing any bad memory access. I am using ArchLinux ARM with ffmpeg 4.

Your backtrace is in a free and hints at earlier corruption.

Depending on how comfortable you are with this stuff you could run asan or valgind yourself, or post your ffmpeg version and md5 hashes of your movie files and I'll see what I can spot anything.

**Comment by TheCycoONE** [comment]
Can confirm I'm getting a double free on Ubuntu 14.04 in the latest master. I must have broken compatibility with old ffmpeg / libav versions inadvertently.

**Comment by TheCycoONE** [comment]
The above PR fixes the regression in 16.04 entirely for me. 14.04 / LibAV seems to have other problems, but they are unrelated to this ticket.

**Comment by TheCycoONE** [comment]
Further tests show that my 14.04 / LibAV VM behaves the same way in all versions back to 0.50, which is the first version it will build on; so that aspect is not a regression.
