### ISSUE TITLE
can't run the game on macOS High Sierra 

### ISSUE THREAD

**Issue by utkusen** [CorsixTH/CorsixTH#1413]
#### Describe the issue
I'm selecting game folder with corsixTH app, when I press "OK" button, nothing happens

#### Steps to Reproduce
1. brew install corsixth

2. Download the demo

3. run corsixth

4. Select HOSP folder on corsixth app

#### System Information
**CorsixTH Version: v0.61

**Operating System:** macOS High Sierra 10.13.4

**Theme Hospital Version:** Demo

#### Gamelog.txt
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The multigesture handler.
A stack trace is included below, and the handler has been disconnected.
.../corsixth/0.61_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:1100: attempt to call a nil value (method 'onMultiGesture')
stack traceback:
	.../corsixth/0.61_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:1100: in function <.../corsixth/0.61_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:1099>
	(...tail calls...)
	.../corsixth/0.61_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:909: in function <.../corsixth/0.61_1/CorsixTH.app/Contents/MacOS/Lua/app.lua:904>

Warning: No event handler for multigesture
```

**Comment by TheCycoONE** [comment]
Does this error happen every time for you? I have run this brew version of CorsixTH on MacOS High Sierra before.

I can see the error in the stack trace, and there is indeed a problem; but it should only trigger if you use a multitouch gesture in main menu, or during the intro movie.

**Comment by TheCycoONE** [comment]
GOG.com version worked, demo didn't, but the error was about the multigesture event handler? That is very curious.

**Comment by TheCycoONE** [comment]
Could you see if your gamelog.txt is always the same, or if the error there is actually unrelated to the not starting?
