### ISSUE TITLE
Add support for Flatpak packages

### ISSUE THREAD

**Issue by LeandroStanger** [CorsixTH/CorsixTH#1416]

**Comment by TheCycoONE** [comment]
I am open to the idea, but not willing to take it on myself. Do you have any experience?

**Comment by LeandroStanger** [comment]
@nedrichards @TingPing could help?

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I've never made a Flatpak before, or contributed to this project, but I think I could learn how. I will look into this.

**Comment by LeandroStanger** [comment]
Publish the app on Flathub
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by TheCycoONE** [comment]
So is the first step to fork flathub under CorsixTH and create the branch? I can do that. I would like someone else to write the manifest file. The App ID should be com.corsixth.CorsixTH

**Comment by TheCycoONE** [comment]
https://github.com/CorsixTH/flathub/tree/com.corsixth.CorsixTH

**Comment by rmnvgr** [comment]
Hello,

I've written a manifest for CorsixTH: https://github.com/rmnvgr/flathub/tree/com.corsixth.CorsixTH

If it looks good to you, I'll create a PR to make it available on Flathub.

**Comment by TheCycoONE** [comment]
It's not clear to me if it's possible but it would be nice to provide wayland support if available. I see the fallback-x11 socket in the documentation, but I can't tell how you would toggle SDL_VIDEODRIVER=wayland based off that.

Certainly not a requirement if it's not possible.

**Comment by TheCycoONE** [comment]
One other note, since my prior comments on this ticket our appstream metadata id and desktop id was changed to com.corsixth.corsixth, in accordance with the guidelines: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic so the flatpak should have the same application id.

**Comment by rmnvgr** [comment]
> It's possible to trim down ffmpeg quite a bit, if that's a concern. We don't need any of the binaries, and for now we only use the smacker and smackaud decoders, and smacker demuxer.

I was already stripping the binaries, I didn't know exactly which components where needed, but thanks to your input I've edited the manifest to only build the necessary components.

> It's not clear to me if it's possible but it would be nice to provide wayland support if available. I see the fallback-x11 socket in the documentation, but I can't tell how you would toggle SDL_VIDEODRIVER=wayland based off that.

For now I'd use the X11 backend, as SDL2 windows currently don't have decoration under GNOME/Wayland. [Work is being done upstream to fix that](https://github.com/libsdl-org/SDL/issues/2710#issuecomment-816164530), once it is fixed and available in the runtime I'll enable Wayland by default.

> One other note, since my prior comments on this ticket our appstream metadata id and desktop id was changed to com.corsixth.corsixth, in accordance with the guidelines: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic so the flatpak should have the same application id.

Noted. The change happened after the 0.64 release, so I had to backport some commits. The new manifest is here: https://github.com/rmnvgr/flathub/tree/com.corsixth.corsixth

**Comment by TheCycoONE** [comment]
Looks good to me, I look forward to your PR.

**Comment by rmnvgr** [comment]
The Flatpak has been accepted, it will be published on Flathub tomorrow.

Do you want me to edit the README to advertise it?

**Comment by lewri** [comment]
Technically yes, it should be a separate PR to 1871.
Great work. If you wanted you can also add it to the wiki (in getting started I think)

**Comment by rmnvgr** [comment]
Well it was published sooner than expected: https://flathub.org/apps/details/com.corsixth.corsixth 🎉

**Comment by rmnvgr** [comment]
Yes, I will be maintaining it. I believe you've also been given access to the [repository](https://github.com/flathub/com.corsixth.corsixth).
