### ISSUE TITLE
Program stops working as soon as the title menu appear.

### ISSUE THREAD

**Issue by meshift** [CorsixTH/CorsixTH#1417]
#### Describe the issue
The program stops working as soon as the title menu appears. It works on CorsixTH 0.60, but not 0.61. The pc is using windows 8 and i used the official 0.61 release installer. The original game files are from Origin. I also tested on my windows 7 where the issue doesn't appear. 
#### Steps to Reproduce
1. Install CorsixTH 0.61 with the installer

2. Run the game

3. Program stops working

#### System Information
**CorsixTH Version:*0.61* 

**Operating System:*Windows 8* 

**Theme Hospital Version:*Origin* 

#### Gamelog.txt
No Gamelog.txt output

### Additional Info
![skaermbillede 1](https://user-images.githubusercontent.com/39861940/40879721-697b23ee-66a4-11e8-8ef1-0dfee6f62ce5.png)
![skaermbillede 2](https://user-images.githubusercontent.com/39861940/40879722-6ae9aac0-66a4-11e8-9853-8abf4ea2bb26.png)

**Comment by LeDocteurr** [comment]
It must be something with your installation, if the game would just fail to run it would be obvious to everyone lol.

Try to uninstall the previous version, delete the CorsixTH data folder from the **Documents and Settings/<user name>/AppData/Roaming**, and then reinstall the 0.61 version. Avoid overwriting versions.

You can also try to download the portable version, I am personally running the portable version of CorsixTH in Sandboxie to be sure it's not messing stuff on my computer and I didn't see any problems so far, but I'm using Windows 7, not 8.

If there really is a problem with the Windows 8, then you should be able to run CorsixTH 0.61 in compatibility mode:  http://www.dummies.com/computers/operating-systems/windows-8/how-to-run-older-programs-under-windows-8/

**Comment by lewri** [comment]
No response
