### ISSUE TITLE
Custom Campaign map Hoppalong is corrupt.

### ISSUE THREAD

**Issue by dmoojunk** [CorsixTH/CorsixTH#1423]
#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Open the hospital

3. Run at speed 3 - 5 hangs the game - until....

4. It seems as the first patient is spawned it crashes with the detail window automatically opened on them. The door blocker never goes away despite opening (see pic). If I buy extra areas, these doors are not 'blocked' but same issue.

Not sure if its just this level in general with this build - restarting and immediately opening causes same issue.

#### Save Game
https://drive.google.com/open?id=1581izCdvPBu9vrCoUc5jTR81ITGy-heY

#### System Information
**CorsixTH Version:** 0.62rc1

**Operating System:** Windows 10

**Theme Hospital Version:** GOG.com

#### Gamelog.txt

Created game with savegame version 125.
Savegame version is 125 (v0.62-rc1), originally it was 125 (v0.62-rc1)
Savegame version is 125 (v0.62-rc1), originally it was 125 (v0.62-rc1)
Error in timer handler: 
Lua\humanoid_actions\seek_reception.lua:59: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	Lua\humanoid_actions\seek_reception.lua:59: in field '?'
	Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:623: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>

### Additional Info

![image](https://user-images.githubusercontent.com/2041905/42187384-d83bb1a8-7e47-11e8-8688-14b292aa5b83.png)

I see the same stack here - unsure if dupe - as my entrance is reachable? https://github.com/CorsixTH/CorsixTH/issues/1378

**Comment by TheCycoONE** [comment]
That map looks broken to me. Closing as a duplicate (you should not have a temporary wall in front of your doors, did you make this map?)

**Comment by dmoojunk** [comment]
No I think its level 9 in the campaign. - CorsixTH Map - Hoppalong

**Comment by TheCycoONE** [comment]
Ok, I'll check my own level 9. Maybe the game is not opening the map correctly.

**Comment by TheCycoONE** [comment]
The map itself is broken, tile flags were not set correctly.

This is a low risk fix and should land in 0.62.

**Comment by TheCycoONE** [comment]
Note that you will have to load a save from before that map, e.g. just before victory on the previous level.
