### ISSUE TITLE
Crash due to patient going to treatment being re-routed on error to GP, but going to treatment once it is its turn in GP

### ISSUE THREAD

**Issue by ElvarT** [CorsixTH/CorsixTH#1425]
#### Describe the issue
As soon as a GP's office was built, a baldness patient queued for it. (The bold patient in the middle of the screen).
But when a doctor arrives to the office, the patient instead of entering the GP office goes to the hair restoration, while its status remains "Queueing for GP's office".
As soon as it reaches the hair restoration clinic the crash happens.

#### Steps to Reproduce (A)
1. Load this savegame: https://nofile.io/f/ND0X6zEdKvp/befcrash2.sav.7z

2. Either just wait ~30 seconds for a doctor to arrive, or drop a doctor in the GP's office. See patient go to hair restoration.

3. Wait for him to get there and wait for crash.

#### Another way to reproduce from a few seconds earlier (B):
1. Load this other savegame: https://nofile.io/f/zZ0FuuD0v0s/causing_boldguy_bug.sav.7z

2. If you complete the GP's office build the bold guy will queue for it as described before.

2.b. If you cancel the build, the bold guy will continue in his way to the hair restoration without problems.

#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Ubuntu 18.04

**Theme Hospital Version:** CD

Note: It is the same run as in here: https://github.com/CorsixTH/CorsixTH/issues/1329#issuecomment-406053152, a few minutes after working around the crash described there.

----------------

**Comment by ElvarT** [comment]
If I send that patient to the reception desk (from the GP's office queue) he will go to the reception, then go to the hair restoration directly, and complete treatment without problems.

Note: In this workaround you can see a small issue (maybe worth its own GH issue?). The patient is placed in the reception desk queue as soon as he is routed manually from the UI. This blocks the reception desk until that patient is handled.

**Comment by ElvarT** [comment]
In that same savegame you can observe an unrelated issue (should I create another GH issue for it?)
In the Operating Theater shown in the picture, there is a "confused" surgeon (circled in red), undressed and ready to get out, while at the same time waiting for the next patient (circled in blue). This patient cannot go in as the surgeon is not dressed. At the same time there is another surgeon (blue) waiting to replace the 1st surgeon.
![stucksurgeon_marked](https://user-images.githubusercontent.com/41392927/42930323-f597f552-8b3c-11e8-9bd3-26ec802be071.jpg)
That 1st surgeon will not get out, and the queue will just grow.

There is a simple workaround just picking the 1st surgeon out of the OT.

**Comment by TheCycoONE** [comment]
@ElvarT good work with these bug reports. Are you able to use 0.62-rc2?

**Comment by ElvarT** [comment]
@TheCycoONE : I just fetched master, compiled it and it runs without problems.

**Comment by mugmuggy** [comment]
Surgeon door thing is probably the door reservation bug - CRABWICK in front of drinks machine has it reserved but he isn't on his way to the operating theatre.

That second one is 'same as #372'.

And the original issue - patient navigates a door other than reserved. The door position is on the path to hair restoration, I assume then that the patient navigates the door, no staff, and leaves and reserves the door (reserve_on_resume) as part of the walk action, when it probably should interrupt and recaculate the path before entering or should realise it was the wrong room and recalculate. I was able to replicate on 0.62-rc2.

**Comment by mugmuggy** [comment]
I was taking a look at the navigating door issue:
https://github.com/CorsixTH/CorsixTH/blob/47b9ed6c3402f0bd9d63eb177ae6e7126237b6c1/CorsixTH/Lua/humanoid_actions/walk.lua#L203-L212

Seem to be checking for walls only and then relies on the logic in navigateDoor to correct the situation where it might be more reliable to only continue if there is a door between and the destination room is the same as the room about to be entered.

Quite easy to replicate the issue, put reception at back of hospital, wait for patient to enter, build room on path, walls it will recalculate, doors will knock and queue.

**Comment by mugmuggy** [comment]
Something along the lines of the following works. I rewrote it as my tilde key is broken at the moment so all negation changed but I think it's a little more readable.

The first if statement establishes if there is difference in the rooms -ie at a wall or door - this is unchanged.
flags_there.room will be true if the destination is in a room, false if in the corridor - 
I made the assumption if we are leaving a room, then we are at the door so we won't want to reroute to enter the corridor anyway and therefore set it recalc_route to true if there is a room on our path.

Then the later predicate becomes:
if about to enter room, and we are at a door and it so happens that the roomId is the same then cancel the reroute so human will enter the room.

```lua
  if not recalc_route and flags_here.roomId ~= flags_there.roomId then
    -- if going to the corridor we don't care as we are at the door
    -- as this will be false we won't bother checking for rerouting
    recalc_route = flags_there.room
    local door = TheApp.objects.door.thob
    local door2 = TheApp.objects.swing_door_right.thob
    -- but we should see if this is the same room id we might want to go to and cancel the reroute
    if recalc_route and (flags_here.thob == door or flags_here.thob == door2 or --is there any door
        flags_there.thob == door or flags_there.thob == door2) and -- is there any door
        map:getCellFlags(path_x[#path_x], path_y[#path_y]).roomId == flags_there.roomId then -- is it still same room id humanoid is going to
      recalc_route = false
    end
  end
`

**Comment by mugmuggy** [comment]
I found an issue with my fix on this one, working on another fix.

**Comment by mugmuggy** [comment]
Resolved
