### ISSUE TITLE
Mouse or keyboard hung on year end

### ISSUE THREAD

**Issue by ElvarT** [CorsixTH/CorsixTH#1428]
#### Describe the issue
For some reason, on this savedgame (on year end):
1. if you dismiss the awards window by clicking on the blueish-greenish close window button. And then click with the middle mouse button to pan, it won't stop panning and will produce this error:
```
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
CorsixTH/Lua/world.lua:1405: attempt to index a nil value (local 'level_info')
stack traceback:
	CorsixTH/Lua/world.lua:1405: in method 'winGame'
	CorsixTH/Lua/world.lua:1157: in method 'checkIfGameWon'
	CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:472: in local 'callback'
	CorsixTH/Lua/window.lua:682: in method 'handleClick'
	CorsixTH/Lua/window.lua:1478: in method 'onMouseUp'
	CorsixTH/Lua/window.lua:1462: in field 'onMouseUp'
	CorsixTH/Lua/ui.lua:654: in function <CorsixTH/Lua/ui.lua:641>
	(...tail calls...)
	CorsixTH/Lua/app.lua:915: in function <CorsixTH/Lua/app.lua:910>

Warning: No event handler for buttonup
```

2. If instead you dismiss that awards window pressing the Esc key, the keyboard won't be usable anymore ingame and the error will be the one below:
```
Running: The keydown handler.
A stack trace is included below, and the handler has been disconnected.
CorsixTH/Lua/world.lua:1405: attempt to index a nil value (local 'level_info')
stack traceback:
	CorsixTH/Lua/world.lua:1405: in method 'winGame'
	CorsixTH/Lua/world.lua:1157: in method 'checkIfGameWon'
	CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:472: in method 'close'
	CorsixTH/Lua/ui.lua:898: in field 'callback'
	CorsixTH/Lua/ui.lua:556: in field 'onKeyDown'
	CorsixTH/Lua/game_ui.lua:289: in function <CorsixTH/Lua/game_ui.lua:288>
	(...tail calls...)
	CorsixTH/Lua/app.lua:915: in function <CorsixTH/Lua/app.lua:910>

Warning: No event handler for keydown
```

#### Steps to Reproduce
1. Load save game attached 
2. Either close the awards window with a. the mouse, or b. the keyboard
3. Loose use of either a. mouse or b. keyboard ingame afterwards.

#### Save Game
https://nofile.io/f/T2ptNngxjRs/middle_button_issue.sav.7z

#### System Information
**CorsixTH Version:** 25b4424
**Operating System:** Xubuntu 18.04
**Theme Hospital Version:** CD

**Comment by ElvarT** [comment]
Note also that in the year end window the "Richest" amounts are displayed with 1 decimal.

**Comment by mugmuggy** [comment]
Custome level file that you had on 0.61 not installed with this build?

**Comment by ElvarT** [comment]
> Custome level file that you had on 0.61 not installed with this build?

Indeed that was the problem. I had assumed the level was kept in the savegame (like the map?), and did not bother moving it to the new build. Thanks :)

**Comment by TheCycoONE** [comment]
Normally you would keep your custom levels in the `~/.config/CorsixTH/levels` directory so they would carry over.
