### ISSUE TITLE
Compile errors on Ubuntu 16.04.x (v0.6.2)

### ISSUE THREAD

**Issue by ultraviolet-1986** [CorsixTH/CorsixTH#1433]
The tarball for v0.6.2 can be compiled using the steps outlined on the 'How to Compile' page, however, once this has been built and the executable has also been built, launching it shows this error:

![corsixth_build](https://user-images.githubusercontent.com/13064323/43369537-2c0c0014-9368-11e8-8c88-8aa1a7e9f2a8.png)

Attempting to build using the alternate instructions: `cmake -DUSE_SOURCE_DATADIRS=ON -DLUA_INCLUDE_DIR=/usr/include/lua5.3 -DLUA_LIBRARY=/usr/lib/i386-linux-gnu/liblua5.3.so ..` will simply cause the build process to crash. The error references Lua 5.3 (i386) and not much else makes sense to me.

I am on Fedora 28, but can test Ubuntu 16.04 again if it would help. Thank you very much for your time.

**Comment by TheCycoONE** [comment]
Alright... the issue with your build in the screenshot is that it expects to be installed (sudo make install). If you want to use the data files directly from a git checkout then add -DUSE_SOURCE_DATADIRS=ON but leave everything else the same.

**Comment by ultraviolet-1986** [comment]
Hi, apologies for the confusion - the 'How to Compile' page didn't mention `sudo make install` (in fact, I've never done that) - but building, running `make` and then `sudo make install` starts CorsixTH flawlessly on Ubuntu 16.04/18.04. Apologies again, looks like a non-issue ^_^b

I'll mark this as closed.

**Comment by wolfy1339** [comment]
I think this could be left open, as a tracker for updating the wiki pages with new build information from 0.62
