### ISSUE TITLE
Epidemic evacuation can lead to invalid action states

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1436]
#### Describe the issue
Patients vomiting outside the hospital.

A patient whilst leaving the hospital as part of an epidemic evacation, receives a VomitAction as part of Patient:tickDay.

This inserts itself as 2nd in action queue:
```lua
    self:queueAction(VomitAction(), 1)
```
Patient proceeds to spawn point (initial walk is not interrupted), then vomit action is started whilst outside the hospital and litter outside the hospital should not be possible.

#### Steps to Reproduce
1. Used save attached to 1394, this has an evacuation in progress.

#### Save Game
[Save from 1394](https://github.com/CorsixTH/CorsixTH/files/2034833/Ulti.XT.zip)

#### Expected Behavior
No vomiting outside hospital.
Epidemic:evacuate should probably just do a Patient:goHome("kicked") type call, but then all patients will affect statistics which I can't recall the original behaviour.  This should prevent the vomit action being added after being kicked.

#### System Information
**CorsixTH Version:** 0.62

#### Gamelog.txt
```
Savegame version changed from 122 (v0.61) to 127 (v0.62). The save was created using 122 (v0.61)
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
```

**Comment by mugmuggy** [comment]
Found another case where a patient has died, fallen, lava hole and grim reaper has spawned, grim has walked to lava and patient has stood up but then evacuate hospital has been called and patient proceeds to walk out of the hospital. This leaves the grim reaper stuck in hospital.

**Comment by TheCycoONE** [comment]
Was the vomit outside the hospital caused by invalid map flags? This ticket reads like that one

**Comment by mugmuggy** [comment]
The decision to vomit appears to be when within the hospital itself, and the action is queued. However i don't think a leaving patient was supposed to vomit even within the hospital. Patient:canPeeOrPuke guards the vomit call.

This guards it:

```lua
function Patient:canPeeOrPuke(current)
  return ((current.name == "walk" or current.name == "idle" or
           current.name == "seek_room" or current.name == "queue") and
      not self.going_home and self.world.map.th:getCellFlags(self.tile_x, self.tile_y).buildable)
end
```

For example: Patient at (65,64) in hospital has action queue [walk (128,64) must_happen, vomit, walk (128,64) must_happen, spawn]

Patients previous action was use_object. So here it appears that the patients initial 'despawn' ran, it queued the walk action then tickDay with vomit appears to have 'interrupted' it without truncating the path.

Just setting going_home in epidemic evacuation and then also only evacuating those that are not already going_home avoids this issue. You still get some 'goHome when patient already going home' as, I guess, 'Stripped' patients have the walk/use_screen actions 'disableTruncated'/must_happen and therefore the callbacks complete for 'dealtWithPatient'. However tickDay won't complete and initiate the vomit call anyway, as the patient will already be going_home (guarded by Humanoid.tickDay())

**Comment by mugmuggy** [comment]
Has been merged
