### ISSUE TITLE
LUA error (patients crashed/frozen outside on pile of vomit)

### ISSUE THREAD

**Issue by tfrengler** [CorsixTH/CorsixTH#1440]
#### Describe the issue

The game gives reports about errors happening after which a patient is crashed on an outside tile. You can still click on them to bring up their chart but they cannot be interacted with. Sending them home does nothing (except for showing the Exit-sign above their heads). See Additional Info for more detailed report.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. *Wait for a patient to crash the game. Note that in this save there is already a handful of patients who have crashed and more are bound to crash after a while.*

3. *Profit?*

#### Save Game
*https://drive.google.com/open?id=1QovFfSIQktnjsUEEPG9Jep_WnEN-V99T*

#### Expected Behavior
*N/A ( game shouldn't crash obviously :) )*

#### System Information
**CorsixTH Version:** *0.62*

**Operating System:** *Windows 10 (1803), Intel HD Graphics 520*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt
```
Created game with savegame version 127.
Warning: Trying to remove nonexistant room build callback (function: 152DBAF0) from humanoid (table: 16E9FDB8).
Warning: Trying to remove nonexistant room remove callback (function: 1292F0B0) from humanoid (table: 16E9FDB8).
Warning: Trying to remove nonexistant room build callback (function: 157904C8) from humanoid (table: 119A0870).
Warning: Trying to remove nonexistant room remove callback (function: 0CAF1E70) from humanoid (table: 119A0870).
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Savegame version is 127 (v0.62), originally it was 127 (v0.62)
Savegame version is 127 (v0.62), originally it was 127 (v0.62)
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1036: in method 'onTick'
	Lua\app.lua:1014: in function <Lua\app.lua:1011>
	(...tail calls...)
	Lua\app.lua:915: in function <Lua\app.lua:910>
```

### Additional Info

![bug01](https://user-images.githubusercontent.com/22467830/44085335-79e4e3e8-9fb9-11e8-83f0-eda70743c18d.png)

This issue is tricky to get a handle on. I reloaded the save game multiple times (before the crashes started happening) to see if it was random and kept playing for a few hours to try and spot a pattern. Unfortunately I don't have a save from before the initial error happened. This is what I found out:

1: It's was guaranteed to happen sooner or later from my clean save, but not always in the same spots, and not at the same time.
2: It always happens outside the hospital interior.
3: It's always new patients on their way to the reception desk
4: They are always standing on a pile of vomit.

I was never able to tell if it happened initially because a patient vomited outside on the way to the reception or something else.
What I do know with reasonable certainty is that patients who pass over the initial trouble spots (crashed patient) tend to crash as well. In the save there are 3 spots with 2 or more crashed patients.
However not everyone who passes over a tile with one or more crashed patients are guaranteed to crash. Again I am not certain if it happens if they vomit on a tile with an already crashed patient or if some other logic ticks right when they are on the problem tile. The fact that it happens with random frequency makes it tricky to observe and nail down exactly.

Keep in mind that this is a late stage save game, way past the requirements for winning the level, where everything is pushed to the max. There's 10-12 GP's, a 9 bed ward, 5 pharmacies and 3 reception desk at work while tonnes of patients pouring in. I never had it happen in the initial stages of the game where things were reasonably quiet so perhaps the sheer amount of patients has something to do with it.

Not sure if relevant but I also noticed that the crashed patients were still queued for the reception desks, and never getting processed. I had to remove the reception desk and put down a new one to get rid of them.

I hope these observations are helpful (this is my first bug report). Let me know if you need anything else.

**Comment by TheCycoONE** [comment]
Excellent report. vomit.lua needs a check that humanoid.tile_* are inside the hospital in action_vomit_end. An assert could be added to newObject as well.

**Comment by mugmuggy** [comment]
Similar to 1436 but different enough. Patient:canPeeOrPuke and Patient:setTile are checking buildable flags already to determine if in the hospital - except the external tiles against the wall of the hospital are buildable. Nearly every other map I've found includes a section of non-walkable tiles around the perimeter of the external walls which avoids this issue.

So this might be more of a map issue. The hospital/buildable/owner/parcelId flags are all set as if they were inside the hospital as the tile is part of constructing that wall.

**Comment by TheCycoONE** [comment]
Thank you mugmuggy. There was another map we shipped like that which I corrected for 0.62. I haven't looked at this save yet. Is it another one of ours?

**Comment by mugmuggy** [comment]
Holby in this case which we are shipping in the custom campaigns. I haven't checked if there are any others with the same sort of issue.

**Comment by tfrengler** [comment]
Ah yes, I had made a note of the map (second of the custom campaign that ships with CorsixTH) but forgot to include it. My mistake.
