### ISSUE TITLE
no emergencies in chrizmantv campaign

### ISSUE THREAD

**Issue by Tigertye** [CorsixTH/CorsixTH#1445]
#### Describe the issue

Though I have been playing v .60 since it came out, this is the first time I have loaded up the chrizmantv custom campaign. It works fine or it did. With the Snuffit level I lost the ability to have emergencies, even if I attempted to cheat them. I get that lil popup that says I either have no helipad or have discovered no new conditions. I get the same issue with every level since then. I am now up to level 9, Hoppalong maybe? and still no emergencies. No matter how many times I reboot <win 7 with an original game disc> or restart the level, still I have no emergencies. This only happens in this campaign. Is there a problem with this campaign or have I borked my install?

Thanks,
Tigertye

**Comment by TheCycoONE** [comment]
It is likely an issue with the campaign. The maps are due for a careful review.

**Comment by Tigertye** [comment]
Thank you for your response. Glad it's not my install. I miss the emergencies but I'm really enjoying playing the maps. Kind of surprised this issue wasn't caught already.

Have a happy!
Tigertye

**Comment by MarkL1961** [comment]
I have loaded snuffit sands as a single map and could get emergencies.  Do I have the correct map? Could it be that the map is different in the campaign?

**Comment by Tigertye** [comment]
Awesome thanks. Hmm, yes the Snuffit map has emergencies as a single game for me also. The Wishinwell map however still doesn't do emergencies as a single game. I'm thinking that maybe it's only specific maps in that campaign that have this issue. I agree with CycoOne that these maps need a careful review. Still shocked that no one noticed this earlier.

**Comment by lewri** [comment]
May be resolved by PR #1532
