### ISSUE TITLE
Error when compiling in Linux: SDL library not found

### ISSUE THREAD

**Issue by Zababon** [CorsixTH/CorsixTH#1447]
#### Describe the issue
I tried to compile the game but got the following exception
```
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
Note: SDL audio is enabled (default)
Note: FFMPEG video is enabled (default)
Note: FreeType2 is enabled (default)

Building CorsixTH
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
CMake Error at CorsixTH/CMakeLists.txt:105 (message):
  Error: SDL library not found, it is required to build.  Make sure the path
  is correctly defined or set the environment variable SDLDIR to the correct
  location

-- Configuring incomplete, errors occurred!
```
Before that, I installed all the dependencies as specified in the instruction. Also, I attempted to set the environment variables `SDL_LIBRARY`,  `SDL_INCLUDE_DIR` and `SDLDIR` by writing them to the .bashr by specifying the path `/usr/lib/x86_64-linux-gnu`. But it did not help.

#### System Information
**CorsixTH Version:** *CorsixTH-0.62*

**Operating System:** *Linux Mint 19*

**Comment by colinjmatt** [comment]
How did you install SDL2 and SDL2_mixer? Did you specify `libsdl2-dev` and `libsdl2-mixer-dev`?

What happens if you try to install `libsdl-dev` and then compile?

**Comment by Zababon** [comment]
@colinjmatt Thank you, the problem really is this. I apologize for the trouble, I found a mistake and she's stupid enough. It seemed to me that in the chapter "Compiling on Linux" you must choose one of the proposed commands and I chose the second one. But now I added the first command and the compilation was successful.

**Comment by Alberth289346** [comment]
I tried to fix this problem, would this be better?

https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile/_compare/feafcb3fe5650cb693ef036dd4d07818f6d8e5cf...4b68c60d5be89b9a94ec13a68f18494f8a14c0de

**Comment by Zababon** [comment]
@Alberth289346 Most likely it's better. But it was only my personal reaction backed up by a not very good knowledge of English.
