### ISSUE TITLE
Simplified Chinese hangs the game

### ISSUE THREAD

**Issue by Icenowy** [CorsixTH/CorsixTH#1449]
#### Describe the issue

I set the game to use Simplified Chinese langauge to play (with either original game downloaded from GOG or the game with Chinese patch applied (which is said to be extracted from an official Simplfied Chinese version) ).

When I start game with default options (First game off and difficulty as "Doctor"), the game hangs after the Ludo-like screen, and doesn't enter the main game screen. (The BGM is changed however.)

Sometimes the screen is changed, but the mouse cursor cannot move, and thus cannot play.

Enable first game seems to be able to workaround this, but I didn't try whether it will hang after.

Traditional Chinese is okay.

#### Steps to Reproduce
1. Set a TTF font

2. Change language to Simplified Chinese ("简体中文")

3. Start game with default options.

#### System Information
**CorsixTH Version:** 0.62

**Operating System:** Linux (AOSC OS)

**Theme Hospital Version:** GOG

#### Gamelog.txt
Nothing is in it.

**Comment by MarkL1961** [comment]
try and disable the game movies, you can do this in config.txt found in AppData\Roaming\CorsixTH.

 you might be missing these files and this is why it hangs

**Comment by Icenowy** [comment]
@MarkL1961 The movie file is okay, and when I report the issue, the movie successfully plays. And this doesn't explain why Traditional Chinese and English work.

BTW still tried your suggestion, fixed nothing, will hang just after "开始"(Start) is clicked.

**Comment by tobylane** [comment]
Can you try some older releases? Are there any relevant messages in the event viewer?

**Comment by mugmuggy** [comment]
Same as #1240.

**Comment by maye9999** [comment]
Same issue here. I've checked the #1240. It hangs exactly when showing the introduction_texts.  And adding whitespaces to end of lines solves it. However, whitespaces are already added to the demo level, but it still hangs when playing demo. I don't know why. But if I just play level 1, it fixes if I add whitespaces to end of lines.

**Comment by TheCycoONE** [comment]
Fixed by #1478
