### ISSUE TITLE
error msg that i don't understand

### ISSUE THREAD

**Issue by Tigertye** [CorsixTH/CorsixTH#1450]
#### Describe the issue
deprecated variable definition in the level file.'%LevelFile' has been renamed to '%MapFile

what does this mean and why do so many maps in the map pack have this msg? I've only played one of them so far and all was going just fine until the end of the year when it suddenly claimed i lost due to a drop below 200 in rep. my rep at the time was 568. it's the only error msg i have gotten yet.

thanks,
Tigertye

**Comment by TheCycoONE** [comment]
The warning doesn't relate to you losing. It means that the levels were never updated to our new format from several versions ago. It is harmless.

**Comment by Tigertye** [comment]
interesting. So it should play properly then? hmmm Now I just have to figure out why the sudden and unexplained drop in rep. Thanks :)

**Comment by MarkL1961** [comment]
Where elements of a map file are missing the defaults take over so look in base_config.lua to see what the default is.

**Comment by Tigertye** [comment]
it happens on several maps when i go to select one from the main menu. could this have anything to do with the fact that I am still playing v .60?

**Comment by Tigertye** [comment]
As for what you suggested MarkL, I have never looked at any of the files so I have no idea what the default is. Will it be easy to find in there?

**Comment by Tigertye** [comment]
TheCycoOne, I probably can I will see which file it is that does this. How do I get the save file to you? can I attch it here or do I need to upload it somewhere then provide the link?

**Comment by TheCycoONE** [comment]
@Tigertye you will need to upload it somewhere. Dropbox or similar.

**Comment by Tigertye** [comment]
@TheCycoONE dropbox. ok this is confusing. not a fan of this site. I have no desire to install their software on my puter. the file is only 530k. can I email it to you instead?

**Comment by wolfy1339** [comment]
You don't have to install their software.
In fact, if you create a zip file with the requested file inside, you can upload it directly to GitHub.
https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

**Comment by Tigertye** [comment]
[1A Abscence Central.sav.zip](https://github.com/CorsixTH/CorsixTH/files/2371141/1A.Abscence.Central.sav.zip)
well that sounds easy enough. let's see if I did that right. It's my first time zipping a file in linux.

**Comment by Tigertye** [comment]
@TheCycoONE is that not the file you wanted?

**Comment by TheCycoONE** [comment]
I haven't checked yet. I or another developer will update the ticket either way when we do.

**Comment by Tigertye** [comment]
cool. thanks

**Comment by mugmuggy** [comment]
Appears the level file is incorrect, it is configured to lose if reputation is above 200.
goal.max_min_lose == 1, therefore 569 - 200 * 1 > 0, needs to be set to 0 to lose when rep falls below 200.

https://github.com/CorsixTH/CorsixTH/blob/553adf362dc8c1cf5e21fc386b961f49852095eb/CorsixTH/Lua/world.lua#L1360-L1375

**Comment by TheCycoONE** [comment]
Thanks @mugmuggy 

Was it one of our maps, or one from the internet?

**Comment by mugmuggy** [comment]
interwebs

**Comment by TheCycoONE** [comment]
Thank mugmuggy. Closing as this is a 3rd party map issue
