### ISSUE TITLE
Intermittently unable to successfully use the picker to set Theme Hospital game data files on MacOS

### ISSUE THREAD

**Issue by colinjmatt** [CorsixTH/CorsixTH#1460]
#### Describe the issue
When running CorsixTH for the first time, or when the game data directory has moved or been renamed, the directory picker that appears does not allow you to successfully select the correct directory. This also occurs when changing the game data folder from within the settings menu also.

Sometimes the picker freezes entirely, sometimes it allows you to navigate to the correct folder, and sometimes, the + symbol next to certain folders will disappear so that you cannot expand the folder to select one within it. Sometimes, even when selecting the correct folder successfully, CorsixTH does not register that folder as the one that contains the game files.

This behaviour is intermittent and it appears you can work around the issue by quitting the game using Cmd + Q and retrying until it allows you to select the folder.

#### Steps to Reproduce
1. Open CorsixTH.app for the first time, or move/rename the game data folder

2. Attempt to locate the game data

3. The picker may freeze, or may not correctly detect the game data directory

#### Save Game
This occurs before loading any level/campaign/savegame.

#### Expected Behavior
The picker allows you to select the correct folder and then press OK to proceed to the main menu.

#### System Information
**CorsixTH Version:** *0.62*

**Operating System:** *MacOS 10.13.6*

**Theme Hospital Version:** *CD & GOG version*

#### Gamelog.txt
No gamelog.txt appears to be generated

**Comment by colinjmatt** [comment]
I've used the version built for 10.10 and 10.13.6 and they both exhibit the same behaviour.

**Comment by colinjmatt** [comment]
This may be the issue:

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The multigesture handler.
A stack trace is included below, and the handler has been disconnected.
/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: attempt to call a nil value (method 'onMultiGesture')
stack traceback:
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1105>
	(...tail calls...)
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:910>

Warning: No event handler for multigesture

**Comment by colinjmatt** [comment]
A further stack trace occurs for when it freezes:

Error while fetching children for /Applications/Calendar.app: cannot open /Applications/Calendar.app: Too many open files
Error while fetching children for /Applications/Chess.app: cannot open /Applications/Chess.app: Too many open files
Error while fetching children for /Applications/Contacts.app: cannot open /Applications/Contacts.app: Too many open files
Error while fetching children for /Applications/CorsixTH.app: cannot open /Applications/CorsixTH.app: Too many open files
Error while fetching children for /Applications/Dashboard.app: cannot open /Applications/Dashboard.app: Too many open files
Error while fetching children for /Applications/Datakam Player.app: cannot open /Applications/Datakam Player.app: Too many open files
Error while fetching children for /Applications/Diablo II: cannot open /Applications/Diablo II: Too many open files
Error while fetching children for /Applications/Dictionary.app: cannot open /Applications/Dictionary.app: Too many open files
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
...rsixTH.app/Contents/Resources//Lua/dialogs/tree_ctrl.lua:369: cannot open /Applications/Authy Desktop.app: Too many open files
stack traceback:
	[C]: in function 'lfs.dir'
	...rsixTH.app/Contents/Resources//Lua/dialogs/tree_ctrl.lua:369: in method 'checkForChildren'
	...rsixTH.app/Contents/Resources//Lua/dialogs/tree_ctrl.lua:407: in method 'getChildCount'
	.../Resources//Lua/dialogs/resizables/directory_browser.lua:83: in method 'getHighlightColour'
	...rsixTH.app/Contents/Resources//Lua/dialogs/tree_ctrl.lua:673: in method 'draw'
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1310: in field 'draw'
	...rsixTH.app/Contents/Resources//Lua/dialogs/resizable.lua:111: in field 'draw'
	.../Resources//Lua/dialogs/resizables/directory_browser.lua:199: in method 'draw'
	...ications/CorsixTH.app/Contents/Resources//Lua/window.lua:1310: in field 'draw'
	/Applications/CorsixTH.app/Contents/Resources//Lua/ui.lua:342: in method 'draw'
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1033: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1026>
	(...tail calls...)
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:910>

Warning: No event handler for frame
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The multigesture handler.
A stack trace is included below, and the handler has been disconnected.
/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: attempt to call a nil value (method 'onMultiGesture')
stack traceback:
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:1105>
	(...tail calls...)
	/Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function </Applications/CorsixTH.app/Contents/Resources//Lua/app.lua:910>

Warning: No event handler for multigesture

**Comment by TheCycoONE** [comment]
The second error is not lua, it's macos open file limits. I have seen the same error in mysql and elsewhere. I don't think we should be holding lots of open file handles so I will look into that.

**Comment by TheCycoONE** [comment]
For open file descriptors I see that one is being open for every file in the directories that are opened. They seem to get garbage collected over time. Just leaving the file picker in one spot for awhile they go away.

**Comment by colinjmatt** [comment]
Will that be the source of the lock up if you expand /Applications since every .app is basically a directory with many sub directories/files within?

I can try file picking from /Users to see if the same issue is experienced.

**Comment by colinjmatt** [comment]
Bumped the file limit which seemed to help. However, the game still sometimes does not detect the game data folder correctly. I think this is due to the open file limit, rather than multi gesture though.

Opening the game and using the picker 20 times - 10 times scrolling using the in game bar and 10 using a multi touch gesture to scroll - resulted in roughly the same frequency of the game data folder not being correctly detected when hovering over it.

This behaviour occurrs even without the file limit error generating, but directories also could not be expanded correctly which makes me believe this issue is related.
