### ISSUE TITLE
HD camera makes hospital edges hard to see

### ISSUE THREAD

**Issue by bobucles** [CorsixTH/CorsixTH#1461]
#### Describe the issue
When the camera is zoomed out, map edges may be hidden and inaccessible

#### Steps to Reproduce
1. Play on a sufficiently high resolution
2. Zoom out
3. Try scrolling the screen
4. Very noticeable on level 8!

#### Expected Behavior
Didn't matter in vanilla because the low resolution and lack of zoom meant it was never a problem. Corsix may have to allow more flexible camera panning so that parts of the map don't get pushed out of view.

### Additional Info
Here's an extreme example of level 8. The screen is zoomed out and entire rooms can not be seen due to the camera boundary.
![can t see top](https://user-images.githubusercontent.com/42895075/45269007-240ec380-b454-11e8-8a42-f9bcc16113c3.jpg)

**Comment by TheCycoONE** [comment]
If you enable debug mode (through the config file), you can disable the camera locking. The original game wasn't meant for such things so they have some glitchy areas outside the normally visible bounds of the map. There is really no good solution.
