### ISSUE TITLE
LocalisedString Cycle while depersisting permanent object key or userdata metatable after 1 objects (1 bytes)

### ISSUE THREAD

**Issue by BaNru** [CorsixTH/CorsixTH#1463]
#### Describe the issue
After testing for the report #1462, after the next launch of the game and attempting to launch the "continue the game" - an error appeared.

```
<LocalisedString> Current value:Ошибка загрузки игры: /usr/share/games/corsix-th/Lua/persistance.lua:266: Cycle while depersisting permanent object key or userdata metatable after 1 objects (1 bytes)
```

#### Steps to Reproduce
1. Run game
2. Click on "continue the game"

#### System Information
* CorsixTH Version: 0.62 from https://launchpad.net/ubuntu/+source/corsix-th/0.62-1/+build/15258578
* Operating System: kUbuntu
* Theme Hospital Version: different sets

#### Gamelog.txt
```
<LocalisedString> Current value:Ошибка загрузки игры: /usr/share/games/corsix-th/Lua/persistance.lua:266: Cycle while depersisting permanent object key or userdata metatable after 1 objects (1 bytes)
```

### Additional Info
![Gamelog](http://dl4.joxi.net/drive/2018/09/10/0004/2123/305227/27/c2435a676e.png)
![Screen](http://dl4.joxi.net/drive/2018/09/10/0004/2123/305227/27/ad51df305b.png)

**Comment by lewri** [comment]
I took a few runs through this on 0.64 with the save in #1462 is no longer doing this. Will close for now unless it can be reproduced.
