### ISSUE TITLE
Port of CorsixTH-0.62 to LJS

### ISSUE THREAD

**Issue by mingodad** [CorsixTH/CorsixTH#1493]
Sorry it's not an issue really !
I just did a port of CorsixTH-0.62 to LJS https://github.com/mingodad/CorsixTH-ljs and I'm anouncing it here just in case someone want to see how it look with another syntax.
My main purpose with this port was to test LJS https://github.com/mingodad/ljs and I went till I could build it on linux64 and execute it but I didn't played with it.

I went to the forum but another login and all that so again sorry for posting it here.
Cheers !

**Comment by TheCycoONE** [comment]
Fun, thanks for sharing. I gather from a brief look around that it was an automatic transformation using a tool you wrote for your own lua derivative?

**Comment by mingodad** [comment]
Yes the tool lua2ljs does the convertion on almost all Lua code, except dynamic Lua code inside strings, C/C++ code, auxiliar scripts and makefiles, LJS also flag as warning/error duplicate variable declarations and a revision is needed mainly using "ljsc -p -l ljsSource.ljs > /dev/null" to only compile and emit the warnings/error to stderr, then several text scans to search and replace "nil", ".lua" inside strings, ...
Then run the tests if available to check that it's working properly (at least with the tests).
