### ISSUE TITLE
Game speed varies from TH

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1494]
#### Describe the issue

Current timer ticks are at 30ms intervals.

The original would most likely be using 18.2ms interrupts.

Running dosbox side by side and starting both the first level and actually not doing anything.

Dosbox gets to Oct whilst Corsix is around finishing June at normal speed.

Changing the SDL timer ticks to 18ms gets a pretty consistent value.

Likewise the higher speed (And then some more) Corsix gets to end of year when TH in dosbox gets to around end of July. (hours_per_tick at 3, means 3 ticks every 30ms with the current timer which is 2 days per second and the original looks to be 18.2 * 50 or just under a second per day.

At the slowest speed, Corsix is much faster than TH also around 13.5 sec rather than around 50-52 secs.

Changing the timer to 36ms we can approximate fairly well the 18.2 ms timer base.

```lua
local tick_rates = {
  ["Pause"]              = {0, 1},
  ["Slowest"]            = {1, 28}, -- 1 tick per s
  ["Slower"]             = {1, 6}, -- 1 tick per 216ms
  ["Normal"]             = {2, 3}, -- 2 ticks per 108ms = 1 tick per 54 ms
  ["Max speed"]          = {1, 1}, -- 1 tick per 36 ms
  ["And then some more"] = {2, 1}, -- 2 ticks per 36 ms = 1 tick 18ms
  ["Speed Up"]           = {4, 1},
}
```
The 'Speed up' would be nearly equivalent of the old And then some more, at a tick per 9ms instead of 10 and a bit slower than the 7.5ms it would currently result in.

The above values, result in approx seconds per game day of 
Slowest - 50
Slower - 10.8
Normal - 2.7
Max - 2
And then some more - 1
Speed up - 0.5

The current rate on slowest speed, without using 'build when paused' is a worse experience than the original when you use it to build something that is missing and need to do it quickly, and at 'And then some more' you have more time to respond to say a message.

**Comment by lewri** [comment]
The "slowest" speed in the original always felt painfully slow to me beyond the point of it really having a purpose (except to cheat the timers I guess like you said).

I'm interested that the 'and then some more' is faster in ours than original though.

**Comment by tobylane** [comment]
[This is a Windows build](https://github.com/tobylane/CorsixTH/suites/18106203745/artifacts/1043709072) of the changes for comparisons with TH97, from [Github Actions](https://github.com/tobylane/CorsixTH/actions/runs/6834436806/job/18587193207).
