### ISSUE TITLE
No staff available to hire

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#1510]
#### Describe the issue
I loaded a save that I had kept from my previous installation of Windows, and everything went according to plan except when trying to hire staff. There were none available to hire.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Try to hire staff

3. Observe how no staff are available at all

#### Save Game
https://drive.google.com/open?id=1xkS5hgsNoWCPrFXiziGgTmqBos90NmqW

#### Expected Behavior
Some staff be available for hire
#### System Information
**CorsixTH Version:** 0.61

**Operating System:** Windows 10 1809

**Theme Hospital Version:** Origin

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
No output, file non-existant
```

### Additional Info
Standard campaign level included with the game. Not edited

**Comment by mugmuggy** [comment]
Can't replicate, are you sure you are going to the hire dialog rather than the staff list?

**Comment by MarkL1961** [comment]
![hire Staff](https://user-images.githubusercontent.com/4965487/55613363-70b84400-5782-11e9-9725-c42c5d6c5669.jpg)

**Comment by TheCycoONE** [comment]
I also cannot reproduce. Tested both with 0.61 and latest master.

**Comment by wolfy1339** [comment]
I really do not know how I missed that. It's been a while since I've played the game.
