### ISSUE TITLE
Assert in call dispatcher executeCall

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1512]
#### Describe the issue

Appears to have been introduced as part of the staff classes. Handyman becomes stuck. Reproduce on new game and old saves.

#### Steps to Reproduce
1. Start any hospital, place bunch of plants so they will require watering around the same time.

2. Hire 2 handymen, prepare to hire a 3rd, but don't place him

3. Wait for the 2 handymen to start actioning the tasks, place 3rd handyman.

#### Save Game
N/A
#### System Information
**CorsixTH Version:** https://github.com/CorsixTH/CorsixTH/commit/f3d204e4deb5e52ce9d57ca6297c0cd008025231
**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt
```
Lua\calls_dispatcher.lua:448: call to be executed is still assigned
stack traceback:
	[C]: in function 'assert'
	Lua\calls_dispatcher.lua:448: in method 'executeCall'
	Lua\entities\humanoids\staff\handyman.lua:177: in method 'assignHandymanTask'
	Lua\entities\humanoids\staff\handyman.lua:124: in method 'searchForHandymanTask'
	Lua\calls_dispatcher.lua:346: in method 'answerCall'
	Lua\humanoid_actions\answer_call.lua:33: in field '?'
	Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:623: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:193: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:105: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by mugmuggy** [comment]
Looks like Handyman:onPlaceInCorridor, calling the meander in Staff:onPlaceInCorridor and allocating the task and answers a call, then its unassigned again immediately after but not dropping the call. Probably get away with unassigning the task before call Staff.onPlaceInCorridor from a quick test

**Comment by TheCycoONE** [comment]
You were quicker than me. I was still focusing on interruptHandyman :smile:

**Comment by TheCycoONE** [comment]
If you make the change, I think the same thing should be done for gotoStaffRoom?

**Comment by mugmuggy** [comment]
Only meander actions and calls dispatcher itself (in answercall) I think call back into the searchForHandymanTask. I built a staff room also after testing only the onPlaceInCorridor and no issues encountered so far.

**Comment by mugmuggy** [comment]
Got more of similar issue from another hospital, with meander and interrupt handyman. This time when one trigger and recovery was attempted many more then failed one after the other.
```
Lua\calls_dispatcher.lua:448: call to be executed is still assigned
stack traceback:
	[C]: in function 'assert'
	Lua\calls_dispatcher.lua:448: in method 'executeCall'
	Lua\entities\humanoids\staff\handyman.lua:183: in method 'assignHandymanTask'
	Lua\entities\humanoids\staff\handyman.lua:145: in method 'searchForHandymanTask'
	Lua\humanoid_actions\meander.lua:35: in field '?'
	Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:623: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:193: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:105: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
Recovering from error in timer handler...
Error in timer handler: 
Lua\calls_dispatcher.lua:448: call to be executed is still assigned
stack traceback:
	[C]: in function 'assert'
	Lua\calls_dispatcher.lua:448: in method 'executeCall'
	Lua\entities\humanoids\staff\handyman.lua:183: in method 'assignHandymanTask'
	Lua\entities\humanoids\staff\handyman.lua:130: in method 'searchForHandymanTask'
	Lua\calls_dispatcher.lua:346: in method 'answerCall'
	Lua\humanoid_actions\answer_call.lua:33: in field '?'
	Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:598: in method 'setNextAction'
	Lua\entities\humanoids\staff\handyman.lua:113: in method 'interruptHandymanTask'
	Lua\hospital.lua:2180: in method 'assignHandymanToTask'
	Lua\entities\humanoids\staff\handyman.lua:167: in method 'assignHandymanTask'
	Lua\entities\humanoids\staff\handyman.lua:140: in method 'searchForHandymanTask'
	Lua\humanoid_actions\meander.lua:35: in field '?'
	Lua\entities\humanoid.lua:531: in upvalue 'Humanoid_startAction'
	Lua\entities\humanoid.lua:623: in method 'finishAction'
	Lua\humanoid_actions\walk.lua:193: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:105: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>

**Comment by TheCycoONE** [comment]
Shouldn't Hospital:searchForHandymanTask just not return any assigned tasks?

**Comment by TheCycoONE** [comment]
So the issue must mean that I'm unassinging tasks without clearing the call assignment. - I am. Why do we ever want that?

**Comment by TheCycoONE** [comment]
Anyway, the main differences are that interruptTask use to not remove assignment on the task (just the call), and only removed the task from the handyman, and goToStaffroom use to unassign the task at the top.

**Comment by TheCycoONE** [comment]
My change to interruptHandymanTask could cause problems. I remove the assignment on the task before that handyman goes to AnswerCallAction which could cause them to take the task again, but it is also assigned to the another handyman in hospital.

Just set self.task = nil instead of calling my function there like it use to. so the task isn't ever unassigned.

**Comment by mugmuggy** [comment]
I've tested with the handyman change. Hospital I didn't notice any related issues but have reverted it back also.

**Comment by TheCycoONE** [comment]
Should this be closed now?
