### ISSUE TITLE
Installing via Homebrew appears broken

### ISSUE THREAD

**Issue by Kaganis** [CorsixTH/CorsixTH#1518]
When running after a fresh install via Homebrew, I get the following error message:

"An error has occurred in CorsixTH:
cannot open /usr/local/Cellar/corsixth/0.62/CorsixTH.app/Contents/Resources//CorsixTH.lua: No such file or directory
stack traceback:
	[C]: in function 'assert'
	[C]: in ?"

There's only an option to exit at this point.  I'm on MacOS 10.14.4. 

#### Steps to Reproduce
1. Install Corsixth via Homebrew (brew install corsixth)

2. Run corsixth from the command line.

3. Error

#### Expected Behavior
No error (not personally sure, not used it before).

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.62 according to https://formulae.brew.sh/formula/corsixth

**Operating System:** *e.g. Windows 10*
MacOS 10.14.4

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
N/A

#### Gamelog.txt
Doesn't appear to have been created.  XDG_CONFIG_HOME hasn't been set and ~/.config/CorsixTH hasn't been created.

**Comment by colinjmatt** [comment]
Have you moved the .app from `/usr/local/Cellar/corsixth/0.62/` to another directory? The app doesn't use relative directories when building which means moving it from the Homebrew build location to `/Applications` will cause this error.

For example, [the build found on the releases page](https://github.com/CorsixTH/CorsixTH/releases/download/v0.62/CorsixTH.0.62.dmg) will only work in `/Applications` as that is where it was built.

**Comment by Kaganis** [comment]
I've left it where homebrew puts it.

**Comment by Kaganis** [comment]
To clarify, /usr/local/Cellar/corsixth/0.62/CorsixTH.app/Contents/Resources exists, but only contains Icon.icns

I've also opened up an issue on the Homebrew Github, since I don't know if it's them rather that you who's got the bug.  Apologies if this turns out to be a build / packaging issue their end.  :-)

**Comment by colinjmatt** [comment]
I suspect this is an issue with Homebrew and how it's building if there's only an icon file in there (there should be many more files).

The .dmg I linked above should work "straight out of the box" if you want to get CorsixTH working straight away. :)

**Comment by Kaganis** [comment]
Ta, both for that & the quick response.  I'm in no rush so will see if homebrew can sort the problem out.

I'm happy for you to close this issue, but will leave it up to you in case you wanted to do any more investigation..  :-)

**Comment by tobylane** [comment]
The homebrew recipe has been updated. Can you try again?

**Comment by Kaganis** [comment]
Yep, seems to work now.  Thanks very much!

Using files from the Origin version of the game, I get the following warnings in the terminal window when pointing corsixth at the game file locations, but since they're just warnings, I'm happy to ignore them.  I'm really only including them here as an FYI:

---------------------------------------------------------------

Welcome to CorsixTH v0.62!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The multigesture handler.
A stack trace is included below, and the handler has been disconnected.
...ixth/0.62_1/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: attempt to call a nil value (method 'onMultiGesture')
stack traceback:
	...ixth/0.62_1/CorsixTH.app/Contents/Resources//Lua/app.lua:1106: in function <...ixth/0.62_1/CorsixTH.app/Contents/Resources//Lua/app.lua:1105>
	(...tail calls...)
	...ixth/0.62_1/CorsixTH.app/Contents/Resources//Lua/app.lua:915: in function <...ixth/0.62_1/CorsixTH.app/Contents/Resources//Lua/app.lua:910>

Warning: No event handler for multigesture


Restarting...




---------------------------------------------------------------

Welcome to CorsixTH v0.62!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Cannot check for updates since LuaSocket is not available.

**Comment by TheCycoONE** [comment]
That warning is already fixed for 0.63
