### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [CorsixTH/CorsixTH#1526]
#### Not issue, just info:

📦 CorsixTH RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/corsix-th/)

How to install:
```shell
sudo dnf copr enable atim/corsix-th -y && sudo dnf install corsix-th -y
```
Run:
```
corsix-th
```

**Comment by tim77** [comment]
Now [in main Fedora repos](https://bodhi.fedoraproject.org/updates/FEDORA-2019-22a8be6b1f).

How to install:

```
sudo dnf install corsix-th
```

**Comment by TheCycoONE** [comment]
Excellent! Are you atim?

**Comment by tim77** [comment]
> Excellent! Are you atim?

Yep. :)

**Comment by TheCycoONE** [comment]
@emorrp1 is the Debian packager; it probably makes sense to collaborate to an extent; and bug me for common needs.
