### ISSUE TITLE
If you are late building a receptionist, you get multiple announcements from her in one go

### ISSUE THREAD

**Issue by terrorcide** [CorsixTH/CorsixTH#1533]
#### Describe the issue
If you are late building a receptionist (April), you get multiple announcements from her in one go

#### Steps to Reproduce
1. *Load save game attached to this ticket* - https://drive.google.com/open?id=1_r9ngIcMWFYq5GLnzpEEvruvYtkrlBln

2. Hire a receptionist

3. Observe multiple announcements

#### Expected Behavior
* Retail doesn't do this from what I can see

#### System Information
**CorsixTH Version: commit 27f5bb8a1b5e9c5e62295ec4befb13d43b8d1867

**Operating System: XUbuntu 18.04.2 LTS

**Theme Hospital Version:** GOG

**Comment by TheCycoONE** [comment]
Side effect of the new announcement queue, and I agree it's weird. We should either just discard announcements before the receptionist is working, or more aggressively cull the queue.
