### ISSUE TITLE
Restarting a level plays the board piece moving video (not same as retail)

### ISSUE THREAD

**Issue by terrorcide** [CorsixTH/CorsixTH#1534]
#### Describe the issue
Restarting a level replays the board piece moving video (not same as retail)

#### Steps to Reproduce
* Restart a level

#### Expected Behavior
Retail doesn't do this from what I can see
System Information
**CorsixTH Version: commit 27f5bb8

**Operating System: XUbuntu 18.04.2 LTS

Theme Hospital Version: GOG

**Comment by TheCycoONE** [comment]
Description doesn't match title. Copy & paste error?

**Comment by terrorcide** [comment]
> Description doesn't match title. Copy & paste error?

Thanks - apologies I missed that
