### ISSUE TITLE
multimedia library generalised dependancy

### ISSUE THREAD

**Issue by mattmill30** [CorsixTH/CorsixTH#154]
FFMPEG and LibAV both provide the same components required by Corsix-TH.

For portability and greater availability, Corisix-TH should be adapted to support either library, and the effect of the MOVIES cmake variable should be to select whichever library is available, and enable the compilation of the corresponding libraries interface code.

Optional FFMPEG or LIBAV parameters could be provided to force compilation against a particular library, in the instance that both are available.

**Comment by tonihele** [comment]
I have Kubuntu 15.04. I installed all the ffmeg-dev packages, and still I get:
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find FFmpeg (missing: AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS
  SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  CMake/FindFFmpeg.cmake:89 (find_package_handle_standard_args)
  CorsixTH/CMakeLists.txt:136 (FIND_PACKAGE)

**Comment by Alberth289346** [comment]
Can you tell us where ffmpeg-dev has its header files, and its libraries?

Also, cmake should have a log of places where it looked for ffmpeg, Could you get the places that it looked for ffmpeg?

**Comment by tonihele** [comment]
I assume the libswscale-ffmpeg-dev is the package that is referred by the error. Package manager has this to say about its directories:
/usr/include/x86_64-linux-gnu/libswscale/swscale.h
/usr/include/x86_64-linux-gnu/libswscale/version.h
/usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.a
/usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so
/usr/lib/x86_64-linux-gnu/libswscale.a
/usr/lib/x86_64-linux-gnu/libswscale.so
/usr/lib/x86_64-linux-gnu/pkgconfig/libswscale-ffmpeg.pc
/usr/lib/x86_64-linux-gnu/pkgconfig/libswscale.pc
/usr/share/doc/libswscale-ffmpeg-dev/changelog.Debian.gz
/usr/share/doc/libswscale-ffmpeg-dev/copyright

**Comment by tonihele** [comment]
I'm unable to determine where this cmake logs these. I found some logs. But I was not able to say where is tells the needed info. Could you point me in right direction?

**Comment by Alberth289346** [comment]
CMakeFiles seems to have .log files, but I can't find my ffmpeg libraries in it.

Also, it seems to consider other libraries as being ffmpeg. I don't know if it's working, as I have movies disabled in the config:
````
-- Found AVCODEC: /usr/lib64/libavcodec.so (found version "56.26.100") 
-- Found AVFORMAT: /usr/lib64/libavformat.so (found version "56.25.101") 
-- Found AVDEVICE: /usr/lib64/libavdevice.so (found version "56.4.100") 
-- Found AVUTIL: /usr/lib64/libavutil.so (found version "54.20.100") 
-- Found SWSCALE: /usr/lib64/libswscale.so (found version "3.1.101") 
-- Found POSTPROC: /usr/lib64/libpostproc.so (found version "53.3.100") 
-- Found SWRESAMPLE: /usr/lib64/libswresample.so (found version "1.1.100") 
-- Found FFmpeg: /usr/lib64/libavformat.so;/usr/lib64/libavcodec.so;/usr/lib64/libavutil.so;/usr/lib64/libswscale.so;/usr/lib64/libswresample.so  
  FFmpeg found
````
This is Fedora, maybe your libraries have a different name. (package of avdevice is however ffmpeg-devel-2.6.4-1.fc22.x86_64, so that seems to be correct)

**Comment by TheCycoONE** [comment]
On Ubuntu you'll need to use -DWITH_LIBAV=ON or else manually specify the location of ffmpeg. CorsixTH supports LibAV these days.

**Comment by Lego3** [comment]
Closing the issue
