### ISSUE TITLE
Builds include libraries twice

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1543]
#### Describe the issue
Portable and windows build includes dlls twice.

avcodec-57.dll
avcodec-58.dll
avformat-57.dll
avformat-58.dll
avutil-55.dll
avutil-56.dll
swresample-2.dll
swresample-3.dll
swscale-4.dll
swscale-5.dll

**Comment by TheCycoONE** [comment]
Resolved.
