### ISSUE TITLE
Suggestion: Submit CorsixTH to Athenaeum

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#1546]
[gitlab.com/librebob/athenaeum](https://gitlab.com/librebob/athenaeum)

**Comment by TheCycoONE** [comment]
Depends on #1416

**Comment by tobylane** [comment]
Is this now complete?

**Comment by lewri** [comment]
This is now in Flathub; and Athenaeum pulls directly from there.
Confirmed. However, the Athenaeum application is a bit broken right now and needed tweaks to get it worked.

Nonetheless...
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/29c4c900-27ea-4c12-84b7-21f0588ebff4)
