### ISSUE TITLE
Libretro Core

### ISSUE THREAD

**Issue by SpaceAgeHero** [CorsixTH/CorsixTH#1553]
Dear team,
please consider developing a Libretro Core to be used with Retroarch.

**Comment by tobylane** [comment]
We use SDL2, which appears to have a work in progress libretro implementation here: https://github.com/r-type/sdl2-libretro. Try building CorsixTH with that, and see if the error messages are about missing features in SDL2.

**Comment by lewri** [comment]
Liberto w/ SDL2 appears to have stalled in development. But correct me otherwise.

**Comment by lewri** [comment]
Liberto project has stalled. Closing for now.
