### ISSUE TITLE
Urgency patients not cured if facility is built after accept the urgency

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#1556]
#### Describe the issue
If you receive an urgency that requires a facility that is not yet built and then you accept the urgency and builds the facility during the patients arrive, makes the urgency patients stuck in the hospital without being cured

#### Steps to Reproduce
1. Receive an urgency of a treatment that needs a facility that is not already built.
2. Accept it
3. Build the necessary facility to accomplish the urgency after acepting the urgency
4. The urgency patients arrive and wait infinitely in the hospital until the times ends (then they die)

You can download this [saved game](https://github.com/CorsixTH/CorsixTH/files/3489174/STAGE7-UrgencyError.zip) and check that there is one urgency patient to be treated in the surgery room that was built while the patient was arriving, but the patient is stuck in the hospital without getting in the row of the surgery room 

#### Expected Behavior
Patients must be notified about new buildings to get cured or treated

#### System Information
**CorsixTH Version:** *0.63*

**Operating System:** *Windows 7 Home Premium SP1*

**Theme Hospital Version:** *CD*

**Comment by mugmuggy** [comment]
The seek room action changes I made in 0.63 around the room detection scenarios I believe is specifically checking for the existence of both the ward and operating theatre here and not seeking. I found another issue with this last week where you could also destroy a room (diagnosis only) even though it wasn't seeking the treatment rooms specifically this prevented the seek action from executing. I'll tack this on to the other change.
