### ISSUE TITLE
Error in timer handler

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#1558]
#### Describe the issue
While playing, this dialog appeared several times:
![errorcorsix](https://user-images.githubusercontent.com/2896275/62825601-f6278700-bbae-11e9-9f32-b646606a2f80.png)

I click accept but the dialog appears repeteadly until the error seems recovered.

At least two times ocurred in this level:

- [STAGE6-ERROR.zip](https://github.com/CorsixTH/CorsixTH/files/3489211/STAGE6-ERROR.zip)
- [STAGE6-ERROR2.zip](https://github.com/CorsixTH/CorsixTH/files/3489212/STAGE6-ERROR2.zip)

I think the problem is related to the bald guy blocked in the corner in the entrance of the hospital. In the first saved game he is in a vomiting loop:

![errorcorsix3](https://user-images.githubusercontent.com/2896275/62825705-62ef5100-bbb0-11e9-9865-ee11a0722e50.png)
In the second I've tried to send it to home but he still in the hospital

![errorcorsix2](https://user-images.githubusercontent.com/2896275/62825698-39362a00-bbb0-11e9-9d2f-46fb1cddad82.png)

#### System Information
**CorsixTH Version:** *0.63*

**Operating System:** *Windows 7 Home Premium SP1*

**Theme Hospital Version:** *CD*

#### Gamelog.txt
```
Created game with savegame version 134.
Warning: Trying to remove nonexistant room build callback (function: 000000001BF04890) from humanoid (table: 000000001EE1E950).
Warning: Trying to remove nonexistant room remove callback (function: 000000001BEEA4C0) from humanoid (table: 000000001EE1E950).
Warning: Trying to remove nonexistant staff callback (function: 000000001BF04900) from humanoid (table: 000000001EE1E950).
Warning: Trying to remove nonexistant room build callback (function: 000000001BF058C0) from humanoid (table: 000000001F124050).
Warning: Trying to remove nonexistant room remove callback (function: 000000001C002B80) from humanoid (table: 000000001F124050).
Warning: Trying to remove nonexistant staff callback (function: 000000001BF05930) from humanoid (table: 000000001F124050).
Warning: Trying to remove nonexistant room build callback (function: 000000001F16FDC0) from humanoid (table: 00000000247D5F20).
Warning: Trying to remove nonexistant room remove callback (function: 000000001C243EC0) from humanoid (table: 00000000247D5F20).
Warning: Trying to remove nonexistant staff callback (function: 000000001F16FD50) from humanoid (table: 00000000247D5F20).
Warning: Trying to remove nonexistant room build callback (function: 000000000B6FCD80) from humanoid (table: 0000000024430040).
Warning: Trying to remove nonexistant room remove callback (function: 000000001C00F330) from humanoid (table: 0000000024430040).
Warning: Trying to remove nonexistant staff callback (function: 000000000B6FCE60) from humanoid (table: 0000000024430040).
Savegame version is 134 (v0.63), originally it was 134 (v0.63)
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
Recovering from error in timer handler...
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

**Comment by mugmuggy** [comment]
I happened on this issue just the other day. Level 6 map has a tile that doesn't appear to be in the hospital (when its within the bounds of the walls). I already have a work around in progress. There is also a tile outside the bounds of the hospital that is passable which could lead to odd behaviour.

**Comment by TheCycoONE** [comment]
Do you know what flags are on the tile (or the coordinates)

**Comment by mugmuggy** [comment]
Inside (56, 71) - not buildable, not in hospital (relevant to the issue at hand)
Outisde (58, 72) - passable next to the door

The following fixes the issue but was yet to validate any other flags with other objects that may have been able to be placed.
    self:setCellFlags(56, 71, {hospital = true, buildable = true, buildableNorth = true, buildableSouth = true, buildableEast = true, buildableWest = true})
    self:setCellFlags(58, 72, {passable = false})
