### ISSUE TITLE
Null Pointer Exception in Litter.setLitterType

### ISSUE THREAD

**Issue by AlexUrbanAc** [CorsixTH/CorsixTH#1563]
#### Describe the issue
During hospital evacuation, with people throwing up in the streets, the nil value returned by World:getHospital (world.lua:2251) is not checked correctly before calling Hospital:addHandymanTask in Litter.setLitterType (litter.lua:90)

#### System Information
**CorsixTH Version:** 0.63

#### Gamelog.txt
Error in timer handler: 
Lua\objects\litter.lua:90: attempt to index a nil value (local 'hospital')
stack traceback:
	Lua\objects\litter.lua:90: in method 'setLitterType'
	Lua\humanoid_actions\vomit.lua:33: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1042: in method 'onTick'
	Lua\app.lua:1111: in function <Lua\app.lua:1108>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
Recovering from error in timer handler...

**Comment by mugmuggy** [comment]
#1436 attempted to fix some of these, and that is in 0.63. I'm testing a lot at the moment with the save from that issue, which has rolling epidemics, it never has occured outside the ones already suffering with that bug. The other one is #1440 which was related to a bunch of maps and wouldn't be corrected on an old save.

'In the streets' could relate to either the issue, and your autosave would help with that.

**Comment by TheCycoONE** [comment]
@AlexUrbanAc did you have a save file?

**Comment by lewri** [comment]
I had a look at the save as mentioned in #1436 . I tracked down the patient that caused the error.

The patient wanted to vomit as it was in their action queue. But they also had reached the end of the hospital grounds. Subsequently, I assume that because they reached the last time, that action completed; and thus they then proceeded to vomit.

```lua
Clicked on:
humanoid - class: Standard Female Patient
Warmth: 0.305   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.341  Toilet_Need: 0.562   Health: 0.552
Actions: [vomit   must_happen, walk - going to 128:64   must_happen, spawn   must_happen]
```

At this point the patient is probably now considered outside hospital grounds, which is why we got a nil value for setLitterType -- they're no longer linked to a hospital.

An additional note, I noticed that someone while exiting also decided to use the vending machine. I imagine the easiest fix for this would be to clear every patient's action queue on evacuation and just make everyone leave as the only action.

**Comment by mugmuggy** [comment]
@Alberth289346 #1768 changes the behaviour of this. As the Litter will be assigned to a hospital, this will allow the patient to successfullly vomit outside the bounds of the hospital. It also allocates the handyman task to be allocated, so handymen will leave the hospital bounds to clean it.

However action_sweep_floor_start does this, which is nil in these same cases as this issue exists.
```lua
  local hospital = litter.world:getHospital(litter.tile_x, litter.tile_y)
```
I don't recall anyone vomiting outside the hospital walls in the original, but you can kill rats between buildings. That rat spawns from a hospital and is 'owned' by it, so handymen should clean it from that hospital. So this change makes sense. Though future network games will require additional changes around World:newObject and its hospital allocation.

**Comment by lewri** [comment]
Yes you could kill rats between hospitals on original. They didn't generate any litter though when you did that. 
I don't think they could vomit between buildings either. But I also think if they were holding vomit until they re-entered a building they wouldn't do it straight away, there was a little wait I think.

**Comment by Alberth289346** [comment]
Cleaning litter outside at the edge of the map seems weird to me, I'd suggest to aim for not vomiting or littering outside hospital floors.

**Comment by tobylane** [comment]
Vomit is indoors only already in [patient.lua](https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/entities/humanoids/patient.lua#L353), litter is fixed by the linked pr.
