### ISSUE TITLE
Linux: black menu butttons

### ISSUE THREAD

**Issue by legluondunet** [CorsixTH/CorsixTH#1570]
Hello,

I just compiled last Corsix-TH git version and I have an issue with bar menu: the buttons at the right are all black. If I put my cursor on, they reappear.

I joined you a video.
[Screencast_08-12-2019_15:49:36_EDIT.zip](https://github.com/CorsixTH/CorsixTH/files/3936428/Screencast_08-12-2019_15.49.36_EDIT.zip)

Thank you for your help.

Tested and compiled on Ubuntu 18.04 and 19.10
GPU: NVidia

**Comment by TheCycoONE** [comment]
That's the debug mode info pane. Add a staff member and hover over them. Look for debug in your config file.

**Comment by legluondunet** [comment]
are you talking about this option? If so it is already set to false.

-- Debug settings.
-- If set to true more detailed information will be printed in the terminal
-- and a debug menu will be visible.
-- 
debug = false

**Comment by mugmuggy** [comment]
Its the dynamic info bar, whenever you’re doing something away from the control panel the buttons disappear and that part of the control panel becomes the dynamic info bar.
