### ISSUE TITLE
Not being paid for most diagnoses or cures

### ISSUE THREAD

**Issue by TwoTailedFox** [CorsixTH/CorsixTH#1571]
#### Describe the issue

Some patient payments towards cures and diagnoses are not being passed to the bank ledger for the balance to be updated.

#### Steps to Reproduce
1. [1.zip](https://github.com/CorsixTH/CorsixTH/files/3999101/1.zip) The zip file attached has a balance in negative figures, caused somewhat by this issue.

2. Look at the Bank Statement

3. You'll see cure costs without cure payments from patients. As for the missing diagnosis fees... you'll have to take my word for them. Some are going through, but not all.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your savegames to
another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### Expected Behavior

Diagnosis or cure fees paid by the patient should always update the ledger in real-time.

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*

0.63

**Operating System:** *e.g. Windows 10*

Windows 10

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

GOG.com

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file
*
```
Paste gamelog.txt output here
```

[config.txt](https://github.com/CorsixTH/CorsixTH/files/3999144/config.txt)

### Additional Info
*Paste any screenshots or other additional information that might help
illustrate the problem.*

![THSS](https://user-images.githubusercontent.com/13187606/71426075-6fc29c00-269c-11ea-99a3-add0df5cdef4.png)

Screenshot is of bank ledger.

**Comment by TheCycoONE** [comment]
Sometimes patients pay with insurance. That money isn't collected immediately

**Comment by TheCycoONE** [comment]
The other thing that can happen is patients refusing to pay due to cost. Will look into it though.

**Comment by TheCycoONE** [comment]
The insurance balances in that save are:
`{{1153,252,0},{0,0,0},{0,1255,301}}`
so you should see some money come in at month end, and more over the following two month ends. You can actually see that money as owing on the bank screen. I played your save through to the end of the month and see the 301 credited.

I think this covers all of your missing money.
