### ISSUE TITLE
Version 0.6.3 won't open on MacOS 10.6.8

### ISSUE THREAD

**Issue by siucu** [CorsixTH/CorsixTH#1585]
Hi. I just downloaded & installed it, but then it won't even open/load. This comes out all the time even if I click Reopen. I use old Macbook White Core2Duo 2.0 13" Mid-2007 on MacOS X 10.6.8 Snow Leopard.

**Comment by colinjmatt** [comment]
The .app on Github is compiled to work on OSX 10.10 or later and isn't compatible below that version. You could try to install using Homebrew but I believe they only support Sierra (10.12) or higher.

If you're feeling up to it, you could install the dependencies and compile yourself using the instuctions [here](https://github.com/CorsixTH/CorsixTH/wiki/Compiling-for-MacOS-for-distribution-purposes).
