### ISSUE TITLE
Game Crashes On Load (Already T

### ISSUE THREAD

**Issue by Shorthorn-Studios** [CorsixTH/CorsixTH#1590]
#### Steps to Reproduce
1. Start the Game

2.

3.

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### Expected Behavior
The Game Starts or shows an error in console, but both windows close
#### System Information
**CorsixTH Version:** 0.63

**Operating System:** Windows 10 Build 1900s

**Theme Hospital Version:** CD

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Created game with savegame version 134.
Error in music_over handler: 
Lua\audio.lua:574: bad argument #1 to 'loadMusicAsync' (string expected, got nil)
stack traceback:
	[C]: in field 'loadMusicAsync'
	Lua\audio.lua:574: in method 'playBackgroundTrack'
	Lua\audio.lua:476: in method 'playNextOrPreviousBackgroundTrack'
	Lua\audio.lua:483: in method 'playNextBackgroundTrack'
	Lua\audio.lua:601: in function <Lua\audio.lua:597>
	(...tail calls...)
	Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by Shorthorn-Studios** [comment]
nvm fixed

**Comment by TheCycoONE** [comment]
Ok. What was the issue?
