### ISSUE TITLE
Invalid memory access in SDL_CreateRenderer

### ISSUE THREAD

**Issue by markhamnr** [CorsixTH/CorsixTH#1592]
#### Describe the issue

When trying to start CorsixTH, I get a dialog "CorsixTH.exe has stopped working".  My choices are "Debug" and "Close Program".

#### Steps to Reproduce
1. Run CorsixTH.exe

#### Save Game
N/A

#### Expected Behavior
CorsixTH launches.

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** Windows 7

**Theme Hospital Version:** GOG.com

#### Gamelog.txt
Not created

**Comment by TheCycoONE** [comment]
I don't have a Windows 7 machine to check. Can you confirm you installed the proper runtime?

**Comment by TheCycoONE** [comment]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by markhamnr** [comment]
Yes, I have the x64 version of the "Visual Studio 2015, 2017 and 2019"
package installed.

**Comment by TheCycoONE** [comment]
See if you can provide a crash dump. Otherwise there's not much I can do, unless you are able to trace the error / compile yourself.

https://social.technet.microsoft.com/wiki/contents/articles/8103.windows-7-application-crash-dump-analysis.aspx

**Comment by markhamnr** [comment]
Here's a crash dump — hope it helps!

[CorsixTH.exe.2272.dmp.zip](https://github.com/CorsixTH/CorsixTH/files/4440941/CorsixTH.exe.2272.dmp.zip)

**Comment by TheCycoONE** [comment]
Unfortunately I couldn't get much out of that dump - I see the crash is in SDL, but that's expected for anything OS or hardware related. I didn't have the foresight to generate debug files with that build.

Extract this version over top of yours, and send me the resulting dump. I should be able to do more with it:
[CorsixTH-0.63-RelWithDebInfo.zip](https://github.com/CorsixTH/CorsixTH/files/4441757/CorsixTH-0.63-RelWithDebInfo.zip)

**Comment by TheCycoONE** [comment]
(assuming you're on 64bit windows 7)

**Comment by markhamnr** [comment]
I had to install a few extra DLLs, but they seemed to be available free on the Internet so I was able to generate a new dump.  Is this more useful?

[CorsixTH.exe.244.dmp.zip](https://github.com/CorsixTH/CorsixTH/files/4445457/CorsixTH.exe.244.dmp.zip)

**Comment by TheCycoONE** [comment]
Yep, got it thanks. It's crashing in SDL_CreateRenderer when it should be creating the window. It looks like glMatrixMode isn't there. That comes from your video driver. Are there any updated video drivers available. Please do paste your GPU info (make, model, driver version)
I can see if it was reported/fixed upstream.

**Comment by markhamnr** [comment]
I'm running Windows in VirtualBox 5.2, so there's not much of a GPU to speak of.  Device Manager calls it a "VirtualBox Graphics Adapter" with driver version 5.2.34.0, if that's any help.  But maybe we just shouldn't expect CorsixTH to work without a discrete GPU?

**Comment by TheCycoONE** [comment]
Try setting the environment variable `SDL_VIDEODRIVER=software` - but generally yes we require accelerated graphics (not necessarily a discrete GPU)

**Comment by markhamnr** [comment]
FWIW, I just got around to trying $SDL_VIDEODRIVER, and all it did was change the error (to "Unable to initialize video").  Not a huge surprise since my configuration really wasn't expected to work.  Thanks for the help looking into it anyway!

**Comment by TheCycoONE** [comment]
No problem. Is there anything preventing you from running on bare metal?

**Comment by mugmuggy** [comment]
You can also try without that, and ensure you have 3D acceleration turned on in the display settings of the VM, install guest additions without d3d - this works for me. Maybe go down the path of enabling d3d in the guest additions if it doesn't work.

**Comment by TheCycoONE** [comment]
I know vmware linux guests work too actually.

**Comment by markhamnr** [comment]
Turning on 3D Acceleration in VirtualBox seemed to do the trick — thanks @mugmuggy!  (Not sure why I didn't think of that.)

Incidentally, the reason I was using a VM was just that I was trying to troubleshoot a similar issue for a family member who runs Windows.  I only have Linux machines, so VirtualBox was the easiest way for me to try the Windows build.  When it didn't run for me, I assumed I'd reproduced their issue, but now it's obvious that it was two different issues.  If I ever get more information on the original (non-virtualized Windows) bug, I'll report it, but current events make that unlikely. :)
