### ISSUE TITLE
Problem with custom campaign

### ISSUE THREAD

**Issue by B17Fan** [CorsixTH/CorsixTH#1593]
I am playing Chrizmantv - dethster hospital - and I have had so many problems with it. See the log file attached.

![error theme hospital](https://user-images.githubusercontent.com/48420174/78898727-2f7d0300-7a6c-11ea-84e1-a6f9442d4ddc.JPG)

Also i get issues with loads of patients suddenly going to one gp's office.

**Comment by mugmuggy** [comment]
The save demonstrating this - like the issue template indicates - would help. Its as if a room is in a invalid state: its active but has no queue on the door (its closed?).

Patients going to one room is a side effect of queue length determination and what they will also do when a door is closed.

**Comment by B17Fan** [comment]
How do i share the saved game here?

**Comment by mugmuggy** [comment]
Zip it up and copy/paste it in... instructions should appear in the bottom of the reply box.
![image](https://user-images.githubusercontent.com/8009292/78905352-341fd680-7ac1-11ea-95af-ac38019530bc.png)

**Comment by B17Fan** [comment]
[after update.zip](https://github.com/CorsixTH/CorsixTH/files/4457272/after.update.zip)

**Comment by mugmuggy** [comment]
The underlying fix is in 0.63, but the issue had already occured by this stage.

You can correct it by enabling debug in the configuration file: https://github.com/CorsixTH/CorsixTH/wiki/Configuration-File
And then, either using the console:  https://github.com/CorsixTH/CorsixTH/wiki/Lua-Console
or alter the debug_script.lua file run the below (Shift-D) as soon as you open that save.

```lua
for _, pat in ipairs(TheApp.world.hospitals[1].patients) do
  if not pat.staff_change_callbacks then
    pat.staff_change_callbacks = {}
  end
end
```

**Comment by B17Fan** [comment]
two questions: Would it be better if i just restarted the level?
And this issue with loads of people queuing,  Every so often, you end up with about 20 or 30 patients all going to one gp office. Especially if you build a new gp office. All the Queues are set to 6. Will the 0.63 update fix this?

**Comment by mugmuggy** [comment]
There are numerous issues with that level so it might be worthwhile starting over. Some of those issues are not fixed in 0.63 but have been addressed since.

Likewise the movement of many patients to a room, isn't fixed either in 0.63 and only part of that is fixed currently, but there are many other fixes. Your previous issue (1498) was also on 0.60 from what I could tell and there again had been numerous fixes that would have addressed issues moving to the latest release.

**Comment by lewri** [comment]
@B17Fan have you come across this issue again in 0.64, if you've had a chance to play again from the start?

**Comment by lewri** [comment]
Owing that the same comes from 0.60 it can't be ruled out that the bug is caused from an old version.
``Savegame version changed from 134 (v0.63) to 138 (v0.64). The save was created using 111 (v0.60)``

Closing this, but happen to reopen if the same bug occurs in a new run of the level.
