### ISSUE TITLE
How to make custom maps playable?

### ISSUE THREAD

**Issue by B17Fan** [CorsixTH/CorsixTH#1594]
Can someone give me advice on how to make custom maps playable? I made a good map and saved it, but how do i play it and how do i set the money and goals etc?

**Comment by MarkL1961** [comment]
You need to create/edit a leve; file as well https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels

**Comment by B17Fan** [comment]
So i have copied and renamed the example level. I've named it the same as the map i made. But when i look at the single scenarios. it says example twice. And none of those have loaded my map i made. what am i doing wrong?

**Comment by TheCycoONE** [comment]
The level file has a line in it for the map it uses. Open the level file and change that line to your map name.

**Comment by B17Fan** [comment]
So i opened the level file with notepad. But when i go to save the changes i made, it says i don't have permission to save it or i can't save it in program files. How do i save it?

**Comment by TheCycoONE** [comment]
If https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels doesn't have all the information you need, please update it.

The level file should be copied to your user level directory, which is in the same location as the config.txt and gamelog.txt. `C:\Users\$(User)\AppData\Roaming\CorsixTH\Levels` on Windows. That should be where your map was saved too.

**Comment by TheCycoONE** [comment]
Nothing actionable in this ticket.
