### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by FrankieCZ282** [CorsixTH/CorsixTH#1595]
![hospital](https://user-images.githubusercontent.com/63579643/79102278-b3840300-7d6a-11ea-9162-fe22fa375af3.png)
#### Describe the issue
I install CorsixTh from Synaptic package manager, (because I am quiet new to Linux)
When I start the game, some text are "ugly"

#### System Information
**CorsixTH Version:* 0.61-1

**Operating System:** Linux Mint 19.3 Cinnamon

**Theme Hospital Version:** CD

#### Gamelog.txt

```
Created game with savegame version 122.
Error in callback handler: 
./Lua/audio.lua:580: Could not load music file 'Sound/Midi/NIGHTSH.XMI' (Unrecognized audio format)
stack traceback:
	[C]: in function 'yield'
	./Lua/app.lua:909: in function <./Lua/app.lua:904>
```

### Additional Info
![hospital](https://user-images.githubusercontent.com/63579643/79102289-b979e400-7d6a-11ea-9368-49e429a53cc1.png)

**Comment by tobylane** [comment]
Can you update to 0.63 or the latest from the master branch? 0.63 should be in your package manager.

**Comment by FrankieCZ282** [comment]
In manager is only version 0.61-1  :-(

**Comment by TheCycoONE** [comment]
That's ok, there haven't been any substantial changes to font rendering in the past several versions. Obviously it doesn't do that for everyone, so it's something environmental. It should be using the font from Theme Hospital - which combined with the missing audio - makes me think something is suspect with your Theme Hospital data.

Please paste your `config.txt` and include information about where/how you installed Theme Hosptial.

**Comment by FrankieCZ282** [comment]
I made a new folder called "game" in home folder, where I put Theme Hospital

Config
[config.txt](https://github.com/CorsixTH/CorsixTH/files/4469680/config.txt)

**Comment by TheCycoONE** [comment]
But what Theme Hospital. Where did you get it?

**Comment by TheCycoONE** [comment]
No update. Appears to be an environment / data issue.
