### ISSUE TITLE
Push requests on translation

### ISSUE THREAD

**Issue by hpoyatos** [CorsixTH/CorsixTH#1596]
#### Describe the issue
Hi, guys!

I helped to translate CorsixTH to Brazilian Portuguese back to 2012 (See header on brazilian-portuguese.lua).
I would like do make some updates/corrections.. I have the new file ready, and I would like to make a push request on repository, but I can't.

Maybe should send the file to one of you?

**Comment by TheCycoONE** [comment]
Yep, if you're comfortable with pull requests go for it, otherwise paste the file here.

**Comment by lewri** [comment]
@hpoyatos We have some updates in #1639 to Brazilian Portuguese but it is always worth having people who know the languages around to make sure we get it right.
