### ISSUE TITLE
Sending Patients Home calls room build function

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1599]
#### Describe the issue
Not a particular issue hindering performance but likely will require a cleanup.
It appears when you send home a patient through the 'exhausted all diagnosis' fax it tries to call some room functions.

#### Steps to Reproduce
1. Click the green question mark prompt for the patient who is awaiting a decision

2. Click send home

#### Save Game
https://www.dropbox.com/s/vrdr4w0r8gjfdlu/savegame4buildcalls.sav?dl=0

#### Expected Behavior
Probably not to call these functions 

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** W10

**Theme Hospital Version:** GOG

**Output from the console/cmd**
```
Warning: Trying to remove nonexistant room build callback (function: 000001DE52530760) from humanoid (table: 000001DE4A5FCA20).
Warning: Trying to remove nonexistant room remove callback (function: 000001DE529F0140) from humanoid (table: 000001DE4A5FCA20).
Warning: Trying to remove nonexistant staff callback (function: 000001DE52530A00) from humanoid (table: 000001DE4A5FCA20).
-----------------------------------
Clicked on:
humanoid - class: Invisible Patient
Warmth: 0.297   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.647  Toilet_Need: 0.294   Health: 0.742
Actions: [walk - going to 126:1   must_happen, spawn   must_happen]
-----------------------------------
-----------------------------------
Clicked on:
humanoid - class: Invisible Patient
Warmth: 0.297   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.647  Toilet_Need: 0.294   Health: 0.742
Actions: [walk - going to 126:1   must_happen, spawn   must_happen]
-----------------------------------
Warning: Trying to remove nonexistant room build callback (function: 000001DE52530D10) from humanoid (table: 000001DE4A6E9070).
Warning: Trying to remove nonexistant room remove callback (function: 000001DE51CFB320) from humanoid (table: 000001DE4A6E9070).
Warning: Trying to remove nonexistant staff callback (function: 000001DE525318E0) from humanoid (table: 000001DE4A6E9070).
```

**Comment by mugmuggy** [comment]
When I implemented the staff callback I didn't really know if I should have implemented the logic for the warning on it, but did as they were used for diagnosing issues earlier on. When I could have removed them. They don't indicate an error, but you do tend to get a lot more now as another change I had made ensures the callbacks are removed in more instances to prevent them being called when they shouldn't.

**Comment by lewri** [comment]
Yeah I suppose this is more of a cleanup issue. At the moment I'm just playing through again slowly to see if there's anything happening that shouldn't be -- like these warnings.

Feel free to ignore them though. I think I'm a bit of a perfectionist sometimes when it comes to these things.

**Comment by lewri** [comment]
An additional update. Same kind of error but different situation. If you have a patient waiting in your hospital for a clinic room to be built, it also causes the same error.

**Comment by lewri** [comment]
Duplicate of #722
