### ISSUE TITLE
Doctors in certain rooms stop working, do not go to staff room - possibly after editing staff room

### ISSUE THREAD

**Issue by ciand** [CorsixTH/CorsixTH#1602]
#### Describe the issue

In one particular large save I have twice now experienced an issue where certain doctors will stop actually working - e.g. surgeons in theatre will revert to their white coat but not leave the room, doctors in GP rooms will wander around the room with a patient in the chair; and other doctors will not leave rooms. I realised that this may be connected to editing a staff room shortly beforehand - one was moved before the first time; and one was resized before the second time. 

I have multiple staff rooms and even staff very distant from the edited room have been affected, however. I cannot reproduce the issue on demand

Both edited staff rooms have valid paths to get to them and are being used by other staff

I've searched for this issue in pre-existing tickets but can't see anything except possibly issue 492

#### System Information
**CorsixTH Version:** 0.63

**Operating System:* Window 10

**Theme Hospital Version:** CD

#### Gamelog.txt
Created game with savegame version 111.
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: Trying to remove nonexistant room build callback (function: 0000000016B8FB00) from humanoid (table: 0000000016BF2C40).
Warning: Trying to remove nonexistant room remove callback (function: 0000000013DED770) from humanoid (table: 0000000016BF2C40).
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: Trying to remove nonexistant room build callback (function: 0000000016B8D4C0) from humanoid (table: 0000000016CD6E80).
Warning: Trying to remove nonexistant room remove callback (function: 000000000D4EB680) from humanoid (table: 0000000016CD6E80).
Warning: Trying to remove nonexistant room build callback (function: 00000000141E4BC0) from humanoid (table: 0000000009CD2750).
Warning: Trying to remove nonexistant room remove callback (function: 0000000018E6C080) from humanoid (table: 0000000009CD2750).
Warning: Trying to remove nonexistant room build callback (function: 000000001378ABD0) from humanoid (table: 000000001BAC2F70).
Warning: Trying to remove nonexistant room remove callback (function: 000000000C6725B0) from humanoid (table: 000000001BAC2F70).
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Savegame version is 111 (v0.60-rc1), originally it was 111 (v0.60-rc1)
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Warning: goHome called when the patient is already going home
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\map.lua:60: bad argument #1 to 'floor' (number expected, got nil)
stack traceback:
	[C]: in function 'math.floor'
	C:\Program Files\CorsixTH\Lua\map.lua:60: in method 'getRoomId'
	C:\Program Files\CorsixTH\Lua\world.lua:2254: in method 'getRoom'
	C:\Program Files\CorsixTH\Lua\room.lua:75: in method 'getEntranceXY'
	C:\Program Files\CorsixTH\Lua\room.lua:692: in upvalue 'tryMovePatient'
	C:\Program Files\CorsixTH\Lua\room.lua:754: in method 'tryToFindNearbyPatients'
	C:\Program Files\CorsixTH\Lua\room.lua:554: in field 'onHumanoidLeave'
	C:\Program Files\CorsixTH\Lua\rooms\gp.lua:199: in method 'onHumanoidLeave'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:352: in field 'on_next_tile_set'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:219: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1059: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1000: in function <C:\Program Files\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:901: in function <C:\Program Files\CorsixTH\Lua\app.lua:896>

**Comment by mugmuggy** [comment]
Editing staff room issue should be addressed in the next version.

**Comment by lewri** [comment]
Issue now appears resolved in new version
