### ISSUE TITLE
Clicking inside Bank Manager opens Town Map

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1605]
#### Describe the issue
This may already be the expected behaviour -- if so close it.
However, when in the Bank Manager/Finance window, if you click the car or the pamphlet on the bottom it opens up the Town Map.

As far as I can see the bottom objects in no way relate to the town map.

#### Steps to Reproduce
1. Open Bank Manager window and click car or pamphlet

#### Expected Behavior
May be the expected behaviour already. But it does throw me off when trying to view the balance sheet. Otherwise Town Map shouldn't open.

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** W10

**Theme Hospital Version:** GOG

**Comment by MarkL1961** [comment]
It is expected, as is clicking on balance in town map takes you to the bank screen

**Comment by lewri** [comment]
Okay I'll close this one then
