### ISSUE TITLE
Doctors in Research Room waiting for imaginary patient

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1606]
#### Describe the issue
In the last two levels I've been playing I've noticed that sometimes doctors in the Research Room are in state 'waiting for patient' despite me not sending anyone for autopsy.
One happened when I dragged a researcher mid-consult from another room (but sometimes will go unnoticed) to the Research Room.

May be a separate issue but can also happen in the operating theatre sometimes (queue becomes empty but doctors get stuck in 'waiting for patient'.

To resolve you just have to pickup the doctor and drop them back in the room. 

#### Steps to Reproduce
1. Load the game file. Go to Research Room

2. Doctor Milwin is in 'waiting for patient' state

To try and reproduce from the start, you could try dragging out a Doctor (Research Skilled) mid-consult or while they have a queue into the Research Room. I don't have a savestate of that one though.

#### Save Game
https://www.dropbox.com/s/u6apj6662ukwbdg/waitingresearcher.sav?dl=0

#### Expected Behavior
Doctors shouldn't be waiting for 'imaginary patients'.

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt
When selecting the doctor in state:

-----------------------------------
On call: no
Busy:   busy
Last room:      research@62,65
-----------------------------------
Clicked on:
<LocalisedString> Current value:humanoid (MILWIN) - class: Doctor
Warmth: 0.361   Happiness: 0.954   Fatigue: 0.409  Thirst: 0.000  Toilet_Need: 0.000   Health: 0.930
Actions: [use_object - desk   must_happen, meander]
Skills: (0.680)  Surgeon (0.000)  Psych (0.000)  Researcher (1.000)
-----------------------------------

### Additional Info
![image](https://user-images.githubusercontent.com/20030128/82080060-cf692480-96db-11ea-86bc-22cd8823c652.png)

**Comment by mugmuggy** [comment]
This one is from Room:tryAdvanceQueue. If you have two staff at the front of the queue, say one of the researchers and a handyman leaving the room as an example, causing one to queue, it will trigger 'waiting for patient' on all staff in the room. You could check front is a patient, and maybe need to check they are actually entering to avoid setting it to waiting for patient.
