### ISSUE TITLE
Receptionist/Announcements have become mute

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1611]
#### Describe the issue
So in my playthrough file for testing today I have found the receptionist has lost her voice (appeared to happen from loading the game). As a result, announcements do not happen.

I have checked a previous version of my game saves, and the announcements are working there. Not sure if the bug is save specific though or just a me problem.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait for an announcement (use Calls Dispatcher to watch if needed)

#### Save Game
https://www.dropbox.com/s/e7pguu1yzceci0u/Newrun063.sav?dl=0

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** *W10*

**Theme Hospital Version:** GOG

#### Gamelog.txt
None

### Additional Info
Config file setting should allow announcements:
```
-- Announcements: By default set at level 0.5
-- 
play_announcements = true
announcement_volume = 0.2
```

Just going to add that I wondered if replacing the receptionist would fix it... it did not.

**Comment by mugmuggy** [comment]
If I understand it correctly an announcement was being made whilst the last save was taken the announcer state will incorrectly persist with the playing property set to true. This prevents further announcements from playing. It gets recreated when you move on to next level. So it would be only a major issue if playing in a very long running hospital with the eventual out of memory error that would occur.

**Comment by lewri** [comment]
No idea. But it was weird. Would there be a way to reset the announcer state perhaps on load of a savefile?

**Comment by TheCycoONE** [comment]
yes, that's probably the fix.
