### ISSUE TITLE
Suggestion: Truncate decimal .0 from Annual Report

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1615]
I've noticed in the annual report that the player's salary, all 'richest', and all total value figures are reported as xxxxx.0
In reality and in line with the game only using whole numbers for money, the .0 should be truncated. This is still present in the current version 0.63.

I would have tried to look at changing this myself in the relevant file (either using math.floor or converting to text) but to be honest I'm not wholly confident in tackling it.

![image](https://user-images.githubusercontent.com/20030128/82709214-fb564e00-9c77-11ea-9da5-851c6470605b.png)

**Comment by lewri** [comment]
This is probably a very bad way of doing it, but would it work?

```lua
    -- TODO: Right now there are no real competitors, they all have initial values.
    for i, hospital in ipairs(world.hospitals) do
      self.money_sort[i] = {value = math.floor(hospital.balance - hospital.loan), hosp_index = i}
      self.visitors_sort[i] = {value = hospital.num_visitors, hosp_index = i}
      self.deaths_sort[i] = {value = hospital.num_deaths, hosp_index = i}
      self.cures_sort[i] = {value = hospital.num_cured, hosp_index = i}
      self.value_sort[i] = {value = math.floor(hospital.value), hosp_index = i}
      self.salary_sort[i] = {value = math.floor(hospital.player_salary), hosp_index = i}
    end
```

**Comment by TheCycoONE** [comment]
Not bad, we need to do something like that because it's compatible with Lua 5.1-5.4. Try it out and submit a PR if it works!

**Comment by lewri** [comment]
@TheCycoONE yes it does work. :)
However, it causes the a freeze where you end the intro movie to go to the mainly menu when you launch the game. The game music also plays during the freeze.

I put the old file back and the freeze goes away. Any ideas on that?

**Comment by lewri** [comment]
Ignore previous comment. Looks like I must've added whitespace or something somewhere... whatever it was it wasn't happy.

Fixed it now, will make a PR.

**Comment by TheCycoONE** [comment]
Thanks
