### ISSUE TITLE
VIP praise lacks variation

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1616]
#### Describe the issue
I believe this may be a resurfacing of #498 (was marked fixed) but through my entire playthrough every single VIP that has entered my hospital has given the $2000 reward.

Now either I'm very good at keep my hospital running (unlikely), or there may be a problem with the VIP appraisal variation.

For the purposes of testing this I sacked all my handymen just before the VIP enters, sacked all but one nurse, and 2 doctors to make the hospital horribly understaffed. Then even after all of this the VIP still gives out the $2000 award.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Speed through game until VIP leaves to get the award notice.

#### Save Game
https://www.dropbox.com/s/fsasy79j8gs6m5v/vip_test063.sav?dl=0

#### Expected Behavior
On the uploaded save I would've expected the VIP rating to have gone down sharply. In the original, VIP rating was usually quite senstive to everything.

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** W10

**Theme Hospital Version:** GOG

### Additional Info
I believe the previous issue did mention the lack of rats can take away a level of persuasion on the VIP's rating. But it seems like rats either are grossly outweighed in a VIP rating; or other items are not taking full effect.

**Comment by mugmuggy** [comment]
498 seems to cover more the outcomes but not the reward balance.
VIP starts with a rating of 50
https://github.com/CorsixTH/CorsixTH/blob/2982e8448d2a5033e33997ce27f90fdcea079e70/CorsixTH/Lua/entities/humanoids/vip.lua#L38
Thus if there are no major negatives added to that value during the evaluation it will always exceed 2000 on most of the levels. 498 does refer to the level number in that calculation as being a factor but it doesn't look like it changed.
https://github.com/CorsixTH/CorsixTH/blob/2982e8448d2a5033e33997ce27f90fdcea079e70/CorsixTH/Lua/entities/humanoids/vip.lua#L447-L456
In saying that there are other attributes that are out of whack especially on large custom maps, the VIP can be there for years visiting every room, whereas TH its just a subset of rooms.

I thought I had made a comment regarding the vip rating scenarios on another issue, like the score comes back to like 13-15 options which then get associated with the result fax and the award value comes from that. For example it might have been add 1 if rooms are staffed with consultants, no change for doctors, and -1 for juniors.  I believe there are even ratios between staff skill levels and even between staff types, ie you might score higher if you have 2 thirds of staff are consultant level (maybe only to doctors) and you have twice as many doctors as any other staff type etc and the room visiting is just window dressing. But I would have to go back over it again.

**Comment by TheCycoONE** [comment]
Albert did some work on VIPs a few years back, e.g. https://github.com/CorsixTH/CorsixTH/pull/837

That was attached to https://github.com/CorsixTH/CorsixTH/issues/835 but I don't see any comments from @mugmuggy there.

**Comment by TheCycoONE** [comment]
I agree with the earlier ticket that the level modifier looks wrong, especially with a fixed cap.

**Comment by mugmuggy** [comment]
I pulled out my old analysis I had done a while back and went through it again. -5 being the best score. Which is adjusted/limited in places to give you roughly a score on the scale of 0-14 (1-15 if you like). Which is also the exact same number of fax responses you have, co-incidence not.

| Score        | Award $     |
| ------------ |-------------:|
| -5 | 4000 |
| -4 | 2000 |
| -3 | 1500 |
| -2 | 1200 |
| -1 | 800 |
| 0 | 400 |
| 1 | 200 |
| 2+ | 0 |

I haven't included the reputation change, but there are 10 scores that have positive reputation, and the rest of the scores have a negative reputation affect. As its not a fixed amount and there are other issues where I've mentioned the ratios there.

The score is made up of the sum of each group.
|Group| Factor| Score| Comment|
|---|:----|----:|-------|
| 1 | litter <= 10| -1|
| 1 | litter > 10 | 1 |
| 2 | Less than two total staff | 4 |  Skips the other group 2 checks
| 2 | Any staff member > gbv.VeryTired | 2 |
| 2 | Average staff member < gbv.Tired | -1 |
| 2 | Average staff member >= gbv.Tired | 1 |
| 3 | Average patient health >=20 and < 80 | -1 |
| 3 | Average patient health >80 or < 20 | 1 |
| 4 | No doctors | 4 |
| 4 | More than half the doctors are juniors | 2 | 
| 4 | More than half the doctors are consultants | -2 |
| 5 | No rooms | 4 | 
| 5 | Total rooms (not crashed I believe) < 3 | 1 |


Also thats not the final score, the final score is then given by the formula: 2 - random(0,5) + total_score. As for the rooms, there is either a finite time spent routing to rooms, or some number of rooms is allocated and there does seem to be a random factor that may influence the rooms visited, but they seem to be evaluated in order and maybe when that time runs out, they leave.

**Comment by lewri** [comment]
Corrrect me if I'm wrong, but it looks like the cash reward increases the higher level of the game you are on.
``
self.cash_reward = math.round(self.world.map.level_number * self.vip_rating) * 10 
``
This in principle seems fine, but it does lead to the reward maxing out more often the higher your level. However, I would've expected pleasing the VIP to get harder the higher the level and more difficult to hit the reward ceiling.

**Comment by mugmuggy** [comment]
Yes thats what I was alluding to and the same was mentioned in 498 as well.

**Comment by lewri** [comment]
I decided to add some debug lines to track what the VIP was thinking while visiting the hospital. 

**Here is a run where I removed my handymen (except 1 to prevent machines exploding).**
```lua
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
I have assessed deaths. My rating is now 60 points
I have assessed cures. My rating is now 80 points
I have assessed queues. My rating is now 86 points
I have assessed toilets. My rating is now 92 points
I have assessed litter. My rating is now 94 points
I have assessed vomits. My rating is now 74 points
I have assessed heating. My rating is now 71 points
I have assessed seating. My rating is now 75 points
I have assessed patient thirst. My rating is now 75 points
I have assessed patient happiness. My rating is now 85.88 points
I have assessed staff happiness. My rating is now 90.88 points
If money were limitless, I award the player $7270
And the scores on the doors are... 90.88points
I rate this hospital 5 out of 5
```

**And here is one with adequate staffage**
```lua
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
Visited a room. My current rating is 50 points
I have assessed deaths. My rating is now 60 points
I have assessed cures. My rating is now 80 points
I have assessed queues. My rating is now 86 points
I have assessed toilets. My rating is now 92 points
I have assessed litter. My rating is now 96 points
I have assessed vomits. My rating is now 104 points
I have assessed heating. My rating is now 101 points
I have assessed seating. My rating is now 105 points
I have assessed patient thirst. My rating is now 105 points
I have assessed patient happiness. My rating is now 116.56 points
I have assessed staff happiness. My rating is now 126.56 points
If money were limitless, I award the player $10120
And the scores on the doors are... 126.56points
I rate this hospital 5 out of 5
```


The things that strike me here are:
* "vip_rating" never changes after every room visit
* The uncapped monetary reward is ludicrous
* Even a hospital in some disarray can get the highest rating

I hope this is helpful to you @mugmuggy

**Comment by mugmuggy** [comment]
I think that the room eval, might have assumed an indexed table, thus expecting the machine to be found first, if one exists, and then also consider the extinguisher/plant afterwards just once. That would apply a score for non-machine rooms.

What I demonstrated on the analysis above from the original is that there are fairly simple rules that could be used to evaluate with a small lookup table of the result, which should provide for variabiity.

**Comment by lewri** [comment]
For the plant + fire extinguisher problem I believe I've fixed that part. There were breaks in the code that caused the for loop to then disregard any other objects of that room. I do believe as mugmuggy said, the reason the strength object was always picked up is because it was the first object.

While dealing with that however, it opens the room rating factor to abuse (i.e. I could place 10 fire extinguishers in the room and rack up points). To combat this, I introduced two variables: room_extinguisher and room_plant. When the for loop now cycles through objects it will only award the player once for a fire extinguisher, and up to 3 times for plants (as plants can make rating go up and down).

**Code change** (pasted with my debug lines, so excuse that).
```lua
function Vip:evaluateRoom()
    --debug adds self.room_extinguisher and self.room_plant
    local room_extinguisher = 0
    local room_plant = 0
  -- Another room visited.
    --debug
    print("Visited a room. My current rating is " .. self.vip_rating .. " points")
    --debug-end
  self.num_visited_rooms = self.num_visited_rooms + 1
  local room = self.next_room
  -- if the player is about to kill a live patient for research, lower their rating dramatically
  if room.room_info.id == "research" then
    if room:getPatient() then
      self.vip_rating = self.vip_rating - 80
    end
  end

  if room.staff_member then
        print("Evaluating room.staff_member")
    if room.staff_member.profile.skill > 0.9 then
      self.room_eval = self.room_eval + 3
    end
    if room.staff_member.attributes["fatigue"] then
      if room.staff_member.attributes["fatigue"] < 0.4 then
        self.room_eval = self.room_eval + 2
      end
    end
  end

  -- evaluate the room we're currently looking at
  for object, _ in pairs(room.objects) do
    if object.object_type.id == "extinguisher" then
        --check if 1 extinguisher already found in room
        if room_extinguisher == 0 then
            self.room_eval = self.room_eval + 1
            print("Found fire extinguisher")
            room_extinguisher = 1
        end
      --break
    elseif object.object_type.id == "plant" then
            --check if more than 3 plants assessed
            if room_plant < 3 then
                if object.days_left >= 10 then
                    self.room_eval = self.room_eval + 1
                elseif object.days_left <= 3 then
                    self.room_eval = self.room_eval - 1
                end
                print("Found plant")
                --pevent abuse of rating by placing lots of plants
                room_plant = room_plant + 1
            else
                print("Maximum plants assessed in this room")
            end
      --break
    end

    if object.strength then
            print("Found object with strength attr")
      if object.strength > (object.object_type.default_strength / 2) then
        self.room_eval = self.room_eval + 1
      else
        self.room_eval = self.room_eval - 3
      end
    end
  end
    print("After assessing this room, my evaluation of rooms is currently " .. self.room_eval .. " points")
end
```

**Output**
```Lua
Visited a room. My current rating is 0 points
Found plant
Found fire extinguisher
Found object with strength attr
After assessing this room, my evaluation of rooms is currently 32 points
Visited a room. My current rating is 0 points
Evaluating room.staff_member
Found plant
Found plant
Found plant
Maximum plants assessed in this room
Maximum plants assessed in this room
After assessing this room, my evaluation of rooms is currently 34 points
```

What I've come up with probably isn't elegant (or the most efficient) but it does work.

**Comment by TheCycoONE** [comment]
So mugmuggy are you saying the rooms visited don't actually factor into the score in the original? That would be simpler. The other thing we could do with our room visits is take an average room condition factor instead of accumulating them so they don't result in an unbounded range.

**Comment by TheCycoONE** [comment]
E.g. sum(avg plant score + extinguisher bonus + machine state if applicable) / total rooms - then other factors.

**Comment by mugmuggy** [comment]
Yeah, the rooms/extinguishers don't appear to come into it at all. Even though the manual says it does.  Except for actually visiting the rooms they don't appear to contribute to the score and nothing appears to came out of the VIP data either.

The final_score = 2 - random(0,5) + score I assume provides the chance of variability and for different critique from different VIPs.

The code sort of reads as though we are trying to give a percentage score and has a few more factors, but the weighting of them probably needs to be thinned out a bit. The initialisation of vip_rating should be a random number in a range for example.

In TH the table of awards is -5 to 14 potential values, thus 20 different values, and 7 of them are positive results. If that was a linear scale, each value would represent a step of 5% and only the top 35% provide an award and with about +/- 10% variability.

In TH as the VIP is there only a limited time, some of the ratings we have in Corsix might not apply very well either. Like the +20 if you have a visitor and no deaths, if you have a large custom hospital, with many rooms, and it takes the vip years to navigate all around, probably more likely to get deaths.

The patient average thirst check is 'around the wrong way' - penalises well hydrated and rewards thirsty, which could be deliberate in the revenue raising interpretation. Patients only become thirsty at 0.7.

So there are some things to think about.

**Comment by lewri** [comment]
So I decided to test myself and rebuilt the rating system as according to the original. I also managed to order the appraisal strings in their original order. Along the way I also found two bugs in hospital.lua that may need addressing separately.

Personally, I think it's just as lenient in some cases.  I can get the 2000 reward even with only 1 doctor employed. I can also get the 800 reward if I have 1 handyman. The only thing I haven't tried to make work is a limited number of rooms visited, so VIP currently visits all rooms.

Considering that, I think the rating system should become a hybrid of the current and original. I like that the current assesses more about your patients and factors it into the rating.

The parts I think would be good to be combined into the orginal rating are:
* Patient happiness
* Room evaluations (drop skill and fatigue test in favour of original method)
* Queue averages
* Death ratio (assume this only counts deaths during the VIP visit)
* Seating
* Heating (but instead get average warmth of patients rather than the VIP)

**Comment by mugmuggy** [comment]
Will try to keep the discussion on the issue and the PR for review.

So the two 'flags' are is it a room and the must visit. Corsix we know its a room so we don't need that check.

There is nothing to indicate that the visit must happen at all right now. Veto the random is as its checked first.

A rough pseudo for the vip room action
```lua
while (true)
  next_room = next(world.rooms, vip.last_room)
  if not next_room then break
  if next_room.hospital = local_player_hospital then
    if next_room.room_info.must_visit or math.random(0,1) == 0 then
      visit next_room
      break
```
We also don't have to replicate the old behaviour 100%. I assume the thinking was VIPs visit wards to mingle, observe surgeries cause they are interesting and likewise a room to see aliens.

The other thing that I noticed is that Corsix uses 2 to 3 days to evaluate, vip.waiting is set to 3 and TH is 50 ticks. So its taking twice as long to evaluate the rooms and on average its nearly twice as many rooms checked also. The worse case for TH is that every room is still visited.

**Comment by lewri** [comment]
Good to keep discussion here I agree.
I'll work on that pseudocode to make it actual code. I would like to keep the check that the VIP must always visit the first room though, for the sake of handling any obscurities (e.g. no must_visit rooms; all rolls come back 0).

**Comment by lewri** [comment]
@mugmuggy I looked into playing about with the vip.waiting values. The value might shorten the time at each room but it is a bit random. Depending on the day cycle, the VIP could be at the room for 8 seconds when vip.waiting = 3.

Setting vip.waiting to 2 doesn't seem to do much.
The most pronounced efffect is vip.waiting = 1. But this sometimes makes the VIP leave as soon as they reach the door. I don't think day cycles (which I believe CorsixTH's ticks are based off) is working well to limit the time at each door consistently.

Do you have any other ideas on how to fix the time at each door?

**Comment by TheCycoONE** [comment]
Ticks in CorsixTH are smaller than days. 50 per day iirc.

**Comment by mugmuggy** [comment]
The IdleAction in action_vip_go_to_next_room_start can get a setCount and change the loop callback to an after use one. But to have it make sense you also need to then select the next room to start the next actions from evaluateRoom or that callback rather than tickDay.

**Comment by lewri** [comment]
I'm not entirely sure how to modify that one. Would that be something you would be able to look at?

**Comment by mugmuggy** [comment]
I've tested your branch as currently pushed with the additional change for 50 ticks for evaluation against a very large hospital I test against from one of these issues. It has 138 rooms.

The save already has a VIP visiting, on the 12th room. 17th Aug 2007

With the changes, VIP is leaving on the 18th April 2009 after visiting 71 total rooms. So a little less than half the remaining rooms.

With 0.64-rc1 thus checking every room (not sure it skipped any when some crashed), the VIP starts leaving on the 1st Sept 2010. A long 3 years.

I snapped some progress points on the current rc. It gets there faster as areas are generally built out close by so no wasting time walking between rooms, but as the hospital is infilled it can slow down.
18th Oct 2008 71 rooms
18th April 2009 89 rooms
18th April 2010 125 rooms

I also ran on the save from this issue, and the VIP is in the hospital about 1 month less.

The change I made was put the room determinination into a method getNextRoom.
Then in Vip:tickDay
do
+      self:getNextRoom()
+      self.waiting = nil

End of Vip:evaluateRoom
+  self:getNextRoom()

Added more to the afterLoad to update current/queued actions
+    for i, action in ipairs(self.action_queue) do
+      if action.name == 'idle' and action.loop_callback and (self.waiting > 1 or i > 1) then
+        action:setCount(50):setAfterUse(action.loop_callback)
+        action.loop_callback = nil
+        self.waiting = nil
+        if i == 1 then
+          self:queueAction(action, 1)
+          self:finishAction()
+        end
+      end
+    end

Then in vip_go_to_next_room
-      humanoid.waiting = 3
+      humanoid.waiting = nil
and 
-    humanoid:queueAction(IdleAction():setLoopCallback(evaluate):setDirection(dir))
+    humanoid:queueAction(IdleAction():setCount(50):setAfterUse(evaluate):setDirection(dir))

**Comment by lewri** [comment]
If even with the proposed code it's taking over 1.5 years to complete a hospital of that size; I would suggest we put in some kind of maximum for the VIP.

We could either use a max_rooms route. Or we could use a max_duration.
Not sure what's the best route?

**Comment by TheCycoONE** [comment]
max rooms is probably sensible.

**Comment by mugmuggy** [comment]
That hospital is about 1.5 times the size of L12.

In a hospital in the original on L12 with only 40 large rooms and not fully built out to all parcels, a VIP still took about 10 more months, even though some rooms had already been visited (roughly a third to half way through the room index). So even though it seems unreasonable its about in line with what the original does considering the size.

**Comment by lewri** [comment]
Thanks for your help @mugmuggy 
The code works if a VIP is in the building, but not if we get a new VIP. Game crashes when they reach the reception desk. I've uploaded the changes to the files on the branch for you:

```lua
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\entities\humanoids\vip.lua:146: attempt to index a nil value (local 'self')
stack traceback:
        Lua\entities\humanoids\vip.lua:146: in field 'getNextRoom'
        Lua\entities\humanoids\vip.lua:103: in method 'tickDay'
        Lua\world.lua:1082: in method 'onEndDay'
        Lua\world.lua:1006: in method 'onTick'
        Lua\app.lua:1111: in function <Lua\app.lua:1108>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>

Error in timer handler:
Lua\entities\humanoids\vip.lua:146: attempt to index a nil value (local 'self')
stack traceback:
        Lua\entities\humanoids\vip.lua:146: in field 'getNextRoom'
        Lua\entities\humanoids\vip.lua:103: in method 'tickDay'
        Lua\world.lua:1082: in method 'onEndDay'
        Lua\world.lua:1006: in method 'onTick'
        Lua\app.lua:1111: in function <Lua\app.lua:1108>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>
Warning: No event handler for timer
```

**Comment by mugmuggy** [comment]
tickDay has typo on the call to getNextRoom()

**Comment by lewri** [comment]
I noticed we have a small... but potential hole in the code to check against death ratio and cure ratio. Namely this line:
```lua
local visitors_diff = self.hospital.num_visitors - self.enter_visitors
```

The hole is that if in a very unlikely event we get no new visitors -- but have people already in the hospital -- but patients are killed, they will get the no penalty.

**Comment by TheCycoONE** [comment]
You have `#hospital.patients`

**Comment by lewri** [comment]
Ah thanks. I'll give it a go!

**Comment by lewri** [comment]
While also working at the issue above. I've finished doing some research into what matters to patients across hospitals. There's a bias to the NHS only here, but nonetheless it was plentiful enough. Data across 4 different sources. One is a meta-analysis so had more reports I could look into to count. 

http://www.wales.nhs.uk/sites3/documents/420/Final%20Project%20Report%20pdf%20doc%20january%202012%20(2).pdf
https://www.england.nhs.uk/statistics/2019/06/20/overall-patient-experience-scores-2018-adult-inpatient-survey-update/
https://www.emerald.com/insight/content/doi/10.1108/09526869810230858/full/html (restricted paper, can get a copy if needed/interested)
http://www.nhssurveys.org/Filestore/documents/QIFull.pdf

The table below summarises key themes we can loosely base our accessible code from.

Key Theme | Count | Will affect
----------- | ------- | ----------
Access to staff/waiting times | 16 | Queues, staff numbers
Getting the diagnosis right/treatment | 12 | Cures, deaths
Confidence in staff | 12 | Doctor skill, Staff happiness
Cleanliness/Environment | 11 | Litter, vomit, room objects
Facilities | 4 | Rooms
Comfort | 3 | Seating
Hospital image | 1 | N/A likely to be ignored

This should be enough data to start rebalancing vip rating factors to represent more real issues. However, I also recognise that as a game, one of its value's was to more away slightly from realness, so I'll also be considering that.

**Comment by mugmuggy** [comment]
Even though the VIP doesn't check these factors, the AI hospitals when I get around to shifting them over to, do use a rough scale for comfort. I don't know how well they translate to what you'll look at implementing. These are just patients per that object type, ie its made for the AI to spend money.

```lua
local comfortFactors = {
  drinks_machine = {10, 9, 8, 7, 6, 5, 4, 3, 2, 1},
  bench = {5, 4, 4, 3, 3, 2, 2, 2, 1, 1},
  plant = {45, 32, 28, 24, 20, 16, 10, 7, 4, 2, 1},
  extinguisher = {32, 28, 24, 10, 16, 10, 7, 4, 2, 1}
}
```

The current code of countSittingStanding, I find that the state is too transient in nature more often than not. Ie you could have 2 patients one seated, one idle in a queue, and either one gets a drink, then becomes positive or negative.  Thats fine, but then you can have another 50 patients all walking around, that don't contribute to this evaluation who may or may not get seated.

Also you have config options that contribute to it also: TheApp.config.alien_dna_must_stand and then there is SeekRoom action where they are basically idle but they can't sit either (waiting for a room to be built situation) and they don't contribute to the standing count, they start a vomit action or a pee whilst standing in the queue, not counted.

**Comment by lewri** [comment]
For the countSittingStanding I think it isn't a big problem. If a patient wants a drink or needs to use the loo then they're technically not simply waiting around (i.e. they needed to get up to do that action). In fact, I believe the latter one they get removed from the queue. 

The alien DNA isn't something I've thought of. Mainly because I've never had it happen in my games. So in effect, we should make sure to ignore alien patients from our counts.

I could see a benefit of counting patients seeking seating. However, the problem that annoys me more with this is sometimes when a patient enters a room, all other people in the queue involuntarily get up and move seats. So I imagine that also removed them from our count. In reality, they should just stay where they are. But that's another issue.

**Comment by lewri** [comment]
Question for you @mugmuggy as I'm testing out that 3 year VIP save... is the variable: self.world.free_build_mode meant to be true? According to the game it is false... But it's never a map I've seen before. (Maybe I mis-understand what free_build_mode is)...

I'm debating about having a special case for free build/custom maps that limit the rooms the VIP visit, to keep their visit under 1 year.

Apart from that the save is horribly broken... doctors keep reserving doors and not leaving... patients get stuck in treatment... But that's another issue.

**Comment by mugmuggy** [comment]
Free build is to play without money or winning and losing conditions.
Custom maps don't have a level_number which is why the cash_reward calculation has that check. It certainly has critieria for a win though.

Yes there are 2 rooms with reserved doors, and the broken psych, but you shouldn't get anymore on trunk than the existing ones. The rooms you can remove dr and rebuild. Psych you can set him ticking again when a patient is in the room, however I think the state isn't the best and the saves might not reload, if you take a save further down the track.

**Comment by lewri** [comment]
I assume the VIP visit is just for a nicety than a real function when in free build mode.
Currently, the VIP doesn't care what state your hospital is in for free build mode.

Maybe we could make free build vary the reputation given at the end... to make things matter a bit more.

**Comment by TheCycoONE** [comment]
Having anything matter is not the point of free build. It's a sandbox mode for creating the perfect hospital without worrying about playing the game.
