### ISSUE TITLE
Game can't be saved if receptioist fired

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1622]
#### Describe the issue
If you try to save the game after firing a receptionist, the game crashes.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Fire a receptionist and immediately save.

#### Save Game
https://www.dropbox.com/s/b42ujhtjqbzvwh2/epidemic.sav?dl=0

#### System Information
**CorsixTH Version:** 0.63 and latest master (not sure what trunk version)

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
...
Unhandled argument to th_getfenv
Unhandled argument to th_getfenv
Unhandled argument to th_getfenv
Unhandled argument to th_getfenv
Unhandled argument to th_getfenv
nil     <no name>
<LocalisedString> Current value:Error while saving game: Lua\persistance.lua:247: Lua functions must be given a unique persistable name in order to be persisted (attempt to persist Lua\humanoid_actions\staff_reception.lua:48)
```

**Comment by TheCycoONE** [comment]
Sounds like there is a callback that is missing it's persistence name. Should be an easy fix for someone.
