### ISSUE TITLE
Improvements on providing source data

### ISSUE THREAD

**Issue by Richard-L** [CorsixTH/CorsixTH#1629]
On first run when prompted for TH's source data, I would suggest:

- To allow "system dialogue" to choose the location, so copy/pasting of paths is possible
- Prompt an error if files haven't been found.
- Make it parse all sub-folders automatically without having to point to the correct one(s).

Many thanks for considering.

**Comment by TheCycoONE** [comment]
Searching all folders is unreasonably expensive. Did you have a more specific idea of what you wanted. e.g. the idea has been floated around to recognize common packages - would that satisfy the requirement?

**Comment by lewri** [comment]
This has (in part) now been addressed by 1687
