### ISSUE TITLE
Staff payrise requests can lapse

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1642]
#### Describe the issue
If your bottom UI is full of faxes etc. the staff rise requests get delayed. As a result a staff member can leave before the request appears. However, instead of the request being cancelled, it appears once there is a space on the bottom (even though the staff member is gone).

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. You'll find there are two staff rise requests in the bottom UI. They are for two staff already left.

3. However, if you continue playing, the two staff currently in the hospital will also do it, because the bottom UI is full.

#### Save Game
https://www.dropbox.com/s/zkfv0pxoqtr3m3c/delayed-staff-rise.sav?dl=0

#### System Information
**CorsixTH Version:** Trunk / 0.64 rc1

**Operating System:** W10

**Theme Hospital Version:** GOG.

**Comment by TheCycoONE** [comment]
Expected behavior is that the fax should be removed when the staff quits.

**Comment by lewri** [comment]
So the reason for this seems to down to the checks we do if a staff member has waited too long. We're checking open windows rather than queued messages in the bottom_panel.

Hopefully the fix is simply pointing the check to the message_queue rather than UIStaffRise windows.

https://github.com/CorsixTH/CorsixTH/blob/617d7dcf9230675e46d05c8a59b17a73a1cd7e73/CorsixTH/Lua/entities/humanoids/staff.lua#L169-L179

**Comment by Alberth289346** [comment]
That looks wrong in several ways :)

**Comment by lewri** [comment]
Actually I think my observation is a little incorrect. The code above is probably used to make sure the relevant screen is closed if we sack the staff. But we then probably need to then do a second check for any remaining messages in the bottom panel.

**Comment by mugmuggy** [comment]
This pause behaviour doesn't match the original, it continues processing in the background but this appears to have been a request in the past that made it through. That loop though probably exists as you can open multiple requests over the top of each other and when it was ticking it would deal with the correct UI dialog.

The 'must pause' nature of the the dialog is easily overwritten leading to the tick functionality being required. The scenario here I guess is that you could open the dialog, wait til after end of month, then grant them. As Corsix allows you to open multiple dialogs there is a much bigger benefit here over TH.

Likewise there are a few other things that are different to TH.

Time for strike message disappear/quit to occur is less, full 30 days in TH, this affects game balance.

One feature I like about TH also is that if there are multiple strike requests before the first one is opened, it doesn't spawn another, but keeps the strike request alert from being removed, up until the last one is opened.


Other issues I have quickly come across is if the hospital policy is set to grant wage increase, the UI still bugs you with a strike alert I guess to indicate that staff are unhappy. If you open this alert before its finished ticking and resume the game in the background, it may grant that increase automatically and you have no abort option, stuck either giving them another raise or firing them. The auto grant should also close that window.

**Comment by lewri** [comment]
I think I prefer the way of pausing on a UIStaffRise. But at the moment yes you can hack out of pause.

Should we prevent people hacking out of pause? That is the question. But likely for a separate issue.
