### ISSUE TITLE
Staff animation glitch when resting on sofa

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1643]
Observed graphical issue. The animations for the doctor getting up/sitting down (and maybe other staff) appear to be glitchy when resting on a sofa.

Should be reproducable on any game where staff are resting. Happening on 0.64 rc1 and trunk. I imagine we didn't apply any graphics changes in rc2...

**Comment by TheCycoONE** [comment]
Can you include the screenshot. For these issues a screen shot is the best way to communicate.

**Comment by lewri** [comment]
I believe this one might require a recording. But I'll do my best to get on it

**Comment by lewri** [comment]
Here you go

https://www.dropbox.com/s/1p24vm6g1ds7gea/0pyqa-j01g0.webm?dl=0

**Comment by TheCycoONE** [comment]
Thanks! Does it always happen when another staff walks in front of the sofa like that? If so I believe it's the same cause as https://github.com/CorsixTH/CorsixTH/issues/1255 - the patch in that ticket would fix it - but cause lots of other glitches. Just speculation as I haven't looked closely at these again yet.

**Comment by lewri** [comment]
Nope. This effect can happen even if they're the online person in the room.

It also open happens in that orientation.

**Comment by mugmuggy** [comment]
This looks to be a frame desync complicated by using the object with split animations.

The staff member in this case is a junior doctor. Entity.tick has these junior staff tick at half the rate (self.slow_animation). But also seems to call Entity.tick from Staff.tick and this operates on only one animation not two. Unlike the Object.tick which handles split animations. and that allows them to desync.

I haven't yet worked out a nice simple resolution

**Comment by lewri** [comment]
> This looks to be a frame desync complicated by using the object with split animations.
> 
> The staff member in this case is a junior doctor. Entity.tick has these junior staff tick at half the rate (self.slow_animation). But also seems to call Entity.tick from Staff.tick and this operates on only one animation not two. Unlike the Object.tick which handles split animations. and that allows them to desync.
> 
> I haven't yet worked out a nice simple resolution

Actually the glitch was happening on a consultant, if that changes things?

**Comment by lewri** [comment]
Merged into meta
