### ISSUE TITLE
Chance of stuck doctors

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1645]
#### Describe the issue
With the changes around the expected counts in 0.64rc, if you edit and cancel a room, that is treating patients, patients and staff in the room go through a leave and requeue process.

The logic may result in emergency patients arriving at the door to requeue before the staff member has popped from the queue. Thus inserting themselves before the staff member. tryAdvanceQueue will then prevent them from leaving as queue:front() is not able to enter the room.

This has quirked me in the past when looking at the code, it used to just work, but it would appear that Queue:push assumes the humanoids in the queue are already in the correct position with the humanoid.is_emergency check just looking for other emergency patients to queue behind.

I added a call to Queue:rerouteAllPatients in the Room:deactivate method that would appear to result in this and thus those already queued are resent ot the room upon the cancel. The old behaviour of reroute expected doesn't occur in TH, indeed they keep arriving whilst the edit room dialog is shown.

With 0.63 if you edit and cancel the edit for a room and have another of the same type the leaving patient will seek out that room as they cannot now find the one they left.

I could probably add another mode to 'rerouteAllPatients' or another method for just the epxected case to restore the functionality to the same as 0.63.

#### Steps to Reproduce
1. Load save game from #1616

2. Before unpausing, edit psych and cancel the edit

#### Save Game
*It is often useful for us if you have a save game from shortly before the
issue occurs that can be used to recreate the problem. Sometimes a save that
shows the issue happening may be useful as well. As GitHub currently only
supports uploading of images, you will have to upload your your savegames to
an another source such as [Google Drive](https://drive.google.com),
[Dropbox](https://dropbox.com), or
[SkyDrive/OneDrive](https://onedrive.live.com). Add the link to the file to
your issue and make the file(s) public, so we can access your gamelog or
savegame. The most important thing is to not remove these files after you
uploaded them!*

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by TheCycoONE** [comment]
@mugmuggy is this going to be worse than the bugs in 0.63, i.e. should we hold the release for it?

**Comment by mugmuggy** [comment]
Not really worse as it only happens on edits, and should only get the queue order out of shape if they are emergency patients arriving, you have one room of the type (they'll find the other room first). Once they get tired, they can leave the room also, at least that seems possible in this save.

The main options for a minimal impact fix, is to remove the code from Room:deactivate. Or to align with 0.63 change the rerouteAllPatients to accept say a 2nd optional parameter indicating the 'mode' and only check for that around the two loops there and use the 'expected' one from deactivate:
```lua
if not mode or mode == 'queued' then
```
and
```lua
if not mode or mode == 'expected' then
```
Or just as easily factor it into its own method and call that instead, which would be basically 0.63 behaviour still.

A more proper fix I believe would entail more logic in the room:deactivate side, to not redirect them if its the only room of that type so those on the way should remain on the way. But this probably has issues around seekroom.

Happy to get one of the options in before 0.64 drops, obviously release also needs to progress.

**Comment by TheCycoONE** [comment]
Thanks @mugmuggy The releases are already tagged and built. It doesn't sound like this is a blocker, so I'm going to go ahead with it as is.

**Comment by lewri** [comment]
@mugmuggy do you want this tagged for 0.65?
