### ISSUE TITLE
Cheats Dialog/Menu can slide off screen

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1647]
#### Describe the issue
If you move the screen with the cheats menu open, it can occasionally clip off the screen when it is closed and re-opened. Happens both in windowed and full-screen mode.

#### Steps to Reproduce
1. Open cheat menu. Scroll up the screen a bit

2. Close cheat menu, then re-open it.

3. If fails, repeat 1 + 2

#### Expected Behavior
Menu should retain its previous location when closed and reopened. Or at least re-centered to its default position.

#### System Information
**CorsixTH Version:** Trunk 139 (+ 0.64rc1)

**Operating System:** W10

**Theme Hospital Version:** GOG

### Additional Info
![image](https://user-images.githubusercontent.com/20030128/84672464-7d0c6500-af20-11ea-94d1-37e16d3dbedc.png)

This might also happen with the debug patient dialog, but haven't tested it.

**Comment by TheCycoONE** [comment]
Probably safest to recenter every time - the number of times I've gotten windows stuck off the edge of the screen in desktop operating systems...

**Comment by TheCycoONE** [comment]
I didn't produce, but I'm not sure I'm doing the same thing. Are you scrolling around in the game, or moving/resizing the game window? How are you opening the cheat menu?

**Comment by lewri** [comment]
Just opening it. Then moving North a bit. Then closing it and reopening it. It's a bit intermittent to reproduce. Sometimes it'll only move a little. Then sometimes a lot.

**Comment by TheCycoONE** [comment]
You open from menu -> debug -> cheats?

**Comment by lewri** [comment]
Yep

**Comment by mugmuggy** [comment]
I was able to get it to do this a few times also.
