### ISSUE TITLE
"Handyman to repair x" announcements rarely trigger

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1649]
#### Describe the issue
While testing a lot of earthquakes I noticed that the receptionist wasn't announcing machines that were in need of urgent repair (i.e. Handyman to repair x). It also appeared in some other saves that the task priority wasn't being bumped in the calls dispatcher (some handymen would still action low priority tasks over heightened ones).

This also doesn't seem specific to earthquakes, if regular machine use takes it over the threshold it still fails to announce.

There's only been one save I managed to get the announcements on. And I think that was from 0.60 or something. So maybe something has broke along the way since then?

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Make some earthquakes happen, may need to reduce handymen numbers.

3. Watch machines with smoke not triggering any announcements.

#### Save Game
https://www.dropbox.com/s/5akhnc9azhbaxyf/vipfor138.sav?dl=0

#### Expected Behavior
Receptionist should be announcing machines in disrepair.

#### System Information
**CorsixTH Version:** 0.64

**Operating System:** W10

**Theme Hospital Version:** GOG

**Comment by mugmuggy** [comment]
Only calls in particular scenarios, 2nd argument to callForRepair controls it.
https://github.com/CorsixTH/CorsixTH/blob/8741d41eb5de865c633e023bcb512b779c131c5e/CorsixTH/Lua/entities/machine.lua#L125-L132
When remainingUsages < 4 and implied > 0 and no task has already been raised. There was some change around handyman calls, but I only really remember dropping calls correctly with that. Was removing having an assigned task assigned to two handymen.

**Comment by lewri** [comment]
Funny, as that's the part of the code I'm looking at now. Trouble is I think repairs are always getting called on low priority (threshold<6) so they're not triggering a verbal warning when it goes under 4.

The only case this would happen then seems to be if strength is 4 or less. Which is a bit odd.  Unless that's how it worked in the original. But in the original I at least remember the klaxon sound happening more often.

**Comment by mugmuggy** [comment]
Yes, < 6 triggers the call and yes where I see it is on an old save I loaded up where an xray has strength of 4 after being repaired (earlier version of Corsix and consistent with 0.64).

The other differences I believe with that callForRepair is that if it does make the announcement it prevents use of the machine, thus the room, until its repaired, but if < 6 it doesn't do that.

I don't normally play with announcements and I generally turn it off when testing, find it too annoying so I don't observe this.

**Comment by lewri** [comment]
Wouldn't that present a new problem where a low priority becomes high priority, the room never gets locked? As a result the machine can keep being used until explosion.

But if the strength <=4 then the room will always get locked, thus preventing explosion.
In my opinion we should be locking the room if the threshold falls below 4 regardless of handyman state. However, it would mean then that only earthquakes can make machines explode.

**Comment by mugmuggy** [comment]
Yep save in #1644 demonstrates this, as there is use between the warning and quake where rooms blow up. I can't recall what it does regarding locking the room, but I assume its when we get to 3 smoke? Original is about after 5% of strength remaining when all 3 smoke animations are added. It also allocates smoke randomly from 10, and 15% strength remaining. There is probably something around.

I assume with the chanage in 0.63? you could edit the room, removing the task, and put the machine back and it will be in the same state so could get the announcement on that too.

**Comment by lewri** [comment]
I believe there were some changes to preserve machine states when editing a room yes. The room gets locked if threshold is <4 and a handyman call hasn't already been made. If a handyman call is already made, machine does not lock and people can still use it.

The smoke is calculated as this for threshold:
<4 = 1 smoke
<3 = 2 smoke
<2 = 3 smoke

I wonder if there could be a way just to trigger an announcement and not lock the room where the machine health is critical and handyman is already on the way. Otherwise the player doesn't really get any audible warning that a machine needs attention.

**Comment by lewri** [comment]
Leave this with me. I might be able to come up with something.

**Comment by lewri** [comment]
I can make this work a little haphazardly by editing modifyHandyManTaskPriority; but it also now triggers a bit too much for my liking. machwarn.wav isn't queued in any way to play for multiple machines so they all play at once. And if a lot of machines suddenly become critical the receptionist can become so busy announcing that some machines get repaired before they are even announced.

```lua
function Hospital:modifyHandymanTaskPriority(taskIndex, newPriority, taskType, object)
  if taskIndex ~= -1 then
    local subTable = self:findHandymanTaskSubtable(taskType)
    -- make an announcement if repair priority was upgraded
    if subTable[taskIndex].priority == 1 and taskType == "repairing" then
      local room = object:getRoom()
      local sound = room.room_info.handyman_call_sound
      if sound then
        self.world.ui:playAnnouncement(sound, AnnouncementPriority.High)
        self.world.ui:playSound("machwarn.wav")
      end
    end
    subTable[taskIndex].priority = newPriority
  end
end
```

**Comment by lewri** [comment]
I hope to pick this up once the other PR in this file gets signed off.
To prevent an amass of machwarn.wav sounds triggering all at once, I may plan to cap the sound trigger to just once while an earthquake is happening (the main phase).

**Comment by TheCycoONE** [comment]
What if you use the regular announcement queue?

**Comment by lewri** [comment]
For the machwarn.wav? I could certainly have a go.

**Comment by lewri** [comment]
The drawback of moving a sound to the announcement queue is people with announcements off will never hear anything about a breaking down machine. But I still think it should be queued inside the announcer regardless.
Maybe a flag that says "must_play" should be put into the announcer to disregard user setting (so in other words, machwarn.wav and cheat.wav )

**Comment by TheCycoONE** [comment]
I said it somewhere else, in my opinion the announcement shouldn't play when the announcer is off. That's the point of the setting.

The advisor could potentially "say" it instead. Or the player could just keep enough handymen, and when they see the warning shake click through all machines.

**Comment by lewri** [comment]
I don't want to spam the adviser. So maybe I will just drop it and see if there's any kickback.
