### ISSUE TITLE
Windows XP support?

### ISSUE THREAD

**Issue by ThatTonybo** [CorsixTH/CorsixTH#1650]
#### Describe the issue
Doesn't look like CorsixTH has any support for an older copy of Windows like XP? I play the game with it's original CD on my XP laptop and wanted to jump onboard CorsixTH but I get an error mentioning `CorsixTH.exe is not a valid Win32 application`.

#### Steps to Reproduce
1. Install and try load CorsixTH on a Windows XP install

#### Save Game
N/A

#### Expected Behavior
It'd launch fine and ask for the game files, so on...

#### System Information
**CorsixTH Version:** 0.64
**Operating System:** Windows XP Professional, Service Pack 3

**Theme Hospital Version:** Original CD

#### Gamelog.txt
```
N/A - No file exists in that directory
```

### Additional Info
N/A

**Comment by mugmuggy** [comment]
Its build it yourself since 0.50 https://github.com/CorsixTH/CorsixTH/releases/tag/v0.50

With the caveat your mileage may vary

**Comment by lewri** [comment]
Just to add on, here is the page in the wiki for compiling CorsixTH
https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile

As time moves on it is only natural to abandon support for older operating systems. But I imagine if you wanted to compile 32-bit versions for users on your own branch you are free to(?) They wouldn't be supported here, however.

**Comment by TheCycoONE** [comment]
To be clear I still build and ship a 32bit version which is automatically installed on 32bit systems by the installer. What I no longer do is build against a Windows XP compatible runtime. The Windows XP target is deprecated in Visual Studio and not receiving support for new language features. I don't believe the source is using any unsupported language features yet, but I make no guarantees. I stopped targeting it years ago.

**Comment by ThatTonybo** [comment]
So, I could compile my own version or go back to find an older version of the installer which works?

**Comment by TheCycoONE** [comment]
Yes. Any version before 0.50 or build your own.
