### ISSUE TITLE
Reinstate the CorsixTH forum

### ISSUE THREAD

**Issue by 12people** [CorsixTH/CorsixTH#1655]
#### Describe the issue
The official forum – http://forums.corsixth.com/ – no longer runs.

That's a shame, because it included a lot of original artwork proposed as replacements for game artwork (including the amazing cut scenes mentioned in #1654), as well as conversations that might still be potentially useful.

#### Steps to Reproduce
1. Visit http://forums.corsixth.com/

#### Expected Behavior
http://forums.corsixth.com/ should display a forum

**Comment by 12people** [comment]
Also, the README points translators to the forum. There's no other place where translators can go if they want to get involved.

**Comment by TheCycoONE** [comment]
It is a shame - there was an announcement on the home page. Unfortunately I don't have the access needed to maintain that server; and @corsix has not responded to my emails.

The readme should be updated - we encourage translators to open PRs or create an issue and paste their updates in it here.

**Comment by TheCycoONE** [comment]
In the mean time there is a new subreddit at https://reddit.com/r/corsixTH as well as our Facebook page at https://facebook.com/corsixth

**Comment by 12people** [comment]
Thanks for the links. I don't have a FB account (nor do I ever plan to), but Reddit theoretically works for me. However, it doesn't support the structured conversations that the old forum did (there's no concept of categories, outside of, perhaps, flairs) and threads get lost easily.

Have you considered applying for the [freely hosted Discourse plan for open-source projects](https://blog.discourse.org/2018/11/free-hosting-for-open-source-v2/)? CorsixTH seems to meet the critera to apply. It doesn't solve the problem of bringing back old posts (unless there's an importer), but at least it would create a new place to have the discussions that there used to be.

**Comment by lewri** [comment]
I'm hoping at the least we can get some of the resources off the forum, which if there's successful contact I'll try and help with.

If there is significant demand still to have the forum (from the wayback archive it seemed to of petered off a lot over the past year) then I personally might look into something to help.

**Comment by TheCycoONE** [comment]
I believe I have access to all of the files that were on the forum. Unfortunately the names and file extensions have been lost.

**Comment by TheCycoONE** [comment]
I downloaded the files and wrote a quick script to assign file extensions to the types of ones I could identify, which is most of them.
One unfortunate thing is not being able to associate level files with the maps they go with.

**Comment by TheCycoONE** [comment]
For those following along at home.

Step 1 - rename the obvious:
```
#!/bin/zsh

setopt RE_MATCH_PCRE

for i in *
do
        if [[ "$i" =~ "\." ]]
        then
                continue
        fi
        type=`file -b $i`
        case "$type" in
                Zip*)
                        mv $i "$i.zip"
                        ;;
                JPEG*)
                        mv $i "$i.jpg"
                        ;;
                PNG*)
                        mv $i "$i.png"
                        ;;
                GIF*)
                        mv $i "$i.gif"
                        ;;
                RAR*)
                        mv $i "$i.rar"
                        ;;
                PDF*)
                        mv $i "$i.pdf"
                        ;;
                RIFF*)
                        mv $i "$i.wav"
                        ;;
                *)
                        echo "$i - unknown ($type)"
                        ;;
        esac
done
```

**Comment by TheCycoONE** [comment]
Step 2 - translation files:
```
#/bin/zsh
IFS=$'\n'
for r in `rg 'Language\('`
do
        lang=`echo $r | cut -d',' -f3 | tr -d ' \"'`
        file=`echo $r | cut -d':' -f1`
        mv $file "$file.translation.$lang.lua"
done
```

A rather unconventional name, but now they're clearly identified and still unique.

**Comment by TheCycoONE** [comment]
Next file I checked was a diff file. File actually pointed that out, so I added:
```
unified diff output*)
   mv $i "$i.diff"
   ;;
```
to the first script.

**Comment by lewri** [comment]
Do you think you'd have enough access to pull out the whole forum db?

**Comment by 12people** [comment]
@TheCycoONE Should I make a request with Discourse to get a freely-hosted forum?
If not and there isn't going to be a forum in the near future, it should at least be removed from the README.

**Comment by TheCycoONE** [comment]
I've removed the forum references from the README, thanks for the reminder.

I hope to move the old forum files to a github repository, though I've been side tracked with other issues. If someone wants to help sort through the binaries and figure out which maps and levels go together and what names they should have, drop me a message and I will send over the files.

**Comment by TheCycoONE** [comment]
As for Discourse - what do you need from us to set that up? I don't feel like I have any monopoly on establishing forums of communication on CorsixTH :smile:

**Comment by 12people** [comment]
:D nothing, I suppose
would a forum make sense to you or would you say that perhaps the ticketing system here is enough (and perhaps it might even be better to keep all feature requests and proposals in one place — here on GitHub)?

**Comment by Alberth289346** [comment]
Forum and ticket system are different things for different purposes for different audiences.

A forum is for more for discussing arbitrary things such as desired features, giving people help and suggestions how to play the game, helping with specific problems on ones system, exchange maps and levels (and help with that), etc.
A ticket system is for highly focussed mostly technical discussions about a feature or fix, directly aiming to make changes in the source code.

A feature request or proposal is of no use in a ticket system, unless its author is willing to spend the time and effort to implement it.

**Comment by TheCycoONE** [comment]
Disagreeing with Albert here, we now have an enhancement button in the issues; I would prefer serious proposals go there where they can be triaged by the development team.

**Comment by 12people** [comment]
Alright, makes sense to me.
Also, since there's an [official Discord](https://discord.gg/Mxeztvh) now, a forum would just make it more confusing as to where to write.

**Comment by lewri** [comment]
Yes I'm running the discord... though time will tell if it helps pick up interest. Need to spread it to more places than just the Github and Reddit....
