### ISSUE TITLE
Serious Radiation Graphics

### ISSUE THREAD

**Issue by MadeInDutch** [CorsixTH/CorsixTH#1659]
#### Describe the issue
In the original Theme Hospital, patients with serious radiation had a green filter on them. For some reason, patients with Serious Radiation in CorsixTH aren't distinguishable from other patients.
#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait until a patient with Serious Radiation comes in.

3.

#### Save Game
https://drive.google.com/file/d/1KG4ZDYoZavyKyDXmbJShr_XMi09_KH__/view?usp=sharing

#### Expected Behavior
I expect the same green filter on Serious Radiation patients as is found in the original game.
#### System Information
**CorsixTH Version:** 0.64rc-2

**Operating System:** Windows 10

**Theme Hospital Version:** CD

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Paste gamelog.txt output here
```

### Additional Info
![image](https://user-images.githubusercontent.com/67276601/85302265-3b903280-b4a9-11ea-8083-b0a4815a5926.png) How it's supposed to look.
![Serious Radiation](https://user-images.githubusercontent.com/67276601/85302631-b6f1e400-b4a9-11ea-8351-b7b48f468ab1.png) How it looks in my game.

**Comment by lewri** [comment]
Odd... I actually can't find any sprites for the serious radiation patients.

Which tells me that the green glow was some kind of overlay ontop of the normal sprite.

**Comment by driverpt** [comment]
I think we need to modify the drawer cpp functions.

Do you have any suggestions on where to start?

I was thinking of implementing this in 2 steps.

- Add a a Color Filter on top of the texture
- Transform that color filter into a tick like animation for glow

**Comment by MadeInDutch** [comment]
Sorry but I have no idea how the code itself works.

24 Eki 2020 Cmt 13:14 tarihinde Luís Duarte <notifications@github.com> şunu
yazdı:

**Comment by Alberth289346** [comment]
`animation_manager` is the class that deals with animations in `th_gfx.ccp,h.

Om top of that there is a lua wrapper (`th_lua_anims.cpp` it seems), that makes the instance accessible to the lua code.

In addition you may want to read the spec of the data-formats in the `CorsixTH/theme-hospital-spec` repo.

For questions/interaction, the IRC channel is useful. Note that in general you will get an answer to a question, but it may take time, people have it typically running in the background, and don't get warned  when a new message arrives. They may also be busy with distractions like work :)

**Comment by Alberth289346** [comment]
@sadger Do you have a list of graphics that may benefit from this extension?

**Comment by sadger** [comment]
I did start looking into this at one point but feel free to investigate some more. We already do some colour transformations with the blueprint overlay which might be good starting point - but be aware this is not an animation. We should make the solution general enough to apply to other visual diseases that need post processing such as Jellyitus being the other one I can think of where we apply some post-processing effect each frame.

For reference I found some youtube videos that show both diseases in progress:
* Serious adiation <https://youtu.be/biD4fPgrZ9Y?t=624>
* Jellyitus: <https://youtu.be/_AsHiNTc4Nk?t=603>

**Comment by lewri** [comment]
@driverpt if you're interested in taking this on I could assign this issue to yourself? And also to @sadger sadger if you wanted to look at it together.

**Comment by driverpt** [comment]
Before saying yes to taking this on. I've been researching the code. I wanted to apply a Green Tint to each of the Animation Frame's RGB.

I was thinking of adding a new Flag to https://github.com/CorsixTH/CorsixTH/blob/ac9ea2ebb7d1a059197c19aec98988d2e923e6af/CorsixTH/Src/th_gfx.h#L40 and Transforming each of the Frames when they are loaded.

Does this make sense ?

**Comment by sadger** [comment]
I did come to a similar conclusion that adding a new flag in an appropriate place and checking it would make sense. This is what we currently do for the blueprint overlay (although it's only a sprite not an animation). So yes, seems ok to me.

**Comment by driverpt** [comment]
I've managed to get Serious radiation partially working. But now i need to find out why the `animation` object is shared with the Entrance Door.
 
![th_radiation](https://user-images.githubusercontent.com/1164534/98984582-4d3aab00-251a-11eb-8862-1ee4af30ff70.gif)

I suspect it has something to do with Lua's Eval Stack

**Comment by lewri** [comment]
Nice work in getting the effect going!

**Comment by driverpt** [comment]
Latest update. Still need to adjust the colors. Do you guys have any suggestions?

![th_radiation_2](https://user-images.githubusercontent.com/1164534/99515021-539aae00-2984-11eb-954c-d1e83ce1a2af.gif)

**Comment by TheCycoONE** [comment]
Just a little lighter, closer to the original pallet. It looks really good.

https://www.youtube.com/watch?v=h8nYGubOkEw (46 minutes in)

**Comment by driverpt** [comment]
@TheCycoONE , perhaps increase the lower light part.

Currently it's using a `sin` formula that increments every 10 Deg for each Tick Number to a Max of 50, Green Channel varies between 155 to 255. `R` and `B` are lowered by half

```
  if (tFn != nullptr) {
    // We want this to vary between 155 -> 205 -> 255.
    // We're using increments of 10 degrees within the Sin function and converting them to rad
    err = SDL_SetTextureColorMod(pTexture, 0x0F, 0xCD + sin(tickNumber*10*PI/180) * 50, 0x0F);
    if (err < 0) {
      throw std::runtime_error(SDL_GetError());
    }
  }
```

**Comment by Alberth289346** [comment]
What about this?
``` cpp
// Amplitude constants.
const int top = 255; // Desired largest amount of green.
const int amplitude = 40; // Amplitude of green variation, green varies [-amplitude, +amplitude] .
const bottom = top - 2 * amplitude; // Lowest amount of green.

// Green computation.
double r = ((tick_number & 31) - 16) * PI / 16.0; // [-PI,+PI) in 32 steps and then wrap around.
double sin_val = (r - r*r*r/(2*3)
                              + r*r*r*r*r/(2*3*4*5)
                              - r*r*r*r*r*r*r/(2*3*4*5*6*7)
                              + r*r*r*r*r*r*r*r*r/(2*3*4*5*6*7*8*9)); // Maclaurin expansion, 4 terms of sin(r).
int green = int(bottom + amplitude * sin_val);
```

**Comment by driverpt** [comment]
You also need to lower the red and the blue.

I'm trying to use HSL based calculation.

**Comment by driverpt** [comment]
> Just a little lighter, closer to the original pallet. It looks really good.
> 
> https://www.youtube.com/watch?v=h8nYGubOkEw (46 minutes in)

@TheCycoONE , can't make it any brighter without having an `SDL_Surface` and manually applying a "Shader".

**Comment by TheCycoONE** [comment]
Ok, leave it. It looks great!

**Comment by driverpt** [comment]
Please bear in mind that for Jellytis we'll definitely need to manipulate the Sprites and apply a "Shader" Transformation.

Can I open an issue regarding this?

**Comment by lewri** [comment]
If you do let me know so I can add it to the 1.0 goal project

**Comment by driverpt** [comment]
@lewri , created #1756
