### ISSUE TITLE
Ward bed shadow gets darker when nurse is adjacent

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1662]
#### Describe the issue
The entire shadow gets darker as the nurse goes past a bed in the ward, which doesn't seem to make much sense. (And considering where our light source comes from for other shadows)

#### Expected Behavior
Persist shadow darkness

#### System Information
**CorsixTH Version:** 0.64

**Operating System:** W10

**Theme Hospital Version:** Demo (but probably in full game too)

### Additional Info
Adjacent nurse
![image](https://user-images.githubusercontent.com/20030128/85898996-41fa1380-b7f5-11ea-9141-6f28de0f8072.png)

Normal:
![image](https://user-images.githubusercontent.com/20030128/85899023-4e7e6c00-b7f5-11ea-8230-91d61eb53e39.png)

I had to confirm I wasn't being dumb, but this behaviour is not present in the original.

**Comment by lewri** [comment]
Potentially related to #1255 as the glitch happens from someone passing by the object (even if they're on the other side of the wall).

**Comment by mugmuggy** [comment]
Yes related to that. Its redrawn over the top. You get this behaivour statically too.
![image](https://user-images.githubusercontent.com/8009292/85921773-efd2f400-b8c1-11ea-8687-61a146041380.png)

I put the bin there just to make it obvious, but you don't need it. Here the plant triggers the redraw as its a multiframe animation, however it doesn't move beyond the single tile. And thus draws the wall twice. Indeed you'll see the darker shadows on many objects, desk in GP is another obvious one.

Replacing it with a bin its as expected
![image](https://user-images.githubusercontent.com/8009292/85921904-f7df6380-b8c2-11ea-8240-414f6ab838a9.png)

**Comment by TheCycoONE** [comment]
Yes, I know exactly how these happen. The back tracking in the renderer should not happen, but it's a hack to fix other glitches.

**Comment by Alberth289346** [comment]
I am wondering if adding a depth to each drawn pixel would work, much like the depth 2d array in OpenGL, but in normal memory and managed by the CPU (assuming we still draw these things there).

Likely we don't need to be that precise, eg start with depth of the tile (which could be the row number relative to the bottom of the screen, for example). That would perhaps eliminate the entire need to do complicated scanline trickery. More advanced would be having several depth layers in a tile, eg floor, back of the tile, center of the tile and front of the tile (allowing staff to pass a tile with two heaters, one at the front and one at the back).

What I did in FreeRCT is to collect all things that need to be drawn in a `set<..>`, sorted  on draw order back to front. Once all was collected, you could simply draw everything (mostly a plain memory copy of the pixels to the image buffer). Sort of the same idea as a depth array except you never track depth at pixel level.

**Comment by lewri** [comment]
Merged into meta

**Comment by ARGAMX** [comment]
unable to reproduce

[1662 Ward bed shadow_0.64.0.sav.zip](https://github.com/user-attachments/files/19848102/1662.Ward.bed.shadow_0.64.0.sav.zip)
