### ISSUE TITLE
Demo game win message has text overlap

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1663]
#### Describe the issue
Seems the win message for the demo is too big for our fax. As a result, it encroaches on the choices section.

#### Expected Behavior
Do not overlap the text

#### System Information
**CorsixTH Version:** 0.64

**Operating System:** W10

**Theme Hospital Version:** Demo

### Additional Info
![image](https://user-images.githubusercontent.com/20030128/85902192-58a36900-b7fb-11ea-95d8-80340e8c10a0.png)

**Comment by TheCycoONE** [comment]
What does this look like in dosbox / original?

**Comment by lewri** [comment]
In original it didn't matter so much because in the original you had the letter video not implemented yet.
