### ISSUE TITLE
[Bug] Patients waiting for operating theatre don't respond when it is built

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1668]
#### Describe the issue
There is a possibility for patients to get stuck waiting for the operating theatre to be built if one doesn't exist.

Edit: They do appear to eventually get unstuck in situation 4b. But 4a seems like a no-go.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. You will need to do some building. Buy the plot on the left, and the plot directly above it. Build a ward in the left plot.

3. Wait for the two female patients to be diagnosed with unexpected swelling. Do not respond to their "awaiting your decision" prompts and instead build the operating theatre.

4. One of two things seem to happen:
    a. Both females don't recognise the operating theatre. You can still access their waiting for decision prompts.
    b. One female recognises the operating theatre after a day and the other seems to get stuck.

5. Additional note: If you tell them to wait in the hospital a while after the operating theatre is built, they just get stuck waiting.

#### Save Game

[operatingnotfound.zip](https://github.com/CorsixTH/CorsixTH/files/4942186/operatingnotfound.zip)

#### Expected Behavior
Patients should respond to the operating theatre being built straight away. But it seems the response is somehow delayed.

#### System Information
**CorsixTH Version:** *0.64*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG*

#### Gamelog.txt

```
Clicked on:
humanoid - class: Standard Female Patient
Warmth: 0.235   Happiness: 0.998   Fatigue: 0.000  Thirst: 0.794  Toilet_Need: 0.491   Health: 0.692
Actions: [seek_room - ward   must_happen]
-----------------------------------
```
Notably one of the stuck patients is seeking ward even though their problem is no operating theatre

### Additional Info
![image](https://user-images.githubusercontent.com/20030128/87859274-c0952d00-c92b-11ea-874b-d575a92d3729.png)

**Comment by mugmuggy** [comment]
This is my bad, when doing the fax updates, I skipped running 
https://github.com/CorsixTH/CorsixTH/blob/0654cd5b59b44ffffa4cc9447264f70b1296f77d/CorsixTH/Lua/humanoid_actions/seek_room.lua#L275-L279

Thus the room_type_needed isn't added to the action, thus the callback on the build of the operating theatre is ineffective. In theory just moving the not req to the next if, should be enough.

They should be seeking ward as thats the next room to visit.

**Comment by lewri** [comment]
It seems possible this can have another knock on affect @mugmuggy 

If you have a patient going to be cured that requires op theatre and you edit the ward while making their way over they get a fax prompt saying they need a ward to treat. But once you dismiss the fax they go straight to the operating theatre.

**Comment by mugmuggy** [comment]
Trying to replicate. Patient has been to the ward and on the way to op theatre or just on the way to ward as part of the process? Edit the ward and it exists after editing (it should remove the fax from bottom panel) or not allowing you to open fax?

I've only gotten the fax for the patient heading to ward. I'll still attempt to replicate again.

**Comment by lewri** [comment]
Can't remember how I did it. I was testing something else as usual and that's what made it happen.

**Comment by mugmuggy** [comment]
I was able to replicate, though I could never get them stuck, they eventually went to Op Theatre.

The UseObjectAction afterUse for the bed will call room:dealtWithPatient, hence they will start a seek for the next treatment room, the Op Theatre. Generally that could occur immediately upon exit when it starts, or it might run first with a meander, then wait, as the SeekRoom may wait depending on when it was interrupted due to the original issue.

The fix appears to be in the same logic, the SeekRoom must distinguish against the initial room routing to ward and op theatre, and just the ward and op theatre.
```lua
if room and (not req or not action.treatment_room) then
```
That change basically means if it isn't the initial seek after leaving the GPs office, do normalish seek behaviour, thus the fax isn't created. Though probably have to check this out more.

**Comment by lewri** [comment]
@mugmuggy Are you able to look at this at all before next release? Or is it able to wait?

**Comment by mugmuggy** [comment]
I've got some changes I am soon to test for this (similiar to the above edits) and the same issue mentioned in #1799 which goes just a little beyond the SeekRoom action in addressing (but a one liner change also). Then I need to verify the faxes are still ok, which they hopefully should be.
