### ISSUE TITLE
[Bug] Opening CorsixTH.app on macOS Catalina results in a Gatekeeper error

### ISSUE THREAD

**Issue by colinjmatt** [CorsixTH/CorsixTH#1676]
#### Describe the issue
If you download the 0.64 .dmg release and try to open it on a machine running macOS Catalina, it'll display the following error

<img width="425" alt="Screenshot 2020-07-27 at 09 08 57" src="https://user-images.githubusercontent.com/13071027/88518716-d8824600-cfe8-11ea-8649-22968490cb2c.png">

This is due to Gatekeeper restrictions in place in Catalina preventing unsigned, non notarised apps from running. In previous version of macOS you could simply override this message and open teh app anyway. It appears that this is no longer the case for anyone keeping their macOS system up to date.

#### Steps to Reproduce
1. Open CorsixTH.app 0.64 downloaded from github

2. Observe message

#### Expected Behavior
The app should open or give an option to override and run the app anyway

#### System Information
**CorsixTH Version:** 0.64

**Operating System:** macOS 10.15.6

**Theme Hospital Version:** CD

#### Gamelog.txt
Game doesn't run so never reaches a logging state

### Additional Info
To workaround this issue, users can manually remove CorsixTH.app from Gatekeeper's quarantine by running
`xattr -d com.apple.quarantine /Applications/CorsixTH.app`

**Comment by colinjmatt** [comment]
The correct solution to this issue would be to sign and notarize the app with an Apple Developer ID. However, that's a $99/£99 a year cost.

**Comment by colinjmatt** [comment]
Building on macOS 10.13.6 with Xcode 9.4.1 returns us to the less frightening message that we expect and most Mac users know how to work around
<img width="422" alt="Screenshot 2020-07-27 at 17 39 18" src="https://user-images.githubusercontent.com/13071027/88567968-23737c00-d030-11ea-9e55-3a3cb54ec79e.png">

This is easily overridden here
<img width="666" alt="Screenshot 2020-07-27 at 17 40 49" src="https://user-images.githubusercontent.com/13071027/88568133-6170a000-d030-11ea-8752-2ee2e92dde73.png">

**Comment by lewri** [comment]
As mentioned earlier we should probably consider how to distribute a MacOS version going forward. From what I saw we have 3 options:
1. Continue to run builds with old XCode as currently done.
2. Purchase a developer license to notarise our builds ($$$)
3. Move CorsixTH MacOS version to homebrew. https://brew.sh/

**Comment by TheCycoONE** [comment]
CorsixTH is already on homebrew, but most users probably prefer DMGs

**Comment by lewri** [comment]
@colinjmatt I expect the behaviour to be the same in Big Sur but can you confirm?

**Comment by colinjmatt** [comment]
Same behaviour on Big Sur 👍

**Comment by lewri** [comment]
@tobylane how has Azure Pipelines testing been going for OS X builds?

**Comment by tobylane** [comment]
Paused for the time being, as GitHub Actions put macOS 11 back into private preview, so I can't use it. A macOS 10.15 workflow can be done, but won't tell us anything new.

**Comment by lewri** [comment]
@colinjmatt / @tobylane Any further action to be taken with this?

We have homebrew, and still have our workaround (for now?).

**Comment by colinjmatt** [comment]
@lewri We can continue the current workaround, at least for the next release.

**Comment by tobylane** [comment]
https://www.macsourceports.com/sourceport/corsixth

MacSourcePorts have signed builds. We could link to this in the release, or ask if we can reupload the file.

**Comment by TheCycoONE** [comment]
I am in favor of reaching out to them, it would be nice to be able to move to C++17. @colinjmatt sound good to you?

**Comment by colinjmatt** [comment]
This sounds like a positive way forwards to me.

**Comment by TheCycoONE** [comment]
```
Hello Tom,

I'm Stephen Baker (aka TheCycoONE) from CorsixTH, one of the
applications you distribute source ports for.

Today we're packaging unsigned releases; we'd like to work with you to
provide your signed builds, either on our GitHub release page, or by
linking to Mac Source Ports. Discussion is publicly taking place in:
https://github.com/CorsixTH/CorsixTH/issues/1676

You mention in your site that you are already working with other open
source projects.

You can respond either to this email or in the github issue. I can add
you to the packagers group for CorsixTH if you'd like.
```

**Comment by lewri** [comment]
This has been resolved now with MacSourcePorts -- just working on tweaking the build recipe.
