### ISSUE TITLE
[Bug] Graphical Glitch in Pharmacy

### ISSUE THREAD

**Issue by MadeInDutch** [CorsixTH/CorsixTH#1678]
#### Describe the issue
Whenever a patient happens to be drinking their medicine in a pharmacy, the cabinet glitches through the wall for some reason.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait for a patient to come to the pharmacy and get treated.

3.

#### Save Game
https://drive.google.com/file/d/1KR6JioKrXxoNsIWkD4jO84Qu-d8qfAlH/view?usp=sharing

or

[1678 Graphical Glitch in Pharmacy.sav.zip](https://github.com/user-attachments/files/19847985/1678.Graphical.Glitch.in.Pharmacy.sav.zip)

#### Expected Behavior
I expect the cabinet to not show through the wall.

#### System Information
**CorsixTH Version:** 0.64-rc2

**Operating System:** Windows 10

**Theme Hospital Version:** CD

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
![Theme Hospital graphical bug](https://user-images.githubusercontent.com/67276601/88652610-5e76bd80-d0cb-11ea-8f1b-bbc750ec7ea3.png)

**Comment by mugmuggy** [comment]
Known issue linked to the meta issue

**Comment by lewri** [comment]
Merged into meta
