### ISSUE TITLE
[Bug] results of linting appdata.xml

### ISSUE THREAD

**Issue by emorrp1** [CorsixTH/CorsixTH#1692]
[CorsixTH/com.corsixth.CorsixTH.appdata.xml](https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/com.corsixth.CorsixTH.appdata.xml)
https://appstream.debian.org/sid/contrib/issues/corsix-th.html

### Warnings

*    asv-description-has-plaintext-url
    com.corsixth.CorsixTH.appdata.xml:16 - ul
    The description contains a web URL in plain text. This is not allowed, please use the <url/> tag instead to share links.

### Hints

*    asv-screenshot-media-url-not-secure
    com.corsixth.CorsixTH.appdata.xml:31 - http://corsixth.com/wp-content/uploads/2016/04/screenshot9-1024x640.jpg
    Consider using a secure (HTTPS) URL to reference this screenshot image or video.
*    asv-url-not-secure
    com.corsixth.CorsixTH.appdata.xml:72 - http://forums.corsixth.com/index.php/board,11.0.html
    Consider using a secure (HTTPS) URL for this web link.
*    asv-url-not-secure
    com.corsixth.CorsixTH.appdata.xml:70 - http://corsixth.com
    Consider using a secure (HTTPS) URL for this web link.
*    asv-cid-contains-uppercase-letter
    com.corsixth.CorsixTH.appdata.xml:3 - com.corsixth.CorsixTH
    The component ID should only contain lowercase letters.
*    asv-screenshot-media-url-not-secure
    com.corsixth.CorsixTH.appdata.xml:34 - http://corsixth.com/wp-content/uploads/2016/04/screenshot0-1024x640.jpg
    Consider using a secure (HTTPS) URL to reference this screenshot image or video.

**Comment by TheCycoONE** [comment]
@tobylane I believe the desktop file needs to be renamed as well now that the id has changed.

**Comment by TheCycoONE** [comment]
Looking over the latest appstream specification we probably want a `launchable` tag too (https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-launchable)

**Comment by TheCycoONE** [comment]
@tobylane additionally CorsixTH/CMakeLists.txt needs to be updated - I really merged that PR prematurely. :frowning: 

We likely want to rename the file to `com.corsixth.corsixth.metainfo.xml` per the latest specs as well.
