### ISSUE TITLE
Reinstating Roujin's Challenge to the code

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1702]
At some point in development the code for Roujin's challenge got lost. So right now entering the fax number for it does nothing except an adviser pop-up.

The challenge itself is inspired by the Anime film Roujin Z; where the Japanese population has become inundated with elderly patients requiring end-of-life care. To solve it they came up with a machine that cared for them without intervention (and things went wrong when the machine develops a mind of its own).

Aims are to:
- [x] Reintroduce the cheat
- [x] Make cheat trigger the "cheating" flag
- [x] Update the wiki page with its origins

Anyone interested reading up about the film (or watching it, it's pretty comfy) see here: https://myanimelist.net/anime/2000/Roujin_Z

**Comment by TheCycoONE** [comment]
Alternative explanation for name: https://github.com/CorsixTH/CorsixTH/blob/master/LICENSE.txt#L5 - or perhaps both are related to the anime??? If only we could ask.

**Comment by lewri** [comment]
Good spot. There was a Roujin mentioned across several parts of the code too from 2009/2010. I imagine before GitHub times. Though it looks like they went for a similar take to the film's issue too.
