### ISSUE TITLE
[Bug] Blue screen while checking out the rewards

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1707]
#### Describe the issue
Blue screen while checking out the rewards.

#### Steps to Reproduce
1. Play the game, save just before the end of the year.

2. At the end of the year, the game stops and overlays the screen with a blue taint, and displays the rewards you received.

3. You can inspect the rewards (clicking on them works), although reading is a bit difficult due to the the blue colour.

4. If you close the reward window, the blue taint disappears and the game continues.

#### Expected Behavior
While I don't like the blue taint at all, I can see the use. However, the rewards screen is fully functional, and the player even need to click on the close button, so at least that area should not be blue.

#### System Information
**CorsixTH Version:** *2dcb109e* currently, but that won't get into the repoistory.

**Operating System:** *Linux Ciinamon Mint 20*

**Theme Hospital Version:** *CD*

### Additional Info
![Screenshot from 2020-09-13 13-02-47](https://user-images.githubusercontent.com/3254232/93017008-c7f05400-f5c5-11ea-94f6-e1c3cb8a0c98.png)

**Comment by lewri** [comment]
The annual report window is meant to be infront of the blue tint.
Does it happen with the fax or staff_rise?

**Comment by Alberth289346** [comment]
I hardly play the game, but I don't remember seeing any blue-screen with a fax or staff related windows. Afaik the game continues to run in those cases.
