### ISSUE TITLE
Should message windows be openable on pause?

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1715]
Currently when paused and "editing while paused" is disabled we can open fax messages, staff rise windows. This has an avenue of unpausing the game. Should we be stopping this behaviour during pause? This came about while making #1714 

I've got no issue with these messages being openable if "editing while paused" is enabled.

Opening a Fax etc also removes the blue taint (even without the above PR). So it definitely is a 'break-out' of some sort.

**Comment by TheCycoONE** [comment]
I agree with you.
