### ISSUE TITLE
Download themes directly

### ISSUE THREAD

**Issue by donno2048** [CorsixTH/CorsixTH#1736]
**What feature or enhancement would you like to add?**
Make it possible to download themes directly from the executable
**How would this feature benefit the gameplay of CorsixTH?**
It won't

**Comment by lewri** [comment]
Are you able to give a bit more detail in what kind of themes you are referring to/suggesting?

**Comment by lewri** [comment]
No response and not enough information given to pick what the enhancement relates to.
