### ISSUE TITLE
Max number of radiators at a tile in TH?

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#1742]
In 99245e26403b108b600f1b803729b4edcf8b28bf (diff is 2896 lines, so reading is not recommended), having multiple objects at a tile was introduced.
There, the heating code started counting radiators at a tile in `iRadiatorNumber`, and computes for the case that `iRadiatorNumber > 0`:
``` diff
                 iMergeTemp = iRadiatorTemperature;
-                iMergeRatio = 2;
+                iMergeRatio = 2 - (iRadiatorNumber - 1) * 0.5;
```
I tried to place more than one radiator at a tile, and the game didn't allow that. In other words, this change does exactly nothing.

So the question is, are we supposed to allow more than one radiator at a tile, or is this code more complicated than needed?

**Comment by TheCycoONE** [comment]
Neither the original game nor CorsixTH allowed multiple radiators on a tile - so yes.

**Comment by mugmuggy** [comment]
Corsix did - I changed it back with #1164 - which was made possible by that earlier commit, so it didn't then it did, and now it doesn't. Later I found that commit and wondered if it should just be unpicked. To disable the multiple objects issue.
