### ISSUE TITLE
[Bug] Support OSX Dark Mode in Sprite Viewer

### ISSUE THREAD

**Issue by driverpt** [CorsixTH/CorsixTH#1752]
#### Describe the issue
Having Dark Mode on OSX causes Frame Viewer and Sprite Viewer font's to be White and the Foreground not Dark.

#### Steps to Reproduce
1. Enable OSX Dark Mode
2. Open AnimView.app

#### Save Game
N/A

#### System Information
**CorsixTH Version:** *N/A*

**Operating System:** *Mac OSX 15.10*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt
N/A

### Additional Info
Currently `wxwidgets` >= 3.1.4 supports Dark Mode. But `wxmac` doesn't have the Development Version available, only the Stable one.

**Comment by TheCycoONE** [comment]
So is this something we're just going to get automatically when you can use the latest versions of wxwidgets?

**Comment by lewri** [comment]
Just to clarify, is the issue specifically with Corsix's AnimView or wxwidgets/wxmac?

https://formulae.brew.sh/formula/wxmac says their version is 3.0.5.1 and supports up to Big Sur.

**Comment by driverpt** [comment]
Issue is with `wxmac`, but i wanted to raise this bug so that the community is aware.

The fix for this issue is "hacky", as you need to modify `Info.plist` inside `AnimView.app/Contents` folder and add the following property:

```
<key>NSRequiresAquaSystemAppearance</key>
<true />
```

This basically tells OSX that the App does not support Dark Mode yet.

**Comment by lewri** [comment]
As I don't think we use the animviewer often are you able to hack the fix for your own build in OS X? It'll be good to monitor how soon wxmac is fixed. If we're expecting it to be a long way off it may be worth considering the workaround.

**Comment by driverpt** [comment]
I can try to fix it. I'll just create an `info.plist.in` template file and write it inside the Package

**Comment by TheCycoONE** [comment]
It's worth noting that wxwidgets have claimed they would release 3.2 by the end of the year - though they also said there would be a 3.1.5 first.

**Comment by lewri** [comment]
Any update from wxwidgets cyco and driver? Or your local fix?

**Comment by TheCycoONE** [comment]
Only that it's planned for early 2021 now; looking through the tracker there's been some pretty major issues / fixes going through.

**Comment by tobylane** [comment]
https://github.com/tobylane/CorsixTH/actions/runs/2221713344

The third and fourth artifacts here include Animview built with wxwidgets 3.1.5, which some are considering stable enough. The dark mode works fine. The new expected date for 3.2 is June.

**Comment by TheCycoONE** [comment]
homebrew now also ships with wxwidgets 3.1 by default instead of wxmac. 3.1.6 is a dev version but their page says it's production ready. I think we can close this out.
