### ISSUE TITLE
[Improvement] Allow Graphics Transformation/Shaders

### ISSUE THREAD

**Issue by driverpt** [CorsixTH/CorsixTH#1756]
While implementing Serious Radiation (#1659), we noticed that currently the Sprites are being loaded directly into the GPU `SDL_Texture` and are being statically saved.

Since both Serious Radiation and Jellytis aren't Standard Sprites and/or Animations, they require bitmap manipulation on pre-rendering.

There are two ways of doing this:

1. Switch from `SDL_Texture` directly to Bitmap and write via OpenGL.
2. Instead of saving `SDL_Texture`, use `SDL_Surface` (uses more memory).

**Comment by TheCycoONE** [comment]
I don't see any advantage to the first option, so I'm partial to the second. You could also manipulate a bitmap and stream data to an SDL_Texture like I do in th_movie but I don't see the advantage of that either.

**Comment by driverpt** [comment]
The first option you can use an OpenGL shader directly on top of the rendered bitmap.

**Comment by TheCycoONE** [comment]
Ok, I prefer to avoid directly using OpenGL. In the past CorsixTH had OpenGL and DirectX specific code that was compile time selected; we dropped it with the move to SDL2. Of course if performance is too bad we can reconsider.

**Comment by driverpt** [comment]
I'm not shocked about using OpenGL for rendering and SDL2 for Resource Loading.

OpenGL is the most portable way of rendering graphics

**Comment by flackr** [comment]
I have an implementation for jellyitus (filed #1946) which uses neither of these approaches. Instead it renders the sprite as separate shifted blocks. While this is more draw calls, I suspect it will in fact be cheaper than generating custom textures and is ultimately drawing the same number of pixels.

**Comment by lewri** [comment]
Resolved by alternative implementation of Serious Radiation / Jellyitis
