### ISSUE TITLE
[Bug] traditional_chinese.lua contains reserved unicode character U+FFFF

### ISSUE THREAD

**Issue by emorrp1** [CorsixTH/CorsixTH#1760]
```
$ grep -c $'\uffff' CorsixTH/Lua/languages/traditional_chinese.lua
11
$ git log -G $'\uffff'
0d1a3491 Add the main menu translation, fix previous versio
```

According to [unicode 7], it has no "standard, interchangeable meaning" so should not be used as part of CorsixTH's translation files. I suspect they can simply be deleted with no user impact, but I am not chinese, so would appreciate it being checked by e.g. @yangfl. The characters can be searched for in vim with `/\v%uffff`, they were added by 0d1a3491 and unchanged in the 10 years since. Originally reported to [debian #976746].

[unicode 7]: https://www.unicode.org/versions/corrigendum9.html
[debian #976746]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976746#10

**Comment by lewri** [comment]
It looks like whether included or not they have no actual effects,
This answer also points to your link above. I'm not entirely knowledgable in what the right answer is though -- what I'm getting is they "should not" rather than "must not".
https://stackoverflow.com/a/16619933

**Comment by yangfl** [comment]
`sed s/$'\uffff'/圖/g traditional_chinese.lua`
