### ISSUE TITLE
[Bug] Can't compile, RncLib warning/error

### ISSUE THREAD

**Issue by squigley** [CorsixTH/CorsixTH#1780]
#### Describe the issue

Following the instructions, I attempted to compile the current git source, but I get an error related to RncLib, and it fails:

squigley@Latitude-E5530-non-vPro ~/CorsixTH $ mkdir build
squigley@Latitude-E5530-non-vPro ~/CorsixTH $ cd build
squigley@Latitude-E5530-non-vPro ~/CorsixTH/build $ cmake -DUSE_SOURCE_DATADIRS=ON .. 
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Note: SDL audio is enabled (default)
Note: FFmpeg video is enabled (default)
Note: FreeType2 is enabled (default)

Building common libraries
You have called ADD_LIBRARY for library RncLib without any source files. This typically indicates a problem with your CMakeLists.txt file
Building CorsixTH
CMake Error at CorsixTH/CMakeLists.txt:46 (add_executable):
  add_executable called with incorrect number of arguments

CMake Error at CorsixTH/CMakeLists.txt:57 (target_link_libraries):
  Cannot specify link libraries for target "CorsixTH" which is not built by
  this project.

-- Configuring incomplete, errors occurred!
See also "/home/squigley/CorsixTH/build/CMakeFiles/CMakeOutput.log".

I found the files under libs/rnc, and they don't configure correctly directly either:

squigley@Latitude-E5530-non-vPro ~/CorsixTH/libs/rnc $ cmake .
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
You have called ADD_LIBRARY for library RncLib without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/squigley/CorsixTH/libs/rnc

#### Steps to Reproduce
1. git clone the source

2. mkdir build

3. cd build
4. cmake -DUSE_SOURCE_DATADIRS=ON ..

#### Expected Behaviour

cmake would complete, so I could compile the source.

#### System Information
**CorsixTH Version: git as of Dec 26th** file in .git includes " 541540bc9f95719269d9129196f53493ef3e988f Simon Quigley <squigley@Latitude-E5530-non-vPro.(none)> 1609043185 -0500	clone: from https://github.com/CorsixTH/CorsixTH.git"

**Operating System: Linux - 4.15.0-128-generic - x86_64** (Mint 19)

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
[CMakeOutput.log](https://github.com/CorsixTH/CorsixTH/files/5748668/CMakeOutput.log)

**Comment by lewri** [comment]
That PR I don't think made any changes that would affect building. I'm guessing it got affected by a previous PR. Have you tried to build before from another time?

**Comment by TheCycoONE** [comment]
The issue is that they are using an older cmake version that doesn't support add_library on it's own. We advertise support for 3.5 but clearly no one has actually tested it lately.

**Comment by squigley** [comment]
This works now.
`
squigley@Latitude-E5530-non-vPro ~/CorsixTH $ git pull
remote: Enumerating objects: 1196, done.
remote: Counting objects: 100% (1196/1196), done.
remote: Compressing objects: 100% (750/750), done.
remote: Total 1317 (delta 892), reused 578 (delta 438), pack-reused 121
Receiving objects: 100% (1317/1317), 1.25 MiB | 3.63 MiB/s, done.
Resolving deltas: 100% (900/900), completed with 43 local objects.
From https://github.com/CorsixTH/CorsixTH
   541540bc..852a5b22  master     -> origin/master
 * [new branch]        gh-pages   -> origin/gh-pages
Updating 541540bc..852a5b22
Fast-forward
 .github/workflows/Linux.yml                          |   27 +-
 .luacheckrc                                          |    2 +-
 CorsixTH/CMakeLists.txt                              |    2 +-
 CorsixTH/Lua/app.lua                                 |    3 +-
 CorsixTH/Lua/dialogs/fullscreen/fax.lua              |    2 +-
 CorsixTH/Lua/entities/object.lua                     |   14 +-
 CorsixTH/Lua/languages/greek.lua                     | 3349 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 CorsixTH/Lua/objects/door.lua                        |    2 +
 CorsixTH/Lua/objects/doors/entrance_right_door.lua   |    8 +-
 CorsixTH/Lua/objects/doors/swing_door_right.lua      |    6 +-
 CorsixTH/Lua/objects/helicopter.lua                  |    8 +-
 CorsixTH/Lua/objects/litter.lua                      |   24 +-
 CorsixTH/Lua/objects/plant.lua                       |    4 +-
 CorsixTH/Lua/objects/rathole.lua                     |    4 +-
 CorsixTH/Lua/objects/reception_desk.lua              |   21 +-
 CorsixTH/Lua/ui.lua                                  |    2 +-
 CorsixTH/Lua/world.lua                               |   75 +-
 CorsixTH/Luatest/spec/entities/machine_spec.lua      |    6 +-
 CorsixTH/Luatest/spec/entities/object_spec.lua       |    5 +-
 LevelEdit/README.txt                                 |    6 +-
 LevelEdit/src/com/corsixth/leveledit/Emergency.java  |    3 +-
 LevelEdit/src/com/corsixth/leveledit/Gui.java        |   39 +-
 LevelEdit/src/com/corsixth/leveledit/StartStaff.java |    2 +-
 libs/rnc/CMakeLists.txt                              |    4 +-
 24 files changed, 3507 insertions(+), 111 deletions(-)
 create mode 100644 CorsixTH/Lua/languages/greek.lua
`
`
squigley@Latitude-E5530-non-vPro ~/CorsixTH $ cd build/
squigley@Latitude-E5530-non-vPro ~/CorsixTH/build $ cmake -DUSE_SOURCE_DATADIRS=ON ..
Note: SDL audio is enabled (default)
Note: FFmpeg video is enabled (default)
Note: FreeType2 is enabled (default)

Building common libraries
Building CorsixTH
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread (found version "2.0.8") 
  SDL2 found
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.3.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "5.3.3") 
  Lua5.3 found
-- Found SDL_mixer: /usr/lib/x86_64-linux-gnu/libSDL2_mixer.so (found version "2.0.2") 
  SDL_mixer found
-- Found AVCODEC: /usr/lib/x86_64-linux-gnu/libavcodec.so (found version "57.107.100") 
-- Found AVFORMAT: /usr/lib/x86_64-linux-gnu/libavformat.so (found version "57.83.100") 
-- Found AVDEVICE: /usr/lib/x86_64-linux-gnu/libavdevice.so (found version "57.10.100") 
-- Found AVUTIL: /usr/lib/x86_64-linux-gnu/libavutil.so (found version "55.78.100") 
-- Found SWSCALE: /usr/lib/x86_64-linux-gnu/libswscale.so (found version "4.8.100") 
-- Found POSTPROC: /usr/lib/x86_64-linux-gnu/libpostproc.so (found version "54.7.100") 
-- Found SWRESAMPLE: /usr/lib/x86_64-linux-gnu/libswresample.so (found version "2.9.100") 
-- Found FFmpeg: /usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so;/usr/lib/x86_64-linux-gnu/libswresample.so  
  FFmpeg found
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "2.8.1") 
  FreeType2 found

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.13") found components:  doxygen missing components:  dot
-- Configuring done
-- Generating done
-- Build files have been written to: /home/squigley/CorsixTH/build
squigley@Latitude-E5530-non-vPro ~/CorsixTH/build $ make
Scanning dependencies of target RncLib
[  2%] Building CXX object libs/rnc/CMakeFiles/RncLib.dir/rnc.cpp.o
[  5%] Linking CXX static library libRncLib.a
[  5%] Built target RncLib
Scanning dependencies of target CorsixTH_lib
[  8%] Building C object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/random.c.o
[ 11%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/bootstrap.cpp.o
[ 14%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/iso_fs.cpp.o
[ 17%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/lua_rnc.cpp.o
[ 20%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/persist_lua.cpp.o
[ 22%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/run_length_encoder.cpp.o
[ 25%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/sdl_audio.cpp.o
[ 28%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/sdl_core.cpp.o
[ 31%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/sdl_wm.cpp.o
[ 34%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th.cpp.o
[ 37%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_gfx.cpp.o
[ 40%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_gfx_font.cpp.o
[ 42%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_gfx_sdl.cpp.o
[ 45%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua.cpp.o
[ 48%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_anims.cpp.o
[ 51%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_gfx.cpp.o
[ 54%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_iso.cpp.o
[ 57%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_lfs_ext.cpp.o
[ 60%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_map.cpp.o
[ 62%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_movie.cpp.o
[ 65%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_sound.cpp.o
[ 68%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_strings.cpp.o
[ 71%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_lua_ui.cpp.o
[ 74%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_map.cpp.o
[ 77%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_map_overlays.cpp.o
[ 80%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_movie.cpp.o
[ 82%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_pathfind.cpp.o
[ 85%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/th_sound.cpp.o
[ 88%] Building CXX object CorsixTH/CMakeFiles/CorsixTH_lib.dir/Src/xmi2mid.cpp.o
[ 91%] Linking CXX static library libCorsixTH_lib.a
[ 91%] Built target CorsixTH_lib
Scanning dependencies of target CorsixTH
[ 94%] Building CXX object CorsixTH/CMakeFiles/CorsixTH.dir/Src/main.cpp.o
[ 97%] Building CXX object CorsixTH/CMakeFiles/CorsixTH.dir/SrcUnshared/main.cpp.o
[100%] Linking CXX executable corsix-th
[100%] Built target CorsixTH
`
