### ISSUE TITLE
[Bug] ButtonUp failed, can't click or type

### ISSUE THREAD

**Issue by squigley** [CorsixTH/CorsixTH#1782]
#### Describe the issue

Sorry to be creating another bug/issue. I was able to compile the latest git code, I loaded a save game from the start of an empty level. It suggested that I restart due to having updated the binary, which makes sense. I chose to restart.

I created a few rooms, I was creating a cardio room, I placed the cardio machine, but then it was still stuck to the mouse cursor. I tried selecting the screen, which went red, but the cardio machine was still stuck to the cursor. I clicked around, couldn't clear it. Clicking the X on the room just made it go red.

Pressing escape removed the whole room, and the cardio machine from the cursor, but now none of the buttons to create rooms, or furnish the hall or anything worked. The menus also didn't work, they would drop down, but I couldn't click on anything.

I tried shift+S to save the game in case I could upload it in that state, but I couldn't type to enter a name, or press enter. I tried typing, it caused different windows like the hire staff window to pop up.

Shift+Q also didn't work, it asked me if I wanted to quit, but I couldn't click on anything. I Alt Tabbed out, and Ctrl+C to kill the process.

In the console it said:

```An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
/home/squigley/CorsixTH/CorsixTH/Lua/entities/machine.lua:39: attempt to index a nil value (field 'ui')
stack traceback:
	/home/squigley/CorsixTH/CorsixTH/Lua/entities/machine.lua:39: in local 'constructor'
	/home/squigley/CorsixTH/CorsixTH/Lua/class.lua:74: in global 'Machine'
	/home/squigley/CorsixTH/CorsixTH/Lua/world.lua:1903: in method 'newObject'
	...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:518: in field 'placeObject'
	/home/squigley/CorsixTH/CorsixTH/Lua/dialogs/edit_room.lua:1552: in method 'placeObject'
	...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:468: in function <...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:451>
	(...tail calls...)
	/home/squigley/CorsixTH/CorsixTH/Lua/window.lua:1641: in field 'onMouseUp'
	/home/squigley/CorsixTH/CorsixTH/Lua/ui.lua:902: in function </home/squigley/CorsixTH/CorsixTH/Lua/ui.lua:889>
	(...tail calls...)
	/home/squigley/CorsixTH/CorsixTH/Lua/app.lua:1027: in function </home/squigley/CorsixTH/CorsixTH/Lua/app.lua:1022>

Warning: No event handler for buttonup
```

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. create a diag|cardio room, draw the outline, place the door/window etc.

3. Click to place the cardio machine.

#### Save Game

Attached
[save.zip](https://github.com/CorsixTH/CorsixTH/files/5749866/save.zip)

#### Expected Behaviour

Cardio machine would place, it would switch to the screen to be placed.

#### System Information
**CorsixTH Version: latest git**

**Operating System:4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux Mint 19 ** 

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt

```
Created game with savegame version 151.
Savegame version is 151 (Trunk), originally it was 151 (Trunk)
Error in buttonup handler: 
/home/squigley/CorsixTH/CorsixTH/Lua/entities/machine.lua:39: attempt to index a nil value (field 'ui')
stack traceback:
	/home/squigley/CorsixTH/CorsixTH/Lua/entities/machine.lua:39: in local 'constructor'
	/home/squigley/CorsixTH/CorsixTH/Lua/class.lua:74: in global 'Machine'
	/home/squigley/CorsixTH/CorsixTH/Lua/world.lua:1903: in method 'newObject'
	...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:518: in field 'placeObject'
	/home/squigley/CorsixTH/CorsixTH/Lua/dialogs/edit_room.lua:1552: in method 'placeObject'
	...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:468: in function <...squigley/CorsixTH/CorsixTH/Lua/dialogs/place_objects.lua:451>
	(...tail calls...)
	/home/squigley/CorsixTH/CorsixTH/Lua/window.lua:1641: in field 'onMouseUp'
	/home/squigley/CorsixTH/CorsixTH/Lua/ui.lua:902: in function </home/squigley/CorsixTH/CorsixTH/Lua/ui.lua:889>
	(...tail calls...)
	/home/squigley/CorsixTH/CorsixTH/Lua/app.lua:1027: in function </home/squigley/CorsixTH/CorsixTH/Lua/app.lua:1022>
```

**Comment by Alberth289346** [comment]
This looks like a bug introduced by me yesterday.
Just added a PR for that. Could you try that?

Alternatively, simply change `CorsixTH/Lua/entities/machine.lua` as indicated in
https://github.com/CorsixTH/CorsixTH/pull/1783/commits/3d9bd8482edbcd4f179a7e7220ed43a3470be72b#diff-80dbb95dd929362936434d22fcc57654f729bc9b0149de237d5908add8a54ffaR39

(the other change in the file is correct, but it doesn't change behaviour, so it's safe to keep it as is).

**Comment by Alberth289346** [comment]
This looks like a bug introduced by me yesterday.
Just added a PR for that. Could you try that?

Alternatively, simply change `CorsixTH/Lua/entities/machine.lua` as indicated in
https://github.com/CorsixTH/CorsixTH/pull/1783/commits/3d9bd8482edbcd4f179a7e7220ed43a3470be72b#diff-80dbb95dd929362936434d22fcc57654f729bc9b0149de237d5908add8a54ffaR39

(the other change in the file is correct, but it doesn't change behaviour, so it's safe to keep it as is).

**Comment by Alberth289346** [comment]
Played with your save for a while (was completely empty hospital), and could build machines without problem with the fix applied.

**Comment by squigley** [comment]
I can confirm that this is now fixed. I did a git pull, make clean, make, and now it all works properly.

One thing I noticed is that when I die/fail the level, I now have to press escape from the video (space used to work), and it no longer tells me why I failed. Not related to this, just thought I would mention it as an observation.

**Comment by lewri** [comment]
Could you open a new issue for that one @squigley and we'll have a look.
