### ISSUE TITLE
[Bug] skip fail videos / given reason for failing

### ISSUE THREAD

**Issue by squigley** [CorsixTH/CorsixTH#1787]
#### Describe the issue

I was using 0.61, but have now updated to trunk 151. When I fail a level, I now have to press escape from the video. Pressing space (or maybe enter) used to work to terminate the video during or at the end of playback.

When you are returned to the menu, it no longer tells you why you failed. It used to come up with a dialogue on top of the menu telling you, eg "you killed over 15% of patients", "your reputation was less than 400".

#### Steps to Reproduce
1. Play a game through until the end of the year, with something in a failing state, eg too many deaths, too far in debt, bad reputation.

2. Video will play to show you failed.

3. During are when the video finishes, clicking or pressing any keys (other than escape) doesn't do anything.
4. Escape returns you to the menu, but it doesn't tell you why you failed.

#### Save Game

Attached. wait about 30 seconds for the end of the year and it will fail (bad reputation), causing the video to run.

[zave.zip](https://github.com/CorsixTH/CorsixTH/files/5756034/zave.zip)

#### Expected Behaviour

Pressing space or enter or clicking would end the video, showing the reason for failing.

#### System Information
**CorsixTH Version:** *trunk 151*

**Operating System:** *Linux Mint 19*

**Theme Hospital Version:** *GOG.com*

**Comment by lewri** [comment]
I can't replicate in 143 (mainly since accidentally executing a reason for  #1779 ) but also quickly used the loselevel cheat and error message came up fine.
Probably something might've broke between 143 and 151. I'll do some more testing soon.

**Comment by lewri** [comment]
Can confirm the following in 151:
1. Enter/space do not exit the failure video
2. Pressing Esc causes the video to exit without lose condition.
3. Pressing left mouse button exits video with lose condition.

**Comment by lewri** [comment]
Okay I found the fault.

When you press Escape our code is executing it both as a ``global_stop_movie`` as well as  ``global_cancel`` command.
The resulting ``global_cancel`` makes the lose window close when the movie ends (because the window is effectively waiting behind the movie... more or less).

**Comment by squigley** [comment]
Can confirm that this is working properly now. Clicking to skip/at end of video, or pressing escape, returns to the menu and the reason is displayed properly. Thanks!
