### ISSUE TITLE
CMake error in Linux Lua 5.1 + LuaJIT tests?

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1802]
``  /home/runner/work/_temp/a76af854-9afe-49c3-8c27-c41ff8951bac.sh: line 11: /opt/hostedtoolcache/cmake/3.19.3/x64/cmake-3.19.3-Linux-aarch64/bin/cmake: cannot execute binary file: Exec format error ``

Looks like the 5.3 test is working though.

**Comment by lewri** [comment]
Looking through the Virtual Environment update 5 days ago to actions, CMake was bumped from 3.19.1 to 3.19.2 so wonder if that could've done something.

**Comment by TheCycoONE** [comment]
cmake changed something about their site that caused actions-setup-cmake to start downloading an aarch64 version. Fixed in the latest version.
