### ISSUE TITLE
[Runtime bug] Unable to run - Missing files

### ISSUE THREAD

**Issue by mdziczkowski** [CorsixTH/CorsixTH#1805]
While attempting to run it, I recieve a window with following message on it's top:

> Corsix-TH need a copy of data files from the orginal Theme Hospital game (or demo) in order to work. Please use the bellow selector to locate the Theme Hospital install directory.

Selecting the pah of it in /usr/share (where are the corsdix-th files) dosn't work

**Comment by tobylane** [comment]
What version of Corsixth are you using? What's the source of your theme hospital data? Eg Cd, GOG. 

It requires the theme hospital data. You can download the demo here https://th.corsix.org/Demo.zip and put it in /usr/share/games/corsix-th.

**Comment by mdziczkowski** [comment]
@tobylane
> What version of Corsixth are you using?
I use the latest avaliable in the repository (0.64-2)

> What's the source of your theme hospital data?
dunno. I had  downloaded from the repository the packages: "corsix-th" and "corsix-th-data"

> It requires the theme hospital data
why it isn't already included (to make it work "out of the box") ?

**Comment by tobylane** [comment]
The original game data isn't ours to distribute, especially in a free software repository. We recommend finding a CD or buying it from GOG.

**Comment by Alberth289346** [comment]
The original game is a commercial product. We don't have a license to distribute that product, so you need to use a different channel to obtain it.
Ultimately, we do want to free ourselves from this need, but we aren't there yet.
