### ISSUE TITLE
Allow Emergencies in Free Build  

### ISSUE THREAD

**Issue by dell3231** [CorsixTH/CorsixTH#1826]
**What feature or enhancement would you like to add?**
I think that people should be able to have emergencies in free build mode (only custom levels)

**How would this feature benefit the gameplay of CorsixTH?**
Not sure

**Was the feature in the original game?**
No

**What version of CorsixTH are you using?**
0.64

**Does this feature/enhancement relate to a current problem?**
Emergencies dont show up in free build mode

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by lewri** [comment]
So looking over the emergency code an emergency is only generated if the level file dictates it (whether custom or not). The only thing missing related to this would be a toggle to _disable emergencies_ on free build. 

Could you share with us what custom level you're playing? It may just not have emergencies set.

**Comment by dell3231** [comment]
The level is called: Coffin's Creek

**Comment by lewri** [comment]
Thanks! I've not seen that one before. Could you zip the .level and .map file for it to and upload it here?

**Comment by Alberth289346** [comment]
Level doesn't have emergencies

**Comment by lewri** [comment]
As per above
