### ISSUE TITLE
[Bug] False missing Psychiatrist fax

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1838]
#### Describe the issue
At some point between 0.64 and Trunk 152 the game is thinking I don't have a Psychiatrist even though a Consultant Surgeon Psychiatrist is given at the start of the level.

#### Steps to Reproduce
1. *Load save game attached to this ticket* (may be useless)

2. Have a Psych built and hire no new doctors etc.

3. Wake for a psych patient to need psych.

#### Save Game

[emergencytests.zip](https://github.com/CorsixTH/CorsixTH/files/6140466/emergencytests.zip)

#### Expected Behavior
See the Psychiatrist

#### System Information
**CorsixTH Version:** *Trunk 151*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
![image](https://user-images.githubusercontent.com/20030128/111136862-1206c200-8576-11eb-9b2e-b71b0a91282a.png)

You can temporarily fix it by editing Psychiatrist and going back 1 stage to replace door, then finish editing. But it comes back.

**Comment by lewri** [comment]
This might potentially be related to #1835 (as the Psychiatrist was in the operating theatre when this happened)

**Comment by lewri** [comment]
Better save:  
[Autosave10.zip](https://github.com/CorsixTH/CorsixTH/files/6140549/Autosave10.zip)

**Comment by mugmuggy** [comment]
Specifically Hospital:countStaffOfCategory, has a case for checking the doctor class for specialties. But as pointed out when they are gowned up in surgery the humanoid_class is Surgeon and so they aren't counted in that function, resulting in the incorrect fax.

**Comment by tobylane** [comment]
Is it neater to check for surgeon here https://github.com/CorsixTH/CorsixTH/blob/faa908ec368cc6b6b00fc38413265147b49ed93f/CorsixTH/Lua/hospital.lua#L1619
or don't turn them into a surgeon (and track gown another way) here? https://github.com/CorsixTH/CorsixTH/blob/1360a99313c5bba85cd7a25c0895fe613b6bac73/CorsixTH/Lua/humanoid_actions/use_screen.lua#L171

**Comment by mugmuggy** [comment]
Indeed that seems like its only supporting mechanism, to track animation state. But it also does it for all the patients also in that same fashion, just we have logic elsewhere dependent on that state. In my opinion, I'm guessing doing 'elseif class.is(staff, Doctor)' is logical in countStaffOfCategory, as this is what that code is actually intending to do, if they are a Doctor, check their profile attributes to see if they have the additional skills. Humanoid class is more animation sets/states and easily interchangeable for the most part.

The other thing is that if you have a surgeon gowned, they don't get counted at all as a Doctor in that code either with or without a fix to include humanoid_class == "Surgeon"/or class.is, it needs ```(category == "Junior" and staff.profile.is_junior) or category == "Doctor" then```

Which probably makes it in the end easier to do the following as its also done in other spots.
staff.humanoid_class == "Surgeon" and "Doctor" or staff.humanoid_class to convert Surgeons to Doctor locally, allowing the 'if' to pick up Doctor category checks, and allowing the elseif to pick up the specialty checks only.

```lua
function Hospital:countStaffOfCategory(category, max_count)
  local result = 0
  local humanoid_class
  for _, staff in ipairs(self.staff) do
    humanoid_class = (staff.humanoid_class == "Surgeon" and "Doctor" or staff.humanoid_class)
    if humanoid_class == category then
      result = result + 1
    elseif humanoid_class == "Doctor" then
      if (category == "Psychiatrist" and staff.profile.is_psychiatrist >= 1.0) or
          (category == "Surgeon" and staff.profile.is_surgeon >= 1.0) or
          (category == "Researcher" and staff.profile.is_researcher >= 1.0) or
          (category == "Consultant" and staff.profile.is_consultant) or
          (category == "Junior" and staff.profile.is_junior)  then
        result = result + 1
      end
    end
    if max_count ~= nil and result >= max_count then break end
  end
  return result
end
```

**Comment by Alberth289346** [comment]
The staff member should have a function (or more functions?) so it can be queried for its skills, eg `hasResearcherSkill` or `hasSkill(skill)`

**Comment by mugmuggy** [comment]
Could just get away with the staff.profile.humanoid_class for those two checks instead of just staff.humanoid_class as that doesn't change and addresses both issues.

Likewise that would also get rid of some of the other areas where this occurs
https://github.com/CorsixTH/CorsixTH/blob/81db3338d89df253e85fc6b7ace9d937092dafaa/CorsixTH/Lua/dialogs/fullscreen/staff_management.lua#L227-L228
 
This one is done different just managing the reference to the the same table.
https://github.com/CorsixTH/CorsixTH/blob/81db3338d89df253e85fc6b7ace9d937092dafaa/CorsixTH/Lua/dialogs/fullscreen/staff_management.lua#L171-L179

Note this one uses profile.humanoid_class in the Handyman check just above.
https://github.com/CorsixTH/CorsixTH/blob/81db3338d89df253e85fc6b7ace9d937092dafaa/CorsixTH/Lua/dialogs/staff_dialog.lua#L258-L274
