### ISSUE TITLE
Remastered music

### ISSUE THREAD

**Issue by cxong** [CorsixTH/CorsixTH#1850]
**What feature or enhancement would you like to add?**
Support remastered music, or custom music

**How would this feature benefit the gameplay of CorsixTH?**
Allow the player to supply their own music

**Was the feature in the original game?**
No

**What version of CorsixTH are you using?**

**Does this feature/enhancement relate to a current problem?**

**Additional information**
There's a remaster of Theme Hospital's OST here: https://www.youtube.com/playlist?list=PL4E687B79796B72CE (video descriptions contain a link to download the music) and I think it'll be neat to have this in CorsixTH
However, even if this music cannot be bundled due to copyright, it would be nice if CorsixTH supports custom music files so the player can download the soundtrack separately, or any other music they might want

**Comment by lewri** [comment]
Hey :)

You are able to add your own music to the jukebox as you want. You just need to specify a folder of MP3 files in the settings menu.

https://github.com/CorsixTH/CorsixTH/wiki/Game-Guide#folder-locations

I'll admit we need some better instructions for it. The reason we can't use the remasters ourselves as the default is copyright issues etc.

**Comment by cxong** [comment]
Thanks! I wasn't aware it was possible already. I'm happy to close

**Comment by Alberth289346** [comment]
It would be nice if someone made new music for the game
