### ISSUE TITLE
[Bug] Replacing a machine in pause state will unpause

### ISSUE THREAD

**Issue by tobylane** [CorsixTH/CorsixTH#1865]
#### Describe the issue
Replacing a machine will unpause the game

#### Steps to Reproduce
1. Build a machine room, eg Inflator
2. Pause
3. Replace the machine

#### Expected Behavior
Game stays paused

#### System Information
0ef7cb0
macOS 10.16.7
CD

**Comment by lewri** [comment]
Interesting... I'll take a look later.
Can you confirm if it's also in stable release?

**Comment by tobylane** [comment]
Did some bisecting and it's the change of https://github.com/CorsixTH/CorsixTH/commit/85613f58a7eaa2ffdfc2e3a636484fc6364b85b1

**Comment by lewri** [comment]
Okay come from #1766 . Not entirely sure how but will find out.

**Comment by lewri** [comment]
Bug arises because we have a confirm dialog when we replace a machine. Hopefully I'll look at handling it tomorrow..

https://github.com/CorsixTH/CorsixTH/blob/0ef7cb030817b8e1a61399ec8c9773b0f7696c34/CorsixTH/Lua/dialogs/machine_dialog.lua#L102-L122

**Comment by lewri** [comment]
The license looks compatible to me, I think it just needs  the author to be mentioned in our license file
https://en.wikipedia.org/wiki/Zlib_License?wprov=sfla1

**Comment by lewri** [comment]
An additional note here. This actually affects several other confirm boxes too. I don't think it's particularly game breaking though (unless thought otherwise) so if I haven't pushed a fix in time it shouldn't hold back 0.65
