### ISSUE TITLE
[Bug] Highlighting Console can temporarily freeze game

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1876]
#### Describe the issue
If text is being sent to the console and you have clicked inside it/highlighted in it the game freezes up until you press Enter.

#### Steps to Reproduce
1. (May be windows specific) Add some debug statements or something to generate into the console on a regular event

2. Highlight/play with the console until game freezes (because it wants to print to the console)

3. Press Enter to resume

#### Expected Behavior
Don't freeze on highlighting in the console (But this may be unfixable, or even intended behaviour)

#### System Information
**CorsixTH Version:** *0.64 & Trunk 155*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG*

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
![image](https://user-images.githubusercontent.com/20030128/118335185-fd5b9180-b506-11eb-9eed-1869d7da121e.png)

**Comment by TheCycoONE** [comment]
This doesn't look like the sort of issue we have any control over?

**Comment by mugmuggy** [comment]
Indeed, nothing we can really do about it.
