### ISSUE TITLE
[Bug] Persistence problem on loads

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1879]
#### Describe the issue
Games are failing to load saved in Trunk savegame version 155.

#### Steps to Reproduce
1. Make a game in master

2. Save it

3. Try to load it.

#### Expected Behavior
Load

#### System Information
**CorsixTH Version:** Trunk 155 (could be earlier)

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
<LocalisedString> Current value:Error while loading game: Lua\persistance.lua:268: Cycle while depersisting permanent object key or userdata metatable after 4 objects (2514 bytes)
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by lewri** [comment]
Still was present in 154... appveyor can't go back further than that.

**Comment by lewri** [comment]
Broke after #1800 
[CorsixTH - 510.zip](https://github.com/CorsixTH/CorsixTH/files/6494326/CorsixTH.-.510.zip)

Problem Win Portable attached as it was due to be deleted today.

**Comment by TheCycoONE** [comment]
Fixed
