### ISSUE TITLE
Please describe the playable status in the Readme

### ISSUE THREAD

**Issue by kparal** [CorsixTH/CorsixTH#1884]
**What feature or enhancement would you like to add?**
I love open source remakes of old games. However, very often they don't describe how playable the project is, and that doesn't allow users to create expectations and decide whether to use this OSS project or not. It seems this problem also applies to CorsixTH. I searched the [Readme](https://github.com/CorsixTH/CorsixTH/blob/master/README.md) and the [FAQ](https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions) and I found no indication on CorsixTH's playable status. Some pieces about missing features can be gathered from [Programming Ideas](https://github.com/CorsixTH/CorsixTH/wiki/Programming-Ideas), however that is difficult to find and not fit for general consumption.

Please include a summary of the current playable status in the Readme (possibly linking to the FAQ where it can be expanded in greater depth). The playable status means "how playable in general this OSS remake is?", so e.g.:
* Is everything from the original game implemented, or is something missing?
* What are the notable features missing in the remake?
* Are there any high-level long-term bugs that people should be aware of?
* Are there any parts of the game missing (like the tutorial, campaign, multiplayer, etc)?
* Are there any important changes to the game or gameplay compared to the original, which should be mentioned (e.g. a different AI, tweaked difficulty, re-balanced economy, etc)? These changes don't need to be "better" or "worse", they are just different (e.g. because the original behavior was hard to replicate, so a different one was used).
* Are there any notable features which the remake has on top of the original (e.g. higher resolution support, larger maps support, an option to speed up time, etc)?

A section like this help users to decide whether to play CorsixTH or the original. (Often I worry that an incomplete OSS remake would make my experience worse, and because a status like this is not published and users are kept in the dark, I often end up playing the original instead. I'm sure there are more people like me). It would also help spread out the word and market your game, if the playable status is very good. And lastly it can attract some developers when they see that some pieces of the game are still waiting to be implemented.

Thanks :slightly_smiling_face:

**Comment by lewri** [comment]
The wiki is generally a bit out of date -- we have a project to attempt to update it [here](https://github.com/CorsixTH/CorsixTH/projects/3)
This suggestion though is probably feasible for anyone to do.  [1.0 Goal](https://github.com/CorsixTH/CorsixTH/projects/2) is probably the most recent indicator of outstanding items.
In terms of long-term bugs -- we don't have a definitive list of this. I suppose you could call #1638 one of them though...

This is probably a low priority, however for after the next release.

**Comment by TheCycoONE** [comment]
A highlight summary in the readme of the major differences isn't a terrible idea.

We have zoom, custom resolution, extra levels, support for additional languages and support for player levels and campaigns. We are missing rats, the bonus levels, and some disease visuals. The original campaign is fully playable.

**Comment by Alberth289346** [comment]
I think most players today have never even seen the orignal game, and thus wouldn't know what it contained.

I agree with lewri it's a good first issue to improve the readme file, so feel free to submit a patch with a merge request.

**Comment by kparal** [comment]
On top of 6dfecdd, you might also want to mention wall transparency, that's a killer feature of CorsixTH, imo.
