### ISSUE TITLE
[Bug] Wingame fax does not appear

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1897]
#### Describe the issue
Observed this twice while my wife was playing the first level of the campaign - a green ? fax tab appears on the bottom, which she clicks immediately.

The game pauses (without the blue tint) but the fax doesn't appear. To continue playing she goes back to the game speed menu, and the ? disappears.

#### System Information
**CorsixTH Version:** *0.65-beta1*

**Operating System:** *Arch Linux*

**Theme Hospital Version:** *CD*

**Comment by lewri** [comment]
Did you get a save of it at all?
