### ISSUE TITLE
[Bug] tag-invalid: <release> versions are not in order [0.64 before 0.65-beta1]

### ISSUE THREAD

**Issue by tim77** [CorsixTH/CorsixTH#1899]
#### Describe the issue
Minor issue in `0.65-beta1` in `com.corsixth.corsixth.metainfo.xml`. Just need to change order. This should be PR, but not enough time sorry.

#### System Information
**CorsixTH Version:** 0.65-beta1

**Operating System:** Fedora 34

**Comment by TheCycoONE** [comment]
Thanks @tim77. I'll fix that.

Are we suppose to keep our pre-releases or replace them?

**Comment by tim77** [comment]
There is special `development` attribute in appdata https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-releases
But even you not using this attribute it's better to keep this pre-releases IMO.

BTW i've already built this beta version for [Rawhide](https://koji.fedoraproject.org/koji/buildinfo?buildID=1755130) so people can test and discover it.

**Comment by TheCycoONE** [comment]
Fixed in release/0.65 85d38c5f5ea0301218db5e7b31d9f4c859457205

Thanks @tim77
