### ISSUE TITLE
TTF fonts are ugly in CorsixTH

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1904]
See #1901 

The font rendering in CorsixTH is particularly ugly. This appears to be because we are rendering all fonts in monochrome so there is no subpixel hinting.

**Comment by TheCycoONE** [comment]
To be clear there still isn't subpixel rendering for LCD screens. That will be a bigger fix. What I enabled here was grayscale anti-aliasing.

**Comment by kparal** [comment]
> To be clear there still isn't subpixel rendering for LCD screens. That will be a bigger fix. What I enabled here was grayscale anti-aliasing.

Is there a ticket to track it? Or should this be reopened?

**Comment by lewri** [comment]
Yes #1907

**Comment by kparal** [comment]
I just tested 0.65-beta2 and this is a night and day difference in readability! Thank you!

before:
![fonts](https://user-images.githubusercontent.com/755451/119690074-aa100a00-be49-11eb-94ae-144cf8288b81.png)

after:
![fonts2](https://user-images.githubusercontent.com/755451/120192287-46a42480-c21b-11eb-9c3c-ec417091aefc.png)
