### ISSUE TITLE
[Bug] 0.65-beta2 Windows Store trigger

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1911]
#### Describe the issue
Launching CorsixTH from the portable Windows version is causing Windows to ask you to launch the Windows Store.
However, regardless of prompt chosen the game still launches.

NOTE: This could be down to group policies as I'm testing on a work laptop. Though I have admin rights...

#### Steps to Reproduce
1. Download the Windows portable

2. Launch and get prompt

3. Press yes or no, game launches (though the store doesn't open on yes)

#### Expected Behavior
Don't ask the prompt and just launch the game

#### System Information
**CorsixTH Version:** 0.65 beta2 portable

**Operating System:** Windows 10 - ver 1909

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
![image](https://user-images.githubusercontent.com/20030128/120117812-f2e7fb80-c186-11eb-8e72-4c010ccb914d.png)

**Comment by lewri** [comment]
Additional notes:

The beta1 and beta2 installer EXEs also cause the Windows Store prompt.
The 0.64 installer does not cause this prompt.

Once 0.65 is installed, the CorsixTH.exe file does not cause the prompt.

**Comment by TheCycoONE** [comment]
I have no idea what might be causing this for you :(

**Comment by lewri** [comment]
There's a more pressing issue:

On the portable, at first launch (config missing) if you press no to the prompt only the command window will display. About 20 seconds later the application loads -- locks the mouse but doesn't show the window until you Alt-tab.

**Comment by lewri** [comment]
So on this machine, %HOMEPATH% returns as ``\`` -- this shouldn't happen on Windows... but it effectively means ``C:\``

**Comment by TheCycoONE** [comment]
That's a separate issue @lewri - and it seems like a special case we need to account for. We do not want to be polling `\\` locations without user interaction.

**Comment by lewri** [comment]
This is potentially upstream with the work build of Windows, cant repro on my own machine.

**Comment by lewri** [comment]
Closing this. Pretty sure it's upstream with whatever policies work has on my account.
