### ISSUE TITLE
File browsers should have an OK button

### ISSUE THREAD

**Issue by kparal** [CorsixTH/CorsixTH#1913]
**What feature or enhancement would you like to add?**
When I wanted to select a different font in _Settings -> Folders -> Fonts_, I was confused how to actually select it. After clicking on the font file, there was no `OK` button (like in the _TH Data_ browser). So I used `Back`, but that turned out to mean `Cancel`. Hitting `Esc` also means `Cancel`. On my third attempt I finally figured out to do a double-click.

It shouldn't be this hard. Please add an `OK` button?

The same UX problem applies to the `Save Game` / `Load Game` dialog.

![1](https://user-images.githubusercontent.com/755451/120193858-312ffa00-c21d-11eb-9504-8213d6e6ddfd.png)

![3](https://user-images.githubusercontent.com/755451/120194089-6d635a80-c21d-11eb-8113-27f80dac42a7.png)

**What version of CorsixTH are you using?**
0.65-beta2, Flathub

**Comment by lewri** [comment]
This will likely miss 0.65... but probably easy to implement in for 0.66

**Comment by lewri** [comment]
#568 talks specifically about the save menu. So just tagging it here.
