### ISSUE TITLE
Hint to people that there are other languages available, after a font selection

### ISSUE THREAD

**Issue by kparal** [CorsixTH/CorsixTH#1915]
**What feature or enhancement would you like to add?**
Currently languages not supported by the default font are way too hidden for most people (who don't read corsixth wiki etc). There's nothing in the GUI telling you there are some languages hidden:
![font selection](https://user-images.githubusercontent.com/755451/120196183-dba91c80-c21f-11eb-98ff-b97a2582f762.png)

I believe this could be easily improved. Ideas:
* Add a note into the tooltips (one above `Game Language`, the other shown in the screenshot). Something like:
  > Note: There are some languages hidden because the game font can't display them properly. Please select an appropriate font in the Folder menu and they will show up in this menu. Currently hidden languages are: Chinese, Czech, Russian, ...

  Create this tooltip dynamically to include the list of hidden languages, and display it only if there is no alternative font selected. If an alternate font is selected, replace it with this content:
  > Note: Some languages are displayed using an alternative font, because they are not supported by the default game font. If some characters are not displayed correctly, select a different font in the Folder menu.

* Add some small info/warning icon right next to the `Game Language` text, to make sure user moves their cursor over the icon and displays the tooltip.

* Alternatively, when the language drop-down is expanded, show a window with this hint next to the `Settings` window.

* Alternatively, add a new item into the language drop-down to the very end, called e.g. `More languages`. When the user clicks on it, ignore the selection (keep the previous language), but display a window/tooltip with the hint.

**What version of CorsixTH are you using?**
0.65-beta2, Flathub

**Comment by tobylane** [comment]
Could we add information like this to the tips window to be more noticeable? In English only, add to the set of tips one of the two quotes above, depending on whether a font has been chosen. When a user sets a font in game, the current tip is set to the second message.

**Comment by Alberth289346** [comment]
Why not have the full set of languages always, with the unavailable languages disabled? That's what is commonly used to list unavailable options. Could add a tool tip that the user needs to find an appropriate font to enable it.
