### ISSUE TITLE
Add Repository: Community Content

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1923]
I can't make repositories in CorsixTH but would like to start working on setting up a repo for fan-made levels and maps etc. after the forum was lost.

Name can be adjusted if desired. Also still working out what licensing to use (either CC0, MIT, or GPL3).

**Comment by lewri** [comment]
On reflection CC 4.0 BY SA may be more balanced 
https://creativecommons.org/licenses/by-sa/4.0/

**Comment by lewri** [comment]
Pulling from the IRC:
> Hedgewars has this approach - https://hedgewars.org/node/6943

But in my opinion an fully unmanaged license approach for a game community DLC is not a good one -- and potentially confusing for the consumer. I would still advocate for providing a uniform license on community submissions into this new repo (if users decide to release content outside the new repo that can be what they like).

**Comment by TheCycoONE** [comment]
Why? What problems do you see with allowing designers to pick their own license?

**Comment by lewri** [comment]
How about then making CC 4.0 BY SA the sane default (suggested/encouraged) but allow users to explicitly opt their own license (or no license)

**Comment by TheCycoONE** [comment]
What wesnoth does is allow any CC or GPL license. A license file must be in the bundle to be approved. I would make the example/default MIT.

**Comment by Alberth289346** [comment]
No license shouldn't be an option, as the only thing you can do with the file then is let it rot for eternity. We may want to block merging in such a case.

Please add an explanation what a license does, and why it's needed. Preferably also with a simple explanation of how the various licenses handle things, as "go read the text of the license if you want to know" is sufficient to never see them again.

Should there be some system in naming or bundling things too? Does it need author credits, high level description, screenshot (not sure it's useful), or text blurb ?

**Comment by TheCycoONE** [comment]
That's not true, under copyright you can grant someone the ability to use something for a particular purpose without giving up ownership, and no copyleft license is required for that. At least in my country uploading the content to a community server could imply that we have the right to make it available for download (though I would want to explicitly have the user check a box to that effect in the PR). Default copyright is 'all rights reserved', and that's perfectly fine - as Hedgewars does.

Wesnoth goes further and will only host Creative Commons or GPL content
OpenTTD requires an explicit license but doesn't restrict what that license is

I'm inclined not to enforce any form of licensing beyond granting us the ability to make the content freely available for download through a website or in game.

**Comment by lewri** [comment]
The MIT license is explicitly meant for software, not creative works.
GPL3 has enough extension to cover creative works derived from the software, but MIT does not.

This many be why https://github.com/CorsixTH/CorsixTH-Graphics is under Creative commons and not MIT (though the code around it to make it work can be MIT)

**Comment by lewri** [comment]
Proposed templates
**Wiki Page for licenses**
-----------------------
CorsixTH encourages its users to create and share custom levels/campaigns with members of the wider community. However, in order to host this we need to establish you're happy to share your content with us; and specify a license to release under (if any).

You might be confused about licenses and copyright. However, in simple terms a license expresses what a 3rd party can and cannot do with your content. A license is not required to share your files, but otherwise your expressed consent to share it with CorsixTH is. Below, we have selected a few popular choices with simple explanations and links to the full license. Please note, we will not be held responsible for any breach of license by 3rd parties except where a contributor falsely declares themselves as the author.

**No license (normal state) - full copyright.**
This means you maintain full exclusive rights to your content. It means that nobody can share, make derivative, modify, or use your works without permission. If you use this option, you will need to give us explicit permission to share your work with CorsixTH, and allow it to be used by players of CorsixTH. By default, you are not relinquished from responsibility of your work.
This license simply requires `Copyright (c) [YEAR] ]NAME]. All rights reserved.`

**CC0 - Creative Commons Zero (aka "No Rights Reserved")**
https://choosealicense.com/licenses/cc0-1.0/
This license means that you relinquish all rights of your work in regard to its usage. However, we will preserve you as the work author in our system. This license also relinquishes you of any responsibility for your work.

**MIT - Massachusetts Institute of Technology**
https://choosealicense.com/licenses/mit/
A very permission license similar to CC0 in terms of what is grants its users to do but preserves you as the copyright holder. CorsixTH uses this license. Derivative works do not need to mention the original author or use the same license. The license also relinquishes you of any responsibility for your work.

**CC BY 4.0 - Creative Commons Attribution 4.0 International**
https://choosealicense.com/licenses/cc-by-4.0/
Creative Commons offer various adaptations of their license (such as Non-Commercial use, No derivative works, Share-Alike), however this version simply permits all use of the work so long as Attribution (credit) to the original author is given (this includes derivative works). The license relinquishes you of any responsibility for your work.

**GPL 2.0 - GNU General Public License 2.0**
https://choosealicense.com/licenses/gpl-2.0/
A permissive license designed primarily for software but by extension can be made to cover 'add-on' content such as community levels/campaigns. The author must be given as part of the copyright. Derivative works must use the same license (or similar license), crediting the original author. This license relinquishes you of any responsibility for your work.

Other licenses are available for your work. You can view these on https://choosealicense.com/appendix/

**Q: What if I don't want to use my real name on a license?**
A: This is perfectly acceptable. You may use any name (including usernames/nicknames) for the license as long as it is a representation of yourself. Some users, in addition to their real name, may include their username too.

**Q: How do I know what license to pick?**
A: If you are unsure about a license, know that it is not a requirement to have one. However, in order to share your work you need to give us permission to do so. In likeness to CorsixTH, however we would recommend using the MIT License.

**Q: How should I include my license in my content submission?**
A: In your submission, include a `LICENSE.TXT` file with the relevant license in there. At the top of the file (or where noted in the license) include `Copyright (c) [YEAR] [NAME]`. Additionally, at the top of the file add the name of your Level or Campaign.

----------------

**Mock Form**

Please check through the following below and change `[ ]` to `[x]` where appropriate
- [ ] I am submitting a standalone level **OR**
- [ ] I am submitting a campaign

**Name of level or campaign**:
**(If relevant) Levels of campaign**:

**Required files:**
- [ ] I have included a `.map` file for my level (or multiple for each level of a campaign)
- [ ] I have included a `.level` file for my level (or multiple for each level of a campaign)
- [ ] I have included a `.campaign` file (if a campaign)

**Licenses: Check our `[license wiki]` page for information about licenses.**
- [ ] I have included a `LICENSE.TXT` file for my submission and chose the following license:
- - [ ] No License (full copyright), but permit my submission to be distributed through CorsixTH
- - [ ] CC0 1.0
- - [ ] MIT
- - [ ] CC BY 4.0
- - [ ] GPL 2.0
- - [ ] Other License, specify:

**Declarations:**
- [ ] I confirm that my submission is free of offensive (or otherwise sensitive) content
- [ ] I confirm I am happy to share and have distributed this content for use with CorsixTH

**Comment by TheCycoONE** [comment]
With heavy use of github action machinery to verify the above that looks fine.

I'm not sure that we should require map files, only that the level file points to a map file already in the repo (or possibly a hardcoded list of other known maps shipped with the game or CorsixTH), likewise with campaigns, just that the campaign file points to level files (and that every new level file points to a map).

I don't love that we currently dump all campaign levels, maps, and the campaign file itself in one directory; but so it goes.

**Comment by lewri** [comment]
You could possibly tweak our lookup code to include subdirectories. Then have each custom submission in its own folder.

For maps, can tweak stuff around to ask user to select an existing map file or submit their own.. Pretty sure most of our creators on Discord also make their own maps

**Comment by TheCycoONE** [comment]
We don't need them to select a map file, the level file MUST already point to one

**Comment by Alberth289346** [comment]
You ALWAYS have copyright, by the virtue that you created the content.
A license is not for copyright handling, it is for distribution handling.

Basically the law says if you want to copy something that is not yours you need to have explicit permission from person owning it. That means you need to ask the person explicitly and they must agree for each and every copy that is made.

A license is a universal agreement stated by the owner that such permissions may be assumed within the bounds of the license of course. With a license you can thus simply make copies as long as you comply with the license.

I have seen loads of work going lost because the original author left, and he didn't arrange a license. At that point you can look at the files being pretty and all that, but you cannot ever given them away to someone else.

**Comment by TheCycoONE** [comment]
Also licensing to us under our terms does not prevent the author from licensing to someone else under different terms.

I strongly advise saying that by contributing you agree that you are the author of the work and you license it by the terms of the CC BY 4.0 license <https://creativecommons.org/licenses/by/4.0/> and done.

**Comment by Alberth289346** [comment]
OpenTTD has an explicit question "( ) you are the author of this work" that needs to be answered.

You may also want a version number or time stamp, perhaps a description and/or a picture. Ie something that you can read or see to decide if a level is worth playing if you have a 30 `xyz.zip` files.

**Comment by TheCycoONE** [comment]
Here: https://github.com/CorsixTH/CommunityContent

Now accepting issue templates, readme content, and a base directory layout

**Comment by TheCycoONE** [comment]
Please open individual issues and PRs against the new repository unless it is relevant to CorsixTH itself, such as bundling formats.

**Comment by lewri** [comment]
Thanks, #2209 once I can polish it up should also assist in organisation of game assets for this too.
