### ISSUE TITLE
[Bug] Firing staff on multi-use object prevents them leaving

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1926]
#### Describe the issue
See save in #1924 along with PR #1925 
If you fire a member of staff at the start of treating a patient with a multi-use object (e.g. Inflator) they will fail to leave after treatment finishes.

#### Steps to Reproduce
1. Have a patient heading to inflator.

2. As soon as patient's head is popped, fire the doctor.

3. Watch doctor stay in room with exit sign.

#### Expected Behavior
Staff should leave when fired.

#### System Information
**CorsixTH Version:** 0.65-beta 1 (present in beta 2 and 0.64 too)

**Operating System:** Windows 10 (and arch linux, cyco's build)

**Theme Hospital Version:** GOG (and CD on cyco's build)

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by TheCycoONE** [comment]
Bumped priority since this renders rooms unusable.

**Comment by mugmuggy** [comment]
The fix appears fairly simple (might not be), looks like its common across many of the MultiUseObject instances. The IdleAction given in the commandEnteringPatient of the room, is not 'must_happen' - to initiate the multi use object. This action gets changed to must_happen in the MultiUseObject start.

When MultiUseObject ends, it restores the staff members IdleAction 'must_happen' back to the original value. In doing so, when setNextAction in the afterUse runs, it replaces the spawn action with the Meander as setNextAction queues up after the last must_happen (starting at the beginning of the queue), but as this spawn action is the second item in the queue, it's replaced.

**Comment by TheCycoONE** [comment]
I suspected something like that. Is there a relatively risk free hack that we could do in the short term to scan the list for the spawn action at that point; until the must_happen is tamed. Thinking something we could slide in to patch without risk.

**Comment by TheCycoONE** [comment]
I see, we could handle it in inflation in the callback (and other rooms) by checking staff.going_home. I think I'm ok with that approach as a hack - it's unlikely to break anything new.

**Comment by TheCycoONE** [comment]
maybe slightly less icky to notify humanoids that they are idle, and let them add the meander / despawn themselves.

**Comment by TheCycoONE** [comment]
Thinking slightly longer term - that's something we could call whenever the action queue emptied, and we wouldn't always need to prevent it from draining, moving one baby step towards a saner action system? @mugmuggy @Alberth289346 ?

(It's late so I might not be thinking straight)

**Comment by mugmuggy** [comment]
Setting going_home and checking that is relatively safe - patients are bad to do that with. The alternative that is in place on other rooms where this would be an issue, cardio/general diag:
```lua
    local cardio_after_use = --[[persistable:cardiogram_cardio_after_use]] function()
      if #staff.action_queue == 1 then
        staff:setNextAction(MeanderAction())
      else
        staff:finishAction(staff_idle)
      end
    end
```
Which only does it if not instructuted to do something else and thus should be relatively safe.
Slack Tounge, Inflation, Ultrascan and Fracture Clinic have the issue. I've confirmed all of these.

Its only an issue with fired staff when, the staff member gets the idle action, and is the 'use_with' argument and the single action in the action queue is not dealt with in the after_use callback. That is probably the safest fix for now.

I've had some thoughts on the better co-ordination of actions and Albert has too and I think my thoughts were something along the lines of a stack of action queues so a series of actions completes within one queue, then pop that off the stack and go back to the previous. Those action queues could then be a stack also, ie Walk to leave room, use_screen (dress), walk to screen, use machine, 'idle', walk to machine, use_screen(strip), walk to screen. This could be two or 3 sets of action sequences, so walk to leave room is pushed to the previous stack, once the screen is used for to strip, push its sequence of events.

If the walk to screen was interruptable for say epidemic evacution, then you could remove everything but the walk to leave room. Likewise the overall action stack is truncated and instead inserts a despawn action. So after walk to leave room executes, despawn starts. But that despawn action could be queued on the stack when the patient was spawned originally. So if a patient was spawned and there was no gp rooms, they could have an empty action queue whislt waiting for a room to be built, and then once times up, pop/interrupt the current action queue, and start the despawn. But interrupting is complicated.

**Comment by TheCycoONE** [comment]
Ok, as i said it was late. It looks like we should be able to just use the same style after_use like you mentioned above. Want to pr?

**Comment by lewri** [comment]
> Bumped priority since this renders rooms unusable.

This isn't strictly true. On my test the doctor just fails to leave, but doesn't get registered anymore as occupying the room. A new doctor just comes in by himself.
The old doctor is just forever stuck in the hospital though sadly.

**Comment by TheCycoONE** [comment]
Ah ok. That does sorta make it less critical. I'm not sure how the room calculations would go. Thanks

**Comment by lewri** [comment]
Priority downgraded so it can be put into 0.66
