### ISSUE TITLE
[Bug] Queue warnings error on crashed rooms

### ISSUE THREAD

**Issue by mugmuggy** [CorsixTH/CorsixTH#1927]
#### Describe the issue
#1807 introduced queue length warning, but in the instance of a crashed room, the queue is nil from Door:closeDoor.

#### Steps to Reproduce
1. Load save game from #1462 for example and wait til the 10th day of month

#### Save Game
See #1462

#### Expected Behavior
Should skip over crashed rooms

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt
```
Savegame version is 155 (Trunk), originally it was 155 (Trunk).
Error in timer handler: 
Lua\hospitals\player_hospital.lua:344: attempt to get length of a nil value (field 'queue')
stack traceback:
	Lua\hospitals\player_hospital.lua:344: in method 'warnForLongQueues'
	Lua\hospitals\player_hospital.lua:184: in method 'dailyAdviceChecks'
	Lua\hospitals\player_hospital.lua:374: in method 'onEndDay'
	Lua\world.lua:1043: in method 'onTick'
	Lua\app.lua:1131: in function <Lua\app.lua:1128>
	(...tail calls...)
	Lua\app.lua:1031: in function <Lua\app.lua:1026>

```

### Additional Info
@tobylane had mentioned in irc the 'fixed' line was failing
> The line "if room.door.queue and #room.door.queue then" causes an error saying attempt to get length of nil value. That sounds impossible, why did the first part return true?
> 
Maybe testing against the code before the fix or forgot to push an update or something else.

**Comment by TheCycoONE** [comment]
It does sound impossible. I would suggest that as the fix. Another one to push in - after a quiet couple weeks everything seems to be coming up now. :frowning:

**Comment by lewri** [comment]
Fixed
