### ISSUE TITLE
Stuck patient

### ISSUE THREAD

**Issue by TinusVL** [CorsixTH/CorsixTH#193]
A patient got stuck in front of a door of a GP's office.

I tried sending the patient home, reloading the save file below, editing the room, adding and removing staff to the room, but she didn't move.

A save where the patient is already stuck: 
https://www.dropbox.com/s/wtdu43pai2mbuy6/T7.sav
(She's in the GP's office near the entrance.)

**Comment by lewri** [comment]
Duplicate of #76

**Comment by lewri** [comment]
@mugmuggy you posted in #76 the issue was fixed there. As this appears to be a duplicate are you happy to close?

**Comment by mugmuggy** [comment]
I'd be in favour of just closing as we can't progress it now. No save, no log, its age.
