### ISSUE TITLE
Allow music control from main menu

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1935]
**What feature or enhancement would you like to add?**
In CorsixTH on first launch, music will play at full volume with no proper control to stop it until you start a game (only global audio). -- Plus 50% music vol is blazingly loud somehow
Instead, a toggle or setting should added to turn music on/off in main menu settings.

**How would this feature benefit the gameplay of CorsixTH?**
This would prevent blaring music for users on launch who don't want it.

**Was the feature in the original game?**
(Technically no, but music didn't happen in main menu on original)

**What version of CorsixTH are you using?**

0.65 beta-2

**Does this feature/enhancement relate to a current problem?**
No

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by lewri** [comment]
As pointed out, it may be better to remove playing music from the menus.
I suppose you could also add a Jukebox to the main menu too

**Comment by TheCycoONE** [comment]
There was some opposition on discord to that idea. I think the real takeaway here is to default the volume < 100%

**Comment by lewri** [comment]
Thanks, probably set music vol to 10% or 20% then.

Though I'm not sure how you really update the config.txt code

**Comment by TheCycoONE** [comment]
Update config_finder.lua to set the default. It doesn't affect people that have already launched the game.

**Comment by lewri** [comment]
@tobylane does your jukebox change to add it to settings now resolve this? (I think it does enough -- and config finder sets 50% already)

**Comment by tobylane** [comment]
Yes.
