### ISSUE TITLE
serialize_table can overflow

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1949]
It also sometimes seems to a bit unreliable. Even though we have some overflow protection we can still have it happen.
https://github.com/CorsixTH/CorsixTH/blob/6397bf051c7b5b6b69ee02d1f28d56ba30e5b183/CorsixTH/Lua/utility.lua#L317-L380

For a potential solution (if hackable into our current function) see here: https://stackoverflow.com/a/42062321

**Comment by TheCycoONE** [comment]
Overflow what exactly?

**Comment by TheCycoONE** [comment]
Based on the discussion we've had in the channel I think this can be closed. The suspected infinite loop is based on instruction count not stack depth, and there's no reasonable use of this function I can think of where it would be an issue. max_depth is also a mitigation for debugging.
