### ISSUE TITLE
Intro movies incompatible with THX Spatial Audio

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1956]
On a new headset I got it comes with THX Spatial Audio enabled. However, it looks like it gets globally enabled when on (not app specific).

When it is on CorsixTH's intro music becomes insanely distorted and no idea why. The MIDI music in the game is fine though.
Turning THX off and relaunching the game appears to fix it, but only until it is turned back on again.
Happening across 0.64 and 0.65

**Comment by lewri** [comment]
(Likely upstream, and guessing likely unfixable)

**Comment by lewri** [comment]
On some checking in the original this could potentially be resolved our side (maybe a SDL2 thing?)
In the original via Dosbox I don't get the horrible choppy helicopter notices on intro video.

**Comment by TheCycoONE** [comment]
Have you tested since the movie cleanup (latest git) - I don't think it would be fixed but there were some audio processing changes.

More likely there's some issues with the number of channels - if anyone has a 5.1 or 7.1 system to test on - I don't.

**Comment by lewri** [comment]
Movie cleanup has made the sound worse (like a plane overhead full of bees)

THX Spatial is a virtual surround rather than real surround though.
