### ISSUE TITLE
SDL2: cursor sticks when moving windows

### ISSUE THREAD

**Issue by alanwoolley** [CorsixTH/CorsixTH#196]
When moving the windows on the main menu, the cursor sticks in the position it was when you started dragging. The window still moves, but the cursor doesn't update.

This only happens on the SDL2 branch. If I had to take a stab at it, I'd guess 8913618a is to blame. @lego3 can you take a look at this?

**Comment by Lego3** [comment]
The pull request fixing this issue has been merged. I'll close it.
