### ISSUE TITLE
MSVC build warnings

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1961]
See below output messages. I'll let you work out if any are relevant or need correction

| Description | File name | Line |Column | Project|
|-------------|-----------|--------|-------|---------|
| Tag 'TCL_SUBST' at line 229 of file 'C:/projects/corsixth/DoxyGen/animview.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_animview |
| Tag 'TCL_SUBST' at line 229 of file 'C:/projects/corsixth/DoxyGen/leveledit.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_leveledit |
| 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details. | CorsixTH\Src\iso_fs.cpp | 374 | 18 | CorsixTH_lib |
| Tag 'COLS_IN_ALPHA_INDEX' at line 986 of file 'C:/projects/corsixth/DoxyGen/animview.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_animview |
| Tag 'TCL_SUBST' at line 229 of file 'C:/projects/corsixth/DoxyGen/corsixth_engine.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_corsixth_engine|
| Tag 'COLS_IN_ALPHA_INDEX' at line 986 of file 'C:/projects/corsixth/DoxyGen/corsixth_engine.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_corsixth_engine |
Tag 'COLS_IN_ALPHA_INDEX' at line 986 of file 'C:/projects/corsixth/DoxyGen/leveledit.doxygen' has become obsolete. | CUSTOMBUILD | | | doc_leveledit |

**Comment by TheCycoONE** [comment]
There are a lot of warnings for deprecated doxygen settings - I've noticed that myself. We haven't really defined a strategy on supported doxygen versions and it's hard to know what's safe to change without it (presumably these aren't obsolete in some versions).

**Comment by TheCycoONE** [comment]
The other warning about `fopen_s` is not valid, it's a Microsoft extension until C11/C++17.

**Comment by lewri** [comment]
@tobylane re the PR: I'm not sure if simply removing the items is the right solution. Shouldn't it be replaced with something not deprecated? Unless you know if hasn't broken anything in doxygen.

**Comment by tobylane** [comment]
It's not a part of doxygen we use. We could massively shorten the files to the little we use (these sources files, that format, that footer template).

**Comment by Alberth289346** [comment]
Most settings are default and only listed in the file so you can change them. You should be able to remove those without problems.
