### ISSUE TITLE
[Bug] Money icon's text gets distorted

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#1966]
#### Describe the issue
If not playing at normal zoom (100%), the money inside the dollar bill when someone pays for services gets distorted.
It is not related to direct zoom.

#### Steps to Reproduce
1. Have a patient use a room with some zoom

2. Watch the dollar bill get distorted.

#### Expected Behavior
We want to keep the text crisp regardlelss of zoom.

#### System Information
**CorsixTH Version:** Trunk (Appveyor 585)

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
Normal zoom
![image](https://user-images.githubusercontent.com/20030128/123458062-81ac3480-d5dc-11eb-9f3e-fa78513200c7.png)

Zoom in/out
![image](https://user-images.githubusercontent.com/20030128/123458088-8a046f80-d5dc-11eb-90ad-de5d2069a2d0.png)

**Comment by flackr** [comment]
The issue here is that the narrow highly transparent font sprites do not preserve font quality well when scaled. As such, we should draw the money icon at 1x scale into a target texture and then scale the entire money icon sprite as a single unit.

**Comment by flackr** [comment]
The other (better) option which @TheCycoONE mentioned on IRC is that we could use vector fonts. This would result in an even better quality and also likely be more efficient than drawing to an intermediate texture. @TheCycoONE would this mean using SDL_ttf?

**Comment by TheCycoONE** [comment]
We already have vector font support using freetype directly see th_gfx_font.cpp.

**Comment by flackr** [comment]
So as I understand it, freetype works by [rendering glyphs onto a canvas](https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx_font.cpp#L795) which is then [copied to the screen](https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx_font.cpp#L816). We just need to make th_gfx_font aware of the scale factor so that it can draw to the final size?

Is this rendering code used for all of the fonts or do we use a mix of freetype and bitmap?

**Comment by Alberth289346** [comment]
The original game has a sprite font, freetype is mostly used for languages not supported in the original programs.

**Comment by flackr** [comment]
I'm guessing then the ideal outcome is that we make freetype able to render scaled text pixel perfect and use for cases where we know we will be scaling it - i.e. the map icons. Skimming the code this looks like map_text_overlay?

**Comment by flackr** [comment]
@TheCycoONE tracked down the money icon rendering to world.lua: `World:newFloatingDollarSign`. This constructs a spriteList / sprite_render_list containing sprites for the individual digits.

My plan is the following:
Add an attribute to sprite_render_list to use an intermediate texture.
In sprite_render_list::draw, if this flag is set, it will call a special functions which calls through to render_target to begin rendering into an intermediate texture large enough to contain all of the sprites.
In sprite_render_list::draw, after all of the sprites are drawn, another function will be called to commit (i.e. copy) the rendered texture to the scaled screen.

These functions to start and commit the intermediate sprite can become no-ops if the scale factor is 1 or target textures are not supported.

Longer term, we could consider supporting and using freetype fonts directly, however this is likely going to be a larger, riskier change.
