### ISSUE TITLE
[Bug] allow_user_actions_while_paused config option is always clobbered by default value

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#1993]
#### Describe the issue

https://github.com/CorsixTH/CorsixTH/blob/ac36518b86b335e6a8be6385074296aaf901a446/CorsixTH/Lua/config_finder.lua#L332

Should read `config_values` not `config_defaults`

**Comment by Tomracer** [comment]
I'd like to take this Issue
