### ISSUE TITLE
Map Editor

### ISSUE THREAD

**Issue by DS1992ds** [CorsixTH/CorsixTH#1995]
i have downloaded the latest version of Corsix TH 

after creating a new map and saving it, i am unable to access this map in anyway to play it

can anyone help

**Comment by lewri** [comment]
Your map needs to be tied to a level file to be playable usually. What's your operating system and we can tell you where it will be located on the hard drive.

**Comment by DS1992ds** [comment]
Thank you,

Windows 10 pro
________________________________

**Comment by lewri** [comment]
It should be in ``C:\Users\<user>\AppData\Roamimg\CorsixTH``

Should be saved to a folder there.

**Comment by DS1992ds** [comment]
Ok so what do I do with this file now
________________________________

**Comment by lewri** [comment]
See here, you need to attach it to a .level file. Just copy the example.level and edit it (it's a plain text file)
https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels#creating-custom-levels

**Comment by lewri** [comment]
Sorry, example.level may be at ``C:\Program Files\CorsixTH\Levels``

**Comment by TheCycoONE** [comment]
Please join us for help on the chat linked to the readme.
