### ISSUE TITLE
Cannot save game (possibly not a CorsixTH issue per se)

### ISSUE THREAD

**Issue by MadeInDutch** [CorsixTH/CorsixTH#1996]
So I've been trying to play CorsixTH on my new laptop for a while. But whenever I try to save my game, it tells me it's saved somewhere else. Reason? Permission denied. Now, I've tried relaxing the permissions to the folder in Roaming already, but that didn't work. I really wanna play Theme Hospital again, does anyone know how to solve this issue? Thanks in advance.

**Comment by lewri** [comment]
We have some fallback directories built in if there's a problem saving. It'd be that OSes temp directory.
https://github.com/CorsixTH/CorsixTH/blob/ac36518b86b335e6a8be6385074296aaf901a446/CorsixTH/Lua/app.lua#L908-L922

What version of CorsixTH are you using? And OS.
@tobylane any ideas?

**Comment by TheCycoONE** [comment]
It would be 0.65, we didn't fallback before.
We need to know your OS to help. Also the install method.

**Comment by MadeInDutch** [comment]
I use Windows 10. I simply installed Theme Hospital off GOG.com, then installed CorsixTH. Just a regular install, worked fine on my older laptop.

**Comment by lewri** [comment]
Do you have any antivirus software other than Windows Defender? We had a report that 360 Total Security was false flagging the game.

**Comment by MadeInDutch** [comment]
I have ESET, although I doubt it's the culprit. I had ESET on my old laptop too, and that worked just fine.

**Comment by TheCycoONE** [comment]
On Windows 10 save games are written to the `Saves` directory in the same location as the `config.txt`. The installer gives you two options, either store everything together with the game files (like a portable or a Win9x install) or store config, saves, logs, etc. in %APPDATA%.

If your CorsixTH directory has a `config.path.txt` file in it, that will override the location. That's what the installer uses to indicate to put all files in the install directory.

If you have no such file then then game is attempting to save in `%APPDIR%/CorsixTH` You might verify that environment variable (APPDIR) exists, and the directory it points to is writable.

**Comment by MadeInDutch** [comment]
So since my saves are in %APPDATA%, if I just reinstall CorsixTH with the saves in Program Files, I might just not have this problem?

**Comment by MadeInDutch** [comment]
Well that didn't work.

**Comment by MadeInDutch** [comment]
![corsixth error](https://user-images.githubusercontent.com/67276601/124939982-de124980-e009-11eb-9357-f7b137d6d8ac.png)
this is the error I get btw (despite the fact that my saves are in program files now)

**Comment by lewri** [comment]
Can you run as Administrator and see if the error still happens.

**Comment by lewri** [comment]
You should be the owner of your own saves too... And  you should have permissions to write to that folder as your user.
![image](https://user-images.githubusercontent.com/20030128/124959318-fe92d180-e012-11eb-94d1-2e93fe94be68.png)

**Comment by MadeInDutch** [comment]
> 
> 
> You should be the owner of your own saves too... And you should have permissions to write to that folder as your user.
> ![image](https://user-images.githubusercontent.com/20030128/124959421-15d1bf00-e013-11eb-9de6-ccfd8739d7dd.png)

I was already.

**Comment by MadeInDutch** [comment]
But the admin thing seems to have worked. Thank you.

**Comment by MadeInDutch** [comment]
I'll reopen this if it turns out to not work, but it does for now.

**Comment by lewri** [comment]
I did try to replicate this again on a limited/restricted device and user account. Still no errors. I'm going to guess it's Windows related sadly, and not our bug.
