### ISSUE TITLE
[Bug] AllCuresTrophy crashes existing saves

### ISSUE THREAD

**Issue by MadeInDutch** [CorsixTH/CorsixTH#2004]
#### The issue
While playing the first hospital, having reached all my goals (10 cured patients and a rating above 200), time freezes on the 31st of December, right before I get the letter to move on to the second hospital. I can still build and place things, but the people are frozen, time doesn't progress and I don't get my letter to go to the next level. Moreover, if I quit out onto the main menu, my cursor freezes in place. And the only way to visibly move it is to click somewhere else.

#### Steps to Reproduce
1. Load the save file attached.

2. See that it's frozen in time.

3. Quit out onto the main menu and observe that the cursor is stuck.

#### Save Game
[CorsixTH save.zip](https://github.com/CorsixTH/CorsixTH/files/6796561/CorsixTH.save.zip)

#### Expected Behavior
I expected the letter to move on to the next hospital, or at least that the game would continue playing.

#### System Information
**CorsixTH Version:** 0.65

**Operating System:** Windows 10

**Theme Hospital Version:** GOG.com

#### Gamelog.txt
Gamelog.txt comes within the .zip file included.

### Additional Info
I don't know if this is related, but my (local) account name on my laptop has a Romanian ș in it, and the Users folder has the Turkish ş in it. This has caused problems for me in the past (I still can't play OpenLoco on this account, and I've already run into countless issues with CorsixTH). It might also be my laptop that's bungling up something. I never had the same problems with CorsixTH on my older laptop (or any program not working because of my username), despite it having the same account name. Thought you might wanna know.

**Comment by lewri** [comment]
Pasting gamelog below for ease
```
Created game with savegame version 138.
Savegame changed from 138 (v0.64) to 156 (v0.65). The save was created using 138 (v0.64).
Savegame version is 156 (v0.65), originally it was 138 (v0.64).
Savegame version is 156 (v0.65), originally it was 138 (v0.64).
Error in timer handler: 
Lua\dialogs/fullscreen\annual_report.lua:211: attempt to perform arithmetic on a nil value (field 'TrophyAllCuredBonus')
stack traceback:
	Lua\dialogs/fullscreen\annual_report.lua:211: in method 'checkTrophiesAndAwards'
	Lua\dialogs/fullscreen\annual_report.lua:132: in local 'constructor'
	Lua\class.lua:74: in global 'UIAnnualReport'
	Lua\world.lua:1059: in method 'onTick'
	Lua\app.lua:1134: in function <Lua\app.lua:1131>
	(...tail calls...)
	Lua\app.lua:1034: in function <Lua\app.lua:1029>
Savegame version is 156 (v0.65), originally it was 138 (v0.64).
Savegame version is 156 (v0.65), originally it was 138 (v0.64).
Error in timer handler: 
Lua\dialogs/fullscreen\annual_report.lua:211: attempt to perform arithmetic on a nil value (field 'TrophyAllCuredBonus')
stack traceback:
	Lua\dialogs/fullscreen\annual_report.lua:211: in method 'checkTrophiesAndAwards'
	Lua\dialogs/fullscreen\annual_report.lua:132: in local 'constructor'
	Lua\class.lua:74: in global 'UIAnnualReport'
	Lua\world.lua:1059: in method 'onTick'
	Lua\app.lua:1134: in function <Lua\app.lua:1131>
	(...tail calls...)
	Lua\app.lua:1034: in function <Lua\app.lua:1029>
```

**Comment by tobylane** [comment]
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/dialogs/fullscreen/annual_report.lua#L211

I didn't add the base config changes to an afterload. FWIW this save version is 138 and my changes were during 140. Where would an afterload for this go?

**Comment by lewri** [comment]
You can't. But I also managed to fix this locally.

This is likely quite a critical bug... at least for level 1.

**Comment by lewri** [comment]
@MadeInDutch if you want to fix you save replace the file ``map.lua`` in ``C:\Program Files\CorsixTH\Lua`` with the attached. Launch your game and load the save. Then save it again if the Annual Report pops up.
After that, put the original ``map.lua`` file back.
[map.zip](https://github.com/CorsixTH/CorsixTH/files/6796651/map.zip)

We will work out if we need to backport the fix.

**Comment by MadeInDutch** [comment]
Heyyy it worked. I'm on the second level now.

**Comment by MadeInDutch** [comment]
So I'm gonna close this unless and until a similar bug happens.

**Comment by lewri** [comment]
Don't close, it is an important bug

**Comment by MadeInDutch** [comment]
oh ok
