### ISSUE TITLE
[Bug] update check never sees a new version

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#2011]
#### Describe the issue
The update check does not find new versions

#### Steps to Reproduce
1. Launch CorsixTH 0.64 (or any other version since 0.60)

2. Observe there are no new updates reported

#### Expected Behavior
Update check should notify the user of 0.65.

#### System Information
**CorsixTH Version:** *0.64*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *Any*

### Additional Info
getVersion since 0.60 has returned a string like 'v0.60' matching the tag name. The update check takes 3 fields and concatenates them into a string <major>.<minor><revision> and then does a string comparison. This string is always less than the v<version> returned by getVersion so it is not considered an update.

Note: When this is fixed, we should also plan to support 3 part versions like 0.65.1.

**Comment by tobylane** [comment]
In App:getVersion there's a letter v in the version _number_, which prevents the check in checkForUpdates from doing a number comparison. Is it better to take the v out in getVersion, or have it stripped in checkForUpdates?

0.65.1 isn't a number, so we would need a different comparison such as semantical versioning.

**Comment by TheCycoONE** [comment]
Yes, what i was picturing was adding a version table with it's own metamethods for comparison and string conversion.

**Comment by lewri** [comment]
Should this be moved to `P4 Low` now as an interim solution is now present

**Comment by TheCycoONE** [comment]
Sure
