### ISSUE TITLE
Show queued patients while hovering on door

### ISSUE THREAD

**Issue by xZise** [CorsixTH/CorsixTH#2016]
**What feature or enhancement would you like to add?**
While hovering over the door the same "queue"-symbol should be shown when hovering over the room itself.

**How would this feature benefit the gameplay of CorsixTH?**
When hovering over the door the infobox at the bottom shows the number of queued patients but not the "queued"-symbol, but while hovering over the room it is the other way around. So you either know how many are queued or know who is queued.

**Was the feature in the original game?**
Yes

**What version of CorsixTH are you using?**
0.65

![Hovering over room](https://user-images.githubusercontent.com/417478/126034200-e0732652-ca21-4be1-b882-b109300f4230.png)
![Hovering over door](https://user-images.githubusercontent.com/417478/126034176-75b01627-f1b6-4f02-9194-57ea276e360f.png)
![Hovering over door in Theme Hospital](https://user-images.githubusercontent.com/417478/126034124-e7b639b9-39af-413d-a25d-882fd5bc6094.png)

**Comment by mugmuggy** [comment]
Just FYI, this wasn't a feature in the original, the example given from dosbox, follows the same as Corsix behaviour. The hit test for the mouse over is on the floor tile. Though its convenient, the hit test probably becomes a little more complex, as the animations changes and moves.
