### ISSUE TITLE
CMake/FindLua.cmake doesn't find lua when lua5.2 is also installed

### ISSUE THREAD

**Issue by timdiels** [CorsixTH/CorsixTH#202]
On ArchLinux when both (lua5.1 or luajit) and lua5.2 are installed CMake/FindLua.cmake sets the include dir to that of lua5.2 instead of the correct one.

This is because FindPath uses CMAKE_SYSTEM_PREFIX_PATH before checking the given PATHS

Suggested fix: Add NO_CMAKE_SYSTEM_PATH to find_path at line 33 in https://github.com/timdiels/CorsixTH/blob/master/CMake/FindLua.cmake

I noted a workaround for the mean time here: https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile#wiki-compiling-on-linux

**Comment by TheCycoONE** [comment]
Duplicate of #139
