### ISSUE TITLE
[Bug] Using drink machine is not queued

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#2020]
#### Describe the issue
When many patients are thirsty and you build a drinks machine, it is being used by several patients at once

#### Steps to Reproduce
1. *Load save game attached to this ticket*
[many.sav.gz](https://github.com/CorsixTH/CorsixTH/files/6836250/many.sav.gz)

2. Buy and place a drinks machine.

3. Observe lots of floating dollar bills.
![Screenshot from 2021-07-18 14-49-32](https://user-images.githubusercontent.com/3254232/126067756-a4657570-3e1a-4eb9-8019-9f07a98e36c9.png)

Version: d85c5351

**Comment by mugmuggy** [comment]
That is by design, the original doesn't limit it to a user at a time either.

**Comment by lewri** [comment]
Yeah I remember in original. Plop a drinks machine down, they all scurry at once like seagulls

**Comment by Alberth289346** [comment]
Seems fair enough.

**Comment by TheCycoONE** [comment]
Question is do we want to preserve original behaviour or make the drink machine queue for more 'realism'. I'm fine with either.

**Comment by lewri** [comment]
> 
> 
> Question is do we want to preserve original behaviour or make the drink machine queue for more 'realism'. I'm fine with either.

If you have the realism, I would also make the patients have logic about it (not all piling to one machine if 3 are next to each other)

**Comment by Alberth289346** [comment]
Drinks machine isn't used enough normally to ever have a queue at all, in my experience. It's 70-80% idle mostly.
Perhaps if you have a really busy hospital, but even then it's likely not worth it.

**Comment by TheCycoONE** [comment]
we have queue balancing already for the rooms. But it sounds like no one really wants this, and we can close won't fix?
