### ISSUE TITLE
Replace corsixth.com with static site

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#2022]
**What feature or enhancement would you like to add?**
We would like to replace the existing WordPress based corsixth.com site with a static one hosted on GitHub pages. 
In particular we would like to preserve all of links in the header bar, and the content of the media tab.

As a first pass it might be good just to copy the entire WordPress generated site in (without WordPress itself).

**Comment by rmnvgr** [comment]
I had time to make some progress for the front page, let me know what you think:

![](https://user-images.githubusercontent.com/66537460/126390216-e7209c80-e0a0-471d-8e34-1faa295db1b1.png)

I was thinking of automatically pulling the news from the releases notes.

**Comment by lewri** [comment]
Lgtm.
Maybe we should pull Reddit, matrix, and discord linksunder a submenu. 
What is the video portion going to show?

**Comment by lewri** [comment]
Also if this lives in the GitHub.io should it also have some way of getting to the luadoc/doxygen pages?

**Comment by rmnvgr** [comment]
> Lgtm.
> Maybe we should pull Reddit, matrix, and discord linksunder a submenu.
> What is the video portion going to show?

**Comment by TheCycoONE** [comment]
New site looks really good. Thanks @rmnvgr 

Facebook and Twitter are still viable, I agree they could go in.
Video idea is pretty neat, thanks for that.

I agree the luadoc/doxygen pages are too dev centric - they could be linked from the wiki (they also live in the project page, vs this is in the organization page).

**Comment by tobylane** [comment]
[Big5.sav.zip](https://github.com/CorsixTH/CorsixTH/files/6907357/Big5.sav.zip)
This is an L12 hospital with about 90 patients and staff. What variation should be shown in the movies?

**Comment by rmnvgr** [comment]
I got this error while loading the save: `Error while loading game: /app/share/corsix-th/Lua/persistance.lua:268: sync fail after 5513 objects (168353 bytes)`, what could be causing it?

> What variation should be shown in the movies?

I was planning on showing close-up interactions between staff and patients, building some rooms, and a few general views of crowded hospitals.

**Comment by lewri** [comment]
> I got this error while loading the save: `Error while loading game: /app/share/corsix-th/Lua/persistance.lua:268: sync fail after 5513 objects (168353 bytes)`, what could be causing it?

Try it in 0.64, could be in a limbo of when for a while master broke for a while on loading saves.

**Comment by TheCycoONE** [comment]
The save opens fine for me in latest master. That is the trend with this issue though. Looking through the issue history we've had a small number of reports of `sync fail after`, and so far no one else is able to reproduce (and a new build has made the problem go away for others).

**Comment by TheCycoONE** [comment]
To be clear on another point, a bug in the lua code cannot cause this error. It indicates an issue with the save format itself, i.e. not encountering a sync marker between objects. It's possible that a broken userdata persist/depersist function could cause it, and it's also possible that a lua compiled with different types might.

**Comment by rmnvgr** [comment]
Alright I've been able to open it using master, thank you!

**Comment by rmnvgr** [comment]
I've added a Download page to not clutter the home page, what do you think?

![Download page](https://user-images.githubusercontent.com/66537460/127983229-a4c8ff88-56a8-4ead-afec-e084be2da170.png)

**Comment by rmnvgr** [comment]
Also right now the historical videos are hosted on YouTube, do you want to keep them there or host them on the website?

**Comment by TheCycoONE** [comment]
I don't have a problem with continuing to host them on YouTube. GitHub does have bandwidth and space restrictions, though we could proxy with cloudflare, YT is still attractive for video.

**Comment by rmnvgr** [comment]
Ah I wasn't aware of those restrictions. [According to the docs](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#usage-limits) they seem quite high though.

I only need to record the gameplay footage for the home page and write the action to auto-update the site on new releases, then it will be good to go!

**Comment by TheCycoONE** [comment]
[Spaces_Level_5.zip](https://github.com/CorsixTH/CorsixTH/files/6926927/Spaces_Level_5.zip)

Save from a custom campaign, submitted by Graham

**Comment by rmnvgr** [comment]
Thank you! Here's the video I made:


https://user-images.githubusercontent.com/66537460/128202866-eb6090e5-c564-4bf4-bbfa-7eb791e228b1.mp4

**Comment by TheCycoONE** [comment]
Sneaky new master features in there 😉 

Looks great!

**Comment by Alberth289346** [comment]
Sneaky new master features caused the sync error perhaps?

**Comment by TheCycoONE** [comment]
Great!, I will move the domain.

**Comment by Alberth289346** [comment]
Had a look at the new `corsixth.com` site, and really like what you did there, it's great!
Looks good, nicely organized, easy to find what you need.

I have two spots where there may be room for improvement.

- The "wiki" link at the top jumps to the wiki root page (unsurprisingly), but as this is a user oriented site, maybe you want to change that to the "Game Guide" at the wiki, ie the manual of the game. The Hotkeys page is likely also nice, and perhaps the FAQ. Not sure if having additional entries at the main page is good. Alternatively, maybe those pages can be added to the game guide?
- Not sure what the value is of all the old videos. Likely we want to keep them, but does it make sense to show eg version 0.10 to a user of 0.65.1 ? Perhaps hide them a bit in "older media" or something?

**Comment by Alberth289346** [comment]
Maybe make "getting started" at the wiki available near download?

**Comment by rmnvgr** [comment]
Thank you!

> * The "wiki" link at the top jumps to the wiki root page (unsurprisingly), but as this is a user oriented site, maybe you want to change that to the "Game Guide" at the wiki, ie the manual of the game. The Hotkeys page is likely also nice, and perhaps the FAQ. Not sure if having additional entries at the main page is good. Alternatively, maybe those pages can be added to the game guide?

The old site pointed to the same page so I just did the same. I actually think this is fine because the wiki root has a menu with the different pages nicely sorted by target audience. It's just a shame this menu only appears on the root page.

> * Not sure what the value is of all the old videos. Likely we want to keep them, but does it make sense to show eg version 0.10 to a user of 0.65.1 ? Perhaps hide them a bit in "older media" or something?

I agree this could be improved, again I simply copied the existing page. Having more screenshots would be nice, and maybe then move the old videos to the wiki?
