### ISSUE TITLE
Colorblind Modes

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2023]
**What feature or enhancement would you like to add?**
CorsixTH is currently developed to provide optimal colours for normal vision. We are not in a position of compensating to colour-blindness conditions. However, we do try to use textual indicators along with colours to re-enforce the fact.

**How would this feature benefit the gameplay of CorsixTH?**
Allows for a better gameplay experience for colour-blind people.

**Was the feature in the original game?**
No

**What version of CorsixTH are you using?**
 0.65

**Does this feature/enhancement relate to a current problem?**
No

**Additional information**
Most commonly we likely do not provide support for red/green colour-blindness. So having one "Alternative colour" option could suffice.

**Comment by TheCycoONE** [comment]
Is there anywhere in particular you were thinking? We do very little based on color in my estimation, and the heat maps already have alternatives. Most of the UI is white on gray or white on purple with light and dark purple to indicate toggle state.

**Comment by lewri** [comment]
I have not made a full analysis yet, not sought input from someone who is colourblind. So for now this is just for reference.
