### ISSUE TITLE
Level advance when owing a loan

### ISSUE THREAD

**Issue by andreyjardim** [CorsixTH/CorsixTH#2027]
On
corsix-th-0.64-1.fc32.x86_64

Even when owing a loan, I received an invitation to advance level. This doesn't happend on the original ThemeHospital game, which requires to pay all debts before this.

**Comment by TheCycoONE** [comment]
We subtract the value of your loan for any balance condition:
```
      -- Special case for balance, subtract any loans!
      if goal.name == "balance" then
        current_value = current_value - hospital.loan
      end
```
I'm not sure what value there is in otherwise blocking the win.

**Comment by andreyjardim** [comment]
I understand, but in the original game the player must remember he owes a loan to advance. If it is already thought, we can close this thread, but it could be cool to keep this behavior.

**Comment by lewri** [comment]
Just to update the issue. Following discussion on irc decision was made to block level advance with a loan.
The advisor gives though messages anyway to remind you to pay it off...

**Comment by Alberth289346** [comment]
We may want to have an additional message when having a loan blocks ending the level, assuming it's not there already.
