### ISSUE TITLE
[Bug] Level 7 no patients visit opened hospital

### ISSUE THREAD

**Issue by andersand** [CorsixTH/CorsixTH#2030]
#### Describe the issue
In level 7 - hospital opens (in march) but no patients seem to come by since opening.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Run full speed

3. Game failed by new year due to no funds.

#### Save Game

[level 7-1.zip](https://github.com/CorsixTH/CorsixTH/files/6925459/level.7-1.zip)

#### Expected Behavior
Patients come visit the hospital shortly after it's opening.

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.65.1

**Operating System:** *e.g. Windows 10*
Windows 10

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by mugmuggy** [comment]
Need a receptionist

**Comment by andersand** [comment]
Oh, looks like I forgot. Maybe the "helpful doctor" that pops up could give me a clue if I press the "open hospital" button, and there are 0 receptionists? Closing as not bug.

**Comment by TheCycoONE** [comment]
There are warnings about this, but you may not have left it long enough to see them?
