### ISSUE TITLE
[Bug] Error in win criteria view (reputation)

### ISSUE THREAD

**Issue by andersand** [CorsixTH/CorsixTH#2031]
#### Describe the issue

Error in win criteria view (reputation) as shown in screenshot.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2.

3.

#### Save Game

[level 7-wincriteria.zip](https://github.com/CorsixTH/CorsixTH/files/6926664/level.7-wincriteria.zip)

#### System Information
**CorsixTH Version:** *e.g. 0.50 or 7d886f35ca*
0.65.1

**Operating System:** *e.g. Windows 10*
Win 10

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*
Gog.com

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

![image](https://user-images.githubusercontent.com/621686/128075554-c6caf80f-3e00-491c-bd2a-cddb765b5f88.png)

**Comment by andersand** [comment]
This "fixed" itself, it went back to normal (476/600) after this error occurred

**Comment by lewri** [comment]
I'm guessing because 474 is closer to 350 (lose criteria) than 600 (win criteria). Technically where your rep is >475 it should be green.

**Comment by TheCycoONE** [comment]
I don't see the error?

**Comment by TheCycoONE** [comment]
To be clear, the criteria has a boundary value, below which it warns you about losing rather than advising you on winning:
```lua
      if cur_value < world_goals[crit_name].boundary then
        world_goals[crit_name].red = true
        res_value = world_goals[crit_name].lose_value
        -- TODO: Make the ugly workaround for the special case "percentage_killed" better
        if crit_name:find("killed") then
          res_value = nil
          world_goals[crit_name].visible = false
        end
     end
      ```

**Comment by TheCycoONE** [comment]
That said the 65.0 is a bug - if we want to make this issue about that.

**Comment by andersand** [comment]
You're right, my bad. I guess the fact it switches quite subtly between quite tall green bar (win criteria) to very low red bar (lose criteria) was not clear / intuitive to me.

**Comment by andersand** [comment]
I got an actual error with the win criteria for reputation, see screenshot
![image](https://user-images.githubusercontent.com/621686/128639669-07f4b7a9-a41c-4fe3-bb48-7cc5ed8f58d4.png)

**Comment by andersand** [comment]
The reputation is actually 573, but the tooltip as shown on the screenshot says it's currently 2450 which, I don't even know if that's possible. Plus it says it should not be less than -500 (I assume it doesn't make sense with negative reputation but don't know for sure). Anyway it's on level 9 and these are not the win nor lose criterias as far as I know.

Please see attached savegame and consider repoening the issue.
[level 9-err.zip](https://github.com/CorsixTH/CorsixTH/files/6951168/level.9-err.zip)
