### ISSUE TITLE
Handymen fixing machinery dynamic threshold

### ISSUE THREAD

**Issue by andersand** [CorsixTH/CorsixTH#2036]
**What feature or enhancement would you like to add?**
A calculated fixing threshold, for when handymen are tasked to repair machinery, depending on you workforce's allocation to fixing vs the amount of machinery installed.

As far as I can tell,  the way it is implemented, probably intentionally as in the OG, handymen will not go and fix unless "remaining uses" < 50% of "strength" of a machinery? That seems to be what causes this problem (in larger, busy hospitals) : I constantly have to go through all machinery (by right clicking the machinery names)  and for each that has some wear, click the "page handyman to fix" button to make sure they are fixed in time. The problem is lessened if you make sure to research on machinery improvements and remember to replace machinery frequently. In hospitals that are more prone to earthquakes this is especially problematic as you need to do this quite often to avoid them from blowing up. 

**How would this feature benefit the gameplay of CorsixTH?**
This would make the game more enjoyable as you can focus more on the fun stuff and less on such chores. 
If this is implemented the way i hope for, hiring more/enough handymen should make it unlikely to see machinery blow up, leaving the space where the room is unusable. 

If you think it may make the game too easy, I'd say it won't be overpowered since you need to invest to get this advantage (pay all the handymen).

**Was the feature in the original game?**
I don't know, don't think so.

**What version of CorsixTH are you using?**

0.65.1

**Does this feature/enhancement relate to a current problem?**
Well depends who you ask I suppose. I'd call it a minor problem that the game can have too much micromanagement for some players taste. Don't get me wrong, most management aspects of this game are good; for instance it can be fun to keep track of staff wages, since you have to consider if they're worth keeping for the pay they demand. It's fun because you have to use your brain, right? Remembering to do this kind of "clicking chores" is not exactly my idea of fun in games.

**Additional information**
![image](https://user-images.githubusercontent.com/621686/128422842-e36f0c08-537c-4615-9220-588fb82dfca2.png)

**Comment by lewri** [comment]
The current repair call thresholds are when <6 uses remaining (low priority), and <4 uses remaining (high priority, starts smoking).
With each handyman repair the machine's overall strength gets reduced by 1 until it reaches 4. So fixing them unnecessarily reduces their lifespan faster.

Then again you're also playing a management game. It's up to the player though in this instance if they want to let the machines be fixed as needed, or be repaired sooner.

Also you do have control over the priority each handyman has to tasks. You can dedicate a handyman to almost always do repair jobs first for example. 

Could you provide a deeper explanation by what you mean when you say "calculated fixing threshold". And how it specifically differs from the current method.

**Comment by andersand** [comment]
I'll try to explain better, english is not my first language, but here we go. :slightly_smiling_face:

I had a feeling about, but had not verified, what you said that fixing reduces lifespan. And yes, I am often setting handyman's task priorities. Sometimes even to only fix machinery since I didn't know exactly how this game mechanic worked. 

`<rant>`
I feel like this part of the game is not so intuitive. It probably says in the game manual about how all this works, but I am guilty as charged I didn't read the manual, usually doesn't these days. Back in '97 when this game came out you could probably expect most people to read the manual to be able to figure out how stuff works, but as newer games came along with more pixels and were more advanced in terms of user experience, games became more intuitive moving from "RTFM" to UX...
`</rant>`

Anyway, the "chore" I've been doing is obviously not a good idea :clown_face: ... but I'm guessing there's others who don't read manuals.

As long as fixing the machinery degrades it, making the calls more frequent like I suggested means the machinery have to be replaced sooner. A costly practice. Having said that, I feel it would be nice to have an alternative to the current (kinda low) 4 and 6 thresholds you describe. 

The reason I've been doing this is when the hospital is in an earthquake area, machinery tends to break and explode if you run the game on the highest speed (especially when there's two consecutive earthquakes). It has sometimes caught me off guard and I lost the space where the room of the exploded machinery was. Which can be a problem when this happens multiple times and your level has little room or you're low on cash to buy more space.

An example:

Let's say your hospital is in an earthquake zone and you have not researched much on improvements, yet as it's quite early game and you need to focus on making your drugs not kill your patients :syringe: :skull_and_crossbones: This can take quite som time even if you have a decent research facility.

_You do however have enough money that you could hire more handymen. But let's stick within the current implementation limits._

An earthquake erupts and gives a lot of damage to many machines. Now I'm worried that they will explode if another earthquake comes before the handymen are done fixing the most damaged ones. So I do my chores, and check up on all the machinery in the hospital immediately. Those that are most damaged (~1/3 of full strength or worse) they start repairing, but I was unable to repair them all in time as another earthquake came by and some machinery exploded. A costly accident that rendered the area unusable. 

So what, you may ask. I can just ignore this and build somewhere else right? Sure, if you have enough money and space then no problem. If you don't it would have been cool to have that extra space you used to rebuild ready for your next treatment room or clinic. 

I don't know how the earthquakes are implemented, but if they can do as much damage as I think it would be nice to have an option to let handymen repair machinery earlier.

Sorry for the lengthy post. I hope this makes it more clear what I'm proposing.


Thanks.

**Comment by andersand** [comment]
More specifically though, I mean to change the constants used in the priority checks (6 and 4) to reflect a percentage of the machinery strength. Wouldn't that make more sense anyway?

So the pseudo code I propose would be 

UsesRemaining < Strength * RepairFactorNormalPriority
UsesRemaining < Strength * RepairFactorHighPriority

What would then be a good value for the constants?  Well take the `Inflator`. When I placed one now it starts out with Strength 8. If use this basis you apply the constants 6 and 4 and it would mean that

RepairFactorNormalPriority = 6/8 = 0.75
RepairFactorHighPriority = 4/8 = 0.50

That would mean if you had an `Operating table` with strength 14, and an earthquake did 8 damage to it, a handyman would automatically be paged for urgent repair.. since 6 remaining uses < (14 * 0.5) 
With the current implementation, this scenario would not even warrant a normal priority repair.

**Comment by lewri** [comment]
I think I understand more thank you.
I would say the caveat of % of machine strength left is older machines are going to be cutting it even finer (e.g. a 50% remaining on a Strength 4 machine would only have 2 uses left). It'd also mean the receptionist calls for repair never would get used if other code wasn't changed.

Earthquakes are designed to be a devastating event you need to control for (heaven forbid, one of the main campaign levels has a Earthquake level of 9!). And yeah you might not be able to save everything. Theme Hospital's main campaign was always very forgiving with space -- you had plenty of room to build replacement machines.

The earthquake mechanic itself is over ticks (though I think in this case 1 damage per day). So the handyman calls actually can go out during an earthquake where the repair call gets met (when you hear the klaxon, it's gone into high priority). Earthquakes are also usually scheduled with reasonable intervals (though main campaign might have some close to each other). So I don't think you're having to constantly repair them. You could even set game speed to 1 on the earthquake warning to do your repair calls, then just let things play out normally.

We also now have the fire extinguisher improvements in 0.65 -- they help give you a little safety net on a machine exploding from overuse.

You might also just need more handymen too, and assign them to plots.
I'll leave this request open though for any thoughts on other ideas (or going against my own views).

**Comment by andersand** [comment]
Thank you for those interesting insights. 

You're absolutely right, I forgot about that. It could be changed like so to ensure you have a lower limit

UsesRemaining < Max(Strength * RepairFactorNormalPriority, 6)
UsesRemaining < Max(Strength * RepairFactorHighPriority, 4)

When it comes to the receptionist calls in accordance to actually paging handymen, you're right, but what if this was an option/setting you could just turn on or off? That way you would still get these announcements if you choose the vanilla repair calls.

Earthquake level 9, yeah that's probably the level where I had issues, though I really only had to rebuild one or two machines on medium difficulty. I wonder if it had been harder on "hard"...

I just think in general it would be a nice improvement to the current repair calls mechanic that you would get this benefit that if you have a stronger machine it would be fixed at an earlier time. It can be a bit frustrating to see your "fixing-only" handymen stand idle when having machinery that actually needs repair. For instance a machine that has strength 16, and only 6 uses left will not survive the next earthquake. It will not be repaired since it still has 6 uses left, and not knowing when the next earthquake comes the player might not trust the fixing mechanic. 
Adding this as a setting I imagine would allow for scenarios with higher difficulty combined with frequent earthquakes and less room available to the player. 

Having more frequent repairs would mean more rapid degrading of your machinery. Not sure how this works in the game now, if a machine is broken down and has very low strength, will the handyman replace the machinery or will it keep being fixed and eventually degrading towards a pile of junk?

I always place fire extinguishers in every room with machinery, but I usually play with high speed and haven't noticed if a fire extinguisher has ever been used. Since I have had things go boom I assumed the handymen were unable to get to the room in time, but maybe that's not it. I have enough handymen, but assigning them to plots is not a feature I was aware. I found it now that I looked for it though. Is there some way perhaps to make that feature more noticeable? Perhaps as a tip from the advisor? Up until now I've been blocking off unused areas with benches to prevent handymen from getting lost and standing where there's no action. So assigning them to plots may solve many issues I have had 👍

**Comment by Alberth289346** [comment]
There are no animations of a fire extinguisher being used, just their presence has a positive effect.

TH is in general a micro-management game, so I am not in favor of automating repairs to the point that you don't need to bother with it at all.

**Comment by andersand** [comment]
Sure. Now that I'm aware of the ability to assign handymen to plots the problem seems to have gone away. 

Is there some way perhaps to make the assign to plots feature more noticeable, like as a tip from the advisor?

**Comment by Alberth289346** [comment]
Advisor is more about concrete problems than "useful tips" isn't it?  Perhaps the sign in the intro-screen?
No idea how to add something there, it may be just as simple as adding line of text in the language file.

**Comment by andersand** [comment]
That could work as well I suppose. Speaking of which, maybe it's just me, but I find the intro screen tips window to be easily missed. The intro screen looks good, but perhaps the tips window could be placed closer to the interface window..? 

![image](https://user-images.githubusercontent.com/621686/128710739-8e9cd395-3961-40f9-b2d2-269cf6386615.png)

**Comment by andersand** [comment]
Not I'm no UX guru, but it seems to me the intro screen (if that's what it's called) could benefit from a review of contrast/focus. What stands out to me is the large sign with the bright white logo, not the interface nor the tips window.

**Comment by lewri** [comment]
I could agree with the plot feature not being that noticeable... though that'd more a carried out problem from the original.
![image](https://user-images.githubusercontent.com/20030128/128752375-99ccbc59-1333-407d-ab8e-f4c0355747a2.png)
It could do with documenting.

**Comment by lewri** [comment]
This one has been addressed by providing additional documentation to the tips window for handyman plot designation (#2053)
