### ISSUE TITLE
[Bug] Update check returns 301 at loading of the game

### ISSUE THREAD

**Issue by abuech2s** [CorsixTH/CorsixTH#2040]
#### Describe the issue

Even if I deactivate the firewall, this message appears. No further firewall installed.

#### Steps to Reproduce
While loading the game, the console shows a http 301.

#### System Information
**CorsixTH Version:** *0.65.1*

**Operating System:** *e.g. Windows 10*

**Theme Hospital Version:** *GOG.com*

![firewall](https://user-images.githubusercontent.com/44176089/131383103-4827f39c-b51b-441a-adc9-290e5d4df381.jpg)

**Comment by lewri** [comment]
For info: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301

**Comment by TheCycoONE** [comment]
Yep, side effect of moving the url, but the update check didn't work anyway. This isn't blocking right; just needs to be fixed for 0.66

**Comment by lewri** [comment]
Yep, not blocking. Pushed the updated URL on a pr.
Suppose up to you if you wanted to do some work on the backend to let the update checker work temporarily when 0.66 comes out ... But probably not worth it.
