### ISSUE TITLE
[Bug] Cryllic languages potentially not supporting "//" in strings

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2043]
#### Describe the issue
It seems that the newline command `//` is not properly recognised in Czech, potentially applying to all Cryllic languages.

![image](https://user-images.githubusercontent.com/20030128/132121743-2410952d-ef6c-4da9-8e18-b7e7ba32f49d.png)

Code:
```lua
 pharmacy = {
    [1] = "Lékárna//",
    [2] = "Pacienti, kteří byly vyšetřeni a jejichž léčba je lék musí navštívit Lékárnu, aby si ho vzali. Jak více a více léků pro léčbu je objeveno a stanou se dostupnými, tato místnost bude více zaneprázdněná. Možná byste mohli chtít později postavit další Lékárnu.//",
    [3] = "Lékárna vyžaduje Sestru. ",
  },
```

#### Steps to Reproduce
1. Load game in Czech (Čeština)

2. Start a new campaign with defaults

3.  Build a room (I used pharmacy)

#### Expected Behavior
Recognise `//` as a newline command.

#### System Information
**CorsixTH Version:** 0.65.1 (likely previously versions)

**Operating System:** Windows 10

**Theme Hospital Version:** *CD, GOG.com, Origin, or Demo*

### Additional Info
**Workaround: Use `\n` for now.**
Ping @jansakos

**Comment by lewri** [comment]
Also confirmed in Russian

**Comment by Alberth289346** [comment]
Seems to be proper ASCII slashes.

![Screenshot from 2021-09-05 11-27-05](https://user-images.githubusercontent.com/3254232/132122006-28e812a7-a8d2-486c-85d5-95ae63cacbf7.png)

**Comment by lewri** [comment]
It is the declaration ``Font("unicode")`` breaking the behaviour it seems.
Adding it to a language without such declaration causes the above.

**Comment by TheCycoONE** [comment]
Try adding an additional next_utf8_codepoint at https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx_font.cpp#L636 and https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx_font.cpp#L651

In the bitmap version 2 characters are skipped at newlines.
