### ISSUE TITLE
Add machine strength indicator on replacing machine prompt

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2049]
**What feature or enhancement would you like to add?**
Suggested in discord. Add the ability to see what strength a machine will have when buying a replacement.
This opens the question to needing a TH97 toggle down the line to try and manage QoL improvements that don't align with the original gameplay.

**How would this feature benefit the gameplay of CorsixTH?**
Will let players see if replacing a machine is going to be worth it (e.g. less repairs?)

**Was the feature in the original game?**
No

**What version of CorsixTH are you using?**
 0.65.1

**Does this feature/enhancement relate to a current problem?**
No

**Additional information**
Add any other information or screenshots about the feature request here.

**Comment by RetroGamerFan** [comment]
There's one more area where strength related info could be shown...

![image](https://user-images.githubusercontent.com/95074358/144235630-12fedb9e-44b9-4eed-9561-f0644b52986e.png)
