### ISSUE TITLE
[Bug] German language files is 3 years old

### ISSUE THREAD

**Issue by abuech2s** [CorsixTH/CorsixTH#2054]
#### Describe the issue

The german language files is over 3 years old (compared to the english one). I believe there might be some differences (e.g. the difference is right now approx. 200 lines)
Do you have anyone working on it?
Or can/should I help you to update the german one?

Bests
Alex

**Comment by Alberth289346** [comment]
Don't think anyone is working on it, feel free to make changes and submit them

**Comment by TheCycoONE** [comment]
@abuech2s do you need any assistance updating and submitting the language file?

**Comment by abuech2s** [comment]
Sorry, did not try it yet. I just took a look into the language files (english and german). As I saw there differences of syntax, order and number of lines. I think I need some time to compare them ...

**Comment by Manuel-K** [comment]
I've started to update `german.lua`, but before I continue I wanted to make sure that it is not a problem that I've changed the order of the existing strings to match `english.lua`. Being able to use a graphical diff tool for translation is a lot easier.

**Comment by lewri** [comment]
Nope. Order is irrelevant. But it does help to group strings if you notice oddities.

E.g.
```lua
foo.bar.kan = "..."
foo.bar.tan = "..."
```
Is the same as
```lua
foo = {
  bar = {
    kan = "..."
    tan = "..."
  }
}

We prefer the latter where we can help it (at least for language files). I can see the German file has a handful of strings at the top in the first format.

**Comment by Manuel-K** [comment]
I've only used lua for some small mpv plugins, but I'm aware of that. I was coming from a minimize changes point of view.

The number of missing strings is huge, but I think I've got all of them at least in a rough state, but I've discovered several that seem to be unused (probably during a rework of the key assignment options) and some that use the un-tranlated version although I've defined them, e.g. `panel_gameSpeedKeys` and `panel_storePosKey`

**Comment by Manuel-K** [comment]
Okay, I've realized that I've been comparing to english.lua from 0.65.1 and key binding strings have been renamed in trunk.

**Comment by lewri** [comment]
Your can do a string dump from the debug menu in the game, though I would imagine you've got that far already. It lists unused strings at the bottom of the the file.

You can always build from trunk, or this appveyor test build from 6 days ago has some missing hotkey strings not in trunk yet (and you had access to Windows)
https://ci.appveyor.com/project/TheCycoONE/corsixth/builds/42806448 (#2112 )
