### ISSUE TITLE
Pls make better rus language

### ISSUE THREAD

**Issue by Matvey1705** [CorsixTH/CorsixTH#2058]
### Main Menu
Map editor -> Редактор карт
Custom campaign -> Дополнительная кампания
### Selecting a campaign or level
Choose a campaign to read more about it -> Выберите кампанию, чтобы узнать про нее больше.
Click a level to read more about it -> Нажмите на уровень, чтобы узнать про него больше.
Start - Старт
### Settings
Hotkeys - Горячие клавиши
Capture mouse -> Захват мышки
Click to toggle capturing the cursor in the game window -> Нажмите, чтобы переключить захват курсора в окне игры
Scroll mouse -> Скорость прокрутки
Set the scroll speed between 1 (slowest) to 10 (fastest).  The default is 2. -> Установите скорость прокрутки от 1 (самая медленная) до 10 (самая быстрая). Значение по умолчанию равно 2.
### Map editor
Inside -> Внутри
Outside -> Снаружи
Foliage -> Растительность
Hedgerow -> Изгородь
Pond -> Пруд
Road -> Дорога
North wall -> Северные стены
West wall -> Западные стены
Helipad -> Верт. Площадка
Paste area -> Размещение
Delete walls -> Удалять стены
Parcel 0 -> Участок 0, Parcel 1 -> Участок 1, etc
Helipad 1 -> Верт. Площадка 1, etc
Camera 1 -> Камера 1, etc
PLAYER COUNT -> Кол-во игроков
1 PLAYER -> Один игрок
2 PLAYERS -> Два игрока
3 PLAYERS -> Три игрока
4 PLAYERS -> Четыре игрока

**Comment by Matvey1705** [comment]
> К сожалению, мы можем рассчитывать только на волонтеров, которые обновят переводы, поскольку никто из нас не говорит по-русски :(
> 
> Если вы были готовы помочь и нуждались в небольшом руководстве, я уверен, что мы сможем вам помочь.

Hmm. Let's try it.

**Comment by lewri** [comment]
Here are all the untranslated strings in a file for you (ignore the superfluous ones at the bottom).
Some translation strings use `%s` and `%d` and these should be included as is. Numbers/intentional spacing should stay too.

I can probably update the file for you if you want once done.
[debug-strings-diff-russian2.txt](https://github.com/CorsixTH/CorsixTH/files/7212556/debug-strings-diff-russian2.txt)

**Comment by Matvey1705** [comment]
> Вот вам все непереведенные строки в файле (не обращайте внимания на лишние внизу).
> Некоторые строки перевода используют `%s`и, `%d`и они должны быть включены как есть. Числа / намеренный интервал тоже должны остаться.
> 
> Я, вероятно, смогу обновить файл для вас, если вы хотите, когда это будет сделано.
> [отладочные строки-diff-russian2.txt](https://github.com/CorsixTH/CorsixTH/files/7212556/debug-strings-diff-russian2.txt)

https://drive.google.com/file/d/1-Rr3f-QmVBgnnyPmLIhZaUhDlDRd_o8x/view

**Comment by lewri** [comment]
Thanks I'll put these strings through definitely before our next release

**Comment by lewri** [comment]
@Matvey1705 while going through the Russian file I found a patch of strings that weren't translated and just used English.

Up to you if you wanted to correct them.
[additional_strings_rus.txt](https://github.com/CorsixTH/CorsixTH/files/7246585/additional_strings_rus.txt)

**Comment by lewri** [comment]
This one should've been resolved now. Do we know why it's reopened?

**Comment by Matvey1705** [comment]
> This one should've been resolved now. Do we know why it's reopened?

i don't know. Perhaps it happened by accident.

**Comment by Alberth289346** [comment]
> This one should've been resolved now. Do we know why it's reopened?

You commented at matrix about not being intended to merge as it was marked RFC.

**Comment by lewri** [comment]
Good point! Though it's old news now :)
