### ISSUE TITLE
[Bug] VIP visiting results partially translated

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#2063]
#### Describe the issue
In Spanish version, when a VIP visit ends and he/she sends fax with results, everything is translated except words from VIP
It doesn't matter if it was good or bad feedback: Their words appears always in english

This problem is not present in previous version (0.63) that I've played

#### Steps to Reproduce
1. Start a game with Language in Spanish (Español)
2. Wait and accept VIP visit
3. Wait for fax with feedback and check it's partially translated

#### Expected Behavior
Fax with VIP visit results is displayed totally translated

#### System Information
**CorsixTH Version:** 0.65

**Operating System:** Windows 10 21H1 Version (Compilation 19043.1237)

**Theme Hospital Version:** CD

### Additional Info
![vip](https://user-images.githubusercontent.com/2896275/134824263-84f0df61-67c2-4d10-9153-21c4f930dc5c.png)

**Comment by lewri** [comment]
This is due to the addition of VIP string ordering in 0.65
It will be fixed by #2055 in 0.66
