### ISSUE TITLE
[Bug] Long windows do not  behave normally when a room is made

### ISSUE THREAD

**Issue by Matroftt** [CorsixTH/CorsixTH#2070]
![image](https://user-images.githubusercontent.com/91145555/140716058-430941b7-b422-4d1c-89e2-9fe7a617dca8.png)
When you put rooms next to long windows, the windows disappear. If the room is removed, there will be a void.

#### System Information
**CorsixTH Version:** 0.65.1

**Comment by lewri** [comment]
I think this might be an oversight in the code. As generally windows should only be removed if they get snipped by an adjacent wall. 

Can you show a picture of the windows before you built the rooms?

**Comment by Matvey1705** [comment]
https://drive.google.com/file/d/1MI6E2EUFvZftZtUAbPrDPSlfSIbResWP/view?usp=sharing
map is not mine

**Comment by lewri** [comment]
It gets weirder. The wall just gets upright deleted
![unknown-4](https://user-images.githubusercontent.com/20030128/141016086-f147a697-bdc9-4308-98ac-baea8dc01e1d.png)

**Comment by mugmuggy** [comment]
Keeping the walls there isn't a real problem, add the following in here for example, should be enough
https://github.com/CorsixTH/CorsixTH/blob/d0201f13cb71b270d69e12a2556cf2d3a8b4be7b/CorsixTH/Lua/walls/external.lua#L33-L41

```lua
  north_window_3 = 120,
```
The issue then is that when an internal wall is perpendicular to the window tiles they normally are replaced with a solid wall section. https://github.com/CorsixTH/CorsixTH/blob/d0201f13cb71b270d69e12a2556cf2d3a8b4be7b/CorsixTH/Lua/dialogs/edit_room.lua#L396
Depending on where that is you might have to check along the wall section to split the window into two windows, or you remove the entire window.
