### ISSUE TITLE
Machine stength in build menu

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2078]
### Discussed in https://github.com/CorsixTH/CorsixTH/discussions/2077

<div type='discussions-op-text'>

<sup>Originally posted by **RetroGamerFan** December  1, 2021</sup>
Add machine strength info to Build Rooms selection dialog and the Drug Case Book.

![image](https://user-images.githubusercontent.com/95074358/144209983-13178387-ee28-4456-a8a9-56b6553ec5d3.png)

![image](https://user-images.githubusercontent.com/95074358/144209784-a57d815b-3f73-464c-bed9-d004df542071.png)

Actually, the Drug Case Book could also use a "bar" for medicine effectiveness and show the percentage as well.
</div>

Ping @RetroGamerFan

**Comment by lewri** [comment]
Drug effectiveness is shown already in the casebook, so I don't think we need to consider that one.

However, I'm intruiged by the strength indicators when building. It won't work properly in the case book, as you may have multiple machines with all different strengths. See https://github.com/CorsixTH/CorsixTH/issues/2049 for upcoming feature in next release.

**Comment by RetroGamerFan** [comment]
There's one more area where strength related info could be shown...

![image](https://user-images.githubusercontent.com/95074358/144235685-bd1abf07-ff8a-488e-96d7-8f17a78fc05f.png)

**Comment by RetroGamerFan** [comment]
In 'machine.lua" change...

"
_S.dynamic_info.object.strength:format(self.strength)
"

...to...

"
_S.dynamic_info.object.strength:format(self.strength, self.world.ui.hospital.research.research_progress[self.object_type].start_strength)
"

And in "english.lua" insert the line...

"
dynamic_info.object.strength = "Strength %d (Replacement %d)"
"

**Comment by lewri** [comment]
Converted back to discussion again for the Build menu
