### ISSUE TITLE
Dynamic Info (info displayed in the HUD info bar) does not update when loading a game.

### ISSUE THREAD

**Issue by RetroGamerFan** [CorsixTH/CorsixTH#2081]
When saving a game, dynamic info is also saved. When loading the game, the dynamic info (for a room machine for example) may be displaying the wrong info because the language setting changed, or the "new_machine_extra_info" config file flag setting changed, etc...

Part of the load routine, should instruct any applicable patient, room, machine, etc.. to update it's dynamic text.

[Temp2.zip](https://github.com/CorsixTH/CorsixTH/files/7647450/Temp2.zip)

**Comment by lewri** [comment]
Language changes have always been difficult things. It's known about I'm sure, but not documented fully.

I'm sure we actually have some onLanguageChange functions but I'm guessing they're not applying when you load a save.

**Comment by RetroGamerFan** [comment]
My old programmer lecturer told me once "calculate it if you can and only cache it if you have to". Dynamic Info is like caching. If fixing the load routine is a big job, perhaps it's better to calculate the dynamic info upon mouse over a machine or patient etc... and then display it in the HUD?

**Comment by Alberth289346** [comment]
'save' in corsix is pretty much literally 'grab all Lua data in-flight by crawling over it, and serialize'. Loading does the opposite. Code doesn't get saved, data pointing to functions get re-attached to the code while loading.

Displayed HUD at the time of save thus gets loaded and displayed again as it was at the time of save without the program "knowing".

Simplest may be to clear the HUD (or never save it in the first place).

**Comment by RetroGamerFan** [comment]
I thought so - the serialisation for the data when saving is probably just a few lines of code.

I meant the way Dynamic info works is like a cache. It is "generated" when something changes. The proper way would be to only generate it when you need to display it. There may be a good reason for this, like improved responsiveness of the GUI.

Even if you don't save the dynamic info, you would still need to set this info upon loading a game.

**Comment by Alberth289346** [comment]
> The proper way would be to only generate it when you need to display it.

Not sure I follow this, but that's what it is doing afaik. You hover or click at something, the text gets generated and displayed. You save the text in the correct language. At the main menu change the language. Load the save again (loading the data that uses the previous language at the time of the save). And there you are with the text in the previous language displayed in the HUD.

I am not convinced you need to set the HUD display upon loading. Do you remember the last thing you clicked at before saving, the previous time you played? I am guessing 90% of the time you don't. Even if you do, it's easy enough to re-generate it after loading, just click at it again.

**Comment by RetroGamerFan** [comment]
"...You hover or click at something, the text gets generated and displayed...." - That's the way I would expect it to work too, but it doesn't work that way for a mouse-hover over a room-machine at least. Perhaps there is a good reason for this?

Unless you mean if no dynamic info exists, some mouse-hover code somewhere knows this and instructs the room to update it's Dynamic Info? Seems unlikely but possible I guess.

**Comment by lewri** [comment]
A quick glance at the code suggests dynamic info is updated at certain events -- not on access.
Odd, and I think it might also be what causes breakages with epidemics regarding dynamic info.

**Comment by RetroGamerFan** [comment]
Uncle Bob would probably advise to "do the job right" no matter the refactoring cost or risk of introducing new issues. Me, well I don't have the time or the debugger setup (yet) to figure out how everything works, so I would do what any good programmer not looking for trouble or too much work would do, implement the "load" fix. Still, I would think someone would know the code well enough already to decide whether or not "doing the job right" is better. Also, if you did need some kind of "caching", there are better ways of implementing such a compromise after "doing the job right".

**Comment by Alberth289346** [comment]
We tend to do lots of stuff on event rather than when needed. It's relatively simple to program, except you mustn't miss a single event or it fails. This becomes very hard when you change or add new features, since that typically introduces new events, and thus opportunities to break stuff. Another, much smaller draw-back is that you have all this information ready for use all the time, even when you don't need it.

In my view, shifting somewhat towards "compute when needed" is likely beneficial as it reduces the complexity of event handling (less things to handle at that moment), and reduces amount of stored data (smaller saves, less variables in the program).
Not sure where the border is though, nor whether this use-case is relevant. (Re-instating every little detail in the UI seems less than useful to me.)

**Comment by lewri** [comment]
To be fair, it's not just dynamic info on machines that can have update discrepancies, it is also patients (and doors?).
Based on discussion in #2080 it should be relatively easy to apply to all needed use cases.

**Comment by lewri** [comment]
So what I have found from some digging is that the code causes some strings to persist in their previous language regardless of a call to update dynamic info at load.

I'm pretty sure the changes I've made for a PR will at least translate some things on load... yay?
A long term solution would be to restructure the `action_strings` on load, but that would require working out what action a humanoid was doing (not impossible, but not work I want to look at right now).

**Comment by Alberth289346** [comment]
Another long term path could be to give all strings a name, and provide name + data to the UI for storage what to display. It can do the conversion to text completely in the UI then.

A language change then just means rebuilding all displayed strings, pulling text by string name from a different language file.

**Comment by lewri** [comment]
> Another long term path could be to give all strings a name, and provide name + data to the UI for storage what to display. It can do the conversion to text completely in the UI then.
> 
> A language change then just means rebuilding all displayed strings, pulling text by string name from a different language file.

This one should probably be in #2126 now

**Comment by TheCycoONE** [comment]
I don't actually think it will unfortunately, which is why I asked. I liked the refactor anyway.
