### ISSUE TITLE
[Bug] App:fixConfig() is looking at incorrect data

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2082]
Looks like when config_finder was set up, nobody thought to include config_defaults in its returned dataset

https://github.com/CorsixTH/CorsixTH/blob/381c3a8b69369a6d21f13c9c46500f279a78d2ae/CorsixTH/Lua/config_finder.lua#L858

As a result, `App:fixConfig()` looks at the same values as what it already knows.

https://github.com/CorsixTH/CorsixTH/blob/81db3338d89df253e85fc6b7ace9d937092dafaa/CorsixTH/Lua/app.lua#L828-L834

Should be a simple fix of realigning some code.

**Comment by lewri** [comment]
Side note: App:fixHotkeys() also does this

**Comment by Alberth289346** [comment]
The joys of long lists and silent dropping or swapping values :p 

Wrapping the values in a table with named fields may be a solution for most cases.

**Comment by mugmuggy** [comment]
That's what this reads as though it does

https://github.com/CorsixTH/CorsixTH/blob/381c3a8b69369a6d21f13c9c46500f279a78d2ae/CorsixTH/Lua/config_finder.lua#L161-L165
