### ISSUE TITLE
LEVEL.L1 error with GOG version

### ISSUE THREAD

**Issue by romadu** [CorsixTH/CorsixTH#2092]
I'm using Linux version of CorsixTH. I have GOG version of Theme Hospital. When I launch I receive a warning that LEVEL.L1 file is the wrong size and may cause the game to crash. The warning suggests that the file size should be around 160kb, which is similar to the size of the demo file. However, all of the level files in HOSP/LEVELS are between 3kb and 8kb (files 1-44). Should I ignore the error, or is there a problem with my GOG files?

**Comment by Alberth289346** [comment]
Seems much less then 160KB. This is from a CD I bought second-hand (not GOG).
``` sh
$ ls -l CD/HOSP/LEVELS/LEVEL.L1*

-r--r--r--. 1 user user 2875 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L1
-r--r--r--. 1 user user 3606 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L10
-r--r--r--. 1 user user 3906 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L11
-r--r--r--. 1 user user 5045 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L12
-r--r--r--. 1 user user 2321 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L13
-r--r--r--. 1 user user 2425 Aug  9  2002 CD/HOSP/LEVELS/LEVEL.L14
```

**Comment by lewri** [comment]
Interesting, never seen this warning pop up before. 
I think the GOG installer definitely has a compressed version of Theme Hospital inside it... How did you extract the files?

**Comment by romadu** [comment]
I used gog installer to launch and play the game, then copied HOSP folder
contents over

**Comment by lewri** [comment]
I found the check for corruption here
https://github.com/CorsixTH/CorsixTH/blob/0b516b82e8da71029cf5630b2f41fb4f032c167a/CorsixTH/Lua/app.lua#L1332-L1349

Interestingly, the LEVEL.L1 should only be checked if you're using the demo files.
Though, it sounds like you're not using the demo files, so not sure why this has trigged...

**Comment by lewri** [comment]
Note: This sets the game to demo mode or full mode.
https://github.com/CorsixTH/CorsixTH/blob/0b516b82e8da71029cf5630b2f41fb4f032c167a/CorsixTH/Lua/app.lua#L1309-L1314

I'd make sure you don't have  `Demo.dat` present somewhere in your HOSP folders.

**Comment by romadu** [comment]
Thanks, that file was present. I hadn't deleted it when copying over the full game files. After deleting it, everything works correctly. Thanks again.
