### ISSUE TITLE
Add 'reset zoom' hotkey

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2097]
**What feature or enhancement would you like to add?**
Add the ability to reset back to default zoom level of the game. Currently, we can only zoom in and out. E.g. `Ctrl + 0`. The save camera position 0 key may need sacrificing for this. Alternatively, use `Shift + 0` (unused).

**How would this feature benefit the gameplay of CorsixTH?**
Reset zoom can be useful where a player may want to quickly go back from a specific zoom level. Reset zoom is also becoming a more universal feature.

**Was the feature in the original game?**
No?

**What version of CorsixTH are you using?**
 0.65.1

**Does this feature/enhancement relate to a current problem?**
Give a summary of the problem referencing an issue number if one exists.

**Additional information**
As evolved from Discord discusison.

**Comment by lewri** [comment]
@TheCycoONE I'm sorry if this ruins the work of #1942 😅

**Comment by TheCycoONE** [comment]
Not at all, it's probably only easily doable because of that work.

**Comment by lewri** [comment]
This was my bad... @flackr already did this and didn't notice!
