### ISSUE TITLE
Fake Blood Emergency Shows Incorrect Cure

### ISSUE THREAD

**Issue by bob2sea** [CorsixTH/CorsixTH#2098]
When there is an emergency presented via the fax machine for Fake Blood, the description says: "You have the drug they need. It is Fake Blood and the drug is 80% effective"

However, the cure is actually a psychiatrist.

![Fake Blood](https://user-images.githubusercontent.com/65736220/152500944-3173d0e2-2179-4cf8-9a71-37e526de8e15.png)

**Comment by mugmuggy** [comment]
That is my bad on that one...
https://github.com/CorsixTH/CorsixTH/blob/a363f3a3264ca4f3177a5d5cd228932f1f7ed45b/CorsixTH/Lua/hospital.lua#L1097
should be
```lua
local casebook = self.disease_casebook[emergency.disease.id]
````
