### ISSUE TITLE
Screen bug/clitch - Windows 10 - 0.64 and 0.65.1 - Origin

### ISSUE THREAD

**Issue by TheSuperGiant** [CorsixTH/CorsixTH#2099]
There are black flickering things come in the screen
I doest saw it in resolution 1920X1080 Fullscreen and when fullscreen is off. Only in full screen is it happening. In all other resolution of 16:9 I saw this and in 800X600 in Fullscreen. Other resolutions I doesn't tested it

#### Steps to Reproduce
1. From starting a new Hospital, when loading a save file, Opening map editor.

#### Expected Behavior
I record the issue. Doesn't see the black flickering things in screen.
https://www.youtube.com/watch?v=AF8RYqjasHQ

#### System Information
CorsixTH Version: 0.64 and 0.65.1
Windows 10 64 bit
Theme Hospital Version: Origin
Nvidia RTX 3060
Driver version 511.65

#### Gamelog.txt
I tried everything that the game is creating the Gamelog.txt file but it isn't creating the file in the folder of config.txt file.

### Additional Info
In the older version of CorsixTH 0.63 there wasn't this problem.

**Comment by lewri** [comment]
This could be some error outside our control. In fullscreen, your os resizes the whole computer resolution to e.g. 800x600. Windows is known for some weird quirks.

You may want to check your graphics driver is up to date, an outdated driver _could_ be responsible.

Im assuming you mean 0.64 and 0.65.1 as the tested versions though.

**Comment by theGriant** [comment]
I'm switching the resolution of mine main monitor to the resolution in windows settings that I want to play in and then I doesn't have the screen glitches.

**Comment by lewri** [comment]
Intriguing. It could maybe be the opposite issue that the latest driver caused the issue.

It might be worth reporting to the manufacturer of the driver too... Just in case..

For now we'll see if anyone else can replicate.

**Comment by lewri** [comment]
Ok, I'm guessing it's driver related. Wondering if you can try an older driver.

**Comment by theGriant** [comment]
I had found this acricle on Nvidia bug report forum.
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/474589/drivers-newer-than-47212-causes-screen-flickering/

I have installed version **472.12** and the **black flickering was gone** it is an driver issue.


i had already make mine own bug report but i think that Nvidia known it already but this is already 6month that's its happening.

Thanks for your time.
