### ISSUE TITLE
[Bug] Scroll Keys missing from Hotkeys menu

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2107]
#### Describe the issue
Before hotkeys revamp, scroll keys were settable in the Hotkeys menu. Now they are missing
#1942 

#### Steps to Reproduce
1. Navigate to Hotkeys and notice Scroll Keys are missing.

#### Expected Behavior
Allow setting scroll keys

#### System Information
**CorsixTH Version:** SAVEGAME version 166 (9 days ago, Master).

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by lewri** [comment]
Worse part is resetting the keys to default also resets scroll keys, that you can't see 😨

**Comment by TheCycoONE** [comment]
Oops
