### ISSUE TITLE
[Bug] Customize folders setting is inconsistent

### ISSUE THREAD

**Issue by Manuel-K** [CorsixTH/CorsixTH#2118]
#### Steps to Reproduce
1. *Open settings menu, then customize folders, then font, click on back.*

2. *Open settings menu, then customize folders, then on anything than font, click on cancel.*

3. *Observe that the fonts window has only one button while all others have to buttons and that the fonts button throws you back to settings while all the others let you stay in the customize folders dialog.*

Nothing serious, but it's very noticeable when you check a modified translation file.

**Comment by TheCycoONE** [comment]
Thanks for the report
