### ISSUE TITLE
Make handyman stay in their plots

### ISSUE THREAD

**Issue by jez9999** [CorsixTH/CorsixTH#2123]
The handyman zoning doesn't seem to work properly.  When I play the "confined" scenario and set a handyman to zone 1, he keeps leaving zone 1.

**Comment by lewri** [comment]
Do you have a savegame you can share with us to look into it?

**Comment by lewri** [comment]
[movetheplant.zip](https://github.com/CorsixTH/CorsixTH/files/8467642/movetheplant.zip)
^ This is in savegame ver 166ish (my test environment) so may not load in 0.65

I haven't been able to replicate the issue specifically with that scenario. I put plants down in each of the 3 plots and and the handymen stuck to their zones. I did pop a staff room down though and all handymen went to it, regardless of plot.

I would assume that a handyman is not bound by plot when he wants to rest -- he should return to his plot after resting.
However, I did (as a potential separate issue) notice that handymen wouldn't move to their assigned plot until a plant needed watering.

I'm not sure if machines or litter are causing different behaviour though, we'd really need a savegame from yourself to look into that.

**Comment by jez9999** [comment]
OK I've uploaded a save of me playing the Confined scenario.  All handymen are set to Plot 1, but they just walk about anywhere.  When placed in plot 1, they leave shortly.

[Handymen.zip](https://github.com/CorsixTH/CorsixTH/files/8470628/Handymen.zip)

**Comment by mugmuggy** [comment]
So the handyman really only answers calls in his allocated spot, but when he is wandering he isn't restricted to the parcel. That appears to be the issue, as the calls aren't being answered elsewhere.

**Comment by jez9999** [comment]
Given that a large part of the handyman's job is sweeping up puke and litter, I'd say being restricted to the area is pretty important too. :-)

**Comment by lewri** [comment]
The meander path requires a certain amount of space to execute. Because that map is extremely space limited, the handyman is more likely to end up with a path that leaves the plot -- and a handyman can't just stop out on the outside path.

This is quite a niche case exposed due to the level.

> I'd say being restricted to the area is pretty important too. :-)
I think this has its own drawbacks. It would also mean handymen could only go to staff rooms inside their plot. And if there's no staff room reachable, they could go crazy.

**Comment by jez9999** [comment]
Well I'd make an exception for when they needed to go to the staff room.  They'd return to their plot after resting.

**Comment by lewri** [comment]
You know, I didn't realise handyman zoning wasn't part of the original game... It was something we added.
Maybe there was a reason or limitation we couldn't keep handymen in their zone when it was made. I'll leave this open for now in need of development/further discussion.
