### ISSUE TITLE
Windows Corrupt on Level 8

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2128]
When buying the bottom middle section of Hospital on level 8, some of the windows are corrupt.

Nothing huge, likely an easy fix, but yeah.
![cth windows lvl 8](https://user-images.githubusercontent.com/1302977/162645225-9a1ed5fc-c809-487a-9b33-3a78fcd6549a.PNG)

**Comment by TheCycoONE** [comment]
That's there in the map file from the game, it's not our bug.
