### ISSUE TITLE
Epidemic patient spawns outside the Hospital.

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2129]
Got an epidemic, found the one patient, Marked him for nurse cure, and went on my way. Health inspector showed up 30 seconds later, declared I'd failed and fined me. during this time (while the inspector was stood at the desk) an infected patient wanders in and heads to reception.

I assume this is an extremely fringe case, as reloading the month gave me 2 different patients that were contagious, I believe the patient spawning outside the hospital and becoming infectious is what triggered the epidemic fail as nobody infectious left the hospital, cured or not during that time, so this other patient is my only other suspect.

Can't provide saves, as by the time it was over, and I worked out what had happened, the inspector was gone and the patient was no longer contagious.

**Comment by lewri** [comment]
During a potential epidemic, epidemic-eligible patients are logged, but are not made known to the player until the epidemic is revealed by a doctor. 

I believe the fringe case could be one of the patients was about to become fed up before the epidemic was revealed -- and they must've got fed up almost immediately after you started a coverup.

Interestingly, the function to manage fairness is this, and it probably still is robust.
https://github.com/CorsixTH/CorsixTH/blob/01f159403e63232871aaef78997b658ec032ec32/CorsixTH/Lua/epidemic.lua#L267-L279

So I think it could've been a case of bad luck here. Did a patient leave almost straight after you started the cover-up?

**Comment by MRMIdAS** [comment]
No. No patient left. I paused the game and moved around every single patient in the Hospital. The only patients leaving were cured or had untreatable illnesses. 

The only thing I can think that happened was the patient had spawned at the furthest spawn point to the entrance, which tripped the "left hospital" condition, and the health inspector triggered at a closer spawn point after that.

**Comment by lewri** [comment]
> Health inspector showed up 30 seconds later, declared I'd failed and fined me. during this time (while the inspector was stood at the desk) an infected patient wanders in and heads to reception.

I think I misunderstood this message before. Are you saying the infected patient was still heading to reception while inspector was called?

**Comment by MRMIdAS** [comment]
That is correct yes. Had one patient in the hospital that had just been diagnosed, searched for another and couldn't find anyone, the clock popped to full straight away, the inspector arrived, clisely followed by the infected patient heading towards reception.

**Comment by lewri** [comment]
I have found the issue I believe.

When a patient is spawned, they get assigned their disease -- and by result their contagiousness (if epidemicable) -- as soon as they appear on the map.

The issue is, our check to see if the epidemic discovery has become inevitable, only checks if a patient is outside the hospital grounds.

The solution will be to somehow exclude patients who haven't got to the hospital yet from the epidemic checks. I have some ideas, but none feel concrete enough yet.

**Comment by MRMIdAS** [comment]
Yeah, I assumed it was a fringe case. The only thing I can think of is something along the lines of setting a flag to see if they've been seen by a receptionist, and if so, that makes them eligible for infection, but that'd limit possible infection among folk queueing for reception.

**Comment by lewri** [comment]
In fact, I rechecked the code we rely on checking for escaped patients and it should be robust.
It may be handy to have any autosave (if you still have one) from before the epidemic started in case it can be replicated. Though appreciate you may have carried on playing now for >12 months in game.

**Comment by MRMIdAS** [comment]
Once I realised what was going on, I did reload the autosave and couldn't reproduce the error, spent an hour trying, just reloading the save over and over, so it seems like a one-in-a-million shot. But yes, my autosave has been overwritten by now, sorry.

**Comment by lewri** [comment]
I have found a hole where it is possible for a patient to be infected while going home (e.g. kicked, fed up). It might not be what caused your issue, but it is a possibly. Either way I will work on at least fixing that.

**Comment by TheCycoONE** [comment]
If we observe this again in master or a future version, reopen.
