### ISSUE TITLE
[Bug] Persisted Knock Door Action breaks on resumption from 0.64 > master

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2142]
#### Describe the issue
If a patient had a knock action queued when the game was saved in 0.64; and reloaded their save in master; the action crashes on that patient.

Any new knock door actions are not affected.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait -- a patient is about to knock on the GP office door.

3.

#### Save Game

[064singlerun.zip](https://github.com/CorsixTH/CorsixTH/files/8556858/064singlerun.zip)

#### Expected Behavior
No crash on resuming a door knock action.

#### System Information
**CorsixTH Version:** Appveyor master build 671

**Operating System:** *Windows 10*

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\humanoid_actions\knock_door.lua:92: Illegal state nil in KnockDoorAction:update
stack traceback:
        [C]: in function 'error'
        Lua\humanoid_actions\knock_door.lua:92: in method 'update'
        Lua\humanoid_actions\knock_door.lua:56: in local 'timer_function'
        Lua\entity.lua:216: in method 'tick'
        Lua\world.lua:1093: in method 'onTick'
        Lua\app.lua:1125: in function <Lua\app.lua:1122>
        (...tail calls...)
        Lua\app.lua:1025: in function <Lua\app.lua:1020>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

**Comment by lewri** [comment]
Error does not occur if going 0.64 > 0.65 > Master

**Comment by lewri** [comment]
Error introduced somewhere after Appveyor 636 build #2065 and on or before Appveyor 652 #2094  build.

**Comment by lewri** [comment]
Potentially #2087 is the cause? Can you verify @Alberth289346

**Comment by Alberth289346** [comment]
> Potentially #2087 is the cause? Can you verify @Alberth289346

Definitely #2087, I added that crash message :)
