### ISSUE TITLE
[Bug] Gamelog.txt isn't generated (generate system info on load/new game)

### ISSUE THREAD

**Issue by colinjmatt** [CorsixTH/CorsixTH#2170]
### Describe the issue

The expected gamelog.txt file isn't being generated when starting the game. No errors appear in the UI or within the console for this.

### Steps to Reproduce

1. Run CorsixTH

2. Check for gamelog.txt where config.txt is (in this case, ~/.config/CorsixTH/)

3. File is not created

### Expected Behaviour

File should be present.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.66-beta1

### Operating System

MacOS Monterey (Apple Silicon)

### Theme Hospital Version

CD

### Gamelog.txt

```bash
Not present
```

**Comment by lewri** [comment]
So this is actually expected behaviour.
Though I would've preferred the gamelog to be made on load/new game with at least the system info.

**Comment by TheCycoONE** [comment]
seconded
