### ISSUE TITLE
[Bug] Edge Scrolling continues after mouse exit

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2175]
### Describe the issue

If CorsixTH has 'Edge Scrolling' turned on, the game will scroll continuously when the mouse leaves the window (including via alt-tab)

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. 

3.

### Expected Behaviour

We should stop edge scrolling once the mouse is no longer inside the window

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.66-beta 1

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

![image](https://user-images.githubusercontent.com/20030128/169873088-7b9cf7a2-33c3-452c-9da8-41133dcef1d6.png)
^ Workaround is to turn Edge scrolling off.

Reported in Discord

**Comment by TheCycoONE** [comment]
This is working as intended, mouse capture and ctrl+10 were built specifically to manage this behaviour. The workaround is to hit ctrl+f10 to release the mouse.
