### ISSUE TITLE
[Bug] Long window becomes wall

### ISSUE THREAD

**Issue by ryanedgewurth** [CorsixTH/CorsixTH#2179]
### Describe the issue

There is a bug with the windows, in which they for some reason turn into an wall if a room is placed there.

### Steps to Reproduce

1. Load v0.2 of Hillside + District's single scenario "Old Hillside", or any map with similar windows

2. Start the level in any form. Place a room at the front windows on Hillside. This effect occurs on all levels.

3. That's the bug

### Expected Behaviour

The windows should have not been replaced

### Save Game

Save game attached to report: No

### CorsixTH Version

0.65.1

### Operating System

Windows 11 Version 22H2 (OS Build 22621.1)

### Theme Hospital Version

CD

### Additional Information

![image](https://user-images.githubusercontent.com/32139009/170958749-2be3b5f1-462a-4348-ac2e-8f5e8903f599.png)

**Comment by mugmuggy** [comment]
Dupe #2070
