### ISSUE TITLE
[Bug] Balance Sheet can load green

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2181]
### Describe the issue

If loading a save where the balance sheet was open, the text becomes highlighted in green and will not go away until the application is restarted. It also continues as new items scroll bay on the balance sheet.

If a save is previously opened where the balance sheet **is not** up, then it is opened, the aforementioned save no longer gets the green.

### Steps to Reproduce

1. Start a new game

2. Navigate to the Bank Manager and open the balance sheet. Save the game.

3. Close CorsixTH and reopen. Load the save.

### Expected Behaviour

The text should not be tainted green.

### Save Game

Save game attached to report: No

### CorsixTH Version

0,66 beta 1

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

![image](https://user-images.githubusercontent.com/20030128/171296186-6745992c-edaf-49fc-854d-39d2e48a8852.png)

I have a suspicion it could be something to do with the highlight colour of the "load game" menu not being cleared the game is loaded.

**Comment by mugmuggy** [comment]
You can fix this with in the afterLoad to reload the fonts. I'm assuming some persistence thing here.

**Comment by lewri** [comment]
> You can fix this with in the afterLoad to reload the fonts. I'm assuming some persistence thing here.

Before a I push a PR for the afterLoad suggestion, is it the correct way to fix this? Or should we be doing something else?

**Comment by TheCycoONE** [comment]
Ok, the actual thing that isn't persisted is the transparency in the pallet. You can produce the same affect by commenting out https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua#L41

I strongly suspect the fix is going to be engine level lewri, and given how obscure it is I wouldn't recommend a lua bandaid over it, lets fix this properly.

**Comment by TheCycoONE** [comment]
```
CorsixTH\Lua\ui.lua
153:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
208:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
212:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
216:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
220:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
224:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
228:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
232:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
236:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\graphics.lua
163:    cursor_palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\staff_management.lua
35:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\research_policy.lua
45:  palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\hospital_policy.lua
33:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\fax.lua
35:  palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\town_map.lua
38:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\graphs.lua
48:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\progress_report.lua
36:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\annual_report.lua
55:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\bank_manager.lua
35:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
41:    -- palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent

CorsixTH\Lua\dialogs\fullscreen\drug_casebook.lua
33:    palette:setEntry(255, 0xFF, 0x00, 0xFF) -- Make index 255 transparent
```

As can be seen the only use of palette:setEntry is this transparent index. It's not immediately clear to me whether there's any situation when it should not be transparent, but for safety sake it will be converted to a flag.
