### ISSUE TITLE
[Bug] Window dragging very stuttery

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2185]
### Describe the issue

This may be a problem out of our control but I have noticed that dragging the CorsixTH window in Windows causes it to be very stuttery (including the command window).

### Steps to Reproduce

1. Load CorsixTH and drag around window

### Expected Behaviour

We should be expecting a smooth transition during a window drag.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.66-beta 2

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

Possibly a separate issue but the game also pauses while being dragged (may be intentional?)

**Comment by TheCycoONE** [comment]
The pause is related to SDL behaviour. There are workarounds - see: https://stackoverflow.com/questions/7106586/keep-window-active-while-being-dragged-sdl-on-win32

I'm not exactly sure what you mean by stuttery here.

**Comment by lewri** [comment]
Never mind it resolved itself this morning... how odd.

**Comment by lewri** [comment]
Oops... reopen if you wanted to address the SDL pause behaviour.

**Comment by TheCycoONE** [comment]
Not in this ticket. We might do something in that other ticket about the movies.
