### ISSUE TITLE
[Bug] patient sitting in hair restorator and want go away

### ISSUE THREAD

**Issue by BoresXP** [CorsixTH/CorsixTH#2188]
### Describe the issue

See hair restorator room,

### Steps to Reproduce

1. *Load save game attached to this ticket* into v0.66-beta2

2. Start playing

3. See hair restorator room. There is a patient and he won't go away. I've already ask him to lease so there is no such button anymore, Other patients are waiting for him. I cannot change this room.

### Expected Behaviour

Patient should leave the hospital.

### Save Game

Save game attached to report: Yes
[boris1.zip](https://github.com/CorsixTH/CorsixTH/files/8884813/boris1.zip)

### CorsixTH Version

v0.66-beta2

### Operating System

Windows 10 x64

### Theme Hospital Version

CD

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2682, game version: v0.66-beta2, savegame version: 170
.
.
.
Savegame version is 170 (v0.66-beta1), originally it was 156 (v0.65).
Warning: Trying to resolve door deadlock at (35, 34)
Warning: Trying to resolve door deadlock at (36, 40)
Savegame version is 170 (v0.66-beta1), originally it was 156 (v0.65).
Savegame version is 170 (v0.66-beta2), originally it was 156 (v0.65).
Error in timer handler: 
Lua\hospitals\player_hospital.lua:345: bad argument #2 to 'random' (interval is empty)
stack traceback:
	[C]: in function 'math.random'
	Lua\hospitals\player_hospital.lua:345: in method 'giveAdvice'
	Lua\calls_dispatcher.lua:118: in method 'callForRepair'
	Lua\entities\machine.lua:156: in method 'machineUsed'
	Lua\humanoid_actions\use_object.lua:342: in local 'timer_function'
	Lua\entity.lua:216: in method 'tick'
	Lua\world.lua:1085: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
```

### Additional Information

Russian langule selected.

**Comment by BoresXP** [comment]
Second error (math.random) is related to this issue.

**Comment by lewri** [comment]
Do you still have the autosave before the crash (Autosave12.sav) in `C:\Users\username\AppData\Roaming\CorsixTH\Saves\Autosaves`?

**Comment by lewri** [comment]
Potential cause #2155

**Comment by lewri** [comment]
Arguably, this could be a `P2 High` as it breaks the humanoid and the room.
However, chances are if the state that triggered this error happened once it would happen again in the same playthrough -- thus breaking more rooms.

**Comment by BoresXP** [comment]
> Do you still have the autosave before the crash (Autosave12.sav) in `C:\Users\username\AppData\Roaming\CorsixTH\Saves\Autosaves`?
[Saves.zip](https://github.com/CorsixTH/CorsixTH/files/8886334/Saves.zip)
Autosave9 - before I ask patient to leave the hospital.
Autosave7 - just before the issue, but I cannot reproduce it.
