### ISSUE TITLE
CallsDispatcher.getPriorityForRoom is a mess

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2193]
https://github.com/CorsixTH/CorsixTH/blob/f5ff0603abc367f058a800ca368d2d4770fac0ab/CorsixTH/Lua/calls_dispatcher.lua#L496-L525

This function works out a 'score', but the values and structure seems very arbitrary. And in addition, it seems that lower scores are better (although this isn't documented).

While I imagine it works, it's likely really not a good way of doing this function imo. I noticed this the more I look at #2133 .

I'm not sure what the answer is yet to make this better, but I'm sure there's something.

To note: this function is used in a `--[[persistable:call_dispatcher_staff_priority]]` so while the function name can't change, I'm pretty sure its guts can be.

**Comment by lewri** [comment]
It actually seems the whole class is full of oddities... I'm pretty sure @Alberth289346 noticed this way before I did though...

**Comment by Alberth289346** [comment]
I did?  Nice :)

But no, don't think I even dared opening that file, or it was a long time ago.

Theoretically, solving allocation problems by allocating 1 person at a time is not going to give you a good solution.

In practice it may be not too bad, the allocation problem in CTH is pretty simple as long as you manage to avoid allocating 1 surgeon in an operating theater and force specialists to do their specialist work. Also, for game play, you may actually want a sub-optimal scheduler, or the player doesn't need to pay attention to it.

I think the original game runs a periodic computation for this problem, the level file seems to have a variable for the interval at least.

**Comment by lewri** [comment]
I don't this is as bad as it seemed at the time
