### ISSUE TITLE
[Bug] Mission doesn't end when victory conditions are met

### ISSUE THREAD

**Issue by JanSimek** [CorsixTH/CorsixTH#2207]
### Describe the issue

The Briefing states you need 400 reputation, 200 patients cured and $50.000 in the bank account. 

I have 821 reputation, 213 cures and $158.041 in the bank, so the mission should be won.

### Steps to Reproduce

1. *Load save game attached to this ticket*

### Expected Behaviour

You should see a window that lets you progress to the next level.

### Save Game

Save game attached to report: Yes

[neverendingstory.zip](https://github.com/CorsixTH/CorsixTH/files/9127604/neverendingstory.zip)

### CorsixTH Version

3a4f98374a9e15c4a84125a04f071be926d0e578

### Operating System

Arch Linux

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x86_64, audio: true, os: unix
SDL renderer: opengl
Lua 5.4 run with api version: 2682, game version: Trunk, savegame version: 172
Created game with savegame version 172.
Error in callback handler: 
/home/jsimek/Development/CorsixTH/CorsixTH/Lua/audio.lua:586: Could not load music file 'Sound/Midi/DOCTOR.XMI' (Couldn't open timidity.cfg)
stack traceback:
	[C]: in function 'coroutine.yield'
	/home/jsimek/Development/CorsixTH/CorsixTH/Lua/app.lua:1052: in function </home/jsimek/Development/CorsixTH/CorsixTH/Lua/app.lua:1047>
```

**Comment by tobylane** [comment]
The briefing is incomplete, the progress report has the full information. You need to cure 45% of patients and have a hospital value of 120k. I bought another plot of land which took it over that, and won the level.

Should the briefing list all the requirements, or just give a flavour of them? As we let level creators write their own, I think we should assume they may not write a full list.

**Comment by lewri** [comment]
Was literally a few drinks machines away from winning. This one is from the original campaign I believe? We shouldn't press much over their briefings imo.

It's disappointing, but I don't believe we should act upon this. As per Toby's comments, it's down to level creators to include what is necessary in the brief.
