### ISSUE TITLE
Should not be possible to place objects in front of doors

### ISSUE THREAD

**Issue by iMiKED** [CorsixTH/CorsixTH#221]
Hello!

What steps will reproduce the problem?
1. Load game
2. Accept incoming emergency patients with bloaty heads
3. Get numerous errors (Empty action queue)

What is the expected output? What do you see instead?
I expect patients to go to Bloaty Head clinic

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
Version 0.30 - released November 2013

What operating system / compile settings are you using?
WinXP SP3 Pro

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game level 10

Saves and gamelog are available here:
https://mega.co.nz/#F!hs9mRZgY!aqHZDrfLGohXc_GhAnLYRA
 -- or here --
https://drive.google.com/folderview?id=0B5wa6TO0a4ZHc2l4SC1LTmNCa0U

**Comment by TheCycoONE** [comment]
I'm also not able to put a radiator in front of a door, but somehow @Frassle managed to (in the bathroom) as evidenced by the save in that ticket.

@Frassle, was that game started in 0.40 or did you originally start it in an earlier version?

**Comment by Frassle** [comment]
Game was started in 0.40, was the first version of Corsix I've used. Using the downloaded installer not built from scratch.

**Comment by MarkL1961** [comment]
@TheCycoONE   Try placing a radiator in a position where if you were to build a room you would place the door.  Now build the room around the radiator and whilst in blue print mode you can place the door next to the radiator.  Now you have a room with a radiator blocking the door

**Comment by TheCycoONE** [comment]
Ahh, thanks @MarkL1961 so it's the door placement that needs to be modified rather than object placement.

**Comment by TheCycoONE** [comment]
Also I just checked the original, and in it you couldn't place a radiator facing any direction on the tiles adjacent to doors.  In CorsixTH you can as long as the radiator isn't on the door wall, which I feel could lead to other bugs.  Suggesting we use the same restrictions as the original when it comes to doors (parcels must be completely clear on each side).

**Comment by MarkL1961** [comment]
I think there is still an issue with the blue double doors and that it is still possible to place a radiator in front and over lapping them.  Can't check it again at the moment, but it was still possible the last time I checked.
Also bench placement can cause a problem when next to a door - think that is in another issue somewhere

**Comment by TheCycoONE** [comment]
Alright, while I think the title of this ticket should cover that case too. It should not be possible to put any object (bench, extinguisher, radiator, etc.) in the parcels immediately in front (or behind) doors and conversely it shouldn't be possible to place doors that would violate that condition.  Right now the only restriction being enforced is the pathfinder.

**Comment by J-Shep** [comment]
![doubledoorproblem](https://cloud.githubusercontent.com/assets/6353342/6735300/4005c93c-ce55-11e4-88e9-6b0b5f763621.png)

I see that door objects don't have footprint cells defined in their class definitions and their cells are checked in edit_room.lua:enterDoorPhase() instead of place_object:setBlueprintCells(). 

I think the setBlueprintCells() check which is failing for radiators is the World:isFootprintTileBuildableOrPassable() check. So I think the code which places doors must be not correctly changing the buildable flag for their footprint cells.

**Comment by tobylane** [comment]
I put a (corridor) radiator down then built toilets with the door in the adjacent block. The radiator was on the door side of its block. The room built fine with no warnings. On each patient use I get the following error as soon as he starts towards the toilets. Patients pass fine with any other radiator orientation.

> Empty action queue!
Last action: walk
stack traceback:
	./Lua/entities/humanoid.lua:546: in upvalue 'Humanoid_startAction'
	./Lua/entities/humanoid.lua:672: in local 'timer_function'
	./Lua/entity.lua:219: in method 'tick'
	./Lua/world.lua:1064: in method 'onTick'
	./Lua/app.lua:979: in function <./Lua/app.lua:976>
	(...tail calls...)
	./Lua/app.lua:880: in function <./Lua/app.lua:875>

**Comment by TheCycoONE** [comment]
Fixed by #1163
