### ISSUE TITLE
[Bug] Psychiatric couch tiles are not passable

### ISSUE THREAD

**Issue by SilPho** [CorsixTH/CorsixTH#2211]
### Describe the issue

After enabling the debug flag for "Allow blocking off areas" it is possible to build a Psychiatry room like this:
![image](https://user-images.githubusercontent.com/22282491/183240504-5d9c9359-e36d-4481-8a38-93219e286ecf.png)

The room looks functional, but the game crashes when a patient enters the room because the doctor is unable to path to the comfy chair.
The tile in front of the long couch and the plant combine to make it impossible to reach that chair.

### Steps to Reproduce

1. Load save game attached to this ticket

2. Wait for the patient to enter the Psychiatry room

3. Observe crash when the doctor's pathfinding starts.

To prevent the bug from happening, simply move the plant.

### Expected Behaviour

The game doesn't crash. Instead, the doctor chooses a path that takes him over the tiles in front of the long couch.

### Save Game

Save game attached to report: Yes
[PsychiatryPathing.zip](https://github.com/CorsixTH/CorsixTH/files/9274687/PsychiatryPathing.zip)

### CorsixTH Version

Release 0.66

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by SilPho** [comment]
For the attention of @lewri

**Comment by lewri** [comment]
Slightly related to the #826 meta but was more of a coding error really. PR to push shortly
