### ISSUE TITLE
macos_luarocks not parsing correctly?

### ISSUE THREAD

**Issue by tomkidd** [CorsixTH/CorsixTH#2213]
When I fire off a build of CorsixTH, at some point in the process I see this:

```
-- fixup_bundle: done
Usage: luarocks install [-h] [--keep] [--force] [--force-fast]
       [--only-deps] [--no-doc] [--verify] [--check-lua-versions]
       [--deps-mode <mode>] [--no-manifest] [--pin] <rock> [<version>]

Error: malformed argument 'dylib (compatibility version 5.4'
```

As near as I can tell, `macos_luarocks` is parsing the `otool` output in order to ascertain the Lua version to pass to luarocks.

So this line

`lua="$(otool -L ../MacOS/CorsixTH | grep 'lua' | cut -d. -f4-5)"`

is parsing out this

`@executable_path/../Frameworks/liblua.dylib (compatibility version 5.4.0, current version 5.4.4)`

And coming up with this

`dylib (compatibility version 5.4`

when it wants to come up with just `5.4`

Probably wouldn't be hard to fix, except it's odd if I'm running into this and no one else is. Any idea what I'm doing wrong?

**Comment by colinjmatt** [comment]
I don't recall ever seeing this issue when building, which means certain versioning outputs probably aren't compatible with the luarocks script.

Out of interest, are you following our wiki page for compiling for MacOS?

**Comment by tobylane** [comment]
I'd like to get it more reliable, cut isn't the way. Both of these (bsd and gnu grep) return "5.4".

````bash
$ echo "@executable_path/../Frameworks/liblua.dylib (compatibility version 5.4.0, current version 5.4.4)" | grep -o "5\.\d" | head -1
$ echo "@executable_path/../Frameworks/liblua.dylib (compatibility version 5.4.0, current version 5.4.4)" | ggrep -o -Pe "5\.\d" | head -1
````
Suggestion: replace line 38-9 with something like this.
````bash
# If GNU grep is installed, extra switches are needed for Perl regex
if grep --version | grep -q 'GNU'; then grepopt="-Pe"; fi
if otool -L ../MacOS/CorsixTH | grep -q 'lua'; then
  lua="$(otool -L ../MacOS/CorsixTH | grep 'lua' | grep -o $grepopt "5\.\d" | head -1)"
````
Also, not relevant to this issue, the install luasec line assumes homebrew on intel, it shouldn't guess either.

**Comment by Alberth289346** [comment]
`sed -e "s/.*current version  *//" -e "s/ *)//"` (delete everything before the 5.4 number, then delete spaces and closing bracket.

String manipulation is horrible in a shell though, writing a python or lua program or so for it is much simpler and more reliable.

**Comment by Alberth289346** [comment]
Can be done in one `-e` argument too, but gets a little more hairy then.
