### ISSUE TITLE
Map Editor Wiki needs refresh

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2216]
The Wiki page for the [Map Editor](https://github.com/CorsixTH/CorsixTH/wiki/Map-Editor) needs updating to the new version.
This would be an ideal time to look into it as we prepare everything for Community Content.

**Comment by SilPho** [comment]
How hard could it be? ;) I'll take a look at this one over the next few days

**Comment by TheCycoONE** [comment]
That would be great, to be clear new version in this case meant Albert and I completely rewrote it from an independent wxwidget app into part of the game.

**Comment by SilPho** [comment]
The wiki is now up to date :) If anyone spots any errors feel free to correct them, but I'm also happy to do it myself if there's any major re-work needed.

**Comment by lewri** [comment]
Thank you looks good.

It may be worth adding some additional notes about roads and paths. I don't specifically know how they work but it seems you need at least 1 road with paths for spawn points. (or maybe it's just a path to the end of the map?)

**Comment by lewri** [comment]
Page has been sufficiently updated to our new system, and many helpful tips. :)
