### ISSUE TITLE
can support chinese audio

### ISSUE THREAD

**Issue by loo100** [CorsixTH/CorsixTH#2228]
### What feature or enhancement would you like to add?

can support chinese audio (Mac)

### How would this feature benefit the gameplay of CorsixTH?

expect！

### Was the feature in the original game?

Yes

### What version of CorsixTH are you using?

0.66

### Does this feature/enhancement relate to a current problem?

No

**Comment by lewri** [comment]
I'm not aware that TH ever had official Chinese audio (likely similar situation to #2066 ). I'm guessing if one existed, it was an unofficial patch.

Likely will be a long way off before we load in our own audio.

**Comment by lewri** [comment]
Until we get close to developing our own sound files, we won't support sound files from other languages except the base ones.
You may be able to forcibly use them though the suggestion from mugmuggy.
