### ISSUE TITLE
[Bug] Give a summary of the problem

### ISSUE THREAD

**Issue by Xcl4m4t10n** [CorsixTH/CorsixTH#2243]
### Describe the issue

After building a room (any type), if you go to edit mode deconstruct it (until light blue/first construction step ) and then, edit the size outside the hospital, and then cancel the build and "cancel the cancellation", you can build the room outside the limits of the hospital.
![imagen](https://user-images.githubusercontent.com/35381298/190746846-be8bfe70-ed4a-4be5-8aab-0725a64c37f0.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747009-44c4e521-5002-42aa-bbcc-a660c5ed363e.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747137-43ce8856-a3c7-44fb-955e-b74b056c2734.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747243-737e2eef-9fb5-4c37-b54e-5c0718bb95ed.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747358-a8df5258-fb2f-46fd-819e-04b573e046c6.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747424-a37e39d3-6190-479b-94e8-fe935e50b5be.png)
![imagen](https://user-images.githubusercontent.com/35381298/190747562-9a04291c-c741-463b-af14-e8cff4df0818.png)

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. 

3.

### Expected Behaviour

Not be able to build outside the hospital.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
WIll note into the other issue log
