### ISSUE TITLE
[Bug] Serious Radiation epidemic with no serious radiation patients

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2256]
### Describe the issue

Game gave me a serious radiation epidemic with no radiation patients to cure, saves "bug3", "bug2" and "bug1" are the progression of months following the issue, save "prebug" is the month before the issue, and "bugtrigger" has the issue triggered, but the epidemic hasn't been accepted yet.

### Steps to Reproduce

1. *Load save games attached to this ticket*

### Expected Behaviour

Give me patients to cure

### Save Game

[Saves.tar.gz](https://github.com/CorsixTH/CorsixTH/files/9660715/Saves.tar.gz)

### CorsixTH Version

0.66

### Operating System

Win10

### Theme Hospital Version

GOG.com

**Comment by TheCycoONE** [comment]
There is a patient 0 in your save:
```
humanoid - class: Standard Female Patient
Warmth: 0.216   Happiness: 0.979   Fatigue: 0.000  Thirst: 0.542  Toilet_Need: 0.339   Health: 0.764   Service Quality: 0.000
Actions: [idle]
going_home:false
dead:false
has_passed_reception:true
```

however they don't have a tile_x or tile_y and are not actually patients in the hospital which makes me suspect they despawned before the fax was read.

The fax should have come up on the same tick that one of the contagious patients was diagnosed. Both patients are diagnosed, so I'm not sure if there was some delay here that let them leave or exactly how it ended up like this.

**Comment by TheCycoONE** [comment]
Actually the epidemic would have been delayed by the emergency you just finished, so that explains the gap. We need hasNoInfectedPatients to return true so that the epidemic would just be removed in that state, `checkPatientsForRemoval` doesn't account for patients with no tile_x/tile_y and it probably should.

**Comment by TheCycoONE** [comment]
Note the fix in the above PR corrects your pre save. Once the fax is triggered with no patients the issue persists, but at least there is no fine now.

**Comment by mugmuggy** [comment]
MRMIdAS killed the infected patients in the research dept. Thats how we end up with not dead and not going_home. Probably set them to dead in ResearchRoom after_use_autopsy. This would allow the dangling pointer to be invalidated without fixing the semi bad state as a permanent solution.

**Comment by lewri** [comment]
> Probably set them to dead in ResearchRoom after_use_autopsy

Do autopsy patients usually count towards killed in the game?

**Comment by mugmuggy** [comment]
No

**Comment by lewri** [comment]
In that case, when setting them as dead you want to make sure you're not increasing the number killed count I guess.

**Comment by MRMIdAS** [comment]
Yeah, During the Emergency I sent a patient to the Research department, it
was likely her.
