### ISSUE TITLE
[Bug] Infectious diseases can transfer to any patient

### ISSUE THREAD

**Issue by MRMIdAS** [CorsixTH/CorsixTH#2258]
### Describe the issue

Got an infectious Laughter CD, One of the patients managed to pass said disease to a patient who was glowing, a serious radiation patient.

Said patient proceeded to psychiatric, was cured, lost his glow and left.
![contagious](https://user-images.githubusercontent.com/1302977/193368022-77043060-5974-4096-87a7-137fbd9b9994.png)

EDIT:
And now inversely, A Radiation patient has infected a non-radiation patient, and visually, the patient didn't change.

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. 

3.

### Expected Behaviour

Patients with graphical effects, such as Radiation and Jellyitis, should not be able to catch contagious diseases.

### Save Game

[Infectious Bug.sav.gz](https://github.com/CorsixTH/CorsixTH/files/9688100/Infectious.Bug.sav.gz)

### CorsixTH Version

0.66

### Operating System

Win10

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
Hmm,

I'm wondering if when we added the serious radiation glow in 0.66 we didn't turn off ability to spread

**Comment by SilPho** [comment]
serious_radiation is currently set as `disease.contagious = true`. As far as I can tell that's the only thing we'd need to change, right?

**Comment by lewri** [comment]
> serious_radiation is currently set as `disease.contagious = true`. As far as I can tell that's the only thing we'd need to change, right?

Yes that would do it. I'd also check jellyitis too as that was changed in 0.66

**Comment by SilPho** [comment]
Good idea. Fortunately, Jellyitis was already not contagious.

No other visual diseases seem to fall into this trap either.
