### ISSUE TITLE
[Bug] Debug: Map Overlay Flags is not dynamically updated

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2261]
### Describe the issue

If you load up Map Overlay 'flags' option and buy a new plot, the overlay does not update to include the new plot area.

### Steps to Reproduce

1. Load a new game/single scenario with multiple plots

2.  Activate debug > map overlay > flags

3. Buy a new plot.

### Expected Behaviour

The map overlay should request an update when a plot purchase happens.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

![image](https://user-images.githubusercontent.com/20030128/193410599-d87951f2-8ad2-4af7-82aa-f46d21a69cf2.png)

**Comment by lewri** [comment]
A slightly separate issue, but loading up a save with Map Overlay on causes that setting to stay active in the system, but not actually display any overlay.

**Comment by mugmuggy** [comment]
Build while paused is blocking the updating of the flags

**Comment by lewri** [comment]
Interesting, thanks mugmuggy

**Comment by lewri** [comment]
Closing for now unless someone else brings this one up (it's more of a developer overlay anyway) or we want it open still.
