### ISSUE TITLE
Check for update still on 0.65

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2263]
Noticed while debugging some stuff yesterday. Check for updates hasn't recognised 0.66 is available.

https://corsixth.com/CorsixTH/check-for-updates
![unknown-11](https://user-images.githubusercontent.com/20030128/193447498-81045911-c0b1-472c-bc32-a56f124e3b46.png)

**Comment by TheCycoONE** [comment]
Try now

**Comment by lewri** [comment]
Yes it works now. Odd that file isn't viewable in the repo. Probably missed from the preparing for release wiki I guess

**Comment by TheCycoONE** [comment]
The file is on the gh-pages branch, due to the way github pages work.
