### ISSUE TITLE
Toggle on/off check for CorsixTH updates

### ISSUE THREAD

**Issue by Paelor** [CorsixTH/CorsixTH#2274]
### What feature or enhancement would you like to add?

I would like the option to toggle on/off the checking for CorsixTH updates when the game starts, which displays in the log window. I'm not always around an internet connection and if I wanted to know if there was a new release, I would just check the GitHub page when I was online. 

### How would this feature benefit the gameplay of CorsixTH?

It wouldn't benefit the gameplay, it is just an annoyance that CorsixTH checks for updates at every startup. A toggle on/off in the settings menu shouldn't be to hard to implement.. not all of us are online 24/7. 

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.66

**Comment by mugmuggy** [comment]
Probably should be but you can do it yourself, https://github.com/CorsixTH/CorsixTH/wiki/Configuration-File
check_for_updates

**Comment by Paelor** [comment]
First of all, thank you. I didn't know the location of that file existed. While it does solve my problem, it would be more convenient if it could be toggled within the game settings.

**Comment by lewri** [comment]
Ideally we do want users to update when they can.

However, it would be better if the update check could exit prematurely if there's no network connection (but may not actually have any benefit with how we use luasocket.

Not fully against adding a GUI config option into the settings menu, though this would take longer to develop. If updates are disabled, I would like something specifically on the main menu to inform you updates are not being checked.

**Comment by TheCycoONE** [comment]
Some people presumably don't want the game making network calls. I can sympathize with that.

**Comment by Paelor** [comment]
lewri you're awesome, thank you!
