### ISSUE TITLE
[Bug] Meta-table Date compare function crashes

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#2290]
### Describe the issue

``` lua
-- date.lua
function Date_mt.__eq(one, other)
  print("one:")
  for k, v in pairs(one) do print(k,v) end
  print("other:")
  for k, v in pairs(other) do print(k,v) end
  return one:isSameDay(other) and one._hour == other._hour
end

-- utility.lua
for _, ref in ipairs(pt_reflist) do
    if ref == obj then -- line 325

```
Output
``` text
one:
start_activity	table: 0x5635a7507cf0
other:
_hour	45
_month	1
_day	30
_year	1
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
/home/alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/date.lua:275: attempt to call a nil value (method 'isSameDay')
stack traceback:
	/home/alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/date.lua:275: in metamethod '__eq'
	.../alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/utility.lua:336: in function <.../alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/utility.lua:325>
	(...tail calls...)
	.../alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/utility.lua:375: in function <.../alberth/dev/corsix-th/npc_repo/CorsixTH/Lua/utility.lua:325>
	(...tail calls...)
...
```
`one` is an `Activity` class without meta-table unless it is added by default.
`other` looks like a `Date` instance.

The code arrives in date comparison, but that is the `other` value. An `Activity` has not such comparison and thus it crashes.

### Steps to Reproduce

I have a save, but it also needs my experimental code, so likely not much use.

### Expected Behaviour

Not crash at least.

Also it seems weird that Lua finds and runs the `Date` comparison but can't bother to ensure the `Date` instance is at the expected spot.

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

custom

### Operating System

something

### Theme Hospital Version

CD

**Comment by Alberth289346** [comment]
Actually, `one` is only a table, not a class instance.

**Comment by lewri** [comment]
Does this currently affect any active code we have, or is this an affected case we don't use yet?

**Comment by Alberth289346** [comment]
The `Date` equality function (testing `date1 == date2`) is being used in a way we don't expect, basically with `{...} == date`, currently in the `serialize` function (line 325 to detect cycles).

We currently don't try that and likely compare dates only with other dates. (A similar case is `date == {...}` which is probably also not expected, although it may show different behavior other than a crash.)

**Comment by lewri** [comment]
So the error gets generated from here?
https://github.com/CorsixTH/CorsixTH/blob/6146a48aa1fd4ed43802d17b83ec62726648569b/CorsixTH/Lua/utility.lua#L331-L333

**Comment by Alberth289346** [comment]
Actually, just below it: `if ref == obj then`

The compare code looks for `__eq` in a metatable in some way of the compared objects, and if found it jumps to that function to perform the comparison. So that's how it ends up in `date.lua`.

The original bug was that we assumed the first object would be a `Date` instance. Common practice in many lanuages but not in Lua apparently. So after Lua found the meta table and jumped to the right function, you need to do all the deduction of Lua again to find out where the `Date` object actually is.
I added the restriction that both sides should be`Date` instances with `class.is`.
(I thought I added the patch here, but apparently not.)

However, that `class.is` function uses `==` again and Lua resolves that to the `__eq` function in `date.lua` again, and ends up back at the `__eq` function, where it finds my added restriction ... and so on until you run out of memory.

In my view classes and instances are different things, so Lua ending up at `__eq` of `Date` instances from `class.is` is just plain wrong.

**Comment by Alberth289346** [comment]
For completeness the additional check I added in `__eq` again:
``` patch
diff --git a/CorsixTH/Lua/date.lua b/CorsixTH/Lua/date.lua
index 90758823..4bd839ea 100644
--- a/CorsixTH/Lua/date.lua
+++ b/CorsixTH/Lua/date.lua
@@ -268,10 +268,17 @@ end
 local Date_mt = Date._metatable
 
 function Date_mt.__eq(one, other)
+  if not class.is(one, Date) or not class.is(other, Date) then return false end
   return one:isSameDay(other) and one._hour == other._hour
 end
 
 function Date_mt.__lt(one, other)
+  if class.is(one, Date) then
+    if not class.is(other, Date) then return false end
+  else
+    if class.is(other, Date) then return true end
+    return false
+  end
   if one._year ~= other._year then return one._year < other._year end
   if one._month ~= other._month then return one._month < other._month end
   if one._day ~= other._day then return one._day < other._day end
@@ -279,6 +286,12 @@ function Date_mt.__lt(one, other)
 end
 
 function Date_mt.__le(one, other)
+  if class.is(one, Date) then
+    if not class.is(other, Date) then return false end
+  else
+    if class.is(other, Date) then return true end
+    return false
+  end
   if one._year ~= other._year then return one._year < other._year end
   if one._month ~= other._month then return one._month < other._month end
   if one._day ~= other._day then return one._day < other._day end
```
