### ISSUE TITLE
save_to_tmp string is too specific

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2294]
```lua
save_to_tmp = "The file at %s could not be used. The game has been saved to %s. Error: %s",
```

This string is used for when we run into a file saving issue and need to save to a temporary location. However, the string currently references `game`, whereas it could be other files that run into issues. As such below, the context doesn't fit:
![image](https://user-images.githubusercontent.com/20030128/204362267-f88535c8-05c7-4483-8534-7be009f4cd3d.png)

There are two routes to resolve this:
1. Amend the string to be more generalised **OR**
2. Create a set of contextual based strings based on the kind of file it had issues with (e.g. a save, config file, gamelog file). A supporting function should assist other code in grabbing the right error text (rather than individual strings in each function).

Pulled from #2291

**Comment by MandrakeHorse** [comment]
Proposed replacement from #2291:

```
save_to_tmp = "Attempt to write to %s failed. File was written instead to temporary location %s because of the error: %s",
```
