### ISSUE TITLE
[Improved feature needed] ÷ Played the game ver 0.66

### ISSUE THREAD

**Issue by tirinkun** [CorsixTH/CorsixTH#2295]
### Describe the issue

The patients are too few need spawn more and the avail doctors doesnt have enough specialist, like always missing one of the 3 skills, I know it's random but in original game you could always find enough specialized doctor just they are good enough or not

### Steps to Reproduce

1.  Start the game in single scenario, the last map with "nearby swamp" version 0.66

2. 

3.

### Expected Behaviour

Right after choose open hospital, patients should come right away instead of waiting like 5 more min and the number is larger in quality, doctor should at least have enough varies specialist

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
Spawn related to #649

Other one is controlled in the `.level` file related to that scenario. It would likely mean the creator did not balance doctor specialism availability well. We wouldn't seek to fix this as it was a legacy community contributed level.
