### ISSUE TITLE
Game crash from drawWrapped when using unicode font.

### ISSUE THREAD

**Issue by divajsz** [CorsixTH/CorsixTH#2296]
While I was browsing employees there were several cases when the same person's page crashed the game. I loaded the autosave and if I repeated the steps the game hung on the exact same person's page again -> bug can be reproduced with savegame

If I avoided the browsing for a while and different people came up in the list there were no crashes.

**Comment by SilPho** [comment]
Could you upload the savegame and list the steps you took that led to the crash?

**Comment by divajsz** [comment]
[Autosave12.zip](https://github.com/CorsixTH/CorsixTH/files/10252145/Autosave12.zip)

If you immediately want to hire an other doctor, click on next and the game will crash immediately

**Comment by lewri** [comment]
Were you playing a specific language? Do you remember the person for hire's name being notable?

**Comment by divajsz** [comment]
Yes, I'm playing hungarian language. The second person is the buggy one, T.Andlin. Just checked again, same crash.

**Comment by divajsz** [comment]
But it happened again later 2-3 times on on different map with different people I just tried to get back to autosave then trying not to hire for 10-15 minutes.

**Comment by lewri** [comment]
English is fine.

Crash confirmed when playing in Hungarian.

**Comment by lewri** [comment]
I'm not 100% if it's the strings of T Andlin or the next doctor that crashes. But I would guess it's a string issue somewhere.

Unfortunately I can't ascertain what the string is in Hungarian as I think the context was changed (in English it was "Raffia worker instructor" on the next doctor. The two other strings used are the same on both Andlin and the next doctor.

**Comment by lewri** [comment]
It's a specific error on this Hungarian text. If I change the text to "dummy" it's fine

`Bambuszács szakkör vezetője.`

All the characters used in that string exist in other places of the language file. Can't see anything specific  about why it would crash the game.

**Comment by lewri** [comment]
Problem is happening from `font:drawWrapped` (specifically the wrapped function. Not sure why yet.

**Comment by lewri** [comment]
@TheCycoONE this is a regression caused by #2045 (luckily I had the old appveyor builds)

**Comment by lokpro** [comment]
Hi @divajsz , is it a crash (disappearing or error message) or freeze?

**Comment by divajsz** [comment]
Hi @lokpro, hi Everyone

It was a complete freeze of the application. There was no way to keep it running. I had to kill the process then restart the game again. I continued with autosave or previous save.
