### ISSUE TITLE
[Bug] Can't install on Mac OS 12.2.1 Monterey

### ISSUE THREAD

**Issue by seotom** [CorsixTH/CorsixTH#2297]
### Describe the issue

Hey guys, I can't install the last .dmg release on my Mac OS Monterey 12.2.1. The main problem is that when selecting the directory to install the files, the action is not confirmed. That is, I click on OK, but nothing happens. See attach. 

I am asking for your help.
 
<img width="789" alt="Screenshot at Dec 24 22-58-53" src="https://user-images.githubusercontent.com/75537781/209443399-4f621b92-b432-4433-8b97-f66b71d22d96.png">

### Steps to Reproduce

I downloaded the latest release (CorsixTH 0.66) and when I run it, it asks for the path to install the files. At this step the problem - I select the right directory, click OK, but nothing happens.

### Expected Behaviour

I couldn't start the game :)

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.66

### Operating System

Mac OS Monterey

### Theme Hospital Version

GOG.com

**Comment by colinjmatt** [comment]
Are you pointing the picker to the original files that are required?

**Comment by TheCycoONE** [comment]
Your screenshot is not showing a location to install the files, it's asking for the location where the original game files already exist. CorsixTH requires Theme Hospital to run.
