### ISSUE TITLE
Typo/grammar issue in english.lua line 82

### ISSUE THREAD

**Issue by netvor** [CorsixTH/CorsixTH#2300]
While enjoying this excellent game, stumbled upon an error in the briefing text: "have sightings of UFOs" should be "have **been** sightings of UFOs"

https://github.com/CorsixTH/CorsixTH/blob/d89a8a1ade452df5a15010f9f09558b09ab232d9/CorsixTH/Lua/languages/english.lua#L82

**Comment by TonyBhargav** [comment]
hi @netvor, can you please assign this issue to me. I'd like to contribute. As a first time contributer this will be helpfull.
Thank you
