### ISSUE TITLE
[Bug] Some objects disappear from map at edge before going off-screen

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2304]
### Describe the issue

The seems to only be affecting objects that have a resulting usage animation where that object can be placed in all 4 directions. And in only one of their orientations (I think south-facing, but the skew of the game confuses me).
Currently noted objects: Sofa, Bed, Bench (north facing?)

This appears to have broken in 0.66, working in 0.65.
It also breaks with direct_zoom being enabled; when disabled it is fine.

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. 

3.

### Expected Behaviour

Objects shouldn't be removed from view while still on screen

### Save Game

Save game attached to report: Yes

Included for an example with the benches; save a little abused but should work 'enough' in 0.66 and dev.
[debug queue overflow.zip](https://github.com/CorsixTH/CorsixTH/files/10669546/debug.queue.overflow.zip)

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

![image](https://user-images.githubusercontent.com/20030128/217097545-1f4a18de-831b-4391-bd32-a96561901833.png)
![image](https://user-images.githubusercontent.com/20030128/217098340-8c227458-7f15-492b-ae9c-41de090cce12.png)

**Comment by flackr** [comment]
The issue may be that we use the raw canvas height for this clip call in `animation::draw`:
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Src/th_gfx.cpp#L1157

When zoomed out, this is multiplied by a draw_scale() < 1 which could clip content which would normally be on screen.

**Comment by flackr** [comment]
Yup, confirmed the issue is exactly this. I *think* that nothing else should be using getWidth / getHeight expecting to get the non-zoomed screen size while draw_scale is set - it doesn't really make sense to do that since any subsequent drawing commands are scaled.
