### ISSUE TITLE
UIInformation box is loading pink

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2308]
Not sure if this relates to #2279 as it's not present in 0.66 but UIInformation when generated at load is pink.
![image](https://user-images.githubusercontent.com/20030128/218836222-9ad9a0c1-15bf-4125-941b-3f6a3d66a267.png)

Doesn't happen if the save fails to load (error on load)

Does happen if we generate a new UIInformation during gameplay (regardless of very_old_save message or not)
![image](https://user-images.githubusercontent.com/20030128/218837015-9a02460c-7a7c-479a-a999-ce109cb4a591.png)

Edit: Didn't notice before but the tooltip can also load yellow on that box
![image](https://user-images.githubusercontent.com/20030128/225140506-5a0cb6c0-bce7-4220-8643-0c294f6f8ea1.png)

**Comment by lewri** [comment]
(Safe to say, I almost prefer the change in colour, though I imagine this isn't the intended behaviour or method of getting the colour)

**Comment by lewri** [comment]
Another one has popped up when loading a test build from #2310 
![image](https://user-images.githubusercontent.com/20030128/219865643-859d23e3-8cbf-4b86-8f3e-4c84086ec136.png)

**Comment by mugmuggy** [comment]
To add to that last example. If loading the demo one first up. The dialog appears fine. If load a full one, and quit using the FILE menu, then load demo, appears fine. If load a full one up and then go into the FILE menu, and load again the demo (don't quit straight load), dialog does not appear fine.

**Comment by lewri** [comment]
When I loaded a trunk save that happened after 0.66 but before #2279 I get this console warning:
`Warning: palette PREF01V.PAL requested with different flags than stored`

It doesn't happen with a normal run from 0.66

**Comment by ryanpenfold** [comment]
Recieved same issue, but with 0.67-beta1 Windows 11
![image](https://github.com/CorsixTH/CorsixTH/assets/110283510
[Autosave1.zip](https://github.com/CorsixTH/CorsixTH/files/12138408/Autosave1.zip)
/32397eea-3f8a-4536-af8f-79a11d4418c8)
``Warning: palette Award02V.pal requested with different flags than stored``
I've also attached the save file, if you just load it it reproduces above.

**Comment by TheCycoONE** [comment]
```
Loading Town01V.pal with flag
stack traceback:
        E:/GitHub/CorsixTH/CorsixTH/Lua\graphics.lua:238: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\graphics.lua:234>
        (...tail calls...)
        [C]: in function 'persist.load'
        E:/GitHub/CorsixTH/CorsixTH/Lua\persistance.lua:287: in function 'LoadGame'
        E:/GitHub/CorsixTH/CorsixTH/Lua\persistance.lua:326: in function 'LoadGameFile'
        (...tail calls...)
        [C]: in function 'pcall'
        ...sixTH/Lua\dialogs/resizables/file_browsers\load_game.lua:41: in method 'choiceMade'
        ...orsixTH/CorsixTH/Lua\dialogs/resizables\file_browser.lua:200: in field 'select_callback'
        E:/GitHub/CorsixTH/CorsixTH/Lua\dialogs\tree_ctrl.lua:636: in method 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\window.lua:1642: in method 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\window.lua:1642: in field 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\ui.lua:877: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\ui.lua:864>
        (...tail calls...)
        E:/GitHub/CorsixTH/CorsixTH/Lua\app.lua:1102: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\app.lua:1097>
Loading Town01V.pal without flag
stack traceback:
        E:/GitHub/CorsixTH/CorsixTH/Lua\graphics.lua:238: in method 'loadPalette'
        E:/GitHub/CorsixTH/CorsixTH/Lua\graphics.lua:296: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\graphics.lua:282>
        (...tail calls...)
        [C]: in function 'persist.load'
        E:/GitHub/CorsixTH/CorsixTH/Lua\persistance.lua:287: in function 'LoadGame'
        E:/GitHub/CorsixTH/CorsixTH/Lua\persistance.lua:326: in function 'LoadGameFile'
        (...tail calls...)
        [C]: in function 'pcall'
        ...sixTH/Lua\dialogs/resizables/file_browsers\load_game.lua:41: in method 'choiceMade'
        ...orsixTH/CorsixTH/Lua\dialogs/resizables\file_browser.lua:200: in field 'select_callback'
        E:/GitHub/CorsixTH/CorsixTH/Lua\dialogs\tree_ctrl.lua:636: in method 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\window.lua:1642: in method 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\window.lua:1642: in field 'onMouseUp'
        E:/GitHub/CorsixTH/CorsixTH/Lua\ui.lua:877: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\ui.lua:864>
        (...tail calls...)
        E:/GitHub/CorsixTH/CorsixTH/Lua\app.lua:1102: in function <E:/GitHub/CorsixTH/CorsixTH/Lua\app.lua:1097>
Warning: palette Town01V.pal requested with different flags than stored
Savegame version is 178 (v0.67-rc1), originally it was 178 (v0.67-rc1).
```

**Comment by TheCycoONE** [comment]
For what it's worth I can't reproduce the pink UIInformation

**Comment by lewri** [comment]
> For what it's worth I can't reproduce the pink UIInformation

If we do our usual thing of trying to support two versions behind in afterloads then 0.65 is getting the pink but 0.66 saves don't.
Tested with changes of #2368 no change to the pinking.

[065-avatar.zip](https://github.com/CorsixTH/CorsixTH/files/12209228/065-avatar.zip)

**Comment by lewri** [comment]
This one still exists for the pink
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/178bb065-4136-4866-891b-2d00767920b5)

I thin this one is a knock on of a level in created in an old savegame version that has been procedurally updated to 0.67 over time. 
If such a game is loaded, it causes the entire game to get the pink attributes until CorsixTH is restarted.

My assumption is that the font palette issue for some things isn't getting properly reset whenever a game goes back to the main menu; or a new save is loaded.

**Comment by lewri** [comment]
Replicated now in moving a save from 0.66 to 0.67 which we should aim to support.
[0-66 fresh.zip](https://github.com/CorsixTH/CorsixTH/files/14487358/0-66.fresh.zip)

if you go to and reopen the briefing on that save it will load in pink.

**Comment by lewri** [comment]
This one is back again. If you open the spriteviewer and close it, UIInformation and tooltips will load pink text instead of black.

<img width="334" height="126" alt="Image" src="https://github.com/user-attachments/assets/b1a3b1ea-c4a6-450f-87e8-21aea4cb4788" />

Essentially it affects anything loading this:
`loadFontAndSpriteTable("QData", "Font00V")`


Edit: For some reason loading Font01V instead in sprite viewer doesn't cause this behaviour with other things that use Font01V. I'm not sure what is special about Font00V.
