### ISSUE TITLE
[Bug] Changing music volume level also changes the all sound volume level.

### ISSUE THREAD

**Issue by astorun** [CorsixTH/CorsixTH#2309]
### Describe the issue

There seems to be some kind of bug that also changes the music volume with all the other sound volume as well.

Music volume level act as a global sound volume level.

I am on corsixTH 0.66

### Steps to Reproduce

No special steps required. Changing music volume level causes the issue.

### Expected Behaviour

Music level should be adjusted only, not the whole sound output level

### Save Game

No

### CorsixTH Version

0.66

### Operating System

Windiws 11

### Theme Hospital Version

CD

**Comment by TheCycoONE** [comment]
This is an upstream bug with windows only. I'm sure we already have it filed.

**Comment by TheCycoONE** [comment]
Seems #524 is the closest we have
