### ISSUE TITLE
Can't see price of machine upgrade unless you can afford it

### ISSUE THREAD

**Issue by bennuttall** [CorsixTH/CorsixTH#2318]
### What feature or enhancement would you like to add?

If you *can* afford a machine upgrade, clicking the cog icon on the machine's dialogue shows you the price when confirming whether you want to proceed with the upgrade:

![Screenshot from 2023-04-17 21-17-03](https://user-images.githubusercontent.com/1609725/232600611-1319ff75-5783-4d16-9510-e3a8d6ee4332.png)

If you can't afford it, there's no way to find out how much it costs. It just ignores you clicking the cog, but the announcer message shows "You don't have enough money in the bank to make that purchase":

![Screenshot from 2023-04-17 21-17-53](https://user-images.githubusercontent.com/1609725/232600902-1fbb4fac-f7a0-4762-945f-eb6b98ee6aa9.png)

It would be nice if it showed either on the cog button (maybe on hover), after clicking the cog (in a similar box to the confirm purchase one), or perhaps in the bottom section where it tells you the machine's strength:

![Screenshot from 2023-04-11 23-46-11](https://user-images.githubusercontent.com/1609725/232601297-1b362b89-3bef-4553-b882-9f822efc23e5.png)

Alternatively, a menu dedicated to machine upgrades would be handy - list all machines and their current vs potential strength, upgrade cost etc.

### How would this feature benefit the gameplay of CorsixTH?

It's difficult not knowing how much an upgrade costs, and the cog button seemingly doing nothing is also frustrating. Showing the price would be useful to players. All other costs of rooms and items is given, regardless of affordability.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.66

### Does this feature/enhancement relate to a current problem?

No

**Comment by lewri** [comment]
Sounds like the UIConfirm (green box) only gets presented if it succeeds an affordability check. We might be able to do something where the check happens on the UIConfirm tick. Or we show the box anyway and grey out the tick.

Okay greying the box isn't possible sadly until new graphics. UIConfirm has a very limited spritesheet
![image](https://user-images.githubusercontent.com/20030128/232606445-2dd22ce5-d49b-4a71-8988-c6d56be5d557.png)

**Comment by lewri** [comment]
> Alternatively, a menu dedicated to machine upgrades would be handy - list all machines and their current vs potential strength, upgrade cost etc.

That's the plan of #2104 but I'm severely slacking on that one getting built.
