### ISSUE TITLE
Progress Report shows incorrect information with loans

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#232]
~~This was raised in the forum http://forums.corsixth.com/index.php/topic,5497.msg7713.html#new~~ Forum gone, pasted post below

> Hello,
> 
> I noticed that CorsixTH behaves different then the regular TH when it comes to the amount of your bank balance in regards to level failing targets. The difference is that loans are applied in CorsixTH
> 
> For example: On level 7 you fail if you are more then $1000 in debt.
> 
> So when I'm 500$ in debt, the Progress Report shows a red column thats 1/2 in height and the description reads: "Your bank account balance must be at least -1000. Currently ists -500".
> 
> I then take a loan of $5000 and therefore have $4500 in the bank which I can spend. Here's where it becomes different:
> 
> In the original TH: The Progress Report column  turns green again (with minimum height). The description still says I'm -500 but also tells me how much I need to win the level. Original TH apparently just cares about what you have in the bank to spend and I don't fail the level at the end of the year.
> 
> In CorsixTH: The Progress Report column remains red and 1/2 in height, telling me that I'm -500 and will loose at -1000. CorsixTH apparently calculates:
> 
> $4500 in the bank
> - $5000 in loans
> = -500 bank balance.
> 
> This difference makes CorsixTH so much harder then the original, because with level 7's -1000 requirement you are basically prohibited from keeping a loan untill the following year, and in the beginning when you have to expand your hospital that's (at least for me) almost impossible.
> 
> Hope you understand what I meant. Was this changed on purpose or is it a mix up?
> 
> Thanks!
> Hage

The red bar shows even if your balance is above the threshold for losing.  I think this is because on lines 204 - 207 we make a special case for the balance.
The special case should only apply to winning and losing, I think by having these lines for the bar is giving the wrong information.   For those that don't remember or know what the special case is, this was that it should be possible to get your bank balance above the losing threshold with loans as otherwise there is no point in having loans.  You can't though win with a loan. What shows in the status screen though is that you are still about to lose, whereas it should show that you are now safe from losing.
I have checked this against TH and what is said in the topic is right.

**Comment by lewri** [comment]
Could I clarify:

If you are over the losing threshold regardless of loans, you will lose.
If you have loans that take you under the losing threshold, you will be safe?

**Comment by mugmuggy** [comment]
Win/Lose logic looks fine in https://github.com/CorsixTH/CorsixTH/blob/644f4dddf402d9d7cd237f926901ce0fb974f407/CorsixTH/Lua/world.lua#L1366

The balance with loan on lose conditions was removed a long time ago https://github.com/CorsixTH/CorsixTH/commit/cee62ed4a0b750f40643539146b754acd8a7bf64

As this progress bar is supposed to represent how close you are to winning/or losing. If the bank balance is < 10k (the Bound value) it should be red.
#lose_criteria[1].Criteria.MaxMin.Value.Group.Bound	2	0	-1000		2	10000

In TH if balance is >10k, it should be green. The tooltip will changes from win/lose type wording based on the overall bank balance. ie on L7, buy every plot, left with 6500. Progress bar should be red, about 32% high. Take out 5k loan. Balance should be 11500, progress bar should be green, fairly low (Bound is 0). Both the red and green tooltip status show current balance as 6.5k. But this can go off track and it doesn't apply anymore.

It gets a little weird then if you go spend some on rooms, you'll have a balance above 0, but the status tooltips will say below -1000. Then take out more loans, and it goes green, but the status tooltip will say -5000 or something. So green/red flip is on the balance, and the tooltip is on balance-loan

**Comment by lewri** [comment]
Potentially a separate issue, but the tooiltip you mention @mugmuggy doesn't update on balance change by the look of things (it should be using a dynamic tooltip).

**Comment by SilPho** [comment]
This still happens in 0.66. Loans don't stop you losing a level for having too little money, which is different to the original game.

Interestingly, the tooltip for the original game seems to work the same way as CTH, it lists the correct negative value when you are deep in debt, but the original game treats win/failure based on your current bank balance. This leads to the following situation (Images taken from Original game)

Loan at $35k. Bank balance at about $3k
![Loan at 35](https://user-images.githubusercontent.com/22282491/190866766-a5370ff4-8eb2-418b-b932-1632b2386217.png)

Then, raise the loan to $50k. Bank balance now reads about $18k.
![Loan at 50](https://user-images.githubusercontent.com/22282491/190866784-2ce94850-21c7-48f8-a6ed-04d9947f835f.png)

What this ultimately means is that you can delay bankruptcy by increasing your loan, but in order to win the level you need enough bank balance to satisfy the criteria even after deducting a loan
