### ISSUE TITLE
[Bug] Crash in _StaffWaitToggle for loop

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2325]
### Describe the issue

Not investigated fully yet but loading the game when testing #2322 caused a crash in code added in #2135 

https://github.com/CorsixTH/CorsixTH/blob/00abd4b822539ba19d3e0b4373207d441258c0f2/CorsixTH/Lua/room.lua#L498-L519

Crashed a game updated to 0.66 (need to test a game made in 0.66).

### Steps to Reproduce

(Attempting to replicate in newer save)

### Expected Behaviour

No crash

### Save Game

Save game attached to report: No

### CorsixTH Version

#2322 artefacts (>0.66)

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Error in timer handler:
Lua\room.lua:514: bad argument #1 to 'for iterator' (table expected, got nil)
stack traceback:
        [C]: in function 'next'
        Lua\room.lua:514: in method '_staffWaitToggle'
        Lua\room.lua:526: in method 'commandEnteringPatient'
        Lua\room.lua:401: in function <Lua\room.lua:296>
        (...tail calls...)
        Lua\humanoid_actions\walk.lua:383: in field 'on_next_tile_set'
        Lua\humanoid_actions\walk.lua:185: in function <Lua\humanoid_actions\walk.lua:172>
        (...tail calls...)
        Lua\entity.lua:216: in method 'tick'
        Lua\world.lua:1074: in method 'onTick'
        Lua\app.lua:1184: in function <Lua\app.lua:1181>
        (...tail calls...)
        Lua\app.lua:1084: in function <Lua\app.lua:1079>
Warning: No event handler for timer
```

**Comment by lewri** [comment]
Hovering over my game it appears the crash occured on a patient trying to enter the toilet
![image](https://user-images.githubusercontent.com/20030128/236646920-f20f7e40-095b-4cc2-a0ef-129e02951a6a.png)

**Comment by lewri** [comment]
Tested in a new game with a debug patient -- crash occurs.

**Comment by lewri** [comment]
I think the fix is just a matter of excluding toilets?

**Comment by Alberth289346** [comment]
Don't know the actual situation precisely, but the solution sounds like adding a special case to hide a logic bug. Assuming a patient may go to the toilet while a doctor waits for them, the action logic should know both NPCs are not in the same room and act accordingly, I think. (The fact that one of the rooms is a toilet seems besides the point imho, it's not different from being in the corridor conceptually.)

**Comment by lewri** [comment]
As @mugmuggy had introduced the function it may help if he's available just to clarify what it was meant to do at toilets. If not, we'll just fix it best we can before release.

**Comment by tobylane** [comment]
[Autosave3.sav.zip](https://github.com/CorsixTH/CorsixTH/files/11680192/Autosave3.sav.zip)
It happens to the pharmacy nurse on the 11th of March.

**Comment by lewri** [comment]
> [Autosave3.sav.zip](https://github.com/CorsixTH/CorsixTH/files/11680192/Autosave3.sav.zip) It happens to the pharmacy nurse on the 11th of March.

I'm also concerned why the nurse fails to leave multiple times but that appears to be something else.

**Comment by lewri** [comment]
Plus I'm pretty sure that room placement doesn't help. You can see other patients queuing in the building down the path.

**Comment by lewri** [comment]
> [Autosave3.sav.zip](https://github.com/CorsixTH/CorsixTH/files/11680192/Autosave3.sav.zip) It happens to the pharmacy nurse on the 11th of March.

It's a bigger issue relating to #2135 again. It's due to how `Room:onHumanoidLeave(humanoid)` handles staff members leaving in that it unsets `self.staff_member`.
@tobylane can you try swapping out this function in room.lua with the below and let me know if you can make it crash in other scenarios.

```lua
--! Activates and deactivates the staff waiting for patient mood icon
-- and dynamic info text
--!param activate (bool) - true to activate, false or nil to deactivate
function Room:_staffWaitToggle(activate)
  local state = "deactivate"
  local dynamic_text = ""

  if activate then
    dynamic_text = _S.dynamic_info.staff.actions.waiting_for_patient
    state = "activate"
  end

  if not self.staff_member_set and self.staff_member then
    self.staff_member:setMood("staff_wait", state)
    self.staff_member:setDynamicInfoText(dynamic_text)
  elseif self.staff_member_set then
    for staff_member in pairs(self.staff_member_set) do
      staff_member:setMood("staff_wait", state)
      staff_member:setDynamicInfoText(dynamic_text)
    end
  -- else no targets to toggle
  end
end
```

**Comment by lewri** [comment]
I'm tempted to revert the problematic part of #2135 and #2333 instead

**Comment by tobylane** [comment]
> can you try swapping out this function in room.lua with the below and let me know if you can make it crash in other scenarios (or if staff with wait toggles are walking outside rooms).

I haven't had a crash in ten runs of that nurse leaving the room, or the next three levels.
