### ISSUE TITLE
[Bug] Pause Logic for Jukebox over-remembering

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2328]
### Describe the issue

Since our new change to MIDI playback, the jukebox is now remembering the position in the first song if you skip to the second song; then go back to the first song. This also happens if you hit stop, then play again and navigate back round to the first song.

### Steps to Reproduce

1. Load game post #2322

2.  Open jukebox and play a song. Skip forward to next song, then skip back

3. Stop the music. Play music again and loop round to first song played from 2.

### Expected Behaviour

Reset the song to play at beginning if 'stop' or 'next'/'previous' is selected.

### Save Game

Save game attached to report: No

### CorsixTH Version

After #2322

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

**Comment by TheCycoONE** [comment]
I see it too, appears that you don't have to invoke pause at all, but it acts like pause was pressed.

**Comment by TheCycoONE** [comment]
So this was always a bug with freesynth or any other music type / backend that doesn't support seek:

Mix_PlayMusic calls Mix_FadeInMusicPos(music, loops, 0, 0.0); https://github.com/libsdl-org/SDL_mixer/blob/142b884b67d226137298f56ab7e7e83b5580015d/src/music.c#L984

Mix_FadeInMusicPos calls music_internal_play with the position: https://github.com/libsdl-org/SDL_mixer/blob/142b884b67d226137298f56ab7e7e83b5580015d/src/music.c#L973

music_internal_play calls music_internal_position: https://github.com/libsdl-org/SDL_mixer/blob/142b884b67d226137298f56ab7e7e83b5580015d/src/music.c#LL1010C32-L1010C32 and that calls Seek to reset the position of the audio - but ONLY on backends that support Seek.

The fluidsynth backend in sdl2_mixer does not support Seek so this is a NOOP and the music just plays from the previous position.

A workaround would be to reload the music every play.

**Comment by TheCycoONE** [comment]
Notably fluidsynth itself does support seek, it's just not implemented in SDL_Mixer: https://www.fluidsynth.org/api/group__midi__player.html#gaab5fe5b25ff513919b138d77e079c75a

**Comment by TheCycoONE** [comment]
Filed an upstream ticket. Would rather contribute upstream than work around this in CorsixTH unless there's a better workaround than reloading.

**Comment by lewri** [comment]
@TheCycoONE is this now closable after https://github.com/libsdl-org/SDL_mixer/pull/592 ?

**Comment by TheCycoONE** [comment]
Yes, we can close as it's an upstream bug. It means we have to ship a version with the patch to avoid the bug; but I don't think any has been released yet. I'm applying the fix for the windows releases myself (in our vcpkg repo)
