### ISSUE TITLE
[Bug] crash to desktop on main menu

### ISSUE THREAD

**Issue by crispin259** [CorsixTH/CorsixTH#2331]
### Describe the issue

windows 11, installed, original files found (gog version).

Intro movie plays, goes to main menu. mouse is in top left corner of screen, frozen then crash to desktop.
Console crashes too.

No error message.

changed location of original files and installation of corsixth. uninstalled reinstalled corsixth in different locations but same issue.

Theme Hospital original works fine.

### Steps to Reproduce

installed theme hospital

installed corsixth

located original install folder

launched corsixth

### Expected Behaviour

corsixth to work

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.66 & 0.65

### Operating System

windows 11

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
Hello! I see you've put CorsixTH 0.65 down. Have you tried with 0.66?
https://github.com/CorsixTH/CorsixTH/releases/tag/v0.66

**Comment by crispin259** [comment]
hi sorry i meant 0.66, i tried an older version 0.65 but it still has the same issue.

**Comment by lewri** [comment]
Could you try our latest build from Appveyor? It's a Windows portable version so you just need to unzip the contents then click the CorsixTH.exe . It currently has a bug that needs addressing though that crashes on using a toilet (woohoo!) so isn't useful to play with.

https://ci.appveyor.com/project/TheCycoONE/corsixth/builds/47037445/artifacts

Hopefully whatever broke has been fixed by some vcpkg changes. Though unless the terminal/command window gave anything else except 'welcome to CorsixTH' we may be stuck.

**Comment by TheCycoONE** [comment]
Are there any updates available for your GPU drivers? This sounds more like a driver issue.

**Comment by lewri** [comment]
Have spun up a W11 VM, can't replicate anything in there.

**Comment by crispin259** [comment]
I'm using a laptop with intel onboard iris gfx, all drivers are up to date. That appveyor version works, but still nothing with the release. I originally thought it would be the drivers but after update, still nothing.

**Comment by lewri** [comment]
Hm.
Just to check have you used the Intel DSA for your updates? https://www.intel.co.uk/content/www/uk/en/support/detect.html

The next thing could be something askew in the Theme Hospital files; or the CorsixTH install.
Have you tried the CorsixTH Portable of 0.66? https://github.com/CorsixTH/CorsixTH/releases/download/v0.66/CorsixTH-0.66-Windows-x64.zip (it's an unzip and run thing again).

To rule out TH files there's also a link to the demo files in the wiki near the top: https://github.com/CorsixTH/CorsixTH/wiki/Getting-Started . Change the TH Data target in a working portable version then quit the game normally (Settings > Folders > TH Data) . Then open 0.66 again.

**Comment by TheCycoONE** [comment]
Since appveyor works the next version should work. I think we can close this. Maybe SDL fixed it.

**Comment by TheCycoONE** [comment]
In the meantime continue to use the appveyor builds.
