### ISSUE TITLE
Origin is now EA app (Download version of Theme Hospital still usable with CorsixTH?)

### ISSUE THREAD

**Issue by bobidle** [CorsixTH/CorsixTH#2338]
In https://github.com/CorsixTH/CorsixTH/blob/master/README.md?plain=1#L23 one of the download version of the original game link to Origin. But the Origin link redirects to a different download page.

`https://www.origin.com/en-gb/store/buy/theme-hospital-origin/pc-download/base-game/standard-edition`
-> `HTTP/2 301`
-> `https://www.ea.com/games/library/pc-download`

That might be the case since October 2022 https://en.wikipedia.org/wiki/Origin_(service)

Is it still possible to use the download version of Theme Hospital (via the EA app) together with CorsixTH? Does someone has an EA account to check that?

The game is available here: https://www.ea.com/games/theme/theme-hospital

**Comment by lewri** [comment]
As long as the original game assets haven't changed it will work. You likely will just have to update the folder location it installs to.
If you can provide us with the folder it installs in we can also update our 'check common folders' script.

**Comment by lewri** [comment]
To verify existing files you may want to also see https://github.com/CorsixTH/CorsixTH/issues/1939#issuecomment-864425818

**Comment by mugmuggy** [comment]
For EA... C:\Program Files\EA Games\Theme Hospital\data\Game

**Comment by lewri** [comment]
I will make the PR for this before Beta 2 is released if nobody else wishes to take it up
