### ISSUE TITLE
[Bug] Hungarian language does not appear

### ISSUE THREAD

**Issue by CsubAzUrmedve** [CorsixTH/CorsixTH#2362]
### Describe the issue

In the options there are a few languages that don't show up at all, including hungarian. The file is present but the game does not see it or something.

### Steps to Reproduce

1. Go to Settings

2. Select Game Languages

3. Hungarian is not present

### Expected Behaviour

I expected the option to be available since the translation is 100% complete.

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

v0.67-beta1 but it's present in older versions

### Operating System

Windows 11

### Theme Hospital Version

GOG.com

**Comment by lokpro** [comment]
Maybe it needs to select a font for Hungarian in the settings?

**Comment by lewri** [comment]
Can confirm Hungarian is appearing in 0.67-beta1 as intended.
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/d808dc43-3264-427d-a74e-c93623f5d36d)
A font needs to be selected first to display this language from Settings > Folders > Font ; or in the config.txt file under the `unicode_font` setting.
