### ISSUE TITLE
Default values on new installation

### ISSUE THREAD

**Issue by RednibCoding** [CorsixTH/CorsixTH#2371]
### What feature or enhancement would you like to add?

I would recommend setting the default for 'Fullscreen' to 'off' and 'Capture Mouse' to 'off'. Both settings can contribute to a less-than-ideal initial experience for new users.

When I first launched the game in fullscreen, my instinct was to switch it to windowed mode. However, the window appeared on the wrong monitor (I have three) and when I attempted to grab the title bar, the mouse got captured. As you can see, these settings can lead to some initial confusion and frustration.

### How would this feature benefit the gameplay of CorsixTH?

These settings may not directly affect gameplay, but they could potentially cause annoyance to users. If a player is frustrated, they may be more inclined to just delete the game.

We wouldn't want that to happen, would we? :

### Was the feature in the original game?

Unsure

### What version of CorsixTH are you using?

v.067-rc1

### Does this feature/enhancement relate to a current problem?

No

**Comment by tobylane** [comment]
The fullscreen default setting in config_finder.lua:97 is false, but in Win32Script.nsi:257 it's true. That installer config could do with some updates like your suggestion.

**Comment by RednibCoding** [comment]
I would do it quickly

**Comment by lewri** [comment]
There are still parts of this issue we didn't correct because of the release time. Did we want to reopen to discuss?
