### ISSUE TITLE
Add ability to change mouse options for panning

### ISSUE THREAD

**Issue by RednibCoding** [CorsixTH/CorsixTH#2372]
### What feature or enhancement would you like to add?

In the current game settings, viewport panning is strictly set to the middle mouse button. However, a trend in modern games assigns this function to the right mouse button and uses the middle button for rotation.

To enhance user experience and increase the game's alignment with current standards, it would be beneficial to provide an option to customize these controls. This would allow players to choose between using the middle or right mouse button for viewport panning based on their personal preferences or habits formed by other games

### How would this feature benefit the gameplay of CorsixTH?

Incorporating user-customizable controls, specifically for viewport panning, it could significantly enhance gameplay experience for several reasons:

1. Familiarity: Many modern games utilize the right mouse button for viewport panning and the middle button for rotation. Players familiar with this control scheme may find it more intuitive to use similar settings in CorsixTH.

2. Comfort: Not all mice are designed with equally accessible middle buttons. For some users, it might be physically more comfortable (me included) to use the right mouse button for frequent actions like viewport panning.

3. Personalization: Allowing users to customize their controls provides a level of personalization that can improve overall player engagement and satisfaction with the game. It demonstrates the developers' commitment to accommodating diverse player preferences and could increase the game's appeal to a broader audience.

While this feature might not directly impact the core gameplay mechanics, it can enhance the overall user experience by making the game more intuitive, comfortable, and personalized.

### Was the feature in the original game?

Unsure

### What version of CorsixTH are you using?

v0.67-rc1

### Does this feature/enhancement relate to a current problem?

No

**Comment by lewri** [comment]
It's likely middle mouse was left in because it was the original behaviour of TH. However, Corsix also lets you pan using the arrow keys (up down etc).

I use wasd myself by configuring the hotkey/button config. However, the `D` interferes with other hotkeys. The hotkey window below lets you change the keyboard keys.
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/43aa9785-5ebd-4c98-9120-9ba1c11deb9c)

Mouse configs may be useful, but it'll need more implementation. RMB is not tied to anything as far as I can see though. I see no issue making an option to toggle mouse pan between MMB and RMB.

**Comment by Alberth289346** [comment]
If you make it configurable, then add the left button too for configuring. Some people like to swap left and right because they are left-handed.

**Comment by RednibCoding** [comment]
I would do it

**Comment by MandrakeHorse** [comment]
On the subject of mouse configuration, should we consider adding support for gaming mice as a separate issue? Granted, most users can simply bind hotkeys to additional mice buttons using third-party software, but it might be convenient to allow for some in-game configuration.
