### ISSUE TITLE
[Bug] CorsixTH won't start

### ISSUE THREAD

**Issue by LordBaal** [CorsixTH/CorsixTH#2376]
### Describe the issue

Whenever trying to start the game the following error is shown as a Windows popup:

The program can't start because api-ms-crt-runtime-|1-1-0.dll is missing. Try reinstalling the program to fix this problem.

The above message is translated from Spanish by the way, so it might not be a exact copy of what might say on a English system.

This is on a Windows 7 Ultimate, 32 bits computer with 2 GB of RAM. The version of the game is GOG and is installed in C:\GOG Games\Theme Hospital, while CorsixTH got installed in C:\GOG Games\Theme Hospital\CorsixTH, using the Windows installer.

### Steps to Reproduce

1. Install the GOG version of Theme Hospital

2. Install CorsixTH

3. Try to run the CorsixTH

### Expected Behaviour

To run the game?

### Save Game

 No

### CorsixTH Version

CorsixTH 0.66

### Operating System

Windows 7 Ultimate 32 bits

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
There's no log created.
```

**Comment by lewri** [comment]
You can try getting this file through Microsoft. It appears this error has also been reported by Adobe for some of their software:
https://support.microsoft.com/en-us/topic/update-for-universal-c-runtime-in-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

@TheCycoONE could you confirm if that's right? Looks like as we build CorsixTH for Windows 10 target (I assume), it needs this library installed.

**Comment by TheCycoONE** [comment]
I have no way of verifying but it's from 0.66 and this is the first I've heard of it.

**Comment by lewri** [comment]
Changes to visual studio for newer windows editions may mean older windows versions need additional libraries installed, which is what I imagine happened here (including for Adobe)
https://helpx.adobe.com/uk/download-install/kb/error_on_launch.html

My guess is simply that maybe the update I linked to earlier wasn't installed automatically. @LordBaal if installing that update fixes the issue let us know and I'll move this to a Discussion (looks like it has prequestive if needing Windows 7 SP1 installed also).

**Comment by lewri** [comment]
Issue related to a missing runtime. Will reopen if we get more reports from Windows 7 users on this release.
