### ISSUE TITLE
[Bug] Missing translation in spanish

### ISSUE THREAD

**Issue by carlosrd** [CorsixTH/CorsixTH#2383]
### Describe the issue

I've observed that there is a string key not overriden in [`Spanish.lua`](https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/languages/spanish.lua) and then it appears in English as default.

It's this one:
`dynamic_info.object.strength_extra_info = "Strength %d (Upgradeable to %d)"`

Spanish translation would be:
`dynamic_info.object.strength_extra_info = "Resistencia %d (Mejorable a %d)"`

### Steps to Reproduce

1. Start any course with Spanish language as selected
2. Build some room with a machine that requires handyman to maintain it
3. Place mouse over the machine to see current Strength and available upgrades
4. Text appears in english 

![translation](https://github.com/CorsixTH/CorsixTH/assets/2896275/0c633b03-a3e5-4eff-bb96-3020b1a1b3c6)

### Expected Behaviour

Text translated in spanish (when it's the language selected)

### Save Game

Save game attached to report: No

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by lewri** [comment]
Yes. The spanish translation hasn't been updated in 3 years, so any new strings since then haven't been added. The single line can be updated, or if someone wants a deeper dive, an update of the Spanish translation.

**Comment by carlosrd** [comment]
I've just found only this, but I can help you with others if it's needed ! 😉

**Comment by lewri** [comment]
> I've just found only this, but I can help you with others if it's needed ! 😉

You're very welcome to! This wiki page will help point you into finding pesky untranslated strings as a starting point:
https://github.com/CorsixTH/CorsixTH/wiki/Localization
