### ISSUE TITLE
0.67 - MP3 playback with Mac DMG

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2384]
We are aware of an issue affecting MP3 playback in the MacOS release of CorsixTH 0.67.

Currently investigating.

**Comment by colinjmatt** [comment]
I needed to compile and install some dependencies for SDL2 mixer for mp3 playback to work.

I've now compiled MikMod, ogg, Vorbis, flac & mpg123 as dependencies of SDL2 mixer and updated the wiki for compiling on MacOS.
