### ISSUE TITLE
[Bug] Selecting folder containing MP3 file with forward-slash in filename will crash CorsixTH

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2385]
### Describe the issue

While I was selecting some custom MP3s in Settings, I encountered a bug where if you select a folder containing an MP3 file with a forward-slash (/) in its filename (e.g. "05 On The Mend (Sound Blaster 16/OPL3 Version).mp3"), CorsixTH will freeze (the Back button highlights on hover but will do nothing when clicked). If you close and relaunch CorsixTH, the following error will occur until you've either deleted or renamed the MP3 file in question:

> An error has occurred in CorsixTH:
Lua\audio.lua:565: C:\Users\Mandrake\Music\Theme Hospital_(SoundBlaster)\05 On The Mend (Sound Blaster 16?OPL3 Version).mp3: Invalid argument
stack traceback:
   [C]: in function 'assert'
   Lua\audio.lua:565: in method 'playBackgroundTrack'
   Lua\audio.lua:459: in method 'playRandomBackgroundTrack'
   Lua\audio.lua:174: in method 'init'
   Lua\app.lua:253: in method 'init'
   CorsixTH.lua:143: in main chunk
   [C]: in ?

### Steps to Reproduce

1. Create a folder on your computer
2. Add an MP3 file with a forward-slash (/) in its filename
3. Launch CorsixTH
4. Click Settings
5. Click Folders
6. Click MP3's ("No folder location specified yet!")
7. Select the folder containing your MP3 file

### Expected Behaviour

Either the filename would be correctly parsed and the MP3 file would be added to the Jukebox, or the error would be caught.

### Save Game

Not applicable

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by lewri** [comment]
`/` Shouldn't actually be possible in Windows.
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/92a54974-4f5d-4f73-9d49-42bd0065dda7)

Something tells me that slash is one of these alternatives (Ctrl+F that page actually matches all the alternatives on Firefox though from your filename):
https://www.baeldung.com/linux/filename-with-slash#1-alternatives-to--in-unicode

**Comment by MandrakeHorse** [comment]
For the record, here's a YouTube playlist of the Theme Hospital soundtrack which I've downloaded for my own personal use. Note that all the video titles contain a forward slash ("Sound Blaster 16/OPL3 Version"), which somehow ended up in the file names of my MP4s: https://www.youtube.com/playlist?list=PLSznlXLF_yXBCtRBWs70nX14XtnsRnFpy

**Comment by tobylane** [comment]
At the point we collect the filenames, https://github.com/CorsixTH/CorsixTH/blob/f410a3b4e44dc5473a8b4833e3e960ed8077e6a0/CorsixTH/Lua/audio.lua#L114 it could reject bad filenames, eg `if string.find(filename, pathsep)`. But I don't want to try to cover all the cases, it may be better to consider this a user error and note it in the wiki.
