### ISSUE TITLE
Ability to customise Jukebox playlist order

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2386]
### What feature or enhancement would you like to add?

Currently, it appears that the Jukebox will play Theme Hospital's MIDIs or the user's custom MP3 files in a random order that's determined during startup. Originally, Theme Hospital would always play the soundtrack in the following order:
1. Atlantis
2. 6's and 7's
3. Fortune
4. Candyfloss
5. On The Mend
6. Doctor Frog
7. Night Shift
8. Steady Pulse

The HOSP/SOUND/MIDI directory contains a file called MIDI.TXT which lists all the XMI files and their corresponding track names in the above order, suggesting that this file might be used by Theme Hospital to define the Jukebox's playlist.

There should be a way for the player to specify the order in which songs will play in the Jukebox, such as:
A) providing a configuration file similar to MIDI.TXT that can be edited before launch
B) allowing the player to manually reorder tracks via the Jukebox's UI
C) sorting MP3 files alphabetically (so that the player can specify their order by renaming each MP3 with a numeric prefix)

### How would this feature benefit the gameplay of CorsixTH?

The player would be able to listen to music in their preferred song order.
CorsixTH would be able to replicate the original tracklist for Theme Hospital's soundtrack by default.
Once a playlist has been defined, a shuffle button could potentially be added to the Jukebox later.

### Was the feature in the original game?

Unsure

### What version of CorsixTH are you using?

0.67

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

I asked about this on the CorsixTH Discord's #help channel, and was informed that no sorting appears to be applied to the user-defined music folder: https://github.com/CorsixTH/CorsixTH/blob/fc38c4f46913b7b91c0b1b53efd7c7f2764adb20/CorsixTH/Lua/audio.lua#L61-L182

**Comment by lewri** [comment]
So I think scenario A and C has been done. Correct @tobylane ?
Scenario B needs some control ability added to the UI I imagine -- Nice is drag and drop; less nice is just up/down buttons.

**Comment by MandrakeHorse** [comment]
I can confirm that scenarios A and C have been implemented in 0.68. 

By default, CorsixTH will use the original track order as defined in midi.txt:
![2024-10-14 00_42_43-CorsixTH](https://github.com/user-attachments/assets/b7bb44c1-971a-45c0-9f62-3c6743c637e8)

If you load custom music, the tracks will be ordered alphabetically. This means you can specify the track order by prefixing a number to the filename:
![2024-10-14 00_42_28-CorsixTH](https://github.com/user-attachments/assets/ea44882e-2e2c-4335-a4a6-9bbe9a16df06)
![2024-10-14 00_51_30-Window](https://github.com/user-attachments/assets/1f0ebb54-9d02-4b1e-8bda-4128f7499024)

Scenario B hasn't been implemented but the workaround is to either edit midi.txt (if using the default music) or rename your music files (if using custom music). If we ever decide to revamp the Jukebox UI, we can consider allowing the user to reorder tracks within the Jukebox itself.

CorsixTH continues to play a random track upon startup and works it way down through the playlist before returning to the top.
