### ISSUE TITLE
[Bug] Left click not working

### ISSUE THREAD

**Issue by lukejames1111** [CorsixTH/CorsixTH#2387]
### Describe the issue

Mouse not working (MacOS)

### Steps to Reproduce

Start game, click new campaign, when it loads cannot close dialogue box as clicking does not work. The "x" to close the dialogue box changes colour when hovering, but left clicking does nothing at all. The same behaviour applies to the menu and navigation. Can only close the game by pressing CMD + Q.

### Expected Behaviour

Expect left click to work

### Save Game

Save game attached to report: No

### CorsixTH Version

v0.67

### Operating System

MacOS Ventura 13.4

### Theme Hospital Version

GOG.com

**Comment by lukejames1111** [comment]
I think I might have narrowed the issue down slightly. I tried changing pause from P to § in the hotkeys, and that stopped left click from working. However, I noticed that when I restore the defaults, left click automatically works again.

**Comment by lewri** [comment]
@colinjmatt @tobylane have you been able to replicate this on Mac?

**Comment by lukejames1111** [comment]
I had a little play around with this, I think it's because it's actually assigning it to left click and not §.

So when I go to set a new hotkey, I select Pause, edit that, try to assign §, but it doesn't work and is still waiting for an input. I then click off that but it then assigns left click as pause. But when I do anything else (i.e. continue game) it registers it as a half click and glitches. Because when I'm in the game I can "click" on things, but it only registers a half click and not a full click because left click is assigned as a hotkey for something else too!

I know it's confusing, but I hope that helps!

**Comment by tobylane** [comment]
I can't set left click as pause. What is the word in the box when you've done that?

§ works for me, on a wired keyboard with number keys.

**Comment by lukejames1111** [comment]
There is no word in the box, it's blank. It won't allow me to set it to § for some reason.

**Comment by lewri** [comment]
Just to check you haven't got any accessibility options enabled in Mac at all?
https://superuser.com/questions/295644/assign-left-mouse-click-to-a-keyboard-key

**Comment by lewri** [comment]
Replication not possible. We'll reopen if we get another report from another device.
