### ISSUE TITLE
[Bug] Freeze on trying to load custom map/scenario

### ISSUE THREAD

**Issue by Skywatcher17** [CorsixTH/CorsixTH#2401]
### Describe the issue

I made some custom maps/scenarios a couple of years ago, obviously in an older version of the game. When I try to load them, the game instantly freezes (at the menu). Is there any way around this issue?

### Steps to Reproduce

1. Place the two files in the ZIP archive attached to this ticket into the game's maps folder.

2. Attempt to load the Basicton map.

### Expected Behaviour

For the map/level to load.

### Save Game

Save game attached to report: Yes

[Archive.zip](https://github.com/CorsixTH/CorsixTH/files/12562736/Archive.zip)

### CorsixTH Version

0.67

### Operating System

Windows 7

### Theme Hospital Version

CD

**Comment by lewri** [comment]
I loaded this one up fine on mine, not sure what happened on your device.
I doubt Windows 7 is the issue... is it 32 bit or 64 bit?

**Comment by Skywatcher17** [comment]
Thanks for the response. It's Windows 7 64-bit. I've just tried loading the scenarios on my main OS (macOS) and they load fine. Weird...

**Comment by lewri** [comment]
I may close this, doubt it's related to #2376 in some way (missing runtime) but I can't verify. If you try and install the runtime linked in that issue and run the single scenario be interested to know if it crashes.

**Comment by lewri** [comment]
Closing this one off
