### ISSUE TITLE
Increase minimum resolution

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2402]
### What feature or enhancement would you like to add?

Currently we obey the TH standard resolution of 640x480 as a minimum. However, as we are now in an age where 1080p is a standard screen resolution we should seek to utilise more of the screen. As such, I'd recommend changing the minimum to 800x600. This is still 4:3.

### How would this feature benefit the gameplay of CorsixTH?

We are approaching some scenarios where increasing height of UI elements would stretch to or go beyond a height of 480px.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.67

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

TH fullscreen windows are originally all 640x480 -- 800x600 handles these windows well enough that they don't get obscured by menus.

At 800x600 however, the main menu has overlap issues with the MOTD window. Background also seems to be a little fuzzy.
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/94101363-2318-4aa4-8bbb-7eb8ecde5561)

**Comment by ageekhere** [comment]
Should the default just be Fullscreen at monitor native resolution?

**Comment by Alberth289346** [comment]
+1 for a larger default screen resolution

-1 for default full screen, some people use more than one application at a time. Claiming the entire screen space is a bad move then.

**Comment by lewri** [comment]
> Should the default just be Fullscreen at monitor native resolution?

4k monitors currently struggle badly from a UI perspective in CorsixTH. Plus fullscreen with mouse capture can be more than a minor inconvenience for some

**Comment by TheCycoONE** [comment]
-1 for me. Plenty of reason to play in small windows. No clear motivation that isn't better addressed by scaling.

**Comment by lewri** [comment]
Our (sane) default is 800x600 in the game code anyway.
https://github.com/CorsixTH/CorsixTH/blob/0202eb30d973b79a321a7d3c5eebe12eff2afc30/CorsixTH/Lua/config_finder.lua#L97-L98

I'm kind of happy with that. What I'm not as keen on is not warning users of some windows being potentially degraded by using a resolution lower than that though if they choose it (without some warning)

**Comment by TheCycoONE** [comment]
Larger base resolutions will make integer scaling for larger screens harder not easier.
