### ISSUE TITLE
[Bug] Continue Game tries to load ZIP file containing most recent save

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2408]
### Describe the issue

If you create a compressed (zipped) folder containing your most recent autosave/manual save and add it to \AppData\Roaming\CorsixTH\Saves, the Continue Game button will attempt to load this ZIP folder and fail with the following error:
`Error while loading game: Lua\persistance.lua:287: Cycle while depersisting permanent object key or userdata metatable after 1 objects (1 bytes)`

![image](https://github.com/CorsixTH/CorsixTH/assets/142453312/bc45f46f-ad9a-419a-8933-6dc7297f5799)
![2023-09-24 14_19_44-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/03afb8d5-7b3a-476c-84a8-decc4a643645)

### Steps to Reproduce

1. Go to \AppData\Roaming\CorsixTH\Saves
2. Create a ZIP folder containing your most recent .sav file (i.e. the file which is currently loaded by Continue Game). You could also download the attached ZIP file and add it to this directory.
3. Start CorsixTH
4. Click Continue Game

### Expected Behaviour

Continue Game should only attempt to load the most recent .sav file and ignore all other file types

### Save Game

Save game attached to report: Yes
[compressedCorsixTHsave.zip](https://github.com/CorsixTH/CorsixTH/files/12708960/compressedCorsixTHsave.zip)

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by ryanpenfold** [comment]
This seems like the Save handler is forgetting to do a checksum
