### ISSUE TITLE
luadoc build - Lua 5.3 unit tests failure

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2412]
```bash
/usr/bin/lua5.3: ./helpers.lua:29: attempt to call a string value (field 'version')
stack traceback:
	./helpers.lua:29: in function 'need_lpeg_version'
	./c_tokenise.lua:22: in main chunk
	[C]: in upvalue 'fn'
	../CorsixTH/Lua/strict.lua:66: in function 'require'
	/home/runner/work/CorsixTH/CorsixTH/LDocGen/main.lua:47: in main chunk
	[C]: in ?
make[3]: *** [CMakeFiles/doc_corsixth_lua.dir/build.make:71: CMakeFiles/doc_corsixth_lua] Error 1
make[2]: *** [CMakeFiles/Makefile2:250: CMakeFiles/doc_corsixth_lua.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:231: CMakeFiles/doc.dir/rule] Error 2
make: *** [Makefile:169: doc] Error 2
```

Not sure what requires patching here.

**Comment by Alberth289346** [comment]
`helpers.lua` is doing

``` lua
local v = require"lpeg".version()
```
and that crashes apparently.

Do you have that installed for Lua 5.3 ?
One way to find out is by running Lua from the CLI:
``` sh
$ lua
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> x = require"lpeg"
> x.version
function: 0x7f36649c64b0
> x.version()
1.0.2
```
Type `lua` or `lua5.3` or so possibly with a directory in front of it, to start the interpreter. You''l get the version line, and a `>` prompt and you can type Lua code then.
To end the session, you need to enter an EOF character. At windows that is isCTL+Z, and then the "enter" key.

Alternatively you can make a file `myfile.lua` with the commands and then type `lua myfile.lua` at the CLI to run the file.

**Comment by Alberth289346** [comment]
Note, apparently I have lpeg 1.0.2 installed, we require 0.9 currently (at the "compiling wiki page).

**Comment by lewri** [comment]
Minimum version is 0.9, unless we've somehow hit a maximum version now
