### ISSUE TITLE
[Bug] Music disabled

### ISSUE THREAD

**Issue by dkrupicka** [CorsixTH/CorsixTH#2443]
### Describe the issue

On Android, I downloaded the game from GOG and used Inno Setup Extractor to extract the game.
In settings, I see the music is disabled and requires additional download, but the download fails.

### Steps to Reproduce

Same as description

### Expected Behaviour

Music enabled 

### Save Game

Save game attached to report: No

### CorsixTH Version

0.50

### Operating System

Android

### Theme Hospital Version

GOG.com

**Comment by tobylane** [comment]
Try the latest version at, and report bugs to, the [CorsixTH Android project.](https://github.com/alanwoolley/CorsixTH-Android)
