### ISSUE TITLE
Redesign options.lua window layout

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2462]
As #2375 extends this window beyond 480px it requires a redesign to fit properly in a 640x480 resolution.

This could be achieved by e.g.
- Making two columns
- Grouping some options into a new sub menu
- Making as scrollbar
- Reactive menu layout (layout changes to fullscreen at 480 height)
- Fullscreen-esque menu layout (e.g. like hotkeys, which is windowed at 640x480 and fullscreen at that resolution)

**Comment by tobylane** [comment]
In #1997 I have made the cheats window reactive, it will switch to two columns when necessary. If that is acceptable, I have written a similar branch for the tips window, it will be taller to fit in the narrower space beside the main menu. I can make the options window switch to two columns, or maybe it should always be two columns in a squarer shaped window, I'll experiment.

**Comment by tobylane** [comment]
<img width="752" alt="Screenshot 2024-01-20 at 16 38 53" src="https://github.com/CorsixTH/CorsixTH/assets/552285/54759df3-4a22-4d9d-aa70-0ff503b3c494">

A two column options window in the minimum resolution. Is there a purpose in the hotkeys button being bigger?

**Comment by lewri** [comment]
> A two column options window in the minimum resolution. Is there a purpose in the hotkeys button being bigger?

For context to the image the hotkeys button is currently as big as the back button. I'm guessing as 'customise' and 'folders' already used up the width they were on it was silly to have hotkeys the same size by itself on the line below.

Likely it doesn't need to be bigger.
