### ISSUE TITLE
[Bug] Hungarian language does not appear

### ISSUE THREAD

**Issue by novakgabor** [CorsixTH/CorsixTH#2473]
### Describe the issue

In the options there are a few languages that don't show up at all, including hungarian. The file is present but the game does not see it or something.

### Steps to Reproduce

Go to Settings

Select Game Languages

Hungarian is not present

### Expected Behaviour

I expected the option to be available since the translation is 100% complete.

### Save Game

No

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

**Comment by novakgabor** [comment]
Hello tobylane!

Thanks! The Segoeui.ttf font is good for it. Unfortunately, even though the Hungarian translation is described as 100%, it is far from being 100%.

**Comment by lewri** [comment]
We usually add strings over time. I don't think Hungarian has had an update in a few years.

If you had the desire to, we always do appreciate when people are able to fill in the missing blanks for new strings!

**Comment by tobylane** [comment]
If you'd like to translate some of the remaining strings [the wiki has a guide.](https://github.com/CorsixTH/CorsixTH/wiki/Localization#working-on-an-existing-language) Where did it say 100% I don't know the current percentages but several have slipped recently and we can give an update.
