### ISSUE TITLE
[Bug] Game crashes when I move my cursor over the ward doors

### ISSUE THREAD

**Issue by wish-i-could-code** [CorsixTH/CorsixTH#2477]
### Describe the issue

I have been playing a custom scenario with a level file that I have modified. About 2-3 days ago, I've noticed CorsixTH crashing at random times in the game. In this particular save file, the game crashes/hangs when I move my cursor over the doors of the 2nd ward I built in the southeast section of my hospital.

Just FYI, the game has also crashed before on different save file, but same map/custom scenario - without this particular crash trigger if I'm not mistaken (I could be wrong). 

### Steps to Reproduce

In **this particular instance**, I was playing this save file and was trying to place down some benches. 
I moved my cursor over the doors of the 2nd ward I built in the southeast section of my hospital and then the game just hangs. 

### Expected Behaviour

In this save file, I had paused the game right at the start of the game, and was building out my hospital before opening my hospital to patients. But then the game crashes right when I inadvertently just moved my cursor over the doors of my 2nd ward. I would have expected the game to 1) keep allowing me build rooms, place items normally without crashing and 2) allow me to click the ward doors to see the queue without the game crashing. 

### Save Game

https://drive.google.com/file/d/1vmrysKp1wDaw2V7a9Loi5l2k3A5t65Np/view?usp=drive_link

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

Origin

### Gamelog.txt

```bash
Gamelog generated on 2024-01-28 00:17:23
Compiled with api_version: 2684, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2684, game version: v0.67, savegame version: 180
Created game with savegame version 180.
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Savegame version is 180 (v0.67), originally it was 180 (v0.67).
Error in motion handler: 
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
	Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
	Lua\game_ui.lua:551: in function <Lua\game_ui.lua:539>
	(...tail calls...)
	Lua\app.lua:1102: in function <Lua\app.lua:1097>
Error in timer handler: 
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
	Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
	Lua\game_ui.lua:853: in method 'onTick'
	Lua\app.lua:1204: in function <Lua\app.lua:1199>
	(...tail calls...)
	Lua\app.lua:1102: in function <Lua\app.lua:1097>
```

### Additional Information

![gamelog](https://github.com/CorsixTH/CorsixTH/assets/157906665/13583366-8e1a-4dca-9340-afd1102df12c)

**Comment by tobylane** [comment]
The swing doors don't link together until the next game tick. The bug is known, and fixed, but we're currently refixing it. In the meantime, can you reload an autosave and briefly unpause the game after finishing any room with swing doors?

**Comment by wish-i-could-code** [comment]
yep, that seems to have fixed the issue - thanks all!
