### ISSUE TITLE
Checkered graphic artifacts issue

### ISSUE THREAD

**Issue by EianAtDawn** [CorsixTH/CorsixTH#2478]
### Describe the issue

Hey there is a known checkerboad bug that's being happening to chromium based apps as been discussed in many forums..
[Techpowerup](https://www.techpowerup.com/forums/threads/rtx-3000-series-artifacts-black-squares-that-flicker-in-desktop-and-2d-mode.297640/page-11)
[Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1155285)

I found this happens constantly in game if I choose a smaller resolution than my monitor's native and run in fullscreen..
(Tested on 0.67v)
Depending on the resolution you'll get similar result..
It's more prominent on my 2k monitor than my 1080p.
The edges will be glitched as seen in the screenshot..

Not sure if the underlying issue is the same but since I'm also facing the bug in other software it looks identical in the way it happens as well.. It's just much more frequent here..
so maybe getting to the bottom of this might also help to fix the known checkerboard issue so many are facing??

![image](https://github.com/CorsixTH/CorsixTH/assets/99512697/90f20ffd-1d20-4d14-a4e2-fda2eeb04ac2)

### Steps to Reproduce

1. choose a smaller resolution than your monitor's native.

2. Play and move the mouse cursor.

3.

### Expected Behaviour

No checkerboard glitches on edges of scree,

### Save Game

Save game attached to report: No

### CorsixTH Version

0.67

### Operating System

Windows 11

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Gamelog generated on 2024-01-02 18:15:25
Compiled with api_version: 2684, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2684, game version: v0.67, savegame version: 180
```

### Additional Information

Not sure but getting to the bottom of this might help to fix the known checkerboard issue so many are facing??

**Comment by Alberth289346** [comment]
How does #2301 look to you?

**Comment by EianAtDawn** [comment]
Oh sorry I missed [2301](https://github.com/CorsixTH/CorsixTH/issues/2301).
Yeh it's the same issue..
I did search for checkered/checkerboard and couldn't find anything so I started a new thread.. my bad..


Btw I'm using nVidia asus 4070 tuf oc..

**Comment by EianAtDawn** [comment]
Shall I close as completed then?

**Comment by lewri** [comment]
It is a duplicate. There is a link in 2301 to the Nvidia post if you wished to bump it (not sure how their forum system works). Or you could report it via their problem feedback form if they have one.
