### ISSUE TITLE
[Bug] Unresponsive and innacurate mouse panning when the zoom level is not 1

### ISSUE THREAD

**Issue by tombolano** [CorsixTH/CorsixTH#2498]
### Describe the issue

The mouse panning has some problems, with a zoom level of 1 the panning works fine, but if we change the zoom level the cursor no longer follows the map exactly when panning, this can be seen in the following example:

https://github.com/CorsixTH/CorsixTH/assets/86369321/ab716545-3d26-4f84-a7ae-30b34d75d4fc

Ideally, when panning the cursor should be on top of the same "tile", but this is not the case when the zoom is changed.

Also, when zooming very close the panning becomes unresponsive, in the following example I was pressing the middle mouse button to pan, but when moving slowly the mouse the map didn't move at all:

https://github.com/CorsixTH/CorsixTH/assets/86369321/49e7cc32-8ce3-4c11-afe9-7b02f0de596a

### Steps to Reproduce

1. Start a new game
2. Change the zoom level
3. Try to pan the map with the mouse

### Expected Behaviour

When panning the cursor should respond and follow the map exactly

### Save Game

Save game attached to report: No

### CorsixTH Version

3899df33db

### Operating System

Fedora 39

### Theme Hospital Version

GOG.com

**Comment by lewri** [comment]
Do you know if 0.67 also exhibits it? I doubt it as the panning changes for 0.68 shouldn't be related to this specific action.

**Comment by tombolano** [comment]
Yes, I checked it on both the 0.67 and on the master branch. I will do a pull request with a fix.
