### ISSUE TITLE
Windows Compile Instructions are not complete enough

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2519]
Our compile instructions for Windows are generally a bit scarce and lack proper guidance with navigating our large dependency/setup list.

Some examples:
In terms of Visual Studio 2022 we now get presented this box on installation and we don't provide guidance on what to use:
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/53aa571c-2f5b-4376-99fc-e25e04ed16c6)

For some Lua libraries they have dependencies we do not mention (e.g. luasec and OpenSSL).

In current cmake, this command does not exist
`cmake.exe --prefix win-dev`
```
PS C:\dev\CorsixTH> cmake.exe --prefix win-dev
CMake Error: Unknown argument --prefix
```
^^ Edit: That one is meant to be `cmake.exe --preset win-dev` it seems

**Comment by TheCycoONE** [comment]
We generally don't accept wiki issues. It's open to edit by everyone, the best approach is to ask around to get any issues sorted out and then clarify in the wiki.

I fixed the prefix/preset thing.
