### ISSUE TITLE
[Bug] No soundfont crashes callback handler on launch

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2520]
### Describe the issue

When loading CorsixTH without an included, detected, or configured soundfont file the callback handler immediately crashes. Gameplay appears to not stop but I'm not sure of the knock-on effects (probably significant).

### Steps to Reproduce

1. Load game without the included SoundFont file, detected file, or configured file.
2. Attempt to play music of MIDI files from Jukebox (or if already enabled, ignore).
3.  Notice the crash in the console.

### Expected Behaviour

Proper handling of lack of soundfont needs to be handled correctly. At a minimum, the handler crash requires suppression before next release.

### Save Game

Save game attached to report: No

### CorsixTH Version

Compiled from master

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The callback handler.
A stack trace is included below, and the handler has been disconnected.
C:/dev/CorsixTH/CorsixTH/Lua\audio.lua:590: Could not load music file 'Sound\Midi\CANDY.XMI' (No SoundFonts have been requested)
stack traceback:
        [C]: in function 'coroutine.yield'
        C:/dev/CorsixTH/CorsixTH/Lua\app.lua:1097: in function <C:/dev/CorsixTH/CorsixTH/Lua\app.lua:1092>
```

**Comment by tobylane** [comment]
https://github.com/CorsixTH/CorsixTH/blob/3bb1100/CorsixTH/Lua/audio.lua#L589

When e == "No SoundFonts have been requested", we could replace the error with a more helpful comment, or even a UIInformation dialog. Another error message I see is "XMP: Unrecognized file format", which means SDL_Mixer couldn't identify the file by extension or magic word, and sent it to libxmp anyway, which also couldn't handle it. Is it better to skip that jukebox item and uncheck its box, or have the user choose if they want to remove it from the folder or uncheck the box?

**Comment by lewri** [comment]
As long as we don't cause the handler to crash I'm fine with however we want to handle it.

**Comment by tobylane** [comment]
```lua
errors = {
  music = {
    soundfont = "Required soundfont is missing, please download one. A suitable soundfont is linked from the CorsixTH wiki.",
    unsupported = "Music format not supported for file %s.",
    other = "Could not load music file %s. Error: %s",
  }
}
```
These are the new error messages I have so far. Do linux users have more options than Windows users, should a package manager be mentioned? Have you had any other error messages worth changing? The jukebox item can be unchecked.

**Comment by lewri** [comment]
Some common linux directories are listed inside the `findSoundFont` function
https://github.com/CorsixTH/CorsixTH/blob/fba17756287a13c9810aeff50992623f92233a39/CorsixTH/Lua/app.lua#L1495-L1514

Ideally linux should also be checked for the `.sf3` in the common dirs as I'm sure there are instances of that file format being used.

For your soundfont error, maybe it should instead say it's `not found` rather than missing -- because the user may have one but it's not defined properly. Also maybe a line about how MIDI music will not play?
