### ISSUE TITLE
Can't activate unlock everything cheat in Corsixth

### ISSUE THREAD

**Issue by Terrussy** [CorsixTH/CorsixTH#2532]
### Describe the issue

I'm not sure is this only me or not, but when I've got into first level on campaign mode I tried to use 24328 as soon as possible because I want to 
unlock every rooms on this level. and when I tried to press the unlock rooms cheat, the receptionist in game said I'm cheating. so that's mean it will work right? but when I checked the rooms it's still unlock. So I went to press Ctrl+Shift+C it's done nothing too.
So I tried again with add money cheat and it worked. So I think it was only the unlock cheat that I can't use in CorsixTH 

Please help.
Thank you.

### Steps to Reproduce

I'm not sure is this only me or not, but when I've got into first level on campaign mode I tried to use 24328 as soon as possible because I want to 
unlock every rooms on this level. and when I tried to press the unlock rooms cheat, the receptionist in game said I'm cheating. so that's mean it will work right? but when I checked the rooms it's still unlock. So I went to press Ctrl+Shift+C it's done nothing too.
So I tried again with add money cheat and it worked. So I think it was only the unlock cheat that I can't use in CorsixTH 

Please help.
Thank you.

### Expected Behaviour

The game should unlock all rooms after press unlock all rooms cheat or Ctrl+Shift+C.

### Save Game

No

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```bash
Gamelog generated on 2024-03-16 01:18:19
Compiled with api_version: 2684, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2684, game version: v0.67, savegame version: 180
```

**Comment by lewri** [comment]
The cheat code unlocks the window for cheats, as CorsixTH does not support the keybinds of the original.

When you use the complete research cheat (or a similar name, not at computer right now) that should make all rooms unlock that are available to the level.

In the first level there is nothing to unlock because it does not contain a research department. There are only things to unlock from Level 2 onwards

**Comment by lewri** [comment]
Okay. I've gone back to the original and `Ctrl+Shift+C` does literally unlock everything even if it makes no sense to the level. 

I can see the benefit unlocking all diagnostic rooms via such a cheat, but it would be better if all treatments were all ones only specifically required for the level. This likely needs a separate cheat path.

Our current cheat description is *not wrong* in that it is just completing "All research". It is not opening up unused rooms for the level.

**Comment by lewri** [comment]
Closing this. Our approach is better in that we limit it to the scope of the available diseases and objects to the level.
I'm going to make a discussion regarding if Diagnosis Rooms should be fully unlocked though (as that's the only cheat change that makes logical sense).
