### ISSUE TITLE
[Bug] Entity Sounds missing from Computer & Atom Analyser

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2534]
### Describe the issue

In the Research Department, you can build the Computer and Atom Analyser later in the game to enhance research speed. However, when Researchers use this object the sounds are missing. They are supposed to use the `SCNBEEP1.WAV` sound during the animation when pressing buttons, which can be heard in the original. (SCNBEEP2 may also come in, but I have my doubts).

I've generally tried to look over where we pull sounds for animations from but can't come across it. I have a feeling it is in the ANIMS DAT files. My only thought is that maybe there's a missing ANIM classification in our files for these objects but not sure.

### Steps to Reproduce

1.  Create a new game targeting Level 9 from the debug menu. Hire a researcher
2.  Perform the all research cheat to load in all discoverable objects
3. Build a research department with Computer and Atom Analyser.
4. Watch the research Dr use object without sound.

### Expected Behaviour

The object is meant to be playing a sound upon pressing of keys by the Dr.

### Save Game

Save game attached to report: No

### CorsixTH Version

0.67 (tested back to 0.65)

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

**Comment by MandrakeHorse** [comment]
For reference, here's a random Let's Play of Theme Hospital where you can hear the beeps when the research uses the Computer and Atom Analyser:
- Computer: https://youtu.be/m20DiNRwIJU?t=149
- Atom Analyser: https://youtu.be/m20DiNRwIJU?&t=326
