### ISSUE TITLE
[Bug] Machinery does not play explosion animation when destroyed

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2553]
### Describe the issue

When machinery explodes through either overuse or an earthquake, there's no explosion animation. Instead, the room instantly becomes destroyed. In Theme Hospital, an explosion can be seen whenever machinery is destroyed.

### Steps to Reproduce

1. Load the attached save file.
2. Wait for the Fractured Bones patient to use the smoking Cast Remover.
3. Reload if the machine doesn't explode.
Alternatively, use cheats to spawn enough earthquakes until machinery explodes.

### Expected Behaviour

The machines will have an explosion animation when they blow up from overuse, as seen in this Let's Play: https://youtu.be/VqJeh3i5j1w?t=728

### Save Game

Save game attached to report: Yes
[level7castremoverboom.zip](https://github.com/CorsixTH/CorsixTH/files/14968779/level7castremoverboom.zip)

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by lewri** [comment]
Merging into #2556
