### ISSUE TITLE
[Bug] Doctor has "%s" for first name initial

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2554]
### Describe the issue

One of my Doctors has the name "%s. Highlet".
![image](https://github.com/CorsixTH/CorsixTH/assets/142453312/421f9baa-2d74-4f85-b7d9-282a5d8199dd)

### Steps to Reproduce

Load either of the save files attached to this ticket.

### Expected Behaviour

The Doctor should have a capital letter for his first name's initial, not a percentage sign followed by an s.

### Save Game

Save game attached to report: Yes
[level7%s.Highlet.zip](https://github.com/CorsixTH/CorsixTH/files/14968825/level7.s.Highlet.zip)
* level7%.sHighletHirable.sav - %s. Highlet can be hired and appears as the first Doctor in Hire Staff 
* level7%s.HighletEmployed.sav - %s. Highlet has been hired and appears as the eighth Doctor in Staff Management

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

**Comment by MandrakeHorse** [comment]
@lewri suggested on Discord that the cause might be the staff initials cache. I also did not change the language from English during this playthrough.

**Comment by lewri** [comment]
If a string isn't given a value where it has a `%s` would that cause it just to show the `%s`?

**Comment by tobylane** [comment]
The number made in this line is zero. The prime number doesn't do the job I was intending.

https://github.com/CorsixTH/CorsixTH/blob/258f7e2/CorsixTH/Lua/world.lua#L2456
