### ISSUE TITLE
Implement gbv.VeryTired / isVeryTired function

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2564]
From #2529 the `fatigue > 0.7` checks in code should be replaced with the config value `gbv.VeryTired` as different difficulties use different values. A central calling function should be used to return a boolean e.g. `Staff:isVeryTired`

Additionally, make sure base_config is given a default value (probably 0.7 again).

As `VeryTired` uses an integer 0-1000, our `fatigue` attribute should be multiplied to run the check (rather than divide)

**Comment by tobylane** [comment]
I have a start on that here https://github.com/CorsixTH/CorsixTH/commit/eb1a585da0b1fb628cb931721b5af9b5572946e6

What other `fatigue > 0.7` checks should be changed? These are possibles.
https://github.com/CorsixTH/CorsixTH/blob/f583c561c96510d233107051ec47346bf21708cc/CorsixTH/Lua/entities/humanoids/staff/doctor.lua#L45
https://github.com/CorsixTH/CorsixTH/blob/f583c561c96510d233107051ec47346bf21708cc/CorsixTH/Lua/entities/humanoids/staff.lua#L361-L363

**Comment by lewri** [comment]
> https://github.com/CorsixTH/CorsixTH/blob/f583c561c96510d233107051ec47346bf21708cc/CorsixTH/Lua/entities/humanoids/staff/doctor.lua#L45

A `<` would be just using a `not` instead? 

> https://github.com/CorsixTH/CorsixTH/blob/f583c561c96510d233107051ec47346bf21708cc/CorsixTH/Lua/entities/humanoids/staff.lua#L361-L363

I'm not convinced if this is the same behaviour as TH, is this confirmed?

**Comment by tobylane** [comment]
From Full00.sam
> #gbv.Tired				600	Staff Tiredness Above this - tired. (below - normal)
#gbv.VeryTired			700	Staff Tiredness Above this - very tired.
#gbv.CrackUpTired			800	Staff Tiredness Above this - could crack up

Which matches the current values of the pair in staff.lua above and https://github.com/CorsixTH/CorsixTH/blob/230b2082fd7c59f25eb571101de02d435af11d88/CorsixTH/Lua/hospital.lua#L194
We can check that these values are in that pair in playtesting.

**Comment by TheCycoONE** [comment]
base_config should probably match the sam files and use 700 rather than 0.7 right.

We may want to go to integers some day for the internal representation too but that's a bigger refactor.
