### ISSUE TITLE
Verify the official Flatpak

### ISSUE THREAD

**Issue by 12people** [CorsixTH/CorsixTH#2568]
### What feature or enhancement would you like to add?

Currently, the [Flathub version of CorsixTH](https://flathub.org/apps/com.corsixth.corsixth) is marked as unverified, even though it's offical.

Verifying it would be as simple as adding a TXT file (with a hash generated by Flathub) to the corsixth.com website.

### How would this feature benefit the gameplay of CorsixTH?

It would let users know that the CorsixTH Flatpak is official, and therefore more trustworthy.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.67

### Does this feature/enhancement relate to a current problem?

No

**Comment by lewri** [comment]
@rmnvgr / @TheCycoONE I guess the PR target for this will be to https://github.com/CorsixTH/corsixth.github.io instead?

**Comment by TheCycoONE** [comment]
I didn't author the app, it would have to be @rmnvgr

**Comment by rmnvgr** [comment]
I added the verification token to corsixth.com, so the Flapak is now verified on Flathub.
