### ISSUE TITLE
walk.lua:273: assertion failed!

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#257]
![2014-04-27-001420_1292x746_scrot](https://cloud.githubusercontent.com/assets/5307545/2810066/8921051e-cd98-11e3-81ed-f8597bd248c6.png)

Pressing 'yes' makes the game return but it has issues.
The nurse wouldn't do anything so I pulled her out of there so she'd go back in. This made her stand outside with the emergency patients while they queue (forever!) to get in.

![2014-04-27-001713_404x249_scrot](https://cloud.githubusercontent.com/assets/5307545/2810075/0a360afa-cd99-11e3-8d67-fefffc74e548.png)
![2014-04-27-001717_375x231_scrot](https://cloud.githubusercontent.com/assets/5307545/2810077/1477d782-cd99-11e3-8afa-d66f7350293b.png)

After a little while, this message came up and there was no new debug output:
![2014-04-27-001856_472x344_scrot](https://cloud.githubusercontent.com/assets/5307545/2810079/3eebc2b2-cd99-11e3-9eb0-3a894965876c.png)

Pressing 'yes' made led to emergency patients never being served at any pharmacy! The nurse keeps running around. One emergency patient almost died, the time it took for response (i.e. never) meant I failed to complete the emergency task so my reputation was penalised!

![2014-04-27-002317_286x434_scrot](https://cloud.githubusercontent.com/assets/5307545/2810087/f10f1142-cd99-11e3-8945-359e9e1d1a7d.png)

He was previously an emergency patient, now he's dying. He still won't leave.

Save file is available here: http://cmpct.info/files/th/broken_dying.sav

```
Notice: LuaJIT not being used.
Consider replacing Lua with LuaJIT to improve performance. Note that there is not currently a 64 bit version of LuaJIT.


---------------------------------------------------------------

Welcome to CorsixTH 0.21!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------


starting game with difficulty full
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
...r/share/games/CorsixTH/Lua/humanoid_actions/walk.lua:273: assertion failed!
stack traceback:
    [C]: in function 'assert'
    ...r/share/games/CorsixTH/Lua/humanoid_actions/walk.lua:273: in function <...r/share/games/CorsixTH/Lua/humanoid_actions/walk.lua:201>
    (tail call): ?
    ...r/share/games/CorsixTH/Lua/humanoid_actions/walk.lua:179: in function 'timer_function'
    /usr/share/games/CorsixTH/Lua/entity.lua:166: in function 'tick'
    /usr/share/games/CorsixTH/Lua/world.lua:1023: in function 'onTick'
    /usr/share/games/CorsixTH/Lua/app.lua:789: in function </usr/share/games/CorsixTH/Lua/app.lua:786>
    (tail call): ?
    /usr/share/games/CorsixTH/Lua/app.lua:690: in function </usr/share/games/CorsixTH/Lua/app.lua:685>

Warning: No event handler for timer
```

**Comment by Alberth289346** [comment]
I guess there is no 'before' save game any more. Also, the issue is about version 0.21, and a lot has changed since. If you find this problem again, please open a new ticket

**Comment by TheCycoONE** [comment]
It is extremely likely that this and #99 are the same issue.
