### ISSUE TITLE
Make save/load UI more unique

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2576]
### What feature or enhancement would you like to add?

Pulled from the CorsixTH Blog:

>can you make different design of save- and load-game screens? Both menu items are located very close to each other, so the player sometimes mistakenly chooses the wrong item and cannot immediately notice it, since the screens are very similar. Even adding two icons “Save” and “Load” of different colors will be enough.

### How would this feature benefit the gameplay of CorsixTH?

Multiple levels of differentiation usually can assist someone who may have difficulty discerning the two. I do admit our save/load UI elements are very samey.

### Was the feature in the original game?

Yes

### What version of CorsixTH are you using?

0.67

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

Technically there was a different in the original, since the original save UI was a menu item. The load screen was independent as well as being another menu item.

**Comment by lewri** [comment]
Differences between the two include text and a black bar at the bottom. I'm open to ideas on what could be useful (if at all)

![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/782e414e-e2a6-4222-98dd-472aae672ae7)
![image](https://github.com/CorsixTH/CorsixTH/assets/20030128/a25c28ff-74cb-47d4-aa73-22946af11491)

**Comment by TheCycoONE** [comment]
Wouldn't change the UI much; Save and Load instead of OK on the action button would be a good idea.
