### ISSUE TITLE
[Bug] Game completely freezes

### ISSUE THREAD

**Issue by j0npq** [CorsixTH/CorsixTH#2594]
### Describe the issue

As stated, the game completely freezes. I can't identify the issue that's triggering it. Sometimes I can play for hours with no issue at all, but other times (like now), it already happened 4 times in the last hour.

After the game freezes, I can still move the mouse on the background and interact with menus, although the cursor is not visible (the in-game cursor is frozen). So by trial and error, I'm able to save the game. When I load the game, I can play normally from the point it froze, usually with no issues. Sometimes, it will freeze again after a few minutes.

### Steps to Reproduce

It seems to always happen when I build while the game is paused. I couldn't identify a specific order of steps that triggers it.

### Expected Behaviour

The game to not freeze.

### Save Game

Save game attached to report: Yes
[error.zip](https://github.com/user-attachments/files/16460881/error.zip)

This save file was created right after the game froze.

### CorsixTH Version

0.67

### Operating System

Windows 10 home - 64 bits

### Theme Hospital Version

CD

### Gamelog.txt

```bash
---------------------------------------------------------------

Welcome to CorsixTH v0.67!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.


Restarting...




---------------------------------------------------------------

Welcome to CorsixTH v0.67!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
        Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
        Lua\game_ui.lua:853: in method 'onTick'
        Lua\app.lua:1204: in function <Lua\app.lua:1199>
        (...tail calls...)
        Lua\app.lua:1102: in function <Lua\app.lua:1097>

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The motion handler.
A stack trace is included below, and the handler has been disconnected.
Lua\game_ui.lua:485: attempt to index a nil value (field 'master')
stack traceback:
        Lua\game_ui.lua:485: in method 'onCursorWorldPositionChange'
        Lua\game_ui.lua:551: in function <Lua\game_ui.lua:539>
        (...tail calls...)
        Lua\app.lua:1102: in function <Lua\app.lua:1097>

Warning: No event handler for motion
Warning: No event handler for timer
```

**Comment by tobylane** [comment]
The issue is hovering over double doors while paused. If you briefly play unpaused after building the room, even in the slowest speed, they will connect correctly. We have fixed this for the next release.
