### ISSUE TITLE
[Bug] Cheats menu can be opened in map editor

### ISSUE THREAD

**Issue by Matroftt** [CorsixTH/CorsixTH#2613]
### Describe the issue

Pressing f11 in map editor will result in opening a cheat menu, using it will break the game.
Not a 0.68.0 issue, it can be reproduced in older versions

### Steps to Reproduce

1. Open Map Editor

2. Press F11

3. Done

### Expected Behaviour

It shouldnt open

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

No

### CorsixTH Version

0.68.0 beta-1

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Additional Information

![image](https://github.com/user-attachments/assets/8b52115a-5433-4d3f-811e-a16637ae5bc6)

**Comment by lewri** [comment]
Not a regression from 0.68.0.
However, the fix will be to disable the hotkey bind in the map editor.
