### ISSUE TITLE
[Bug] Long windows not counted as window of a room.

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#2617]
### Describe the issue

4af0e99a added long windows, but the `Room:countWindows()` function (`room.lua` line 1081), doesn't use the newly added long window tiles.

The list tiles (`local window_tile = list_to_set({116, 117, 118, 119, 124, 125, 126, 127})`) is also using hard-coded numbers rather than constants.

### Steps to Reproduce

1. Open `room.lua` at the `Room:countWindows()`` function.
2. Compare the list tiles there with the list in `walls/external.lua`. 
3. You may also check what was changed in 4af0e99a 

### Expected Behaviour

Long windows are also counted as window.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

v0.68.0-rc1

### Operating System

Linux

### Theme Hospital Version

CD

### Gamelog.txt

```bash
Not relevant.
```

**Comment by TheCycoONE** [comment]
They should probably be counted once not for each part.
