### ISSUE TITLE
[Bug] Tooltips in research screen are not consistent

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#2619]
### Describe the issue

In the research screen you can increase or decrease research effort at a research topic.
The buttons to change the effort have tooltip texts. Some of these mention the research topic, while others don't.

### Steps to Reproduce

1. Open the research screen in the original english language.
2. Hover on the increase and decrease buttons, and compare the tooltip texts of the various buttons.
3. Find that not all buttons follow the same pattern.

### Expected Behaviour

All displayed tooltip texts of the research effort buttons should follow the same pattern.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

No

### CorsixTH Version

v0.68.0-rc1

### Operating System

Mint 22

### Theme Hospital Version

CD

### Gamelog.txt

```bash
Not relevant
```

### Additional Information

I dumped the original english strings, and appended the actual strings as comment after the lines that define the lua name. Then I shuffled those lines so the increase and decrease button tooltips are next to eachother, for easy comparing. This is the result:
``` lua
  research = {
    close              = S[32][163],

    cure_dec           = S[32][164], -- "Decrease Cure percentage"
    cure_inc           = S[32][169], -- "Increase Research percentage"

    diagnosis_dec      = S[32][165], -- "Decrease Research percentage"
    diagnosis_inc      = S[32][170], -- "Increase Equipment research percentage"

    drugs_dec          = S[32][166], -- "Decrease Drugs percentage"
    drugs_inc          = S[32][171], -- "Increase Drugs research percentage"

    improvements_dec   = S[32][167], -- "Decrease Improvements percentage"
    improvements_inc   = S[32][172], -- "Increase Improvements percentage"

    specialisation_dec = S[32][168], -- "Decrease Special Research percentage"
    specialisation_inc = S[32][173], -- "Increase Special Research percentage"

    -- S[32][174] unused
    allocated_amount   = S[32][175],
  },
```
Observe:
- The last two pairs are fully consistent with each other, except for the verb (as expected).
- For the `dugs_*` strings, `Drugs` is mentioned in both tooltips, but one has research and one has not.
- `cure_dec` and `diagnosis_inc` do mention the topic, one of them has the additional word "research".
- `cure_inc` and ` diagnosis_dec` do not mention the topic, and in fact look like strings for general tooltips for these buttons rather than topic-specific strings to me.

These strings could use a little ❤️

**Comment by MandrakeHorse** [comment]
A quick reminder that after updating these strings, we'll need to check all their translations as well.

**Comment by MandrakeHorse** [comment]
We should replace the strings so that they follow this format -> "Increase/Decrease [Topic] research percentage"

Suggested replacement strings:

```
    cure_dec           = S[32][164], -- "Decrease Cure research percentage"
    cure_inc           = S[32][169], -- "Increase Cure research percentage"

    diagnosis_dec      = S[32][165], -- "Decrease Diagnosis research percentage"
    diagnosis_inc      = S[32][170], -- "Increase Diagnosis research percentage"

    drugs_dec          = S[32][166], -- "Decrease Drugs research percentage"
    drugs_inc          = S[32][171], -- "Increase Drugs research percentage"

    improvements_dec   = S[32][167], -- "Decrease Improvements research percentage"
    improvements_inc   = S[32][172], -- "Increase Improvements research percentage"

    specialisation_dec = S[32][168], -- "Decrease Specialisation research percentage"
    specialisation_inc = S[32][173], -- "Increase Specialisation research percentage"
```

**Comment by lewri** [comment]
@Alberth289346 does the Dutch interpretation of these strings work as they're written in their lua file?

We could force a rewrite in all languages with `tooltip.research.x_2` but could be overkill.
