### ISSUE TITLE
[Bug] Machine strength and room stats reset on room edit

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2622]
### Describe the issue

If you edit room with machine and change room layout, machine Strength in this room will be automatically reseted to current max value (as for new machine) for free.

<img width="500" alt="x1Screenshot 2024-09-18 at 20 29 14" src="https://github.com/user-attachments/assets/4a07b8ec-c3c1-422a-b52c-6db6785565e0">

### Steps to Reproduce

1. Build room with any machine.
2. Repair this machine or research improvement for it. So machine Strength should be different from the available max Strength value.
3. Remember the current Strength value for machine in this room.
4. Go to edit room mode and move it to any another place.
5. Arrange items and machine in the room. Finish room edit.
6. Check that current Strength is different from the point 3.

### Expected Behaviour

Machine Strength value shouldn't be changed on room realign.

### Save Game

[Campaing_Chriz_03.sav.zip](https://github.com/user-attachments/files/17047993/Campaing_Chriz_03.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
Makes sense, looks like edit room needs to preserve the strength until the room is finished again, hopefully not too hard.

**Comment by ARGAMX** [comment]
Also rooms values "Visitors count" and "Max queue size" resets after room realign.

**Comment by ARGAMX** [comment]
WIP
