### ISSUE TITLE
[Bug] ALLOW FALLING option prevent occupied bench to be moved

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2623]
### Describe the issue

ALLOW FALLING option prevent occupied bench to be taken by cursor.

### Steps to Reproduce

1. Enable ALLOW FALLING option.
2. Try to take any occupied bench and fail.
3. Disable ALLOW FALLING option.
4. Try to take any occupied bench and success.

### Expected Behaviour

Bench should be movable regardless to it occupied status.

### Have you enabled any current CorsixTH Experimental Features?

- [X] Falling actions

### Save Game

Yes

[Campaing_Chriz_03.sav.zip](https://github.com/user-attachments/files/17049251/Campaing_Chriz_03.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
Incorrect order of checks got implemented.

https://github.com/CorsixTH/CorsixTH/blob/ac6b361605c2a3a86f2b625f853c97ec6d32b0c3/CorsixTH/Lua/entities/humanoids/patient.lua#L62-L89

The check for `self.user_of` should come before `TheApp.config.debug_falling and button == "right"`
