### ISSUE TITLE
[Bug] Automatically satisfying salary request does not close the salary request window.

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2625]
### Describe the issue

<img width="373" alt="Screenshot 2024-09-20 at 21 51 30" src="https://github.com/user-attachments/assets/7f16d8d8-ec5e-48d5-a555-d5a2abbef746">

_
Set 'WAGE REQUEST' options to 'GRANT'. When employee requesting salary we get "salary request fax icon". If press the "salary request fax icon" then salary request window will appear. And if we will not take any action in it then salary increase request will be made (grant) automatically. But window will still appear on the screen and there is no way to close it or hide. If we press "rise" button then salary will increase one more time but there no longer any need for this. If we press "dismissal/sacking" button, then employee will be fired.

### Steps to Reproduce

1. Set 'WAGE REQUEST' options to 'GRANT'.
2. In Debug menu check that the option 'DISABLE SALARY RISE' is disabled.
3. Wait for any employee request salary increase.
4. Press the "salary request fax icon" for salary request window appear.
5. Do not take any action in this window.
6. Wait around 2 weeks game time.
7. Salary request will satisfy (grant) automatically.
8. That salary request window still appear on the screen.

[salary_request_situation.sav.zip](https://github.com/user-attachments/files/17083312/salary_request_situation.sav.zip)

### Expected Behaviour

Salary request window should close on automatically resolve.

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by TheCycoONE** [comment]
The expected behavior here is to leave the dialog open but clicking raise doesn't increase any further?

**Comment by MRMIdAS** [comment]
I believe his issue is that by opening the salary request, then waiting the expected time it takes for the request to disappear/auto accept (I believe it's a month?) the icon disappears, and so should the "Salary Request" screen, but it stays.

**Comment by lewri** [comment]
I believe when I improved the check for salary windows code I didn't account for open ones. 

If you wait for the staff member to get sacked (turn grant salary requests automatically off) does the window close?

**Comment by ARGAMX** [comment]
**WAGE REQUEST** options is set to **GRANT**.

@MRMIdAS, yes, correct.

@lewri, if I turn grant salary requests automatically off, then all works correct: after employee automatically fired window closed successfully. But if option is ON, then window stays on screen.

btw 
I read your comments and realized that I didn't understand before that "WAGE REQUEST" and options "GRANT" and "DENY" indeed means: 
"Wage request automatically resolve on no action as" and options "raise salary" and "dismissal/sacking".

I was thought it means that there is choose between 2 options:
GRANT = is fax will shown and ask user for situation resolution.
OR 
DENY = request will be handled automatically immediately by dismissal/sacking (because in original game it was always resolving as "dismissal/sacking" as default automatic resolution).

**Comment by lewri** [comment]
> @lewri, if I turn grant salary requests automatically off, then all works correct: after employee automatically fired window closed successfully. But if option is ON, then window stays on screen.

Thanks :)

That confirms that granting the raise automatically should also ensure window destruction (which clearly was absent from my thoughts at the time). It's not a regression just a regular missed bug at least.

**Comment by ARGAMX** [comment]
WIP
