### ISSUE TITLE
[Bug] 'AgreesToPay' check triggers not in a proper moment.

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2631]
### Describe the issue

If patient already heading to the cure room you can set treatment charge at max value and patient will agree to pay. There is no any 'AgreesToPay' checks on queue join or room door opening.

<img width="320" alt="Screenshot 2024-09-23 at 18 02 40" src="https://github.com/user-attachments/assets/5105fe52-12bb-4396-ab00-f7fae63afeb7">

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. This is gamesave with 6 'Bloaty Head' Emergency guys in progress. Helicopter landing in progress.
3. While Helicopter not landed yet go to Casebook (F5).
4. Find 'Bloaty Head' in list.
5. Set 'treatment charge' at 200% (Hold Ctlr while to increase 25% at one mouse click).
6. Close Casebook and Wait until Helicopter landed and all 6 Emergency patients will shown on screen.
7. Observe that some patients from the Helicopter will refuse to pay price. (if non of them - repeat from step 1).

<img width="180" alt="Screenshot 2024-09-23 at 18 03 40" src="https://github.com/user-attachments/assets/aa808555-79b3-41c6-a8d6-2a5f922c0886">

8. Next. Check the opposite case. *Load save game attached to this ticket*
9. Wait until Helicopter landed and all 6 Emergency patients will shown on screen.
10. Go to Casebook (F5).
11. Find 'Bloaty Head' in list.
12. Set 'treatment charge' at 200%.
13. Observe that non of patients from the Helicopter will refuse to pay 200% price. (if doubt repeat from step 8).

'treatment charge' 100% - you got $5128 from this Emergency.
'treatment charge' 200% - you got $10253 from this Emergency.

### Expected Behaviour

1. 'AgreesToPay' check should be trigger as later as possible (at room door opening?). 
2. At this last check currently 'treatment charge' value should be binded to this patient cure process in this room. So if a treatment price will changed after he entered room but before patient paid this change should not affect the amount of his payment. After cure patient should pay this 'binded value', not the 'treatment charge' value from Casebook.

### Save Game

[bloaty_head_6_guys.sav.zip](https://github.com/user-attachments/files/17099973/bloaty_head_6_guys.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

**Comment by MandrakeHorse** [comment]
It's worth remembering that CorsixTH hasn't implemented overcharging yet, so patients will always pay whatever you charge for a treatment. Earlier this year, I briefly investigated how charging works in the original Theme Hospital (https://github.com/CorsixTH/CorsixTH/discussions/2428) and documented the following observation:

> Patients decide whether they want to pay for treatment before they start walking towards the room. If they decide to pay, the game remembers what the treatment's price was at the time of their decision, so you can't slow time and jack up prices to 200% before they arrive - they will pay whatever the price was when they were referred.

**Comment by lewri** [comment]
> It's worth remembering that CorsixTH hasn't implemented overcharging yet, so patients will always pay whatever you charge for a treatment

I'm not sure that's entirely true, we have code to check diagnosis/treatment costs here:
https://github.com/CorsixTH/CorsixTH/blob/ac6b361605c2a3a86f2b625f853c97ec6d32b0c3/CorsixTH/Lua/entities/humanoids/patient.lua#L298-L306

The point raised about the time to check for whether a patient agrees to play is an interesting one. @MandrakeHorse you may be able to fill us in from the observation in TH when the `overpriced` trigger would occur? Was it at the door of the room, or earlier?

**Comment by mugmuggy** [comment]
Some background on this issue was covered in PR #1732, which allowed them to decide to not pay. And yes, TH stores the 'agreed to pay' amount rather than calculating with the the inflated price.

**Comment by ARGAMX** [comment]
> https://github.com/CorsixTH/CorsixTH/blob/ac6b361605c2a3a86f2b625f853c97ec6d32b0c3/CorsixTH/Lua/entities/humanoids/patient.lua#L298-L306
> 
> `return not (is_over_priced and math.random(1, 5) == 1) `
>

Looks like the possibility of 'AgreesToPay' in case of `is_over_priced` does not depends on the overpriced size?
I mean the chance of AgreesToPay is the same for 150%, 175% and 200% cases?

I thought it should depend on the overprice size.
The bigger is overprice, then the lesser the 'AgreesToPay' chance.
Sounds reasonable?

I can do the research in original game.

**Comment by lewri** [comment]
> I mean the chance of AgreesToPay is the same for 150%, 175% and 200% cases?

Yep I agree with that partially. There is code to work out a price distortion that is subjective to each patient.
https://github.com/CorsixTH/CorsixTH/blob/ac6b361605c2a3a86f2b625f853c97ec6d32b0c3/CorsixTH/Lua/entities/humanoids/patient.lua#L240-L267
Though the treatment being overpriced is more likely as you increase the charging `%`, the actual payment check still succeeds 4/5 times. I'm not entirely sure about the magic at line 264. Though arguably this would be a separate issue.
On another note, `casebook.price` is a silly name for representing a percentage.

**Comment by ARGAMX** [comment]
I have made more research on this and found that:

1. In original TH patients do AgreesToPay check on routing to the room. (as in CTH)
2. After AgreesToPay is success, they bind current price for self and the changes in casebook dosn't affect them. (CTH doesn't do that)

Also if we will call AgreesToPay for the same patient several times, then the chance for agree will reduce on increased price.

Thats mean we can't add an additional checks in the way it checks right now. Only move check from one place, to another.

I will do more research on how AgreesToPay work In original TH in cases when patient binded price and later go to toilet, starting queue from the end. Because in such scenario looks like patient can call AgreesToPay several times. But this will reduce the chance for success on increased price will.

**Comment by ARGAMX** [comment]
> How about an additional check in knock_door.lua?
> 
> ```lua
> function KnockDoorAction:update()
> 
>   if not self.humanoid:agreesToPay(self.humanoid.disease.id) then
>     self.humanoid:goHome("over_priced", self.humanoid.disease.id)
>     return
>   end
> ```

By the moment looks like OK solution.
With one correction:
Check should moved from the place where it located to KnockDoorAction.
AgreesToPay should be call once per patient.
