### ISSUE TITLE
[Bug] Doctor does not rest in the staff room

### ISSUE THREAD

**Issue by ARGAMX** [CorsixTH/CorsixTH#2651]
### Describe the issue

Doctor does not rest in the staff room. There are several unoccupied sofas.
He infinitely wanders around the staff room and never lie down on the sofa.

<img width="208" alt="Screenshot 2024-10-01 at 21 56 37" src="https://github.com/user-attachments/assets/8cc620a7-7c90-4beb-a746-89f47ab02fde">

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. Find doctor # 17 (for 0.66.0 save) or doctor # 5 (for 0.67.0 save).
3. Observe that doctor infinitely walks around the staff room and never lie down on the sofa.

### Expected Behaviour

Doctor should lie down on the sofa in the staff room, rest to the full and leave the room.

### Save Game

[doc_wont_use_sofa_0.66.0.sav.zip](https://github.com/user-attachments/files/17214781/doc_wont_use_sofa_0.66.0.sav.zip)

[doc_wont_use_sofa_0.67.0.sav.zip](https://github.com/user-attachments/files/17214648/doc_wont_use_sofa_0.67.0.sav.zip)

### CorsixTH Version

0.66.0
0.67.0

### Operating System

MacOS Sonoma 14.5

**Comment by lewri** [comment]
Do you have a 0.68 pre release save?

**Comment by lewri** [comment]
In 0.67's one dropping them out the room, then back in resolves the issue. However, we ideally need a save from before this occurs.

**Comment by ARGAMX** [comment]
I have successfully reproduced this bug in 0.68.0 beta 1. 
It turned out that this bug is consequence of #2632 bug.
So if you spam by grabbing of occupied employe and then put him in staff room, he will never rest here. 
The probability of reproduction is 100%.
So for 'before problem' can be any savegame taken.
