### ISSUE TITLE
Make gamelogs unique

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2665]
### What feature or enhancement would you like to add?

Currently when a game crashes we overwrite the gamelog file, which could destroy error trace data before it is reported back to here.

A suggestion here is to generate a tagged gamelog.txt file with the savegame name and date/time in the name to preserve the error entry.

Additionally, a method would need to exist to remove old logs from within the game.

### How would this feature benefit the gameplay of CorsixTH?

While having a single gamelog file makes it simpler for uses, it is potentially destructive in nature. Multiple will allow it to be pinpointed and preserved.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.68.0

### Does this feature/enhancement relate to a current problem?

No

**Comment by tobylane** [comment]
```lua
"Logs" .. pathsep .. os.date("%y-%m-%d--%H-%M-%S--") .. save_name .. "--gamelog.txt"
```
This would create a filename like Logs/24-10-30--22-16-01--test--gamelog.txt. Should it also write to gamelog.txt?

**Comment by TheCycoONE** [comment]
You'll need to have a cleanup policy, we don't want or need logs forever.

**Comment by lewri** [comment]
> Additionally, a method would need to exist to remove old logs from within the game.

Would that note in the op be enough? I'd prefer user managed over automatic but open to either (or both)

**Comment by TheCycoONE** [comment]
I don't think so. Why would someone ever need to go back a month to get this file and why would you make them manually clean it up to recover space.

**Comment by ravenPenfold** [comment]
Another option would be to compress the previous log file upon loading of the game...

**Comment by lewri** [comment]
> Another option would be to compress the previous log file upon loading of the game...

It's likely compression isn't going to be really favoured over cleaning up routinely by the sound of it. Likely a suitable value will be a clean up of files after 1 month.

It would be odd though not to give the user an option in the settings menu to view and clear logs. But the scope of this issue could be a bit messy

**Comment by TheCycoONE** [comment]
This is somewhat a solved problem, we should be able to find an off the shelf logger that does all this.

**Comment by TheCycoONE** [comment]
https://lunarmodules.github.io/lualogging/rolling_file.html for instance

**Comment by TheCycoONE** [comment]
https://github.com/gabime/spdlog would probably be my pick based on under half an hour of research, then expose some of the functions to lua.
