### ISSUE TITLE
New language / Japanese

### ISSUE THREAD

**Issue by ShimaKen523** [CorsixTH/CorsixTH#2672]
### What feature or enhancement would you like to add?

I'd like to try to add new language, Japanese.
It has originally existed in PC and PS version, but not in current one which we can download at GOG.com today.

### How would this feature benefit the gameplay of CorsixTH?

Japanese players can enjoy this game more.

### Was the feature in the original game?

Yes

### What version of CorsixTH are you using?

0.68

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

I reviewed some lua files of other languages, but not sure which one I should use to start my localization of Japanese.
Can I start with English one?

**Comment by lewri** [comment]
Hey :) Great to hear you're interested in translating the game.

The most complete language file currently is likely Ukranian: https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/languages/ukrainian.lua

Guidance on making a translation is available here: https://github.com/CorsixTH/CorsixTH/wiki/Localization

**Comment by MandrakeHorse** [comment]
Honestly, I'm surprised that we don't already have a Japanese translation. @lewri, does Corsixth already support kanji and kana characters or will we need to add them?

**Comment by TheCycoONE** [comment]
Supported

**Comment by TheCycoONE** [comment]
Do you happen to have a japanese version of the original game @ShimaKen523

That language wasn't in the US/UK versions and would have required it's own font sets. I'm interested in those fonts - they would not be covered by copyright at least in the US.

**Comment by ShimaKen523** [comment]
Thank you for all your prompt replies.
I will start my challenge with Ukranian one.

@TheCycoONE , Yes, I have original game disk (wow, it is not DVD but CD!)
It seems there are two font files. Let me attach them here, though I am not sure it is allowed.
[Font12j.zip](https://github.com/user-attachments/files/17395739/Font12j.zip)

**Comment by lewri** [comment]
Was there a `LANG-x.DAT` file in `Data/`? I wonder if Japanese just took `LANG-7.DAT`

**Comment by ShimaKen523** [comment]
I found 7 LANG-x.DAT (0-6) files in HOSP/Data/, and seems #6 was for Japanese!
Is there any good way to transfer DAT file to LUA file?
Do I need to do just find-copy-paste?

**Comment by TheCycoONE** [comment]
That part we can't do, the original game text is their copyright. The lang file is probably in a different code page than the ones in the GOG/western version.

A developer with that version could make it work but I don't know where to get it.

**Comment by ShimaKen523** [comment]
Well noted. We must respect their copyright.
I have finished first 1000 lines, and need to start another 1000 lines.
I will store the lua file once I finished everything.

**Comment by ShimaKen523** [comment]
My work is almost done, except end of year trophies room.
I found two weird English ones. What should I do? (Do I need to submit it to another tree?)

`trophy_room.cleanliness.regional_good[1] = "Your hospital has been noted as one of the least clean in the area. A dirty hospital is smelly and dangerous. You should pay more attention to mess."`
-> I think it should be good one, but seems bad meaning in English.

`trophy_room.best_value_hosp.trophies[1] = "Congratulations on receiving the SqueakiKlean Trophy for the hospital with the best reputation over the last year. Well deserved it is too."`
-> I think it should be best VALUE but seems mentioning REPUTATION.

**Comment by lewri** [comment]
> My work is almost done, except end of year trophies room. I found two weird English ones. What should I do? (Do I need to submit it to another tree?)

Neither of these are implemented yet in the Annual Report. Some translations have added them anyway.

> `trophy_room.cleanliness.regional_good[1] = "Your hospital has been noted as one of the least clean in the area. A dirty hospital is smelly and dangerous. You should pay more attention to mess."` -> I think it should be good one, but seems bad meaning in English.

I agree the English is poorly worded, but there's no priority to change the English one yet. In your Japanese translation (if you include it), feel free to alter it slightly if you think it would work better another way.

> `trophy_room.best_value_hosp.trophies[1] = "Congratulations on receiving the SqueakiKlean Trophy for the hospital with the best reputation over the last year. Well deserved it is too."` -> I think it should be best VALUE but seems mentioning REPUTATION.

That does appear to be an error reading around its other related strings. Please don't translate this string; the English (and other base languages) will have to be rewritten at some point.

**Comment by ShimaKen523** [comment]
Thank you for your prompt reply as always.
I would like to share Japanese.lua as attached.
It is well worked in my laptop. I hope nothing critical for others.
If you could include this Lua file in the next version, it would make me incredibly happy.
[japanese.zip](https://github.com/user-attachments/files/17619429/japanese.zip)

**Comment by MandrakeHorse** [comment]
@ShimaKen523 Thank you for making this Lua file! I'll create a pull request with the necessary changes and link it to this ticket.
