### ISSUE TITLE
[Bug] Plants not being watered while inside "bench loop"

### ISSUE THREAD

**Issue by masterofobzene** [CorsixTH/CorsixTH#2681]
### Describe the issue

![2024-10-18 12-57-35](https://github.com/user-attachments/assets/43993abb-1b23-4365-ac7e-02c3fd06e444)

This layout can be used in original TH but not in corsix. Helps with patient's happyness (and is visually pleasant).

### Steps to Reproduce

1. Put plants inside a "bench loop" (doable in original TH, already opened another issue for this)

### Expected Behaviour

The janitors should be able to water the plants inside the "bench loop" as in the original game.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68

### Operating System

Windows 10 x64

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
No log generated for me in 0.68.
```

### Additional Information

No log generated for me in 0.68.

**Comment by ARGAMX** [comment]
https://github.com/CorsixTH/CorsixTH/issues/1738

**Comment by TheCycoONE** [comment]
Closing as duplicate. Thands @ARGAMX
