### ISSUE TITLE
[Bug] Training seems to be broken.

### ISSUE THREAD

**Issue by masterofobzene** [CorsixTH/CorsixTH#2683]
### Describe the issue

Tried 3 doctors already, they get to consultant grade and then I cannot teach them the skills, placing them inside training room again makes the real teacher leave the room.

### Steps to Reproduce

1. Put a consultant with 2 or more skills as a teacher.
2. Put a medic with no skills to learn.
3. Trainee may get ONE skill and get to consultant, making it impossible to train him on both skills. This could be done in original TH. More [info here](https://bullfrogproductions.fandom.com/wiki/Training_Rooms)

### Expected Behaviour

The trainee should get both skills learned.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68

### Operating System

Windows 10 x64

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
No log on 0.68 for me
```

### Additional Information

No log on 0.68 for me

**Comment by ARGAMX** [comment]
#2262 #1458 #2603 #2314

**Comment by TheCycoONE** [comment]
Duplicate.
