### ISSUE TITLE
Remove deprecated Eclipse Lua Debugger

### ISSUE THREAD

**Issue by lewri** [CorsixTH/CorsixTH#2705]
Our remote debugging solution is no longer properly supported and pretty much obsolete.

As the debugging is seldom used outside the main developers, it should be stripped out with nothing remaining (or the barebones `run_debugger.lua` entry point).

Update Wiki instructions on remote debugging, suggesting solutions like ModDebug with ZeroBranesStudio IDE.

**Comment by lewri** [comment]
Tasks:

* [ ] Strip debugger from `CorsixTH.lua`
* [ ] Remove `run_debugger.lua` file
* [ ] Strip debugger start command from `README.txt`
* [ ] Update `debug_script.lua` explanation text to be better understood
* [ ] Strip debugger settings from config files
* [ ] Strip debugger hotkeys
* [ ] Strip run debugger menu item
* [ ] Update Wiki page for running a debugger from Eclipse. Recommended MobDebug

**Comment by TheCycoONE** [comment]
Slight correction, it's Mo**b**Debug rather than https://github.com/pkulchenko/MobDebug

**Comment by TheCycoONE** [comment]
Updated the wiki with information about ZeroBrane and demoted information about Eclipse. More debuggers can be filled in over time. I don't like holding issues open about the wiki as a policy.
