### ISSUE TITLE
Allow transparent walls without requiring holding down a hotkey

### ISSUE THREAD

**Issue by ajhbh** [CorsixTH/CorsixTH#2720]
### What feature or enhancement would you like to add?

Currently it is possible to have transparent walls by holding down a hotkey. It would be a great enhancement if, rather than needing to keep the hotkey held down, this could be a toggle to switch on/off or some other similar setting to achieve the effect of being able to have transparent walls enabled all the time without needing to hold down a key.

### How would this feature benefit the gameplay of CorsixTH?

Users can see behind walls all the time.

### Was the feature in the original game?

Unsure

### What version of CorsixTH are you using?

0.68

### Does this feature/enhancement relate to a current problem?

No

**Comment by MandrakeHorse** [comment]
We're always welcome to new ways of improving accessibility! The most obvious place to put this toggle in Custom Settings. We could also expand this feature to include pressing Z to toggle maximum/"and then some more" speed.

**Comment by ARGAMX** [comment]
> ### What feature or enhancement would you like to add?
> Currently it is possible to have transparent walls by holding down a hotkey. It would be a great enhancement if, rather than needing to keep the hotkey held down, this could be a toggle to switch on/off or some other similar setting to achieve the effect of being able to have transparent walls enabled all the time without needing to hold down a key.
> 

Currently you can achieve this by press and holding down transparent key, then select top menu, select save game, press save button. You can now release the key. Next load that save game - voila, now the walls are always transparent.
