### ISSUE TITLE
Improve the tooltips for Hotkey Assignment screen

### ISSUE THREAD

**Issue by MandrakeHorse** [CorsixTH/CorsixTH#2721]
### What feature or enhancement would you like to add?

The Hotkey Assignment screen displays some tooltips when you hover over each button. However, most of these tooltips simply repeat the label of the button. These should be replaced with something more useful:

- Global Keys -> "Global Keys"
- General In-Game Keys -> "General In-Game Keys"
- Game Speed Keys -> "Open window to set keys to control game speed"
- Scroll Keys -> "Scroll Keys"
- Zoom Keys -> "Zoom Keys"
- Toggle Keys -> "Toggle Keys"
- Panel Keys -> "Open window to assign panel keys"
- Recall Position Keys -> "Open window to set keys to store and recall camera positions"
- Debug Keys -> "Debug Keys"

### How would this feature benefit the gameplay of CorsixTH?

More useful tooltips will help players understand what each section covers.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.68

### Does this feature/enhancement relate to a current problem?

No

**Comment by TheCycoONE** [comment]
The hardest part of this one is coming up with useful tool tips. Suggestions welcome.

**Comment by MandrakeHorse** [comment]
Found the existing tooltips in the english.lua file:
https://github.com/CorsixTH/CorsixTH/blob/b85335272f1bda9fc5cf462f098ea13cab431ff0/CorsixTH/Lua/languages/english.lua#L681C1-L690C1

**Comment by MandrakeHorse** [comment]
Some simple descriptions with a consistent structure will suffice. For example:
- Global Keys -> "Assign global hotkeys"
- General In-Game Keys -> "Assign general in-game hotkeys"
- Game Speed Keys -> "Assign hotkeys to control the game speed"
- Scroll Keys -> "Assign hotkeys to scroll the screen"
- Zoom Keys -> "Assign hotkeys to zoom in and out"
- Toggle Keys -> "Assign hotkeys to toggle options"
- Panel Keys -> "Assign hotkeys to open panels"
- Recall Position Keys -> "Assign hotkeys to save and recall camera positions"
- Debug Keys -> "Assign hotkeys for debugging"
