### ISSUE TITLE
Error when moving a staff member

### ISSUE THREAD

**Issue by NigeNigeNige** [CorsixTH/CorsixTH#278]
Hi, I downloaded CorsixTH for the first time today and ran into this pretty quickly.

What steps will reproduce the problem?
1. Play level 1 until you have a staffroom with at least one couch and a tired doctor sitting in it
2. Click on the doctor so that his properties window appears
3. Click the 'pick up' button to pick up the staff member and move him

What is the expected output? What do you see instead?
Expected: The doctor is picked up from the couch and can be placed elsewhere
Actual: The doctor is picked up and so is the couch he is sitting on. He then can't be placed anywhere, nor can the 'picking something up' state be cancelled, so the game is effectively broken.

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
0.30 

What operating system / compile settings are you using?
Windows 7 64-bit

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game level 1

Here's the contents of my log:
Created game with savegame version 78.
Warning: Trying to remove nonexistant room build callback (function: 0x0cede218) from humanoid (table: 0x0d50e200).
Warning: Trying to remove nonexistant room remove callback (function: 0x02590cf0) from humanoid (table: 0x0d50e200).
Warning: Trying to remove nonexistant room build callback (function: 0x0cf6c940) from humanoid (table: 0x0d50e200).
Warning: Trying to remove nonexistant room remove callback (function: 0x0cf2b3f8) from humanoid (table: 0x0d50e200).
Error in buttonup handler: 
D:\Games\CorsixTH\Lua\humanoid_actions\queue.lua:71: Proper idle not in action_queue
stack traceback:
    [C]: in function 'error'
    D:\Games\CorsixTH\Lua\humanoid_actions\queue.lua:71: in function 'action_queue_find_idle'
    D:\Games\CorsixTH\Lua\humanoid_actions\queue.lua:225: in function 'onChangeQueuePosition'
    D:\Games\CorsixTH\Lua\queue.lua:194: in function 'pop'
    D:\Games\CorsixTH\Lua\room.lua:476: in function 'tryAdvanceQueue'
    D:\Games\CorsixTH\Lua\room.lua:355: in function 'onHumanoidEnter'
    D:\Games\CorsixTH\Lua\humanoid_actions\pickup.lua:28: in function 'on_interrupt'
    D:\Games\CorsixTH\Lua\entities\humanoid.lua:613: in function 'setNextAction'
    D:\Games\CorsixTH\Lua\dialogs\place_staff.lua:56: in function 'close'
    D:\Games\CorsixTH\Lua\dialogs\place_staff.lua:132: in function 'onMouseUp'
    D:\Games\CorsixTH\Lua\window.lua:1390: in function 'onMouseUp'
    D:\Games\CorsixTH\Lua\ui.lua:703: in function 'dispatch'
    D:\Games\CorsixTH\Lua\app.lua:739: in function <D:\Games\CorsixTH\Lua\app.lua:734>

**Comment by lewri** [comment]
After 6 years have we had more reports of this? May be safe to assume resolved.
