### ISSUE TITLE
Demo to full: Cannot access the Research window

### ISSUE THREAD

**Issue by marcelhbertonzzin** [CorsixTH/CorsixTH#279]
Hi everyone,

I'm using the 0.30 version with Ubuntu 14.04 and the videos disabled.

The problem is that I cannot access the Research window even after building the Research Dept. The doctor keeps saying that I need to build it.

The odd thing is that the new conditions keeping being found and I can send patients to the room without a problem, two doctors are working there too.

Please tell me if I can provide any information that would be helpful.

**Comment by lewri** [comment]
This bug is still present in 0.64 when switching from demo to full. However, if you switch while your hospital is in full swing, things usually break.

**Comment by lewri** [comment]
I would suggest we lock demo hospitals and full game hospitals from being opened interchangeably. Things will just break as what exists in one may not be in the other.
