### ISSUE TITLE
Placing bench, mouse not working, game is continuing on background (OSX and WINDOWS) reproducible

### ISSUE THREAD

**Issue by DjCoke** [CorsixTH/CorsixTH#291]
I get the following bug:

Every where when i move or place a new bench, the game won't respond to mouse commands or other ones, any longer. 

It will do this on both osx and windows version 0.30

---

Welcome to CorsixTH 0.30!

---

This window will display useful information if an error occurs.

---

[smk @ 00000000113c1300] max_analyze_duration 5000000 reached at 5016000
Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\world.lua:1823: attempt to perform arithmetic on f
ield 'tile_x' (a nil value)
stack traceback:
        C:\Program Files\CorsixTH\Lua\world.lua: in function 'objectPlaced'
        C:\Program Files\CorsixTH\Lua\world.lua:1802: in function 'newObject'
        C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:502: in function
 'placeObject'
        C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:465: in function
 'onMouseUp'
        C:\Program Files\CorsixTH\Lua\window.lua:1390: in function 'onMouseUp'
        C:\Program Files\CorsixTH\Lua\ui.lua:703: in function 'dispatch'
        C:\Program Files\CorsixTH\Lua\app.lua:739: in function <C:\Program Files
\CorsixTH\Lua\app.lua:734>

Warning: No event handler for buttonup

"The place new bench window" will allow to press buttons, but nothing happens, also sometimes the window moves with the mouse cursor.

On OSX: the bug is very annoying, in full screen, no way to close the program. hard reboot still does the trick though.

Screenshot
https://www.dropbox.com/s/s9mxe6w9njmyn5s/Screenshot%202014-08-06%2023.55.46.png
![image](https://user-images.githubusercontent.com/20030128/90294143-a3497500-de7d-11ea-8e66-8dd59373a965.png)

Save file:
https://www.dropbox.com/s/uivkce7ld9foxtg/Erwin%20lvl%204.sav

**Comment by lewri** [comment]
I can't seem to reproduce this behaviour in 0.64.

But got a different issue I'll have to make a report for.

**Comment by lewri** [comment]
Assume resolved based on comments in #293
