### ISSUE TITLE
User and campaign maps should not have earthquakes unless they opt in

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#296]
At the moment it is hard coded that there can be no earthquakes in the first 4 levels of the campaign. However this does not help with custom maps as leaving earthquake control blank still generates random earthquakes.

When a level contains only the instruction `#quake_control[0].StartMonth.EndMonth.Severity 0 0 0` no random earthquakes should be added.

**Comment by TheCycoONE** [comment]
I think this behavior from the original (no random earthquakes) would be a good fix.

**Comment by MarkL1961** [comment]
Or a toggle that allows you to turn off random earthquakes.  As I said in the other issue this then gives the player the choice of not having any in a map they create or for that to be ignored by turning on randoms.
It should be a simple enough fix, as I recall when I attempted a solution it was the random that caused me the problems when trying to make it accept 0 severity means none and remove the hard coded bit for levels 1 - 5 or something like that.

**Comment by TheCycoONE** [comment]
Alright, I think it's fine to add a new level flag to enable/disable random earthquakes, defaulting to disabled.

**Comment by Stefan1200-de** [comment]
I support this, also looking for a way to disable earthquakes in custom levels (not playing campaign). Is that already possible?

**Comment by Alberth289346** [comment]
the issue is still open, so no

**Comment by TheCycoONE** [comment]
The current earthquake trigger is wrong. I'm in favor of earthquakes being purely opt-in, and only at the dates defined in the level file. If we want random quakes indefinitely we can add a new level file line for that.

**Comment by MarkL1961** [comment]
I can't see this mentioned here, but it may have been said elsewhere. In TH you always had a warning (tremor or slight screen jolt) to tell you a quake was on the way.  This was when most of us would have slowed the game down and checked all our machines were up to it.  CorsixTH is lacking this tremor.   

Edvin and I did look at this a few years back, but the current code is complex and Edvin was busy at that time.  Was thinking that perhaps a month prior to the specified quake the screen moves quickly and you get the warning announcement etc, but no damage - then get the quake.

In favour of the other suggestions as well

**Comment by TheCycoONE** [comment]
Thanks @MarkL That warning was critical on later earthquakes.

**Comment by TheCycoONE** [comment]
I've run several tests on the original with earthquakes added to the first level.

Unlike ours it seems nothing is random in the original:
Damage is the severity of the earthquake. We do severity plus or minus 1.
The earthquake always happens in the month following end month (accounting for 0 based months), we pick a random date between start date and end date.
They have a warning tremor that does not damage about 12 days before, we are missing that.

Other observations
The day of the month is consistent each time I restart but not between different  earthquakes in the same level. I don't know what determines this.

**Comment by MarkL1961** [comment]
@TheCycoONE  I am not sure I understand your "Other observations" regarding different earthquakes in the same level?

**Comment by TheCycoONE** [comment]
I was wrong about never happening between start month and end month.

What I mean is if you replay the same level quakes will happen on the same date every time you play. But from the level config I can't predict when that date will be.

**Comment by TheCycoONE** [comment]
Anyway I think that's just due to the way randomness is handled in the original. The only real difference is +-1 severity and the 12 day warning

**Comment by TheCycoONE** [comment]
And that we insert random earthquakes after the scheduled ones - which I would like to drop. No reason to treat earthquakes different from other scheduled events in this regard.

**Comment by MarkL1961** [comment]
Agreed

**Comment by TheCycoONE** [comment]
Fixed
