### ISSUE TITLE
Staff image corruption 

### ISSUE THREAD

**Issue by mpmc** [CorsixTH/CorsixTH#308]
I've just came across this when hiring staff..

![staff](https://cloud.githubusercontent.com/assets/2352508/4254443/d4d70f32-3aab-11e4-86b5-4ba058364fb5.png)

There is no error log, just image corruption!

Sys Info as in screenshot: Windows 7 x64 OpenGL :)

**Comment by Lego3** [comment]
As we are now on SDL2 I'll close this issue. Please reopen it if the problem persists on SDL2
