### ISSUE TITLE
Freeze "Running: The frame handler"

### ISSUE THREAD

**Issue by marc-cairo** [CorsixTH/CorsixTH#327]
The game is suddently not responding anymore. This happened 3 times in 30 minutes.
I cannot reproduce this problem. I remember that I had checked a doctors profile to see his skills.
The last error I got when I placed a seat in the training room (see screenshot).

Sadly, there is no stack trace in the console:
![th error 0 40 beta1](https://cloud.githubusercontent.com/assets/3812889/4599183/094271b2-50c3-11e4-9a80-41934f7be6f9.PNG)

I had an issue in 0.30 where my game suddenly hangs. But that was different:
in 0.30:  game hangs every 2-3 hours.   Now more often.
in 0.30:  mouse stuck, but game was still running in background (sound still working).   Now the process is not responding at all.
in 0.30:  no output in console.   Now there is at least a message that an error occurred :-)

I am using windows 8.1  64bit

**Comment by pwaller** [comment]
I just hit this on master.

**Comment by TheCycoONE** [comment]
Interesting that the original comment here and #715 both reference clicking a doctor as the trigger.

**Comment by bobcanthelpyou** [comment]
I am not sure but i think that problem is somehow LuaJIT related, i can't reproduce these freezes with Lua only. But running CorsixTH with LuaJIT the problem occurs very often. Any ideas how to debug problems with LuaJIT? At https://github.com/CorsixTH/CorsixTH/issues/753 is a gdb backtrace but it seems to be not very helpful.

**Comment by TheCycoONE** [comment]
Even for lua debugging jit mode needs to be disabled in LuaJIT. I'm not sure how to begin debugging this unfortunately. In the mean time we are recommending plain Lua instead.

**Comment by TheCycoONE** [comment]
I believe we fixed this when I readded support for LuaJIT 2.x only.
