### ISSUE TITLE
Fax about cure when room isn't built

### ISSUE THREAD

**Issue by mpmc** [CorsixTH/CorsixTH#329]
I'm playing the 0.40b1 build (SDL, Win7 x64), on level 2.

I've had a patient with slack tongue, I have no research dept so I have no slack tongue clinc, yet I'm greeted with this... (paused for screenie).
![image](https://cloud.githubusercontent.com/assets/2352508/4630160/31195558-53ab-11e4-8c49-d58f6d769c4a.png)

And after selecting take a chance at the cure I get another fax with this.. 

![image](https://cloud.githubusercontent.com/assets/2352508/4630276/220532de-53ac-11e4-824f-589cd45fd4f8.png)

And while typing this, I've sent the patient home and received another fax for slack tongue..84% this time.. :/

![image](https://cloud.githubusercontent.com/assets/2352508/4630706/8f8206d6-53af-11e4-9de1-44ba3ba7829f.png)
- No debug info in log :/
- Split issues.

**Comment by lewri** [comment]
I'm not sure if this issue still still exists? What exactly is the key desire in this issue as it feels a bit lost in the discussion.

**Comment by lewri** [comment]
Have replayed in 0.65.1. This issue is no longer of concern
