### ISSUE TITLE
debug mode changes game behaviour (hides first built room information)

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#337]
This behaviour was intentional, it was introduced in 41c8b342b9ba162d1b2c4f1552cb4588ffd8279d but my feeling is that it's an unexpected / seemingly unrelated functionality change from the act of debugging, and in the case of #256 actually made debugging harder because toggling information off prevented the error.

@MarkL1961 mentioned that this had been discussed in google issues.  I haven't been able to find the issue in a quick skim, but if someone can find it there it would be interesting to see the reasons why this change was introduced in the first place.

My recommendation at this point is to introduce a config option specifically for whether to show first time room information dialogs, and to disassociate it with the debug flag.

**Comment by lewri** [comment]
PR #1360 mentions that this had already been fixed.

**Comment by TheCycoONE** [comment]
PR comment is wrong, this is not fixed. Actually that PR would still be useful.
