### ISSUE TITLE
use of undeclared variable 'needed_objects_name  0.40

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#350]
I am going to assume this is specific to 0.40 as I don't recall seeing this error before.
Using beta 2, just finished off the previous game started in beta 1 and decided to jump from level 1 - 6 to test out epidemics again.

I am laying out the hospital rooms and just got to Feb 2nd, then whilst building my third GP room got this error message when attempting to place the first object being the desk.

Created game with savegame version 88.
Savegame version is 88 (Trunk), originally it was 88 (Trunk)
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\world.lua:1954: use of undeclared variable 'needed_objects_name'
stack traceback:
	[C]: in function 'error'
	C:\Program Files\CorsixTH\Lua\strict.lua:43: in function '__index'
	C:\Program Files\CorsixTH\Lua\world.lua:1954: in function 'willObjectsFootprintTileBeWithinItsAllowedRoomIfLocatedAt'
	C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:644: in function 'setBlueprintCell'
	C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:780: in function 'onCursorWorldPositionChange'
	C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:236: in function 'addObjects'
	C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:85: in function 'constructor'
	C:\Program Files\CorsixTH\Lua\class.lua:73: in function 'UIPlaceObjects'
	C:\Program Files\CorsixTH\Lua\entities\object.lua:666: in function 'onClick'
	C:\Program Files\CorsixTH\Lua\ui.lua:739: in function 'dispatch'
	C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>

I am not adding the save as it does not repeat the error

**Comment by Lego3** [comment]
If someone has experienced this recently, please reopen the issue.
