### ISSUE TITLE
Nurse freeze

### ISSUE THREAD

**Issue by auguster** [CorsixTH/CorsixTH#357]
My nurses keep freezing in place. At first I thought it was happing when they were coming out from the rest room but it happened also in the corridor.

I'm running 0.40 beta 2 and the full game (in french) on Windows 7 x64. I'm not sure what level I'm at, I think it's the one with a plane crash on the board game. I left the CorsixTH settings untouched.

Here is a save right before it happening:  https://drive.google.com/file/d/0B1Me6G50GsdRdTBtWG8wcWJGQ0U/view?pli=1
You will also see a bunch of frozen fired nurse in front of the rest room.

**Comment by sadger** [comment]
Fixed by a713a222e557cf4b366453cee32b1339025a1b41
