### ISSUE TITLE
Doctor get stuck in room when quits/fired 0.4beta

### ISSUE THREAD

**Issue by sirlimpy** [CorsixTH/CorsixTH#358]
Doctor gets stuck in room after he has quit or been fired. 
![cthbug](https://cloud.githubusercontent.com/assets/7224313/4908762/4ad8cda2-646d-11e4-9ed9-2f3cb03f33b9.png)

hes in the top gp room next to the door

I have a save file with it as well

**Comment by Lego3** [comment]
Closing from lack of more info.
