### ISSUE TITLE
Zoom related graphical glitches [SDL2]

### ISSUE THREAD

**Issue by sadger** [CorsixTH/CorsixTH#370]
I have been testing some custom graphics and both with and without the custom graphics loaded the whole SDL2 version is very glitchy. Picking up objects or zooming in can make the rendering mess up. Often it seems it is displaying sprites that have been rendered in the past so you get duplicates all over the screen.

Tested on ArchLinux 64bit. 

An screenshot to give you an idea of what happens quite often:
![glitchy](http://i.imgur.com/APm32sv.png)

Notice the repeated receptionist and the filing cabinet in the GP.

**Comment by sadger** [comment]
This is still an issue in the latest master (6316114) since sdl2 has been merged. Makes the game unplayable for me. I'll see if I can track down what is causing it. 

Video of the offending glitches:
https://www.youtube.com/watch?v=ny7aVIUxBno

**Comment by Lego3** [comment]
So far I haven't seen this type of issue when running on Windows. What I have seen though is that it sometimes can show a black frame.

**Comment by pwaller** [comment]
I've hit it too. Linux Ubuntu 14.04 x64 d61335421a5c0a9e3121c868e033d5f33279296b.

**Comment by sadger** [comment]
I can confirm that it is the zooming for me causing these glitches. The offending commit for me is commit 476df8b. adding zoom support to sdl2. I tried the fix by @pwaller  but didn't fix any of the glitches for me. But checking out the commit prior to 476df8b I have no graphical issues.

**Comment by Andy51** [comment]
Some additional info on various zoom glitches.

1. Do some zooming
2. Start placing a room -> Bottom GUI panel disappears
3. Place the door and press "Confirm" -> The whole screen blinks black
4. Press "Cancel" -> The room still displayed in furnishing mode, ground cursor gets duplicated
![screenshot8](https://cloud.githubusercontent.com/assets/4835002/5989424/cdca693a-a998-11e4-84ac-fb0c1c1af406.jpg)

And in fullscreen mode additional to listed above:
1. Do some zooming -> bottom GUI panel jumps to the center of the screen
![screenshot6](https://cloud.githubusercontent.com/assets/4835002/5989443/6ad1e7d0-a999-11e4-8fb4-17c9d97d5790.jpg)
2. Start placing a room -> notice the ground cursor position vs mouse cursor:
![screenshot5](https://cloud.githubusercontent.com/assets/4835002/5989449/93f5daea-a999-11e4-8c90-67f445ec5ebe.jpg)

**Comment by Andy51** [comment]
Oh, just noticed #616 has exactly the same sympthoms as reported above, so it must be the same one

**Comment by sadger** [comment]
Yes it's very likely probably related. I think an intermediate solution might be to disable zooming until it can be fixed properly.

**Comment by pwaller** [comment]
PR #632 fixes the problem for me, at the expense of making the objects being built the wrong size.

**Comment by sadger** [comment]
I tried that @pwaller but sadly didn't fix it for me :(

**Comment by TheCycoONE** [comment]
If zoom still causes problems when we're getting close to release I'll disable it, for now there's still plenty of time to sort out the issues, and the workaround is not to zoom.  Put some tape over that mouse wheel @sadger ;-)

**Comment by TheCycoONE** [comment]
And because it's not explicitly stated here, the scaling on sprites that are drawn on the mouse location (which are not part of the zoom texture) appears to be the problem with the ghosting cursors. The other issues @sadger has may be unrelated.

**Comment by pwaller** [comment]
I've cracked it, and I've got a branch which doesn't seem to exhibit this bug! Please take a look at #370 :grinning:
