### ISSUE TITLE
0.40b2: Cannot load SAV previously saved by 0.40b1

### ISSUE THREAD

**Issue by mpmc** [CorsixTH/CorsixTH#371]
Unable to continue/Load game

Platform: Windows 7 x64 - All Engines fail to load sav file.
```
<LocalisedString> Current value:Error while loading game: D:\Games\CorsixTH\Lua\
persistance.lua:234: Cycle while depersisting permanent object key or userdata m
etatable after 9726 objects (265107 bytes)
```

http://www.markclarkstone.co.uk/Autosave5.sav

**Comment by Lego3** [comment]
As we have nothing more to go on, I'll close this. If it happens again, please file a new issue or reopen this one.
