### ISSUE TITLE
New arrivals claim position in Reception Queue too soon

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#372]
Everyone joins the queue for reception as soon as they enter the hospital.  If you have your desk near to the only entrance this is not so noticeable.  However as you can see in the picture the doors at the bottom are a long way from the desk, but he is already second in the queue.  This can cause a queue to build up at reception when there are multiple entrances and lots of visitors.  VIPs stop others being dealt with as they are pushed to the front, even though they may be a long way from the desk.

This is not a regression, it has been this way for a while now.

![reception_queue](https://cloud.githubusercontent.com/assets/4965487/4982292/a763cf24-6911-11e4-893a-501268b9f43a.png)

**Comment by MarkL1961** [comment]
5 or 6 tiles would be better @phillipp

**Comment by TheCycoONE** [comment]
Is the new title right, or does this apply to all arrivals?

**Comment by MarkL1961** [comment]
All arrivals, VIP gets pushed to the front and blocks reception until he gets there.  Others join the queue in the order they arrive in the hospital, no matter how far from the desk they are

**Comment by lewri** [comment]
There's a commit mentioning this on mugmuggy's own repo. Has this commit been implemented in any way to CorsixTH?

**Comment by mugmuggy** [comment]
@lewri No it hasn't as yet, from memory there was some quirk with it or it was visually masking another issue. It is on my todo list
