### ISSUE TITLE
Patient with "EXIT" status still in queue, and then causes unexpected behavior

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#385]
![screenshot1](https://cloud.githubusercontent.com/assets/9609391/5024048/fd5f373a-6b03-11e4-83e8-d01eef107715.jpg)

One thing: this patient is from 0.40 beta 2 save game, but now I'm playing 0.40 beta 3. Maybe there is connection.

This patient is in exit status but she is still waiting for room. But I can not kick her out. 

When she gets a surgical intervention, she wont pay, but there is an issue with dressing a she's stuck. It's some how connected with doctor on right side. When I move him, she will finish dressing, leave room. But she will be waiting for room againg... and again.

![screenshot3](https://cloud.githubusercontent.com/assets/9609391/5024107/4c25b758-6b05-11e4-9c8e-817bcd5dcbf4.jpg)

Save before stuck:
https://drive.google.com/file/d/0B22eJ2vI7RgLN2ItSmZ2OGZ6Wjg/view?usp=sharing

Save after stuck:
https://drive.google.com/file/d/0B22eJ2vI7RgLS0cwaGpTN3ZXMWc/view?usp=sharing

**Comment by lewri** [comment]
Error output looks like the jump in savegame versions is too much to logically analyse the save any more.

```
Savegame version changed from 88 (0.40) to 138 (v0.64). The save was created using 88 (0.40)
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\rooms\operating_theatre.lua:202: attempt to index a nil value (global 'surgeon1')
stack traceback:
        Lua\rooms\operating_theatre.lua:202: in method 'loop_callback'
        Lua\humanoid_actions\multi_use_object.lua:257: in local 'timer_function'
        Lua\entity.lua:216: in field 'tick'
        Lua\entities\humanoids\staff.lua:105: in field 'tick'
        Lua\entities\humanoids\staff\doctor.lua:93: in method 'tick'
        Lua\world.lua:1042: in method 'onTick'
        Lua\app.lua:1111: in function <Lua\app.lua:1108>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

**Comment by TheCycoONE** [comment]
Let's close this. We've change a lot of behavior since then, and there isn't anything useful in this ticket now. If it happens still a fresh ticket can be made.
