### ISSUE TITLE
Uncleaneable litter

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#388]
I found a litter, which can not be clean. It's second time, so I choose to report it too. Every time it's near reception desk. (It was removed before I take a screen).

![screenshot0](https://cloud.githubusercontent.com/assets/9609391/5036229/5ee18f06-6b7e-11e4-9b78-9d219dcaae6e.jpg)

I can place new room over it, but if I try to remove that room, game will stuck.

Here is the save game: https://drive.google.com/file/d/0B22eJ2vI7RgLdW1nb2VXQmRLbGs/view?usp=sharing

Using 0.40 beta 3, language Czech, Windows 7 x64.

**Comment by bobcanthelpyou** [comment]
I have a similar issue, the vomit on the floor is ignored by the handymen near the reception desk.

![bildschirmfoto von 2015-06-19 22 28 49](https://cloud.githubusercontent.com/assets/4523264/8262459/e31c6fa2-16d2-11e5-9877-6077c5448405.png)

http://filebin.ca/25oH9ZCBy76j/vomit.sav

Trunk (master branch) version of CorsixTH

**Comment by Alberth289346** [comment]
It seems to be a regular 'puke'. The only mystery is that it is not in the 'todo' list of the hospital for handyman. Since handyman only looks in that list for things to do, it doesn't see this vomit.

If you add it again by hacking the source code, the handyman promptly cleans it up.
Did something special happen with any handyman, during the game?

**Comment by bobcanthelpyou** [comment]
I don't know what happened there. Is it possible to log objects that should be on the 'todo' list, but which are not? Or to 'pause' the game like when an error occurs? I could try to take a look at the patients when they vomit, but i am not sure if the maps are to big and i might miss the problematic one.

**Comment by MarkL1961** [comment]
@Alberth289346  In TH dropping the handyman on the  litter would make him clean that first. Could our code be altered so that when we drop an handyman on a task like litter cleaning it gets added to the list with the priority to do it next?

**Comment by MarkL1961** [comment]
Could it be that  the handyman assigned this task was sacked, quit or killed in an exploding room?  Are tasked reassigned?

**Comment by bobcanthelpyou** [comment]
> Could our code be altered so that when we drop an handyman on a task like litter cleaning it gets added to the list with the priority to do it next?

+1

**Comment by Alberth289346** [comment]
@MarkL1961 I suspect something like that happened. I see tasks being de-assigned, but it happens in different ways at different places, which is of course suspicious.

I am not in favor of adding a second system on top of a broken system for fixing. While things may look solved for a while, you also create a big maze with even more complicated edge cases than we currently have. I already fail at solving the current ones, let alone if I get more complicated ones.

In all, my conclusion is that the 'todo' list is too fragile. You make a mistake once in the code, and information gets lost forever. So I believe the solution is in ripping out the todo list completely, and making a simpler system, for example find things to do by looking around.

**Comment by TheCycoONE** [comment]
Partially solved by #1119 - it is now possible to build over the litter and remove it that way. I don't think it is possible from this issue to determine why that particular piece of litter got dropped from the task lists.

**Comment by lewri** [comment]
Was partially resolved by #1119 is this still an issue?

**Comment by Alberth289346** [comment]
Nothing was changed in the handyman task stuff, so yeah it is.
On the other hand, since it's old, and has no savegame before the task disappeared, I consider this issue unsolvable until we either kill the tasks list, or get a savegame with more information.

**Comment by lewri** [comment]
Closing this as a tidy-up as per Alberth's comments. I feel a new issue should be made with what specifically still needs fixing -- and a working savegame of the issue.
