### ISSUE TITLE
Characters walk through plants

### ISSUE THREAD

**Issue by daiscog** [CorsixTH/CorsixTH#393]
Whilst playing the first level of the campaign mode in version 0.40beta3 today (on 32-bit Linux) I noticed two occasions where a character walked through a tile containing a plant.  (The first was a handyman, the second a patient.)

Sorry, I don't have a save game as I only thought about reporting it way after it happened.

**Comment by tobylane** [comment]
No longer happens, everyone path finds around the solid objects (plants) and through the non-solid (radiators turned to be on one side of the tile rather than the front or back from the person's point of view).

**Comment by Lego3** [comment]
If it happens it is rare and needs more info to be reproducible.
