### ISSUE TITLE
Doctors will not enter a room whilst a handyman is in there watering a plant

### ISSUE THREAD

**Issue by daiscog** [CorsixTH/CorsixTH#394]
Whilst playing version 0.40beta3 (32-bit Linux) earlier, I noticed a doctor heading towards a GP's Office which had a queue and pausing outside the door with a queue icon above his head.  Inside the room a handyman was watering a plant.  Once the handyman left, the doctor went in.

I would not expect a handyman's presence in a room to prevent a doctor entering it; I don't think I've ever seen that happen in the original TH (with the possible exception of a handyman repairing a machine).

**Comment by Alberth289346** [comment]
@daiscog  do you have a savegame about this?

**Comment by mugmuggy** [comment]
#1566 should address this issue, with the onHumanoidEnter change to include attempting to advance the queue after the Handyman has entered.
