### ISSUE TITLE
[Graphic Error] Radiation shield partially visible through wall

### ISSUE THREAD

**Issue by honux** [CorsixTH/CorsixTH#403]
There is no secret on reproducing it, just create this object next to a wall.
![bug](https://cloud.githubusercontent.com/assets/2934877/5232554/b90b6f70-773a-11e4-9ba2-f0d5abe9fbd0.png)

Example save: http://www.filedropper.com/autosave12_1

**Comment by TheCycoONE** [comment]
The @Glimmer-Man screen is closely related to #463 The top screen looks different to me so far.

**Comment by lewri** [comment]
Merged into meta
