### ISSUE TITLE
Crash on mac sleep/wake cycle

### ISSUE THREAD

**Issue by JamesWP** [CorsixTH/CorsixTH#404]
This is a problem with Version: 0.30 Stable on OSX 10.10 on Mac Air

To reproduce:

1) while running on mac, close lid and open to trigger sleep
2) observe crash

[error dump](https://gist.github.com/JamesWP/3ffb965a00fd814284bd)

note this has happened with a few times but is not consistent :/
i will endeavour to reproduce again and update

**Comment by bobcanthelpyou** [comment]
@JamesWP @t0mtaylor Is that issue still a problem with the latest v0.50 beta release?

**Comment by colinjmatt** [comment]
This doesn't appear to be an issue on v0.62 and running MacOS 10.14.3.

I've put my Mac to sleep and woken it up ~10 times whilst playing without a single crash.

**Comment by TheCycoONE** [comment]
Thanks @colinjmatt
