### ISSUE TITLE
[BUG] Doctor will stay inside an operation theater without any action.

### ISSUE THREAD

**Issue by honux** [CorsixTH/CorsixTH#407]
The doctor on the image will not do any action, just will walk around.
No idea how to reproduce it.

![bug](https://cloud.githubusercontent.com/assets/2934877/5273251/263d0dae-7a6c-11e4-8292-76acbd2b2534.png)

Example save:
http://www.filedropper.com/autosave99sav

**Comment by lewri** [comment]
Closing this one as a tidy-up. I have tested the possible cause from Glimmer-Man and can't see this happen now.
I will assume it has been fixed by other changes over the years (even if not specifically targeting this one).
