### ISSUE TITLE
Warning: no event handler for buttonup

### ISSUE THREAD

**Issue by azayrahmad** [CorsixTH/CorsixTH#418]
I found this while playing in Chapter 4 campaign (the first one with Training Room). When I want to edit a Research Dept room, removing all objects using X button makes the button turn red but it wont turn back. And so when I click the other button like Check button, it behaves like that too. The title is the warning I get from console. I never found this in previous gameplay. Thank you

**Comment by Alberth289346** [comment]
This sounds like the "vomit in room getting edited" bug that was solved recently in #798.
Without stack trace or save game (from just before the occurrence), there is no way for us to decide if this is really the case. In its current state, this issue cannot be solved.

If you can manage to dig up more information about this problem, feel free to make a new issue and attach the information.
