### ISSUE TITLE
Screen blurs and deforms

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#421]
I am running version 0.30
I ran the OpenGL version, on my windows 8.1 64bit computer, and changed the resolution to 1920x1080 (what i'm currently running on windows) then the screen went all weird.
I checked the console and nothing was written except for the update checker.
This bug happpens on a fresh install of CorsixTH
I cannot reproduce it.

Attached is a screenshot of what happened
![screenshot 11](https://cloud.githubusercontent.com/assets/4595477/5350922/57883cd2-7f1a-11e4-8053-4a769fb1fa1c.png)

**Comment by Lego3** [comment]
Do we believe that we can close this now? I have tried a little going back and forth between resolutions and fullscreen (Windows, SDL2, uses directx). Will anyone try to run CorsixTH with OpenGL in Windows in the future?

**Comment by TheCycoONE** [comment]
Yes, I use to produce this frequently in OpenGL and haven't seen it in SDL2 (OpenGL)
