### ISSUE TITLE
Emergencies stopped - without reason (?)

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#422]
I tried to set emergencies at semi-random, with this values: days: 30, variance 20. I made it in level editor. I was expected a lot of emegencies and they came. But after time, emergecies stops and no one comes again.

I told myself "maybe semi-random is limited" and put it away...  and set back random mode.

After some time, I was edited world.lua, function "World:nextEmergency()", and set:

local mean = control[0].Mean or 30
local variance = control[0].Variance or 10

and looking for any reason, why emergencies could stop at random mode. I see no reason, but my skills are limited. So maybe there is a reason...

So I played, and after some time emergencies stops again. I found it weird.

I think about that and I have an idea - with this setting ( 30 - 10) is possible that next emergency could be set on same month as previous one ended. And I think this is the source of error. But I didn't find it in code... (not skilled with lua).

So I tried to set new values: days - 45, variance - 10 (always in next mont). In game I've returned back before last emergency ends (using autosaves). And it seems OK. Emergencies don't stop and appears according to this settings. 

Maybe I missed something in manual - sorry about that, but nevertheless I deside to report this finding.

**Comment by bobcanthelpyou** [comment]
@Glimmer-Man could you share your maps with different emergency values for testing?

**Comment by mugmuggy** [comment]
The Mean-'Variance' values where the issue stems from, is probably from negative values and thus emergencies will never start again once the start date is set back in time.

The documentation does refer to the 'variance' on a normal distribution - https://github.com/CorsixTH/CorsixTH/wiki/Custom-Levels#random-emergencies - but then alludes to the range relating to that figure as more than likely being with the 'variance' days of the mean.

However, the 'variance' is actually the standard deviation in the Box-Muller transform (math.n_random), thus in the original example, 99.7% would be in the range of 30 +- (3*20) resulting in those negative numbers. 68% would be in the range when interpretting the documentation.

Suggest we close this issue then for an update to that documentation instead.

**Comment by lewri** [comment]
Recommended action as above
