### ISSUE TITLE
DPI Scaling Issue - Cursor Not Moving

### ISSUE THREAD

**Issue by ArcticRavine** [CorsixTH/CorsixTH#430]
This is a very specific problem. I have a Surface Pro 2 and I use CorsixTH .40rc2 (Also an issue on older versions) DirectX. When I load up the game, I will notice that the cursor does not move with the Surface pen (which acts as a mouse), nor does it move with a proper mouse. This is because the game's settings force 'Disable display scaling on high DPI settings' on in its property settings (for me anyway). And I can not turn the setting off. If I turn the setting off and boot up the game, it'll reset the setting as if I didn't even turn it off. I think I know the DPI setting is the issue because it used to work somehow, and when I change my global content scaling settings on Windows from 150% to 100%, it will work, this requires me to reboot my computer every time if I want to play the game. I could also use the windowed option, which does work but it is difficult to play because of edge scrolling and the use of the pen.

Some Technical Stuff:
Windows 8.1 Pro
CorsixTH 0.40rc2

I can also give more information about this if needed.

Any help regarding this would be greatly appreciated.
Thank you.

**Comment by Dinnerbone** [comment]
I can reproduce this issue on my surface pro 3 using either DirectX or OpenGL rendering, but SDL rendering is fine. SDL doesn't seem to lag for me though, so I have no issues using it.

The sdl2 branch works too, but comes with a range of its [own rendering issues](http://i.imgur.com/RkBBV2X.jpg) that I shan't spam here (I can reproduce those on my main pc, though, so they're not relevant to this issue.)

**Comment by TheCycoONE** [comment]
Alright, will close this as soon as SDL2 is merged to master then.  Thanks.
