### ISSUE TITLE
A suggestion: edge scrolling in windowed mode

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#431]
I found out that if you just make 2 simple modifications as shown below, the game screen can scroll in windowed mode very naturally (scroll according to the mouse cursor's velocity at the moment when the mouse leaves the window) and it does not affect fullscreen mode at all:
1) change the GameUI:onWindowActive(gain) function, replace the disable-scroll line with "self.tick_scroll_amount_mouse = {x = self.dx, y = self.dy}"
2) add 2 lines "self.dx = dx" and "self.dy = dy" in GameUI:onMouseMove(x, y, dx, dy) function

The resultant file is as shown below: (change starting from line 412 of game_ui.lua)
--! Called when the mouse enters or leaves the game window.
function GameUI:onWindowActive(gain)
  if gain == 0 then
    self.tick_scroll_amount_mouse = {x = self.dx, y = self.dy}
  end
end

-- TODO: try to remove duplication with UI:onMouseMove
function GameUI:onMouseMove(x, y, dx, dy)
  local repaint = UpdateCursorPosition(self.app.video, x, y)
  if self.app.moviePlayer.playing then
    return false
  end

  self.cursor_x = x
  self.cursor_y = y
  self.dx = dx
  self.dy = dy
  if self:onCursorWorldPositionChange() or self.simulated_cursor then

**Comment by TheCycoONE** [comment]
Closing this in favour of #723 which suggests locking the mouse in the window (like dosbox, dota2, and other window mode games.)
