### ISSUE TITLE
Value "Expected patients" is not subtracted.

### ISSUE THREAD

**Issue by Glimmer-Man** [CorsixTH/CorsixTH#444]
I have noticed, that patients prefers room far away instead the nearest one (with a doctor inside). I find it weird. So I find a strange thing - after clicking on room door, there is a value "expected", and it's not zero. 

So I removed all reception desks and hold on untill all patients are out. So I have 0 patients in hospital, but that value (expected) is not 0.

Here is screen:
![screenshot7](https://cloud.githubusercontent.com/assets/9609391/5526129/81f0dc28-89f0-11e4-9ce2-ae8fa4e34db8.jpg)

So, trere must be a situation when patient is not substracted.

I counted all this numbers from all psychiaty rooms, and it's 36. That is very high number for me to thing, that reason is dead patient or angry leaving. This situation is in this case of psychiatry patients very rare.

So I thing that is a connection between #127 fix. Patient is now in queue - it's repaired, but maybe that number is not corrected. I haven't notice this bug before repairing #127, but I'm not sure.

I'll try to remove all affected rooms and buil them again. Maybe it was inherited from previos version save.

I will watching this...

**Comment by Glimmer-Man** [comment]
New clue: I think it's happening when there are lot of patients waiting for all GP's Office (for example) and walking from one room to another trying to reach better position in queue.

**Comment by mugmuggy** [comment]
Enroute to queue changes (#1568) counts patients hopefully correctly now
