### ISSUE TITLE
Automated Error Reporting Email System

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#445]
I would be willing to work on this as my priority task this week if this idea is accepted.

When a CorsixTH player experiences a Lua error they may not find time to report it, so CorsixTH could ask them if they want it to report the problem for them by sending an email to an error reporting email address containing:
- The CorsixTH version.
- The stack trace.
- One or more autosaves from before the error occurred.
- Optionally a message from the player describing what happened and what they were doing before the error occured.
- The player's operating system.

This email address's server could have email sorting rules which could compare the stack traces in received emails to group up emails which have the same error by putting them in a folder for their error & CorsixTH version.

CorsixTH developers could then open Github issues for errors reported with this email address.

**Comment by J-Shep** [comment]
I'm now going to include support for the source code to report its errors by calling this report email sending Lua code.

**Comment by J-Shep** [comment]
I will probably submit a pull request for this issue in a few days time, error replays probably won't be included because I think I will need to spend at least one more week working on making them work.

**Comment by J-Shep** [comment]
I'm nearly ready to submit a pull request.

**Comment by J-Shep** [comment]
I think I will be able to finish working on this issue this weekend.

**Comment by J-Shep** [comment]
This should be finished soon.

The latest error report dialog:
![latestdialog](https://cloud.githubusercontent.com/assets/6353342/6333395/9487211a-bb84-11e4-9698-fafc8c2bb268.png)

A error report message for an in game error:
```
****  In Game Error:    ****
Version: Trunk
OS: Microsoft Windows [Version 6.3.9600]
World previously recovered from error?: false
World Date: 8/1/1:12 (D/M/Y:H)
Map: TOXICITY
Tick Entity: 3

[The Error]:
The Error

Occurred In keydown handler: 
Trace L1
 Trace L2
 Trace L3

[Steps To Reproduce?]:
1) aaa
2) bbb
3) ccc

[Game Configuration]:
fullscreen = false
allow_user_actions_while_paused = false
check_for_updates = true
play_announcements = true
sound_volume = 0.5
enable_avg_contents = false
alien_dna_only_by_emergency = true
language = english
grant_wage_increase = false
alien_dna_must_stand = true
movies = true
theme_hospital_install = C:\GOG Games\Theme Hospital
scroll_speed = 2
free_build_mode = false
music_volume = 0.5
twentyfour_hour_clock = true
height = 600
prevent_edge_scrolling = false
alien_dna_can_knock_on_doors = false
adviser_disabled = false
audio_buffer_size = 2048
player_name = j_she_000
zoom_speed = 80
warmth_colors_display_default = 1
track_fps = false
disable_fractured_bones_females = true
play_intro = true
audio = false
audio_frequency = 22050
volume_opens_casebook = false
play_sounds = true
announcement_volume = 0.5
width = 800
scrolling_momentum = 0.8
debug = true
play_music = true
audio_channels = 2
use_new_graphics = false
```

I've also added 2 new debug menu commands:
* Pause Game After Date
* Center View On Entity (Given its ID)

**Comment by J-Shep** [comment]
Here's my repository branch for my work on this enhancement:
https://github.com/J-Shep/CorsixTH/tree/autogenerated_lua_error_email_reports

**Comment by sadger** [comment]
Hi @J-Shep  looks good! Does this come up automatically when an error is detected or does the user have to click a button to  "send  error report" bring this up? The later approach would be better I think based on how much corsix crashes.

**Comment by sadger** [comment]
Also you have a typo. It should be "if **you're** not going to report this yourself"

**Comment by J-Shep** [comment]
Hi @sadger ,

>> Does this come up automatically when an error is detected or does the user have to click a button to "send error report" bring this up? The later approach would be better I think based on how much corsix crashes.

It comes up automatically when an error is detected. But the later approach you've mentioned sounds like it would be worth including as a drop down menu option for when a player experiences a bug which doesn't throw a Lua error and doesn't crash the game, like an unexpected behavior bug.

I personally I think this error report dialog should be shown automatically when an error occurs so that a player will be more likely to use it when an error occurs.

>> It should be "if you're not going to report this yourself"

Where I come from in England "your" is a valid contraction of "you're" which everyone uses and I always see "your" being used on the internet instead of "you're".

**Comment by TheCycoONE** [comment]
@J-Shep that last statement about "your" is just wrong.  http://www.oxforddictionaries.com/definition/english/your explicitly talks about the difference between your and you're - and @sadger is from England too.

**Comment by J-Shep** [comment]
@TheCycoONE I've now deleted that statement because I'm embarrassed I stated it.

**Comment by sadger** [comment]
I was thinking it should work much like Windows reporting. You get a small popup with 2 buttons 1) Ignore 2) Report Error then when you  select the second option you get your nice error reporting dialog. That way it's not too intrusive.

**Comment by J-Shep** [comment]
>> I was thinking it should work much like Windows reporting. You get a small popup with 2 buttons 1) Ignore 2) Report Error then when you select the second option you get your nice error reporting dialog. That way it's not too intrusive.

@sadger Thanks for this suggestion: personally I don't think having a simple, small and unobtrusive  "ignore or report" dialog appear before a bigger "send report" form dialog would be worthwhile because unless the player is a developer testing their code then they won't want and shouldn't ignore the error which would have crashed their game and, with the current error recovery attempt code, probably won't be recoverable. 

@sadger If there was no need to ask the player to specify error reproducing steps then I could make a error report dialog like you've suggested with no text boxes (a prompt could appear to ask them for contact details when they've not provided this info before). However my code for error reproducing replay files is a long way from being usable but when this code does work I will create an error report dialog like you've suggested to replace the big intrusive form dialog I'm going to commit first. I will give it a save button though in addition to the ignore and send buttons because ideally a player should save the report and then attach it to a Github issue instead of telling CorsixTH to email the report to devs.

I'm sorry I've still not finished this important task: I've not spent much time doing CorsixTH programming in the last 5 days but my branch for this enhancement is almost ready to be pushed.

**Comment by J-Shep** [comment]
>> @sadger If there was no need to ask the player to specify error reproducing steps then I could make a error report dialog like you've suggested with no text boxes (a prompt could appear to ask them for contact details when they've not provided this info before). However my code for error reproducing replay files is a long way from being usable but when this code does work I will create an error report dialog like you've suggested to replace the big intrusive form dialog I'm going to commit first.

There will actually have to be two separate dialogs: 

1) A small & simple dialog like @sadger suggested for reporting game crashing errors: which would have no text boxes. This dialog will be automatically displayed when Lua errors occur and when source code error checks and catch statements detect that a source code error has occurred which should be reported.
2) A bigger dialog with a text box for reporting unexpected behavior bugs which won't give developers a stack trace to work with. A player would use a drop down menu command to display this dialog.

**Comment by sadger** [comment]
I think that sounds like a good solution @J-Shep. I was just making a suggestion, whatever you think would work best, the easier the player can report and error the better I reckon!

**Comment by J-Shep** [comment]
I might submit a pull request tomorrow.

**Comment by J-Shep** [comment]
I will try to finish this my work on this issue weekend.

**Comment by J-Shep** [comment]
I've had an idea I could implement in a commit for this issue's pull request: beta testers could give CorsixTH permission to use a game state copy which would only be updated after a successful execution of the other game state with App:run(). 

So when an error occurs the copy could be saved and attached to an error report email along with the dispatch event which caused the error so that a developer could then repeat the error by simply loading this game state and then having app:run() respond to the dispatch event.

**Comment by J-Shep** [comment]
I've finished implementing the code for generating crash error reports and emailing them with useful attached files. 

I'm now going to work on one last commit which will use a separate report dialog to report problems which don't crash games like unexpected behavior bugs. A "Report problem" drop down menu command will display this dialog. I will probably finished this tomorrow.

**Comment by J-Shep** [comment]
Here's the dialog for the drop down menu "Report Problem" command:
![reportproblem](https://cloud.githubusercontent.com/assets/6353342/6779805/b4ca6c3c-d157-11e4-9957-9357cb82986d.png)

**Comment by TheCycoONE** [comment]
Have you looked at the github api?  It would certainly be feasible to send the issue to github on the user's behalf.

**Comment by sadger** [comment]
Looks good. +1 on the github integration if you can work it in. Not so sure on the severity option as users won't really know how severe their crash is.  Maybe just behind the scenes say if it's a crash or something else?

**Comment by Grimdoc** [comment]
Great job!

**Comment by J-Shep** [comment]
>> Have you looked at the github api? It would certainly be feasible to send the issue to github on the user's behalf.

@TheCycoONE I've not, now that I know it supports programs opening Github issues for their errors I will make CorsixTH open issues for Lua crash errors. 

However I don't think errors which can't provide stack traces should be posted to Github because making CorsixTH check for an existing issue wouldn't simply involve making it look for an identical stack trace in an open issue's comment. Unless the "Report Problem" dialog asks players to check themselves before clicking "Send To Github" but some players would click this sometimes without checking.

>> Not so sure on the severity option as users won't really know how severe their crash is. Maybe just behind the scenes say if it's a crash or something else?

@sadger This dialog isn't meant to be used for reporting crash errors because there's the new "An error has occurred" dialog I've made for this purpose which automatically appears when Lua crashes occur. 

Maybe this "Report Problem" dialog shouldn't have a severity question (to allow the checking of received emails to be prioritized as they could be auto sorted into inbox folders for the severity of their problem) which a player may not accurately answer but instead should  simply ask "Did this error crash your game?" for when this dialog is used to report source code game crashing errors which can't display the "An error has occurred" dialog and auto report their errors.

**Comment by TheCycoONE** [comment]
Sounds good @J-Shep - definitely great work.

I kinda don't think the user should be asked to choose how they want to report the error (email or github) we should make the choice for them based on what we know.  My feeling is that they shouldn't be expected to learn our processes just because their game crashed, and the choice might intimidate people into not filing at all.  I'm not sure if that's reasonable or not, so I'm just putting the idea out there, not making a requested change.

**Comment by J-Shep** [comment]
>> I kinda don't think the user should be asked to choose how they want to report the error (email or github) we should make the choice for them based on what we know. My feeling is that they shouldn't be expected to learn our processes just because their game crashed, and the choice might intimidate people into not filing at all. I'm not sure if that's reasonable or not, so I'm just putting the idea out there, not making a requested change.

@TheCycoONE Thanks for posting your idea. If players had no choice to simply click a send button to make CorsixTH report their problem on their behalf, disavowing them from it, then I think a lot of them wouldn't report problems with Github because they wouldn't have the time/inclination/would be too intimidated to want to get involved in our processes by registering at Github, opening an issue and then chatting with developers about the problem they experienced.

For crash errors I now won't ask players to consider opening Github issues since this can be done without their involvement. When a new issue is opened for a crash error a player's game has reported I will make it tell them the address of the opened issue so that they can get involved in their problem's discussion if they are willing to register and chat with developers.

**Comment by J-Shep** [comment]
My commit for the "Report Error" dialog is finished now so I just need to modify my commit for the "Error Occurred" dialog to make it use an HTTPS Github connection for opening crash issues.

I'm currently stuck because I need to compile Luasec for making Luasocket support HTTPS but I'm getting "undeclared identifier" errors and I don't know what I'm doing wrong:

```
1>------ Build started: Project: luasec, Configuration: Debug Win32 ------
1>  ssl.c
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(113): error C2065: 'WAITFD_R' : undeclared identifier
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(118): error C2065: 'WAITFD_W' : undeclared identifier
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(157): error C2065: 'WAITFD_R' : undeclared identifier
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(162): error C2065: 'WAITFD_W' : undeclared identifier
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(204): error C2065: 'WAITFD_R' : undeclared identifier
1>c:\users\j_she_000\desktop\luasec-luasec-0.5\src\ssl.c(209): error C2065: 'WAITFD_W' : undeclared identifier
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
These variables are defined in header files located in .../luasec-luasec-0.5/src/luasocket/

I'm using a compatible version of OpenSSL (1.0.1e) and I've given the Visual Studio project which came with Luasec all the paths it requires for its dependencies.

**Comment by J-Shep** [comment]
I will try using the release configuration.

**Comment by J-Shep** [comment]
I've now successfully compiled Luasec so I will now get my Github issue opening code done asap.

**Comment by J-Shep** [comment]
Having not done any CorsixTH programming for a month I now have my PC setup for Lua 5.3 and I can compile CorsixTH.exe and run it without the graphics problem I mentioned in the [developer forum](https://groups.google.com/forum/#!forum/corsix-th-dev).

However I've not yet been able to setup Luasec which would be required for making CorsixTH use the Github HTTPS API for opening error tickets and with its latest release being a year old, the Visual C++ project which comes with it is setup for Lua 5.2: I don't know how to reconfigure it for Lua 5.3. This libraries LuaRocks rock is also currently [unusable](https://github.com/brunoos/luasec/pull/26) for Windows users.

@TheCycoONE @Lego3 Do you want me to wait until I can submit a pull request for a complete commit with Github support or would your prefer to get a commit with email error reporting functionality asap? I would prefer to do the latter so that there could be a patch released for #588 before asap which could also introduce this error reporting functionality.

**Comment by TheCycoONE** [comment]
Just email reporting is fine.

**Comment by TheCycoONE** [comment]
It may be easier to implement the github API connection in the C++ code since luasec appears to be quite a problem. There are definitely mature portable libraries for C/C++ for sending https traffic. (libcurl for instance).

**Comment by J-Shep** [comment]
>> It may be easier to implement the github API connection in the C++ code since luasec appears to be quite a problem. There are definitely mature portable libraries for C/C++ for sending https traffic. (libcurl for instance).

I think Luasec should be used so that the Lua code I've made for email reports can just be modified to include code for opening error tickets after checking that no tickets are already open for an error.I will just use Lua 5.2 with Luasec.

**Comment by TheCycoONE** [comment]
To be frank it wouldn't make a difference. My suggestion was to only implement the network interface to github in C++, then call that from lua with all the ticket information you wanted to submit.

**Comment by J-Shep** [comment]
@TheCycoONE Thanks for your suggestion. I will use libcurl if the most recent Luasec release (released in January 2014) isn't compatible with Lua 5.3 and there won't be a new release compatible with it soon.

**Comment by J-Shep** [comment]
Hi, 

Having not contributed to the development of this game for a long time I want to start contributing again by finishing my unfinished tasks I assigned myself to and then didn't unassign myself from during my contribution hiatus (I guess I should have considering how long its been).

Has anyone taken over this task? I've not compiled the latest master version yet so I don't what features have been added to this game since I last played it a long time ago.

**Comment by Alberth289346** [comment]
hi again, and welcome back

game hasn't moved much, the cyco one is working on pushing the price impact patch into shape for inclusion, I mostly do code changes while pondering about actions and killing dispatch queues. I changed the lua code style of the project, you may want to read it again.

**Comment by J-Shep** [comment]
Thanks for welcoming me back @Alberth289346 , I will read about the latest Lua code style.

**Comment by J-Shep** [comment]
I'm now going to actually start contributing to this game's development again by finishing this important task asap and then the other tasks I assigned myself to many months ago.

**Comment by J-Shep** [comment]
My pull request will include a commit for making new Window component adding functions and another commit for implementing Window layout managers to remove the need for components to be placed with absolute screen coordinates which has made creating the error report form dialog much easier.

However my new functions for adding components to windows require lots of optional parameters, for example:
```
function Window:addTextBox(x, y, width, height, is_multi_line, tooltip, col_textbox, col_highlight, col_shadow, font, allowed_input, confirm_callback, abort_callback)
``` 

So would it be acceptable for me to request the optional parameters for a function like this with so many of them be provided in an extra parameters table like so:
```
--!param width  (integer)
--!param height (integer)
--!param optional_params (table)
--!param optional_paramas-x (integer) Not required if a Layout Manager will provide it.
--!param optional_paramas-y (integer) Not required if a Layout Manager will provide it.
--!param optional_paramas-is_multi_line (integer) Default: false
--!param optional_paramas-tooltip (string)
--!param optional_params-col_textbox (table) {red = ?, green = ?, blue = ?}
--!param optional_params-col_highlight(table) {red = ?, green = ?, blue = ?}
--! etc ...
function Window:addTextBox(width, height, optional_params) 
```
Then they could be provided in any order and no nil parameters would have to be included.

Another question I have is about the code length convention: is a function call with many parameters allowed to be much longer than 80 characters or should its parameters be instead listed vertically instead of horizontally?

**Comment by Alberth289346** [comment]
I think this is the better option indeed. I would rename "optional_params" to just params, and describe its contents as description of "params", rather than faking a lot of parameters that don't exist as real argument. Ldocgen will get highly confused by this, and possibly even crash on it.

Secondly, please split this away from the reporting system. It's a separate feature, that deserves its own PR.

**Comment by J-Shep** [comment]
@Alberth289346 Thanks for your helpful reply. I will make the changes you've suggested and split this feature away from the error reporting system.

**Comment by J-Shep** [comment]
Status update: I'm currently finalising my commits for Layout Managers and for the new Window methods I've created to support the use of Layout Managers and also to allow components to be added to windows with single simple function calls instead of a Window's creating having to issue a sequence of calls in order to create a single: Button, Label, Drop Down Menu, Textbox or Toggle Button for example:
```
-- Textbox for entering code
self.textbox = self:addBevelPanel(20, 20, 280, 140, col_textbox, col_highlight, col_shadow)
    :setLabel("", app.gfx:loadBuiltinFont(), "left"):setTooltip(_S.tooltip.lua_console.textbox):setAutoClip(true)
    :makeTextbox():allowedInput("all"):setText({""})

-- Can now be made as follows:

-- Textbox for entering code
self.textbox = self:addTextBox(280, 40, {x = 20, y =20})

-- Or with LayoutManager providing the screen coordinates for its position:

-- Textbox for entering code
self.textbox = self:addTextBox(280, 40)
```

My Report_Problem Window is up to date with the latest LayoutManager and Window code. So since the Report_Error window will reuse most of this window's code, most of the GUI code which will be required by my "error report system" pull request has been done. 

Leaving me with the coding tasks of finalising my error report generating code and creating new code for making CorsixTH report errors by opening Github issues instead of reporting them via email as I originally intended.

I will submit a separate pull request for implementing Layout Managers and for my Window changes  either before or after this weekend when I won't be able to do any programming because I will be away from home on a trip without a computer.

**Comment by J-Shep** [comment]
Its been more than a week since I've done any programming for CorsixTH but I will resume my work on this enhancement now.

**Comment by J-Shep** [comment]
I think I will be ready to submit a pull request for my implementation of layout managers by Monday.

I made this window today to test and demonstrate Window support for having multiple layout managers working together to group window components in separate bevel panels with each layout manager having a bevel background enabled for its area:

![image](https://cloud.githubusercontent.com/assets/6353342/15410243/a09b821c-1e10-11e6-82ca-630b3b1db819.png)

```
function UIMultiplayerLobby:UIMultiplayerLobby(ui)
  self:UIResizable(ui, 640, 480, col_bg)
  self.esc_closes = true
  self.on_top = true
  self:setDefaultPosition(0.5, 0.25)

  -- Add window components:
  local main = self:setLayoutManager("main", TabularLayout(nil, self.width, self.height, {5, 5, 5}, 2, 5, 5))
  self:addButton("Join", 50, 25)
  self:addButton("Host", 50, 25)

  local layout = TabularLayout(main, main.space_w, 275, {6,5}, 2, 5, 5)
  self:setLayoutManager("games_panel", 
                        layout,
                        "bevel",
                        {red = 134, green = 126, blue = 178})

  self:addLabel({"Joe's Game", "Dave's Game"}, "64%", "98%", {font = "Font04V", bg_c = {red = 0, green = 0, blue = 0}})
  self:addLabel({"Paul", "Mike", "Emma", "Steve"}, "34%", "98%", {bg_c = {red = 0, green = 0, blue = 0}})

  main:skipRow()
  layout = TabularLayout(main, main.space_w, 160 , {5,4,5,4}, 1, 0, 5)
  self:setLayoutManager("chat_panel",
                        layout,
                        "bevel",
                        {red = 134, green = 126, blue = 178})
  self:addTextBox("100%", 25)
  self:addLabel({"Steve: Does anyone want to play the original TH multiplayer mode with me?", "Emma: I do!"}, "100%", 120, {bg_c = {red = 0, green = 0, blue = 0}})
end
```

**Comment by MarkL1961** [comment]
:+1: Looking good

**Comment by J-Shep** [comment]
@TheCycoONE I could submit a pull request for a email crash reporting system for 0.60 within the next few days which would just use the existing Window code for the error report dialog, if this enhancement would be allowed with this release being in beta. 

I know I would have to be frugal with the amount of new code I would add to 0.60 and I would keep it as simple as possible.

**Comment by J-Shep** [comment]
I've almost finished making error report dialog for 0.60 with the existing Window code I just need to correct some spacing inoncistancies:

![image](https://cloud.githubusercontent.com/assets/6353342/15447972/93d64e78-1f4a-11e6-9c95-a20f70c8b5fb.png)

Having already implemented Lua code for generating error reports and sending  error report emails a long time ago when I first started working on this enhancement before my long hiatus, I think I could probably have a barebones email error reporting system implemented by Monday for 0.60.

If 0.60 had an auto error reporting system it would help us strive to make 0.70 error free.

**Comment by Alberth289346** [comment]
I don't believe it is wise to add new features at the last minute, especially such a big and complicated feature with sending reports over the internet. So much stuff that can go wrong and has never been tested.

Catching the error in the program and a window for the user is just the user front end. I don't know where you are sending the reports, but something needs to capture that traffic, and process incoming stuff, like duplicate detection, and perhaps spam or virus filtering?

While I am sure the new feature won't add many new errors, I current still fail to understand how it makes it significantly better. Who is going to deal with all the new issues? It's not like we are low on open issues that we can't seem to get rid of. Do we need even more?

Sorry to sound so negative, but I'd really like to understand what this is going to solve.

**Comment by TheCycoONE** [comment]
There are no new features going in 0.60 at this time. This pr will be reviewed for 0.70.

Thanks for all the work J-Shep

**Comment by J-Shep** [comment]
>> There are no new features going in 0.60 at this time. This pr will be reviewed for 0.70.

No problem your in charge and I should have waited for you to accept my idea before spending any of my free time working on a new error report window which wouldn't have required my new code for Windows. 

>> I don't believe it is wise to add new features at the last minute, especially such a big and complicated feature with sending reports over the internet.

Well this feature's code would have been independent from the code which is involved in the running of a CorsixTH game so its code would have been rarely used and any problems with it would have therefore rarely occurred and had no affect on the running of a game. After all this feature would only have been activated in 0.60 after a Lua error with the game running code or a window had occurred and crashed a player's game.

>> While I am sure the new feature won't add many new errors, I current still fail to understand how it makes it significantly better. Who is going to deal with all the new issues? It's not like we are low on open issues that we can't seem to get rid of. Do we need even more?

This code would have only reported game crashing errors, so issues it reports would be distinct from most open issues by being critical issues we as developers want to make sure we find out about and do so asap, no matter how rare they are and how many players (a small minority I bet) would bother to register at Github & open new issues to report them.

 >> I don't know where you are sending the reports, but something needs to capture that traffic, and process incoming stuff, like duplicate detection, and perhaps spam or virus filtering?

As I mentioned in my recent post, my code for 0.60 would have simply sent email error reports to an email address and this code already works & can send error report emails to an email server program I run on my PC. Since only CorsixTH crashing Lua errors would have been reported their unique stack traces would have been included in the emails so email filters could have checked received emails for identical stack traces deleting emails for already reported errors.

> Sorry to sound so negative, but I'd really like to understand what this is going to solve.

Imagine this feature coupled with an automatic Lua code patching feature: we could find out about a game crashing Lua error as soon as it happened for the first time on a player's computer, who was willing & had the time to at least just click "Send" in the error report dialog (including players who can't speak English and therefore wouldn't otherwise report crash errors). Then those of us who would be willing to be on the email forwarding list for the error reports email address would be notified and one of us with the time would open a critical priority Github issue for the crash error. Finally with the auto Lua code patching feature, as soon as one of us had found a fix for the error it could be released to players in a crash fix patch which would be auto downloaded and applied to a player's game scripts when they next ran CorsixTH with an internet connection. 

So with these enhancements working together all players could receive a fix for a game crashing error potentially within less than a week of it being first experienced by a player instead of having to wait many months for the fix to be included in a new CorisxTH release, when it may only require a few statements in a single script to be changed. Players would therefore be much less likely to experience these game crashing errors since they could be quickly fixed.

So I want to finish implementing this feature for 0.70 and then I want to implement automatic Lua script patching because I will enjoy working on these enhancements & I personally think they are amongst the most important enhancement this game needs since they would help so much with improving its reliability.

**Comment by lewri** [comment]
Closing for tidy-up. Happy to reopen in the future if we want to work on this again.
