### ISSUE TITLE
Mood icons appear above the wrong place when using objects

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#446]
_From [chris_lo...@hotmail.com](https://code.google.com/u/101094553588000836480/) on December 07, 2009 19:14:49_

What steps will reproduce the problem? 1. Member of staff has a mood icon when going to sit in the staff room
(most likley tierd mood)
2. Icon jumps to the hover over the right seat instead of remaining above
the member of staff (who is sat on the left) What version of the product are you using? On what operating system? r162

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=65_

**Comment by lewri** [comment]
Some investigation on this leads me to believe mood icons is mostly fixed. Only time we still get a misalignment seems to be on using doors.
For the sake of the original issue being resolved (and it's so old) I'll recreate new issues for existing parts.

**Comment by lewri** [comment]
Turns out this was not fixed. But keeping closed in favour of #2794
