### ISSUE TITLE
Refactor the progress dialog lua file

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#449]
_From [e.sara...@gmail.com](https://code.google.com/u/118272899384684447472/) on June 28, 2010 19:13:02_

What steps will reproduce the problem? 1. Borrowed 10 000$
2. Repaid it
3. Win Criteria Never rising anymore What is the expected output? What do you see instead? Money requirement stays at nothing even though I've clearly accomplished it.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?

SVN R917 - http://th.corsix.org/corsix-th-r917-win32.zip What operating system / compile settings are you using? Windows 7 Professional 64 bits English

What level was this on (e.g. "Demo level", "Full game level 12")?

Full Game - Level 2 Please provide any additional information below.

**Attachment:** [Capture.PNG](http://code.google.com/p/corsix-th/issues/detail?id=344)
![image](https://user-images.githubusercontent.com/20030128/91656642-4f13d700-eab2-11ea-82c9-3e157efc2f53.png)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=344_

**Comment by lewri** [comment]
I can't replicate the original issue here anymore in 0.64. Do we still require this one open?

**Comment by TheCycoONE** [comment]
Ancient issue, and it's not clear what work is remaining - just close it.
