### ISSUE TITLE
Disappearing wall when buying a new plot of land

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#451]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on July 09, 2010 15:27:02_

What steps will reproduce the problem? 1.start game
2.build rooms
3.buy another plot of land What is the expected output? What do you see instead? At the moment you can't build across what will become corridors if/when you buy the adjacent plot.   You can build next to these plots if you are not blocking off an area of the hospital. To a certain extent the same could happen in the original, but what I did find odd was building against a plot that I did not own for a wall of a clinic to disappear when I did buy the plot. see screen shot

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r942 What operating system / compile settings are you using? win XP
What level was this on (e.g. "Demo level", "Full game level 12")?
full version - L9 Please provide any additional information below. I think that in the original you could block off areas and when you did you could not place an object in the blocked off space.  You could not block off an area if someone was walking in the area. This was usefull at the start of a game to maximise the area you could build in.  Once you purchased another plot you would have to move or delete the objects doing the blocking before you could add objects to the new space.

**Attachment:** [screen.bmp](http://code.google.com/p/corsix-th/issues/detail?id=384)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=384_

**Comment by TheCycoONE** [comment]
Confirmed that this bug still affects 0.40 from #681

**Comment by TheCycoONE** [comment]
As seen in #1011 this can lead to crashes. Also confirmed in 0.50.

**Comment by Lego3** [comment]
Time to have a look at this.

**Comment by Lego3** [comment]
We need #1018 as well to fix this completely.

**Comment by Lego3** [comment]
I put the test map I used here: https://www.dropbox.com/sh/1urn1hfvq76e61b/AAAPVCfWrz63QQlyV2jVfsgGa?dl=0
#1015 fixes issues when you build rooms next to expansion walls, while #1018 fixes issues when you later on buy the expansion.

**Comment by TheCycoONE** [comment]
It was closed automatically by merging the pull request because it had fix #451 in the message.

**Comment by Lego3** [comment]
Yes, I know. Would have looked strange to just open it though. :-P

**Comment by TheCycoONE** [comment]
#1018 was merged.
