### ISSUE TITLE
The sound stops working and will be replaced by an intermittent tone (beep)

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#452]
_From [Florent....@mac.com](https://code.google.com/u/103532768767381548432/) on August 22, 2010 11:51:54_

What steps will reproduce the problem? 1. Play a moment (~20mins/30mins) What is the expected output? What do you see instead? The game works correctly, but the sounds (and music) was replaced by an intermittent tone like a beep

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Beta 3 What operating system / compile settings are you using? Binary for OS X

What level was this on (e.g. "Demo level", "Full game level 12")?
At all levels, noticed at the first and second with different versions of TH, (US and FR)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=428_

**Comment by Lego3** [comment]
Since nobody has added any info to this issue, and we have moved to SDL (mixer) 2 I'll close it. If someone experiences this again they will surely create a new jira.
