### ISSUE TITLE
Hire a researcher should update existing faxes with autopsy option

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#453]
_From [roujin.mw](https://code.google.com/u/roujin.mw/) on November 05, 2010 08:24:57_

Currently it is decided at creation time of Messages if the autopsy option is available or not (depending on if a research room was built).

However with the possibility now to hold back a decision until later (with the new fax system in r999 ), it should be made possible to build a research room and then open the fax again and choose autopsy. This is currently not possible.

Care should be taken that even opened faxes are updated (someone with a high resolution could manage to build a research room while keeping the fax opened).

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=480_

**Comment by Alberth289346** [comment]
In short, the options displayed by the fax should be computed at the moment it is opened rather than being generated beforehand. That way, new options to deal with the situation will also be mentioned in the fax.

**Comment by MarkL1961** [comment]
What if you were to minimise the fax and they say build the research department?
Would the fax update to show the option of send to research?

**Comment by Alberth289346** [comment]
That's how I read the enhancement indeed. Do you read something else?

For that reason, I believe that at the moment the fax gets opened for display, it should decide what to show. If you minimize the fax, change the hospital, and then open it again (re-computing what the fax show display), it will show the correct choices.

**Comment by MarkL1961** [comment]
I wanted to be sure as it did not read that way to me in the previous comment.  If re-opening does a recalculate that is indeed what is needed

**Comment by mugmuggy** [comment]
Digging this issue out from the grave.
This [commit](https://github.com/CorsixTH/CorsixTH/commit/426dd039b32456142d3ea76992b9cf7d6dfdaa5c#diff-af0b4fc49dace13a57ed7623269991de) original tried to address the old Issue 480.

It has a logic bug that partialy accounts for the above. In TH, if the room is buildable (ie discovered) but doesn't exist in the hospital then you should have the option to send to research still if research exists, currently its disabled in this case.

In the original it has a bug, in that an unoccupied research room will allow patients to 'go there', but when you start, and remove the researcher (sack them), it will disable the button again.

The other issue is also with the content of the faxes. Emergency does it correctly:
https://github.com/CorsixTH/CorsixTH/blob/f16a51011a611c1a66ba91bea8fa640739905ccf/CorsixTH/Lua/hospital.lua#L1232-L1240

But the seek room doesn't, as the build callbacks exist only for a room build. The original would only 'open' a room for use when a suitable staff member was also in the room. CorsixTH doesn't really allow that. And its complicated as the room build call back gets called, but then you also sort of need a staff notification as well to successfully implement the seek actions to populate the fax correctly.

The build callbacks call updateMessage to enable the button, but not for the notification of the staff member.

**Comment by lewri** [comment]
May be resolved by PR #1484

**Comment by mugmuggy** [comment]
Yep
