### ISSUE TITLE
MapEdit: Buildable flag is not removed in all cases

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#454]
_From [roujin.mw](https://code.google.com/u/roujin.mw/) on November 07, 2010 17:02:14_

What steps will reproduce the problem? 1. New map
2. Place square of walkable ground
3. Place walls surrounding them (all inner tiles are now buildable)
4. Delete the building again by dragging grass over the whole area. What is the expected output? What do you see instead? Expected: all tiles are non-buildable again
Observed: ring of buildable tiles Please use labels and text to provide additional information. observed in r1014

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=488_

**Comment by Lego3** [comment]
As the old map editor has been deprecated I'll close this issue.

**Comment by TheCycoONE** [comment]
The new and old map editor share a certain amount of code, so it's possible this may transfer over.
