### ISSUE TITLE
MapEdit: Floor tile (stone plate) affected by wall transparency

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#455]
_From [roujin.mw](https://code.google.com/u/roujin.mw/) on November 07, 2010 17:09:38_

What steps will reproduce the problem? 1. Place the last floor tile in the list (stone plate without any cracks)
2. Toggle wall transparency What is the expected output? What do you see instead? Not only walls, but also the stone plate floor tile becomes transparent.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=489_

**Comment by tobylane** [comment]
This patch is inaccessible and was for the previous Map Editor. On the current Map Editor floors aren't affected by toggling wall transparency.
