### ISSUE TITLE
Exhausted staff members don't go to staff room - patch though causes another issue

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#458]
_From [jorrit...@gmail.com](https://code.google.com/u/115977478486224968984/) on December 23, 2010 15:46:15_

What steps will reproduce the problem? See screenshot. This has been happening since the addition of the new calls dispatcher. It seems to affect both doctors and nurses, and as far as I can tell it's random. It happens both when the room the staff member in has a queue and also when it doesn't.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1123 What operating system / compile settings are you using? Windows XP

What level was this on (e.g. "Demo level", "Full game level 12")?
Custom level

**Attachment:** [r1123-staff-exhausted.JPG](http://code.google.com/p/corsix-th/issues/detail?id=592)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=592_

**Comment by Alberth289346** [comment]
Lots of talk, and a few save games, but no patch outside the now dead google code.

Aside from that, afaik, getting overworked people is part of game play, I am not sure it should be fixed.

Closing this one, please open another one if the issue happens again.

**Comment by TheCycoONE** [comment]
There is a staff policy that should affect whether / when they go to the staff room. Haven't looked into whether it works.

**Comment by MarkL1961** [comment]
The issue was that odd staff members would stop in the room and not go for a rest, nothing to do with the policy.  With handymen I think they would just wander around getting more and more tired, but not go for a break.
I have no idea whether this still happen or not, but it was never all staff, just odd ones here and there.

**Comment by TheCycoONE** [comment]
I guess we can reopen if we see it again.
