### ISSUE TITLE
Wall dissapears in Mapeditor 

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#459]
_From [Lmkoning...@gmail.com](https://code.google.com/u/110204401679812303496/) on December 25, 2010 13:23:19_

What steps will reproduce the problem? When you occupy certain tiles (with plants or floor tiles) the wall next to the tile will dissapear. Using other tiles will not make the wall next to it dissapear (see picture 2 and 3 for example) Hopefully this can be fixed because now I cant place plants near the wall in my little greenzone park.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
corsix-th- r1127 -win32-ogl

What level was this on (e.g. "Demo level", "Full game level 12")?
Level independant/custom level Please provide any additional information below. -Attached screenshots

**Attachment:** [1.png 2.png 3.png](http://code.google.com/p/corsix-th/issues/detail?id=602)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=602_

**Comment by tobylane** [comment]
This doesn't happen in the new Map Editor.

**Comment by Alberth289346** [comment]
good enough for me
