### ISSUE TITLE
Room builder, view window graphical glitch

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#460]
_From [Grim...@gmail.com](https://code.google.com/u/118083579813208703807/) on January 06, 2011 09:59:49_

What steps will reproduce the problem? 1. Open the room builder
2. Look at all the "big" machines (example research dept)
3. You see that the "machine" is sticking outside the "view-window" What is the expected output? What do you see instead? I checked with original TH, and the machines seems better centered or maybe made smaller in the view window, since they aren't sticking out so much.
But it wasn't perfect in old TH either, just check the operating table (the lamp sticks out over the window at the top).

Just take research dept for example:
In old TH, the machine isn't sticking out of the view window at all, but in CorsixTH it does.
Look at the attached photo.
I couldn't provide a photo from old TH because the colors are too messed up to see anything.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Beta 5, r1176

**Attachment:** [Graphicissue.png](http://code.google.com/p/corsix-th/issues/detail?id=643)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=643_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Reproduced on v0.67. This issue affects Research Dept, Operating Theatre, Decontamination, X-ray, Ultrascan, Electrolysis Clinic, DNA Fixer, and Jelly Vat.
![2024-04-13 21_01_30-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/fd961b1a-15a2-4fe2-94e6-6c667f0857e7)
