### ISSUE TITLE
Patient Stuck

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#462]
_From [mrapsout...@gmail.com](https://code.google.com/u/108689480183180951876/) on January 25, 2011 16:27:44_

What steps will reproduce the problem? Not Sure see below

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Beta 4 What operating system / compile settings are you using? Win7

What level was this on (e.g. "Demo level", "Full game level 12")?
See attached Please provide any additional information below. This has happened to me before on different levels and with different rooms.

In this case look at the inflation clinic.

**Attachment:** [Alex.sav](http://code.google.com/p/corsix-th/issues/detail?id=702)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=702_

**Comment by mugmuggy** [comment]
Think we can put this one to bed, its quite old, the closest issues I could think of was the edit staff room type issue on some of the rooms fixed in 0.64.
