### ISSUE TITLE
Game crash when a room about to be entered is removed

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#466]
_From [sr.ribe...@gmail.com](https://code.google.com/u/118260187238810357641/) on March 29, 2011 17:18:56_

When there are patients on the way to use a toilet room (Toilets) and the player is completely removes it the game crashes and isn't able to recover from the error.

This has happened on levels three and four so far.

Best regards,

Version: Beta 6 (Linux 32-bit Debian package)
OS: Ubuntu 10.10

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=794_

**Comment by tobylane** [comment]
I can't replicate this with a nurse and pharmacy, doctor and x-ray, doctor and psychiatrist, or patient and toilets. This appears to be fixed for all rooms.
