### ISSUE TITLE
No music on Ubuntu

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#467]
_From [JoaoCMBa...@gmail.com](https://code.google.com/u/101776954707642261684/) on April 12, 2011 12:05:57_

1. Installing deb package beta 6 on Ubuntu Maverick 10.10 amd64 provoques sound issues.

From beta 5, in which sound worked perfectly, to beta 6, only sound effects work and there's no music, no announcements. Music is disabled

I just rolled back to beta 5 and music starts instantly playing when i open the game.

Here's terminal feedback on beta 6:

Consider replacing Lua with LuaJIT to improve performance. Note that there is not currently a 64 bit version of LuaJIT.there is no soundcard
could not load music file 'Sound/Midi/MEND.XMI

Perhaps some error in the amd64 deb package compilation? And if corrected how will it be announced so we can download the fixed version?

Regards.

P.S. This clone is great, thank you very much.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=826_

**Comment by Lego3** [comment]
I'll close this. Music plays fine on Ubuntu 14.04, and we currently don't distribute debian packages.
