### ISSUE TITLE
._ Files causing issues

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#468]
_From [catapult...@gmail.com](https://code.google.com/u/117944295485878544497/) on April 14, 2011 00:09:24_

What steps will reproduce the problem? Initialise file copy from Mac OS X What is the expected output? What do you see instead? Error message related to Music Folder

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? Beta 6

What operating system / compile settings are you using? OpenPandora

What level was this on (e.g. "Demo level", "Full game level 12")? N/A

Please ignore ._ files as it causes the game to stop playing music and crash when that song comes on.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=829_

**Comment by tobylane** [comment]
Can't recreate this, after confirming it is playing from a folder with the .DS_Store file.

Worth noting, and it is now in the wiki, that homebrew installs SDL2_mixer without smpeg by default, `brew install sdl2_mixer --with-smpeg2` is necessary for mp3 playback.
