### ISSUE TITLE
Missing fax when built room has no staff available

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#469]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on June 27, 2011 14:55:48_

What steps will reproduce the problem? 1. build op theatre 
2. be one or both surgeons short for it to be usable What is the expected output? What do you see instead? Dr diagnoses someone that needs surgery and sends them to the ward.
The casebook tells you that you can't treat this and tells you why, the same check should occur at diagnosis and the Dr should either send them home or you ought to get a fax so that you can decide.

I think that the same can happen with the pharmacy.  You build it, forget to employ a nurse and yet patients are still sent there.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=906_

**Comment by mugmuggy** [comment]
Yep
