### ISSUE TITLE
Mixed languages in the dynamic info when changing languages before loading a save

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#471]
_From [Grim...@gmail.com](https://code.google.com/u/118083579813208703807/) on July 16, 2011 13:59:36_

What steps will reproduce the problem? 1. Start the game in norwegian language
2. Change to english
3. Change again back to norwegian

Wait until the announcer tells you the fracture clinic has been upgraded. Then you get a message looking like the one in the attached image.
I have only seen this happening with this single message. Everything else seems to be like it should. What is the expected output? What do you see instead? I expect it to be in all norwegian. But now I see an english message when playing in norwegian - and one word in the message is norwegian (Gipsfjerner).

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1353 What operating system / compile settings are you using? Win7 64

What level was this on (e.g. "Demo level", "Full game level 12")?
Level 6

Attached image and save.

**Attachment:** [TESTING3.sav thegipsfjerner.png](http://code.google.com/p/corsix-th/issues/detail?id=937)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=937_

**Comment by bobcanthelpyou** [comment]
This issue is still valid with v0.50 trunk c2e5b0c334fc7094616120efc74b8a18f15b13e9. The dynamic info (e.g. where is a patient going to) is not updated when loading a savegame with a different language.

**Comment by tobylane** [comment]
I can't recreate either problem. Dynamic info is instantly correct after loading a game in a different language.
