### ISSUE TITLE
The handyman can water a plant through the outer wall

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#474]
_From [Grim...@gmail.com](https://code.google.com/u/118083579813208703807/) on July 26, 2011 18:50:14_

The handyman can water a plant through the outer wall
See attached screenshot and savegame.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1353 What operating system / compile settings are you using? Win7 64

What level was this on (e.g. "Demo level", "Full game level 12")?
Level 11

**Attachment:** [wateringplantthroughwall.png watering.sav](http://code.google.com/p/corsix-th/issues/detail?id=955)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=955_

**Comment by tobylane** [comment]
Fixed by #1743
