### ISSUE TITLE
Training room chair glitches through walls

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#475]
_From [CharlesP...@googlemail.com](https://code.google.com/u/103365645135809169866/) on August 01, 2011 11:28:56_

What steps will reproduce the problem? 1. 'put a training chair' next to a wall, as with picture

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
beta 7 What operating system / compile settings are you using? ubuntu 11.04 (32bit)

What level was this on (e.g. "Demo level", "Full game level 12")?
full game level 3 (?) Please provide any additional information below. picture attached

**Attachment:** [training chair.png](http://code.google.com/p/corsix-th/issues/detail?id=967)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=967_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Reproduced on v0.67. Note how the back wheel of the chairs appear underneath the wall.
![2024-04-13 20_44_04-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/c91f95b5-ffbe-4e77-81fb-e542ad5ba7ae)
