### ISSUE TITLE
Falling over animations

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#476]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on September 22, 2011 15:12:11_

What are the major things which your patch changes / adds? Adds yawning for some patients that are waiting or if they have sleeping illness.
Added queue to the list of possible vomit/pee patients to test it out
Also add falling over and shaking of fist for some patients. What version of the product are you using? On what operating system? The falling animations are for when there is an earth quake, as some patients should fall down. Please provide any additional information below. As earth quakes are not in the game yet (fingers are crossed that they never will be) I have made it that from time to time if you click on a patient he or she could fall over.  This is not in TH, but I thought it may make people smile.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1020_

**Comment by tobylane** [comment]
This was merged.
