### ISSUE TITLE
Can't change resolution in DirectX mode

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#477]
_From [raisinge...@gmail.com](https://code.google.com/u/100625675300387157188/) on October 02, 2011 13:23:54_

What steps will reproduce the problem? 1. Open Corsix-th in DirectX mode
2. Enter resolution width and height
3. Click Change Resolution What is the expected output? What do you see instead? Expect the screen size to change resolution like in OpenGL/SDL mode but instead get an error message saying "The screen size you requested is not available in fullscreen mode"

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Beta 8 What operating system / compile settings are you using? Windows Vista 32-bit / windows 32-bit installation using DirectX 10.

What level was this on (e.g. "Demo level", "Full game level 12")?
First game menu and during the game at any level. Attach a saved game file if you have one and it is relevant. Please provide any additional information below. Changing the resolution is not an issue in OpenGL and SDL modes.

Sounds like its a bug where your code is calling the wrong function in DirectX to check if the screen resolution is correct.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1037_

**Comment by Lego3** [comment]
Since we no longer input individual values, but have a list instead, I'll close this. I am able to change resolution using SDL2 and DirectX...

**Comment by MarkL1961** [comment]
Not sure why you think that @Lego3 as you are still able to type in your own values by clicking on custom!
Anyway I can't replicate the error reported, although I did find entering the dimensions awkward to do.

**Comment by Lego3** [comment]
True... I haven't even noticed that at the bottom...
