### ISSUE TITLE
Music cutting off

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#478]
_From [sgr...@gmail.com](https://code.google.com/u/118328560835082530892/) on October 26, 2011 01:29:33_

What steps will reproduce the problem? 1.load game on Mac
2.wait
3.listen What is the expected output? What do you see instead? instead of each full song, they are being cut to the middle of the song, and many songs simply disappear and refuse to play.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Beta 8 What operating system / compile settings are you using? Macintosh
What level was this on (e.g. "Demo level", "Full game level 12")?
any level Attach a saved game file if you have one and it is relevant. Please provide any additional information below.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1056_

**Comment by tobylane** [comment]
Midi and MP3 songs start playing from the start of the songs. MP3 continues to play as long as the music lasts and loops around, I just tested an hour long album.
