### ISSUE TITLE
Double Door Glitch

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#487]
_From [kizzyco...@yahoo.co.uk](https://code.google.com/u/115712554665875184479/) on April 02, 2012 14:57:47_

What steps will reproduce the problem? Glitch appears at random. if played on freebuild with loads of rooms, glich will likely manifest the quickest. Only observed with room doors, not outside doors What is the expected output? What do you see instead? The character should enter/exit the room.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?

0.01 What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?

Any level, but happened once on a campaign level (unsure of a number), and once on the fanmade "Grand Hospital" map. Please provide any additional information below. Editing the room does nothing - the room is effectively "bricked". removing any items nearby does nothing. I have not been able to recover from this, aside from loading an earlier autosave.

As the particular issue was from an emergency, it cannot be reproduced in an autosave. all autosaves of the custom map was overwritten before I had the second issue, this time with a handyman.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1196_

**Comment by lewri** [comment]
Do we know if this one is still possible? It looks like the report was around `0.01` and I would imagine door code has been changed a lot since.

**Comment by mugmuggy** [comment]
For the gamelog attached, the error was changed to a warning a while back see #367.
<html><body>
<pre>

Created game with savegame version 51.
--
Error in timer handler:
...ommon\Corsix\CorsixTH\Lua\humanoid_actions\queue.lua:71: Proper idle not in action_queue
stack traceback:
[C]: in function 'error'
...ommon\Corsix\CorsixTH\Lua\humanoid_actions\queue.lua:71: in function 'action_queue_find_idle'
...ommon\Corsix\CorsixTH\Lua\humanoid_actions\queue.lua:225: in function 'onChangeQueuePosition'

</pre>
</body>
</html>

**Comment by lewri** [comment]
Merged into meta (but reopen if this one is actually a crash rather than just a graphical glitch).
