### ISSUE TITLE
Map with helipad not being accessible due to unowned properties causes crash

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#491]
_From [henke@henke37.cjb.net](https://code.google.com/u/henke@henke37.cjb.net/) on April 14, 2012 17:59:08_

What steps will reproduce the problem? 1. Play the attached map
2. Get an emergency
3. Accept the emergency

Or just load the attached save. What is the expected output? What do you see instead? Notice: LuaJIT not being used.
Consider replacing Lua with LuaJIT to improve performance. Note that there is no
t currently a 64 bit version of LuaJIT.
An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\world.lua:1443: attempt to compare number with boo
lean
stack traceback:
        C:\Program Files\CorsixTH\Lua\world.lua:1443: in function <C:\Program Fi
les\CorsixTH\Lua\world.lua:1428>
        (tail call): ?
        ...am Files\CorsixTH\Lua\humanoid_actions\seek_room.lua:218: in function
 '?'
        C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:528: in function 'Hu
manoid_startAction'
        C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:620: in function 'ti
mer_function'
        C:\Program Files\CorsixTH\Lua\entity.lua:165: in function 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:825: in function 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:709: in function <C:\Program Files
\CorsixTH\Lua\app.lua:707>
        (tail call): ?
        C:\Program Files\CorsixTH\Lua\app.lua:611: in function <C:\Program Files
\CorsixTH\Lua\app.lua:606>

Warning: No event handler for timer

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.01

What level was this on (e.g. "Demo level", "Full game level 12")?
Custom attached one.

I was bored and wanted to see if this incredibly stupid setup would cause an error. It will.

**Attachment:** [Heli fail test.map Heli fail test.level heli fail test.sav](http://code.google.com/p/corsix-th/issues/detail?id=1223)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1223_

**Comment by lewri** [comment]
May be resolved by PR #825

**Comment by tobylane** [comment]
Resolved. Cheating in an emergency on that map tells you there's no helipad.
