### ISSUE TITLE
Doctors getting stuck due to empty action queue / not knowing what to do next!

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#492]
_From [intergal...@gmail.com](https://code.google.com/u/117071775202938624959/) on April 17, 2012 09:16:31_

What steps will reproduce the problem? 1. In the full game campaign level 3, build an Operating Theater
2. After some time, notice that the doctors will get stuck in the Operating Theater and the patients, stuck out of the Operating theater (some of them even dying). What is the expected output? What do you see instead? No one should get stuck in or out of the Operating Theater. 

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.01b What operating system / compile settings are you using? Windows 7, 64-bit

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game level 3 Please provide any additional information below. The doctors and the patients stop going in or out of the Operating Theater. Firing the doctor will not make him go. Also, the doctors in the Operating Theater can't be picked up. What's weird is the handyman can come and go in the Operating Theater as he pleases. The game will also not allow editing the Operating Theater or removing it.

I'm attaching a save game file of when I already noticed the issue. I will try to find a save game before the issue happened and post it here.

**Attachment:** [lvl3stuckOperatingTheatre.sav](http://code.google.com/p/corsix-th/issues/detail?id=1226)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1226_

**Comment by lewri** [comment]
Assume as we haven't had enough info to continue with this ticket
