### ISSUE TITLE
Patients now spend longer in the GPs office

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#493]
_From [sdre...@hotmail.co.uk](https://code.google.com/u/109912214433682013607/) on April 21, 2012 10:41:06_

In the original game, the GP worked in a cycle of using the filing cabinet, waiting for patient, talking to patient, and returning to the filing cabinet. In the new version it seems that the doctor continues to get up and use the filing cabinet while the patient is sitting in the chair, making some visits take longer. In level 2 this has led to a bottleneck in the queue for the GPs office and I'm concerned how it will affect gameplay when I reach the higher levels.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1230_

**Comment by lewri** [comment]
Potentially a non-issue?
