### ISSUE TITLE
Music (on disk) loading blocks the rest of the game from running

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#494]
_From [henke@henke37.cjb.net](https://code.google.com/u/henke@henke37.cjb.net/) on April 30, 2012 16:06:03_

What steps will reproduce the problem? 1. Install the game and point to the HOSP directory on your cd drive
2. Start the game, start a level and play until the current music track is over What is the expected output? What do you see instead? The game will hang for a moment while it loads in the next music track from the disc.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.01b What operating system / compile settings are you using? Win 7 64 bit

Music loading should be asynchronous and take the stall in a separate thread.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1238_

**Comment by tobylane** [comment]
The game doesn't now pause/lag while music from a spun down external hard drive is accessed.
