### ISSUE TITLE
Humanoid graphic glitch

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#495]
_From [jayjay...@gmail.com](https://code.google.com/u/117114112728420604611/) on May 07, 2012 07:18:11_

One of the humanoids died after using the Hair Restorer, but as he collapsed, the graphic changed from a 'man with restored hair' to a 'blonde Bloaty Head'. The Bloaty Head graphic remained when he became an angel

I've seen this happen twice, both on the Greenpool level, but I never thought to screengrab it. I'm using the DirectX version of 0.01b on Windows 7, 64-bit

If I can give you any more information, ask away

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1242_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Having played around with the debugger on Level 7, what I'm seeing is that when a bald patient enters the dying state and collapses to the ground, he suddenly switches to a sprite with hair (not the fancy pompadour that they get from the Hair Restorer, but a generic sprite similar to a cured Bloaty Head patient). I don't know if this behaviour occurred in Theme Hospital, which would depend on whether or not sprites were made for baldies ascending to heaven/falling into the lava. However, I'm not seeing any patients with Bloaty Head, let alone any blonde patients.
![image](https://github.com/CorsixTH/CorsixTH/assets/142453312/dc3c8d99-392c-4dc0-8101-d8847bffb38d)
![image](https://github.com/CorsixTH/CorsixTH/assets/142453312/d35e5956-5284-4bca-935a-5f78e1b21436)
