### ISSUE TITLE
Patient stuck waiting for Operating Theatre

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#496]
_From [sican...@yahoo.co.uk](https://code.google.com/u/114421107135462753382/) on July 15, 2012 09:27:13_

What steps will reproduce the problem? 1. Build two operating theatres
2. Allow the game to play for a while
3. A patient will eventually "jam" waiting for an operating theatre. What is the expected output? What do you see instead? The patient stands up and proceeds to either of the Operating Theatres.

Instead, the patient remains sitting until he eventually dies. The patient also does not use the nearby Vending Machine.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1586 What operating system / compile settings are you using? Linux x86. Using OpenGL renderer.

What level was this on (e.g. "Demo level", "Full game level 12")?
Level 5 Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Unfortunately, I don't have an autosave file before it occured. Will continue playing on this level to see if problem can be reproduced. Attached save file already have problem present. Please provide any additional information below. The patient's current status is the following:
\-----------------------------------
Clicked on humanoid	table: 0x8ad68d8
Class: 	Standard Male Patient
Warmth: 0.301   Happiness: 0.998   Fatigue: 0.000  Thirst: 0.981  Toilet_Need: 0.324   Health: 0.310

Actions:
use_object - bench  must_happen  
queue - Bench distance: 1 Standing: false
walk - going to 38:56    
\-----------------------------------

The patient is waiting for the Operating Theatre to the north (closest to the Ward). The Operating Theatre currently has two surgeons waiting.

Running the following in the LUA console unjams the patient:
TheApp.world.hospitals[1].patients[1]:setNextAction({name = "seek_reception"})
The patient visits the reception, then heads to the operating theatre and successfully enters it.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1268_

**Comment by tobylane** [comment]
Cannot replicate this in a operating theatre with over 100 patients operated on.

**Comment by Lego3** [comment]
This is also one of those issues that might very well happen, but under some very specific circumstances (the vending machine is mentioned). Given that this was reported 4 years ago I would say the one that actually encounters this issue is better of creating a new issue with more information.
