### ISSUE TITLE
VIP feedback does not seem to vary from positive / $2000 reward

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#498]
_From [stu...@stuartmcmillen.com](https://code.google.com/u/101948062527667262717/) on August 25, 2012 23:49:34_

Linux version 0.01 - problem noticed when playing through 10 levels

Visiting VIPs to my hospital always give me a $2000 reward, regardless of how good/crummy their hospital experience ought to have been (based on the temperature, amount of litter, etc they should have spotted on their journey). 

Either that or their sensitivity is not high enough (I have not been deliberately trying to make life hell for the VIPs).

Can you please unlock the full range of VIP reactions and monetary/reputation implications.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1281_

**Comment by Alberth289346** [comment]
@TheCycoONE  @MarkL1961   how is this related to #835 (or associated PR #837 )

**Comment by MarkL1961** [comment]
@Alberth289346  In that it is the VIP and the fax causing the issue!
I think the level multiplier is the issue here for always getting the same award, which I think is also the maximum award.  I have not checked the changes in #837 in detail to see if you have done that there

**Comment by Alberth289346** [comment]
Is this done now?

**Comment by TheCycoONE** [comment]
Fixed
