### ISSUE TITLE
Patient got stuck at door in pharmacy

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#499]
_From [hil...@gmail.com](https://code.google.com/u/115467366052923359740/) on September 02, 2012 08:29:50_

What steps will reproduce the problem? 1. I put the nurse in the pharmacy and a patient just got stuck by the door. The game said there was an error and tried to recover but to no avail... 2. 3. What is the expected output? What do you see instead? I think they should not get stuck :)

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.01 What operating system / compile settings are you using? Win 7

What level was this on (e.g. "Demo level", "Full game level 12")?
I think it was on level 4.

Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Please provide any additional information below.

**Attachment:** [Clipboard02.jpg](http://code.google.com/p/corsix-th/issues/detail?id=1287)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1287_

**Comment by lewri** [comment]
May be resolved by PR #1567

**Comment by mugmuggy** [comment]
Reads as though the same as #436, for the original issue. The last log though is potentially mitigated through 1567 and other fixes since this original issue

**Comment by lewri** [comment]
Optimistically closing as fixed via mitigation as per mugmuggy's comments (and nobody else coming forward)... and we haven't had any actual updates on this issue since 2012 on Google.
