### ISSUE TITLE
Alt+Tab does not work when using the OpenGL version 

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#502]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on October 20, 2012 14:41:29_

What steps will reproduce the problem? 1.Go to your desktop or Task Manager with Windows key or Ctrl+Alt+Del when you're playing CorsixTH (OpenGL) (in case of an error.)
2.You see the Desktop in fornt of you and CorsixTH minimized to the Task bar (in case of Windows key.) And when you use ctrl+Alt+del, the Task Manager will show up.
3.The mouse getting stuck at the left corner of the screen and you can't move him. What is the expected output? What do you see instead? The mouse getting stuck at the left corner of the screen.
You have to close CorsixTH with only the keyboard.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1662 What operating system / compile settings are you using? Windows 7, using OpenGL-executable.

What level was this on (e.g. "Demo level", "Full game level 12")?
Everything: levels and menu. Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Please provide any additional information below. Yes, I could use one of the other executables, but this is very annoying for everyone.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1344_

**Comment by Lego3** [comment]
I'll close this issue now, as we've moved to SDL2.
