### ISSUE TITLE
Alt-tab/ scrolling  issue

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#503]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on November 02, 2012 16:31:48_

What steps will reproduce the problem? 1. Pause the game
2. make sure that you are centred somewhere and that the screen is not scrolling
3. Alt-tab from the game
4. Alt-tab back into the game What is the expected output? What do you see instead? Expect that you will be over the same point of the hospital
You have for some reason moved, you are no longer over the hospital and may even be at the edge of the map.  It's as if there is some scrolling when the game screen is minimized.

Win7 using the DirectX exe of the RC

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1361_

**Comment by bobcanthelpyou** [comment]
@MarkL1961 does this affect the latest v0.50 beta of CorsixTH, too?

**Comment by tobylane** [comment]
DirectX is gone, and this doesn't happen with SDL (with any combination of lock windows and edge scrolling).
