### ISSUE TITLE
Crash that may be windows related

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#504]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on November 03, 2012 16:49:16_

I paused the game to report something on this site and noticed that the CTH music had stopped.  There is now an error message, not from CTH, so I have attached a screen shot and the error logs.
you will notice that there is nothing in the usual console window.

This may just be a random directx error, but I have been running the game for a couple of hours and I remember there being an issue at some point on those lines.  If I had been in the game window I suspect that I would have had to ctl+alt+delete to get out as I can't open the game window at all.  So in that respect I am lucky that I had paused and alt
-tab from the game and therefore able to see the error message.

I don't know whether anyone can make sense of these, but I thought it worth mentioning

**Attachment:** [WER6491.tmp.WERInternalMetadata.xml WERA8A3.tmp.appcompat.txt WERA8F2.tmp.mdmp 4.png](http://code.google.com/p/corsix-th/issues/detail?id=1362)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1362_

**Comment by Lego3** [comment]
Mark, has this happened lately? It's been a long time since your last post, and we've moved to SDL2 as well.

**Comment by MarkL1961** [comment]
Not tried SDL2 yet, otherwise yes at times it does crash

**Comment by TheCycoONE** [comment]
The crash is a memory violation but I'm afraid without a more complete heap dump it could be anything.  If you were able to reproduce this from within the Visual Studio debugger and provide a stack trace it would be useful.

**Comment by MarkL1961** [comment]
Is Visual Studio debugger  something I can download for nothing and would it need to be running in the background to get this stack trace?
Might all be pointless, but all the same it could be useful if it does crash again

**Comment by TheCycoONE** [comment]
It's part of the Visual Studio IDE.  Compile for debugging and launch CorsixTH through Visual Studio with F5.

**Comment by MarkL1961** [comment]
Ah, in that case I am not sure as I have never had any luck with compiling.
I am thinking of giving @J-Shep 's eclipse method ago at some point (when I have several hours to spare that is), but does that use Visual Studio IDE?

**Comment by TheCycoONE** [comment]
J-Shep's eclipse is just for editing and debugging Lua so far.

**Comment by MarkL1961** [comment]
@TheCycoONE  my mistake, it was his `  Setting Up Windows Dev Software  ` page I was thinking about.

I've now compiled a copy, so how do I go about running it from visual studio?  pressing f5 just throws an error.

My exec is in C:\Users\Mark\Documents\GitHub\MarkL\CorsixTH\build\CorsixTH\Debug, but my corsix files will be in C:\Users\Mark\Documents\GitHub\MarkL\CorsixTH\CorsixTH.

If I move my exec to where the other files are, how does visual studio know what to open?

Sorry if the questions sound stupid, but I am new to this sort of thing

**Comment by MarkL1961** [comment]
![error](https://cloud.githubusercontent.com/assets/4965487/5806740/f2f5281e-a013-11e4-9d53-fa1bc41cdf0d.png)

**Comment by MarkL1961** [comment]
I suspect that even though it compiled there may be something wrong as the file size is 827kb and the latest sdl2 is 1950kb - so a big difference.

**Comment by TheCycoONE** [comment]
Ok, a couple more things to do.
1. Set CorsixTH as the startup project (as opposed to all build), you can do that by right clicking on it.
2. You need to copy all the dlls into the folder where CorsixTH.exe is.

**Comment by Lego3** [comment]
It also usually works for me to have the dlls in the CorsixTH folder itself (where the Lua folder is etc - and the CorsixTH.sln file) then you get the same folder hierarchy as the installed version has.

**Comment by TheCycoONE** [comment]
@Lego3 curious, normally that wouldn't be part of the search path so I haven't tried it.  Maybe either CorsixTH itself or CMake influences that.

**Comment by MarkL1961** [comment]
Neither worked for me, do I need to start again with cmake as it has been told where to build?
see the wiki page mentioned above to see the build path

**Comment by TheCycoONE** [comment]
No, what error do you get?

**Comment by MarkL1961** [comment]
No error as such, it just closes straight away

**Comment by TheCycoONE** [comment]
The folders are normal.  For VS it still looks like your start up project is set to the wrong thing.  Right click CorsixTH under projects and select Set as startup project.

If you were double clicking on the exe the error might be hidden, best to run it from VS or the command line to see any errors.

**Comment by MarkL1961** [comment]
This is the error I see now

'CorsixTH.exe' (Win32): Loaded 'C:\Users\Mark\Documents\GitHub\MarkL\CorsixTH\build\CorsixTH\Debug\CorsixTH.exe'. Symbols loaded.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Cannot find or open the PDB file.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Cannot find or open the PDB file.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Cannot find or open the PDB file.
The program '[2620] CorsixTH.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by MarkL1961** [comment]
Those 3 dll's are in that folder

**Comment by MarkL1961** [comment]
Downloaded the PDB and the message is now
'CorsixTH.exe' (Win32): Loaded 'C:\Users\Mark\Documents\GitHub\MarkL\CorsixTH\build\CorsixTH\Debug\CorsixTH.exe'. Symbols loaded.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\ntdll.dll'. Symbols loaded.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\kernel32.dll'. Symbols loaded.
'CorsixTH.exe' (Win32): Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. Symbols loaded.
The program '[3840] CorsixTH.exe' has exited with code -1073741515 (0xc0000135) 'A dependent dll was not found'.

**Comment by Lego3** [comment]
I would still guess you are missing some of our dependency dll's.

Most important is SDL2.dll, SDL2_mixer.dll and lua51.dll (or equiv), but then for movies there are 7 more.

As you state in a previous comment it's funny that you get your executable in that path. For me it's CorsixTH/Debug/CorsixTH.exe, counted from the top CorsixTH repository directory. And then I have all my dlls in the CorsixTH folder.

**Comment by Lego3** [comment]
Are you in the chat channel?

**Comment by MarkL1961** [comment]
I copied all the dll's into the folder where the exec is from where I test.  I would say there are more than is needed as I have not compiled for movies, just the basic as in the wiki page

**Comment by TheCycoONE** [comment]
@MarkL1961 do you still get errors like were reported in this ticket?

**Comment by MarkL1961** [comment]
I've not tried since then

**Comment by TheCycoONE** [comment]
Not enough info. Only call stack is for old engine
