### ISSUE TITLE
Patient is not being treated/diagnosed 

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#505]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on November 12, 2012 14:54:22_

What steps will reproduce the problem? 1. Load the attached save
2. Look at pychiatric room near to slicer What is the expected output? What do you see instead? Elvis has been on the couch for ages and the Dr just wanders around the room.  You expect him to be dealt with and leave the room.
It might be connected to the issue where staff get stuck in rooms, but this time he is not yet in need of a rest.

Win 7 64bit testing RC for 0.11
the is no error log as no error has been thown

**Attachment:** [005.sav](http://code.google.com/p/corsix-th/issues/detail?id=1383)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1383_

**Comment by lewri** [comment]
May be resolved by PR #1505

**Comment by TheCycoONE** [comment]
Not the right PR but I am in favor of closing this since the save isn't valid any more, version is old, and similar or the same issue has been fixed.
