### ISSUE TITLE
Music stop playing and all sounds became glitchy

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#507]
_From [bach...@gmail.com](https://code.google.com/u/109309702708131621512/) on November 17, 2012 11:11:42_

Sometimes the music stop playing (i think after every song in the playlist has been played). When it stops, all the sounds became glitchy (i can record it if you desire). Restarting the game is the only solution. Toggle sound or music on/off don't recover the sound.

I never had this problem with the 0.10, but i don't played a lot.

CorsixTH-0.11-OSX.dmg    Version 0.11 - OS X Universal Package

Mac OS X 10.8.2
Tested with the integrated sound card and with an external usb sound card (M-AUDIO Fast Track Pro). 

Full game ITA (folder copied on hard disk)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1389_

**Comment by tobylane** [comment]
The music now loops around, so there is no way to recreate this.
