### ISSUE TITLE
Equipment marked for repair even after being destroyed by quake

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#508]
_From [damjan.k...@gmail.com](https://code.google.com/u/107831984088981069478/) on December 14, 2012 17:12:05_

What steps will reproduce the problem? 1. Mark some equipment to be repaired (in my case scanner)
2. earthquake that destroys equipment What is the expected output? What do you see instead? After the equipment was destroyed there should be no cog symbol above it. It shouldn't give an error. Currently there is an error when handyman tries to enter the room (when attempting recovery all the menu buttons stopped working)

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.11 What operating system / compile settings are you using? OSX (binary from the main site)

What level was this on (e.g. "Demo level", "Full game level 12")?
Some full game level Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Please provide any additional information below.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1425_

**Comment by TheCycoONE** [comment]
From #641 we have confirmation that this is still an issue.

**Comment by mrbenjamin1** [comment]
From my issues #641 I can also add I had manually asked janitor to fix the now exploded rooms. This is useing the latest version.

**Comment by lewri** [comment]
Off the top of my head I think this one is now resolved?

**Comment by lewri** [comment]
Tested in 0.64 and issue is resolved now.
