### ISSUE TITLE
graphical glitch with toilet

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#509]
_From [Alberth2...@gmail.com](https://code.google.com/u/117559702027655025914/) on December 20, 2012 15:30:27_

Glitches are getting smaller! What steps will reproduce the problem? 1. Build a toilet room like shown in the image.
2. Observe the glitch, the edge against the back-wall of the last / back-most toilet is much smaller than the edge of a 'normal' toilet. 3. What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")? r1768

**Attachment:** [toilet_glitch.png](http://code.google.com/p/corsix-th/issues/detail?id=1427)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1427_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Reproduced on v0.67. Note how the toilet in the corner closest to the Decontamination room clips into the wall.
![2024-04-13 20_49_34-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/e4433c55-258f-4734-b218-42ee2c462070)
