### ISSUE TITLE
Graphical glitch in general diagnosis room

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#510]
_From [Alberth2...@gmail.com](https://code.google.com/u/117559702027655025914/) on December 31, 2012 10:38:57_

What steps will reproduce the problem? 1. Doctor is standing in front of the trolley, yet his head is at the right of it. See image.

trunk version with movie patch (exact revision is unknown as git is very unhelpful)

**Attachment:** [escher_trolley.png](http://code.google.com/p/corsix-th/issues/detail?id=1433)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1433_

**Comment by Alberth289346** [comment]
![escher_trolley](https://cloud.githubusercontent.com/assets/3254232/7094017/4525a8b8-dfbe-11e4-9976-5cac40a83e9b.png)

**Comment by lewri** [comment]
Merged into meta
