### ISSUE TITLE
Possible to repair fracture clinic machine which is adjacent clinic through the wall!

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#511]
_From [r.wiels...@gmail.com](https://code.google.com/u/105437784604245180732/) on January 03, 2013 18:18:09_

What steps will reproduce the problem? 1.Playing the game at normal speed
2.An error occurred, handyman won't move. 3. What is the expected output? What do you see instead? the handyman should keep moving and do his job, but he's just stuck. I can pick him up and place him somewhere else, but he won't move anywhere.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
CorsixTH_OpenGL, 0.11 What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?
full game, (i think) last level. Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Don't know where to find it :( Please provide any additional information below. This happens to various people and personnel.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1437_

**Comment by mugmuggy** [comment]
#624 was duplicate.
