### ISSUE TITLE
Graphical glitch when using video game next to each other

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#512]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on January 17, 2013 12:45:13_

What steps will reproduce the problem? 1.See attached save and image. What is the expected output? What do you see instead? When a doctor plays at the third video game, the second one will almost dissapear behind the third. And when he plays at the second one, the first one will almost dissapear behind the second one. See attached image.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Latest snapshot. What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?
Sorry, I don't know, but I think this is not level-related. Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. See attached savegame. Please provide any additional information below.

**Attachment:** [screenshot1.bmp With the problem.sav](http://code.google.com/p/corsix-th/issues/detail?id=1451)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1451_

**Comment by Alberth289346** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/3254232/7094104/08e9fbc8-dfbf-11e4-9f86-bc695f020d76.png)

**Comment by lewri** [comment]
Merged into meta
