### ISSUE TITLE
Slack tongue: doctor can walk through machine?

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#514]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on January 19, 2013 14:17:30_

What steps will reproduce the problem? 1.Build a slack tongue room.
2.Put an doctor in it.
3.See attached image. What is the expected output? What do you see instead? It looks like the doctor can walk through the machine. Please use labels and text to provide additional information.

**Attachment:** [screenshot6.bmp](http://code.google.com/p/corsix-th/issues/detail?id=1459)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1459_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Reproduced on v0.67. Just before the doctor walks in front of the Tongue Slicer, he briefly appears underneath it.
![2024-04-13 21_02_29-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/31a48190-d846-4590-b9c5-f6f9560197c0)
