### ISSUE TITLE
Copy/paste functionality in Textboxes

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#515]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on January 22, 2013 03:44:55_

What is it you would like in the game? Maybe it's a good idea to add these two hotkeys as copy & paste for the Lua Console, because there's not possibility for copy/paste at the moment? These two hotkeys are the standard at the moment for Windows to Copy/paste, so everyone knows it. What version of the product are you using? On what operating system? Latest SVN.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1472_

**Comment by lewri** [comment]
This feature is still missing from the lua console. Is it still a relevant request?

**Comment by Alberth289346** [comment]
Perhaps. I never use Lua console, but there may be others.

I'd like to see use-cases for both CTL-C and CTL-V. That is, what kind of data does one typically take from a Lua console, and what data is typically added?
I can see use-cases for CTL-V, eg pasting expressions from the source to get their value.
I am not sure there are many cases for CTL-V.

As pasting is an order of magnitude simpler than copy, one direction is to add pasting but not copying.

**Comment by lewri** [comment]
I think where a large code snippet is needed, it's proably better to put it into `debug_script.lua` ; since you can update an reload that one on the fly.

**Comment by lewri** [comment]
As the lua console is a developer use item (mainly) and we have debug_script it's unlikely we need this right now.
