### ISSUE TITLE
Directory selection screen does not show path/directory names (OpenGL)

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#516]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on January 23, 2013 14:40:45_

See attached screenshot

This is what I see if I click on the new data location button in options menu

**Attachment:** [7.png](http://code.google.com/p/corsix-th/issues/detail?id=1473)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1473_

**Comment by bobcanthelpyou** [comment]
@MarkL1961 does this affect the latest v0.50 beta of CorsixTH, too?

**Comment by TheCycoONE** [comment]
Verified working in the latest master. Likely fixed with the move to SDL2.
