### ISSUE TITLE
Prevent crash when queue is nil

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#517]
_From [phazas...@gmail.com](https://code.google.com/u/111150909296903482702/) on January 24, 2013 09:13:54_

219,220c219,222
<   door.queue:unexpect(humanoid)
<   door:updateDynamicInfo()

---
>   if door.queue then
>       door.queue:unexpect(humanoid)
>       door:updateDynamicInfo()
>   end
244c246
<       if queue:size() > 0 and room.is_active then

---
>       if queue and queue:size() > 0 and room.is_active then
251c253
<     if is_entering_room and queue:size() == 0 and not room:getPatient()

---
>     if is_entering_room and queue and queue:size() == 0 and not room:getPatient()

**Attachment:** [walk.lua.patch](http://code.google.com/p/corsix-th/issues/detail?id=1474)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1474_

**Comment by tobylane** [comment]
[Readable patch.](https://web.archive.org/web/20160620112654/http://code.google.com/p/corsix-th/issues/attachmentText?id=1474&aid=14740000000&name=walk.lua.patch&token=ABZ6GAfHJphLMdEF_tLDGfM2YHBH2oCP0A%3A1466411942947) We have similar protections in the functions called - Queue:unexpect, Room:tryAdvanceQueue, etc.
