### ISSUE TITLE
Choose some resolutions (bigger then the computer uses) result in crash

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#519]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on February 02, 2013 12:04:18_

What steps will reproduce the problem? 1.Open options window.
2.When you select by me the following solutions, the game will crash:
-1600X1200
-1366X758
-1500X900
-1920X1080
-1680X1050
-1920X1200

These resolutions are all higher then my screen maximum resolution (1280X1240.) What is the expected output? What do you see instead? The game will be closed and the lua-console crashes.

Maybe the game could better give you a message about that these resolutions are too high instead of crashing? Please use labels and text to provide additional information.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1485_

**Comment by TheCycoONE** [comment]
This doesn't crash anymore. In fullscreen it scales so everything is tiny, and in windowed it just makes big windows.

**Comment by bobcanthelpyou** [comment]
> In fullscreen it scales so everything is tiny, and in windowed it just makes big windows.

On Windows i also see a combination of both, in window mode and high screen resolutions. It makes a big window and scales at the same time.
