### ISSUE TITLE
glitch in ultrascanner animation

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#520]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on February 02, 2013 15:30:12_

What steps will reproduce the problem? 1. View the linked movie https://www.dropbox.com/s/tpogzsfhb7yfgpx/ultrascanner.wmv What is the expected output? What do you see instead? You will notice that when either the male or female leaves the bed it appears that they jump back on before leaving the clinic. Please use labels and text to provide additional information. I think the problem is that in animviewer is reports it as being 11 frames, but after frame 10 it loops back to the patient being back on the bed.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1486_

**Comment by tobylane** [comment]
The animation looks correct now.
