### ISSUE TITLE
Crash during earth quake (segmentation fault)

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#522]
_From [Alberth2...@gmail.com](https://code.google.com/u/117559702027655025914/) on February 07, 2013 14:53:26_

I decided to play 'confined', the new level (at least it had that name) What steps will reproduce the problem? 1. Load the autosave
2. Click "send patient go home" when needed.
3. Wait until the earhquake happens (while the VIP is visiting)
4. After a while in the quake, the application crashes with a segmentation fault.

The stack trace is as follows:

Program received signal SIGSEGV, Segmentation fault.
0x0000000000458844 in THLinkList::getDrawingLayer() ()
(gdb) bt
#0  0x0000000000458844 in THLinkList::getDrawingLayer() ()
#1  0x000000000045e05b in THMap::draw(THRenderTarget_, int, int, int, int, int, int) const ()
#2  0x0000000000452fa4 in l_map_draw(lua_State_) ()
#3  0x0000003518e0c404 in ?? () from /lib64/liblua-5.1.so
#4  0x0000003518e16848 in ?? () from /lib64/liblua-5.1.so
#5  0x0000003518e0baba in ?? () from /lib64/liblua-5.1.so
#6  0x0000003518e0c8ca in lua_resume () from /lib64/liblua-5.1.so
#7  0x000000000043b5c5 in l_mainloop(lua_State_) ()
#8  0x0000003518e0c404 in ?? () from /lib64/liblua-5.1.so
#9  0x0000003518e16848 in ?? () from /lib64/liblua-5.1.so
#10 0x0000003518e0c82d in ?? () from /lib64/liblua-5.1.so
#11 0x0000003518e08436 in lua_call () from /lib64/liblua-5.1.so
#12 0x0000000000443af1 in CorsixTH_lua_main(lua_State_) ()
#13 0x0000003518e0c404 in ?? () from /lib64/liblua-5.1.so
#14 0x0000003518e0c7e4 in ?? () from /lib64/liblua-5.1.so
#15 0x0000003518e0baba in ?? () from /lib64/liblua-5.1.so
#16 0x0000003518e0c9df in ?? () from /lib64/liblua-5.1.so
#17 0x0000003518e084d1 in lua_pcall () from /lib64/liblua-5.1.so
#18 0x000000000042658e in main ()

Linux, trunk r2033 , 64bit AMD

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1497_

**Comment by Alberth289346** [comment]
Autosave doesn't load in trunk any more, making reproducing a lot more tricky.

**Comment by TheCycoONE** [comment]
Looks very much like #124 and #155. It would have been nice to have known that the values were.

**Comment by TheCycoONE** [comment]
I believe this was a duplicate of #124
