### ISSUE TITLE
audio:pauseBackgroundTrack mutes all sound in windows

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#524]
_From [baker.st...@gmail.com](https://code.google.com/u/103808344187714755160/) on February 09, 2013 18:55:59_

audio.lua contains a function audio:pauseBackgroundTrack().  This function exposes an SDL/timidity bug that causes all audio to be muted not just the music track if a midi is playing.

More about the problem can be read here: http://stackoverflow.com/questions/5864603/sdl-mixer-midi-volume-issues-on-windows-vista-7 Because of this bug I had originally avoided calling this function from movie_player.lua, but that was changed when fix was put in to avoid turning music off in the config when movies were playing.  ( r1910 )  Because of this on Windows 7/Vista when using midi, movies are played without sound.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1503_

**Comment by lewri** [comment]
This is a 3rd party issue from 2013. Is it still broken?

**Comment by TheCycoONE** [comment]
Yes, the upstream bug is https://bugzilla.libsdl.org/show_bug.cgi?id=3495

**Comment by lewri** [comment]
libsdl-org/SDL_mixer#128
libsdl-org/SDL_mixer#213
