### ISSUE TITLE
Save a savegame when you're move around the map; map will still move if you open it

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#525]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on February 10, 2013 13:48:33_

What steps will reproduce the problem? 1.Move at the map (scroll) and save the game (with ''enter'') at the same time.
2.Open that savegame (like the one attached.)
3.The scrolling goes on when opening it. What is the expected output? What do you see instead? See above. I'm using the latest snapshot.

**Attachment:** [test scroll.sav](http://code.google.com/p/corsix-th/issues/detail?id=1504)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1504_

**Comment by lewri** [comment]
Non-issue
