### ISSUE TITLE
Can't open a save with a window open (saved with demo) with full game files

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#528]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on March 05, 2013 14:40:22_

What steps will reproduce the problem? 1.Save a game with a window (like Town map and research-screen) open, when using the full original game files.
2.Use the demo files.
3.Open the save (from step 1.)
4. You'll get an error. What is the expected output? What do you see instead? There should no error occur when doing this, opening that window should be canceled. 

This situation could occur when somebody (using the demo-files) opens a savegame from an another user, who was using the full game files.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1525_

**Comment by Alberth289346** [comment]
#279  looks related?

**Comment by TheCycoONE** [comment]
Related but not a duplicate I think.

**Comment by lewri** [comment]
Not specifically related but CorsixTH can't handle loading a demo save with full game files. The game just breaks.
In this case we probably need a behaviour to restrict opening saves in both directions.

**Comment by Alberth289346** [comment]
Even though the actual graphics are the same, should we consider full game data files and demo data files as 2 different 'graphics' sets? (As in, "custom graphics" sets sold commercially.)

Or does the data include more than graphics? (eg behavior or difficulty settings, ie anything beyond just pictures)

OpenTTD has the notion "baseset" (as opposed to graphics extensions, eg new sets of trains, buses, industries, etc). "baseset" is the stuff you need by default, and besides several original commercial versions, there are also 2 or 3 fee versions.
