### ISSUE TITLE
Sliding doors: won't close

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#532]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on March 18, 2013 15:06:48_

I've seen this problem occur before. The attached save is created with 0.20 RC1 and is level 12.

Look at the green sliding doors near the operation room; the door hangs. It seems that the animation to close them doesn't ''start'' sometimes.

**Attachment:** [doors error.sav](http://code.google.com/p/corsix-th/issues/detail?id=1537)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1537_

**Comment by tobylane** [comment]
Fixed. In this save the operating theatre double door is right next to the green double doors with no problem, even when both doors are in use at the same time. http://cl.ly/2O3a1r2H281p
