### ISSUE TITLE
People and staff are blocked

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#537]
_From [kamolada...@gmail.com](https://code.google.com/u/110716004157955082697/) on April 01, 2013 09:06:55_

What steps will reproduce the problem? Free scenario, buildings and bench like on the screen What is the expected output? What do you see instead? People cannot walk between benches

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
last version for windows (downloaded yesterday) What operating system / compile settings are you using? Windows 7
What level was this on (e.g. "Demo level", "Full game level 12")?
AVATAR map Please provide any additional information below. I thing everything is on the screen

By the way, amazing project guys! Im php programmer but if i can help anyway, just write :)

PS. i cant remove bench with scissors, theres any other way to do that, or its another bug?

Best regards

**Attachment:** [blocked.jpg](http://code.google.com/p/corsix-th/issues/detail?id=1563)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1563_

**Comment by mugmuggy** [comment]
Benches aren't passable, and patients can't move diagonally, so this is consistent with the original.
