### ISSUE TITLE
Update some discriptions of the Debian package

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#539]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on April 03, 2013 13:57:39_

This patch updates some discriptions used in the Debian Package. I edited things like that CorsixTH would be still in beta.

**Attachment:** [Debian_update.patch](http://code.google.com/p/corsix-th/issues/detail?id=1566)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1566_

**Comment by Alberth289346** [comment]
Patch nor issue description is available any more, it seems, the only page I get from google archive is "project moved to github https://github.com/CorsixTH/CorsixTH"
