### ISSUE TITLE
Nurse in Pharmacy bug

### ISSUE THREAD

**Issue by ledowong** [CorsixTH/CorsixTH#54]
An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
E:\CorsixTH\Lua\rooms\pharmacy.lua:76: attempt to index local 'staff' (a nil val
ue)
stack traceback:
        E:\CorsixTH\Lua\rooms\pharmacy.lua:76: in function 'commandEnteringPatie
nt'
        E:\CorsixTH\Lua\room.lua:351: in function 'onHumanoidEnter'
        E:\CorsixTH\Lua\humanoid_actions\walk.lua:347: in function 'on_next_tile
_set'
        E:\CorsixTH\Lua\humanoid_actions\walk.lua:142: in function <E:\CorsixTH\
Lua\humanoid_actions\walk.lua:129>
        (tail call): ?
        E:\CorsixTH\Lua\entity.lua:166: in function 'tick'
        E:\CorsixTH\Lua\world.lua:1023: in function 'onTick'
        E:\CorsixTH\Lua\app.lua:789: in function <E:\CorsixTH\Lua\app.lua:786>
        (tail call): ?
        E:\CorsixTH\Lua\app.lua:690: in function <E:\CorsixTH\Lua\app.lua:685>

Warning: No event handler for timer

step to reproduce:
1. a patient need to use Pharmacy but no nurse inside.
2. a nurse (Nurse A) open the door and go in to Pharmacy.
3. right before (or around) the Nurse A close the door, hire a new nurse (Nurse B) and drop her in to Pharmacy. (so two nurse in pharmacy)
3a. (I guess) Nurse A is trying to go out the room, because Nurse B is drop in to the room.
4. before Nurse A go out the room, drag and drop Nurse B out of the room.
--- bug happens ---

the result:
Nurse A stuck in the room cannot go out. Patients in queue cannot go in the room.

**Comment by Lego3** [comment]
Cleaning up among issues.
I couldn't reproduce this either, and since we haven't heard anything in a long time I'll close it.
