### ISSUE TITLE
MapEdit: Selection stays when releasing cursor outside the screen

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#541]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on April 07, 2013 11:08:12_

What steps will reproduce the problem? 1.Press the left mouse button to place something (and keep it pressed.)
2.Then select a area to place the object, parcel etc. (This happens with everything.)
3.Move the mouse cursor outside the screen and release it.
4.Now finish the selection by pressing into the screen and you see that the selection stays. You can remove this selection with selecting it with something else.

See attached movie.

**Attachment:** [CorsixSelectionProblem.mp4](http://code.google.com/p/corsix-th/issues/detail?id=1573)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1573_

**Comment by TheCycoONE** [comment]
I still see similar behavior in the new map editor.  What is the expected behavior?

**Comment by lewri** [comment]
Is this one still relevant/still happening?

**Comment by tobylane** [comment]
Old behaviour: Releasing the button to create a selection while the cursor is out of the window leaves the selection box on screen even when clicking within it. [Archived video.](https://web.archive.org/web/20160620113007/http://corsix-th.googlecode.com/issues/attachment?aid=15730000000&name=CorsixSelectionProblem.mp4&token=ABZ6GAcIMokaHxmaKiuR5G7v0pemLL5p0A%3A1466412021370&id=1573&mod_ts_token=ABZ6GAemVTtDvZft2ipGuW7xgxjPRP8CxA%3A1466412021370)

Current behaviour: Dragging the mouse and releasing the mouse button out of the window works the same as if the cursor was inside the window. I think this is expected, and if not there's the Capture Mouse setting.
