### ISSUE TITLE
Cannot save when jukebox screen is open

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#543]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on April 08, 2013 14:50:31_

I have discovered that you cannot save a game if the jukebox screen is open.  You get an error as follows:

Savegame version changed from 68 (Trunk) to 70 (Trunk). The save was created using 68 (Trunk)
nil     <no name>
<LocalisedString> Current value:Error while saving game: ...op\corsixth\Custom m
enu\CorsixTH\Lua\persistance.lua:214: Can only persist non-empty userdata if they have a __depersist_size metafield

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1580_

**Comment by tobylane** [comment]
It's now possible to save a game while the jukebox window is open.

**Comment by Lego3** [comment]
Closing, thanks for checking through old issues!
