### ISSUE TITLE
Error: attempt to index local 'room' (a nil value) - ocurring when editing rooms 

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#544]
_From [online.s...@gmail.com](https://code.google.com/u/114249464512048550284/) on April 15, 2013 15:03:35_

What steps will reproduce the problem? 1. Edit room
2. At any point click the cancel button. What is the expected output? What do you see instead? It appears as though the left mouse button is in down-state permanently afterwards. Oddly enough though, if I move the mouse to any movable display (like the room menu, or the game bar on the bottom of the screen), the first one attaches to the mouse and gets dragged around, being unable to release it. Also (if I don't already drag some window around), I can open the dropdown-menus from the menu-bar on top, but I can't click any of the options.

Error Log:
Savegame version is 66 (0.20), originally it was 66 (0.20)
Warning: Trying to remove nonexistant room build callback (function: 0000000008472C90) from humanoid (table: 000000000A5D2F50).
Error in buttonup handler: 
...ospital\CorsixTH-0.20-Win64\Lua\entities\machine.lua:258: attempt to index local 'room' (a nil value)
stack traceback:
    ...ospital\CorsixTH-0.20-Win64\Lua\entities\machine.lua:258: in function 'onClick'
    ...ategie\Theme Hospital\CorsixTH-0.20-Win64\Lua\ui.lua:710: in function <...ategie\Theme Hospital\CorsixTH-0.20-Win64\Lua\ui.lua:692>
    (tail call): ?
    (tail call): ?
    (tail call): ?
    ...tegie\Theme Hospital\CorsixTH-0.20-Win64\Lua\app.lua:690: in function <...tegie\Theme Hospital\CorsixTH-0.20-Win64\Lua\app.lua:685>

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
CortixTH-0.20, using DirectX application What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?
Level 6 'Festering on the Wold'
I actively recreated the bug on that map, but I do believe I had the issue at least in level 5 as well. Please provide any additional information below. The error doesn't appear all the time.
Also it seems as though it appears with doctor-used rooms only (this may be a coincidence though, and I am not entirely sure about that. I recreate d the bug with a slack-tongue clinic and an inflator room.)
Similar issues are supposed to be solved already: https://code.google.com/p/corsix-th/issues/detail?id=84&can=1&q=buttonup is particularily close to the bug I have experienced.
I found many more buttonup-errors on the issue pages, all which were supposed to be fixed (which is why I created a new report).

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1588_

**Comment by lewri** [comment]
I spent a while trying to replicate this one. It doesn't happen (including with same room). So closing as resolved, unless it comes up again.
