### ISSUE TITLE
Graph window: text stays through UI

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#549]
_From [maartenp...@hotmail.nl](https://code.google.com/u/103280305005036074093/) on April 30, 2013 13:43:19_

What steps will reproduce the problem? 1.Start a completely new game.
2.Open the Graph window.
3.See attached screenshot. What is the expected output? What do you see instead? This should of course not happen.

**Attachment:** [screenshot21.bmp](http://code.google.com/p/corsix-th/issues/detail?id=1606)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1606_

**Comment by Alberth289346** [comment]
Screenshot is not available any more

**Comment by MarkL1961** [comment]
I don't remember the issue, but is he referring to this?

![issue 549](https://cloud.githubusercontent.com/assets/4965487/20841426/a92e63a0-b8ab-11e6-8fb6-4ac90dcfcaf5.png)

**Comment by Alberth289346** [comment]
Issue 1008 is a better one for this problem
