### ISSUE TITLE
Earthquakes are more violent at slower game speeds

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#550]
_From [dugu...@gmail.com](https://code.google.com/u/115875571364606670451/) on May 03, 2013 09:55:42_

What steps will reproduce the problem? 1. Put game speed into slow speed
2. Wait for earthquake
3. See whole screen shake around more violently than at faster game speeds. What is the expected output? What do you see instead? I expect the screen to move around only a few pixels, as it does at higher game speeds. Instead, the slower the game speed is, the more violent the screen movement is.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
Version 0.20 What operating system / compile settings are you using? Windows 7 64-bit, DirectX 9

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game Level 12 Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. Please provide any additional information below. Save is a few days before an earthquake (starts on 20th Sept). Saved at high speed, so change the speed down before this date to see the difference.

Due to a piece of litter blocking an exit, this also causes a crash around the 24th Sept. I've posted this as separate bug 1608

**Attachment:** [debug.sav](http://code.google.com/p/corsix-th/issues/detail?id=1609)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1609_

**Comment by tobylane** [comment]
Still happens. In this autosave from March there's an earthquake on the 8th. http://cl.ly/0m0h212t403f

**Comment by TheCycoONE** [comment]
Fixed
