### ISSUE TITLE
Switching out of full screen mode on Windows 8 causes black screen and always-on-top

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#554]
_From [dugu...@gmail.com](https://code.google.com/u/115875571364606670451/) on May 05, 2013 11:56:04_

What steps will reproduce the problem? 1. Go into options, switch into full screen mode
2. Switch back to non-full screen mode What is the expected output? What do you see instead? Expect it to go to non-fullscreen mode.
Instead, the whole screen goes black. The mouse cursor is still the needle. Hitting Ctrl+Alt+Delete and choosing task manager restores it (no errors), but the game is then Always-On-Top until restarting the application.

What version of CorsixTH are you using (e.g. "Beta 2", "SVN r123 ")?
0.21RC in DirectX mode What operating system / compile settings are you using? Windows 8, 64-bit
Also occurs in Windows 7 (sometimes without the Always-on-top problem afterwards).

What level was this on (e.g. "Demo level", "Full game level 12")?
Options screen with full game. Please provide any additional information below. Does not occur in OpenGL or SDL modes. Nothing appears in gamelog or console window.

Strangely, on changing to full-screen mode, the data and font locations appear empty, although the tooltips stay correct. That occurs on Win7 and Win8 too.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1620_

**Comment by tobylane** [comment]
This bug was DirectX only, no such problem with SDL now.

**Comment by Alberth289346** [comment]
closing
