### ISSUE TITLE
Replacement Doctors become stuck wandering room

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#560]
_From [whiteros...@gmail.com](https://code.google.com/u/101018178141716639530/) on June 22, 2013 09:13:32_

Placing a new Doctor in a room with an existing Doctor and Patient can lead to new Doctor getting stuck walking around the room. I have observed this frequently in the GPs office. Also seen in Operating Theatre, Psychiatry and X-Ray.

"Good" behaviour (expected behaviour)
1) Patient and Doctor are in GPs office, Patient seated and talking.
2) I put a replacement Doctor in the room.
3) Old Doctor finishes with Patient, then leaves room. Patient leaves also.
4) New Doctor, who has been wandering the room waiting for it to be free, now takes over the room and deals with the next Patient.

The buggy behaviour
1) Patient and Doctor are in GPs office, Patient seated and talking.
2) I put a replacement Doctor in the room.
3) Old Doctor leaves immediately. Patient remains seated.
4) New Doctor keeps wandering room. Becomes tired but never goes to Staff Room. Never sits at the Desk.
5) Patient sits there indefinitely unless interrupted.
6) Fixed by picking up Doctor, forcing Patient to vacate the room.

Pretty much the exact same behaviour is seen in Psychiatry with replacement Doctors - they just wander around the room uselessly, never sitting in the Comfortable Chair, while the Patient remains on the Couch. 

Only seen twice in X-Ray - the new Doctor wanders without ever sitting at the Console, while the Patient remains in place by the X-Ray. Also seen at least once in Operating Theatre - the old Surgeon leaves, but the new Surgeon never goes behind the screen, while the already undressed Patient and other Surgeon stand around and wait forever.

I think the issue is with the Patient - s/he sits there waiting for their original interaction to finish, but it never does.

This may be related to " Issue 1164 " - the new Doctor "ignores" his Patient and just wanders the room.

Other notes:
1) I never have any plants in my hospital - so it is not the Handyman trying to enter the room.
2) I've only seen it where there is a queue outside. Patients may be competing for the door.
3) It's probably not a room layout issue - my GPs offices and Psychiatry are spacious and accessible.

I am using version 0.21 (DirectX) with Windows 7. I have the full game.

The problem has become noticeable in the middle levels as the hospital becomes more congested and I do much more micro-management of staff, particularly around the GPs. I actively watch for this behaviour when placing a replacement Doctor in the GP, because the resulting traffic jam can go unnoticed for a while and ruin a game. It's quite predictable.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1654_

**Comment by tmarplatt** [comment]
I've got a 0.50 savefile of the "GP doctor wandering in the room-bug", but it happened spontaneously (I didn't have to replace any doctor).
Not sure what triggered this but I've seen it happen spontaneously as well a few times.

[walkingGP.zip](https://github.com/CorsixTH/CorsixTH/files/110373/walkingGP.zip)

**Comment by Alberth289346** [comment]
In issue #1063, the same error trace as above occurred; a cause for this was fixed in commit 4f3ac15 where loading a save game caused objects to disappear for walking to them, even though they are still displayed at the screen. It would be interesting to know if this commit also fixes this problem

**Comment by lewri** [comment]
May be resolved

**Comment by TheCycoONE** [comment]
Very old migrated ticket and there have been lots of fixed stuck staff/patient bugs. Closing.
