### ISSUE TITLE
Graphical glitch when operation table is destroyed

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#565]
_From [Grim...@gmail.com](https://code.google.com/u/118083579813208703807/) on August 07, 2013 09:23:48_

When the operation table is destroyed, the machine can be seen through the wall.

See attached screenshot.

**Attachment:** [operation.png](http://code.google.com/p/corsix-th/issues/detail?id=1680)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1680_

**Comment by lewri** [comment]
Merged into meta

**Comment by MandrakeHorse** [comment]
Reproduced on v0.67. Occurs if the operating table is placed directly behind/adjacent to the wall, regardless of orientation.
![2024-04-13 21_54_12-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/25f3e574-4df7-4e1a-a204-a1106dd22b60)
![2024-04-13 21_56_50-CorsixTH](https://github.com/CorsixTH/CorsixTH/assets/142453312/9062b24a-5304-4115-935f-f978030d859d)
