### ISSUE TITLE
Suggest adding OK button to select save

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#568]
_From [mark.l1...@hotmail.co.uk](https://code.google.com/u/117099726060447259318/) on August 19, 2013 04:27:56_

What steps will reproduce the problem? 1. Load a save
2. Go to select a save from the list
3. First it is highlighted and then it is not
4. You have to double click to select the save where as before it would highlight and select it one go

I suspect this is as a result of the recent changes to the directory browser.  I see no hardship here by having to double click now, but thought it worth mentioning.
Perhaps we should add an ok button on this screen too?

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1689_

**Comment by Alberth289346** [comment]
Imho OK button would be useful at several places in the GUI
