### ISSUE TITLE
Fracture Clinic not destroyed correctly in explosion

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#570]
_From [elisabet...@gmail.com](https://code.google.com/u/104118195279680514726/) on September 01, 2013 07:40:25_

After an earthquake happens in the game (in this case, the level Eggsenham), everything seems to get unstable. In the attached save file, several earthquakes have already occured, and a lot of handymen have frozen. In the save, trying to hire new staff, will immediately cause the entire game to hang.

Another thing is that some of the rooms does seem to trap in doctors and patients (not sure if this is an earthquake-caused error). They are not able to leave the room without me editing the room (which seems to reset this "locked" state). What steps will reproduce the problem? 1. Load Elisabeth.sav
2. Try to hire someone, or just try to do anything
3. Get lots of crash output What is the expected output? What do you see instead? ---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Elisabeth\Corsix-TH\Lua\hospital.lua:1668: bad argument `#4` to 'getPathDistanc
e' (number expected, got nil)
stack traceback:
        [C]: in function 'getPathDistance'
        C:\Elisabeth\Corsix-TH\Lua\hospital.lua:1668: in function 'searchForHand
ymanTask'
        C:\Elisabeth\Corsix-TH\Lua\entities\staff.lua:921: in function 'searchFo
rHandymanTask'
        C:\Elisabeth\Corsix-TH\Lua\calls_dispatcher.lua:232: in function 'answer
Call'
        ...abeth\Corsix-TH\Lua\humanoid_actions\answer_call.lua:24: in function
'?'
        C:\Elisabeth\Corsix-TH\Lua\entities\humanoid.lua:550: in function 'Human
oid_startAction'
        C:\Elisabeth\Corsix-TH\Lua\entities\humanoid.lua:642: in function 'finis
hAction'
        ...abeth\Corsix-TH\Lua\humanoid_actions\sweep_floor.lua:29: in function
'timer_function'
        C:\Elisabeth\Corsix-TH\Lua\entity.lua:166: in function 'tick'
        C:\Elisabeth\Corsix-TH\Lua\entities\staff.lua:146: in function 'tick'
        C:\Elisabeth\Corsix-TH\Lua\world.lua:1035: in function 'onTick'
        C:\Elisabeth\Corsix-TH\Lua\app.lua:824: in function 'dispatch'
        C:\Elisabeth\Corsix-TH\Lua\app.lua:725: in function <C:\Elisabeth\Corsix
-TH\Lua\app.lua:720>

Warning: No event handler for timer

What version of CorsixTH are you using (e.g. "0.21", "SVN r123 ")?
SVN r2458 SDL What operating system / compile settings are you using? Windows 7 x64

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game, Eggsenham Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. If possible, also attach the gamelog. Please provide any additional information below.

**Attachment:** [Elisabeth.sav gamelog.txt](http://code.google.com/p/corsix-th/issues/detail?id=1698)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1698_

**Comment by lewri** [comment]
I believe the bugs related here have since been fixed over various versions. I do not believe earthquakes cause crashes with exploding rooms in 0.64

**Comment by lewri** [comment]
In the last two releases I have not seen anything like this behaviour reoccur, even in my testing of earthquakes in 0.63/0.64

I will optimistically close as fixed now.
