### ISSUE TITLE
Handyman gets stuck at the door of operating room

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#572]
_From [rachelc...@gmail.com](https://code.google.com/u/117627996219786745139/) on October 16, 2013 14:20:21_

I seem to be having the same problem from issue `#1291` ( https://code.google.com/p/corsix-th/issues/detail?id=1291 ), with the latest version of CorsixTH (I downloaded it yesterday). I'll get the prompt that would say something along the lines of "an error has occurred, would you like to correct it?" but clicking yes or no doesn't make any difference.

Even if I leave the handyman stuck, other handymen would get stuck at the same spot if they try to go into the operating room. The game would then freeze up.

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1715_

**Comment by ChrisPre** [comment]
I've had a similar issue but where a handyman entered the Operating theatre, watered a plant and got stuck trying to leave (seemingly as if he's joined the queue for the room). This prevents any patients or even doctors from entering the room.

I have a save I could provide if required (although I can't find a way of uploading a .sav to this report!).

**Comment by mugmuggy** [comment]
This original issue is avoided now with the merge of #1435. The last issue mentioned here appears to be one of the door reservation bugs, thus closing.
