### ISSUE TITLE
Patients should queue for rooms with 0 max queue set

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#573]
_From [fang.xianfu](https://code.google.com/u/fang.xianfu/) on October 19, 2013 07:06:32_

As discussed here: http://forums.corsixth.com/index.php/topic,5454.0.html This patch removes the exception for rooms with a max queue set to 0 in World:findRoomNear(). This means that there will be functionally no difference between a room with 6 patients queueing and a max queue of 6, and a room with a max queue of 0. See the thread for more info.

I was amazed that this change was so tiny, but it looks like this was all it took. Incidentally this may also fix a bug with the toilet callback in patient.lua that would prevent the callback from being called even though there was a usable toilet. 

findRoomNear() is used in the following places:

seek_room.lua, seek_toilets.lua - used to find nearest sought room. Intended change to allow patients to queue for rooms with 0 max queue, which would be skipped before. Because they use advanced mode, rooms with max queue 0 always receive the "full queue" penalty to their getUsageScore() and will not be returned unless all rooms have full queues.

patient.lua - used to find a nearby toilet to determine if one is built and so it's ok to queue a seek_toilet action. Previously this function couldn't tell the difference between an unbuilt toilet and a toilet with 0 max queue, so the callback would be created if the only available toilets had a max queue of 0. If the max queue was increased after the callback was created, it would never be called despite there now being an available toilet.

This change will cause a seek_toilet to be queued even if all available toilets have 0 max queue, where previously it would have acted as if there were no toilets built. Since patients will now be allowed to queue for toilets with 0 max queue by seek_toilet.lua, this is appropriate. 

staff.lua, seek_staffroom.lua - used to determine if a staffroom exists or if we need to wait for it to build, and to find nearest staff room to rest in. Should be unaffected as staff rooms don't have user-settable queues.

Thanks!

**Attachment:** [zeroqueue.patch](http://code.google.com/p/corsix-th/issues/detail?id=1717)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1717_

**Comment by TheCycoONE** [comment]
I guess the patch is lost on this, but the idea isn't a bad one. It's clear from the thread that some people want the original theme hospital behavior, and when there is controversy it's good to side with the original game.

**Comment by fangxianfu** [comment]
I reconstructed the patch, I'll make a PR :)
