### ISSUE TITLE
Chinese is not shown in game language options

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#574]
_From [shuffle....@gmail.com](https://code.google.com/u/113767169585775459938/) on October 26, 2013 19:34:18_

What steps will reproduce the problem? 1. start up
2. setting
3. game language What is the expected output? What do you see instead? Chinese is not shown in game language options, even with unicode font(arialuni.ttf) installed and used in corsixTH.

What version of CorsixTH are you using (e.g. "0.21", "SVN r123 ")?
0.21 What operating system / compile settings are you using? MAC OS X Mavericks

What level was this on (e.g. "Demo level", "Full game level 12")?
Full Game

screen cap attatched

**Attachment:** [屏幕快照 2013-10-27 上午10.30.34.png](http://code.google.com/p/corsix-th/issues/detail?id=1719)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1719_

**Comment by saprys** [comment]
Hi, after installing under mac os High Sierra in the settings there is no Russian language, I run the version from gog
![2018-01-11 23 59 25](https://user-images.githubusercontent.com/35349175/34847951-17025776-f72e-11e7-877b-d7d5be54b8cb.png)

**Comment by TheCycoONE** [comment]
The most common reason for this is that the font in your config.txt doesn't cover the characters (or isn't set). See #823 

The cause of this issue was resolved.
