### ISSUE TITLE
Issue with poor translation of an advisor string from original TH data (French translator could fix maybe?)

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#576]
_From [walzer.e...@gmail.com](https://code.google.com/u/117742393957013122806/) on November 02, 2013 14:48:17_

What steps will reproduce the problem? 1.load the file nivequ7b
2.wait for the urgency "main moite"
3.a few second after the patients enter the hospital, the screen become black, but i hear the music which plays when there is a "you lose video"

What version of CorsixTH are you using :
version 0.21, running with the open GL What operating system / compile settings are you using? windows 7

For me it's the level 7, but i had the famous "level 5 bug" at the level 4, so i suppose i'm missing something... could be the level 8.

I can't have a clear screen shot of the first windows, there only is something about a possible speed loss due to the max analyz duration being higher than 500000

the error log of windows, for what it's worth :
Description :
  Un problème a provoqué l’arrêt de l’interaction de ce programme avec Windows.
Signature du problème :
  Nom d’événement de problème:	AppHangB1
  Nom de l’application:	CorsixTH_OpenGL.exe
  Version de l’application:	0.0.0.0
  Horodatage de l’application:	51795ad0
  Signature de blocage:	7424
  Type de blocage:	0
  Version du système:	6.1.7601.2.1.0.768.3
  Identificateur de paramètres régionaux:	1036
  Signature de blocage supplém. 1:	74247f02fc3c0bfb01c5a22e2ac8595e
  Signature de blocage supplém. 2:	a5b1
  Signature de blocage supplém. 3:	a5b13fd80aa1c7fe0e68bd332eefd309
  Signature de blocage supplém. 4:	7424
  Signature de blocage supplém. 5:	74247f02fc3c0bfb01c5a22e2ac8595e
  Signature de blocage supplém. 6:	a5b1
  Signature de blocage supplém. 7:	a5b13fd80aa1c7fe0e68bd332eefd309

**Attachment:** [niveau7b.sav config.txt gamelog.txt](http://code.google.com/p/corsix-th/issues/detail?id=1721)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1721_

**Comment by wolfy1339** [comment]
The famous level 5 bug has been fixed in a later release.
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/languages/french.lua#L26

**Comment by MarkL1961** [comment]
Brilliant
