### ISSUE TITLE
Doctor stuck in slack tongue clinic

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#577]
_From [dr.dr....@o2mail.de](https://code.google.com/u/115503304786806343366/) on November 07, 2013 10:41:09_

What steps will reproduce the problem? Load the attached savegame.
No message in the log window.

What version of CorsixTH are you using?
Latest 2566 OpenGL What operating system / compile settings are you using? XP x64 sp2

What level was this on (e.g. "Demo level", "Full game level 12")?
Custom Map Grand Hospital

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1723_

**Comment by mugmuggy** [comment]
Grabbed the save from wayback and it appears to have the only slack tongue room functional, no other detail to work with.
