### ISSUE TITLE
Room blocked

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#579]
_From [Kirbe...@gmail.com](https://code.google.com/u/106242792039554983747/) on November 23, 2013 22:45:29_

What steps will reproduce the problem? 1. Load the attached saved game.
2. Watch the X-Ray room
3. Notice handymen and patients aren't entering that room. What is the expected output? What do you see instead? Handymen and patients should be entering the X-Ray room

What version of CorsixTH are you using (e.g. "0.21", "SVN r123 ")?
SVN r2579 (SDL) What operating system / compile settings are you using? Windows 7

What level was this on (e.g. "Demo level", "Full game level 12")?
Not sure, check the briefing. Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. If possible, also attach the gamelog. Please provide any additional information below.

**Attachment:** [xray blocked.sav](http://code.google.com/p/corsix-th/issues/detail?id=1725)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1725_

**Comment by tobylane** [comment]
The save game is no longer available.
