### ISSUE TITLE
Washed fonts in DX & oGL mode

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#580]
_From [spea...@googlemail.com](https://code.google.com/u/111841606487299453808/) on March 18, 2014 16:58:01_

What steps will reproduce the problem? 1. start corsix th on DX or OpenGL mode (SDL works great)
2. tried in windowsmode as well as in fullscreen
3. fonts are blurry / washed What is the expected output? What do you see instead? clear fonts

What version of CorsixTH are you using (e.g. "0.21", "SVN r123 ")?
0.30 What operating system / compile settings are you using? Windows 8.1 64bit

What level was this on (e.g. "Demo level", "Full game level 12")?
all incl. menu Attach a saved game file (preferably an autosave from before the error) if you have one and it is relevant. attached screenshots If possible, also attach the gamelog. no sense Please provide any additional information below. cant play dx & oGl cause of font / missing cleartype? cant play sdl cause of missing zoom :(

**Attachment:** [corsixth_DX.png corsixth_oGL.png corsixth_SDL.png](http://code.google.com/p/corsix-th/issues/detail?id=1734)

_Original issue: http://code.google.com/p/corsix-th/issues/detail?id=1734_

**Comment by Lego3** [comment]
As we have now moved to SDL2 and I can't really see the image supplied anymore I'll close this issue. Please open a new one if the issue persists.
