### ISSUE TITLE
Lava hole freeze when using French sounds

### ISSUE THREAD

**Issue by Sigzegv** [CorsixTH/CorsixTH#588]
Built 0.40 release under linux ( archlinux ). 

Game seems to freeze every time a lava hole pops when a patient dies.

**Comment by J-Shep** [comment]
I will try to fix this bug today.

**Comment by J-Shep** [comment]
>> The lava sounds do look correct in all the files, but only 5 crashes for me.

This crash occurs for SOUND-5.dat when LAVA004.WAV is played.

**Comment by Sigzegv** [comment]
Did you got the crash with SOUND-1.dat like me ?

**Comment by J-Shep** [comment]
>> Did you got the crash with SOUND-1.dat like me ?

@Sigzegv No, like @MarkL1961 only SOUND-5.dat is crashing my CorsixTH. My TH sound data files are from a gog.com TH install. Is your SOUND-5.dat file from a CD install/demo?

**Comment by J-Shep** [comment]
>> This crash occurs for SOUND-5.dat when LAVA004.WAV is played.

LAVA004.WAV is actually played but the crash occurs when CorsixTH tries to play the next Lava sound. I will try to fix this tonight.

**Comment by Lego3** [comment]
It might be worth including some fallback if possible. There might be some versions of Theme Hospital that lack certain sounds. We have had that issue before (I think it was the Italian original release or something that lacked a certain "idle" sound)

**Comment by J-Shep** [comment]
>> It might be worth including some fallback if possible. There might be some versions of Theme Hospital that lack certain sounds. We have had that issue before (I think it was the Italian original release or something that lacked a certain "idle" sound)

@Lego3 I will create a fallback response and error print statement for when a sound is missing from a releases's active SOUND-X.dat. LAVA004.WAV isn't missing from my SOUND-5.dat.

There's no response for [SDL.Mix_PlayChannelTimed()](http://sdl.beuc.net/sdl.wiki/Mix_PlayChannelTimed) returning an error, so I will add a print call for Mix_GetError():

```
void THSoundEffects::_playRaw(size_t iIndex, int iVolume)
{
    int iChannel = reserveChannel();
    Mix_Volume(iChannel, iVolume);
    Mix_PlayChannelTimed(iChannel, m_ppSounds[iIndex], 0, -1) == -1;
}
```

**Comment by J-Shep** [comment]
SDL.Mix_PlayChannelTimed() is returning a channel number instead of -1 (critical error) when LAVA004.wav is played.

**Comment by MarkL1961** [comment]
There were no sounds missing in any of my sound-*.dat's but with 5 lava004.wav (extracted) did crash sometimes when played with the media player.
@J-Shep  I think by fall back @Lego3 means that it should not crash at all, perhaps skips that sound on error?

**Comment by J-Shep** [comment]
The error is occurring in **th_lua_sound.cpp:l_soundfx_play()** after its playRaw() call, in this IF statement closure I created for playing lava sound sequences:

```
//SDL SOUND_OVER Callback Timer:
    //6: unusedPlayedCallbackID
    if(lua_isnil(L, 6) == false)
    {
        //7: Callback delay
        int iPlayedCallbackDelay = 0; //ms
        if(lua_isnil(L, 7) == false)
            iPlayedCallbackDelay = luaL_checknumber(L, 7);

        if(m_iPlayedSoundCallbackIDsPointer == sizeof(m_a_iPlayedSoundCallbackIDs))
            m_iPlayedSoundCallbackIDsPointer = 0;

        m_a_iPlayedSoundCallbackIDs[m_iPlayedSoundCallbackIDsPointer] = luaL_checkint(L, 6);
        SDL_TimerID timersID = SDL_AddTimer(pArchive->getSoundDuration(iIndex) + iPlayedCallbackDelay,
                                            played_sound_callback,
                                            &(m_a_iPlayedSoundCallbackIDs[m_iPlayedSoundCallbackIDsPointer]));
        m_mapSoundTimers.insert(std::pair<int, SDL_TimerID>(m_a_iPlayedSoundCallbackIDs[m_iPlayedSoundCallbackIDsPointer], timersID));
        m_iPlayedSoundCallbackIDsPointer++;
        cout << "DONE: SDL SOUND_OVER Callback Timer." << "\n";
    }
```

The "DONE: SDL SOUND_OVER Callback Timer" print statement isn't being printed.

>> @J-Shep I think by fall back @Lego3 means that it should not crash at all, perhaps skips that sound on error?

@MarkL1961 Well I don't think SDL failing to play a sound would actually crash a game using it and would only result in the sound not being played. 

But if a sound can't be played because its missing then I think there a error/warning message should be printed & this error should be auto reported by my WIP [Error report email sending code](https://github.com/CorsixTH/CorsixTH/issues/445) and I think CorsixTH should try to find the sound in at least the English sound data archive.

**Comment by Lego3** [comment]
Have in mind also that not all distributions contained all sound archives.

**Comment by J-Shep** [comment]
The crash is being caused by an infinite loop in: th_lua_sound.cpp:THSoundArchive:getSoundDuration()

I will find out why this is happening and then fix this later.

**Comment by J-Shep** [comment]
I will try to fix this today.

**Comment by J-Shep** [comment]
I've fixed this error. I will make a pull request soon.
