### ISSUE TITLE
Game Replays

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#589]
I'm working on this now and I may include this enhancement's commit in my pull request for automated Lua error reports (#445).

I guess no player would be entertained by watching a replay of another player's game but this enhancement would be useful for developers because it could be used to repeat reported Lua errors and it could be used to test CorsixTH by making it play through levels at a fast speed.

Replay data will be stored in a App.lua table: if a player chooses to attach a replay to a saved game then its data will be persisted in this table. To play a replay a player/developer would just load a saved game which has an attached replay and then they would be asked if they wanted to play the attached replay.

CorsixTH could also be launched from the command line in a no input & optionally no graphics, replay test mode. So a level replay test could be added to the travis build script.

**Comment by J-Shep** [comment]
>> @J-Shep No offence intended, but as a fellow 'idea flitterer', would it not be a good idea to complete your existing proposals before starting new ones? :-/

@admdly Your right but I do have some good reasons for having lots of unfinished tasks:

My tasks (Proposed in December):
1. Implement a LAN multiplayer system & mode: this is a big task which will take me a long time to finish. I didn't work on this in December because I wanted to get task 2 & 3 done first so that when I've designed my solution to this task I can implement it more quickly using Eclipse because of the its helpful features I've made CorsixTH support. I will now spend at least an hour every day working on this task until its finished.
2. Done (will make changes request by @Lego3 ): support for debugging CorsixTH's lua scripts at runtime in Eclipse.
3. Done: changed classes to make Eclipse outline their functions, allowing a user to jump their text editor view to a function's declaration by simply clicking on it its class's list of functions. 
4. 90%+ Done: Implement automated emailing of Lua error reports. Won't submit a pull request until task 5's changes for Lua error replays can be included.
5. WIP: Implement game replays.
6. Proposed (originally as a task I would get done in my Christmas week): Implementing IRC chat support for singeplayer and multiplayer games.
7. WIP: fixing issue 558 because this error can crash CorsixTH for non English players and although it isn't necessarily being caused by a mistake I made implementing hell deaths, as the developer who implement this death action I want to make sure that no game crashing errors can occur when it takes place.

Unfinished tasks from before December:
8. Lua done but graphics source code changes required: Make Hairyitis patients who die transform into female patients sometimes before their death action starts. 
9. Graphics source code changes required: Remove the need for the on_ground animation to be used for males in hell deaths because it has less layers than the last frame of the male fall animations so their hats disappear and white shoes become brown shoes.

I've not finished tasks 7 & 8 because I've kept finding more important tasks to work on like fixing game crashing bugs.

Finishing task 4 & 5 is now my priority in order to help other developers find and fix game crashing bugs because making sure new CorsixTH releases are free of crash bugs is more important than implementing any new enhancement/feature.

I will now spend at least an hour every day working on task 1 and when 4 & 5 are done, task 1 will become my priority.

**Comment by J-Shep** [comment]
As @admdly and other devs have told me I should really finish implementing my existing enhancement tasks before I give myself new ones to work on, "striking while the iron is hot". So I will now spend only a few days seeing how much progress I can make with this task and then if I'm not close to finishing it I will pause my work on it to get my more important auto error reports task finished.

**Comment by Alberth289346** [comment]
Sorry to disrupt the party, but wouldn't you need a proper savegame first before this is of any use?

**Comment by J-Shep** [comment]
>> Sorry to disrupt the party, but wouldn't you need a proper savegame first before this is of any use?

If you have no automatically or manually saved games for a hospital your running then you've started a new hospital so to run a replay for this hospital CorsixTH would create a new game for this hospital's scenario and then modify it by replaying your sequence & timing of input events.

**Comment by Alberth289346** [comment]
Hmm. Before you go off on spending time on this, did you try reloading a game a few times, do nothing, and see how it progresses? the replay sequence is empty (so trivially reproduced), and there are no input events (also trivially reproduced).
You'd expect that literally everything progresses in the same way, right?

I don't remember exactly, but I did this as part of debugging something, and iirc sometimes something different happened. It didn't affect me, so I didn't investigate it, but in your case it could be a problem.
If that is indeed the case, then a savegame is already not sufficient information to replay. It probably doesn't save the random generator state, or the generator is reset??

**Comment by MarkL1961** [comment]
I  know what @Alberth289346 is saying.  In the past I have had an error, but when I tried to reproduce it things did not happen in the same way.  I replayed the same save 50 times and only reproduced the error once.  I put it down to the randomness in the game and there is a lot of it.
So unless you are able to record the decisions made in a game you will never get a proper replay

**Comment by J-Shep** [comment]
Well while the hospital is closed with the gameplay being in its event less "build time" state obviously nothing will change regardless of the difficulty setting except for the value of the countdown timer. But once this timer has expired & the hospital's forced to open world & gameplay events would happen randomly sometimes despite there being no entities (such as earthquakes & VIP requests) because of "should they happen with the set difficulty?" World:tick() checks with calls to Lua's pseudo random number generating function:  **math.random(...)**. 

I think it would best to create a wrapper Util.lua:random() function to replace these math.random() calls with an if statement check inside of it to check if TheApp.replay_active is true in order to decide whether to return a number from math.random(...) with the provided parameters or to pop a number off the replay stack.

**Comment by TheCycoONE** [comment]
l_randomdump and l_randomseed (see random.c) exist for this purpose. Storing a table of generated random numbers from a deterministic random number generator would be wasteful.

**Comment by J-Shep** [comment]
>> Storing a table of generated random numbers from a deterministic random number generator would be wasteful.

@TheCycoONE Are you against the idea of storing data for even short replays for what happens between autosaves in order to always be able to reproduce Lua errors without having know what input events caused them? If you or @Lego3 don't want me to implement this then I won't.

**Comment by TheCycoONE** [comment]
All I'm saying is that the random numbers don't need to be stored. If you dump the initial random seed, and then populate it at the start of the replay the numbers will be the same.

**Comment by J-Shep** [comment]
@TheCycoONE I see. Well if you and @Lego3 have no objections to me implementing game replays to help with reproducing errors and running automated beta tests then I will definitely work on this. 

Would you object to "Black Box" replays being enabled by default with this feature increasing how much memory CorsixTH would use?

**Comment by Alberth289346** [comment]
Euhm, I still don't understand. How does this work?

Let's say I am a user. I load a random savegame X from the Internet or something.
I play for some time, and save into savegame Y onto my disk. I continue playing, and then it crashes.
What file do I send you?

**Comment by J-Shep** [comment]
When you've loaded saved game X:
1) CorsixTH will begin recording a new black box replay, marking for deletion any previously referenced black box replay: by making TheApp.black_box_replay reference a new Replay object, giving this Replay object the current game state for its prior_game_state field and then telling it to start recording input events.
2) Lets say an autosave occurs before you create saved game Y: so CorsixTH will repeat step 1 this time creating a fresh black box replay for the this new autosave and discarding the blackbox replay for savegame X.
3) Then you create saved game Y, so CorsixTH will repeat step 1 again.
4) Now you continue playing and as you play TheApp will record each SDL input event in:
>> TheApp.black_box_replay.events{1:{time, playback_callback}, 2: time, playback_callback} etc}

Each event is recorded before its executed and could potentially cause a Lua error. An event's playback_callback will simply be its App:on...() handling callback with its occurrence parameters.
5) Then before any new saved games are created an event handled by a call to one of TheApp's SDL event handling callback functions causes a Lua error to occur.
6) TheApp.run() will now begin responding to this Lua error in its CorsixTH executing coroutine, by creating a new saved game for the black box replay: creating this new saved game from the game state table referenced by **TheApp.black_box_replay.prior_game_state** and then persisting this replay by including a reference to its Replay object's table written to the saved game file.

7) Now a developer wants to reproduce your error so you give them your **black_box.rsav** file to load from their "load saved game" menu.
8) When CorsixTH loads this saved game it notices that this saved game's state table doesn't have a nil replay field so after initialising the game state CorsixTH will pause it and the prompt developer user to confirm if they want it to run the replay.
9) The developer clicks yes: so a reference to this Replay object's loaded table is assigned to TheApp.replay, the variable for referencing a replay being recorded/played which isn't the black_box replay.
10) Then CorsixTH begins the replay by calling: **TheApp.replay:play()** making this object create  a SDL countdown timer for the first "playback" event's execution delay.
11) This countdown timer expires making SDL call sdl_core.cpp which passes a new replay_timer_expired event to the App class which has a onReplayTimerExpired() handler which in turn calls: TheApp.replay.countdown_timer:onExpired().
12) CountDownTimer:onExpired() replays the event by simply executing TheApp.replay.events[TheApp.replay.pointer].callback. Then incrementing the pointer. Its response finishes by calling TheApp.replay.play() which will be called recursively to reset the countdown timer for triggering the execution of the next playback event until there's no more events when it finish the replay's execution by calling TheApp:onReplayFinished().
13) But because the last replay playback event will be the one which caused the error to occur, the final TheApp.replay:play() call would never be reached for this replay. With this being a black_box.rsav replay the developer and CorsixTH will know that the last replay event will cause an error to occur so CorsixTH can avoid executing this instruction until the developer tells it to allow this this event's Lua error to occur.

I've created the essential code for recording, playing and persisting replays. Now I need to debug this code.

I want to make a Busted Lua script to include in my pull request which will make use of replay execution calls to perform a useful runtime test. This way I can find out what the functional requirements will be for making my implementation of game replays support effective integration with Busted Lua script tests.

I have in mind a Busted script which would use one or more game replays to construct & thoroughly test any room (provided as a parameter) with all its objects  and patients, to see if any Lua error occur.

**Comment by J-Shep** [comment]
I've realised that having **TheApp.black_box_replay.prior_game_state** refer to a game state copy in memory in an unnecessary waste of memory space. It should instead refer to the game state copy on a player's hard drive in the saved game a  black box replay is created for.

**Comment by J-Shep** [comment]
Hi,

Has anyone taken over this task during my contribution hiatus?

**Comment by Alberth289346** [comment]
No

**Comment by TheCycoONE** [comment]
Multiplayer is actually somewhat contingent on a lot of the same work needed to get this working properly - that is a deterministic client that can play a list of events and end up at the same end state.
