### ISSUE TITLE
Game freezes when picking up consultant surgeon

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#591]
Version: 0.40 SDL on Windows 7 x64
Playing Level 6
I picked up a consultant surgeon to place him in the operating theatre and the game froze. It was after an earthquake.

Included below is stack trace from console
<pre>An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
...ownloads\CorsixTH-0.20-Win64\Lua\dialogs\place_staff.lua:78: bad argument #1
to 'getCellFlags' (Map co-ordinates out of bounds)
stack traceback:
        [C]: in function 'getCellFlags'
        ...ownloads\CorsixTH-0.20-Win64\Lua\dialogs\place_staff.lua:78: in function 'draw'
        ...ers\user\Downloads\CorsixTH-0.20-Win64\Lua\window.lua:1238: in function 'draw'
        ...rs\user\Downloads\CorsixTH-0.20-Win64\Lua\game_ui.lua:150: in function 'draw'
        C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:869: in function 'dispatch'
        C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:753: in function &lt;C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:748&gt;

Warning: No event handler for frame
</pre>
Gamelog.txt:
<pre>Created game with savegame version 91.
Warning: Trying to remove nonexistant room build callback (function: 0x11fc0a30) from humanoid (table: 0x0c938ee8).
Warning: Trying to remove nonexistant room remove callback (function: 0x08e61990) from humanoid (table: 0x0c938ee8).
Warning: Trying to remove nonexistant room build callback (function: 0x0bf0eda8) from humanoid (table: 0x0bdc6338).
Warning: Trying to remove nonexistant room remove callback (function: 0x07876440) from humanoid (table: 0x0bdc6338).
Error in frame handler: 
...ownloads\CorsixTH-0.20-Win64\Lua\dialogs\place_staff.lua:78: bad argument #1 to 'getCellFlags' (Map co-ordinates out of bounds)
stack traceback:
	[C]: in function 'getCellFlags'
	...ownloads\CorsixTH-0.20-Win64\Lua\dialogs\place_staff.lua:78: in function 'draw'
	...ers\user\Downloads\CorsixTH-0.20-Win64\Lua\window.lua:1238: in function 'draw'
	...rs\user\Downloads\CorsixTH-0.20-Win64\Lua\game_ui.lua:150: in function 'draw'
	C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:869: in function 'dispatch'
	C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:753: in function <C:\Users\user\Downloads\CorsixTH-0.20-Win64\Lua\app.lua:748>
</pre>
**The folder name is CorsixTH-0.20-Win64, but it is version  0.40**

**Comment by MarkL1961** [comment]
Can you share your save?

**Comment by wolfy1339** [comment]
Unfortunately I don't have one from before the game froze.



But, I remembered that it was after an earthquake

**Comment by MarkL1961** [comment]
Did any rooms explode?  The error mentions out of bounds which makes me think the surgeon was perhaps being placed somewhere he shouldn't be

**Comment by wolfy1339** [comment]
No, all the room were intact.
I picked him up from a gp's office to place him in the operating theatre, which was intact

**Comment by MarkL1961** [comment]
I wonder if the operating theatre was in need of repair after the earthquake and was perhaps locked.
Should be easy enough to replicate to see if such a thing would throw an error when you place some staff in such a room.

**Comment by wolfy1339** [comment]
There was already one surgeon in the room before I placed the one that caused the <freeze>.
So I don't think it was needing repairs

**Comment by Lego3** [comment]
Did you fire a surgeon before this happened, or had one resigned recently?

**Comment by wolfy1339** [comment]
Not that i'm aware of

**Comment by MarkL1961** [comment]
I tried that and ended up with three surgeons in the room!  

![op error](https://cloud.githubusercontent.com/assets/4965487/5592674/24739662-91d4-11e4-9b78-5b14653fa4bb.png)
If a machine is in urgent need of repair the staff don't usually leave, but the room can lock so no one enters until it is repaired or so I thought.  I had four uses left and another patient entered, so that blows that theory....

**Comment by ms609** [comment]
I am finding that the game often crashes when I move a staff member whilst they are completing a task, then perform another action before they have been relocated.
For example: right click a surgeon whilst he is performing surgery; click the intended destination, press F3 to open the Staff dialog; close the staff dialog.  When surgery is completed, two instances of the transported staff member are briefly visible; often, the instance that finally becomes the staff member becomes frozen and will not move further.

**Comment by wolfy1339** [comment]
Can anyone still reproduce this? As there have been a lot of updates from 0.50 through to the latest git revision and maybe some commits fixed this bug

**Comment by TheCycoONE** [comment]
I'm not sure anyone was ever able to reproduce it, even you.

**Comment by TheCycoONE** [comment]
Should note that the error hints that the cursor left the map area. There have been changes related to cursor to map location binding.

**Comment by TheCycoONE** [comment]
Cannot reproduce.
