### ISSUE TITLE
Difficult camera controls on touch devices

### ISSUE THREAD

**Issue by Dinnerbone** [CorsixTH/CorsixTH#593]
On devices with only touch as input (such as surface pro3 , windows 8.1) it's almost impossible to scroll the game around, and more so to zoom in and out. I'd propose that we take advantage of the touch API introduced in SDL2 and allow two finger gestures to move around + pinching to zoom.

Most other things in the game is usable, it's just the lack of camera controls which makes it fall short! I'm willing to investigate implementation if others agree it will be worthwhile to have (and if those gestures are enough).

**Comment by Lego3** [comment]
Yes, it would certainly be worth it for SDL2. :-)

**Comment by Alberth289346** [comment]
@Dinnerbone  is the issue solved now with sdl2?

**Comment by TheCycoONE** [comment]
I don't think so, we didn't add any gesture support explicitly during the SDL2 transition.

**Comment by wolfy1339** [comment]
@TheCycoOne is right here. I can say that on a similar device touch gestures dont work.

**Comment by lewri** [comment]
May be resolved by PR #1260

**Comment by TheCycoONE** [comment]
Yes, touch support is good now.
