### ISSUE TITLE
Failed to index field black_font 

### ISSUE THREAD

**Issue by sadger** [CorsixTH/CorsixTH#605]
Arch linux 64 bit. Loaded from the most recent master ref 6316114

Loaded a new-ish save from 0.40 save index 86 created using save index 80.

Staff dialog was open when the save was made so would appear immediately on loading. 
Crashes with error.

Error in frame handler: 
./Lua/dialogs/staff_rise.lua:140: attempt to index field 'black_font' (a nil value)
stack traceback:
	./Lua/dialogs/staff_rise.lua:140: in function 'draw'
	./Lua/window.lua:1250: in function 'draw'
	./Lua/game_ui.lua:150: in function 'draw'
	./Lua/app.lua:876: in function <./Lua/app.lua:869>
	(tail call): ?
	./Lua/app.lua:758: in function <./Lua/app.lua:753>
Warning: No event handler for frame

**Comment by TheCycoONE** [comment]
I made the change that caused this issue, sorry. (https://github.com/CorsixTH/CorsixTH/commit/9e962a022715c24b0eab8b51454f4db4019fd6e3)  You wouldn't be able to load the save in 0.40 final either.

**Comment by sadger** [comment]
Ah ok. Removed the SDL2 bit from the title then.

**Comment by Lego3** [comment]
Hmm. What do we do with this type of thing? We create a backwards compatibility fix and include it in a 0.41 release maybe?

**Comment by TheCycoONE** [comment]
@sadger would you mind to attach the problematic save to the ticket.

**Comment by MarkL1961** [comment]
@sadger Can you load your save in an earlier version, save it when you closed the open menu (was it staff wage request) and then load in current version?

**Comment by sadger** [comment]
Save file: https://www.dropbox.com/s/tiyi123les6pdfu/epidemicpatients.sav?dl=0

Can confirm it works pre 9e962a0.

Loading in an older version and closing the dialog and saving again fixes the save and new pop up windows seem to work. Looks like it's affecting saves where the dialog is present when the file was saved. Hope that helps..

**Comment by MarkL1961** [comment]
I would say that is going to be rare, so does it need a fix?

**Comment by MarkL1961** [comment]
I can't think of any games that remember what menus you had open when the save was created.
Would a solution be for the future for us to stop our saves from remembering?
That would also solve the issue where you cannot create a save if the jukebox menu is open and if we had done this earlier would have stopped this issue.

**Comment by sadger** [comment]
It's not really a menu it's the staff wage dialog, you could collapse it down to the fax again on save I guess.

**Comment by MarkL1961** [comment]
That would work as well I guess

**Comment by TheCycoONE** [comment]
Added a pull request to fix this in master.  If we really want a 0.41 patch for this let me know and do not merge this, I'll base it against 0.40 instead and then merge that into master.  My feeling though is that there isn't a strong demand, mostly developers would run into it.
