### ISSUE TITLE
Compiling: alloca is _alloca on Windows (VS)

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#606]
I was trying to compile CorsixTH and CMake failed.
My CMakeError.log: http://qp.mniip.com/p/q4j
From a quick google search, I found that it is named _alloca and not alloca.

**Comment by TheCycoONE** [comment]
Several of us compile on Visual Studio including myself and haven't encountered this problem.  I don't have any files resembling cmTryCompileExec1278357856.vcxproj either. I'm curious what edition of Visual Studio you used and what steps you took to get this error:

**Comment by wolfy1339** [comment]
I'm using Visual Studio Express 2013 for Windows Desktop.
Windows Version: 8.1
I followed this <a href="https://github.com/CorsixTH/CorsixTH/wiki/Setting-Up-Windows-Dev-Software">wiki</a>

**Comment by TheCycoONE** [comment]
Visual Studio Express 2013 is not supported.  Fortunately there is a much more full featured Visual Studio 2013 Community Edition now which should work better for you.

**Comment by wolfy1339** [comment]
Weird, I could compile it before using that same version before.
