### ISSUE TITLE
Problem following Setting Up Windows Dev Software wiki page

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#611]
@J-Shep 

I am testing out the instructions you did thinking if I can build from them anyone can (I have never managed to compile, so I am a complete novice)

I get stuck on point 9.  I got an error, but have no idea where to paste path 2 and 3

Can you help?

![build error](https://cloud.githubusercontent.com/assets/4965487/5790148/78e56516-9e83-11e4-8e75-09c24b3da87a.png)

**Comment by MarkL1961** [comment]
I managed to figure out where I went wrong, my path was slightly out.
Now on to the compiling and I get an error
`  error C1083 Cannot open include file SDL,h: No such file or directory  `
I think I downloaded everything listed, so I am now lost.

**Comment by TheCycoONE** [comment]
That error means your SDL_INCLUDE_DIR is wrong.  You could paste it here, though we'll also need to know your folder layout.

**Comment by J-Shep** [comment]
@MarkL1961 I'm sorry you've had trouble following the Wiki instructions I've made, I will make them clearer.

I want to add a few statements to a cmake script so that if a dev follows the Windows setup wiki they won't need to edit, copy & paste any library paths into the CMake GUI program. CMake could instead detect the presence of a  .../Documents/Github/Libraries directory and then work out what the paths are to CorsixTH's required libraries.

I'm also going to add instructions for compiling an exe with support for movies, using the find_ffmepg find module to remove the need for FFMPEG's many library paths to be provided. And I will add instructions for Freetype 2 support so that this is a complete setup guide.

**Comment by J-Shep** [comment]
There are problems with the provided library directory paths I will correct them now.

**Comment by J-Shep** [comment]
A quick way of checking that a library path is valid is to copy & paste it into a windows command prompt and then use it with the change directory command: cd

I've corrected all the SDL paths, @TheCycoONE made a few mistakes when he updated these paths recently for SDL 2.

**Comment by J-Shep** [comment]
@TheCycoONE Well I guess it wasn't your fault: your zip program didn't just extract the contained folder for SDL 2 and the SDL 2 mixer libraries, it stored them in folders with their zips' names. I've added an instruction now to say that the contained folder should be the top level folder. I will add a screenshot of what the libraries directory should look like when all the zips have been extracted.

**Comment by J-Shep** [comment]
@TheCycoONE What should be done with: msinttypes-r26.zip when its been downloaded? I don't need to do anything with it to compile a CorsixTH exe without movie and Freetype 2 support.

**Comment by J-Shep** [comment]
>> A quick way of checking that a library path is valid is to copy & paste it into a Windows command prompt and then use it with the change directory command: cd

And for library file paths you could use the command for: notepad

**Comment by J-Shep** [comment]
I've finished fixing the library paths having checked that every include directory & library file path is valid.

**Comment by J-Shep** [comment]
@MarkL1961 CMake saves the paths you give it in: .../Github/CorsixTH/build/CMakeCache.txt

**Comment by MarkL1961** [comment]
These are my paths
`  1) C:/Users/Mark/Documents/Github/CorsixTH  `
`  2) C:/Users/Mark/Documents/Github/Libraries/SDL2-2.0.3/include  `
`  3) C:/Users/Mark/Documents/Github/Libraries/SDL2-2.0.3/lib/x86/SDL2.lib  `
`  4) C:/Users/Mark/Documents/Github/Libraries/SDL2_mixer-2.0.0/include  `
`  5) C:/Users/Mark/Documents/Github/Libraries/SDL2_mixer-2.0.0/lib/x86/SDL2_mixer.lib  `
`  6) C:/Users/Mark/Documents/Github/Libraries/lua-5.1.5-Win32/include  `
`  7) C:/Users/Mark/Documents/Github/Libraries/lua-5.1.5-Win32/lua5.1.lib  `

I am not clear where `  msinttypes-r26.zip  ` goes, so my directory looks like this at the moment.

![build error](https://cloud.githubusercontent.com/assets/4965487/5792614/66824e52-9f19-11e4-8dfa-5f531e4db0b7.png)

On the last attempt my errors are

![error](https://cloud.githubusercontent.com/assets/4965487/5792620/9c988290-9f19-11e4-8f4e-6c75c18f64f5.png)

It is likely I am doing something stupid, if that is the case I am sorry.  I am following the instructions to make sure they are idiot proof and I am the idiot when it comes to understanding compiling. :/

**Comment by MarkL1961** [comment]
This is what I see in cmake
Note: Using SDL as renderer (default)
Note: SDL audio is enabled (default)
Note: FFMPEG video is disabled
Note: FreeType2 is disabled

Building CorsixTH
  SDL found
Found Lua library: C:/Users/Mark/Documents/Github/Libraries/lua-5.1.5-Win32/lua5.1.lib
Found Lua: C:/Users/Mark/Documents/Github/Libraries/lua-5.1.5-Win32/lua5.1.lib  
  Lua found
  SDL_mixer found
CMAKE_MODULE_PATH=C:/Users/Mark/Documents/GitHub/CorsixTH/CMake
Configuring done
Generating done

**Comment by MarkL1961** [comment]
I have followed all the steps now several times, if anything I am getting more errors now.

![error](https://cloud.githubusercontent.com/assets/4965487/5793678/a2b790e6-9f44-11e4-998f-d5c36b13a554.png)

**Comment by J-Shep** [comment]
@MarkL1961 I don't have time to help you now, I will try to spot what the problem is later and reply then.

**Comment by MarkL1961** [comment]
I have figured out one problem, although I changed the paths earlier, I had kept on loading the wrong file/solution as one of the mistakes in my paths was to a different corsixth folder.
With that sorted things are progressing in Visual Studio and I now get the following errors
![error](https://cloud.githubusercontent.com/assets/4965487/5793803/88ffc3e4-9f49-11e4-8f80-7a07400c5c67.png)

**Comment by J-Shep** [comment]
The warnings don't matter and are normal, so the only error you have now preventing Visual Studio from compiling a CorsixTH.exe is that it can't find SDL_mixer.h . Your path to the SDL_mixer's "include" source files directory is valid. 

I guess you've done this already but if you haven't please make sure that SDL_mixer.h is in: .../Libraries/SDL2_mixer-2.0.0/include . If you downloaded "SDL2_mixer-2.0.0.zip" instead of "SDL2_mixer-devel-2.0.0-VC.zip" then your "SDL2_mixer-2.0.0" library directory won't have a "include" folder. "SDL2_mixer-devel-2.0.0-VC.zip" is required instead.

**Comment by J-Shep** [comment]
>> msinttypes-r26.zip

@MarkL1961 You don't need this to compile a 32 bit CorsixTH.exe which doesn't support movies & Freetype 2 fonts (required for non English fonts which weren't supported by TH).

**Comment by MarkL1961** [comment]
Thanks, I had the wrong SDL and SDL_mixer, I should have scrolled down the page a little more.

It has now built for me, so my next task is running corsixth in debug -thanks for the assistance :+1:

**Comment by TheCycoONE** [comment]
1. It really doesn't matter where you put the files as long as the cmake variables point to them.
2. msinttypes is a compatibility library because Visual Studio 2012 and earlier were missing the ability to handle C99 int types.  I don't believe it's necessary with VS2013 or higher as MS has corrected the problem.

**Comment by MarkL1961** [comment]
Could we update this page to explain where these come from?

` 5.Copy the following files from your libraries folder into: .../Github/CorsixTH/build/CorsixTH/Debug: ◦SDL2_mixer.dll (lib/x86)
◦SDL2.dll (lib/x86)  `

**Comment by J-Shep** [comment]
@MarkL1961 I will add the paths for these files now.

**Comment by MarkL1961** [comment]
I was wondering why is it you only have to copy over these two dll's and not the lua one for example?

**Comment by TheCycoONE** [comment]
Depending on your system you may have to copy the lua ones as well.  You must have it somewhere in your system's library search path, e.g. system32.  (https://msdn.microsoft.com/en-us/library/7d83bc18.aspx)

**Comment by MarkL1961** [comment]
Ah, in an earlier version of the wiki page you had to download lua for windows or something like that (it has since been removed from the instructions), so it must be down to that.
That might also explain why in cmake it was defaulting the lua to a different location (in program files) than the one in the wiki page

**Comment by J-Shep** [comment]
>> That might also explain why in cmake it was defaulting the lua to a different location (in program files) than the one in the wiki page

@MarkL1961 Yes, using this Lua setup program installs it so that cmake & CorsixTH.exe can find its libraries.

**Comment by J-Shep** [comment]
Because the instruction to use the "Lua for Windows" setup program has been removed I've now added instructions to copy the Lua dynamic link libraries into the debug executable's folder so that it can find them now that they won't be in a Window's system's search path.

**Comment by MarkL1961** [comment]
@J-Shep 
I have found this wiki page very useful and although I had a few problems on the way, I do now have a working exec that I compiled.
I have tried several times in the last few years to do some compiling and was never able to manage it as something or other did not go the way it said it would in the instructions I was following at the time.

The page should prove very useful to other first timers - thanks

**Comment by J-Shep** [comment]
@MarkL1961 I'm glad I've helped you by creating that wiki page. 

@TheCycoONE Thanks for improving it.
