### ISSUE TITLE
cursor trails

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#616]
Whilst editing a room I noticed that the game paused - not sure that it did that before - and that there were red boxes where the cursor had been.  They did go once I stopped editing.
This is with the latest code.

![sdl2error](https://cloud.githubusercontent.com/assets/4965487/5842980/17ff4e1c-a1a1-11e4-8ba3-1a7771a6b4e9.png)

**Comment by MarkL1961** [comment]
Notice also that the bottom menu does not show in the screenshot, I have not edited that out.

**Comment by Glimmer-Man** [comment]
If you are using pull request #381, then read my post there.

**Comment by pwaller** [comment]
Is this #370? If so, I've made a pull request with a potential fix for this here: https://github.com/CorsixTH/CorsixTH/pull/687

**Comment by TheCycoONE** [comment]
I think this is fixed with #687.  Please comment if you're still experiencing issues and I'll reopen this.
