### ISSUE TITLE
0.40: Can't load autosaved games.

### ISSUE THREAD

**Issue by mpmc** [CorsixTH/CorsixTH#618]
__Version:__ 
Using 0.40 SDL on Win7x64:
__Issue:__

No autosaved games load, I first tried to continue a game and got this error
```
You are running the latest version of CorsixTH. 
<LocalisedString> Current value:Error while loading game: D:\Games\CorsixTH\Lua\persistance.lua:234: Cycle while depersisting permanent object key or userdata metatable after 6201 objects (332985 bytes)
```
Then I tried to load an autosave game and got this:-
```
Savegame version changed from 88 (0.40) to 91 (0.40). The save was created using  88 (0.40) 
Savegame version changed from 88 (0.40) to 91 (0.40). The save was created using  88 (0.40) 
Savegame version changed from 88 (0.40) to 91 (0.40). The save was created using  88 (0.40) 
<LocalisedString> Current value:Error while loading game: D:\Games\CorsixTH\Lua\persistance.lua:234: sync fail after 4449 objects (99700 bytes) 
```

Interestingly my manually saved games work fine!

Package of broken SAV files is available for your enjoyment [here!](https://fargalarg.ml/CorsixTH/AutoSave.7z)

**Comment by Frassle** [comment]
Also using 0.40 SDL on Win7x64. Some autosaves load ok, but (this one)[https://drive.google.com/file/d/0BzdXpBSuyzy3TEtPSFN2a2RQZkk/view?usp=sharing] crashes fairly soon after loading it. No gamelog.txt is generated and no console output appears.

**Comment by TheCycoONE** [comment]
I can replicate @Frassle 's freeze on the latest master.  No crash, no console output.

**Comment by Frassle** [comment]
Ah yes, freeze not crash. I should get my terminology correct.

**Comment by TheCycoONE** [comment]
I have determined that there is an infinite path finding loop when the man in the bathroom reaches the door. (tile 58,60)

**Comment by TheCycoONE** [comment]
In particular it keeps calling https://github.com/CorsixTH/CorsixTH/blob/582fee058e/CorsixTH/Lua/humanoid_actions/walk.lua#L179

**Comment by TheCycoONE** [comment]
There seems to be a lot of different issues in this ticket, it would be better to open one ticket per issue.  @Frassle could you open a new ticket about freezing after loading that save game.  Include details like whether the game froze while you played originally or only when loading the save, and what I said about the infinite loop when the man tries to leave the bathroom.

**Comment by Lego3** [comment]
When that type of cycle appears I think the save game is "lost", so to speak. Has anyone encountered this issue recently, or did it go away in 0.5?

**Comment by Alberth289346** [comment]
Recently fixed a bug in loading save games for overlapping objects in a room that may cause this kind of issues. Also, version is quite old, let's close this.

Please make a new issue when you see it happening again.
