### ISSUE TITLE
Game crash on fax creation

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#619]
With this save the game will crash on creation of a fax including a debug fax.  Digits disappear from the bank balance and date on bottom menu bar at the same time.

No error messages displayed.  Using trunk 

https://www.dropbox.com/s/9woclsejvcginz4/02b.sav?dl=0

**Comment by MarkL1961** [comment]
Seems to be limited to autosaves, so is this connected to issue #618 ?

**Comment by MarkL1961** [comment]
Something else I have just noticed is that click on the screen once it has locked makes it all work again and the fax icon appears

**Comment by TheCycoONE** [comment]
What version was the save created on?

**Comment by MarkL1961** [comment]
It  will tell you when you load it, from the top of my head it was 80.  It was one I was using to test the 0.40 betas

**Comment by MarkL1961** [comment]
There is an issue on the forum http://forums.corsixth.com/index.php/topic,5538.msg7898/boardseen.html#new which has a screen shot of the error message.
It looks to be fax related so there might be a connection ?

**Comment by MarkL1961** [comment]
I have now been able to check and the save is 90 (0.40)

**Comment by Alberth289346** [comment]
![ctkhik8](https://cloud.githubusercontent.com/assets/3254232/8398080/9ef88c40-1de2-11e5-9d7e-54508e0dbb27.png)

This error? If so, that was fixed in  #760 for #759

**Comment by Alberth289346** [comment]
Closing it now.
If you referred to another issue, feel free to comment here, and re-open the issue.
