### ISSUE TITLE
Improving how games are manually & automatically saved

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#622]
Hi,

The emails sent by the automated error report system I've nearly finished #445  will need to include the latest saved game for the hospital an error occurred in and a player shouldn't have the inconvenience of having to select their latest saved game for this hospital when this can be done automatically. So to do this automatically a new field will need to be added to a hospital/its world when its started for a level/scenario.

So this new ID field could be used with a hospital's scenario/level name to create an organised saved game hierarchy which would allow error report emails to easily find all the saved games for a hospital which has experienced an error so that they can all then be attached, in case the cause of an error didn't start in the latest saved game.

Saved game dialog tree hierarchy idea:

```
- Campaign:
   -  Level 1:
       - Hospital created on: 23/1/2015:
          - Auto saves:
            * 23/1/2015: 15:01:00
            * 23/1/2015: 15:00:30
            * 23/1/2015: 15:00:00
          - Manual saves:
            * 23/1/2015: 15:01:25 : My second manually saved game.
            * 23/1/2015: 15:01:15 : My first manually saved game.
+ Singleplayer Scenarios
+ Multiplayer Saved Games
```

This new hierarchy would also allow there to be no limit to the number of auto saves a player can have allowing them to have the most frequent auto save rate their computer can handle without performance issues because their auto saves for a hospital wouldn't override auto saves for another hospital and having more auto saves wouldn't make finding auto saves for another hospital difficult.

Allowing auto saves to occur more often would also benefit error report emails because they would be more likely to have an attached saved game close to the time when the error occurred with a game state closer to the game state which caused the error.

The in game load saved game drop down menu could display the 5 most recently manually and 5 most recently automatically, saved games for the hospital a player is playing.

I will add a "Autosave Interval (Seconds):" option to the options menu.

**Comment by J-Shep** [comment]
@admdly While working on two new buttons for saved game UI dialogs #369, have you done any work for one/both of these saved game enhancement ideas?

**Comment by TheCycoONE** [comment]
Your hierarchy probably doesn't have unique enough names and doesn't appear to contain the new ID you were discussing above.  If we're going to have globally unique hospital identifiers for email they almost certainly have to be guids.

If we're going to save games that way automatically there needs to be a way or mechanism to clean up old games.

**Comment by J-Shep** [comment]
>> If we're going to have globally unique hospital identifiers for email they almost certainly have to be guids.

@TheCycoONE Thanks for this suggestion I will do this.

>> Your hierarchy probably doesn't have unique enough names...

@TheCycoONE  I now think this should be the hierarchy:

```
- Campaign:
   -  Level 4:
        - Auto:
          * (2) 23/1/2015: 15:01:00
          * (2) 23/1/2015: 15:00:30
          * (2) 23/1/2015: 15:00:00
        - Manual:
          * (2) 23/1/2015: 15:01:25: My second manually saved game.
          * (2) 23/1/2015: 15:01:15: My first manually saved game.
```

So a level's/scenario's different hospitals wouldn't each have their own saved games directory because a player is unlikely to want to keep saved games for a hospital they've won a level/scenario with or abandoned. 

A saved game's hospital's ID would be shown in brackets in its description and I think there should be a new saved game cache directory containing .cache text files for each saved game, having the name of an associated saved game and containing the value of its ID field so that this can be obtained without loading all the other variable's for a saved game's state first. This cache file could have other saved game fields and/or meta data added to it in future if required.

>> If we're going to save games that way automatically there needs to be a way or mechanism to clean up old games.

@TheCycoONE Well I think all of a hospital's auto saved games should be deleted when a player has won the hospital's level/scenario and I guess there will have to be a maximum number of auto saves kept for each hospital. 

@admdly If your saved game deletion button will delete one or more selected saved games, I could implement a button to delete all the saved games for a hospital which has a given ID number.

**Comment by MarkL1961** [comment]
Would it not be simpler to allow the player the chance to select which save or saves they send?
I am not sure I like the idea of the game doing this without the player taking some part in the process.  There is also privacy laws to think about, even windows reporting gives you the option to not send information.

**Comment by J-Shep** [comment]
>> Would it not be simpler to allow the player the chance to select which save or saves they send?

Finishing the implementation of this auto error reports enhancement would be simpler and quicker if no saved games changes had to be included but I don't want players to have the inconvenience of having to do an extra input step which could be automated instead, in what is meant to be a quick and convenient to use automatic error reporting process.

>> There is also privacy laws to think about, even windows reporting gives you the option to not send information.

@MarkL1961  Thanks for raising this important issue, I will remove the only 2 personal details which are in my current implementation of auto error reports.

The error report dialog will have a button for choosing not to send a report:

![error report](https://cloud.githubusercontent.com/assets/6353342/5987841/497c7c62-a93a-11e4-8975-747554cad185.png)

The only personal information which my current implementation of reports includes is contact information and the IP address a player had (they may have dynamic IP address) when they sent a report:

![email](https://cloud.githubusercontent.com/assets/6353342/5987930/75049366-a93e-11e4-9cd7-4b2a7e88bce1.png)

I will remove this personal information so that then all the data which will be included in a error report email will only be about the responsible code and the game state when the error occurred. Plus the identity of the player who's game created this data would be anonymous. 

So I think its safe to say there would be no potential privacy law issues when I've removed the personal information currently in error reports.

**Comment by J-Shep** [comment]
I will try to have my code for this issue ready to be submitted in a pull request by Tuesday.

I'm sorry I've spent very little time doing CorsixTH programming this week despite having some important tasks to do. I've been playing PC games in my free time at home instead of programming things for games.

I know I'm responsible for two important tasks: this task and implementing a LAN multiplayer mode #386 . I will spend a lot more time doing CorsixTH programming next week.

**Comment by Lego3** [comment]
The dialog looks nice to me. :-) Possibly we could suggest an e-mail address as contact info? And also possibly say somewhere that it's still good to create an issue in our issue tracker anyway.

**Comment by J-Shep** [comment]
>> Possibly we could suggest an e-mail address as contact info?

@Lego3 I wasn't going to ask for any personal information after @MarkL1961 raised the issue of personal data protecting privacy laws, like my country's Data Protection Act and its data protection principles. But I guess just asking for an email address shouldn't cause any legal issues.

>> And also possibly say somewhere that it's still good to create an issue in our issue tracker anyway.

@Lego3 I will add this.

@Lego3 @TheCycoONE As leaders of the development of CorsixTH feel free to tell me what you want me to do and not do when I'm working on something for it. I know I'm prone to scope creep and maybe my pull request for this issue shouldn't include any saved game changes, players could just be asked to manually select a saved game to be attached. But I still intend to do make CorsixTH auto attach all saved games for a hospital which has experienced an error unless you guys tell me this isn't worth working on.

**Comment by MarkL1961** [comment]
@J-Shep If you are asked for something and choose to give it there are no issues with data protection, well, as far as I am aware for UK.  It only becomes a problem if you take personal information without the persons explicit knowledge.

**Comment by J-Shep** [comment]
I'm not going to have time to implement any of these improvements myself in the near future because I have lots of other more important enhancements I want to work on first like the  auto error reporting feature, an auto Lua error patching feature and my long term task of implementing multiplayer support.

So someone else could work on implementing improvements for this issue if they want.

**Comment by tobylane** [comment]
No longer in our roadmap. Monthly autosaves are typically enough.
