### ISSUE TITLE
game crash: Handyman arrived is on call but not arriving to the designated room

### ISSUE THREAD

**Issue by ms609** [CorsixTH/CorsixTH#624]
![image](https://cloud.githubusercontent.com/assets/1695515/5879713/65b9dfee-a329-11e4-92c3-c4f8c18a7993.png)

![image](https://cloud.githubusercontent.com/assets/1695515/5879747/b099634a-a329-11e4-91b3-a551e3090a5f.png)

I'm afraid I can't work out how to locate savegame files.  Let me know, and I will upload them.

**Comment by TheCycoONE** [comment]
Save games by default are in the same location as the configuration file: https://github.com/CorsixTH/CorsixTH/wiki/Configuration-File

**Comment by TheCycoONE** [comment]
Could you also let us know what version you're using and whether this is a fresh game or a save loaded from an earlier version?

**Comment by adrianopol** [comment]
Hello, the same problem (v0.40; Gentoo GNU/Linux; game was loaded from v0.40-rc3).

    Warning: A patient supposedly sitting down was not, trying to recover assuming he/she is standing.
    Destroying Inspector
    An error has occured!
    Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
    Running: The timer handler.
    A stack trace is included below, and the handler has been disconnected.
    Lua/humanoid_actions/walk.lua:227: attempt to index field 'queue' (a nil value)
    stack traceback:
      Lua/humanoid_actions/walk.lua: in function 'action_walk_raw'
      Lua/humanoid_actions/walk.lua:187: in function 'timer_function'
      Lua/entity.lua:215: in function 'tick'
      Lua/entities/staff.lua:146: in function 'tick'
      Lua/world.lua:1103: in function 'onTick'
      Lua/app.lua:852: in function 'dispatch'
      Lua/app.lua:753: in function <Lua/app.lua:748>

Saved game: https://yadi.sk/d/ToyvUoGlgfHns.

**Comment by TheCycoONE** [comment]
Thanks adrianopol

**Comment by Ben22640** [comment]
Hello,

I got the same error too (Windows 10, CorsixTH 0.50, game was loaded from 0.50) :

Created game with savegame version 105.
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\room.lua:317: Handyman arrived is on call but not arriving to the designated room
stack traceback:
	[C]: in function 'assert'
	C:\Program Files\CorsixTH\Lua\room.lua:317: in function <C:\Program Files\CorsixTH\Lua\room.lua:285>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:356: in local 'on_next_tile_set'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:190: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:218: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>


[Save.zip](https://github.com/CorsixTH/CorsixTH/files/154557/Save.zip)

**Comment by TheCycoONE** [comment]
@ElvarT did you move the slicer mugmuggy referred to?

**Comment by ElvarT** [comment]
@TheCycoONE : Yes, moving the "slicer" one tile away from the pharmacy wall, from (55-56,95-96) to (56-57,95-96), seems that both the pharmacy plant and the slicer are serviced without problems.

**Comment by mugmuggy** [comment]
I had a search and couldn't find the handyman_position being updated anywhere besides the Machine constructor. You have to go back to door phase in editing a room to be able to update the handyman_position.
