### ISSUE TITLE
Windows states there is an error and must close program

### ISSUE THREAD

**Issue by DuckyDM** [CorsixTH/CorsixTH#625]
I have tried DirectX, SDL, and OpenGL. All have the same results. After a few minutes, Windows states that it has stopped working and must be closed. I have tried doing different things to see if that was the issue. I found that it does not matter what I do, it will have the same error. I am using CorsixTH 0.4 on Windows 7 64. Please help!

Ducky

**Comment by DuckyDM** [comment]
a new error box came up today

<a href="http://s133.photobucket.com/user/crystilian/media/corsixth_error_zpsthubyurd.jpg.html" target="_blank"><img src="http://i133.photobucket.com/albums/q73/crystilian/corsixth_error_zpsthubyurd.jpg" border="0" alt=" photo corsixth_error_zpsthubyurd.jpg"/></a>

**Comment by TheCycoONE** [comment]
The error in your screenshot is known with directX and movies, if you turn movies off or use SDL you shouldn't run into it.  Your first issue is something else, but we don't really have anything to go on.

**Comment by Alberth289346** [comment]
Video backend was moved to SDL2, discarding all other video backends. This renders the issue obsolete.
