### ISSUE TITLE
Patient with EXIT sign is stuck in threatment room, and blocks the room

### ISSUE THREAD

**Issue by eeerlend** [CorsixTH/CorsixTH#635]
**What steps will reproduce the problem?**
1. Threat a patient
2. Wait for the patient to leave the room.

**What is the expected output? What do you see instead?**
A patient should walk out of the room when finished with the threatment. Instead, the patients in some cases get stuck in the threatment room, with an exit sign over her/his head. The room is then blocked - no one can use it, and the room itself cannot be deleted.

**What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?**
0.40

**What operating system / compile settings are you using?**
Mac OSX Yosemite

**What level was this on (e.g. "Demo level", "Full game level 12")?**
Custom level, "St. Peters Near Cawley"

**Comment by Alberth289346** [comment]
A little very late, but do you have a game log, or a save game just before the event?

Without a way to see what went wrong (or better, a savegame that replicates the behavior, there is very little that can be done.

**Comment by lewri** [comment]
Not enough info to continue this issue, and time may have lapsed too long.
