### ISSUE TITLE
Binaries for GNU/Linux

### ISSUE THREAD

**Issue by ezeenova** [CorsixTH/CorsixTH#638]
Any chance you could provide precompiled binaries for GNU/Linux for 0.40?

**Comment by Lego3** [comment]
Unfortunately I believe that our main issue right now is that none of us know how to create such packages...

**Comment by Lego3** [comment]
Good ones that is.

**Comment by TheCycoONE** [comment]
@ezeenova GNU/Linux is a little bit general.  In the past members of the respective distributions provided their own packages for CorsixTH.  PlayDeb for instance does have a 0.40 package.

http://www.playdeb.net/app/corsix-th (Ubuntu) - 0.40
https://aur.archlinux.org/packages/corsix-th (Arch Linux) - 0.40
http://packages.gentoo.org/package/games-simulation/corsix-th (Gentoo) - 0.30
http://software.opensuse.org/download.html?project=games&package=CorsixTH (Open SUSE) - ???
http://rpmfind.net//linux/RPM/mageia/cauldron/x86_64/media/core/release/corsixth-0.40-1.mga5.x86_64.html (Mageia) - 0.40

Hopefully that just about covers your needs?  If not please bug your distribution packagers.

**Comment by ezeenova** [comment]
My (extremely particular) usecase is that I'm writing an install script for TH for Lutris, an open source gaming platform (think open source Steam, sorta). The install script would download the corsix-th binary for the user, ask them to point the installer at the TH data files, and then handle the rest of the installation automagically. We can build and host the binary ourselves, but using one provided by the project in question is preferable. Anyway, I'm looking into setting up a build environment for corsix-th right now, so if I'm able to build something portable enough for Lutris, maybe you'd be interested in adding it to your official downloads?

**Comment by Lego3** [comment]
Definitely

**Comment by ezeenova** [comment]
I added the binary to my fork: https://github.com/ezeenova/CorsixTH/raw/master/CorsixTH-0.40-GNU-Linux.tar.gz
I'm not going to send a pull request since you don't keep the other binaries in the tree, it's just a convenient place to put it.

It's built with GCC 4.7 on Debian Wheezy, with statically linked FFmpeg, SDL, and SDL_mixer. FFmpeg is stripped down to only support the codecs CorsixTH needs (smacker and smackaud), and with lots of unnecessary components disabled, so both size and number of dependencies kept to a minimum. It should run on any Linux Standard Base compliant distro with GCC >= 4.7. I've only compiled it for amd64 architecture, but if there is demand for a i386 version I can build that as well.

I'll document the build process on the Wiki, if you do add it to your release binaries.

**Comment by TheCycoONE** [comment]
I've added your tarball to the releases page.  Thanks!

**Comment by TheCycoONE** [comment]
@ezeenova I don't know if you follow the mailing list, but I started a CorsixTH\deps repository with all the prebuilt dependencies.  You must have already done all that work for this, if you have time would you mind adding the 0.40 x64 (amd64) dependencies.

If that's something you're interested in doing, please let me know here or on the mailing list and I'll make you a contributor for that repository.
