### ISSUE TITLE
Conversion/Integration of MapEdit into Game UI

### ISSUE THREAD

**Issue by sgtbigman** [CorsixTH/CorsixTH#639]
I briefly mentioned this to @TheCycoONE on the IRC channel, but wanted to make it more official/formal, following the guidelines for contributing. 

I have begun work on bringing the Map Editor into the native game's UI. This will allow users to more easily create their own maps without needing a separate application and its dependencies. @TheCycoONE had begun work on this in the past and was kind enough to give me the url to his branch. I have integrated his work into my own branch and will continue to push updates to my branch as often as I can.

Please let me know of anything you'd like to see in the native map editor or of anything else that I may have missed with this post.

Thanks.

**Comment by TheCycoONE** [comment]
An initial goal of feature parity with the old MapEdit is probably a good target.  If you get to it after that I would like to see the level edit functionality integrated into the Map Editor too, my thought was that one of the map edit menu options would bring up all of the level configuration.

**Comment by MarkL1961** [comment]
there are a couple of suggestions that have been made in the past [here](https://github.com/CorsixTH/CorsixTH/wiki/Future-Options#map-editor).
To add to that it would be nice to see a birds eye view of your map in miniature at the side, or to have the ability to zoom in and out.  I usually end up saving it, loading it in the game. just to see if I need to add or change something.

**Comment by Alberth289346** [comment]
Current version (unfinished, feel free to work further on it) https://github.com/CorsixTH/CorsixTH/tree/map_editor2

commit 0ff9194ceca092cbb1567071185dd6405ebf845e contains a list of known things that need to be addressed (some small, some large).

List from MarkL above:
- [x] 1300 Premade templates that the editor can add to the map for you in one go. Things like complete windows, complete doors, complete helipads and so on. (done)
- [ ] 1301 An automatic command in the map editor to add patches of worn hedges in long streaks of pristine hedges.
- [ ] 1304 An option to let the map editor automatically manage the borders for outside walkways and ponds.
- [ ] Addition by MarkL: birds eye view of your map in miniature at the side, or to have the ability to zoom in and out (may be done as well, as the new map editor is already in the game itself, but needs checking)

**Comment by Alberth289346** [comment]
https://github.com/Alberth289346/CorsixTH/tree/map_editor3  adds copy (RMB-drag) and paste (LMB click or drag) functionality.

- commit 197ea427fe7757c8d4235ff3258571c3bef41a44 fixes some minor problems in map editor2.
- commit 6f33ecacc14130a7534c973c9748c55265e9205c fixes function documentation generation.
- commit c1ece7cd6c4225fb181550245e37c3e9a8db568f could be refactored to belonging in map editor2, but not sure it's relevant enough.
- commit 35654ecfd92624000953dab95db995832f4d8b8e should be mergeable with some other commit
- other 4 commits add the functionality.

**Comment by TheCycoONE** [comment]
@Alberth289346 can you rebase and push these changes into the map_editor2 branch on CorsixTH. Consider it a development branch except that we share it (so don't do any force pushes).

**Comment by TheCycoONE** [comment]
Zoom is now fully supported, my last commit fixes the cursor for it.

**Comment by Alberth289346** [comment]
copy/paste rebased and pushed onto corsix/map_editor2 branch

**Comment by MarkL1961** [comment]
I thought I would give this a test and got this error, which you may already be aware of.

Created game with savegame version 105.
Error in buttonup handler: 
C:\CTH Map Editor\Lua\game_ui.lua:50: use of undeclared variable 'UIMapEditor'
stack traceback:
	[C]: in function 'error'
	C:\CTH Map Editor\Lua\strict.lua:43: in function <C:\CTH Map Editor\Lua\strict.lua:39>
	C:\CTH Map Editor\Lua\game_ui.lua:50: in function 'constructor'
	C:\CTH Map Editor\Lua\class.lua:76: in function 'GameUI'
	C:\CTH Map Editor\Lua\app.lua:501: in function 'loadLevel'
	C:\CTH Map Editor\Lua\app.lua:1273: in function 'mapEdit'
	...\CTH Map Editor\Lua\dialogs\resizables\main_menu.lua:121: in function 'callback'
	C:\CTH Map Editor\Lua\window.lua:682: in function 'handleClick'
	C:\CTH Map Editor\Lua\window.lua:1475: in function 'onMouseUp'
	C:\CTH Map Editor\Lua\window.lua:1459: in function 'onMouseUp'
	C:\CTH Map Editor\Lua\ui.lua:623: in function <C:\CTH Map Editor\Lua\ui.lua:610>
	(tail call): ?
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in timer handler: 
C:\CTH Map Editor\Lua\world.lua:1060: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\world.lua:1060: in function 'onTick'
	C:\CTH Map Editor\Lua\app.lua:882: in function <C:\CTH Map Editor\Lua\app.lua:879>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in motion handler: 
C:\CTH Map Editor\Lua\app.lua:944: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\app.lua:944: in function <C:\CTH Map Editor\Lua\app.lua:943>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in keydown handler: 
C:\CTH Map Editor\Lua\app.lua:920: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\app.lua:920: in function <C:\CTH Map Editor\Lua\app.lua:919>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in keyup handler: 
C:\CTH Map Editor\Lua\app.lua:924: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\app.lua:924: in function <C:\CTH Map Editor\Lua\app.lua:923>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in active handler: 
C:\CTH Map Editor\Lua\app.lua:952: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\app.lua:952: in function <C:\CTH Map Editor\Lua\app.lua:951>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
Error in textediting handler: 
C:\CTH Map Editor\Lua\app.lua:928: attempt to index field 'ui' (a nil value)
stack traceback:
	C:\CTH Map Editor\Lua\app.lua:928: in function <C:\CTH Map Editor\Lua\app.lua:927>
	(tail call): ?
	C:\CTH Map Editor\Lua\app.lua:783: in function <C:\CTH Map Editor\Lua\app.lua:778>
downloaded CTH-20151019-map_editor2-c0a33e68d6.zip            19-Oct-2015 16:41  
from http://www.armedpineapple.co.uk/cth/builds/

**Comment by Alberth289346** [comment]
do you have the file "CorsixTH/Lua/dialogs/resizables/map_editor.lua" ?

https://github.com/CorsixTH/CorsixTH/blob/map_editor2/CorsixTH/Lua/dialogs/resizables/map_editor.lua

**Comment by MarkL1961** [comment]
Yes

**Comment by MarkL1961** [comment]
Line 50 reads `  local FLIP_H = DrawFlags.FlipHorizontal << 8  `

**Comment by Alberth289346** [comment]
The error is at game_ui.lua, line 50, which says "self:addWindow(UIMapEditor(self))"
That "UIMapEditor" is in the map_editor.lua file, at line 41

So apparently, it doesn't see the new file, but it doesn't complain about it?
I have no idea what is wrong at this time :(

**Comment by MarkL1961** [comment]
I commented out the `  << 8  ` and it now loads.

**Comment by Alberth289346** [comment]
Hmm, change "<< 8" to "* 256". What Lua version are you using?

**Comment by MarkL1961** [comment]
that works too.  I am using the files that came in the zip
There is lua 5.1 installed from ages ago, would that make a difference?

**Comment by Alberth289346** [comment]
Apparently, the << is new, I'll change it to "* 256" instead, thanks for the report

**Comment by TheCycoONE** [comment]
Added support for showing the parcel number overlay on the map when a parcel button is pressed. This overlay is now a live view so that changes in the map editor are reflected.

I do have some concerns with performance, caching might be necessary (there is a cache mechanism built into getCellFlags that may work if we can reset it appropriately as the map is updated).

**Comment by TheCycoONE** [comment]
Also what's currently labeled as Parcel 0 is actually the delete parcel button.

**Comment by MarkL1961** [comment]
@TheCycoONE   I noticed that performance was slow when trying it out last night.  I select a floor tile and then select a tile to drag out an area and it seems slow to update, it was almost as if I had something else running in the background - which I didn't. I can't think of another way to describe it other that it was very juttery.

**Comment by TheCycoONE** [comment]
@MarkL1961 I've seen that too. We'll need to do a performance pass on this once it's all working.

**Comment by sgtbigman** [comment]
Wow, this editor has really come along, great job!

As to the slow performance comment, I only notice it when trying to create a large area with the selected tile. (Although, as I am typing this, I'm noticing lag while I type, which may be related as the map editor is running in the background...)

Anyways, awesome work!

**Comment by TheCycoONE** [comment]
The map editor is now capable of setting the number of players for the map (1-4) as well as the starting camera and heliport locations for each of them.

If no one has any objections I'd like to merge this branch into master soon. I think that while there are still nice to haves that are not done the new map editor is usable and better than what we have now (nothing).

**Comment by Lego3** [comment]
I agree

**Comment by TheCycoONE** [comment]
Apparently the new map editor isn't setting flags like buildable, passable and so forth, so it's not ready to merge yet.

**Comment by TheCycoONE** [comment]
Thanks for fixing the map flags @Alberth289346. I made some simple maps and they're working in game. One odd thing that's happening is that when I save and then load a few of the tiles seem to change. 

In the map editor before saving:
![corsix-map-road-before](https://cloud.githubusercontent.com/assets/823433/12737352/93e3b520-c925-11e5-8b9b-288000124f6a.png)

In the map editor after loading the save (or in game):
![corsix-map-road-after](https://cloud.githubusercontent.com/assets/823433/12737375/c8d6e068-c925-11e5-8960-5df62de7f5e9.png)

**Comment by Alberth289346** [comment]
The mirror bit got flipped?

**Comment by TheCycoONE** [comment]
The sprites that don't work are the ones with the FlipHorizontal drawing flag enabled. I took a look at the map format, as well as the old map editor and the maps shipped with the game and I can conclude that flipped sprites have never been supported in maps.
In the future we could make our own map format with an extended tile set and/or support for draw flags, but for now we can just drop these flipped tiles.

**Comment by TheCycoONE** [comment]
The map editor has been merged.
