### ISSUE TITLE
new function: spacebar to center view

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#645]
I added a new function in my forked branch:

when there are announcements for missing staff or handyman in any room, the player can press spacebar to center view on the room, so that he can find the room immediately instead of searching for the room.

For example, if you have many GP offices all over the place, when you hear "doctor required in GP office", you no longer need to search though every GP office to find out which one is requesting.

**Comment by MarkL1961** [comment]
What happens if you are editing a room when one of these announcements happen?
Will my object rotate or will my view centre on the cause of the announcement?

https://github.com/CorsixTH/CorsixTH/wiki/Hotkeys#edit-room--place-objects-window

**Comment by xuancong84** [comment]
Oops, I did not realize that spacebar is also used in rotating objects when setting rooms. 

In principle, the key handler should be stored and disabled, then after finishing the room, restore the old key handler for center view. 

Cheers,
Xuancong
