### ISSUE TITLE
Graphics freezes on the first patient

### ISSUE THREAD

**Issue by Andy51** [CorsixTH/CorsixTH#646]
What steps will reproduce the problem?
1. Started a new game, built a reception and GP, opened the hospital
2. Waited for the first patient to come out of GP

What is the expected output? What do you see instead?
Expecting the incoming fax icon.
Just as soon as the tip guy pops up from the bottom, my score disappears and the graphics freezes, while the game continues to run (i can hear sounds of doctors activity)
Also, if I manage to blindly "catch" someone with invisible mouse pointer, the graphics unfreezes again and seems to run normally. No error messages in console.
![screenshot1](https://cloud.githubusercontent.com/assets/4835002/5983851/e36e911a-a8e1-11e4-8e3e-2b1bc2dcfce6.jpg)

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
9cc12540

What operating system / compile settings are you using?
Win7 x64, buit with MSVC2013CE, SDL 2.0.3, SDL_mixer 2.0.0, Lua 5.1.5, all defaults

What level was this on (e.g. "Demo level", "Full game level 12")?
Verified with GOG level1 and Demo level

I think this might be related to #619 or #482, though I have 100% reproduce rate with the steps provided

**Comment by TheCycoONE** [comment]
Yes, definitely sounds like a clipping bug to me - this is the first I've heard of it affecting windows but it makes sense that it would.  Agreed @jorgenpt ?

**Comment by xuancong84** [comment]
Yup, I also encounter the same problem, on the newest master branch (2015.1.29). Essentially, the fax sliding icon cannot appear.
This bug is fatal.

**Comment by Andy51** [comment]
Yes, i confirm it unfreezes when pressing alt+enter as well
I have also merged @pwaller #631 but that did not fix the freeze. I guess i would try to find what is going on in the code then..

**Comment by xuancong84** [comment]
I have worked around it successfully!
In Lua/dialogs/message.lua, comment out the two lines of canvas:setClip(...)
Since this animation is very short and fast, the imperfection is hardly perceivable, at least to me.

Good luck!

**Comment by Andy51** [comment]
@xuancong84 that helped avoiding the freeze for me too. So it actually is a clipping issue.

**Comment by TheCycoONE** [comment]
Thanks for that @xuancong84 
It's still very likely the problem is in our own code, but that helps us focus.

**Comment by xuancong84** [comment]
Maybe you are right. The old code also does clipping. Why doesn't it cause any problem then?

Cheers,
Xuancong

**Comment by Andy51** [comment]
@xuancong84 because the old code was mapped 1:1 to SDL API, which is not the case right now
