### ISSUE TITLE
2 enhancements: one for dynamic info display during pause, the other for spacebar to center view

### ISSUE THREAD

**Issue by xuancong84** [CorsixTH/CorsixTH#648]
Hi CycoOne, please check whether I am doing commit/push correctly this time, I have already created the pull request.

1.
a small change: when paused, the bottom panel will still display object info if mouse is moved over an object, previously it only displays the tag "PAUSED" so that you cannot actual play the game when paused.

2.
added a new function: when there is an announcement such as "doctor required in GP office", the player can now press "tab" to center view or press "spacebar" to scroll to view, so that he does not need to check one-by-one which GP office is missing a doctor when there are many GP offices around the hospital.
It applies to nurses and handyman urgent repair as well.

**Comment by Alberth289346** [comment]
This was #644 and #647 (both closed unfinished), or are there other PRs ?
Do you have plans to continue working on this?

(If so, please add the numbers of the pull requests here, so it's easier to find them again.)

**Comment by TheCycoONE** [comment]
I believe #644 was open before this issue and #647 was opened in conjunction with it. Nothing to be done for this issue.
