### ISSUE TITLE
Grid appearing when started in fullscreen mode

### ISSUE THREAD

**Issue by Andy51** [CorsixTH/CorsixTH#653]
What steps will reproduce the problem?
1. Start a new game in fullscreen mode

What is the expected output? What do you see instead?
Expecting the same level view as in windowed mode. I get this fancy grid effect instead:
![screenshot4](https://cloud.githubusercontent.com/assets/4835002/5989528/349727b8-a99c-11e4-9828-5f17de2133df.jpg)
That grid disappears when i zoom in or out

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
fc3eb27

What operating system / compile settings are you using?
Win7 x64, buit with MSVC2013CE, SDL 2.0.3, SDL_mixer 2.0.0, Lua 5.1.5, all defaults

What level was this on (e.g. "Demo level", "Full game level 12")?
Any

**Comment by Andy51** [comment]
OK, after some meddling with the code i have an idea this is most probably just a texel bleeding issue. Conclusion is, we should never ever render any sprites with SDL_RenderSetLogicalSize not equal to the render target, as happens in our case when we use fake fullscreen resolution (we dont actually chage the screen resolution when going fullscreen) so even though my SDL logical size is set to 720p, it actually renders on 1080p sized render target for my desktop.

Considering all the above is correct, the simple solution would be to switch to 'real' fullscreen mode, plus that would solve some of the zooming artifacts in fullscreen. Or alternatively we might apply the same rendering technique as when zooming (right now the issue is present only with zoom=0)

**Comment by TheCycoONE** [comment]
I don't get artifacts on full screen anymore, do you still see them @Andy51 ?

**Comment by Andy51** [comment]
Yes, just checked on ee23df1f and there were no artifacts. Probably zooming changes fixed that (eliminated rendering fastpath when zoom=0)?
