### ISSUE TITLE
TravisCI failing on busted tests

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#658]
PR #413 introduced unit testing with busted, however the travis ci script seems to be failing.  It looks like the lpath is not being interpreted properly.

0.01s$ cd $TRAVIS_BUILD_DIR/CorsixTH/Luatest

The command "cd $TRAVIS_BUILD_DIR/CorsixTH/Luatest" exited with 0.

0.04s$ busted --lpath=../Lua/?.lua

●●

0 successes / 0 failures / 2 errors / 0 pending : 0.0 seconds

Error → ./class_test_base.lua @ 27

./spec/entities/object_spec.lua

./class_test_base.lua:27: module 'class' not found:

no field package.preload['class']

no file '../Luaclass.lua'

no file '/usr/local/share/lua/5.1//class.lua'

no file '/usr/local/share/lua/5.1//class/init.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class/init.lua'

no file '/usr/local/share/lua/5.1//class.lua'

no file '/usr/local/share/lua/5.1//class/init.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class/init.lua'

no file '/usr/share/lua/5.1//class.lua'

no file '/usr/share/lua/5.1//class/init.lua'

no file './class.lua'

no file '/usr/local/share/lua/5.1/class.lua'

no file '/usr/local/share/lua/5.1/class/init.lua'

no file '/usr/local/lib/lua/5.1/class.lua'

no file '/usr/local/lib/lua/5.1/class/init.lua'

no file '/usr/share/lua/5.1/class.lua'

no file '/usr/share/lua/5.1/class/init.lua'

no file './csrc/class.so'

no file './csrc/class/class.so'

no file '/usr/local/lib/lua/5.1//class.so'

no file '/home/travis/.luarocks/lib/lua/5.1//class.so'

no file '/usr/local/lib/lua/5.1//class.so'

no file '/home/travis/.luarocks/lib/lua/5.1//class.so'

no file './class.so'

no file '/usr/local/lib/lua/5.1/class.so'

no file '/usr/lib/x86_64-linux-gnu/lua/5.1/class.so'

no file '/usr/lib/lua/5.1/class.so'

no file '/usr/local/lib/lua/5.1/loadall.so'

Error → ./class_test_base.lua @ 27

./spec/class_spec.lua

./class_test_base.lua:27: module 'class' not found:

no field package.preload['class']

no file '../Luaclass.lua'

no file '/usr/local/share/lua/5.1//class.lua'

no file '/usr/local/share/lua/5.1//class/init.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class/init.lua'

no file '/usr/local/share/lua/5.1//class.lua'

no file '/usr/local/share/lua/5.1//class/init.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class.lua'

no file '/home/travis/.luarocks/share/lua/5.1//class/init.lua'

no file '/usr/share/lua/5.1//class.lua'

no file '/usr/share/lua/5.1//class/init.lua'

no file './class.lua'

no file '/usr/local/share/lua/5.1/class.lua'

no file '/usr/local/share/lua/5.1/class/init.lua'

no file '/usr/local/lib/lua/5.1/class.lua'

no file '/usr/local/lib/lua/5.1/class/init.lua'

no file '/usr/share/lua/5.1/class.lua'

no file '/usr/share/lua/5.1/class/init.lua'

no file './csrc/class.so'

no file './csrc/class/class.so'

no file '/usr/local/lib/lua/5.1//class.so'

no file '/home/travis/.luarocks/lib/lua/5.1//class.so'

no file '/usr/local/lib/lua/5.1//class.so'

no file '/home/travis/.luarocks/lib/lua/5.1//class.so'

no file './class.so'

no file '/usr/local/lib/lua/5.1/class.so'

no file '/usr/lib/x86_64-linux-gnu/lua/5.1/class.so'

no file '/usr/lib/lua/5.1/class.so'

no file '/usr/local/lib/lua/5.1/loadall.so'

The command "busted --lpath=../Lua/?.lua" exited with 2.

**Comment by Lego3** [comment]
Strange. In the pull request itself it succeeded right?

**Comment by TheCycoONE** [comment]
It did, and it succeeded on my machine with the latest master.  There was a conflict in the .travis.yml file but I don't think I changed anything that would have broken it.
