### ISSUE TITLE
Vomit in a room (editing it causes an error)

### ISSUE THREAD

**Issue by mrtnptrs** [CorsixTH/CorsixTH#66]
I think this is already reported here: http://code.google.com/p/corsix-th/issues/detail?id=1338&q=vomit%20in%20room But I now also know how to reproduce this:

1.Make a blueprint of a room and make sure a patient which is going to vomit is already standing at the blueprint or will stand (walk to the blueprint) at the blueprint after you made the selection of the blueprint, but before you confirmed it.
2. Confirm the blueprint.
3. The patient will vomit at the blueprint and the room can be builded over it.

And when I want to edit the room, I get this nice error:
Savegame version is 78 (0.30), originally it was 78 (0.30)
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:227: attempt to index field 'orientations' (a nil value)
stack traceback:
    [C]: in function 'sort'
    C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:226: in function 'addObjects'
    C:\Program Files\CorsixTH\Lua\dialogs\edit_room.lua:603: in function 'returnToDoorPhase'
    C:\Program Files\CorsixTH\Lua\dialogs\edit_room.lua:187: in function 'callback'
    C:\Program Files\CorsixTH\Lua\window.lua:645: in function 'handleClick'
    C:\Program Files\CorsixTH\Lua\window.lua:1406: in function 'onMouseUp'
    C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:449: in function 'onMouseUp'
    C:\Program Files\CorsixTH\Lua\window.lua:1390: in function 'onMouseUp'
    C:\Program Files\CorsixTH\Lua\ui.lua:703: in function 'dispatch'
    C:\Program Files\CorsixTH\Lua\app.lua:739: in function <C:\Program Files\CorsixTH\Lua\app.lua:734>

Attached save: https://drive.google.com/file/d/0Bwc5O5IR0pMpUkE1NExSTW9DQWc/edit?usp=sharing

This bug can be reproduced especially since version 0.30, because of the vomit tweaking, which causes much more vomit.

**Comment by J-Shep** [comment]
@Alberth289346 Since I'm going to be changing the "edit room" blueprint checking code for #147, I could take over the task of fixing this for 0.50.

**Comment by TheCycoONE** [comment]
Fixed by #798
