### ISSUE TITLE
Keydown handler crashes if Esc is pressed during intro movie

### ISSUE THREAD

**Issue by ezeenova** [CorsixTH/CorsixTH#660]
If the Esc key is pressed during the intro movie, the keydown handler crashes and no further keyboard input is registered. The game otherwise continues to run normally. Only the intro movie appears to be affected, not other movies such as the level transition cutscenes. The error message is:

    An error has occured!
    Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
    Running: The keydown handler.
    A stack trace is included below, and the handler has been disconnected.
    ./Lua/ui.lua:836: attempt to index field 'windows' (a boolean value)
    stack traceback:
            ./Lua/ui.lua: in function 'callback'
            ./Lua/ui.lua:527: in function 'dispatch'
            ./Lua/app.lua:761: in function <./Lua/app.lua:756>

The next time any key is pressed, this warning is shown:

    Warning: No event handler for keydown

After that no further warnings or errors occur.

My operating system is Debian Sid, architecture is amd64, rendering system is SDL/SDL2 (crash occurs in both 0.40 and master). Whether the game is running in windowed or fullscreen mode does not matter.

**Comment by MarkL1961** [comment]
Same in Windows 7 for 0.40.

I have a feeling though that to skip the intro movie it is click or spacebar.  Even so it should not crash.

**Comment by jorgenpt** [comment]
Untested fix, but according to my reading of the source, this should resolve the issue.

**Comment by TheCycoONE** [comment]
#684 does indeed fix the issue.
