### ISSUE TITLE
adv queue error, maybe due to earthquake room explosion

### ISSUE THREAD

**Issue by ledowong** [CorsixTH/CorsixTH#663]
save:
https://drive.google.com/file/d/0B05D0Cat5usfWnNzNmRnNGRXT2c/view?usp=sharing

video:
http://youtu.be/6R583XXOheM

it not 100% crash, u will find out in video.

**Comment by TheCycoONE** [comment]
Please paste the full error / stack trace in the issue tracker.  It makes it easier to classify and find through search.

**Comment by MarkL1961** [comment]
I think you have added the wrong save, for me it is the start of the level!

**Comment by ledowong** [comment]
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\room.lua:481: attempt to index field 'queue' (a nil value)
stack traceback:
        C:\Program Files\CorsixTH\Lua\room.lua: in function 'tryAdvanceQueue'
        ...am Files\CorsixTH\Lua\objects\doors\swing_door_right.lua:135: in function 'timer_function'
        C:\Program Files\CorsixTH\Lua\entity.lua:215: in function 'tick'
        C:\Program Files\CorsixTH\Lua\world.lua:1103: in function 'onTick'
        C:\Program Files\CorsixTH\Lua\app.lua:852: in function 'dispatch'
        C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\CorsixTH\Lua\app.lua:748>

Warning: No event handler for timer

**Comment by ledowong** [comment]
sorry, here is the save:
https://drive.google.com/file/d/0B05D0Cat5usfeGJSYlZYVHlkNlk/view?usp=sharing

**Comment by ledowong** [comment]
for debugging, after i modify LUA files, do I need to recompile to make it works?
and how can i put (output) something (variables, text, etc) in console?

**Comment by TheCycoONE** [comment]
you do not need to recompile lua, and you put something in the console with print "This is my print statement".

You could also try out the eclipse debugger that @J-Shep put together in pr #439  He can provide you more instruction on using it.  (As an aside, @J-Shep would you mind putting together a wiki page on how to debug lua.  I think that would be generally helpful.)

**Comment by J-Shep** [comment]
@TheCycoONE I will make a wiki page for this now.

**Comment by J-Shep** [comment]
I will try to have this page ready to be published before tomorrow.

**Comment by J-Shep** [comment]
>> As an aside, @J-Shep would you mind putting together a wiki page on how to debug lua

I've finished [this](https://github.com/CorsixTH/CorsixTH/wiki/Debugger-Tutorials) page and I've finished [another page](https://github.com/CorsixTH/CorsixTH/wiki/Setting-Up-Eclipse-(Any-OS)) about setting up Eclipse for CorsixTH programming and for [debugging Lua scripts at runtime](https://github.com/CorsixTH/CorsixTH/wiki/Setting-Up-Eclipse-(Any-OS)#setup_lua_debugging).

**Comment by TheCycoONE** [comment]
Thank you @J-Shep , they were a very informative read.

@ledowong the above, as well as https://github.com/CorsixTH/CorsixTH/wiki/Lua-Console should be everything you need to get started looking at this.  Thanks for your interest.

**Comment by bobcanthelpyou** [comment]
Same issue here, could reproduce it with the following savegame, but the last fax while waiting for the earthquake have to be opened, if not the game does not crash.

http://filebin.ca/260Gd0LIuc4u/earth.sav (CorsixTH trunk / master branch)

```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
/home/bob/dev/Games/CorsixTH/CorsixTH/Lua/room.lua:504: attempt to index field 'queue' (a nil value)
stack traceback:
	...CorsixTH/CorsixTH/Lua/objects/doors/swing_door_right.lua:138: in function 'timer_function'
	/home/bob/dev/Games/CorsixTH/CorsixTH/Lua/entity.lua:218: in function 'tick'
	/home/bob/dev/Games/CorsixTH/CorsixTH/Lua/world.lua:1108: in function 'onTick'
	/home/bob/dev/Games/CorsixTH/CorsixTH/Lua/app.lua:876: in function 'dispatch'
	/home/bob/dev/Games/CorsixTH/CorsixTH/Lua/app.lua:777: in function </home/bob/dev/Games/CorsixTH/CorsixTH/Lua/app.lua:772>

Warning: No event handler for timer
```

**Comment by mugmuggy** [comment]
Change in #1566 guards against the race of door swinging, whilst room is destroyed.
