### ISSUE TITLE
Errors on starting CorsixTH

### ISSUE THREAD

**Issue by wiolen** [CorsixTH/CorsixTH#664]
1. Install Origin version of Theme Hospital
2. Install CorsixTH
3. Run CorsixTH

See attached jpgs.
![attachment1](https://cloud.githubusercontent.com/assets/10837148/6030216/45aa64aa-abf6-11e4-91f5-f4c5220d1a3b.jpg)
![attachment](https://cloud.githubusercontent.com/assets/10837148/6030218/46d33f1e-abf6-11e4-82bc-8bdcc04ab1c6.jpg)

Reply:
This isn't a bug. Please separate the CorsixTH folder from the Theme Hospital folder.
I have had this happen to me too before.

Answer:
I've installed corsix in other location (c/programfiles/corsixth) and "(...)/themehospital/corsixth" and the same error appear.

**Comment by TheCycoONE** [comment]
Alright.. perhaps you could tell us what is in your Theme Hosptial directory, because it appears to be missing the normal data files, e.g. Levels/Level.L1

**Comment by MarkL1961** [comment]
Did you uninstall origin?
I know when I did it took away the theme hospital files at the same time.

**Comment by wiolen** [comment]
G:\Program Files (x86)\Origin Games\Theme Hospital\data\Game\DOSBox\LAUNCHER.exe

No, origin is installed. Normal game (themeHospital) working with no issues.

**Comment by Lego3** [comment]
What directory have you specified as your "Theme Hospital directory" in CorsixTH?

**Comment by wiolen** [comment]
Where I can find this ?

**Comment by wolfy1339** [comment]
Press the Windows Key + R
and enter %AppData%/CorsixTH and open the config.txt file

**Comment by wiolen** [comment]
-- preferred.
theme_hospital_install = [[G:\Program Files (x86)\Origin Games\Theme Hospital]]

**Comment by wolfy1339** [comment]
Ok, I see now.
Please open up that path in Windows Explorer, and browse through the sub-folders to find the DATA, LEVELS, etc directories. Once you found that directory, copy it and paste it in CorsixTH's config.txt file

**Comment by wiolen** [comment]
Yes, now its working !
Thaks man.

Unfortunetly saves from "non mod" game are not working, even if i place save files in save directory (...)\AppData\Roaming\CorsixTH\Saves.

Maybe there is a solution ?

**Comment by TheCycoONE** [comment]
No, CorisxTH doesn't work with original game saves at this time.

**Comment by wiolen** [comment]
Ok, thanks a lot !
Close.
