### ISSUE TITLE
0.40: Midi files 'not found'/won't play on Windows installs that use WIMBOOT [Possible timidity++ problem?]

### ISSUE THREAD

**Issue by mpmc** [CorsixTH/CorsixTH#667]
__Device:__
VOYO A1 Mini 1280x800 / 2GB / 32GB / Intel Atom - Tablet.

__Issue:__
This device uses a WIMBOOT install due to it's small hard drive, unfortunately because of this it appears that CorsixTH Cannot play the music midi files and errors out saying that it cannot find the files even though they exist.

By the looks out the output it appears to be an issue with timidity++

```


---------------------------------------------------------------

Welcome to CorsixTH 0.40!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The callback handler.
A stack trace is included below, and the handler has been disconnected.
C:\Program Files\CorsixTH\Lua\audio.lua:594: Could not load music file 'Sound\Mi
di\DOCTOR.XMI' (/etc/timidity.cfg: No such file or directory)
stack traceback:
        [C]: in function 'yield'
        C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files
\CorsixTH\Lua\app.lua:748>

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
An error has occured!
Almost anything can be the cause, but the detailed information below can help th
e developers find the source of the error.
Running: The callback handler.
A stack trace is included below, and the handler has been disconnected.
Error in async music load callback: C:\Program Files\CorsixTH\Lua\audio.lua:594:
 Could not load music file 'Sound\Midi\STEADY.XMI' (/etc/timidity.cfg: No such f
ile or directory)
stack traceback:
        [C]: in function 'yield'
        C:\Program Files\CorsixTH\Lua\app.lua:753: in function <C:\Program Files
\CorsixTH\Lua\app.lua:748>
```

**Comment by TheCycoONE** [comment]
As I mentioned on IRC, this looks to be a problem with SDL_Mixer and/or a lack of midi support on that system (normally provided by windows).  SDL_Mixer has a built in timidity that is suppose to be a fallback on operating systems without midi support, but it can't find it's configuration file.

You may be able to work around this, installing timidity and a soundfont with the configuration in `c:\timidity` (based on a reading of https://github.com/aduros/SDL_mixer/blob/ac2df1b04a424c507839303ffb1c9cf000a95ac3/timidity/config.h) or possibly by providing another virtual midi interface.

**Comment by Lego3** [comment]
I'll close this issue now. I don't think we can do much here.
