### ISSUE TITLE
Changing Diseases

### ISSUE THREAD

**Issue by Oleander29** [CorsixTH/CorsixTH#671]
This is the only place I can find to ask this question...

I love theme hospital, but I would very much like for the game to incorporate real-life diseases, and probably real-life equipment. I don't think this is too big a jump but I'm not a terribly good coder so I'm not sure how to do that. Is it possible?

If yes, I'd be happy to help get that kind of thing going. I'd really like to add some level of realism, even if it's optional, perhaps?

**Comment by TheCycoONE** [comment]
First of all, it is possible yes, and disease suggetions are a very popular category in the forum (http://forums.corsixth.com/index.php/topic,292.0.html)

You can see disease definitions in CorsixTH\Lua\diseases, the expertise id and visual/non-visual ids should be defined in base_config.lua and then referenced in the levels you want to include these diseases in.  The new strings/translations that show up in the game should go in CorsixTH\Lua\languages\english.lua and any other language you want to translate to.

In light of different people having their own ideas of the types of diseases they want to see in the game (with some people having a strong preference for the comical, and some for the realistic) I think a welcome development would be the ability to plug in desease packs that either replace the existing diseases for campaign levels, or introduce new diseases for custom levels.  I feel that any other approach would be controversial.

**Comment by Oleander29** [comment]
Well, I will very happily make a realistic disease pack once I figure out exactly how. The big negative is the clinics - I can't very well use, for example, the inflator room to simulate cardiac catheterization, now can I? :P But it's an awesome start, thank you!!

**Comment by lewri** [comment]
Was a question, can be closed.
