### ISSUE TITLE
Xperia L

### ISSUE THREAD

**Issue by transmeta** [CorsixTH/CorsixTH#673]
I got the error starting CorsixTH
![screenshot_2015-02-06-00-00-02](https://cloud.githubusercontent.com/assets/10886121/6084195/010bd5e4-ae40-11e4-8487-66faa27cc005.png)

**Comment by SimplyRyan** [comment]
I suggest you re copy the files from the CD or digital release, if you found the files online then I would say try and obtain a legit copy that you can be sure isn't corrupt.

**Comment by transmeta** [comment]
Thanks Ryan.
I appreciate your reply, but I've done it once. After a few times of running the game, I got the issue)

Thank you again!

P.S. I really was surprised to play a game I got in childhood: seems I'm getting old, as it was just 15 years ago! Good for you for that stuff!

**Comment by MarkL1961** [comment]
The error message does suggest you have file corruption, so it would be worth doing as suggested by Ryan and copying the files over again.
Also you can check the config file for corsixth in case the data location has been altered
