### ISSUE TITLE
Bugs with contagious diseases

### ISSUE THREAD

**Issue by Necrobare** [CorsixTH/CorsixTH#674]
First: when a contagious patient is being clicked to cure the contagious, sometimes the patient stop being contagious within few seconds, and sometimes never. Hence, we are not sure if it is a bug or if some conditions must be met to stop patient being contagious.

After a contagious disease, if all patient are kicked out, some bugs appears. I got it with Cardiogram and Scanner: if patient is undressed at this moment, he try to leave the room without putting back his clothes.

Note that the bug is not appearing with surgery. With surgery room, doctors achieve the work, patient get dressed and then leave the hospital as if he was not cured but kicked out.

**Comment by sadger** [comment]
Hi @Necrobare. Thanks for letting us know.

The first thing you mention, what exactly is happening? Is a different icon showing after being clicked? What do you expect to happen that isn't? 

 I will look into the one where the patient isn't getting dressed before leaving. This is definitely a bug!

Any screenshots or save files would help a lot if you can supply them. I would also recommend looking at the wiki of how epidemics work in case it's expected behaviour you are experiencing. 
https://github.com/CorsixTH/CorsixTH/wiki/How-epidemics-work

Thanks

**Comment by sadger** [comment]
The patient trying to evacuate whilst not dressed is definitely a bug after some testing. This would go for any diagnostic step that needs the patient to undress.

http://i.imgur.com/pJVgh2t.png

 ```
Error in timer handler: 
./CorsixTH/Lua/humanoid_actions/walk.lua:304: Humanoid (Stripped Male Patient 3) without door animations trying to walk through door (from scanner to corridor)
stack traceback:
```
I'll try and fix it!

**Comment by Necrobare** [comment]
Hi !

Forget about the first thing. I read the link you shared and it appears I
was not aware of this new way of working for contagious disease (compared
to what I knew of original TH).

I'm glad you managed to fix the bug for undressed patient. Thanks for your
hard work !

Necrobare

2015-02-07 16:39 GMT+01:00 William Gatens <notifications@github.com>:

**Comment by sadger** [comment]
If you remember it differently then I am interested to know what you thought would happen. It was programmed by myself based on various memories by various people. We ended up doing it in the way which seemed most correct. 

As for the fix it needs verifying but hopefully we will see it in game soon :)

**Comment by MarkL1961** [comment]
When you click on a contagious patient he is marked for vaccination.  Once the nurse does that he or she is no longer contagious, but still needs to be cured.  You can tell this as there is a cross through the bug icon

**Comment by sadger** [comment]
@MarkL1961 I explained it by linking to the guide to epidemics I wrote. I'm interested in how he/she might remember it differently as my decisions were based on how you remembered it.

**Comment by MarkL1961** [comment]
@sadger I am interested in what is meant by "new way".
What we have done is not just from my memory, as I can still play the original game

**Comment by Necrobare** [comment]
In fact, in original version of TH, I never noticed that once the patient is marked it requires a nurse to perform the vaccination. I thought that when you mark the patient, some times later the vaccination is automatically performed.

However, it can be because I did not noticed it before so I always thought it was this way.

**Comment by sadger** [comment]
Fixed merged for dressing patients. The other part is a non-issue as discussed above.
