### ISSUE TITLE
Stuck in Operating Theatre

### ISSUE THREAD

**Issue by ledowong** [CorsixTH/CorsixTH#68]
I don't know how to reproduce this bug, and there is no error message.

In the save, there are two Operating Theater. The one has issue is one the right hand side.

This is what happened to me:
1. some people in queue but can't get in.
2. two doctor inside, they are very sleeping but look like can't go out to take a rest. They are wearing operating cloth (green cloth).
--- as a result, no one go in and doctor can't come out --
3. When i notice this, I drag and drop the doctors from inside to outside. So they can take a rest.
4. I drag and drop another two doctors inside the room, they change the cloth, but patient not go in....
--- room stuck ---

Similar issue happened a few times in GP office too, the doctor is very very sleepy but keep working.

save:
https://drive.google.com/file/d/0B05D0Cat5usfYUQwa0NDX3prUEE/edit?usp=sharing

**Comment by TheCycoONE** [comment]
This is very similar to #76 
Until we know they are the same issue, this one is for the Operating Theater and that one is for the GP office.

**Comment by maverique** [comment]
Seems like this happens to me every time I play now. And it seems to get worse whenever I use my strategy of building a GP at the hospital entrance then all my diagnostics facilities, along with a second GP in another section of the hospital. All clinics and machines I build near my first GP at the hospital entrance. I didn't do this in the earlier levels as there was no need but as soon as I began to do it, this bug happened. Every time. It might just be a coincidence of course.

**Comment by mugmuggy** [comment]
This looks like it was probably same as #1087. The other example appears it was #1104.
