### ISSUE TITLE
Issue when buying building extension

### ISSUE THREAD

**Issue by Necrobare** [CorsixTH/CorsixTH#681]
Hi !

On a map which has one building split in several parts, for example 2 part with only the first available at the beginning. If I build a room with one wall common to the limit between the two part of the building, this wall will disappear when I buy the expension. Moreover, the game will crash if I interact with the room and game will also crash if I load a saved game after I bought the building extension.

Here are two saves: one before extending the building and one after. The room to consider is the research department.
http://www.filedropper.com/autosaves

**Comment by MarkL1961** [comment]
Duplication of issue #451
