### ISSUE TITLE
Game crash with shared collision area

### ISSUE THREAD

**Issue by RichUK5** [CorsixTH/CorsixTH#691]
Made the game crash when placing the auto-autopsy machine sharing a collision area with the door to the room. See screenshot for details.
![corsixth-crash01](https://cloud.githubusercontent.com/assets/11014991/6202842/523177d0-b4f8-11e4-9796-cb17c9a83668.jpg)

**Comment by MarkL1961** [comment]
How does it crash?
What is the error message?

**Comment by RichUK5** [comment]
The game just froze, no error messages i'm afraid.

**Comment by tobylane** [comment]
Can't replicate in 0.60 beta2
