### ISSUE TITLE
Trunk version of CorsixTH doesn't play sound when Fluid3 soundfont selected in timidity's config

### ISSUE THREAD

**Issue by ggppjj** [CorsixTH/CorsixTH#700]
I have no idea why this would happen, but the newest (as of Feb 21, 20:40) trunk version of CorsixTH doesn't play sound when Timidity is set up to load the fluid soundfont. It works in version 0.8-beta-1, compiled as SDL and running on 64 bit mode, but not on commit 205628c39938fa3bb90d9b5bfee65f8a485d0ae5. Like I said, I'm not sure what the problem could be. I have no errors in console, and Timidity is able to play sample Midi files with fluid and is able to play music on the trunk version with freepats.

**Comment by ggppjj** [comment]
Trunk version compilation (all flags default) notes:

Note: SDL audio is enabled (default)
Note: FFMPEG video is enabled (default)
Note: FreeType2 is enabled (default)
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file malloc.h
-- Looking for include file malloc.h - found
-- Looking for include file alloca.h
-- Looking for include file alloca.h - found
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found

Building CorsixTH
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread (found version "2.0.2") 
  SDL found
-- Found LuaJIT library: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
-- Found Lua: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so  
  LuaJIT found
-- Found SDL_mixer: /usr/lib/x86_64-linux-gnu/libSDL2_mixer.so (found version "2.0.0") 
  SDL_mixer found
-- CMAKE_MODULE_PATH=/home/gabriel/.corsixth/CorsixTH/CMake
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'libavcodec'
--   found libavcodec, version 54.92.100
-- checking for module 'libavformat'
--   found libavformat, version 54.63.104
-- checking for module 'libavdevice'
--   found libavdevice, version 53.5.103
-- checking for module 'libavutil'
--   found libavutil, version 52.18.100
-- checking for module 'libswscale'
--   found libswscale, version 2.2.100
-- checking for module 'libpostproc'
--   found libpostproc, version 52.2.100
-- checking for module 'libswresample'
--   found libswresample, version 0.17.102
-- Found FFmpeg: /usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so;/usr/lib/x86_64-linux-gnu/libswresample.so  
  FFmpeg found
-- checking for module 'freetype2'
--   found freetype2, version 17.1.11
-- Found Freetype: /usr/lib/x86_64-linux-gnu/libfreetype.so (found version "17.1.11") 
  FreeType2 found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/gabriel/.corsixth/CorsixTH

**Comment by TheCycoONE** [comment]
This would have to be an SDL Mixer issue.  We switched to SDL2 / SDL_Mixer 2 recently.

**Comment by ggppjj** [comment]
Is there a build flag to change SDL Mixer to the old version so I can test for you?

**Comment by TheCycoONE** [comment]
No, we're not maintaining compatibility with sdl1.  You could try using the latest mecurial version of sdl2 mixer or seeing if there is a known issue reported for it.  http://www.libsdl.org/projects/SDL_mixer/  The latest stable version is 18 months old and there have been quite a few bug fixes since then.

**Comment by ggppjj** [comment]
After downloading and compiling version [b28b41b93ba7](http://hg.libsdl.org/SDL_mixer/file/b28b41b93ba7) of SDL2, then running make install on it, then clearing CorsixTH's CMakeCache, and remaking it, the problem persists.

**Comment by ggppjj** [comment]
(Also, I'm having difficulty finding a bug tracker for SDL_mixer.)

**Comment by TheCycoONE** [comment]
II believe it shares a tracker with the rest of SDL2: https://bugzilla.libsdl.org/  Maybe it relates to this? https://bugzilla.libsdl.org/show_bug.cgi?id=876

**Comment by ggppjj** [comment]
Doesn't seem to relate to that bug, although I could be completely wrong. I was able to play both of the attached midi files with no errors that would break timidity. Again, could be wrong. I know just enough to compile things, and not much more.

**Comment by TheCycoONE** [comment]
Does it play with freepats / without fluid, or does it not work at all for you?

**Comment by ggppjj** [comment]
It does, although with a fair amount of crackling.

**Comment by ggppjj** [comment]
I have no idea what was happening, but I decided to move to a soundfont that supposedly is more FM sounding, as I liked the sound of the music through Adlib emulation that the GOG version run through Playonlinux supported better. I tried [this](http://woolyss.com/chipmusic/chipmusic-soundfonts/OPL-3_FM_128M.zip) soundfont, which had to be converted with [this](https://github.com/raboof/sfarkxtc) program, and it works now. Seems to be either a problem with the specific soundfont or my ineptitude. I'll close the issue, and you can reopen if you end up testing and don't come to the same conclusion.

**Comment by ggppjj** [comment]
OK. So I was wrong. I had accidentally not told Timidity to load any of the soundfonts I was trying to run. Seems as though the ONLY soundfont CorsixTH supports is freepats. Hum.

**Comment by ggppjj** [comment]
Using the DOS program XMI2MID, I was able to convert and play CANDY.XMI, and it works. Maybe a problem with the XMI conversion?

**Comment by ggppjj** [comment]
OK. Two of my soundfonts were corrupt, but there's one that should definitely work that isn't. I can provide it to you if it helps.

**Comment by TheCycoONE** [comment]
It wouldn't help us.  As I mentioned above this will need to be taken upstream with sdl mixer if there is an issue with sound fonts.

**Comment by Alberth289346** [comment]
I just installed all timidity and libtimidity stuff through yumex-dnf at my Fedora 22 system. It came with the fluid-soundfont-lite-patches too. After compiling current master commit: f50e626 , it played out of the box.
