### ISSUE TITLE
Crash straight after an earthquake

### ISSUE THREAD

**Issue by mshine** [CorsixTH/CorsixTH#701]
Game seems to crash straight after an earthquake or almost mid-earthquake playing on a Nexus 6, can anyone let me know what further information you need and where in the folder structure I can find any stack trace from the logs?

**Comment by TheCycoONE** [comment]
@alanwoolley pinging you because this seems to be related to the android version.

**Comment by trumpetporvida** [comment]
I can confirm. Have the same issue on my nexus 9. Game crashes to home screen with no error message.

**Comment by alanwoolley** [comment]
Thanks @TheCycoONE. It is indeed a bug, but it should be fixed already in the beta channel. If it's still an issue, could I ask that it be raised separately on the CorsixTH-Android issue tracker?

**Comment by mshine** [comment]
@alanwoolley  Silly question... whats the beta channel?
