### ISSUE TITLE
Fail on edit room (Pharmacy)

### ISSUE THREAD

**Issue by mortengormmadsen** [CorsixTH/CorsixTH#706]
v0.4, SDL

*Reproduction*
Edited a pharmacy with a line of people
Nurse went out while zzz icon showed
Clicked X twice (place and resize room)
Error occured
Recovered from error
Moved and completed the room
Now the room is just all weird...

*Problems*
A nurse is stuck in front of the door.
Patients walk in without a nurse in the pharmacy
Placing a nurse in the room has no effect
Firing the nurse in front of the door has no effect

*Files*
Gamelog http://bit.ly/1EUrXfv
Savegame http://bit.ly/1AS5yyG

**Comment by SimplyRyan** [comment]
Adding the text to the issue to preserve it allow searching for similar issues across all issues.


Created game with savegame version 91.
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x0e64edc8) from humanoid (table: 0x0e72a010).
Warning: Trying to remove nonexistant room remove callback (function: 0x0c184b08) from humanoid (table: 0x0e72a010).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x102cc080) from humanoid (table: 0x0d2833e0).
Warning: Trying to remove nonexistant room remove callback (function: 0x102cc0e8) from humanoid (table: 0x0d2833e0).
Warning: Trying to remove nonexistant room build callback (function: 0x101fb0a8) from humanoid (table: 0x0d28a100).
Warning: Trying to remove nonexistant room remove callback (function: 0x10463718) from humanoid (table: 0x0d28a100).
Warning: Trying to remove nonexistant room build callback (function: 0x0c6b0388) from humanoid (table: 0x0d28b3c0).
Warning: Trying to remove nonexistant room remove callback (function: 0x0ddbe968) from humanoid (table: 0x0d28b3c0).
Warning: Trying to remove nonexistant room build callback (function: 0x06aafbb0) from humanoid (table: 0x10445678).
Warning: Trying to remove nonexistant room remove callback (function: 0x06ab8ec0) from humanoid (table: 0x10445678).
Warning: Trying to remove nonexistant room build callback (function: 0x079edba0) from humanoid (table: 0x102e6e88).
Warning: Trying to remove nonexistant room remove callback (function: 0x102e4900) from humanoid (table: 0x102e6e88).
Warning: Trying to remove nonexistant room build callback (function: 0x06ac5ff0) from humanoid (table: 0x0dc9f7d0).
Warning: Trying to remove nonexistant room remove callback (function: 0x079ed690) from humanoid (table: 0x0dc9f7d0).
Warning: Trying to remove nonexistant room build callback (function: 0x0ddc7a00) from humanoid (table: 0x07a35b78).
Warning: Trying to remove nonexistant room remove callback (function: 0x163ed078) from humanoid (table: 0x07a35b78).
Warning: Trying to remove nonexistant room build callback (function: 0x105009a0) from humanoid (table: 0x03cc3c40).
Warning: Trying to remove nonexistant room remove callback (function: 0x102eadc8) from humanoid (table: 0x03cc3c40).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x160ab150) from humanoid (table: 0x16070fc0).
Warning: Trying to remove nonexistant room remove callback (function: 0x161b62c8) from humanoid (table: 0x16070fc0).
Warning: Trying to remove nonexistant room build callback (function: 0x034dbd00) from humanoid (table: 0x0e1d97e8).
Warning: Trying to remove nonexistant room remove callback (function: 0x16119678) from humanoid (table: 0x0e1d97e8).
Warning: Trying to remove nonexistant room build callback (function: 0x163ee000) from humanoid (table: 0x16357308).
Warning: Trying to remove nonexistant room remove callback (function: 0x0cc8c000) from humanoid (table: 0x16357308).
Warning: Trying to remove nonexistant room build callback (function: 0x0e22f860) from humanoid (table: 0x162f5018).
Warning: Trying to remove nonexistant room remove callback (function: 0x0e224760) from humanoid (table: 0x162f5018).
Warning: Trying to remove nonexistant room build callback (function: 0x162b8c50) from humanoid (table: 0x16357308).
Warning: Trying to remove nonexistant room remove callback (function: 0x10804880) from humanoid (table: 0x16357308).
Warning: Trying to remove nonexistant room build callback (function: 0x1633dc48) from humanoid (table: 0x0804c2a8).
Warning: Trying to remove nonexistant room remove callback (function: 0x1608a080) from humanoid (table: 0x0804c2a8).
Warning: Trying to remove nonexistant room build callback (function: 0x0ccca4d0) from humanoid (table: 0x162ad158).
Warning: Trying to remove nonexistant room remove callback (function: 0x0a38bf40) from humanoid (table: 0x162ad158).
Warning: Trying to remove nonexistant room build callback (function: 0x0ccdf2e0) from humanoid (table: 0x16471e80).
Warning: Trying to remove nonexistant room remove callback (function: 0x01255e98) from humanoid (table: 0x16471e80).
Savegame version is 91 (0.40), originally it was 91 (0.40)
Warning: Trying to remove nonexistant room build callback (function: 0x00b6dbf8) from humanoid (table: 0x0c35ac30).
Warning: Trying to remove nonexistant room remove callback (function: 0x0cec8020) from humanoid (table: 0x0c35ac30).
Error in timer handler: 
C:\Program Files\Hospital\CorsixTH\Lua\map.lua:46: bad argument #1 to 'getCellFlags' (number expected, got nil)
stack traceback:
	[C]: in function 'getCellFlags'
	C:\Program Files\Hospital\CorsixTH\Lua\map.lua:46: in function 'getRoomId'
	C:\Program Files\Hospital\CorsixTH\Lua\world.lua:2246: in function 'getRoom'
	C:\Program Files\Hospital\CorsixTH\Lua\room.lua:69: in function 'getEntranceXY'
	C:\Program Files\Hospital\CorsixTH\Lua\room.lua:666: in function 'tryToFindNearbyPatients'
	C:\Program Files\Hospital\CorsixTH\Lua\room.lua:456: in function 'commandEnteringStaff'
	C:\Program Files\Hospital\CorsixTH\Lua\room.lua:354: in function 'onHumanoidEnter'
	...am Files\Hospital\CorsixTH\Lua\humanoid_actions\walk.lua:356: in function 'on_next_tile_set'
	...am Files\Hospital\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function 'timer_function'
	C:\Program Files\Hospital\CorsixTH\Lua\entity.lua:215: in function 'tick'
	C:\Program Files\Hospital\CorsixTH\Lua\entities\staff.lua:146: in function 'tick'
	C:\Program Files\Hospital\CorsixTH\Lua\world.lua:1103: in function 'onTick'
	C:\Program Files\Hospital\CorsixTH\Lua\app.lua:852: in function 'dispatch'
	C:\Program Files\Hospital\CorsixTH\Lua\app.lua:753: in function <C:\Program Files\Hospital\CorsixTH\Lua\app.lua:748>

**Comment by bobcanthelpyou** [comment]
Can't reproduce the issue with the latest trunk version (https://github.com/CorsixTH/CorsixTH/commit/5cd0314e28d6360019afc20af211ed0ddd71e719) of CorsixTH. Maybe it is already fixed?

**Comment by Alberth289346** [comment]
Thanks for testing, let's open a new issue if it happens again
