### ISSUE TITLE
Shadow on the wall disappears with zoom

### ISSUE THREAD

**Issue by Alberth289346** [CorsixTH/CorsixTH#713]
Before zooming, there is a diagonal-ish show at the north wall in a NW corner (towards the top of the screen). After zoom, it's not there any more. (Version: trunk commit:ded32b7)

![Screenshot](http://i.imgur.com/3zmDmPb.png)

**Comment by TheCycoONE** [comment]
Cannot reproduce on Windows with 7b8c4ca0570edda77a815b7635df1b0691cc8960. Does this still happen for you (e.g. opengl only) or has it been fixed?

**Comment by TheCycoONE** [comment]
Ping @Alberth289346

**Comment by Alberth289346** [comment]
It works now.
