### ISSUE TITLE
Clicking on doctor froze game

### ISSUE THREAD

**Issue by Frassle** [CorsixTH/CorsixTH#715]
> What steps will reproduce the problem?

Clicked on doctor sitting in staff room

> What is the expected output? What do you see instead?

Game immediately froze, staff information window did not show.

> What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?

Version 0.40

> What operating system / compile settings are you using?

Windows 7

> What level was this on (e.g. "Demo level", "Full game level 12")?

Full game first level

> Upload a saved game file (preferably an autosave from before the error) if you have one and it is relevant.

Maybe relevant https://drive.google.com/file/d/0BzdXpBSuyzy3aFlMdHBTV1lJRFU/view?usp=sharing, autosave from a bit before the freeze

> If possible, also upload the gamelog.

I'm assuming the following is what's meant by gamelog?
```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The keydown handler.
A stack trace is included below, and the handler has been disconnected.
D:\Program Files\CorsixTH\Lua\ui.lua:949: attempt to index field 'windows' (a boolean value)
stack traceback:
        D:\Program Files\CorsixTH\Lua\ui.lua: in function 'callback'
        D:\Program Files\CorsixTH\Lua\ui.lua:669: in function 'dispatch'
        D:\Program Files\CorsixTH\Lua\app.lua:753: in function <D:\Program Files\CorsixTH\Lua\app.lua:748>

Checking for CorsixTH updates...
You are running the latest version of CorsixTH.
Warning: No event handler for keydown
starting game with difficulty full
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
```

**Comment by TheCycoONE** [comment]
The console output is very helpful, on top of that there is also a file in the same location as the saves called gamelog.txt which could be attached.

**Comment by Frassle** [comment]
Unfortunately not. I can't find a gamelog.txt anywhere. I had to process kill Corsix due to the freeze is there a chance gamelog wasn't written due to process termination?

**Comment by TheCycoONE** [comment]
Alright, the stack trace at the top of your output is unrelated.  It's issue #660 

The frame handler error with no debugging information is known (though very difficult to diagnose). #327
