### ISSUE TITLE
Lock mouse pointer in the window for better windowed mode play

### ISSUE THREAD

**Issue by leaveboss** [CorsixTH/CorsixTH#723]
What is it you would like in the game?
I think there should be an option to lock the mouse inside the window like dota 2. 
I have a big screen so I have to play in the window mode. However the mouse keeps going outside the window and it is impossible to scroll on the window edge with mouse. I googled this issue, it seems that the mouse cursor was locked inside the window in the previous version, but updated in a newer version.
I like the feeling when I am playing dota 2, the mouse is locked inside the window to enable edge-scroll, which will secure fast control like over 250 APM when playing. Right now i have to use arrow keys to scroll in window mode, and my left hand is jumping around as playing a piano.

What version of the product are you using? On what operating system?
0.40 RC3

**Comment by TheCycoONE** [comment]
I like this solution better than the one in #431 because it matches the experience people would have playing with dosbox, and other window mode games.  Needs a key combo to unlock the cursor obviously.
