### ISSUE TITLE
Allow setting non-shifted scroll speed

### ISSUE THREAD

**Issue by leaveboss** [CorsixTH/CorsixTH#724]
I am using CorsixTH(v0.40 RC3) with a full version of ThemeHospital. The scroll speed is too slow when I move the mouse cursor to the edge of the screen. It is much slower compared to the original game version. I set the scroll_speed from 2 to 9 in 'config.txt' (%Users%\AppData\Roaming\CorsixTH\config.txt). Back to game, nothing changed.
Can anyone help me with this? Thanks

**Comment by TheCycoONE** [comment]
It's not very clear on this point, but the scroll_speed in the config file is just the multiplier when fast scrolling is enabled (while you are holding down the shift key).  2 is 2x normal speed.

**Comment by leaveboss** [comment]
Got this. Is there a way to accelerate the scroll speed by mouse?

**Comment by TheCycoONE** [comment]
Holding shift will accelerate both mouse and keyboard scrolling, but there is no way (without modifying the game's lua) to speed up the scrolling with just the mouse at this time.

It would be pretty easy to allow setting both the regular scroll speed and the modified scroll speed in the config file, which would allow people to set regular scroll to fast and shift scroll to fine if they'd rather work that way.

**Comment by MarkL1961** [comment]
`  It is much slower compared to the original game version.   `
For me they seem to be about the same.  Maybe Theme hospital seemed faster as it was a much small resolution?
Perhaps it is something that is specific to some computers compared to others - different graphics cards for instance may slow things down if they have a higher definition! 
~ just throwing ideas out there ~

**Comment by TheCycoONE** [comment]
Didn't seem much different to me either (running dosbox and CorsixTH side by side) but if we fix up the configuration options everyone should be happy.

**Comment by sadger** [comment]
This is solved now after pr #726
