### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [CorsixTH/CorsixTH#725]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [IsoFilesystem::_clear](https://github.com/CorsixTH/CorsixTH/blob/e3d2b0377552ef2bdd1a2e93e49a09270a25fd71/CorsixTH/Src/iso_fs.cpp#L51 "IsoFilesystem::_clear function")
* [THMapNode](https://github.com/CorsixTH/CorsixTH/blob/e3d2b0377552ef2bdd1a2e93e49a09270a25fd71/CorsixTH/Src/th_map.cpp#L45 "Destructor for THMapNode")
* [THPathfinder](https://github.com/CorsixTH/CorsixTH/blob/e29d7713b7400ec6f8202db8cb36d6bb0b0593ee/CorsixTH/Src/th_pathfind.cpp#L45 "Destructor for THPathfinder")

**Comment by TheCycoONE** [comment]
@elfring would you mind to submit a PR for this?  It would be accepted (I have cleaned up redundant NULL checks in e.g. th_movies.cpp)

**Comment by elfring** [comment]
Thanks for your small source code improvement.
