### ISSUE TITLE
Infinite loop causes crash on spawnPatient

### ISSUE THREAD

**Issue by crucifigo** [CorsixTH/CorsixTH#732]
Update: I restarted and opened the hospital immediately with one receptionist and nothing else, and it still crashed.

The timer ran down on my hospital and I turned off pause, and when the first patient would normally arrive, the game freezes up.

What steps will reproduce the problem:
Simply leaving it or turning off pause.

What is the expected output? What do you see instead?
The game freezes instead of spawning patients.

What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?
0.40

What operating system / compile settings are you using?
Win7

What level was this on (e.g. "Demo level", "Full game level 12")?
Full game lv.11 (Croaking Hospital)

Upload a saved game file (preferably an autosave from before the error) if you
have one and it is relevant:

Dropbox: https://www.dropbox.com/s/0577fqrrn3n9lwb/Main.sav?dl=0
![image](https://cloud.githubusercontent.com/assets/11978903/7181578/be980a72-e443-11e4-80ff-4f8d588a8014.png)

**Comment by TheCycoONE** [comment]
Copying stack trace so that a search pulls up this issue:
world.lua:531 Suspected infinite loop

world.lua: in function 'spawnPatient'
world.lua:1097: in function 'onTick'
app.lua:852: in function 'dispatch'
app.lua:753: in function <app.lua:748>

**Comment by TheCycoONE** [comment]
The code block that is failing is:

```lua
    local disease = self.available_diseases[math.random(1, #self.available_diseases)]
    while disease.only_emergency or not isVisualDiseaseAvailable(disease) do
      disease = self.available_diseases[math.random(1, #self.available_diseases)]
    end
```
which suggests possibly that the disease list being loaded isn't complete.

Would you be able to paste the md5sums of your EASY11.SAM, FULL11.SAM, and HARD11.SAM files.  Of course mention if you have done any modifications yourself to either the level files or the lua.
