### ISSUE TITLE
Absolute paths are not preserved when selecting a font file in-game.

### ISSUE THREAD

**Issue by p-bo** [CorsixTH/CorsixTH#734]
Seems to be related to #391.
(this language is missing in config_finder.lua too)

Even if tried to use configuration file posted in #383 (apparently using Czech language, but on Windows), game complains with:

"The game language has been reverted to English because the desired language could not be loaded. Please make sure you have specified a font file in the config file."

So apparently there is also problem with font for characters, which are specific to this language.

It is a bit sad, that all translator(s) work is wasted due this...

System - Ubuntu 15.04 64bit
Game - 0.40 (getdeb.net package) + original game data

**Comment by TheCycoONE** [comment]
We did not produce the getdeb.net package. However this sounds like an issue either with linking freetype, or with the fonts detected.

What languages show up when you pull up the language list in game?

**Comment by p-bo** [comment]
In game (language list pull up menu): English, Castellano, Dansk, Deutsch, English, Francais, Italiano, Nederlands, Norsk, Portugues, Portugues do Brasil, Suomi, Svenska

And regarding packaging deficiency (good point indeed) - tried
https://github.com/CorsixTH/CorsixTH/releases/download/v0.40/CorsixTH-0.40-GNU-Linux_amd64.tar.gz

...and language is missing in menu there too. So it is reproducible error directly in official release.

Maybe there are two problems - one missing entry in menu, the other with fonts. Sorry for mixing it in one report. So maybe just now lets concentrate on missing entry, then on font problem?

**Comment by TheCycoONE** [comment]
They are likely related, if there is no font for an entry it won't show up in the menu and it can't be selected from the configuration.

Since you are not seeing a lot of other languages that require unicode fonts I think that is the issue (simplified chinese, russian, korean, etc.).

Have you followed the instructions here? https://github.com/CorsixTH/CorsixTH/wiki/Fonts

**Comment by p-bo** [comment]
Thanks for hint, but still no luck :(

Installed package fonts-arphic-uming, which resulted in file /usr/share/fonts/truetype/arphic/uming.ttc
(libfreetype package installed already)

Then in game settings menu, folders, font pointed on that .ttc file.
(resulted in unicode_font = [[usr/share/fonts/truetype/arphic/uming.ttc]] in config.txt)
Quieted from game and reruned - in language settings still no entry for Czech language.

Manually edited config.txt file according #383 (language = [[Čeština]]). Started game - still complaining about font (why???) and defaulting to English.

The same behaviour is with getdeb.net package and binary release from there (github).

Any ideas?

**Comment by Alberth289346** [comment]
Config file misses the initial / before "usr", so it searches the font relative to your home directory rather than from the root of the file system.

**Comment by p-bo** [comment]
You are right - now language menu is complete and switching to additional languages works! Thanks :)

But reason, why this omitted "/" before "usr" was overlooked is, that it was generated by game itself (so supposed to be correct)!
In another words, _there still is a bug_: when one selects patch to .ttc file from game settings interface, it is written to config.txt incorrectly!

**Comment by Alberth289346** [comment]
Yep, that was my conclusion too. Apparently, CorsixTH needs to learn about / being special.

**Comment by p-bo** [comment]
Great!
And may I share some thoughts about user experience there
(As a feedback, in no case instructing you what to do - it would be inappropriate.)?

In case when yes:
In case of game data, it is solved very well. Want to play? Point where game data are (In basic game description there is clearly stated, that you need it, so you know, what to do). Done - playing. Perfectly handled, no confusion there.

But what about language select?
User even isn't informed, that translation for his/her language exists - it isn't in menu. Result is, that majority of users conclude, that translation simply doesn't exists and will not solving any more about it.
So idea - what about display in menu always all languages and in case of attempt selecting one, requiring additional font, react analogically as with game data: Want this language? Point where necessary font is! And for better understanding sake, in this message there would be link https://github.com/CorsixTH/CorsixTH/wiki/Fonts mentioned, so all is clear (or at least more clear).

And maybe what about overall out-of-box experience? It would be possible to ask packagers (I volunteer for asking getdeb.net packagers) for adding dependency on package fonts-arphic-uming and add into game code built-in check, which will check presence of /usr/share/fonts/truetype/arphic/uming.ttc and places it into config.txt, wouldn't it? It would made possible to autoconfigure language according user environment variables (LANG)!
In another worlds, to have there sane defaults and don't let all translators hard work to be unrevealed ;-)
(disclaimer: I'm not involved in any translation in this project, but as I do in many others, I know, how frustrating it is to have obstacles there, which are preventing your work to be actually useful for users).

Thanks for reading this :)

**Comment by TheCycoONE** [comment]
The Windows out of box experience is that a unicode font is automatically detected and available on install. I haven't looked into exactly how this works, but ideally this should be the same on all platforms (at least as far as possible, e.g. checking for the existence of common unicode fonts in common locations).

The language names are presented in their own language, which means without an appropriate font we cannot display them. I suppose it would be possible in that case to give the English names for the language?

It would be interesting to compare in game against arphic-uming, dejavu sans, gnu unifont, fixedsys-excelsior and other unicode fonts (for coverage and appearance).

**Comment by TheCycoONE** [comment]
Fixed by pr #803
