### ISSUE TITLE
affiliate ID

### ISSUE THREAD

**Issue by a-detiste** [CorsixTH/CorsixTH#735]
Hi, GOG.com has a "affiliate partner program"
You might be interrested to get such ID (the hash appended to the URL);
then I would re-use it for Debian's `game-data-packager` ;
a tool that turn the demo/full game data into a .deb

https://www.gog.com/affiliate 
```
Want to be our affiliate partner?
Feel free to drop us a line at affiliate@gog.com. Join us, spread the word, and          
earn money from GOG.com games!
```

Now the tool default to ScummVM's id; as found on their website/wiki url's.

![shot](https://cloud.githubusercontent.com/assets/7994192/7470942/9f36f994-f321-11e4-8fa2-e2e0d55d2641.png)

**Comment by TheCycoONE** [comment]
I'm not sure we're organized enough to decide who should get the money. :) Though it would be good if it went towards hosting corsixth.com.

Is that owned by @corsix ?

**Comment by Alberth289346** [comment]
I don't think this will happen at all.

**Comment by a-detiste** [comment]
yup :smile:
