### ISSUE TITLE
libav Support

### ISSUE THREAD

**Issue by admdly** [CorsixTH/CorsixTH#738]
Moving forward are we to support both libav and ffmpeg for all platforms? I'll note that libav does not, at the time, provide all the necessary components, when installed via Homebrew, to build on OS X. 

If needed I can put the effort in to providing a fix for this, but as ffmpeg works I don't see a need or purpose for it. Indeed, libav is a fork of ffmpeg and I don't really see the point of supporting both (is Linux support an issue?).

**Comment by wolfy1339** [comment]
From what I understood from the pull request that implemented LibAV support, it was that some Linux distroes use FFMPEG and some others use LibAV

**Comment by TheCycoONE** [comment]
Yes, the intent is not for the packaged releases to support both, but for people attempting to build (or package) for environments where one or the other isn't available. So on OSX you would use FFMPEG exclusively, on Ubuntu they would use LibAV, and for Gentoo the ebuild would depend on their USE flags.
