### ISSUE TITLE
Cold hospital has low consequences

### ISSUE THREAD

**Issue by mounirlamouri** [CorsixTH/CorsixTH#74]
I played the first level of the game with barely no heating and patients such as doctors where quite upset. Nearly every patient had a frowny face and doctors were asking for raises/bonuses very often.

The same scenario applied to CorsixTH does not go that bad. Patients will be cold but not too upset and doctors will barely complain. Also, the heat indicator will be at ~15-25% even though there is not one single heater in the hospital. It was quite close to 0% in the original game.

**Comment by TheCycoONE** [comment]
I'm in favor of removing the grace period. Whatever balance issues people were complaining about could probably be better addressed directly.

**Comment by Lego3** [comment]
Indeed. For instance making sure that the adviser tells you it's cold before staff starts threatening to resign.

**Comment by TheCycoONE** [comment]
Now that sounds like a good feature :+1:

**Comment by Lego3** [comment]
I believe the grace period was originally added just after happiness degradation from cold was introduced, to mimic the original game. In TH you could finish both level 1 and 2 without any radiators, but then it started to get harder.

**Comment by TheCycoONE** [comment]
Is the happiness degradation too severe or is the effect of being unhappy too quick?

**Comment by Lego3** [comment]
Before it was a little of both, and especially with staff resignations 
it was drastic in the way that a single doctor could threaten to resign 
like 3-4 times a year.
