### ISSUE TITLE
Litter system is broken

### ISSUE THREAD

**Issue by QTurtle** [CorsixTH/CorsixTH#744]
My friend was playing using my top of tree build and throughout the whole game he has never seen any other litter type other than vomit and puke, even after patients' using vending machine.

One apparent bug is that in Patient:setTile(x, y), "self.world.map.th:getCellFlags(x, y).buildable" should really be "not self.world.map.th:getCellFlags(x, y).buildable".

However, even that doesn't fix the problem. If you leave out all the if clauses, you'll find the following 3 lines does nothing even if they are executed (I added an exception after them to make sure they are indeed executed and no, there is no handman in the game):

"local trash = math.random(1, 4)
 local litter = self.world:newObject("litter", x, y)
 litter:setLitterType(trash, math.random(0, 1))"

I do not have debugging environment to further trace the bug. Thanks guys for your excellent work and thanks for looking into this.

**Comment by TheCycoONE** [comment]
The file mentioned above is '''CorsixTH\Lua\entities\patient.lua'''

On a quick look I think the buildable flag check is right.  Pee and Vomit are handled elsewhere, so it's likely that the conditions for this function are not being triggered at all; perhaps litter_countdown isn't being triggered. I will take a more in depth look later.

Please mention in your ticket what version of the game you are using.

**Comment by QTurtle** [comment]
I am using top of tree DirectX build. litter_countdown is already 0 but self.world.map.th:getCellFlags(x, y).buildable is always false. Also, even if the function is actually triggerd no litter was actually drawn on the screen.

**Comment by TheCycoONE** [comment]
I have seen bottles. Maybe this is resolved in latest master?

**Comment by TheCycoONE** [comment]
Seeing all litter types. Vomit is just more common.
