### ISSUE TITLE
Save name can change game speed

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#745]
I have noticed that if you were to use a number in your saves name, as you type it your game can speed up i.e. save the game as level 5 and the game speeds up to fastest speed.

**Comment by MarkL1961** [comment]
Checked this again 0.3 and 0.4 and this only becomes an issue in the trunk version

**Comment by TheCycoONE** [comment]
Thank you @MarkL1961, there were substantial changes to input in trunk because of the change to SDL2, so it makes sense that such a regression occurred.

**Comment by bobcanthelpyou** [comment]
I can't reproduce that issue with 
CorsixTH trunk (be5d8f444b4ac42365397e1e1d1ae988d5bed672) on Debian Jessie 32 bit and 64 bit
CorsixTH v0.50 beta 2 on Windows 7 32 bit

@juef17 @MarkL1961 which system do you use? And how to reproduce that issue exactly?

I put the cursor to the input field of the savegame dialog and typed letters and numbers but the game speed did not changed by the keys 1,2,3,4 and 5

**Comment by MarkL1961** [comment]
@bobcanthelpyou 
Windows 7. try using number pad keys as it does not happen with top row number keys

**Comment by bobcanthelpyou** [comment]
@MarkL1961 thx 

Could reproduce it with the numpad keys (keypad 1, keypad 2, ..) and also some other keys like for zooming (+, -, keypad +, keypad -) should not work while enter a savegame name.

Already had a look at the code, will try to fix that this weekend
