### ISSUE TITLE
No MIDI on Linux Mint 17.1 on both binary and from source

### ISSUE THREAD

**Issue by GregPK** [CorsixTH/CorsixTH#746]
**What steps will reproduce the problem?**
1. Run game
2. (listen) 

**What is the expected output?**
Midi music.

**What version of CorsixTH are you using**
* binary 0.40-rc3
* ref:18e45548084068dffc0c01066356d2499eae8fc3

Notes:
* Audio works fine
* Jukebox can be operated, but nothing can be heard
* No messages in console

Tried:
* running binary distribution (0.40-rc3)
* `apt-get install timidity`, then run binary again
* git clone & compile from source - no changes

**Operating system**:
```
$ lsb_release -a
Distributor ID: LinuxMint
Description:    Linux Mint 17.1 Rebecca
Release:        17.1
Codename:       rebecca
```

**Comment by TheCycoONE** [comment]
Typically this suggests an issue with your timidity configuration or a lack of sound fonts.  Do you have timidity-freepats installed?  Can you confirm midi works elsewhere?

**Comment by GregPK** [comment]
@TheCycoONE Yup - that was the problem. I have not yet needed midi on this machine. Still is seems strange that there are no errors during startup.

For the record for Ubuntu/Mint users: if you want MIDI working on your system run
```
apt-get install timidity freepats
```

If you're still having problems download a sample MIDI and run `timidity sample.midi`
