### ISSUE TITLE
Nurses keeps bugging

### ISSUE THREAD

**Issue by Typiskk** [CorsixTH/CorsixTH#748]
Hi!

Everytime a nurse leaves the staff room, she freezes and i get the "Sorry, but an error has occured".
Then she is stuck there between the staff room door, and another door appearing just infront.  

Image of log: http://imgur.com/JkF2bsn

It only happens in level 9, so far.
Im using Windows 7, with latest CorsixTH version.

In this saved game, it happens after 1 minute
http://s000.tinyupload.com/?file_id=04776651535174280878

**Comment by sadger** [comment]
Hi @Typiskk. Thanks for reporting this. Sorry I didn't see this issue until it was pointed out to me just now. I assume this is during an epidemic or just before one was revealed? Probably can fix this one pretty easily with any luck.
