### ISSUE TITLE
Detect and warn about levels that contain untreatable diseases

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#751]
Related to #749

If a level has a disease but the room to treat the disease is not available e.g.:
#visuals[12] 1 I_PREGNANT
#objects[30].StartAvail.StartStrength.AvailableForLevel 0 12 0 Operating Table

then when a patient with that disease seeks treatment (after being diagnosed), the game errors.

It would be helpful for level designers (and frustrated players) if this condition was scanned for and warned about up front. I'm open to debate over whether their should be a warning and the affected diseases disabled, or an error dialog and the level refusing to play.

**Comment by Alberth289346** [comment]
My first idea would be to disable the treatment as option for the disease.
If that is not feasible, or removal of the treatment makes the disease non-treatable, then disable the disease.

The level editor should check, and refuse it, avoiding new levels to be created. The game should be quite silent about the removal in general imho, a user cannot fix it, and refusing to play is generally bad. That keeps the existing levels playable.

If a level designer disables treatments, he clearly doesn't mean the treatment to be available, thus silently discarding it is in line with his ideas.

Until the level editor is fixed, a warning before the removal may be useful to alert the level designer.

**Comment by MarkL1961** [comment]
In both Avatar and the level I tested an operating theatre is researchable.  There are many of the campaign levels where a disease appears before you have researched a room.
So why does it crash in this case?

**Comment by TheCycoONE** [comment]
@MarkL1961  as I said in the other issue, the operating theatre is not buildable in Avatar, because the operating table isn't.

**Comment by Alberth289346** [comment]
Maybe this is another issue? Researching a room which is eventually not buildable doesn't sound very useful

**Comment by MarkL1961** [comment]
I was thinking it was researchable because of RschReqd, but as @TheCycoONE  says the room cannot be without the table.

**Comment by MarkL1961** [comment]
What I don't understand is Avatar was added a couple of years ago, so why as this error never appeared before?

**Comment by MarkL1961** [comment]
To test this I have just run it on a version from March 2013 and got the same error.  Perhaps nobody has ever played this level or if they have they haven't informed us of the error!

**Comment by TheCycoONE** [comment]
Closed by pr #766 and #768

**Comment by TheCycoONE** [comment]
The warnings currently occur for any disease that can't be treated, which makes even valid levels like level 1 of the campaign issue warnings. The warning should only happen if the disease is enabled and cannot be cured.

**Comment by Alberth289346** [comment]
Addressed in #770

**Comment by TheCycoONE** [comment]
Confirmed fixed with #770
