### ISSUE TITLE
Freeze "Running: The music_over handler"

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#753]
```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The music_over handler.
A stack trace is included below, and the handler has been disconnected.
```

At the moment i can't reproduce that error. But it cause a game freeze without a stack trace, again.

**Comment by TheCycoONE** [comment]
I wouldn't be surprised if this was somehow releated to #709, but at the moment there's not much to go on. I've never seen this particular crash.

@bobcanthelpyou would it be possible for you to run the game in a debugger so that when you hit this error or the frame one you are able to see all of the stacks?

**Comment by bobcanthelpyou** [comment]
Is the following output useful? What else could help?

```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff765905b in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
```

```
(gdb) backtrace
#0  0x00007ffff765905b in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#1  0x00007ffff76644aa in lua_getstack ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#2  0x00007ffff769741e in luaL_traceback ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#3  0x00007ffff7697672 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#4  0x00007ffff7656a88 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x0000000000477ae4 in CorsixTH_lua_main(lua_State*) ()
#6  0x00007ffff7656a88 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#7  0x00007ffff7699f60 in lua_pcall ()
   from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#8  0x00000000004357c3 in main ()
```

**Comment by ajdlinux** [comment]
I'm having the same issue - first saw it today as I was playing the Greenpool level, nothing in particular which seems to trigger it. Not sure if it occurs on other levels. Running Debian unstable, my dpkg logs don't seem to indicate any changes to relevant libraries in the past couple of days. Will play again under gdb to get a backtrace for you.

**Comment by ajdlinux** [comment]
Unfortunately couldn't reproduce the crash under gdb :(

**Comment by bobcanthelpyou** [comment]
@ajdlinux this issue and #327 are not reproduce able and hit users somehow randomly, maybe you could run CorsixTH always with gdb or another debugger (i am not sure which is perfect for lua and luajit)

**Comment by bobcanthelpyou** [comment]
```
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The frame handler.
A stack trace is included below, and the handler has been disconnected.
^C
Program received signal SIGINT, Interrupt.
0x00007ffff7659028 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
(gdb) info stack
#0  0x00007ffff7659028 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#1  0x00007ffff76644aa in lua_getstack () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#2  0x00007ffff769741e in luaL_traceback () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#3  0x00007ffff7697672 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#4  0x00007ffff7656a88 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#5  0x0000000000477a95 in CorsixTH_lua_main (L=0x40000378) at /home/bob/dev/Games/CorsixTH/CorsixTH/Src/main.cpp:184
#6  0x00007ffff7656a88 in ?? () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#7  0x00007ffff7699f60 in lua_pcall () from /usr/lib/x86_64-linux-gnu/libluajit-5.1.so.2
#8  0x00000000004357c3 in main (argc=1, argv=0x7fffffffe258) at /home/bob/dev/Games/CorsixTH/CorsixTH/SrcUnshared/main.cpp:85
```

**Comment by TheCycoONE** [comment]
It appears based on these traces that the freeze is within lua and not C++.  It's still possible that an issue running the frame handler which causes lua to freeze / infinite loop afterwards rather than crashing immediately.

**Comment by bobcanthelpyou** [comment]
I running the game with Lua 5.1 for some week now and i can't see similar crashes with it. Maybe it is a problem with Luajit or the problem is already fixed. I will switch back to Luajit and try to reproduce the issue with it.

**Comment by bobcanthelpyou** [comment]
Back to Luajit 2.0.3 the game is crashing like before, the problem still exists. Is there another way to find the reason for the freezes with Luajit? It seems these issues can't be reproduced with Lua, only.

**Comment by TheCycoONE** [comment]
@bobcanthelpyou have you tried this in luajit recently? I'm curious if it was related to #709

**Comment by bobcanthelpyou** [comment]
@TheCycoONE can't reproduce the issue and can't figure out which commit fixed it. Could use Luajit (2.0.3 & 2.0.4) without any trouble.
