### ISSUE TITLE
Patient with serious radiation at research department

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#757]
The shower to heal the serious radiation is already researched. Possible i send a patient to the research department and when the patient arrived it was already researched (but i could be wrong). 

I only could send the patient home. If the shower is already researched, the patient should not access or leave the research department and visit the shower. Or do something different instead of waiting for the death.

http://filebin.ca/25vd3snDvgiG/stuck.sav

CorsixTH trunk (master branch)

**Comment by MarkL1961** [comment]
do you have the save from before he went to research?
Was he already on the way there when you researched and built the room?

**Comment by bobcanthelpyou** [comment]
I have a savegame before that issue occurs but i can't reproduce it.

If serious radiation is already researched then a doctor also take attention to the patient

Maybe something happens to the doctor with the attention, and then nobody else take care of the patient. Sometimes a doctor starts wandering around and don't leave the room he is in, like here #505 maybe that happened here too. But it doesn't happen here.

But you could force the issue, send the patient to the research department and pick up the doctor with the attention and put the doctor to the staff room. Now the patient is waiting until he is dead ...

Is there also a 'todo' list for doctors as there are for handymen? described here: https://github.com/CorsixTH/CorsixTH/issues/388#issuecomment-113790765 

If a doctor lost his attention somebody else should take care of the patient.

http://filebin.ca/25zcuEEapkSl/beforestuck.sav

**Comment by MarkL1961** [comment]
This is as I thought, you get the fax, send him to the research and just after this the shower is researched before he gets there.  I think to get the error it would be bad timing/edge case.  It might even be the researcher with the task of putting him in autopsy leaves the room and the task is not reassigned as it should be

**Comment by bobcanthelpyou** [comment]
It doesn't matter if the shower is researched before, he will also be put inside the autopsy machine.

The problem is the researcher that leaves the room (for a break, fired, ..) and the task is not reassigned to a different researcher.
