### ISSUE TITLE
Nobody can go in or out of the GP's office

### ISSUE THREAD

**Issue by mrtnptrs** [CorsixTH/CorsixTH#76]
Strangely, you continouly see the docor walking the same every time, but he never leaves the room. A handyman wants to water the plant inside this room, but can't. And when you place an another doctor or handyman, he can't also get out of the room.

Save: https://drive.google.com/file/d/0Bwc5O5IR0pMpWEtESzBzNEVEaW8/edit?usp=sharing

**Comment by TheCycoONE** [comment]
#193 possibly related.

**Comment by mugmuggy** [comment]
Closing as the reserved door issue has been addressed
