### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by ihithim** [CorsixTH/CorsixTH#775]
Gog version - music plays, black screen with error message top left:-

An error has occured in CorsixTH:
D:\Games\CorsixTH\Lua\audio.lua:235: bad argument #3 to 'setCamera' (number has
no integer representation)
stack traceback:
        [C]: in method 'setCamera'
        D:\Games\CorsixTH\Lua\audio.lua:235: in method 'initSpeech'
        D:\Games\CorsixTH\Lua\app.lua:414: in method 'initLanguage'
        D:\Games\CorsixTH\Lua\app.lua:232: in method 'init'
        D:\Games\CorsixTH\CorsixTH.lua:135: in main chunk
        [C]: in ?
D:\Games\CorsixTH\Lua\audio.lua:676: attempt to index a nil value (field 'ui')

**Comment by TheCycoONE** [comment]
Thanks @ihithim 
Based on the error I assume this is 0.50 beta 1.  Could you tell me what resolution you are playing at?

**Comment by ihithim** [comment]
Hiya, sorry: it is indeed 0.50 beta 1. 
For reference, I am on a unusual resolution of 3440x1440 (one of those superwide screens)

**Comment by TheCycoONE** [comment]
Alright, I can't test that specific resolution but I believe my resolution pr will solve that. Of course please verify on beta 2 when it's out.
