### ISSUE TITLE
Why is the 'Visitor Count' and the 'Number of times hardware used' different?

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#779]
There where three patients in the Inflator room, but the 'Number of times hardware used' shows six uses. Why are these counters different?

![bildschirmfoto von 2015-07-03 13 39 47](https://cloud.githubusercontent.com/assets/4523264/8498776/353d5b1c-218b-11e5-905b-22354185a3df.png)

**Comment by MarkL1961** [comment]
Can you share the save?

**Comment by bobcanthelpyou** [comment]
I did not edit the room, i just build it. 3 patients came .. 

It is also a problem with other rooms. It is the Confined scenario, where i remove and rebuild rooms very often cause of the lack of space.

**Comment by bobcanthelpyou** [comment]
save: http://www.xup.to/dl,45797095/counter.sav/

**Comment by TheCycoONE** [comment]
This save doesn't have an inflator. It has a scanner but the visitor count there is quite high (139).  It also appears to crash when showing the room information, but that's unrelated to this.

**Comment by MarkL1961** [comment]
I'm baffled as I can't reproduce it.  Editing the room does reset the machine usage, but this is the other way around so it can't be to do with that.
Are you sure that queue menu is for the same room?

**Comment by bobcanthelpyou** [comment]
@TheCycoONE i downloaded the file and loaded it within CorsixTH, there is a Inflator room inside. And the room queue and the uses of the Inflator are different.

I am using the latest trunk version from the Git master branch on a Debian Linux 64bit. Do you use a game with a different savegame version (Savegame version is 102) which could lead to the crash? Can't reproduce it here.

@MarkL1961 what are the values of the 'Number of times hardware used' and the 'Visitor Count' of my savegame?

**Comment by MarkL1961** [comment]
I didn't look at your save after reading @TheCycoONE comments about the save not having an inflator.

I'll check it out tonight

**Comment by MarkL1961** [comment]
@bobcanthelpyou 
Has an earthquake occurred in this game?
Earthquakes can damage machines and this will appear as uses until there are none left then boom the machine is soot

**Comment by bobcanthelpyou** [comment]
Ah that should be the reason, thx
