### ISSUE TITLE
Block diagram 

### ISSUE THREAD

**Issue by driverpt** [CorsixTH/CorsixTH#782]
I don't know if you have any. But if you don't, can you please create a block diagram of how the layers and components interact with each other (e.g.: how the lua connects to c++/sdl)

**Comment by Alberth289346** [comment]
There is no diagram, and I wouldn't be able to make one quickly either.

C++ side of things is in CorsixTH/Src. Lua interface is in *lua*cpp files, with gfx, anims, and sdl being obvious candidates. Lua instantiates the class, and manages its lifetime.
At the CorsixTH/Lua side, everything is an animation, app or world.lua instantiates the class, and manages (I don't know how exactly) the running animations.

For further detail questions, I'd suggest you use the google forum or perhaps IRC, as that is a better place to discuss such topics.

**Comment by driverpt** [comment]
Hello Alberth,

I'm not saying do it quickly. I'm just suggesting because it will make it
faster for the developers to "catch the train".

I'll analyze the code and try to extract a block diagram on draw.io

**Comment by J-Shep** [comment]
I've made a few UML diagrams to depict how this game works for singleplayer games for the analysis section of my multiplayer design document #386. I will post links to them when they are finished.
