### ISSUE TITLE
crash on startup -bad argument #3 to setcamera

### ISSUE THREAD

**Issue by wouterx** [CorsixTH/CorsixTH#783]
I have the same problem as the guy who posted about this on the forum. He did not create an issue as advised, so I will.

Game does not start all the way:  logo, then black screen with message. music keeps playing but message says:

-audio.lua:235: bad argument #3 to setcamera (number has no integer representation)

-0.50 beta (tried fresh install, and also upgrade from 0.40)
-origin on the house data
-installed the vcredist, and rebooted
-win 8.1 32bit

**Comment by TheCycoONE** [comment]
Duplicate of #775
