### ISSUE TITLE
Unicode languages do not work

### ISSUE THREAD

**Issue by adam900710** [CorsixTH/CorsixTH#785]
Although simplified_chinese.lua and traditional_chinese.lua is in "/usr/share/CorsixTH/Lua/languages" directory, I still can't select these two languages.

I installed the requested libs, especially freetype2 mentioned by the wiki, before compiling, but still not work.

Any clue?

Thanks.

**Comment by TheCycoONE** [comment]
Have you set the font in the config file to one that supports Chinese. Also what OS is this?

**Comment by adam900710** [comment]
I set the font path to wqy-microhei.ttc, which is my daily use font.
But still not work.

OS is linux, distribution is Archlinux.

Thanks

Stephen E. Baker wrote on 2015/07/05 15:46 -0700:

**Comment by TheCycoONE** [comment]
I'm getting a segfault when I try to use a unicode font:
```
THRenderTarget::createTexture (this=0x0, iWidth=60, iHeight=13, pPixels=0x13cd230)
CorsixTH/Src/th_gfx_sdl.cpp:635
SDL_Texture *pTexture = SDL_CreateTexture(m_pRenderer, m_pFormat->format, SDL_TEXTUREACCESS_STATIC, iWidth, iHeight);
```

**Comment by TheCycoONE** [comment]
Full backtrace:

```
Program received signal SIGSEGV, Segmentation fault.
0x000000000047c996 in THRenderTarget::createTexture (this=0x0, iWidth=37, 
    iHeight=13, pPixels=0x1b02e90)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_gfx_sdl.cpp:635
635	    SDL_Texture *pTexture = SDL_CreateTexture(m_pRenderer, m_pFormat->format, SDL_TEXTUREACCESS_STATIC, iWidth, iHeight);
(gdb) bt
#0  0x000000000047c996 in THRenderTarget::createTexture (this=0x0, iWidth=37, 
    iHeight=13, pPixels=0x1b02e90)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_gfx_sdl.cpp:635
#1  0x000000000047ed7b in THFreeTypeFont::_makeTexture (this=0x18829c8, 
    pEventualCanvas=0x0, pCacheEntry=0x1882d60)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_gfx_sdl.cpp:1538
#2  0x000000000046c456 in THFreeTypeFont::drawTextWrapped (this=0x18829c8, 
    pCanvas=0x0, sMessage=0x15c4948 "Magyar", iMessageLength=6, iX=0, iY=0, 
    iWidth=2147483647, pResultingWidth=0x7fffffffe0cc, pLastX=0x0, 
    eAlign=Align_Left)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_gfx_font.cpp:734
#3  0x000000000046b4f1 in THFreeTypeFont::getTextSize (this=0x18829c8, 
    sMessage=0x15c4948 "Magyar", iMessageLength=6, pX=0x7fffffffe0cc, 
    pY=0x7fffffffe0c8)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_gfx_font.cpp:489
#4  0x0000000000440224 in l_font_draw (L=0x13bf298)
    at /home/stephen/CorsixTH/CorsixTH/Src/th_lua_gfx.cpp:346
#5  0x00007ffff768f950 in ?? () from /usr/lib/liblua.so.5.3
#6  0x00007ffff769c7bd in ?? () from /usr/lib/liblua.so.5.3
#7  0x00007ffff768fbc0 in ?? () from /usr/lib/liblua.so.5.3
#8  0x00007ffff768f2b2 in ?? () from /usr/lib/liblua.so.5.3
#9  0x00007ffff768fde4 in lua_resume () from /usr/lib/liblua.so.5.3
#10 0x00000000004704fe in l_mainloop (L=0x6df718)
```

As discussed on irc, we should be caching a surface instead of a texture so the renderer is not necessary.

**Comment by TheCycoONE** [comment]
@adam900710 To address your concern, once pr #787 is in place you should be able to set ```unicode_font = [[/usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc]]``` and see the Chinese language options. Tested in Arch Linux x86_64.

**Comment by adam900710** [comment]
Thanks Stephan, but that's what I did first, and then I still can't 
select Chinese.

And if I choose Chinese through config by force, it just tells me that 
it can't load the font.

Anyway, I'll try it again later.

Thanks

Stephen E. Baker wrote on 2015/07/08 18:58 -0700:

**Comment by Alberth289346** [comment]
Paths have to be exactly correct to work.The leading / is crucial, as is having no spaces between the path and the [[ and ]] brackets.

An easy way to test paths is to 'ls' them in a shell

    ls -l /usr/share/fonts/wenquanyi/wqy-microhei/wqy-microhei.ttc

where you copy the file path from with a paste, so you don't make typing errors.
If the path is right, you'll get a line telling you owners, and size of the file. If the path is wrong, you'll get an error saying the file doesn't exist.

**Comment by adam900710** [comment]
Thanks for the hint from Alberth.
I thought I found the problem.

If I edit the config file and set the font option to absolute path of the font, it works without problem.

The real cause is, if you goes *in-game font file selector* , which I did at first, then font path in
config file will lose the leading '/', causing CorsixTH consider it as a relative path, and fail to load the font.

**Comment by Alberth289346** [comment]
That shouldn't happen, something goes wrong in the path handling thus.
Thanks for reporting.

**Comment by TheCycoONE** [comment]
Reopening because of the additional font selector path issue.

**Comment by TheCycoONE** [comment]
I can confirm that the root ```/``` is not included in Linux. In windows the path is created properly.
This issue does not affect any of the directory lookup widgets.
