### ISSUE TITLE
Room queue and mouse over room

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#789]
![bildschirmfoto von 2015-07-11 10 49 11](https://cloud.githubusercontent.com/assets/4523264/8633130/dbd56d04-27ba-11e5-96e0-cff80b4a07c3.png)

When the room queue is opened it is sometimes over the room (mostly when it is a large room and the room is more or less in the center of the screen), now when i try to move a patient and i mouse over the room at the same time, the icons over the patients change. But this behavior is bad, when patients with unhappy smileys or skulls should be moved.

This only should happen when i mouse over the room directly and not when an other window like the room queue is between the mouse pointer and the room.

Not sure if the icons should change within the room queue when mouse over the room, but this also could be a feature to show 'this room queue belongs to a special room'.

**Comment by mugmuggy** [comment]
GameUI:onCursorWorldPositionChange isn't hit testing the UI components for the queuing over room logic, pretty simple fix this one.

**Comment by TheCycoONE** [comment]
Fixed by #1314
