### ISSUE TITLE
Pick up square and mouse over items

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#790]
When i try to pick up an item (when editing a room) there is a red square on the ground but this square is very often wrong placed. I thing that it should help to select items more easily, but at the moment i could only pick up an item when the mouse pointer is directly over the item.

When i pick up a radiator it is sometimes like the following but i expect the red square on the ground where the radiator is standing (and not outside the building):
![bildschirmfoto von 2015-07-11 11 33 34](https://cloud.githubusercontent.com/assets/4523264/8633296/1bb9a3bc-27c1-11e5-8256-3a6b458e64de.png)

Here is the red square on the area where the radiator is standing, but i will pick up the bed. The red square should be under the bed.
![bildschirmfoto von 2015-07-11 11 33 49](https://cloud.githubusercontent.com/assets/4523264/8633298/21182dce-27c1-11e5-90f5-001aa2fd353c.png)

**Comment by lewri** [comment]
Merged into meta
