### ISSUE TITLE
Suggestion: reputation cheat

### ISSUE THREAD

**Issue by mrtnptrs** [CorsixTH/CorsixTH#80]
When I want to test level 12, It is very hard to have your reputation above the 450. Especially with testing this is very irritating. Couldn't we add an reputation cheat that highers your reputation with a value like 25, 50 or 100?

**Comment by fusionstream** [comment]
What is the reputation variable?

**Comment by lewri** [comment]
> What is the reputation variable?

It is the standing of your hospital in the community essentially.
https://github.com/CorsixTH/CorsixTH/wiki/Game-Guide#reputation-meter

**Comment by fusionstream** [comment]
> > What is the reputation variable?
> 
> It is the standing of your hospital in the community essentially. https://github.com/CorsixTH/CorsixTH/wiki/Game-Guide#reputation-meter

Haha. Nice one.

I mean what is the name of the variable when accessing it from the in game lua console?

I've tried Hospital.unconditionalChangeReputation(100) but it doesn't work so I was wondering if the variable itself was accessible like @sadger mentioned.

**Comment by lewri** [comment]
No worry. You can check the function here:
https://github.com/CorsixTH/CorsixTH/blob/6322c991b8bbb654548efdedf6edb4a5d3261a66/CorsixTH/Lua/hospital.lua#L1644-L1663

As the function has a `:` declaration, it will expect `self` to be passed to it. You can do this in two ways. But first you need to determine a route to get the local player hospital. The route you take depends what the class knows (defined usually in the main class function e.g. `World:World`; `Patient:Patient` etc).
```lua
local hosp = self.hospital
local hosp = self.ui.hospital
local hosp = self.world:getLocalPlayerHospital()
```
If you're adding to the Hospital class, you're just going to call `self` instead. See below for implementation options

```lua
hosp:unconditionalChangeReputation(100) -- colon (:) carries self in automatically
hosp.unconditionalChangeReputation(hosp, 100) -- note how we pass self in if we use a dot (.)

-- If you're already in Hospital
self:unconditionalChangeReputation(100)
```

Hope that helps. If you need more discussion or support it may be better to message our Technical channel or Discord or Matrix as we'll be necroing an old issue commenting here. Alternatively, raise a Discussion post via Github.

Edit: I only just saw the lua console bit. You would want `local hosp = TheApp.world:getLocalPlayerHospital()` to get your hospital class to target. Or if it's just a simple play around you can use `local hosp = TheApp.world.hospitals[1]` as that currently is always the current player.

**Comment by fusionstream** [comment]
Got it tyvm! Not very familiar with lua.

This does come up as one of the first when searching for reputation though.

So for posterity,
```
local hosp = TheApp.world.hospitals[1]
-- reputation change is relative so 50 is +50
hosp.unconditionalChangeReputation(50)
```
or
```
TheApp.world.
hospitals[1]:unconditionalChangeReputation(50)
```
or

`TheApp.world.hospitals[1]:unconditionalChangeReputation(50)`
