### ISSUE TITLE
Zoom out and the bottom panel is moving

### ISSUE THREAD

**Issue by ghost** [CorsixTH/CorsixTH#805]
When zoom out the bottom panel start to move inside the screen.

![bildschirmfoto vom 2015-07-16 09 25 15](https://cloud.githubusercontent.com/assets/4523264/8717557/fa1d4c92-2b9c-11e5-9fb1-8e2cffb7ec74.png)

I am running CorsixTH trunk (master branch) with Lua 5.1 and a screen resolution of 1024x500 (on a netbook), the OS is Debian Jessie 32bit

**Comment by TheCycoONE** [comment]
I do not see this with Lua 5.3 on Windows with a screen resolution of 600x800.  Would need to do more testing to isolate what condition causes it.

Also, please specify what commit hash you are using if you are using a non-release version. You can get this with ```git rev-parse --short HEAD``` or from the top of ```git log``` or ```git show```

**Comment by bobcanthelpyou** [comment]
Could only reproduce the issue when the screen height is equal or lower than 636

Sometimes i have to maximum zoom out and zoom in one step and it looks like the screenshot

Tested with CorsixTH trunk de27e4d77a80495d47cb3ac14849c546e7d393b3

**Comment by TheCycoONE** [comment]
At least on Windows (DirectX) I'm unable to replicate, with the same resolution you are using. I also don't get the artifacts around my tiles.

![corsix-1024x500-zoom](https://cloud.githubusercontent.com/assets/823433/8759591/4d828964-2cc5-11e5-8054-24a03eab4e74.png)

Perhaps this only affects OpenGL/Linux?

**Comment by bobcanthelpyou** [comment]
It only occurs when the zoom factor is lower that 0.32 in the function GameUI:setZoom(factor)
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/game_ui.lua#L114

When the issue occurs and i quit the game (with the shortcut Shift + q and Enter), the screen looks like that:

![bildschirmfoto von 2015-07-18 08 11 47](https://cloud.githubusercontent.com/assets/4523264/8760575/2d391cda-2d25-11e5-955b-de9f07ef70e8.png)

**Comment by bobcanthelpyou** [comment]
Could also reproduce it with Windows 7, 32 bit, 1280x500 and a Intel 965GM graphic card 

![bug](https://cloud.githubusercontent.com/assets/4523264/8760744/8e4f86b4-2d2d-11e5-924c-9a25588c120d.png)

**Comment by MarkL1961** [comment]
I have this happen and can also lose the bottom menu altogether.
I found this happens when I have selected a resolution my computer display was not designed to run.  When I do I also see the artifacts @TheCycoONE  has mentioned.

**Comment by TheCycoONE** [comment]
For all you people that can reproduce this, could you see if you get a false from canvas:scale when this happens:
https://github.com/CorsixTH/CorsixTH/blob/master/CorsixTH/Lua/game_ui.lua#L150

**Comment by TheCycoONE** [comment]
What looks to be happening is that it's failing to render to the zoom texture. When that happens the scale is not reset, but applies to the entire window instead.

I'm attaching a PR that will reset the scale and output a warning to the console when that happens. I won't be able to test it myself, but I'll link to the travis build once it's done.

**Comment by TheCycoONE** [comment]
Unfortunately it doesn't seem like the build was put up on http://www.armedpineapple.co.uk/cth/builds/
If someone can reproduce, they can build themselves (master >= 1c4bc2381)

**Comment by bobcanthelpyou** [comment]
canvas:scale is never false when that happens.

Also there is no output on the console for me with https://github.com/CorsixTH/CorsixTH/commit/1c4bc2381a651077544c66779a16e35994edecdc when reproducing the issue

**Comment by TheCycoONE** [comment]
I am able to reproduce *only* in full screen mode when running the game in a non-native resolution. After zooming the game changes to native resolution, but the bottom panel appears where it would be on the set resolution. A some zoom levels (zooming in) the map shrinks to just the set resolution size (in the top left corner), and after exiting, the menu does as well.

I think this is a result of not factoring in the pseudo resolution full screen stretch (we don't switch screen modes) when calculating or resetting the zoom scale.
