### ISSUE TITLE
Automatically select unicode font from system if available

### ISSUE THREAD

**Issue by caoli5288** [CorsixTH/CorsixTH#817]
This is official language supported lang.

**Comment by bobcanthelpyou** [comment]
Did you specify a font file with unicode support for Chinese characters in the settings-folders game menu or the config.txt-file?

```
-- Font file setting. Can be changed from main game menu
-- Specify a font file here if you wish to play the game in a language not
-- present in the original game. Examples include Russian, Chinese and Polish.
--
unicode_font = [[C:\Windows\Fonts\yourfont.ttf]]
```

**Comment by GlimpseOpen** [comment]
You need the Unicode version of NSIS which is required to support other languages such as Chinese, Russia etc. Read the "Readme.txt" file at
https://github.com/CorsixTH/CorsixTH/tree/master/WindowsInstaller

**Comment by caoli5288** [comment]
> Did you specify a font file with unicode support for Chinese characters in the settings-folders game menu or the config.txt-file?

Yes, I specify adobe-source-font in settings, but there is no chinese lang to select.

**Comment by caoli5288** [comment]
I see this is a origin bug, I select font file what path is [[/usr/share/fonts/...]] but what store in config.txt is [[usr/share/fonts/...]].
After change it everything works.

**Comment by Alberth289346** [comment]
Thanks for the report, that problem was found recently, and has been fixed in #803. It will should work in the next release.

Have fun playing! :)

**Comment by caoli5288** [comment]
A in-game message is needed, or select system default font automatic.

**Comment by TheCycoONE** [comment]
I don't disagree with the last suggestion.  What is currently done is that a default hard coded windows path and a default hard coded linux path are checked if unicode_font in nil, but even on Windows 8 those paths are wrong.

I don't know how one automatically finds a true type font with good unicode coverage (on a number of different operating systems), but web browsers can do it so it must be possible.

**Comment by TheCycoONE** [comment]
Probably cleaner if I open a new issue actually.
