### ISSUE TITLE
0.50 beta 2 - room.lua:699: attempt to perform arithmetic on a boolean value

### ISSUE THREAD

**Issue by zsolmanz** [CorsixTH/CorsixTH#819]
**What steps will reproduce the problem?**
1. Load provided autosave game file of Level 10 Eggsenham
2. Purchase south/eastern plot for $6750
3. Build Operating Theatre within that plot
1. Alternatively, load "Can't build" save game file of Level 10 Eggsenham and repeat test.

**What is the expected output? What do you see instead?**
Operating Theatre should build without issue, as it does in other plots (limited testing) and as other rooms do within this plot (limited testing).
Instead, game throws "No event handler for button up" issue.
With the "Can't build" save game file, it also tends to throw a "No event handler for timer" issue, and ask whether a recovery attempt should be made.  Obviously you can't click the tick to make a recovery with a button up error, but it's a nice thought.

**What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?**
0.50 beta 2

**What operating system / compile settings are you using?**
Windows 8.1 64bit, based on the GOG game files.

**What level was this on (e.g. "Demo level", "Full game level 12")?**
Full game level 10, Eggsenham

**Upload a saved game file (preferably an autosave from before the error) if you
have one and it is relevant... If possible, also upload the gamelog. Look at HOW TO UPLOAD GAMELOG AND/OR SAVES for how to do this:**
You need to update your CONTRIBUTING.txt to explain where to find this stuff is - I wouldn't have known to look in AppData\Roaming for it.
The files are [**here**](https://drive.google.com/open?id=0BzMXwT_4ohHBfkNTcjlYQzQxdlZNcTBsdDRPOWpoOUUxMTlnWkFHci1Dc2NObHFGdVl6a3M).

**Please provide any additional information below:**
There's a stuck handyman in decontamination from an earlier (recovered) error, but to my knowledge he hasn't caused any issues besides making it impossible to build upon his square if you delete the room.
It's worth highlighting that this issue is unrecoverable simply by nature of preventing all mouse-clicks.

**Comment by Alberth289346** [comment]
Good point about the CONTRIBUTING.TXT

Copied the stack dump for easier access, can't upload the savegame unfortunately.
Thanks for the report.

````
Warning: Trying to remove nonexistant room build callback (function: 00000084F8448530) from humanoid (table: 00000084FD43C260).
Warning: Trying to remove nonexistant room remove callback (function: 00000084814C38B0) from humanoid (table: 00000084FD43C260).
Warning: Trying to remove nonexistant room build callback (function: 00000084FE034450) from humanoid (table: 00000084FE698B30).
Warning: Trying to remove nonexistant room remove callback (function: 00000084FD82BAD0) from humanoid (table: 00000084FE698B30).
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\entity.lua:118: Suspected infinite loop
stack traceback:
	[C]: in function 'error'
	C:\Program Files\CorsixTH\Lua\app.lua:797: in hook '?'
	C:\Program Files\CorsixTH\Lua\entity.lua:118: in method 'setTile'
	C:\Program Files\CorsixTH\Lua\entity.lua:174: in method 'setTilePositionSpeed'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:175: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:575: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:651: in method 'queueAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\meander.lua:94: in field '?'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:575: in upvalue 'Humanoid_startAction'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:667: in method 'finishAction'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	C:\Program Files\CorsixTH\Lua\entity.lua:218: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>
Recovering from error in timer handler...
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:60: attempt to call a nil value (local 'timer_function')
stack traceback:
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:60: in local 'on_interrupt'
	C:\Program Files\CorsixTH\Lua\entities\humanoid.lua:638: in method 'setNextAction'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:421: in method 'onClick'
	C:\Program Files\CorsixTH\Lua\ui.lua:626: in function <C:\Program Files\CorsixTH\Lua\ui.lua:609>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>
Savegame version is 102 (Trunk), originally it was 91 (0.40)
Savegame version is 102 (Trunk), originally it was 91 (0.40)
Savegame version is 102 (Trunk), originally it was 91 (0.40)
Savegame version is 102 (Trunk), originally it was 91 (0.40)
Error in buttonup handler: 
C:\Program Files\CorsixTH\Lua\room.lua:699: attempt to perform arithmetic on a boolean value
stack traceback:
	C:\Program Files\CorsixTH\Lua\room.lua:699: in method 'tryToFindNearbyPatients'
	C:\Program Files\CorsixTH\Lua\room.lua:673: in function <C:\Program Files\CorsixTH\Lua\room.lua:655>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\world.lua:859: in method 'markRoomAsBuilt'
	C:\Program Files\CorsixTH\Lua\dialogs\edit_room.lua:245: in local 'callback'
	C:\Program Files\CorsixTH\Lua\window.lua:664: in method 'handleClick'
	C:\Program Files\CorsixTH\Lua\window.lua:1445: in field 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:454: in function <C:\Program Files\CorsixTH\Lua\dialogs\place_objects.lua:453>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\window.lua:1429: in field 'onMouseUp'
	C:\Program Files\CorsixTH\Lua\ui.lua:622: in function <C:\Program Files\CorsixTH\Lua\ui.lua:609>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>
````

**Comment by TheCycoONE** [comment]
Is it possible that you blocked off part of your hospital? That could cause the stuck handyman and this error.

**Comment by zsolmanz** [comment]
The stuck handyman was repairing the decontamination unit when he became stuck - hence he's in the middle of the hospital.  I fired him anyhow, so he shouldn't really be interacting with much.  Anyway, I've yet to find a way to block off parts of the hospital - the game prevents placement of objects that would do this.

I would say the error is related to the Operating Theatre patient queue, since it's the only room that produces this error, but since it doesn't occur when you build the OT in a different plot I'm at a loss.

**Comment by TheCycoONE** [comment]
When you build a new room it loops through all the other rooms in the hospital looking for patients that maybe should be redirected to the newly created room.

This error is happening when checking the distance of people at the back of the queue for an old room with the people at the back of the queue for this newly created room. It appears (though I haven't yet run a debugger to be 100% certain) that world:getPathDistance() is not returning a number in one of those look ups. Will need to check with a debugger to determine why that is. I suspect either a room doesn't have a location, a patient doesn't have a location, or there is no path from the patient to the room (all of which would be a sign of another bug, because none of those things should be possible)

**Comment by MarkL1961** [comment]
The reason you can't build in that plot from I can see is it is blocked off by the bench, drinks machine and radiator.  Move those objects and you should be fine.
![blocked](https://cloud.githubusercontent.com/assets/4965487/8858710/d73effb6-3170-11e5-9fa6-094eb65d9c08.png)

**Comment by TheCycoONE** [comment]
Thanks @MarkL1961 , so this is one of those cases where it shouldn't be possible to block a path but the checks aren't working correctly.

**Comment by TheCycoONE** [comment]
It's somewhat related to #491 and if the suggestion in that issue (to make the tiles next to purchase points unbuildable) was implemented then this issue couldn't happen.

**Comment by MarkL1961** [comment]
No, the check is correct.
At the time the items are placed they are against the wall, and I think that should be possible.  There are hospitals where you can and would want to build a room at the joining point, so I don't see why that should be banned either.
I think the player should be prepared to either remove objects or rooms if they block areas when new plots are purchased.  In TH it was actually possible to block off areas of the hospital and I think it is only disallowed in corsixth because of the path finding code.

**Comment by TheCycoONE** [comment]
There is a lot of code in CorsixTH that assumes nothing is ever blocked off, but I suppose removing that assumption is another possibility.

In the original was it possible to trap patients too?

**Comment by MarkL1961** [comment]
Perhaps the solution is to disallow the purchase of that plot until the corridor is cleared?
A message could be shown to say you cannot buy this plot as it does not have access to the main hospital.

**Comment by MarkL1961** [comment]
Yes, because the advisor would say you should plan your hospital better as someone was stuck or something like that.

**Comment by MarkL1961** [comment]
It was also possible to trap staff, an easter egg was where the handyman turns into a yeti if he is trapped

**Comment by TheCycoONE** [comment]
I think a goal for CorsixTH then should be to not complain so much about blocked paths. There are good reasons to do so, like containing people to the heated parts of the hospital.

**Comment by TheCycoONE** [comment]
Which is to say we'll directly fix this bug (the error when there isn't a path), instead of preventing the blocked path. In the mean time there is a workaround as pointed out by MarkL @zsolmanz

**Comment by MarkL1961** [comment]
Agreed, this has been an issue for several years, it has come up a lot, so it would be nice to mimic TH behaviour instead of disallowing something that players like to use to as you said to partition off parts of the hospital,

**Comment by TheCycoONE** [comment]
I've made a small fix for the error in the stack trace, and another one that happens just afterwards. As soon as you try to add staff though the whole thing gets quite a bit more complicated but I think that all the problems should be tracked through separate issues so the overall problem can be fixed in stages?
