### ISSUE TITLE
0.50 beta 2 - map.lua:438: bad argument #3 to 'draw'

### ISSUE THREAD

**Issue by zsolmanz** [CorsixTH/CorsixTH#820]
**What steps will reproduce the problem?**
1. Load provided autosave from Level 10 - Eggsenham
2. Clear End-of-Year Report (unpause)
3. Wait 16.5s

**What is the expected output? What do you see instead?**
The game ought to continue working.
Instead, the game appears to freeze (visually).  Outside door movements and receptionist announcements (as well as some cure-cheers and patient noises like coughs) can still be heard.

**What version of CorsixTH are you using (e.g. "0.30", "4c66e39985")?**
0.50 beta 2

**What operating system / compile settings are you using?**
Windows 8.1 64bit, based off GOG game files.

**What level was this on (e.g. "Demo level", "Full game level 12")?**
Full game level 10 - Eggsenham

**Upload a saved game file (preferably an autosave from before the error) if you
have one and it is relevant.  If possible, also upload the gamelog.**
See [**here**](https://drive.google.com/open?id=0BzMXwT_4ohHBfkFLRUNvSUZ1WGZpRnk4VmpLYTVjb244bFBmQjdhOEQwcE9ia3NiT3pXSEE)

**Please provide any additional information below.**
The time taken for the error to be thrown is dependant on game speed, but I wouldn't have thought that frame rendering would be determined by anything in-game.  I really need to better familiarise myself with CorsixTH.

**Comment by zsolmanz** [comment]
The relevant stack traceback:

> Savegame version is 102 (Trunk), originally it was 91 (0.40)
> Error in frame handler: 
> C:\Program Files\CorsixTH\Lua\map.lua:438: bad argument #3 to 'draw' (number has no integer representation)
> stack traceback:
> 	[C]: in method 'draw'
> 	C:\Program Files\CorsixTH\Lua\map.lua:438: in method 'draw'
> 	C:\Program Files\CorsixTH\Lua\dialogs\patient.lua:136: in method 'draw'
> 	C:\Program Files\CorsixTH\Lua\window.lua:1277: in field 'draw'
> 	C:\Program Files\CorsixTH\Lua\game_ui.lua:153: in method 'draw'
> 	C:\Program Files\CorsixTH\Lua\app.lua:897: in function <C:\Program Files\CorsixTH\Lua\app.lua:890>
> 	(...tail calls...)
> 	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

**Comment by zsolmanz** [comment]
Upon further testing, editing the blood machine room (without actually doing anything except making it zzZZZ) prevents this error.  The same cannot be said for editing any other room (I checked).

**Comment by TheCycoONE** [comment]
Thanks for the error report!

**Comment by TheCycoONE** [comment]
I wasn't able to reproduce; I believe this issue may have already been fixed since 0.50 beta 2. The actual error relates to the positioning of the people in the door dialog you have open.
