### ISSUE TITLE
"Crash" (unknown cause, got the log though)

### ISSUE THREAD

**Issue by juef17** [CorsixTH/CorsixTH#827]
Greetings! I'm running CorsixTH Version 0.50 beta 2 for Windows and I encountered the following problem. I was in the level that's represented on the board by a derailing train, pretty zoomed out with no open window (I believe, anyway), and the game froze (video only, audio kept on playing correctly, with new sounds occuring). I Alt-Tabbed out, and the console window showed pretty much the same info as the gamelog.txt file:

    Created game with savegame version 102.
    Savegame version is 102 (Trunk), originally it was 102 (Trunk)
    Warning: Trying to remove nonexistant room build callback (function: 000000001388B250) from humanoid (table: 000000000B183200).
    Warning: Trying to remove nonexistant room remove callback (function: 000000000F56A900) from humanoid (table: 000000000B183200).
    Warning: Trying to remove nonexistant room build callback (function: 00000000137FCEF0) from humanoid (table: 000000000C5A0EA0).
    Warning: Trying to remove nonexistant room remove callback (function: 000000000C811010) from humanoid (table: 000000000C5A0EA0).
    Warning: Trying to remove nonexistant room build callback (function: 0000000015A9CA00) from humanoid (table: 000000001335A6D0).
    Warning: Trying to remove nonexistant room remove callback (function: 000000000ECD3980) from humanoid (table: 000000001335A6D0).
    Savegame version is 102 (Trunk), originally it was 102 (Trunk)
    Error in frame handler: 
    C:\Program Files\CorsixTH\Lua\map.lua:438: bad argument #3 to 'draw' (number has no integer representation)
    stack traceback:
    	[C]: in method 'draw'
    	C:\Program Files\CorsixTH\Lua\map.lua:438: in method 'draw'
    	C:\Program Files\CorsixTH\Lua\dialogs\patient.lua:136: in method 'draw'
    	C:\Program Files\CorsixTH\Lua\window.lua:1277: in field 'draw'
    	C:\Program Files\CorsixTH\Lua\game_ui.lua:153: in method 'draw'
    	C:\Program Files\CorsixTH\Lua\app.lua:897: in function <C:\Program Files\CorsixTH\Lua\app.lua:890>
    	(...tail calls...)
    	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

In case it is related, when I reloaded my game (with "Continue Game"), the "New offer at *** hospital" window was open. I did have the game on "... and then some more" speed and waited a minute before actually closing the game window, so perhaps it happened after the "video crash".

**Comment by TheCycoONE** [comment]
This has been reported before. We believe it's fixed in the latest master, please retest after the release candidate is released Sunday night!
