### ISSUE TITLE
Line breaks / paragraphs in tutorial text

### ISSUE THREAD

**Issue by juef17** [CorsixTH/CorsixTH#828]
Greetings! I'm running CorsixTH Version 0.50 beta 2 for Windows and I encountered the following problem. There seems to be line breaks at the wrong place in some (English) tutorial texts. I can provide screenshots if necessary.

**Comment by SimplyRyan** [comment]
Any screenshots would be very useful, please add them here and we can review.

**Comment by juef17** [comment]
Of course, sorry I didn't do this initially. In this example, I don't think the last two paragraphs should be separate.

![untitled](https://cloud.githubusercontent.com/assets/5288991/9141975/b889b98a-3d0a-11e5-906a-125b97e11996.png)

**Comment by Lego3** [comment]
This is because the current way of handling original texts is not optimal. My "Custom campaigns" pull request changes the behaviour of parsing original text blocks, if I can get the time I might try to break that pull request into smaller pieces.

**Comment by Alberth289346** [comment]
@Lego3  is this solved now?

**Comment by Lego3** [comment]
Yes, the sentences are no longer broken like that. There is a paragraph indent now, though, that I can't decide if it looks good or not...
