### ISSUE TITLE
Decimal for hospital value

### ISSUE THREAD

**Issue by juef17** [CorsixTH/CorsixTH#830]
Greetings! I'm running CorsixTH Version 0.50 beta 2 for Windows and I encountered the following problem. When checking the hospital value with the mouseover the corresponding graph, the hospital value has a point and decimal rather than being an integer.

**Comment by bobcanthelpyou** [comment]
Could you provide a screenshot please?

**Comment by juef17** [comment]
Of course! It appears the same is true for the bank balance, also.
![01](https://cloud.githubusercontent.com/assets/5288991/8889765/c07b7908-32b5-11e5-9959-99d766d51977.png)
![02](https://cloud.githubusercontent.com/assets/5288991/8889766/c07c2222-32b5-11e5-8992-00e1e0cbf13e.png)

**Comment by TheCycoONE** [comment]
I guess this is a change resulting from lua 5.3's new integer types. It should be fixable with explicit formatting strings: http://www.lua.org/manual/5.3/manual.html#pdf-string.format (use %d)
