### ISSUE TITLE
New GP office built: multi_use_object.lua:313: attempt to index field '?' (a nil value)

### ISSUE THREAD

**Issue by J-Shep** [CorsixTH/CorsixTH#832]
Reported by @bobcanthelpyou:

> > I moved the Pharmacy room and build a new GP's Office nearby and an error occurs:

```
Will not check for updates since this is the Trunk version.
Savegame version is 102 (Trunk), originally it was 102 (Trunk)
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/humanoid_actions/multi_use_object.lua:313: attempt to index field '?' (a nil value)
stack traceback:
    ./Lua/humanoid_actions/multi_use_object.lua:313: in function '?'
    ./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
    ./Lua/entities/humanoid.lua:667: in function 'finishAction'
    ./Lua/humanoid_actions/walk.lua:152: in function 'timer_function'
    ./Lua/entity.lua:218: in function 'tick'
    ./Lua/world.lua:1121: in function 'onTick'
    ./Lua/app.lua:876: in function <./Lua/app.lua:873>
    (tail call): ?
    ./Lua/app.lua:777: in function <./Lua/app.lua:772>

Error in timer handler: 
./Lua/humanoid_actions/multi_use_object.lua:313: attempt to index field '?' (a nil value)
stack traceback:
    ./Lua/humanoid_actions/multi_use_object.lua:313: in function '?'
    ./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
    ./Lua/entities/humanoid.lua:667: in function 'finishAction'
    ./Lua/humanoid_actions/walk.lua:152: in function 'timer_function'
    ./Lua/entity.lua:218: in function 'tick'
    ./Lua/world.lua:1121: in function 'onTick'
    ./Lua/app.lua:876: in function <./Lua/app.lua:873>
    (tail call): ?
    ./Lua/app.lua:777: in function <./Lua/app.lua:772>
Warning: No event handler for timer
```

> > savegame before error: http://www.xup.in/dl,10243463/congame2.sav/
> > savegame after error: http://www.xup.in/dl,94694418/conerror.sav/ (the room with the cast remover seems problematic)

**Comment by TheCycoONE** [comment]
What version is this error from?

**Comment by J-Shep** [comment]
He reported this 3 weeks ago by posting a comment in #362 because he thought he may have been related but these errors have different stack trace error messages and the cause of #362 isn't actually related to a room being moved. I've now deleted that comment and posted it here.

The stack trace says its from a trunk version with save game version 102.

**Comment by J-Shep** [comment]
I will try to fix this error today.

**Comment by J-Shep** [comment]
@bobcanthelpyou I think this error may have been caused by your Theme Hospital data files, where are they from? an English demo? (if so please provide a download link for it)

**Comment by bobcanthelpyou** [comment]
I am using a German full version of TH. It was part of the following games collection: http://www.amazon.de/PC-Games-Collection-Vol-1/dp/B00004TPL3/

What could be wrong with the data files of the game?

**Comment by J-Shep** [comment]
>> What could be wrong with the data files of the game?

Well in the past there was a problem with one of the lava hole sound effects in the sound DATs for some non English versions which would crash the game when it was played and as the developer who took on the task of fixing this I never found out exactly what the problem was but I did manage to fix this error by finding a way to prevent CorsixTH from getting stuck in an infinite loop when it would try to find the end of this sound effect's audio data.

Your error resulted from the cast removal machine having none of its animations for "Alternate Male Patients" so something went wrong with your game when it tried to load these animation from your TH .DAT files and the animation loading code is tried & tested so its unlikely to be at fault.

Please create a fracture clinic in a new closed hospital on the same map so you or I can check to see if its cast_remover machine successfully obtains all the animations for "Alternate Male Patients".

Lua/objects/machines/cast_remover.lua:
```
object.multi_usage_animations = {
  ["Alternate Male Patient - Nurse"] = copy_north_to_south {
    north = {
      begin_use    = 2720, -- Patient invited onto machine
      begin_use_2  = 2696, -- Machine closes
      begin_use_3  = 2692, -- Nurse introduces the almighty black bucket
      in_use       = 2688, -- The machine spits in the bucket
      finish_use   = 3662,  -- Nurse takes the bucket again (different tile than 3658!)
      finish_use_2 = 3658, -- The machine opens and the patient stands up
    },
  },
  ["Standard Female Patient - Nurse"] = copy_north_to_south {
    north = {
      begin_use    = 4658, -- Patient invited onto machine
      begin_use_2  = 4666, -- Machine closes
      begin_use_3  = 4670, -- Nurse introduces the almighty black bucket
      in_use       = 4674, -- The machine spits in the bucket
      finish_use   = 5112,  -- Nurse takes the bucket again
      finish_use_2 = 4682, -- The machine opens up and patient leaves
    },
  },
}
```

**Comment by J-Shep** [comment]
>> Your error resulted from the cast removal machine in your saved game having none of its animations for "Alternate Male Patients"...

I'm now repeating the test I did yesterday with the saved game from after the error and the cast remover does have all its animations for alternate male patients but when I tested this yesterday I was shown the same error message that was printed in your stack trace. I will find out why I'm now not experiencing this error.

**Comment by bobcanthelpyou** [comment]
As you could reproduce the issue by your self i don't have to do anything at the moment and my game data might not be the problem?

**Comment by J-Shep** [comment]
I'm not able to reproduce it myself now and maybe in my debug script test with your "after error" saved game before when a did experience an error it could have been caused by a mistake in my testing code. This is the debug script code I'm using now:
```
local fracture_clinic = nil
for _, room in pairs(TheApp.world.rooms) do
  if room.room_info.id == "fracture_clinic" then
    fracture_clinic = room
    break
  end
end

local object = nil
for current_object,_  in pairs(fracture_clinic.objects) do
  if current_object.object_type.id == "cast_remover" then
    object = current_object
    break
  end
end

local orient = object.direction
local flags = 0
if not object.object_type.multi_usage_animations["Alternate Male Patient - Nurse"][orient] then

end
```
The last if statement is a copy of the if statement in the multi_use_object script which experienced your error but when I run this script down with your after error saved game no error occurs and I can see with my Eclipse debugger that there's no problems with cast remover's mult_usage_animations table.

Please try to reproduce this error yourself and if you can then I would like you to provide me with a saved game from just before the use of the cast remover causes this error to occur.

**Comment by bobcanthelpyou** [comment]
Could reproduce it, a dead patient enters the cast remover room for unknown reason

```
Savegame version is 105 (0.50 rc1), originally it was 102 (0.50 rc1)
An error has occured!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
./Lua/humanoid_actions/multi_use_object.lua:313: attempt to index field '?' (a nil value)
stack traceback:
	./Lua/humanoid_actions/multi_use_object.lua:313: in function '?'
	./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
	./Lua/entities/humanoid.lua:667: in function 'finishAction'
	./Lua/humanoid_actions/walk.lua:152: in function 'timer_function'
	./Lua/entity.lua:218: in function 'tick'
	./Lua/world.lua:1121: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:875>
	(tail call): ?
	./Lua/app.lua:779: in function <./Lua/app.lua:774>

Error in timer handler: 
./Lua/humanoid_actions/multi_use_object.lua:313: attempt to index field '?' (a nil value)
stack traceback:
	./Lua/humanoid_actions/multi_use_object.lua:313: in function '?'
	./Lua/entities/humanoid.lua:575: in function 'Humanoid_startAction'
	./Lua/entities/humanoid.lua:667: in function 'finishAction'
	./Lua/humanoid_actions/walk.lua:152: in function 'timer_function'
	./Lua/entity.lua:218: in function 'tick'
	./Lua/world.lua:1121: in function 'onTick'
	./Lua/app.lua:878: in function <./Lua/app.lua:875>
	(tail call): ?
	./Lua/app.lua:779: in function <./Lua/app.lua:774>
```

savegame: http://filebin.ca/2BKBI2xhiOd8/crash4.sav

**Comment by J-Shep** [comment]
Thanks for reproducing this error and providing a saved game, I will investigate this asap. 

I've not been able to do any CorsixTH programming recently because my PC's hacker hacked my Ubuntu 15.04 install to interfere with my CorsixTH programming. I have a fresh Windows 10 install now so I hope I will be able to do CorsixTH programming for a while without interference. I will try to find a solution to my security problems.

**Comment by Alberth289346** [comment]
File of aug 7 reproduces in trunk commit a54ddfa a set of images:
![jan_12](https://cloud.githubusercontent.com/assets/3254232/10716405/6b7ea5e4-7b38-11e5-88d3-c5a23f625b99.png)
![jan_13](https://cloud.githubusercontent.com/assets/3254232/10716407/7cb5c84c-7b38-11e5-82e3-beba247bc2bc.png)
![jan_14](https://cloud.githubusercontent.com/assets/3254232/10716412/84f3515a-7b38-11e5-85c3-3bdec1049b9a.png)
![jan_15](https://cloud.githubusercontent.com/assets/3254232/10716414/93633552-7b38-11e5-8831-b4fbd7977955.png)

Fallen patient seems to be woken again (does the reaper do that??), and trying to visit the cast remover, except he has no cast. Animation that is searched is "anim_set = Standard Male Patient - Nurse", while only "Standard Female Patient - Nurse" and "Alternate Male Patient - Nurse" animations exist.

**Comment by MarkL1961** [comment]
Could that be down to the small space?  I think the patient falls, a hole appears which he is supposed to walk to and disappear into it.  The animation thing might be where it has to change for the disappearing part.  He should not continue on for any treatment and I am surprised the hole is so near to where he fell, but that could be down to the small space available.

**Comment by Alberth289346** [comment]
No, the animation thing is with the nurse, he stands up, knocks on the door and gets into position as shown in the last picture.

Interesting theory though, the pathfinder probably cannot find a path to walk to the hole, so he tries his last thing again or so?

**Comment by MarkL1961** [comment]
Hell deaths do need a bit of space, so I am surprised it did one there when it should really have switched to heaven death.

**Comment by Lego3** [comment]
Is it because the hole spawned underneath him?

**Comment by J-Shep** [comment]
Hi,

Has anyone taken over this task during my contribution hiatus?

**Comment by Alberth289346** [comment]
Hi again!
Nope nobody works on this.

I did see some fuzzy code in the grim reaper action when there wasn't enough space. I now think the dead person is trying to move into the hole by first going to a tile a bit west of it (in the room), but I haven't looked into it.

**Comment by J-Shep** [comment]
@Alberth289346 Thanks for the info and for replying to all my other posts today.

**Comment by TheCycoONE** [comment]
#1201 has the same stack trace and also involves the cast remover. I'm not sure if a hell death was involved. @l29ah can you clarify?

**Comment by l29ah** [comment]
On Tue, Apr 04, 2017 at 05:11:10AM -0700, Stephen E. Baker wrote:
> #1201 has the same stack trace and also involves the cast remover. I'm not sure if a hell death was involved. @l29ah can you clarify?

I'm not sure, i don't have an earlier save and don't pay attention to such things.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by mugmuggy** [comment]
@Alberth289346 last comment is correct here the patient was getting a walk to the inside of the room to use the hole from the west. I think that comes down to the function tryToUseHellDeathSpawnScenario in the DieAction process that has a similar check for distance already.
```lua
local hole_has_passable_side = humanoid.world:getPathDistance(grim_use_tile_x, grim_use_tile_y, humanoid.hole_use_tile_x, humanoid.hole_use_tile_y) == 4
```
This doesn't take into account that the patient would have to walk into a room to access the tile and that walk will result in the queuing of the actions for that room. The hole can't be spawned in a room so its only the patient that would appear to need the room check.

In #1201 it appears different as this seems to not have a grim stuck. But from a look at the code, would be due to transient nature of the entity_map with patients moving around the corridors also and the check for the room. It would appear to occur due to the World:isTileEmpty checks (already removed with #1288) taking place (checking room also) not occuring for the north option (#1285 was the related issue).
```lua
      if humanoid.world:isTileEmpty(humanoid.tile_x - 1, humanoid.tile_y, true) then
        humanoid:walkTo(humanoid.tile_x - 1, humanoid.tile_y)
      else
        humanoid:walkTo(humanoid.tile_x, humanoid.tile_y - 1)
      end
```

**Comment by TheCycoONE** [comment]
Ok, so the hell death one is as easy as checking that the room id is 0.

**Comment by TheCycoONE** [comment]
My understanding is that a patient can't die in a room? Did you notice this being violated?

**Comment by mugmuggy** [comment]
Thats not violated. I tested the change in a non-git repository so I haven't yet pushed it, but the patient die action starts, does grim death, the patient gets the incorrect walk that leads them to use door, they walk to the tile, but then start the rest of the normal room procedures, so walk back to the use position, then you hit the missing animation issue.
