### ISSUE TITLE
Adding english names to all languages in the menu

### ISSUE THREAD

**Issue by Grimdoc** [CorsixTH/CorsixTH#84]
As I mentioned in issue 1719 in the Google Project page:

Should we maybe add the english name for the languages to the menu so that everyone can easily identify the languages?
For example I can't tell chinese from korean, but it could sometimes be handy to know which is which.

Example of what the menu might would look like:
Castellano (Spanish)
Dansk (Danish)
Deutsch (German)
 Etc..

What do you think?

**Comment by TheCycoONE** [comment]
Wouldn't it be more appropriate for the bracketed or tool-tip language to be the player's current language instead of always English?

**Comment by bobcanthelpyou** [comment]
at the moment it looks like this:
![bildschirmfoto von 2015-07-23 00 58 53](https://cloud.githubusercontent.com/assets/4523264/8839526/96457b42-30d6-11e5-9c25-7ee3b7ffd1cd.png)

And i think it is a good idea to keep it, you could always switch to the languages you could read.

The idea of @TheCycoONE is also okay, to add the translation of the actually chosen language to the tool-tip or the brackets of the languages. 

But what is the befit of adding a translation to it? Would you choose a language if you can't read the origin name? 'Ah of cause it Korean let me chose that!'

**Comment by lewri** [comment]
PR 1362 needs linking to this issue (i.e. fixes xxxx)
