### ISSUE TITLE
Background image of start screen different positions with different screen resolutions

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#842]
The background image of the start screen is different centered or positioned on different screens resolutions. On the lowest resolutions the image is to much left and some black background is shown. I know that on different proportions (4:3, 16:9, ..) the detail should be different but i would also expect a similar detail on similar proportions.

640x480
![screenshot from 2015-07-29 01_10_57](https://cloud.githubusercontent.com/assets/4523264/8946398/2bde166a-3590-11e5-989d-ea6e6c56491f.png)
800x600
![screenshot from 2015-07-29 01_10_43](https://cloud.githubusercontent.com/assets/4523264/8946412/4c37d036-3590-11e5-85b1-4768c04fde23.png)
1024x768
![screenshot from 2015-07-29 01_10_24](https://cloud.githubusercontent.com/assets/4523264/8946448/9865a17c-3590-11e5-9dbb-231dcb7a22ec.png)
1280x720
![screenshot from 2015-07-29 01_10_02](https://cloud.githubusercontent.com/assets/4523264/8946654/583d4102-3592-11e5-938a-18655fe7a22e.png)

CorsixTH trunk ee23df1fb7ae5a0842854f3aea7a2cddb8e3a711 on Ubuntu Trusty 32bit with Lua 5.1

**Comment by TheCycoONE** [comment]
It looks like the distance to the top is constant, and it's centered horizontally.  You want it to be centered vertically and horizontally or are you seeing something different?

**Comment by TheCycoONE** [comment]
Nevermind, I was looking at the menu and you were talking about the background image.  Sorry for the bad reading comprehension :(
