### ISSUE TITLE
Wrong translation In CorsixTH/Lua/languages/french.lua Line 160

### ISSUE THREAD

**Issue by Masteroshi** [CorsixTH/CorsixTH#853]
Wrong translation In CorsixTH/Lua/languages/french.lua Line 160 :

adviser.research.drug_improved_1 = "la drogue %s a été améliorée par votre département de recherche."

SHOULD BE 

adviser.research.drug_improved_1 = "Le médicament %s a été amélioré par votre département de recherche."

**Comment by bobcanthelpyou** [comment]
@wolfy1339 could you have a look at the french translation and could you create a pull request for the french.lua file?

**Comment by Masteroshi** [comment]
@bobcanthelpyou I will try to (I'm new to Github).

**Comment by bobcanthelpyou** [comment]
If you want to do that, follow the HowTo under the headline 'CONTRIBUTING CODE:' of the file https://github.com/CorsixTH/CorsixTH/blob/master/CONTRIBUTING.txt

It is a really good point to start dealing with Github and pull requests

**Comment by Masteroshi** [comment]
Done!
