### ISSUE TITLE
Wrong adviser.warnings.pay_back_loan in German translation

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#862]
When running the game in German i see the following message which sounds like the English equivalent of `adviser.level_progress.financial_criteria_met`:

![bildschirmfoto von 2015-08-07 15 17 39](https://cloud.githubusercontent.com/assets/4523264/9151158/655670c4-3df9-11e5-8aa2-0f60b30e1276.png)

When running the game in English (and in some other languages i tested, too) i see the following message which is the `adviser.warnings.pay_back_loan` message

![bildschirmfoto von 2015-08-08 18 08 26](https://cloud.githubusercontent.com/assets/4523264/9151196/602cd218-3dfa-11e5-9ac6-8891ba48fb10.png)

What could be wrong here? Messages at different places in origin language files?

Should the `adviser.warnings.pay_back_loan` be overridden in the german.lua file to fix that or somewhere else?

Savegame where the message appear shortly after loading the savegame http://filebin.ca/2BRxAtTFSOIn/Autosave8.sav

**Comment by Alberth289346** [comment]
While discussing at IRC, @bobcanthelpyou compared original english strings with original german strings, and found that strings [28,32] and [28,33] are the same in the original german texts. After that, strings don't match between both files.

**Comment by bobcanthelpyou** [comment]
I compared the English and the German strings with the debug-strings-orig.txt file.

There is a mismatch after the string [28,32], that string is repeated in the German translation, but not in the English one. The strings [28,32] and [28,33] are the same in the German translation .

The English strings end at [28,63]
The German strings end at [28,64]

**Comment by bobcanthelpyou** [comment]
I would add the following code to the `function fixGermanStrings(lang_num)` in `Lua/languages/original_strings.lua`

```
  if #S[28][32] == #S[28][33] then
    for str = 33, 63, 1 do
      S[28][str] = S[28][str+1]
    end
  end
```

**Comment by bobcanthelpyou** [comment]
There are some more mismatches between the German translation and the English strings (after the strings [39,30], [44,172] and [57,37]). There are some mismatches in the French translation, too (after string [57,133]). The original_credits mismatches in all translations [43,1] (but that doesn't matter much, i guess)

Need to check the strings with the demo version of the game, too.

**Comment by bobcanthelpyou** [comment]
The language file of the demo version is not affected by the problem with the repeated string `[28,32]` / `[28,33]` in the German translation

Also all other mismatches i mentioned are handled already. The lines mismatches but there are blocks of strings which are separated by lines with punctuation marks, only.

The strings of the demo game are slightly different with the strings of the full game but i think these differences are handled by the `Lua/languages/original_strings.lua` file, already.
