### ISSUE TITLE
Patient walk through wall while building a operation theater

### ISSUE THREAD

**Issue by bobcanthelpyou** [CorsixTH/CorsixTH#865]
While building a operation theater, a patient walks through the wall and get stuck in a corner.

When finishing the operation theater the patient leave with the following error message:

![bildschirmfoto von 2015-08-09 22 36 06](https://cloud.githubusercontent.com/assets/4523264/9156843/376b5c84-3ee8-11e5-9a38-157ebe3299ba.png)

```
Empty action queue!
Last action: walk
stack traceback:
    ./Lua/entities/humanoid.lua:541: in function 'Humanoid_startAction'
    ./Lua/entities/humanoid.lua:667: in function 'finishAction'
    ./Lua/humanoid_actions/walk.lua:152: in function 'timer_function'
    ./Lua/entity.lua:218: in function 'tick'
    ./Lua/world.lua:1121: in function 'onTick'
    ./Lua/app.lua:878: in function <./Lua/app.lua:875>
    (tail call): ?
    ./Lua/app.lua:779: in function <./Lua/app.lua:774>
```

Savegame: http://filebin.ca/2BaGplTtY1d1/test08.sav

CorsixTH trunk 9576da101bb3e8682029708c9f92eaa667cfe4da / Lua 5.1 / Debian Jessie 64-bit

**Comment by mugmuggy** [comment]
Closing as fixed with #1425
