### ISSUE TITLE
0.5 rc1 Surgens won't operate. 

### ISSUE THREAD

**Issue by hulagutten2** [CorsixTH/CorsixTH#869]
One of the surgens (which I placed there manually), will not change clothes and start working.
Link to save game. It is based upon the same save game as issue #868: 
https://drive.google.com/file/d/0B_gMIT2wvyj2eDFRdVZOMjBZLXM/view?usp=sharing 

Also, in that same savegame, a patient is stuck in the scanner room. That level is a real challenge with these unexpected things. ;)

**Comment by TheCycoONE** [comment]
Is this a duplicate of #483 ?

**Comment by hulagutten2** [comment]
@TheCycoONE Yes, it seems to be a duplicate. Please close this issue if it is best, but it contains an additional save game.
