### ISSUE TITLE
Crash with track_fps enabled

### ISSUE THREAD

**Issue by Huppi** [CorsixTH/CorsixTH#877]
I can start the game and start to build but nothing is "moving". All People are freezed and the game-time doesn't ellapse. It's always Jan 1st...
![th_freezed](https://cloud.githubusercontent.com/assets/13886960/9383495/d861625a-4749-11e5-883e-e85bc3baabc7.png)

**Comment by wolfy1339** [comment]
Is your game on pause?

**Comment by Huppi** [comment]
Game Speed is set on 5

In Pause the screen would be in a different color

**Comment by Huppi** [comment]
![th_freezed](https://cloud.githubusercontent.com/assets/13886960/9383574/881e108a-474a-11e5-903a-b4458c3272f8.png)
I've set the language back to English to make another Screenshot with the Game-Speed menu. You can also see that all are in the same position as above...

**Comment by TheCycoONE** [comment]
Please upload a save game if possible, and attach the contents of gamelog.txt or the output of the console window. Also tell us what version you are playing, and on what operating system.

**Comment by Huppi** [comment]
Where can I put the savegame? I'm using 5.0 RC3 with Windows 10.

gamelog.txt Output:

Created game with savegame version 105.
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\dialogs\bottom_panel.lua:486: bad argument #1 to 'format' (number has no integer representation)
stack traceback:
	[C]: in function 'string.format'
	C:\Program Files\CorsixTH\Lua\dialogs\bottom_panel.lua:486: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\window.lua:1634: in field 'onTick'
	C:\Program Files\CorsixTH\Lua\ui.lua:708: in field 'onTick'
	C:\Program Files\CorsixTH\Lua\game_ui.lua:592: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:880: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

**Comment by wolfy1339** [comment]
You can put the savegame anywhere that you can share it publicly (ex: Google Drive, Dropbox, Onedrive, etc.)

**Comment by TheCycoONE** [comment]
Could you disable the FPS display in your config.txt and see if that solves the freeze? Assuming it does I don't need your save - I can see the problem.

**Comment by Huppi** [comment]
Savegame: https://dl.dropboxusercontent.com/u/7209172/Huppi-1.sav

I can only find the "track_fps" Option in the config.txt which is already set to "false":

-- If set to true, the FPS, Lua memory usage, and entity count will be shown
-- in the dynamic information bar. Note that setting this to true also turns
-- off the FPS limiter, causing much higher CPU utilisation, but resulting in
-- more useful FPS values, as they are not artificially capped.
-- 
track_fps = false

**Comment by Huppi** [comment]
Ok, don't know what it was, but it's working now *confused* ... ok, thanks for all, but I there is no more issue ;)

**Comment by TheCycoONE** [comment]
The crash message from your gamelog.txt is from code that's only accessed if track FPS is enabled, and there is a bug there. I will use this issue to track that problem.

**Comment by wolfy1339** [comment]
Closed by #878 (I beleive)

**Comment by TheCycoONE** [comment]
Yes, thanks @wolfy1339
