### ISSUE TITLE
Mac 0.50 RC3 Release Broken

### ISSUE THREAD

**Issue by admdly** [CorsixTH/CorsixTH#879]
The OS X release for 0.50 RC3 crashes on launch as the required libraries are missing, specifically LuaJIT. However, by the looks of it other required libraries are missing so fixing the LuaJIT dependency is most likely just going to bring up another issue for the next missing library. 

I have been meaning to make the required changes to get the latest version compiling with the required libraries included, but unfortunately I haven't had the time and can't commit to releases at this time. If nobody else steps up in the mean time I will most likely at least do a stable 0.50 release.

In the mean time, it's likely a good idea to pull the OS X release for 0.50 RC3 as it just doesn't work.

**Comment by TheCycoONE** [comment]
Thanks @admdly, I was afraid of that. Good to here you're still around.

Pinging @tobylane

**Comment by TheCycoONE** [comment]
I've pulled the OSX release until the issues with it can be dealt with.

It should be noted that for this release Lua 5.3 is preferred to LuaJIT. There are some crashes that affect LuaJIT and not Lua (see #327).

**Comment by tobylane** [comment]
I was expecting what I have done in my fork to include the dependancies but it's not. You're welcome to take over, but if you don't have the time for it and can point out how to do it I can try.

**Comment by TheCycoONE** [comment]
@admdly is this the same as #1035 

You didn't really provide any details.

**Comment by TheCycoONE** [comment]
Resolved for 0.62
