### ISSUE TITLE
Videos crash

### ISSUE THREAD

**Issue by halapli** [CorsixTH/CorsixTH#880]
Hi, sorry if there's a fix for this already but I didn't find anything. When starting the game it freezes on the intro movie. When I disabled it in the config I could get into the menu and play custom maps but when I try to play the campaign it freezes on the board game after a second. Tried with both Origin and GoG versions. Running the latest version on Win 7. Thanks.

**Comment by Alberth289346** [comment]
What version are you using?

**Comment by halapli** [comment]
0.50-rc3

**Comment by TheCycoONE** [comment]
What video card do you have? Is it Win7 64bit? Could you paste the console output for the feeze?

I haven't seen this in my windows tests.

**Comment by halapli** [comment]
ATI Radeon HD 2600 XT. Yes it's 64bit. 
![089b18bc90](https://cloud.githubusercontent.com/assets/13918727/9429451/c1188798-49d0-11e5-939f-1599c4962eae.jpg)

**Comment by TheCycoONE** [comment]
I don't have access to any comparable hardware to test with. Do you happen to have Visual Studio and the technical expertise to diagnose where the problem is?

If not I suppose a couple things are worth checking. First, do the videos work for you in CorsixTH 0.40 (The decoding is nearly identical, but the rendering is completely different), secondly, does the problem still happen in windowed mode (600x800), and finally does the problem still happen with OpenGL: Open the command line, navigate to the CorsixTH directory, type ```set SDL_RENDER_DRIVER=opengl``` and press enter, then ```CorsixTH.exe```. If you are still in windowed mode you should see it say opengl instead of direct3d in the window title.

**Comment by halapli** [comment]
Videos work in 0.40. Happens in windowed mode too but it kinda works with OpenGL. The videos play but they are choppy.

**Comment by TheCycoONE** [comment]
When you say the board game freezes "after a second", do you mean it plays several frames of the board game before stopping?

**Comment by halapli** [comment]
Yes and the music finishes then its quiet.

**Comment by MarkL1961** [comment]
Not played in a while, but I think with the board you have to click on it for it to open the level, but I guess you know this....

**Comment by TheCycoONE** [comment]
For the board game the music playback should be independent of the video (the video is actually silent for that one and we trigger a sound to start playing at the same time we start the video).

Anyway if I understand correctly, the token starts at the start position, gets a few frames in, but doesn't make it to the final position (on level 1 of the board game). It sounds like some sort of deadlock which means it would be really helpful to have the stack trace of all the threads. It would be easy to get that information if you were comfortable with Visual Studio and compiling CorsixTH.

If that's an option for you, you can read: https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile the dependencies are available precompiled for Visual Studio 2013 at https://github.com/CorsixTH/deps and we can provide further assistance on irc (#corsix-th on freenode), where I have the same nick.

I'll spend some time looking too, but without being able to reproduce the problem the chances of finding the problem are pretty slim for me.

**Comment by janejohn** [comment]
Same probleme here. After starting the game the intro freezes but the sound continues. 
Card ist ATI Mobility Radeon HD 5470, Windowd 7, 64 bit.

Is there any solution so far?

**Comment by TheCycoONE** [comment]
No solution so far. It's probably not a coincidence that the two of you are on very similar video cards (ATI cards using the drivers that covered r600 until southern islands).

We are still looking for someone with an affected video card that can trace down what exactly is failing.

**Comment by janejohn** [comment]
thanks for the quick answer :)

**Comment by halapli** [comment]
Totally forgot about this sorry. I'm using a different pc now so it's not an issue for me anymore.

**Comment by Oberalp** [comment]
Hi there,
I have exactly the same problem with an ATI FirePro M7820, running Windows 7 64bits. But for me it doesn't crash every time!
It seems it is less likely to crash with the resolutions 800x600, 1366x768, 1920x1080 and 1920x1200 (crashed sometimes though). The other resolutions usually crash. Seems to be the same on both windowed and full screen mode...

When I change the resolution, the console displays 4 times the line
"Problem creating overlay: Texture dimensions can't be 0"
Sometimes when it crashes, the console also displays the warning
"*Warning: data is not aligned! This can lead to a speedloss"
I don't know if it is actually related.

Hope this info can help...

**Comment by Lego3** [comment]
Can you try on the latest master? It's a long shot, but TheCycoONE has done some changes to video rendering.

**Comment by TheCycoONE** [comment]
It's not a long shot. With my changes our interactions with the GPU are more conventional so we're less likely to hit driver/hardware issues.

Is anyone able to retest with the latest master?

**Comment by halapli** [comment]
I'm not using that PC anymore so I can't, sorry.

**Comment by Oberalp** [comment]
I'm already using Release 0.50 (Aug. 30th) that I downloaded on Oct. 3rd.

**Comment by Alberth289346** [comment]
The change with discussed above was created after 0.50.

**Comment by Lego3** [comment]
Please try the following version: https://ci.appveyor.com/api/buildjobs/11glfp1yayhdipae/artifacts/CorsixTH/CorsixTH.zip

**Comment by suipaste** [comment]
I'm getting some very similar problems occurring. I seem to get the issue in all video sections like the opening video and the level progression video. I'm running Windows 7 64 bit with a ATI Radeon 5700 series GFX card.

The crashes don't happen 100% of the time but don't seem that hard to recreate. I'm a Java programmer by trade but I'd be interested in helping. I don't have eclipse for C++ set up but if you could give me some advise of what I'd be looking to do once I'm set up I'd be happy to give it a shot.

**Comment by TheCycoONE** [comment]
@suipaste we believe this issue is already fixed after the release of 0.50, are you testing with the latest master?

**Comment by suipaste** [comment]
Yeah it's v0.50 I saw your message yesterday but wasn't home until now to have a look at the installer to double checker the version number.

**Comment by emorrp1** [comment]
Came here to report a (related) issue in 0.50 on Debian having rendering issues for the videos (stuttering, initial blockiness) on Radeon HD 7560D. Rebuilt with the latest master (g7d886f3) and can confirm the videos play smoothly.

**Comment by TheCycoONE** [comment]
Thanks @emorrp1
