### ISSUE TITLE
Deprecated audio units

### ISSUE THREAD

**Issue by ntapiam** [CorsixTH/CorsixTH#881]
I use OS X and have recently installed 10.11 El Capitan's beta 5 (15A262e). Since this update, when starting CorsixTH 0.50rc2—which I built myself under OS X 10.10 Yosemite last month (I think)—I get the following warning in Terminal.App:

<img width="570" alt="captura de pantalla 2015-08-24 a las 7 26 07 p m" src="https://cloud.githubusercontent.com/assets/1558791/9454155/5f0d920c-4a96-11e5-8a00-97005a059266.png">

I don't know if this will be an issue in the future but this message started appearing since the update and I never saw it before. If you require any further information don't hesitate to ask.

Thanks for creating this amazing project.

**Comment by TheCycoONE** [comment]
We do not directly access the operating system's audio framework in CorsixTH, all of our audio is output through SDL2_Mixer.

**Comment by ntapiam** [comment]
Ok, thanks. So it's related to SDL2 then.

**Comment by TheCycoONE** [comment]
Possibly one of the libraries SDL2_mixer uses e.g. Timidity.

If you're building CorsixTH yourself and could step through the code to determine what is happening (what line is being executed) when that warning is issued) it would help for reporting the issue upstream.

**Comment by Lego3** [comment]
Any news here? Otherwise we'll close the issue.

**Comment by tobylane** [comment]
Upstream's PR on the matter: https://bugzilla.libsdl.org/show_bug.cgi?id=3127.

**Comment by TheCycoONE** [comment]
I've been leaving upstream issues open until they are resolved upstream. Hopefully people will see them before filing duplicates.

**Comment by ntapiam** [comment]
Resolved upstream
