### ISSUE TITLE
Coundown timer left/right click functionality.

### ISSUE THREAD

**Issue by joewestcott** [CorsixTH/CorsixTH#882]
After flicking through the [TH Manual](http://imgur.com/KdSVIhk) (the paragraph in question is starred) I found that the countdown timer used on Emergencies and Epidemics has some hidden left and right click functionality not currently implemented in CorsixTH.

#### Emergencies:
Right clicking the timer brings up an emergency patient's* information panel (The same panel as a standard left click on a patient) Subsequent right clicks cycle through each emergency patient.
Left clicking centres the view on this patient, the patient centred on is dependant on the last right click.

#### Epidemics:
Epidemics are a little bit different, as right click *does not cycle though* patients. Right clicking only brings up one patient needed a vaccination*, even though there could be many patients needed Vaccination present in the Hospital.
Left clicking centres the view on this patient.

### In both instances:
* The first left click does nothing. (until you right click)
* Clicking the timer plays sound ~~[TYPING.WAV or XRAY2.WAV](https://github.com/CorsixTH/CorsixTH/wiki/Sound-List)~~, I can't quite tell which.

~~*As far as I can tell, the first patient chosen is the one nearest you at the time.~~

EDIT: The sound heard is CAMCLICK.wav, this is verified in the title field of the [Sound List](https://github.com/CorsixTH/CorsixTH/wiki/Sound-List).

**Comment by sadger** [comment]
"Needing a vaccination" is it one marked for vaccination with the blob + spray can on their head or one with just a blob or maybe both?

**Comment by joewestcott** [comment]
~~*As far as I can tell, the first patient chosen is the one nearest you at the time.~~
Playing it though again, I'm uncertain on the order of cycle or which patient comes first.

**Comment by sadger** [comment]
Choosing any patient for the start of the cycle sounds reasonable - in our case the first in the table of emergency/epidemic patients. I can't see any measurement of which should be chosen first so any should do the trick to begin with.

**Comment by sadger** [comment]
Is the countdown timer a button? Does it depress when you click it? A video would be very useful if you can provide one :)

**Comment by joewestcott** [comment]
> Is the countdown timer a button?
Nope, the timer itself shows no visual difference. (Only the vaccination button above it does, for epidemics)

Here's a video showing the process during an Emergency.
(30mb) https://www.dropbox.com/s/59r4wv8tacnpl6w/timer_functionality.mp4

**Comment by sadger** [comment]
Thanks, this should help implement it pretty nicely.

**Comment by sadger** [comment]
Out of interest, what does right clicking do if you haven't left clicked first? Does it bring up the dialog or does it centre the patient with no dialog or nothing?

**Comment by joewestcott** [comment]
I'm not entirely sure what you're asking, swapping 'left' and 'right' makes more sense, did you mean that?
In which case the answer is *nothing*.

* Right click will always show the next patient's information window. Even if the open one is closed, it will reopen on the next patient.
* The first left click of the timer does nothing.
* After the first right click, the next left clicks will centre on the last patient shown with a right click.

**Comment by sadger** [comment]
Ok your first bullet point is what I meant, in your video you only right click after you have left clicked. I was wondering if it centred without bringing up the dialog but it seems it always brings one up to centre.

**Comment by sadger** [comment]
I think we are confusing right and left clicks which makes this conversation confusing.

To my understanding based on the video:

Left click - first click brings up the dialog and subsequent clicks centres on the patient
Right click - cycles to the next patient

Is this correct?

**Comment by joewestcott** [comment]
> in your video you only right click after you have left clicked.

The first click in my video is a right.

**Comment by sadger** [comment]
Oh I see. Right ok. So left does nothing until you have right clicked?

**Comment by joewestcott** [comment]
> Oh I see. Right ok. So left does nothing until you have right clicked?

Correct, yes :)

**Comment by sadger** [comment]
Right got it now, thank you for your explanation, you have been very helpful. Being slow today. I've got timer clicks working now so i'll try get this behaviour implemented.

**Comment by joewestcott** [comment]
Awesome. It's great that you've decided to implement this! I'm on IRC this afternoon (gmt) if you've got anymore questions. :)

**Comment by joewestcott** [comment]
Awesome! Just a few changes:
* The timer inside ring appears to have moved a bit off centre.
* The timer clicking functionality applies to the whole timer graphic, not just the inside ring.
* If I close a patients information window, I can no longer left click to centre.
* camclick.wav should play for each click.

**Comment by sadger** [comment]
I'm talking to you in IRC now of course but I have noted these changes and will take a look.

**Comment by sadger** [comment]
Have done the changes to gameplay - and added the sound. The button off centre and the button being on the whole graphic I will do probably tomorrow.

**Comment by sadger** [comment]
Done all these changes now, please can you test them when you get a chance.

**Comment by joewestcott** [comment]
In TH, right clicking during an epidemic timer will only show one patient, not cycle though like emergencies. I'm not sure if this is deliberate, or a TH bug. Other than that, it looks really good and functions perfectly - great work! :+1:

**Comment by sadger** [comment]
Well it makes a lot of sense to show one patient because in an epidemic you have to try and find and cure all the patients. Which patient does it show? I think it should be the first infected with the green icon (not cured) epidemic patient as you dont really want to cycle between the cured ones. Can you see if you can tell which it is?

**Comment by joewestcott** [comment]
> Which patient does it show?

I couldn't determine how the patient was chosen, at the time I played there were about 3 needed to be done.

**Comment by sadger** [comment]
Ok, I'll try something out and hopefully its a sensible solution to which one is chosen. We can always change it later

**Comment by sadger** [comment]
Right I have made it so in an
 * Emergency - right click cycles between all patients, left click centres on a patient
 * Epidemic - right click goes to the first infected patient who has not been vaccinated or cured - repeated clicking will not move to another patient until you have vaccinated the first one. Left click still centres on the chosen patient.

@joewestcott  I have updated my code can you test it for me? Mostly if the behaviour for epidemics is sensible to you, you can create infected patients in the cheat menu to start an epidemic. If it seems odd or restricted please let me know.
