### ISSUE TITLE
Can't get into game, mouse clicks not functioning properly in Win7 x64

### ISSUE THREAD

**Issue by morphine00** [CorsixTH/CorsixTH#886]
Hi, installed GOG Theme Hospital and CorsixTH 0.50

The game starts up fine, but I can't into the game proper as the mouse click processing looks a bit wonky.

If I click Campaign, then click on Start, the first mouse click will depress the button but nothing will happen. The second mouse click will not register at all. The third click will be interpreted as a drag action, and the menu will be dragged under the mouse despite me not pressing any buttons. The game will not be navigable from that point on, no matter what mouse buttons are pressed, you just keep dragging the window.

A similar behavior exists if I go to Settings instead.

Operating system: Windows 7 x64
Graphics card: Nvidia GTX 970

**Comment by TheCycoONE** [comment]
It sounds like mouse up isn't being registered. That's not something I've seen. Does this happen every time?

**Comment by morphine00** [comment]
Yep, every time.


------ Original Message ------

**Comment by TheCycoONE** [comment]
Is this a traditional mouse, or some other type of pointing device? Is there anything else unusual about your setup? Does the problem happen in both fullscreen and windowed mode? (you can edit config.txt in notepad, it's in %APPDATA%/CorsixTH)

Basically anything you can tell us that might help tracking it down, since it doesn't happen to us.

**Comment by TheCycoONE** [comment]
You should also post your gamelog.txt file or any console output from when this happens.

**Comment by morphine00** [comment]
I have two mice plugged in, and thinking that may had something to do 
with it, I unplugged one of them. (This dual-mouse setup has no issues 
with any apps or games.)

On the next startup, CorsixTH said it can't write to its config file, 
something that it's still doing unless I run it with Administrator 
privileges. I managed to play the game for a few hours now, albeit with 
some other unrelated bugs.

Plugged the second mouse back in, and tried running CorsixTH again. Now 
it works, and I can't fathom why.

As a possibly related note, I did have an issue with the mouseup handler 
after changing levels. Screen went black after the video, had to hit 
Esc, entered the level, then the mouseup handler wasn't being 
registered. Could not reproduce that, though.


------ Original Message ------

**Comment by lewri** [comment]
Behaviour is unusual but unfortunately we didn't get any debug info. @morphine00 have you encountered this with a new release if you've played at all recently? Otherwise might be safe to close.

**Comment by morphine00** [comment]
I haven't played TH in a while, so I don't know. Thanks for looking into this, best to close the bug. Thanks for CorsixTH.

**Comment by lewri** [comment]
Issue closed. Can be reopened in future if it's come across again.
