### ISSUE TITLE
Could not find Lua

### ISSUE THREAD

**Issue by chaosink** [CorsixTH/CorsixTH#895]
```
CMake Error at CMake/FindLua.cmake:70 (MESSAGE):
  Could not find Lua
Call Stack (most recent call first):
  CorsixTH/CMakeLists.txt:105 (FIND_PACKAGE)
```
I have already installed Lua.
```
➜  CorsixTH-0.50  lua -v
Lua 5.2.3  Copyright (C) 1994-2013 Lua.org, PUC-Rio
```

**Comment by Alberth289346** [comment]
Did you also install lua-dev (or lua-devel), the lua development package (which should have /usr/include/lua.h and some other files it needs to compile against the lua libraries) ?

**Comment by chaosink** [comment]
I have already installed `liblua5.2-0` and `liblua5.2-dev` using `apt-get`.

**Comment by TheCycoONE** [comment]
Should be fixed by #899 In the mean time you can work around this by manually specifying your LUA_INCLUDE_DIR and LUA_LIBRARY. e.g.``` cmake -DLUA_INCLUDE_DIR=/usr/include/lua5.2/ -DLUA_LIBRARY=/usr/bin/lua5.2/ .```

**Comment by chaosink** [comment]
Now `cmake` works, but `make` reports an error:
```
make[2]: *** No rule to make target `/usr/lib/lua5.2', needed by `CorsixTH/CorsixTH'.  Stop.
make[1]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TheCycoONE** [comment]
it sounds like your LUA_LIBRARY variable was wrong. It should be the exact path to liblua.so (or liblua5.2.so, or liblua.so.5.2, or whatever it is in your distirubtion) including the file name.

**Comment by chaosink** [comment]
I used the correct path:
```
cmake -DLUA_INCLUDE_DIR=/usr/include/lua5.2/ -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu .
```
And then:
```
➜  CorsixTH-0.50  make
Linking CXX executable CorsixTH
/usr/bin/ld: /usr/local/lib/libavformat.a(http.o): undefined reference to symbol 'inflateInit2_'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CorsixTH/CorsixTH] Error 1
make[1]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by TheCycoONE** [comment]
@chaosink I specifically said in my last comment to include the file name.

**Comment by chaosink** [comment]
Do you mean `cmake -DLUA_INCLUDE_DIR=/usr/include/lua5.2/ -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua5.2.so .`?

```
➜  CorsixTH-0.50  cmake -DLUA_INCLUDE_DIR=/usr/include/lua5.2/ -DLUA_LIBRARY=/usr/lib/x86_64-linux-gnu/liblua5.2.so .      
Note: SDL audio is enabled (default)
Note: FFMPEG video is enabled (default)
Note: FreeType2 is enabled (default)

Building CorsixTH
  SDL found
-- Found Lua library: /usr/lib/x86_64-linux-gnu/liblua5.2.so
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so  
  Lua found
  SDL_mixer found
-- CMAKE_MODULE_PATH=/home/lin/下载/CorsixTH-0.50/CMake
  FFmpeg found
  FreeType2 found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/lin/下载/CorsixTH-0.50
➜  CorsixTH-0.50  make
Linking CXX executable CorsixTH
/usr/bin/ld: /usr/local/lib/libavformat.a(http.o): undefined reference to symbol 'inflateInit2_'
//lib/x86_64-linux-gnu/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CorsixTH/CorsixTH] Error 1
make[1]: *** [CorsixTH/CMakeFiles/CorsixTH.dir/all] Error 2
make: *** [all] Error 2
➜  CorsixTH-0.50  
```

**Comment by TheCycoONE** [comment]
Yes that's what I meant. Your current issue is with ffmpeg, which appears to be failing to find a symbol in libz. This is out of scope for CorsixTH as we don't require ffmpeg to link against libz at all.

**Comment by chaosink** [comment]
It seems that I still can't play CorsixTH... :pensive:

Thanks anyway!

**Comment by TheCycoONE** [comment]
@chaosink you should be able to set -DWITH_MOVIES=off and not include ffmpeg in your build. If you care to join us on irc (freenode #corsix-th) that is a more appropriate forum to continue this discussion.

**Comment by chaosink** [comment]
With `-DWITH_MOVIES=off` the compilation succeeds !

And after installing `lua-filesystem` and `lua-lpeg`, it runs ! :smiley:
