### ISSUE TITLE
Why isn't there a binary release for mac os x?

### ISSUE THREAD

**Issue by moonfruit** [CorsixTH/CorsixTH#897]
As shown in the title, why isn't there a binary release for mac os x?

**Comment by tobylane** [comment]
It's planned, but we don't have people with the skills. We're close (#771), and the current best effort works if you personally install the dependancies (eg with homebrew). With that unideal requirement this will work https://transfer.sh/Z9hhi/cth-20150906-containers-d1bd734a6e-mac.zip

**Comment by TheCycoONE** [comment]
Non issue, there are actual issues blocking the OSX release e.g. #1035
