### ISSUE TITLE
"Research Screen unavailable" message missing in demo level

### ISSUE THREAD

**Issue by therealgreenpower** [CorsixTH/CorsixTH#90]
On CorsixTH trunk with demo files, the game doesn't recognize a 10x5 research department, even though it's fully equiped.

**Comment by tobylane** [comment]
A 10x5 research room in the demo level works (researcher sits at desk, takes/kills patients, new room learned, reputation affected).

**Comment by TheCycoONE** [comment]
@tobylane I don't think this issue was resolved. See @MarkL1961's first comment. The title is misleading.

**Comment by lewri** [comment]
I can confirm this is still happening on 0.64
