### ISSUE TITLE
Error finding main

### ISSUE THREAD

**Issue by JoshKeegan** [CorsixTH/CorsixTH#905]
Hi,
I've just followed the "Setting Up Windows Dev Software" guide and got through it with only the minor hiccough that I'd put a space in a directory and the cmake GUI wasn't a big fan of that.
Once I'd followed the guide though, there was an error when I went to compile:
```
error LNK2019: unresolved external symbol _main referenced in function ___tmainCRTStartup
```

I've worked around this by adding #undef main before the main function as it seems to be clashing with a main from elsewhere.
Just wondering if I've done something wrong to have needed this?
Cheers,
Josh

**Comment by TheCycoONE** [comment]
It seems so. Probably the easiest way to build on Windows is to copy the appveyor.yml script. Usually problems with main have to do with linking sdl2.

**Comment by JoshKeegan** [comment]
Thanks, I've followed the appveyor script & using the libs from CorsixTH/deps repo rather than following the "Setting Up Windows Dev Software" wiki page & no longer need to #undef main.

I came across another minor problem that I'll leave here for anyone else that has it:
Since I last ran cmake I'd installed VS2015. Cmake would no longer work out of the box for "Visual Studio 12 2013 Win64", giving the following errors:
```
No CMAKE_C_COMPILER could be found.
No CMAKE_CXX_COMPILER could be found.
```
I thought I'd give compiling with VS2015 a try, so ran cmake with "Visual Studio 14 2015 Win64" which worked fine.
The current version of SDL (2.0.3) caused a couple of issues when trying to compile the CorsixTH project:
```
unresolved external symbol __imp____iob_func
unresolved external symbol _imp_sprintf
```

These workarounds shouldn't be necessary for future versions of SDL (as they'd hopefully be compiled for the VS2015 toolset), but for now add somewhere in the src:
```
//Fix SDL for VS2015
FILE _iob[] = { *stdin, *stdout, *stderr };

extern "C" FILE * __cdecl __iob_func(void)
{
	return _iob;
}
```
(Credit to http://stackoverflow.com/a/32449318)

And then add legacy_stdio_definitions.lib as an additional linker dep (see https://connect.microsoft.com/VisualStudio/feedback/details/1134693/vs-2015-ctp-5-c-vsnwprintf-s-and-other-functions-are-not-exported-in-appcrt140-dll-breaking-linkage-of-static-libraries).

With those small changes, it will then build successfully under VS2015 targeting the latest toolset.

**Comment by TheCycoONE** [comment]
Yes, I ran into that myself. Currently all the deps are built against 2013 rather than 2015.

**Comment by Lego3** [comment]
Since the original issue is no more I'll close this.

**Comment by TheCycoONE** [comment]
There are VS2015 x64 deps in the deps repo as well, so the second issue isn't either.
