### ISSUE TITLE
Nightly/development builds?

### ISSUE THREAD

**Issue by fosils** [CorsixTH/CorsixTH#917]
I am a huge fan of this project, and I would like to contribute by testing the latest version and providing bug reports on them. Unfortunatelly, I cannot find any development or nightly builds of this project, so I seem to be stuck with version 0.50. Am I missing something? If not, would it be possible to download it from the automated testing system (is it called travis?)?

**Comment by MarkL1961** [comment]
The is a link in the wiki home page

**Comment by fosils** [comment]
Thank you! That got me to this page: http://www.armedpineapple.co.uk/cth/builds/ Which seems to contain fairly recent builds, but not based upon the very latest commit. Am I missing something?

**Comment by MarkL1961** [comment]
My understanding is they get updated when merged not when committed.
I used to download the latest build and then merge pull requests to test them

**Comment by Alberth289346** [comment]
Last merge that is available seems to be
````
commit de495c315ac27501d2bde17d6cc9693ae66eaa9b
Merge: bd344a1 9a88bb0
Author: Alberth289346 <alberth289346@gmail.com>
Date:   Tue Sep 29 17:38:50 2015 +0200

    Merge pull request #890 from TheCycoONE/new_travis
    
    Use travis containers and g++ 5 in TravisCI
````
Maybe the disk is full or so? the 43 entries there are around 740MB

**Comment by wolfy1339** [comment]
I know that Windows builds are stored on the AppVeyor servers, an included feature of AppVeyor

**Comment by TheCycoONE** [comment]
Yes, the build location moved recently. I did update the wiki, so if you found an old link let me know where it was please. You want to go to https://ci.appveyor.com/project/TheCycoONE/corsixth/history then click a build with just a number (the ones with number-stuff are pull requests), then click the artifact tab and there it is.

**Comment by Lego3** [comment]
I updated the page at https://github.com/CorsixTH/CorsixTH/wiki/Testing-Builds to more clearly state that the second build link no longer is updated.
