### ISSUE TITLE
Level 12: Machines cannot be repaired

### ISSUE THREAD

**Issue by Develop3r** [CorsixTH/CorsixTH#918]
Hi there,
up to now I am not sure whether this is wanted or not, but I strongly doubt it.

I accepted promotion from Level 11 where everything worked well, then went on to Level 12 and built up my hospital. Pretty late I noticed that I am unable to set any machine to be repaired by the handyman. Clicking on the "repair" button simply does nothing.

Only possible outcomes are:
- Machine blows after maxima for uses is reached
- Replace the machine with a new one (unfeasable with a fully working hospital with dozens of machines)
- Adjust the room back to blueprint, plant machine, counter is set to 0 (also unfeasable for lots of machines and time consuming)

So I though, what the heck, restart the level - I did this 3 or 4 times now, but it stays the same. I went back to Level 11 and waited for another promotion, but even then, problem persists.... 

Regards

**Comment by Alberth289346** [comment]
Could you add a savegame demonstrating the problem (through some file upload service, unfortunately, as github does not allow uploading binary files)

**Comment by Develop3r** [comment]
Sure thing, here you go:

http://www.mirrorcreator.com/files/1VNU1APQ/TH_Saves_Level12_Repair_Bug.rar_links

I also added the last Level11 Savegame although I doubt that it has anything to do with it.

Using the "Level12in201510drei0.5.sav" you will see that no1 is coming to repair and the machine will blow up. 

What I noticed is that the cardiogram also causes some graphical glitches when in use... like you can see it through the wall for example. This I experienced before but I never had any problems with it...

**Comment by MarkL1961** [comment]
How do you know that there is no handyman coming to repair?  Did you open the calls dispatcher menu or are you expecting to see the cog over the machine?

**Comment by Develop3r** [comment]
The latter, plus: simple observation.

**Comment by MarkL1961** [comment]
The repair calls are pending, but you have only two handymen!

**Comment by MarkL1961** [comment]
You have also told one of them to sweep rubbish only and the other to water plants only!

**Comment by Develop3r** [comment]
Hell you're right, that really solves it. Thanks mate!
