### ISSUE TITLE
free build mode still has costs

### ISSUE THREAD

**Issue by zzcmeiou** [CorsixTH/CorsixTH#924]
rooms still have cost in free build mode

windows 7 home premium 64 bit

![roomcost](https://cloud.githubusercontent.com/assets/15532166/10867589/1c84502a-80a5-11e5-9fe2-3bb7d056edae.jpg)

only rooms

staff, corridor and land cost 0

no error logs generated

**Comment by Alberth289346** [comment]
Thanks for the report, apparently nobody ever actually to play a free game.
Since rooms already failed, you may encounter other things now that are also not free (they could not have been tested at all). Please report them as well, so they can be fixed.

**Comment by MarkL1961** [comment]
@Alberth289346  It was working perfectly up until 0.40, it got broke in 0.50.

I have used it many times for testing new maps

**Comment by Alberth289346** [comment]
oh
Thanks for letting me know, that dramatically reduces the chance of running into other problems then.
