### ISSUE TITLE
Cast from void* to function pointer is invalid in c++

### ISSUE THREAD

**Issue by TheCycoONE** [CorsixTH/CorsixTH#929]
There is a cast from void* to void(*) void at https://github.com/CorsixTH/CorsixTH/blob/e8ef33ad1a0791cfacb9f7c976e0f58733da2a8e/CorsixTH/SrcUnshared/main.cpp#L116

Casting a void* to a function pointer is implementation dependent in c++. (See: http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#195) In particular it is not supported in MSVC 2013 when microsoft extensions are disabled (/Za)

I'm not sure if it's possible to implement this functionality another way, but if so it should be investigated.

**Comment by TheCycoONE** [comment]
From a brief glance, it seems like all this lua cleanup functionality can be removed, simply calling the two cleanup operations, Mix_CloseAudio, and SDL_Quit explicitly.

**Comment by Alberth289346** [comment]
Seems like a much simpler solution to me, perhaps it had its use in a previous version with all the different back-ends.
