### ISSUE TITLE
Crash/freeze after quite a while of playing.

### ISSUE THREAD

**Issue by Andruvan** [CorsixTH/CorsixTH#932]
CorsixTH 0.50
WIndows 7 x64
Level: Sacred Heart Hospital from the forum community mappack (although it has happened before with a stock map that I can't remember the name of)

This problem has appeared twice now, and I've managed to capture the save file this time.
While playing a long session I noticed that a doctor couldn't enter a room and would just stand outside it with the queue icon above his head. A janitor that wanted to go in also was standing outside with the same icon above his head (while hovering the mouse pointer over the room door). 
- Nothing was blocking the door and I tried rearranging the objects inside the room without any effect. 
- I then picked up the doctor and dropped him inside the room and that's when a symptom I hope you will see from the save file occurred: the doctor kept walking back and forth continuously in front of the door (trying to get out i assume)

After this the whole game pretty much bugged out completely, the game kept running and I could change game speed using the keyboard but not much else worked. 
Using the F-keys I was able to open and close the corresponding game dialogs but clicking on anything with the mouse did not produce any action. The main game toolbar at the bottom of the screen did not respond to any mouse clicks as well. I should also note that the menu options at the top of the screen displayed but clicking them did nothing. 

Link to save file and the gamelog.txt: https://drive.google.com/file/d/0B9xM0RvxY_MqUnhKT1E0OGVQTlE/view?usp=sharing

Kind regards
André C

**Comment by Alberth289346** [comment]
Dump of gamelog + first analysis
````
Created game with savegame version 105.
Savegame version is 105 (0.50), originally it was 105 (0.50)
Warning: Trying to remove nonexistant room build callback (function: 0000000013FC11F0) from humanoid (table: 0000000008B4E2A0).
Warning: Trying to remove nonexistant room remove callback (function: 0000000012A78600) from humanoid (table: 0000000008B4E2A0).

[lots more removed]

Warning: Trying to remove nonexistant room remove callback (function: 0000000017717C20) from humanoid (table: 0000000012CD8BF0).
Error in buttonup handler: 
F:\Spel\CorsixTH\Lua\map.lua:389: attempt to index a nil value (local 'thData')
stack traceback:
        F:\Spel\CorsixTH\Lua\map.lua:389: in method 'loadDebugText'
        F:\Spel\CorsixTH\Lua\dialogs\menu.lua:711: in field 'handler'
        F:\Spel\CorsixTH\Lua\dialogs\menu.lua:390: in method 'onMouseUp'
        F:\Spel\CorsixTH\Lua\window.lua:1429: in field 'onMouseUp'
        F:\Spel\CorsixTH\Lua\ui.lua:623: in function <F:\Spel\CorsixTH\Lua\ui.lua:610>
        (...tail calls...)
        F:\Spel\CorsixTH\Lua\app.lua:779: in function <F:\Spel\CorsixTH\Lua\app.lua:774>
Error in keydown handler: 
F:\Spel\CorsixTH\CorsixTH.lua:56: cannot open F:\Spel\CorsixTH\Lua\debugger.lua: No such file or directory
stack traceback:
        [C]: in function 'persist.dofile'
        F:\Spel\CorsixTH\CorsixTH.lua:56: in function 'dofile'
        F:\Spel\CorsixTH\Lua\run_debugger.lua:17: in function <F:\Spel\CorsixTH\Lua\run_debugger.lua:7>
        (...tail calls...)
        F:\Spel\CorsixTH\Lua\ui.lua:243: in field 'callback'
        F:\Spel\CorsixTH\Lua\ui.lua:528: in field 'onKeyDown'
        F:\Spel\CorsixTH\Lua\game_ui.lua:235: in function <F:\Spel\CorsixTH\Lua\game_ui.lua:234>
        (...tail calls...)
        F:\Spel\CorsixTH\Lua\app.lua:779: in function <F:\Spel\CorsixTH\Lua\app.lua:774>
````
This looks like you pressed ctrl+c, after enabling debugging, not sure where "debugger.lua" is supposed to come from, probably an external install.

**Comment by Alberth289346** [comment]
![double_use](https://cloud.githubusercontent.com/assets/3254232/11014256/0ef50f4c-852f-11e5-9b75-00bbd5fec627.png)

Door is not usable, janitor wants to water plant inside, doctor wants to leave.

**Comment by Alberth289346** [comment]
Savegame is already in bad state, we would need an earlier one to understand how the game gets in this state.

**Comment by TheCycoONE** [comment]
Closing is this was reported in an old version; there has been no response from the original poster, and there is nothing actionable here.
