### ISSUE TITLE
On FFmepg 2.8+ every animation cause crashes

### ISSUE THREAD

**Issue by NerosTie** [CorsixTH/CorsixTH#939]
My data files come from Origin (french) and on Windows everything is perfect.

But on Archlinux (https://aur.archlinux.org/packages/corsix-th) every animation cause crash with the error: 
`[1]    10302 segmentation fault (core dumped)  CorsixTH`

I have to delete or rename the folders `ANIMS` and `INTRO` for the game to work.

**Comment by TheCycoONE** [comment]
The problem happens with recent versions of ffmpeg (2.8 and higher) on all operating systems. When it first happened with 2.8.0 I assumed it was an ffmpeg bug that would be fixed shortly. It may  be an ffmpeg bug, or it may be something we're doing wrong that only now is causing problems.

Thank you for the reminder, the issue needs to be isolated and dealt with or reported upstream.

**Comment by TheCycoONE** [comment]
On further investigation this is our bug. sws_scale takes the source height parameter not the destination height parameter. I checked earlier versions of ffmpeg and this has always been the case, so I'm uncertain why the issue suddenly started causing problems in 2.8.

A PR will be coming soon. The AUR maintainer should apply the fix as a patch.

**Comment by NerosTie** [comment]
The package has been updated on AUR and it works! It was really fast, thank you!
