### ISSUE TITLE
Having a Patient window open while they leave the map crashes the game

### ISSUE THREAD

**Issue by subenji** [CorsixTH/CorsixTH#943]
Simple enough to reproduce: cure a patient, and leave their info window open while they leave the map.
Found on version 0.50 Win. No output to the console, no gamelog.txt file - even with debug on.

Stumbled across this bug while I was busy doing another task and had forgotten their window was open. Tested after realising what the likely cause was.

**Comment by Alberth289346** [comment]
Already fixed, but not in the 0.50 release
