### ISSUE TITLE
Can't save on level three.

### ISSUE THREAD

**Issue by TonyTilley** [CorsixTH/CorsixTH#944]
When I attempt to save on level three, the game itself freezes while the command prompt looking thing just spams "Unhandled argument to th_getfenv" for a while before saying "nil  <no name>" and "<Localized String> Current value:Error while saving game: C:\Users\finta\Desktop\CorsixTH\Lua\persistance.lua:242 Lua functions must be given a persistable name in order to be persisted (attempt to persist C:\Users\finta\Desktop\CorsixTH\Lua\diseases\bloaty_head.lua:33)

When it attempts to auto save it says this
"Error while autosaving game: C:\Users\finta\Desktop\CorsixTH\Lua\persistance.lua:242 Lua must be given a unique persistable name in order to be persisted (attempt to persist C:\Users\finta\Desktop\CorsixTH\Lua\diseases\bloaty_head.lua:33)

**Comment by TheCycoONE** [comment]
Which version and operating system is this?

**Comment by TheCycoONE** [comment]
No reponse
