### ISSUE TITLE
CMakeLists.txt specifies OS X Deployment target that causes configuration failures on newer installations of OS X

### ISSUE THREAD

**Issue by msmollin** [CorsixTH/CorsixTH#959]
Since there doesn't seem to be a ton of movement on the OS X binary front, I went about trying to build from source following the directions here - https://github.com/CorsixTH/CorsixTH/wiki/Compiling-on-OS-X

My machine is a 2013 Retina Macbook Pro Running OS X 10.10.5 with Xcode 7.2 installed.

The major failure comes from having specified an OS X Deployment Target of 10.9 when that SDK doesn't exist on my machine, and thus generating a warning and an error. 

```
CMake Warning at /Applications/CMake.app/Contents/share/cmake-3.4/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk".
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.4/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:3 (project)


CMake Error at /Applications/CMake.app/Contents/share/cmake-3.4/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.4/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:3 (project)


CMake Error: Internal CMake error, TryCompile configure of cmake failed
```

These can be resolved in a few ways, but it's not obvious to me why the deployment target was specified in the first place as CMake claims (unsure how true it is) it will figure out what the deployment target should be based on the system doing the building. Any thoughts on ways forward here?

**Comment by tobylane** [comment]
I'm not sure why it was set, but I bumped it up because it was the only way I found to build C++ as C14 without also building the ObjC as C14. It works for both of us to not specify a target so it seems redundant.

I don't get that matching SDK warning, it just falls back to the only one avaliable - 10.11.

**Comment by msmollin** [comment]
@tobylane CMake seems to indicate according to it docs (https://cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html) that not specifying that variable will cause CMake to compute it. If I comment out both of those lines:

```
IF(APPLE)
  #SET(CMAKE_OSX_DEPLOYMENT_TARGET 10.9)
  #SET(CMAKE_OSX_ARCHITECTURES x86_64)
ENDIF()
```

Then it seems to do just that. However I'm unsure how to test the success of this given the other issues I'm running into?

**Comment by tobylane** [comment]
That works for me, 10.10.5 and Xcode 7.0. It works for Travis on Xocde 6 https://travis-ci.org/tobylane/CorsixTH/jobs/99822377 (expand line 2571 for details).
