### ISSUE TITLE
FindLua.cmake doesn't find Lua on newer versions of OS X + Homebrew

### ISSUE THREAD

**Issue by msmollin** [CorsixTH/CorsixTH#960]
I'm attempting to build CorsixTH from source (see #959) and if I pick a path that manages to resolve the configuration failure I noted in #959 then I get configure failure that it's unable to find Lua. It seems the FindLua.cmake script is lacking some of the paths that homebrew is using when installing Lua5.3 (which requires explicitly specifying that homebrew version as it seems the main Lua brew recipe no longer installs 5.3).

I fixed this but am unsure if I should submit a PR for the issue as it seems there is some work going on (at least as of september) to get OS X builds building on travis. Thoughts?

**Comment by tobylane** [comment]
The findlua.cmake doesn't look in the directory (/usr/local/) that homebrew uses. I need to specify the location like cmake . -G Xcode  -DLUA_PROGRAM_PATH=/usr/local/bin/lua5.3 -DLUA_INCLUDE_DIR=/usr/local/include/lua5.3/ -DLUA_LIBRARY=/usr/local/lib/liblua.5.3.dylib

Please do make new PRs. We're finding various issues with OSX and that Travis PR doesn't have a solution to the specific problem of including dependancies yet.

**Comment by msmollin** [comment]
@tobylane Please see https://github.com/CorsixTH/CorsixTH/pull/962 for the fix.

**Comment by wolfy1339** [comment]
Should've been closed by #962.
