### ISSUE TITLE
Training Doctors

### ISSUE THREAD

**Issue by ssleahcar** [CorsixTH/CorsixTH#968]
I've noticed that when training doctors they don't learn or start learning any skills from their teachers, they just become consultants.

**Comment by MarkL1961** [comment]
Skills improve quicker in the classroom, but they also improve slowly whilst working.
Could it be this is what you have seen?

**Comment by bobcanthelpyou** [comment]
If a doctor is already well trained, sometimes the time to become a consultant is shorter then learning a new skill from another consultant.

**Comment by ssleahcar** [comment]
It happens with every doctor I try to train in the class. I've tried training about 6, but they all only become consultants.

**Comment by MarkL1961** [comment]
If you want to train a researcher etc you are better off starting with a junior so there is time for him to learn the skills and become a consultant.  If you put in a mid skill Dr you will find there is not the time for him to learn the skill and they become consultants quickly
The hardest to do is train a consultant with all three skills, but it is doable with a really low skilled junior.
You can also increase the speed they learn by adding a skeleton and some bookcases.
