### ISSUE TITLE
Game error and glitch: doctor sprite stuck between doors

### ISSUE THREAD

**Issue by tmarplatt** [CorsixTH/CorsixTH#969]
There was a sudden error and then I noticed a doctor inside a room being behind a door and in front of another (which should not be there), and the sprite is frozen.
[Screenshot here](https://i.imgur.com/uCY0YB4.jpg)

[gamelog.txt](https://github.com/CorsixTH/CorsixTH/files/109006/gamelog.txt)
[stuckdoctor.zip](https://github.com/CorsixTH/CorsixTH/files/109009/stuckdoctor.zip)

**Comment by MarkL1961** [comment]
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\map.lua:50: bad argument #1 to 'floor' (number expected, got nil)
stack traceback:
	[C]: in function 'math.floor'
	C:\Program Files\CorsixTH\Lua\map.lua:50: in method 'getRoomId'
	C:\Program Files\CorsixTH\Lua\world.lua:2275: in method 'getRoom'
	C:\Program Files\CorsixTH\Lua\room.lua:75: in method 'getEntranceXY'
	C:\Program Files\CorsixTH\Lua\room.lua:696: in upvalue 'tryMovePatient'
	C:\Program Files\CorsixTH\Lua\room.lua:758: in method 'tryToFindNearbyPatients'
	C:\Program Files\CorsixTH\Lua\room.lua:479: in function <C:\Program Files\CorsixTH\Lua\room.lua:474>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\room.lua:371: in method 'onHumanoidEnter'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:356: in field 'on_next_tile_set'
	C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:150: in function <C:\Program Files\CorsixTH\Lua\humanoid_actions\walk.lua:137>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:218: in field 'tick'
	C:\Program Files\CorsixTH\Lua\entities\staff.lua:149: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1121: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:878: in function <C:\Program Files\CorsixTH\Lua\app.lua:875>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:779: in function <C:\Program Files\CorsixTH\Lua\app.lua:774>

**Comment by Alberth289346** [comment]
What version is this exactly? There was a fix in 'tryToFindNearbyPatients', version 0.50 (release).
If your version is earlier (ie a 0.50 RC), this bug is likely already fixed.

**Comment by TheCycoONE** [comment]
@Alberth289346 it's 0.50 final. The version indicator in each release candidate included -rc#.

**Comment by Alberth289346** [comment]
save game is after the problem occurred and thus not useful for reproducing the issue, do you have a previous savegame?

**Comment by tmarplatt** [comment]
Sadly I don't have one, I'm sorry :/ There's one from that same level but saved a few hours later.

**Comment by mugmuggy** [comment]
More recent issue #1602 indicates the same error, so I ended up taking a look back at this one as we have a save. Found that World.rooms, room 15 and 16 refer to the same room.

One of which is _built_ and the other not. The one that is not _built_ results in the the door.tile_x/y being nil and thus the lookup fails.

**Comment by mugmuggy** [comment]
Actually fairly simple by the looks to replicate, start building room, go to object phase and cancel the way back out. abortRoom doesn't get called, as you haven't paid for the room yet.

https://github.com/CorsixTH/CorsixTH/blob/3de736a9d92b5e6411678fad7eac4e21a035e9fe/CorsixTH/Lua/dialogs/edit_room.lua#L161-L164

From what I can gather should be replicated in cancel.
https://github.com/CorsixTH/CorsixTH/blob/3de736a9d92b5e6411678fad7eac4e21a035e9fe/CorsixTH/Lua/dialogs/edit_room.lua#L188-L190
