### ISSUE TITLE
Bank screen numbers suddenly show up in floating point

### ISSUE THREAD

**Issue by tmarplatt** [CorsixTH/CorsixTH#974]
At some point in the game, the bank loan and hospital value numbers changed to floating point. I couldn't tell when or how.

https://www.dropbox.com/s/5l8n0fu5z4p5uuf/fp.sav?dl=0

**Comment by TheCycoONE** [comment]
@tmarplatt do you have any suspicion as to how this might have happened? Did you save the game and load it between when you knew it was good and when it wasn't? Are you able to reproduce?

**Comment by Alberth289346** [comment]
Fixed by #1004
