### ISSUE TITLE
Stuck on loading screen on 2 OSes

### ISSUE THREAD

**Issue by agolsby** [CorsixTH/CorsixTH#982]
Both the Android (Play Store) and Linux (Manjaro Linux, built from AUR) versions get stuck when using the TH CD's HOSP directory to open the game. Everything is fine until that loading screen with the CD graphic in the middle that has a picture of a doctor, nurse, and administrator on a black background. Nothing ever happens after that, even if I click, and push every button imaginable, and wait up to 15 minutes. 

Reproduction: Using android or an arch-derived linux, attempt to start the latest build of the game while pointing to a HOSP directory pulled from the theme hospital CD.

**Comment by TheCycoONE** [comment]
By latest build do you mean the latest git copy of master or 0.50.

It's worth noting that the Android version is a sister project not directly managed by us; you can find their project here: http://www.armedpineapple.co.uk/projects/corsixth-for-android/

Is there anything in your gamelog.txt, or if you run from the terminal does anything show up in your terminal? The game works for us on Arch Linux; and the last time I worked with https://aur.archlinux.org/packages/corsix-th/ that was working as well.

**Comment by agolsby** [comment]
Ah ok I'll handle the android issue separately then.
No gamelog.txt gets generated. When I run the game from the terminal, all I see is this:
---------------------------------------------------------------

Welcome to CorsixTH 0.50!

---------------------------------------------------------------

This window will display useful information if an error occurs.

---------------------------------------------------------------

At that point the game is frozen, and I have to force-kill it to close the window. It's running CPU1 at 100% but not doing anything on CPU0.

**Comment by TheCycoONE** [comment]
There still isn't much to go on here. Could you compile with debugging symbols and reduce optimizations to e.g. -O1, then run the program with gdb and post the back trace at the point that it is stuck.

**Comment by agolsby** [comment]
Ok, here's the stack trace from gdb. 
[http://pastebin.com/60BhtYN3](url)

Also, the arch wiki suggested running strace -eopen, so in case that's useful to you, here it is. It seems to indicate what file is being processed when the crash occurs.
http://pastebin.com/1WMmWqZe

**Comment by TheCycoONE** [comment]
Sadly the gdb output isn't very helpful. We would need the ```backtrace``` on each thread, and we would need the game compiled with ```-g -O1```

That said, we think there may be an issue with your CD. To rule that out could you run md5sum against DATA/LANG-0.DAT, DATA/SOUND-0.DAT, and INTRO/INTRO.SM4

I would also be curious if the result is any different if you copied the files off the CD into your home folder (the files themselves, don't trip the iso), and change the config to point there. It's been quite some time since I tested with my physical cd and I'm not sure about others, so there may be an issue with our iso support.

Finally please paste your config file. For clarity in github surround it with ```.

**Comment by agolsby** [comment]
Found the problem -- the CD was scratched and apparently it had corrupted files. I tried again pointing to the HOSP directory taken from an ISO file from a different source, and it works flawlessly. Marking this closed. Thanks for your help tracking the problem down!
