### ISSUE TITLE
Hang while loading

### ISSUE THREAD

**Issue by shazoo1** [CorsixTH/CorsixTH#984]
The game hangs while loading (the disc picture).

OS: Windows 7
Version: 0.50

**Comment by TheCycoONE** [comment]
If you are using a CD, verify that you can copy all the files to your hard drive. If you are using a pirated or "abandonware" version of theme hospital, it is not supported and we do not endorse it's use, buy a copy from Origin or GOG or download the demo.

**Comment by shazoo1** [comment]
Yep, it was caused by pirated version. Thank you!
