### ISSUE TITLE
[Meta] Attachments from migrated Google code issues unaccessible

### ISSUE THREAD

**Issue by wolfy1339** [CorsixTH/CorsixTH#987]
Hey guys!
It seems that the _'moved'_ flag has been set on Google Code but a lot of open issues that were migrated still point to attachments wich are not accesible anymore since that flag is set.

A solution would be to download the attachments to an alternate server, and edit all the issues to point to the new links. It would take a bit of work but can be done.

**Comment by TheCycoONE** [comment]
Would have to be @Lego3 since I didn't have any access back then. Was there any particular attachment you thought might be valuable? I would think most of that stuff would be too old to be useful.

**Comment by wolfy1339** [comment]
I wasn't thinking of anything in particular, just in general

**Comment by Lego3** [comment]
I haven't done anything recently. It looks like the whole Google Code Archive is being shut down very soon.
https://code.google.com/archive/
https://code.google.com/archive/about

**Comment by Alberth289346** [comment]
We consider all google.com data as lost now? I have never been able to pull anything from the archive.
Can we close this issue?

**Comment by wolfy1339** [comment]
I guess so
