### ISSUE TITLE
walk.lua:281: assertion failed!

### ISSUE THREAD

**Issue by MarkL1961** [CorsixTH/CorsixTH#99]
Odd error, if you look at the image it says she is queuing for inflation, but has sleeping illness.

Error in timer handler: 
...xTH-epidemics\CorsixTH\Lua\humanoid_actions\walk.lua:281: assertion failed!
stack traceback:
    [C]: in function 'assert'
    ...xTH-epidemics\CorsixTH\Lua\humanoid_actions\walk.lua:281: in function <...xTH-epidemics\CorsixTH\Lua\humanoid_actions\walk.lua:209>
    (tail call): ?
    ...xTH-epidemics\CorsixTH\Lua\humanoid_actions\walk.lua:187: in function 'timer_function'
    ...\corsixth\CorsixTH-epidemics\CorsixTH\Lua\entity.lua:178: in function 'tick'
    ...p\corsixth\CorsixTH-epidemics\CorsixTH\Lua\world.lua:1039: in function 'onTick'
    ...top\corsixth\CorsixTH-epidemics\CorsixTH\Lua\app.lua:839: in function <...top\corsixth\CorsixTH-epidemics\CorsixTH\Lua\app.lua:836>
    (tail call): ?
    ...top\corsixth\CorsixTH-epidemics\CorsixTH\Lua\app.lua:740: in function <...top\corsixth\CorsixTH-epidemics\CorsixTH\Lua\app.lua:735>
![a](https://f.cloud.github.com/assets/4965487/1727899/40171f5a-62a6-11e3-9be3-d3bffdb2bd55.png)

**Comment by TheCycoONE** [comment]
For reference before the back trace becomes too dated to follow, the assert that failed was ```assert(action.reserve_on_resume == door)```, the function was ```navigateDoor```

**Comment by mugmuggy** [comment]
Was fixed with #1452
