### ISSUE TITLE
Cleanup/remove exploded rooms

### ISSUE THREAD

**Issue by scorchsoft** [CorsixTH/CorsixTH#991]
What is it you would like in the game?
The ability to delete broken rooms. Ideally this should be a non-default game setting.

What version of the product are you using? On what operating system?
Windows 10, latest production release of CorsixTH installed ontop of the GOG version.

**Comment by Alberth289346** [comment]
To be sure we speak about the same thing, "broken room" is what you get after a machine blows up, eg due to an earth quake? The common terminology in that case is "exploded room". Or do you mean something else?

Anyway, I think there should be a severe penalty for this, any suggestions?

**Comment by scorchsoft** [comment]
Hi Alberth,

Yeah that's right, an exploded room.

A penalty is a good idea, maybe you can have a handyman repair the whole room and it take 100% of their time plus cost the original rooms building fee again. Assuming that can even be coded to work that way as the typical process if for a handyman to repair equipment and not whole rooms.

Another option would be to immediately delete the broken room but have the cost implication as described above. 

The game has some metrics around hygiene right? Maybe whilst the room is being repaired the hygiene level drops for a period. I mean, in theory demolishing a room is a dirty task right?

Another option is that you can delete the room but all rooms of that type will also be deleted and you will have to re-research the room. Though maybe that is a bit too harsh.

Andrew

**Comment by Alberth289346** [comment]
Thanks for the confirmation and suggestions.
The topic of undoing exploded rooms tends to pop up every now and then, but we don't have an issue for it, it seems. This one looks like a good start :)

Unless you work on it yourself, don't expect any quick solution. On the other hand, who knows... :)

**Comment by voodoo070** [comment]
I think the original games used the exploded rooms as a mechanic to limit players' time
And to make them use the full number of rooms in the hospital instead of just sticking to 1 corner

Once a room explodes you cannot use the space anymore, but the levels are designed in such a way that you'll always have space if the game wants you to have the time
you can extend time by taking care of your machines well

just my 2 cents, it shouldnt be default anyway

**Comment by TheCycoONE** [comment]
The idea is controversial, I tend to agree with @voodoo070, but I've seen it come up often enough that it probably warrants an option (down the road).

**Comment by scorchsoft** [comment]
Yeah it definitely shouldn't be a default. It is just a nice to have extra setting for those who would like to use it. Part of the Corsix project is about staying true to the original game, but part of it is also about extension and improvement around player feedback (which is why I'd like to see it in if at all possible).

Thanks again guys!

**Comment by MarkL1961** [comment]
Could it be an option in free play?
I agree with @voodoo070 that it is a mechanic of the game / all part of the challenge.
If it gets easy you are less likely to enjoy, but as part of free play it could be seen as the training ground.  There would need to be some sort of penalty though, perhaps time penalty that you have to wait a year before you can edit it and replace the machine and clean up the tiles.

**Comment by maverique** [comment]
This would be a very welcome decision IMO. Make it optional. Best of both worlds. You don't want it? You don't have to play with it. You want it? Have it! I'm all for playing with more of the gameplay decisions on my end of things.

**Comment by lewri** [comment]
I believe something to add would be the placement of fire extinguishers seems rather useless in the game, rather more a 'vision' thing.
I would rather propose the fire extinguishers could do something to prevent rooms exploding, e.g. if there is a doctor/nurse in the room at the time and the room is near explosion the fire extinguisher could be used to put out the 'smoking' the machine causes.

However, I do also endorse the option to rebuild/repair the room at a penalty/long repair time as an optional component.

**Comment by AVeryFatElf** [comment]
Hey guys, probably the wrong section but as i *think* there might be a dev following this, I didn't realise about the blown up rooms not being removeable and after clicking "Edit Room" it caused an error signified by a window in-game which eventually after about 20 seconds caused the game to crash.

**Comment by TheCycoONE** [comment]
@AVeryFatElf if you can reproduce please open a new issue and fill in all the information from the template.

**Comment by AVeryFatElf** [comment]
@TheCycoONE Will do! New to the forum but after work if I get a chance to I'll do just what you've said. Thanks and enjoy your weekend!

**Comment by overlordchaos** [comment]
i agree to have a non-default option to remove the exploded room. this also happens on small hospitals not just big ones. plus is stupid. a hospital would not leave a exploded room shut down forever. it could damage the structure over time as well (collapse the next or previous floor on real hospitals)
put a non-default option where you can remove the room, (as if you where deleting it) but put 50% of the build cost + loss of 30 rep points.
