### ISSUE TITLE
missing dependency on Linux compile options

### ISSUE THREAD

**Issue by LiamDawe** [CorsixTH/CorsixTH#998]
I installed all the packages it required from: https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile  for Ubuntu and I also needed "doxygen", could someone update it?

It also needs updating in general as I needed to install some older deps for compiling on Ubuntu 16.04.

**Comment by TheCycoONE** [comment]
You could update the wiki :)

**Comment by LiamDawe** [comment]
Okay, gave it a shot https://github.com/CorsixTH/CorsixTH/wiki/How-To-Compile

**Comment by TheCycoONE** [comment]
@LiamDawe doxygen shouldn't be required to compile unless you want to make docs. What was the error you got when you tried to compile without it?

**Comment by LiamDawe** [comment]
Is there a log I can show you that stores each time I tried?

**Comment by Alberth289346** [comment]
````
cmake . 
````

output will work, please use 4 backticks above and below the log, so it gets formatted as fixed width teletype font

**Comment by LiamDawe** [comment]
Okay, not sure what's going on, tried with new release and it's fine without it.

**Comment by Alberth289346** [comment]
For reference, this is how it looks, and I can see people confusing it for an error :)

![2016-05-12-182806_576x97_scrot](https://cloud.githubusercontent.com/assets/3254232/15222504/63727332-1870-11e6-9a80-2cebf55868e9.png)
